confluentinc/ksql

docs/quickstart/README.md, ksql-core/src/main/java/io/confluent/ksql/QueryEngine.java, ksql-core/src/main/java/io/confluent/ksql/ddl/commands/AbstractCreateStreamCommand.java, ksql-core/src/main/java/io/confluent/ksql/physical/GenericRow.java, ksql-core/src/main/java/io/confluent/ksql/util/KsqlConfig.java, ksql-core/src/main/java/io/confluent/ksql/util/StringUtil.java
I found some misspelled words in documents or source files.
It's simple, but I hope it's meaningful. :0
=> Feature fix misspelled words

checkstyle/suppressions.xml, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java, ksql-rest-app/src/main/resources/log4j.properties
Fix to prevent the priorCommandReplay from hanging
#303  #320
=> 0.1.x bug fix command queue replay hang

docs/examples.md
=> KSQL-378: content-based routing

ksql-metastore/src/main/java/io/confluent/ksql/metastore/KsqlTable.java, ksql-metastore/src/main/java/io/confluent/ksql/metastore/KsqlTopic.java, ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetastoreUtil.java
some minor tidy ups to classes in metastore pacakge
=> MINOR: remove dead code. make field and method access more restricted

ksql-cli/pom.xml, ksql-common/pom.xml, ksql-engine/pom.xml, ksql-metastore/pom.xml, ksql-parser/pom.xml, ksql-serde/pom.xml, pom.xml
We refactored the code and created more fine grained packages. This PR cleans up the pom files.
=> Pom cleanup after refactor

ksql-cli/src/main/java/io/confluent/ksql/cli/StandaloneExecutor.java, ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java, ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClientImpl.java, ksql-engine/src/test/java/io/confluent/ksql/IntegrationTestHarness.java, ksql-engine/src/test/java/io/confluent/ksql/integtests/json/JsonFormatTest.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
This is a temporary change until we have Kafka 0.11.0.1 available.
=> Reverting adminclient singleton temporarily.

ksql-cli/pom.xml, ksql-cli/src/main/java/io/confluent/ksql/cli/StandaloneExecutor.java, ksql-clickstream-demo/pom.xml, ksql-common/pom.xml, ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java, ksql-engine/pom.xml, ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java, ksql-examples/pom.xml, ksql-metastore/pom.xml, ksql-parser/pom.xml, ksql-rest-app/pom.xml, ksql-serde/pom.xml, ksql-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedDeserializer.java, pom.xml
=> Revert "Ksql 388 fix 400 build issues"

ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java
=> fix findbugs in json deserializer

ksql-examples/src/main/java/io/confluent/ksql/datagen/AvroConsumer.java, ksql-examples/src/main/java/io/confluent/ksql/datagen/JsonConsumer.java, ksql-examples/src/main/java/io/confluent/ksql/datagen/SessionManager.java
=> fix findbugs warnings in examples

ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/KudafAggregator.java, ksql-engine/src/main/java/io/confluent/ksql/structured/SqlPredicate.java, ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java, ksql-engine/src/main/java/io/confluent/ksql/util/Version.java
fix various findbugs warnings in ksql-engine #412
=> findbugs warnings in ksql-engine

findbugs/findbugs-exclude.xml, ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java, ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/SqlFormatterQueryRewrite.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AliasedRelation.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ExpressionTreeRewriter.java, ksql-parser/src/main/java/io/confluent/ksql/util/DataSourceExtractor.java, pom.xml
fix warnings in parser and add suppressions for generated code #412
=> findbugs warnings in ksql-parser

ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KafkaTopicsList.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStatusFuture.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriter.java
=> fix findbugs warnings in ksql-rest

findbugs/findbugs-exclude.xml
=> findbugs exclusions

ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java, ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java, ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java, ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DDLCommandFactory.java, ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/SetPropertyCommand.java, ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java, ksql-engine/src/test/java/io/confluent/ksql/util/FakeKafkaTopicClient.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateAsSelect.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStream.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStreamAsSelect.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTable.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTableAsSelect.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DDLStatement.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropStream.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropTable.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropTopic.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/RegisterTopic.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/SetProperty.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
Clean up code in `StatementExecutor`, `QueryEngine` etc.
=> add DDLStatement interface, extract command factory, tidy up, test etc

ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java, ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java, ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/AbstractCreateStreamCommand.java, ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DDLCommandExec.java, ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
Correctness check for DROP statements. Sanity check for DDLs before writing to the command topic.
=> Ksql 294 drop source correctly

docs/syntax-reference.md
https://confluentinc.atlassian.net/browse/KSQL-351
=> KSQL-351 - Doc error for ksql-server-start

Jenkinsfile
Changed the slack channel for jenkins build notifications to ksql-eng.
=> Change jenkins slack channel

pom.xml
+ Remove obsolete comment (I think we always need to specify a plugin repo here...)
=> Add snapshots repo for Confluent dependencies

ksql-cli/src/test/java/io/confluent/ksql/TestRunner.java
The CLI tests occasionally fail because the test assertions are too brittle: they expect output like `Stream Created And Running` to be written to the console immediately after the statement is submitted. 
This is mostly, but not always true. It could be that the server is slow, or sometimes we get responses like `Queing statement`, etc. In these cases, the tests will spuriously fail.
The fix is to wait a little while for the expected output, and also allow for extra statements in the output from the console. This is more flexible and will help keep the test more stable over time.
=> Fix the sporadically failing CLITests

docs/README.md
- TODO: once approved, add to https://github.com/confluentinc/ksql/pull/504
=> KSQL-484 - Add version compatibility table to the docs

docs/quickstart/README.md, docs/quickstart/docker-compose.yml, ksql-clickstream-demo/docker-clickstream.md
This patch also updates the yaml file to refer to the right versions of the docker images and jar files.
The most noteworthy change is the update to the quickstart where one of the derived streams is in the Avro format.
=> Docs updates for 0.3 release

docs/examples.md, docs/syntax-reference.md, ksql-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java, ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockKafkaTopicClient.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
This PR fixes issue with case sensitivity of inferred field names in avro tables.
=> Schema inference for tables

docs/syntax-reference.md
Correction: Changed `REPLICATIONS` to `REPLICAS`.
=> Updated the docs.

pom.xml
=> Fix compilation issue group id '113584762' is too big in assemly-plugin

ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java, ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/KudafInitializer.java, ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToTimestamp.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
I noticed that there's style check plugin configured, however, looks like it's not enforced. Am I wondering it turned of by temporary or some configuration issue?
=> Fix code style issues

ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
Added more tests for SchemaUtil class.
=> Tests for commons package.

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/BrokerCompatibilityCheck.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/BrokerCompatibilityCheckTest.java
Broker Compatibility test needs at least one topic to check compatibility. If none exist then create a topic with a single partition. #612
=> create topic if none exist during broker compat test #612

ksql-cli/src/main/java/io/confluent/ksql/Ksql.java, ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java, ksql-cli/src/main/java/io/confluent/ksql/cli/LocalCli.java, ksql-cli/src/main/java/io/confluent/ksql/cli/RemoteCli.java, ksql-cli/src/main/java/io/confluent/ksql/cli/StandaloneExecutor.java, ksql-cli/src/main/java/io/confluent/ksql/cli/commands/Standalone.java, ksql-cli/src/test/java/io/confluent/ksql/CliTest.java, ksql-cli/src/test/java/io/confluent/ksql/TestTerminal.java, ksql-cli/src/test/java/io/confluent/ksql/cli/RemoteCliSpecificCommandTest.java, ksql-cli/src/test/java/io/confluent/ksql/cli/RemoteCliTest.java, ksql-cli/src/test/java/io/confluent/ksql/cli/StandaloneExecutorTest.java, ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java, ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java, ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java, ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
=> Tests for cli module plus further tests for refactoring.

ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java
Added propertiesFile argument to specify connection settings
=> Allow passing a properties file to the quickstart examples

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/RootDocument.java
The RootDocument was incorrectly redirecting to "localhost:8080" it should be using the base url as in config.
=> [bugfix] fix url in root document

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
When creating the command topic set the retention to Long.MAX_VALUE so we don't lose data after 7 days. 
#479
=> create command topic with retention set to Long.MAX_VALUE

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriterFormatTest.java
Update mock expectation to getById
=> Fix the TopicStreamWriterFormatTest

ksql-engine/src/test/java/io/confluent/ksql/util/GenericRowValueTypeEnforcerTest.java
Fix for #792
First commit moves the test and gets it recompiling.
Second applies code style rules.
Third is a quick clean-up / refactor.
=> Move stranded test

ksql-cli/src/main/java/io/confluent/ksql/cli/RemoteCli.java, ksql-cli/src/test/java/io/confluent/ksql/cli/RemoteCliSpecificCommandTest.java
=> fix remote cli help to print server help correctly indented

docs/quickstart/index.rst
General update of the page to bring it inline with the code (and the .md version of the doc).
To make the steps hang together better I've also added an additional step to create an unfiltered join, and use this to build the pageviews_regions later. Which makes more sense than making a 'view count by region and gender' table from a filtered stream that only contains one gender.
Resolves #809
=> #809 - update quick start docs

.gitignore, ksql-rest-app/pom.xml, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ZipUtil.java
extract the experimental UI so that it can be loaded from a WAR file.
Instructions:
1. download https://s3.amazonaws.com/ksql-experimental-ui/ksql-experimental-ui-0.1.war
1. copy the war into ksql/ui folder
1. run ksql-server-start
https://confluentinc.atlassian.net/browse/KSQL-706
https://confluentinc.atlassian.net/browse/KSQL-674
=> extract ksql experimental ui

ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java, ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
This reverts commit 765cb43f1a8d81f5343abe035e0eda1d8ccdd0a7.
=> Revert "Fix some issues with comparison op codegen (#751)"

docs/concepts.md
=> Drop UI from docs

ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctAggFunctionFactory.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctKudaf.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/DoubleTopkDistinctKudafTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/IntTopkDistinctKudafTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/LongTopkDistinctKudafTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/StringTopkDistinctKudafTest.java, ksql-engine/src/test/resources/query-validation-tests.json
`TopKDistinct` throws `ArrayStoreException` when they type is anything other than `Double`
Fixes #911
=> Fix array store exception in TopKDistinct

docs/installation/config-ksql.rst
=> Minor doc format fixes

docs/installation/config-ksql.rst
https://confluentinc.atlassian.net/browse/DOCS-143
=> DOCS-143 - KSQL poison-pill

docs/faq.rst, docs/includes/ksql-includes.rst, docs/syntax-reference.rst
https://confluentinc.atlassian.net/browse/KSQL-718
=> KSQL-718 - Add CSV description and fix tables

docs/installation/index.rst, docs/installation/server-config/index.rst
Per https://confluentinc.atlassian.net/wiki/spaces/Engineering/pages/212140663/KSQL+Documentation+structure+v2
=> Create Server configuration section

bin/ksql-server-start, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
=> add KSQL_INSTALL_DIR env variable and use that when extracting the ui

docs/installation/architecture.rst, docs/installation/cli-config.rst, docs/installation/common-scenarios.rst, docs/installation/index.rst, docs/installation/installing.rst, docs/installation/server-config/avro-schema.rst, docs/installation/server-config/ccloud-ksql.rst, docs/installation/server-config/index.rst, docs/installation/server-config/security.rst, docs/operations.rst
Skeletal outline of complete KSQL TOC. This PR purposely does not contain other content changes. 
Internal staging server http://staging-docs.confluent.io.s3-website-us-west-2.amazonaws.com/PR/771/4.1.0/ksql/docs/index.html
=> KSQL Proposed TOC

docs/README.md, docs/requirements.txt
Add local docs build instructions.
@ewencp does this look right - i copied from another project?
=> Add local docs build instructions

docs/installation/index.rst, docs/installation/server-config/ccloud-ksql.rst, docs/installation/server-config/index.rst
https://confluentinc.atlassian.net/browse/DOCS-351
Staging server for PR is here:
http://staging-docs.confluent.io.s3-website-us-west-2.amazonaws.com/PR/766/4.1.0/ksql/docs/installation/server-config/ccloud-ksql.html
=> DOCS-351 - KSQL in CCloud

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
=> don't throw IllegalArgumentException if ui war not downloaded

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
=> Don't close std out when printing welcome message

docs/syntax-reference.rst
=> KSQL-808 - Document RUN SCRIPT command

docs/tutorials/examples.rst
Missing feedback from https://github.com/confluentinc/ksql/pull/1010
=> Follow-on DOCS-357

docs/installation/server-config/security.rst
I've picked up some of the final tweaking of the security docs from @joel-hamill.
=> Security Docs tweaks

docs/installation/index.rst
Moved in this open PR: https://github.com/confluentinc/docs/pull/703
=> Fix moved /includes path

docs/syntax-reference.rst
Correct, (I hope!), the meaning of the `WITH (TIMESTAMP='x') ` clause for CTAS and CSAS statements.
=> Correct WITH TIMESTAMP docs.

docs/includes/ksql-includes.rst, docs/installation/installing.rst, docs/operations.rst
Update docs to set LOGDIR when running CLI
Get rid of TBD Capacity Planning / Scaling section until its ready
=> Set log dir when running CLI

bin/ksql-run-class
=> Drop `UserParNewGC` flag as its implicit and causes an error in Java 10.

ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java, ksql-engine/src/test/java/io/confluent/ksql/util/FakeKafkaTopicClient.java
The updates from the previous merge was not applied to the following two classes. This PR fixes it.
=> Tests fixes.

docs/includes/ksql-includes.rst, docs/installation/architecture.rst, docs/installation/installing.rst, docs/installation/server-config/index.rst
Also fixed some bad links and cleaned up some usage of technical terms.
=> Documentation: Updates to the configuration property descriptions

DEVELOPMENT.md, README.md, ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
=> Add some dev / local build instructions.

docs/installation/cli-config.rst, docs/installation/server-config/ccloud-ksql.rst, docs/installation/server-config/config-reference.rst, docs/installation/server-config/index.rst, docs/syntax-reference.rst
https://github.com/confluentinc/ksql/issues/818#issuecomment-373307121
=> DOCS-352 - Add info for kafka.core.streams

ksql-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java, ksql-engine/src/main/java/io/confluent/ksql/util/SerDeUtil.java, ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
=> update error messages when failing to parse an avro schema

docs/includes/ksql-includes.rst, docs/installation/installing.rst, docs/tutorials/basics-local.rst
- corresponding fix in /docs https://github.com/confluentinc/docs/pull/830
=> Add CLI log clarification

docs/faq.rst, docs/includes/ksql-includes.rst
https://github.com/confluentinc/ksql/issues/1028#issuecomment-381510492
=> Clarify AVRO

PULL_REQUEST_TEMPLATE.md
With this change, new pull requests will have the following text by default. 
=> Add a Pull request template

docs/installation/common-scenarios.rst, docs/installation/index.rst
=> Delete empty content

docs/syntax-reference.rst
=> Fix link to include

docs/tutorials/basics-docker.rst, docs/tutorials/docker-compose.yml
Updated the docker quickstart instructions for the upcoming preview release.
Ran the quickstart
=> Update docker quickstart for 5.0.0-beta1

ksql-clickstream-demo/Dockerfile
=> Fix clickstream 5.0.0 beta

ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java, ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
Minor changes to improve the error message when trying to drop stream/table that is in use.
=> Improved error message for Stream/Table and Query relation correctness.

docs/index.rst
https://confluentinc.atlassian.net/browse/DOCS-419
Add links to main KSQL landing page. 
=> DOCS-419 - KSQL doc should link to syntax reference etc

docs/installation/server-config/config-reference.rst
https://confluentinc.atlassian.net/browse/KSQL-843
=> KSQL-843 - Docs: listeners vs. ksql.listeners

docs/quickstart.rst
Fix repeated instance of "Confluent Platform"
=> Fix double-instance of CP

docs/tutorials/basics-docker.rst
=> Change GIT URL to HTTPS

docs/capacity-planning.rst, docs/installation/server-config/config-reference.rst
Fixes grammar and formatting issues. Adds hyperlinks to other docs.
=> Edit of Capacity Planning

docs/index.rst
Fixes left-hand TOC from this:
To this:
=> KSQL-945 - Fix KSQL left-hand nav

pom.xml
No behavior change, just inherit jackson.version from the parent common pom, which provides one location for us to update the dependency platform-wide.
NA
=> Rely on jackson.version from common parent pom

docs/installation/installing.rst, docs/installation/server-config/security.rst, docs/installation/upgrading.rst, docs/operations.rst
We can make this even better, but this should be a good starting point to improve the status quo.
=> Clarify how to install KSQL

docs/installation/installing.rst, docs/installation/server-config/index.rst, docs/syntax-reference.rst
Follow-on to https://github.com/confluentinc/ksql/pull/1330 
=> Follow-on updates for KSQL_OPTS

ksql-engine/src/test/resources/query-validation-tests/extract-json-field.json
Added a test around extracting data from a JSON array.
=> Minor: Add test around extract JSON array field.

ksql-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java
Because we don't ensure that branches are up to date with master before a merge, we get failures only after we merge. The latest is because #1356 pushed the method length beyond the limit.
This patch fixes it.
`mvn package` no longer fails.
=> Fix checkstyle failures

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java
Improve the message for delete topic. Now using the actual kafka topic name instead of the internal topic name.
=> Using the kafka topic name in delete topic message.

Jenkinsfile
This completes the job from  #1371 
Let's wait for the PR builder to complete this time.
=> Drop cp-ksql-server from jenkinsfile as well

README.md
=> Update with May 2018 preview release information

docs/includes/ksql-includes.rst, docs/tutorials/docker-compose.yml
=> Fix 5.0 beta30 docs

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
Use non-deprecated constructor for RecordMetadata in test.
=> MINOR: Remove use of deprecated method removed in AK

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java, ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java, ksql-engine/src/test/resources/query-validation-tests/concat.json
Fix for regression #1396, with added test cases.
Fixes #1396 
Replaces: #1398 (Rebased against 5.0.x branch)
=> #1396 Fix regression issue with string concat using '+' operator.

ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java
Fixed the comment length issue that was breaking the build.
=> Minor style change in comment.

docs/tutorials/generate-custom-test-data.rst, docs/tutorials/index.rst
Shows how to use `ksql-datagen` with a custom schema.
=> DOCS-415: New topic on KSQL custom test data

docs/installation/server-config/security.rst, ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java, ksql-engine/src/test/java/io/confluent/ksql/testutils/EmbeddedSingleNodeKafkaCluster.java
Updated the security documentation to take advance of the improvements introduced in AK 2.0 via KIP-277, (finer grained topic create ACLs) and KIP-290, (ACLs on prefixed resource patterns). 
Updated the security integration test proves the config works.
=> Simplified Security

docs/installation/server-config/security.rst
Having reviewed my recently merged doc changes, I've noticed a couple of rendering issues. See:
http://staging-docs.confluent.io.s3-website-us-west-2.amazonaws.com/5.0.0/ksql/docs/installation/server-config/security.html
None.
=> Fix some doc formatting issues.

ksql-examples/src/main/resources/clickstream_schema.avro
=> Use a string for formatted time field in clickstream schema

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SimpleFunctionInfo.java
sort the udf list/show into alphabetical order.
=> sort udf names

ksql-engine/pom.xml, ksql-examples/pom.xml, pom.xml
We use multiple versions of the avro random generator right now. Let's standardize on one.
PR builder gives a green build.
=> Standardize on a single version for the avro-random-genator

ksql-common/pom.xml, ksql-engine/pom.xml, ksql-metastore/pom.xml, ksql-parser/pom.xml, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java, ksql-serde/pom.xml, ksql-udf/pom.xml, pom.xml
and remove unused scala plugin
=> Fix test not run due to incorrect imports

docs/syntax-reference.rst
- Adds documentation about how to specify struct schemas for DDL statements
- Adds documentation for the operators that KSQL supports, including struct
dereference
=> Add documentation for structs

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/RootDocument.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/RootDocumentTest.java
Now that the UI is part of C3, drop references to the KSQL experimental UI. 
Project builds. Server starts, CLI can connect and do basic stuff.
=> Drop all references to the KSQL UI

README.md
=> Updated the read me for June preview.

ksql-serde/src/main/java/io/confluent/ksql/serde/avro/KsqlAvroTopicSerDe.java, ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlGenericRowAvroSerializerTest.java
Add avro serializer unit tests that validate that all the different
KSQL types can be serialized
=> Add more unit tests for avro serializer

ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java, ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java, ksql-engine/src/test/resources/query-validation-tests/project-filter.json
=> Fix the bug for null check in comparison expression code gen,

ksql-package/src/assembly/package.xml
Recreating #1577 since the PR builder job was magically not created for that PR.
see #1577
=> Add example avro schemas to the ksql packaging build

docs/installation/server-config/config-reference.rst, docs/syntax-reference.rst
Headings won't render correctly if they don't have the right length of underlining - whack!
Doc change only.
=> Fix headings in docs.

docs/installation/installing.rst, docs/installation/server-config/index.rst, docs/installation/server-config/security.rst
https://confluentinc.atlassian.net/browse/DOCS-416
Add note that start/stop command syntax assumes ZIP/TAR installation.
- related https://github.com/confluentinc/docs/pull/1043
=> DOCS-416 - Make installation method explicit

ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java, ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java, ksql-engine/src/test/resources/query-validation-tests/project-filter.json
This PR adds multi dimensional array support.
Fixes #1600 
Unit and integration tests were added.
=> Added support for multi dimensional array.

docs/changelog.rst, docs/index.rst
Add a changelog for 5.0 to CP ksql docs
make html
=> Add a changelog for 5.0 to CP ksql docs

ksql-clickstream-demo/Dockerfile
This fixes the 5.0.0 build. The previous tarball seems to have moved or been deleted.
PR Builder should pass.
=> Update DockerFile for clickstream demo to point to the final 5.0.0 release

docs/udf.rst
Improve the documentation a little around UDFs handling of primitive vs boxed types and nulls.
Docs only change
=> Better docs around UDF handling of nulls

docs/udf.rst
Cherry pick #1632 into 5.0.x branch.
=> Cherry pick "better UDF null handling docs" into 5.0

CONTRIBUTING.md
Add some details to our contributing docs page to cover code style and static code analysis.
Docs only change.
=> Document code style and static checks.

docs/capacity-planning.rst
… doc.
The section title was `Internal Topics` which was ambiguous since it includes both `Output Topics` and `Internal Topics`. 
=> Update the section title for generated topics.

ksql-clickstream-demo/README.md
Fix the link to the clickstream demo
=> Fix the link to the clickstream demo

docs/syntax-reference.rst
Update syntax reference to include the new join syntax.
None. Docs only.
=> Add updated join syntax to the syntax reference

checkstyle/checkstyle.properties, ksql-cli/src/test/java/io/confluent/ksql/CliTest.java, ksql-common/src/main/java/io/confluent/ksql/query/QueryId.java, ksql-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java, ksql-engine/src/main/java/io/confluent/ksql/function/UdfClassLoader.java, ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/ProjectNode.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/min/IntegerMinKudafTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/sum/IntegerSumKudafTest.java, ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java, ksql-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java, ksql-engine/src/test/java/io/confluent/ksql/planner/PlanSourceExtractorVisitorTest.java, ksql-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java, ksql-engine/src/test/resources/Multiply.java, ksql-metastore/src/test/java/io/confluent/ksql/metastore/MetastoreTest.java, ksql-parser/src/main/java/io/confluent/ksql/parser/DefaultTraversalVisitor.java, ksql-parser/src/main/java/io/confluent/ksql/parser/KsqlParserErrorStrategy.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DefaultTraversalVisitor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/TopicDescription.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/utils/TestUtils.java, ksql-serde/src/main/java/io/confluent/ksql/serde/KsqlTopicSerDe.java, ksql-udf/src/main/java/io/confluent/ksql/function/udf/UdfDescription.java, ksql-udf/src/main/java/io/confluent/ksql/function/udf/UdfParameter.java
Turn on checkstyle rule to enforce import order.
(Plus fix up some errors).
=> Turn on checkstyle rule to enforce import order

docs/syntax-reference.rst
=> Updated the syntax ref. to include interval/sample.

ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java, ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionCheckerAgent.java
Update to match changes in BaseMetricsReporter
Tested that build works
=> Update KsqlVersionChecker to match changes to BaseMetricsReporter

docs/operations.rst
Fixes [Document error and workarounds for replicated Avro topics with no SR subjects](https://confluentinc.atlassian.net/browse/KSQL-1119).
=> KSQL-1119: Add solution for replicated topic schema deserialization error

docs/syntax-reference.rst
This replace #1727 with the correct target.
=> Minor docs fix.

ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java, ksql-engine/src/test/java/io/confluent/ksql/QueryEngineTest.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java, ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStore.java, ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java, ksql-metastore/src/test/java/io/confluent/ksql/metastore/MetastoreTest.java
This PR fixes #1029 by improving the error message.
Unit tests.
=> Ksql 1029 improve csas/ctas existing stream error message

docs/index.rst, docs/tutorials/basics-docker.rst, docs/tutorials/basics-local.rst, docs/tutorials/examples.rst, docs/tutorials/index.rst
I found a sensible home for some of the videos and embedded those; the rest I listed in the Tutorials and Examples index topic.
=> DOCS-441: Embed Level Up Your KSQL videos

ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/FilterNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/OutputNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/PlanNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/ProjectNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java, ksql-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java, ksql-engine/src/test/java/io/confluent/ksql/planner/plan/OutputNodeTest.java, ksql-engine/src/test/java/io/confluent/ksql/planner/plan/ProjectNodeTest.java
This will make sure that the logical plan nodes have correct data source type.
This fixes #1637 
Unit tests were added.
=> Include data source type in the logical plan

docs/faq.rst
Add details on how to set retention for KSQL output topics.
=> DOCS-546: Add section about setting retention.ms

README.md, docs/installation/installing.rst, docs/installation/server-config/index.rst, docs/tutorials/basics-docker.rst, docs/tutorials/docker-compose.yml
Some of our docs referred to wrong docker image versions, or to configs which no longer exist.
Docs only change
=> Fix out of date documentation

docs/includes/ksql-includes.rst
Adds comment to include that is used in confluentinc/docs.
=> Optimize include for CP quickstart

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
Fix build due to https://github.com/confluentinc/ksql/pull/1764
build passes
=> Fix permissions on ksql rest configs

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
I don't find the use of these two constants in the code.
Also, the second had a typo.
mvn clean package
=> Remove ksqlConstants not used

docs/syntax-reference.rst
Add docs on how to handle columns with reserved words.
=> Add docs on how to use reserved words in KSQL.

.github/CODEOWNERS
Previous change doesn't seem to have added Jim to docs PRs.
=> Ensure Jim is added to docs PRs

docs/syntax-reference.rst
=> Currently we don't support AS for aliasing stream/table.

docs/installation/index.rst
=> DOCS-630 - Add CCloud link to KSQL installing nav

docs/tutorials/basics-docker.rst
@JimGalasyn this is to fix currently broken docs. I've targeted 5.0.0-post, is that correct? Do I need to do anything to get this onto master too?
=> KSQL-1532: Fix ECR docker image references

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
=> Disable the cli integration test

docs/includes/ksql-includes.rst, docs/tutorials/basics-docker.rst
* Fix docker KSQL tutorial. 
* Amended some sample output and minor instructions etc on the way for accuracy. 
I did actually test it this time :-D
Built the docs and ran the docker tutorial through from start to finish.
=> Fix docker references, and clarify instructions

ksql-engine/src/main/java/io/confluent/ksql/util/json/JsonPathTokenizer.java, ksql-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java
Fix checkstyle violation due to use of Unicode char.
unit test added to ensure output not changed
=> Minor: Fix checkstyle violation due to use of Unicode char.

ksql-cli/pom.xml, ksql-cli/src/test/java/io/confluent/ksql/CliTest.java, ksql-engine/pom.xml, ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java, ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java, ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java, ksql-engine/src/test/java/io/confluent/ksql/test/util/IntegrationTestUtils.java, ksql-engine/src/test/java/io/confluent/ksql/util/KafkaTopicClientImplIntegrationTest.java, ksql-engine/src/test/java/io/confluent/ksql/util/TopicConsumer.java, ksql-engine/src/test/java/io/confluent/ksql/util/TopicProducer.java, ksql-metastore/pom.xml, ksql-rest-app/pom.xml, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/test/util/TestKsqlRestApp.java, ksql-test-util/pom.xml, ksql-test-util/src/main/java/io/confluent/ksql/test/util/AssertEventually.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/ZooKeeperEmbedded.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/secure/ClientTrustStore.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/secure/Credentials.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/secure/KeyStoreUtil.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/secure/SecureKafkaHelper.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/secure/ServerKeyStore.java, ksql-tools/pom.xml, pom.xml
- Split out some test utilities into separate module.
- Expose ksql-rest-app test-jar
Needed for some cloud work.
Only test code effected
=> Expose some KSQL test types

ksql-common/src/main/java/io/confluent/ksql/util/Pair.java, ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java, ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGenProducer.java, ksql-examples/src/main/java/io/confluent/ksql/datagen/ProducerFactory.java, ksql-examples/src/main/java/io/confluent/ksql/datagen/RowGenerator.java, ksql-examples/src/main/java/io/confluent/ksql/datagen/SchemaUtil.java, ksql-examples/src/main/java/io/confluent/ksql/datagen/SessionManager.java, ksql-examples/src/test/java/io/confluent/ksql/datagen/DataGenTest.java, ksql-examples/src/test/java/io/confluent/ksql/datagen/RowGeneratorTest.java, ksql-examples/src/test/java/io/confluent/ksql/datagen/SessionManagerTest.java
Fix up checkstyle issues in datagen and speed up tests.
Manual running of datagen with several configs.
=> Checkstyle: Fix up issues in datagen

docs/includes/ksql-docker-includes.rst, docs/tutorials/basics-docker.rst, docs/tutorials/clickstream-docker.rst
Update Docker prerequisites to 8 GB and add command for discovering the current Docker memory allocation.
=> KSQL-1572: Update Docker prerequisites

docs/syntax-reference.rst
Updating the doc to prevent unintended consequences when using key hint for stream declaration.
=> Updated the docs for better stream key hint.

docs/includes/ksql-includes.rst
=> DOCS-803: Change heading markup to H2

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/test/util/TestKsqlRestApp.java
Improve the `TestKsqlRestApp` to make it easier to use.
Added some methods to help others to make requests against the app:
- method to get rest endpoint
- method to get ws endpoint
- method to get a http client.
None.
=> Improve the `TestKsqlRestApp` to make it easier to use.

ksql-common/src/main/java/io/confluent/ksql/ddl/DdlConfig.java
I don't find the use of these two constants in the code.
mvn clean package
=> Remove DDLConfig not used

ksql-clickstream-demo/demo/clickstream-schema.sql
I screwed up the merge as part of the pint conflict resolution, and left some diff stuff in there. Only wrong in `master`; `5.0.0-post` and `5.0.x` are fine.
=> Fix dodgy merge

ksql-common/pom.xml, pom.xml
Coordinating change with https://github.com/confluentinc/common/pull/163 to move over to spotbugs.
Build passes with no new spotbugs failures (when run against the modified upstream)
=> Switch to spotbugs annotations

docs/installation/server-config/security.rst
Minor: correct continuation char in docs for config file based config.
Consistent with http://kafka.apache.org/documentation.html#security_jaas_broker
Doc only change.
=> Minor: correct continuation char in docs for config file based config.

docs/capacity-planning.rst
This is a minor documentation change to the capacity planning doc. It should help avoid any confusion about the impact of KSQL on Kafka.
Did not test locally, minor change.
=> DOCS-796 KSQL Capacity doc has a confusing sentence

docs/developer-guide/index.rst, docs/index.rst
This is the first of six PRs for refactoring existing dev content in a new KSQL Developer Guide directory. This approach mirrors how we handle dev content in the [Streams docs](https://docs.confluent.io/current/streams/developer-guide/index.html). In one of the the next PRs, existing developer topics will move into this directory, and site redirects will be added to ensure that we don't break any external links.
Future developer-focused content will be authored in this directory.
=> KSQL-1656: Create new developer-guide directory

ksql-cli/src/test/java/io/confluent/ksql/cli/BasicAuthFunctionalTest.java, ksql-cli/src/test/java/io/confluent/ksql/cli/console/cmd/RemoteCliSpecificCommandTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/test/util/TestKsqlRestApp.java
Some random tidy up / refactor while I was working on something else.
=> Minor: Tidy up of rest client

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java, ksql-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java, ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
=> Improve error messages for Avro/SR interaction

docs/includes/ksql-includes.rst
=> KSQL-1709: Replace bash code blocks for KSQL snippets with ksql blocks

docs/includes/ksql-includes.rst
Fixed the KSQL CLI banner code block.
=> KSQL-1709: Fix code block lexing warnings in docs build

docs/faq.rst
=> KSQL-1717: Fix build warning in faq.rst

ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java, ksql-engine/src/test/java/io/confluent/ksql/QueryTranslationTest.java, ksql-engine/src/test/java/io/confluent/ksql/SchemaTranslationTest.java, ksql-engine/src/test/java/io/confluent/ksql/TopologyFileGenerator.java
- Include test file name in test name, (so that tests from same file are grouped together)
- Include output row that failed in test.
- Refactor common code into single place.
It's test code thats changed.
=> Minor: Improve test output for QueryTranslationTest

docs/changelog.rst
Add a line to make the list parser happy.
=> KSQL-1722: Fix build warning in changelog.rst

ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java, ksql-engine/src/test/java/io/confluent/ksql/util/FakeKafkaClientSupplier.java
Avoiding log spam in the tests from clients that can't connect as there is no Kafka cluster.
Only test changed.
=> Minor: Switch tests to use mock Kafka clients.

docs/changelog.rst
Remove `...` char to fix build.
=> KSQL-1722: Fix build error in changelog.rst

docs/changelog.rst
Line 29 was truncated in the GitHub title.
=> KSQL-1722: Fix truncated line in changelog.rst

docs/changelog.rst
=> KSQL-1722: Fix broken inline literal

docs/index.rst, docs/tutorials/examples.rst, docs/tutorials/index.rst
=> KSQL-1657: Update wording around KSQL Cookbook links

ksql-console-scripts/src/assembly/resources.xml, ksql-etc/pom.xml, ksql-etc/src/assembly/resources.xml, pom.xml
Add a module that publishes an artifact that contains ksql configs. We'll use
this in the downstream docker image build to include the configs managed here
in docker images
=> Add ksql-etc module

docs/developer-guide/udf.rst
Add an introductory section that gives an overview of UDFs/UDAFs.
=> KSQL-1636: Add intro section to UDFs/UDAFs reference

docs/developer-guide/index.rst, docs/developer-guide/join-streams-and-tables.rst
New topic describing details of KSQL joins.
=> KSQL-1602: First draft of JOIN topic

ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java, ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java, ksql-engine/src/test/resources/query-validation-tests/project-filter.json
Fixes https://github.com/confluentinc/ksql/issues/2027.
=> Minor: Fix bug involving LIKE patterns without wildcards.

docs/installation/installing.rst
Fix indent error in note that breaks the numbering.
=> KSQL-1772: Fix broken numbered list

ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java, ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionTypeManagerTest.java, ksql-engine/src/test/resources/query-validation-tests/project-filter.json
Fixes https://github.com/confluentinc/ksql/issues/866. (Also fixes tabs in ExpressionTypeManagerTest.java to be two spaces instead of four.)
=> Minor: Fix bug involving filters with NOT keyword.

docs/tutorials/index.rst
=> KSQL-1773: Fix indent error under KSQL in a Kafka Streaming ETL section

docs/installation/server-config/avro-schema.rst
Rearrange example statements into linkable headings.
=> KSQL-1771: Update headings per style guide; rework examples for headings

ksql-serde/pom.xml
This makes it easier to switch the Scala version
across the platform.
=> Use `kafka.scala.version` Maven property

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java, ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/HoppingWindowExpression.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/SessionWindowExpression.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/TumblingWindowExpression.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/WithinExpression.java, ksql-parser/src/test/java/io/confluent/ksql/parser/tree/HoppingWindowExpressionTest.java, ksql-parser/src/test/java/io/confluent/ksql/parser/tree/TumblingWindowExpressionTest.java
=> Fix deprication issues.

ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
=> Fixed the test.

ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java, ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
Disable streams optimizations in 5.1.x
=> Disable optimizations for 5.1.x

docs/developer-guide/syntax-reference.rst, docs/tutorials/examples.rst, ksql-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/placeholder/PlaceholderTableUdaf.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/window/WindowEndKudaf.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/window/WindowSelectMapper.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/window/WindowStartKudaf.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/ProjectNode.java, ksql-engine/src/main/java/io/confluent/ksql/structured/QueuedSchemaKStream.java, ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java, ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java, ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java, ksql-engine/src/main/java/io/confluent/ksql/structured/SelectValueMapper.java, ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionMetadata.java, ksql-engine/src/main/java/io/confluent/ksql/util/SelectExpression.java, ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderUtil.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/placeholder/PlaceholderTableUdafTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/window/WindowEndKudafTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/window/WindowSelectMapperTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/window/WindowStartKudafTest.java, ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java, ksql-engine/src/test/java/io/confluent/ksql/planner/plan/ProjectNodeTest.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SelectValueMapperTest.java, ksql-engine/src/test/resources/query-validation-tests/window-bounds.json
* add WindowStartTime UDAF
(cherry picked from commit 839b049)
Original PR: #1993
=> Add WindowStart and WindowEnd UDFs (#1993) (#2090)

docs/developer-guide/index.rst, docs/developer-guide/partition-data.rst
New topic that describes co-partitioning requirements for joins.
=> KSQL-1762: Partition Data to Enable Joins [WIP]

docs/developer-guide/partition-data.rst
Clarified co-partitioning considerations, plus various edits. I added a bit about the `DefaultPartitioner` class and custom partitioners, because there's no obvious topic in our docs or AK docs that discusses this.
=> DOCS-950: Reworked partitions topic per feedback

docs/developer-guide/create-a-stream.rst, docs/developer-guide/create-a-table.rst, docs/developer-guide/index.rst
Also, some clarifications to the "Create a KSQL Stream" topic.
=> KSQL-1789: First draft of Create a KSQL Table topic

pom.xml
depends on https://github.com/confluentinc/common/pull/172
=> inherit shared dependency versions from common

ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerTest.java
=> Fix the build failure.

docs/installation/server-config/config-reference.rst, docs/installation/upgrading.rst
=> Add reference about compatibility breaking configs in upgrade docs

docs/developer-guide/syntax-reference.rst
Which version should I target? Seems like this code made it into pre-5.0.0 bits.
=> KSQL-1912: Add IFNULL function to functions table

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java, ksql-cli/src/main/java/io/confluent/ksql/cli/console/OutputFormat.java, ksql-cli/src/main/java/io/confluent/ksql/cli/console/TrimmingParser.java, ksql-cli/src/test/java/io/confluent/ksql/cli/console/OutputFormatTest.java
Couple of really minor improvements.
Add new test.
=> Fix up some minor CLI issues

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
We duplicated calls to `activenessRegistrar.updateLastRequestTime` when merging the
version checker changes into master. Fixing that with this patch.
=> Fix broken version checker test

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
Reverts confluentinc/ksql#2263
=> Revert "MINOR: Fix bug encountered when restoring RUN SCRIPT command."

docs/troubleshoot-ksql.rst
corrected one typo and made other small changes
Make content easier to understand.
Previewed locally.
- [x ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
=> copy-edited

ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java, ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/ConsumerTestUtil.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/MapMatchers.java
The test this fails intermittently, even with this change, but this change at least removes the confusing combination of `verifyAvailableUniqueRows` and `waitForCondition`
=> Improvements to WindowsIntTest.

docs/troubleshoot-ksql.rst
Fixes this community contribution https://github.com/confluentinc/ksql/pull/2324. 
=> Fix community contribution

docs/troubleshoot-ksql.rst
Backport https://github.com/confluentinc/ksql/pull/2345
=> troubleshooting edits

docs/includes/ksql-includes.rst, docs/operations.rst
=> DOCS-1202 - Cleanup shared include

docs/installation/install-ksql-with-docker.rst
Still not quite baked, please don't review yet.
=> KSQL-2046: Add snippets for communicating with containerized KSQL [WIP]

docs/includes/ksql-includes.rst
=> Remove conflict markers

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandQueue.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogServerUtils.java, ksql-rest-app/src/test/java/io/confluent/ksql/parser/ParserMatchers.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/ProcessingLogServerUtilsTest.java
* Refactor CommandQueue to accept PreparedStatements
(cherry picked from commit 410854e)
Reviewed in #2432
=> Minor: Refactor CommandQueue to accept PreparedStatements (#2432)

docs/installation/server-config/index.rst, docs/installation/server-config/integrate-ksql-with-confluent-control-center.rst
First attempt to capture various details around integrating KSQL with Confluent Control Center.
=> KSQL-1802: First draft of KSQL/C3 integration topic

findbugs/findbugs-exclude.xml, ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlDecodeParamKudfTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlEncodeParamKudfTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlExtractFragmentKudfTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlExtractHostKudfTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlExtractQueryKudfTest.java, ksql-udf-quickstart/pom.xml, ksql-udf-quickstart/src/main/resources/META-INF/maven/archetype-metadata.xml, ksql-udf-quickstart/src/main/resources/archetype-resources/pom.xml, ksql-udf-quickstart/src/main/resources/archetype-resources/src/main/java/ReverseUdf.java, ksql-udf-quickstart/src/main/resources/archetype-resources/src/main/java/SummaryStatsUdaf.java
Fix old copyrights on some files
=> Fix old copyrights on some files

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopic.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutorFactory.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/ConfigStore.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/ConfigTopicKey.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/KafkaConfigStore.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/WriteOnceStore.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/InternalTopicJsonSerdeUtil.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtils.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFactoryTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/ConfigTopicKeyTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/KafkaConfigStoreTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtilsTest.java
Retargeting https://github.com/confluentinc/ksql/pull/1491 at 5.2.x
=> Persist configs standalone 5.2.x

docs/changelog.rst, docs/developer-guide/api.rst
Update changelog (in preparation for 5.2 release) to mention read-after-write consistency.
Docs only change.
=> Minor: update changelog to mention read-after-write consistency.

pom.xml
=> Bump airline version to 2.6.0 (#2043)

ksql-package/src/assembly/package.xml
Use fully specified artifact names in excludes. Temporary fix until we
get logging artifacts in their own group
=> Use fully specified artifact names in excludes

docs/developer-guide/join-streams-and-tables.rst
Per internal ticket DOCS-1246 from @rmoff, the title, [Joins Streams and Tables with KSQL](https://docs.confluent.io/current/ksql/docs/developer-guide/join-streams-and-tables.html), is a bit confusing, since it implies the topic is about stream-table joins only. This PR reworks the title to be more descriptive.
=> DOCS-1246: Update join topic title to include event streams

docs/capacity-planning.rst, docs/faq.rst, docs/includes/ksql-supported-versions.rst, docs/index.rst, docs/installation/check-ksql-server-health.rst, docs/installation/installing.rst, docs/installation/server-config/avro-schema.rst, docs/installation/server-config/config-reference.rst, docs/installation/server-config/security.rst, docs/operations.rst, docs/quickstart.rst, docs/syntax-reference.rst, docs/troubleshoot-ksql.rst, docs/tutorials/basics-docker.rst, docs/tutorials/basics-local.rst, docs/tutorials/examples.rst, docs/tutorials/generate-custom-test-data.rst, docs/tutorials/index.rst
Depends on https://github.com/confluentinc/docs/pull/1646.
=> KSQL-2261: Update ak tokens to ak-tm

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
Drop a var which is written too, but never read
=> Minor: remove unused variable.

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/DistributingExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeFunctionExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ExplainExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListFunctionsExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListPropertiesExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListRegisteredTopicsExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListTopicsExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PropertyExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RequestHandler.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StatementExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/PrintTopicValidator.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/PropertyValidator.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/QueryValidator.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/RequestValidator.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/StatementValidator.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/TerminateQueryValidator.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ExplainExecutorTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/RequestHandlerTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/RequestValidatorTest.java
XLint was failing IntelliJ compilation under higher java languages. This fixes that issue
Compile with intelliJ with -Werror
=> Minor: Add <?> to anywhere were raw types were used

ksql-examples/src/main/java/io/confluent/ksql/datagen/AvroProducer.java, ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java, ksql-examples/src/main/java/io/confluent/ksql/datagen/ProducerFactory.java, ksql-serde/src/main/java/io/confluent/ksql/serde/avro/KsqlAvroTopicSerDe.java
Security-related SR props were not being passed where needed for ksqldata-gen
=> KSQL-2278: Ensure all SR props are passed where needed

pom.xml
https://github.com/google/guava/wiki/CVE-2018-10237
24.0-jre--> 24.1.1-jre
exclude guava from avro.
=> Guava version upgrade and Exclude Guava from Avro dependencies

ksql-engine/src/test/java/io/confluent/ksql/testutils/EmbeddedSingleNodeKafkaCluster.java
Retrofit improvements to the `EmbeddedSingleNodeKafkaCluster` from the master branch to stabilise tests.
=> Minor: Retrofit improvements to test Kafka node to stabilise tests in 4.1.x

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
Code doesn't compile for me. (Not sure where the discrepancy is between my machine and others...)
This PR fixes issues with use of raw types.
usual
=> Minor: fix issue with raw types

ksql-cli/src/main/java/io/confluent/ksql/cli/Options.java, ksql-cli/src/test/java/io/confluent/ksql/cli/commands/OptionsTest.java, ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java, ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/Substring.java, ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/ssl/SslUtil.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/ssl/SslUtilTest.java
move off of cp configdefs.
this depends on https://github.com/confluentinc/rest-utils/pull/133
ran tests locally
=> move off of cp configdefs

docs/developer-guide/syntax-reference.rst
Reverts https://github.com/confluentinc/ksql/pull/2669.
=> Revert edit for SET/UNSET section in KSQL syntax reference

ksql-engine/src/test/resources/expected_topology/5_3_0_pre/key-field_-_table_|_initially_null_|_group_by_(-)_|_key_in_value_|_aliasing, ksql-engine/src/test/resources/expected_topology/5_3_0_pre/key-field_-_table_|_initially_null_|_group_by_(-)_|_key_in_value_|_no_aliasing, ksql-engine/src/test/resources/query-validation-tests/key-field.json
Following on from https://github.com/confluentinc/ksql/pull/2635, this just adds some more details and fixes a few issues.
=> Minor: More key field test enhancements

docs/tutorials/docker-compose.yml
A bad merge slipped in from before. This PR fixes it.
Ran `docker-compose up`.
=> Minor: fixed munged version in quickstart docker-compose

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
The formatting in `JoinNode` is foobarred - this PR makes not code change other than to fix some of the indenting, to minimise future PRs.
The main issue was around the `switch statements`. Fixed those, and a few other issues, then ran our code style over the whole file to pick up any other issues.
=> Minor: Reformat JoinNode

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
Outstanding 'TODO' and previous review comment to pull out common logic of two related functions...
Ran `mvn test`
=> Minor: Refactor to pull out common logic in ScheamKStream

docs/changelog.rst, ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java, ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java, ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
- add release notes on change to the timestamp of the output from joins in the presence of late data.
- Fix KafkaTopicClient
- Fix AggregateNodeTest
=> Fix build: Fix up few tests and add release notes

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java, ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java, ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java, ksql-engine/src/main/java/io/confluent/ksql/planner/PlanSourceExtractorVisitor.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/DataSourceNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/PlanNode.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/PlanVisitor.java, ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java, ksql-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java, ksql-engine/src/test/java/io/confluent/ksql/planner/plan/DataSourceNodeTest.java, ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java, ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java, ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStore.java, ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java, ksql-metastore/src/main/java/io/confluent/ksql/metastore/MutableMetaStore.java, ksql-metastore/src/main/java/io/confluent/ksql/metastore/model/DataSource.java, ksql-metastore/src/main/java/io/confluent/ksql/metastore/model/StructuredDataSource.java, ksql-metastore/src/test/java/io/confluent/ksql/metastore/MetaStoreImplTest.java, ksql-metastore/src/test/java/io/confluent/ksql/metastore/MetaStoreTest.java, ksql-metastore/src/test/java/io/confluent/ksql/metastore/model/StructuredDataSourceTest.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/ClusterTerminatorTest.java
- make `StructuredDataSource` package private as its just an implementation detail
- rename `StructuredDataSoureNode` to `DataSoureNode`
=> Minor: Fix up some remaining issues with data source refactor

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
=> Improve error message when not running queries in headless mode

docs/installation/server-config/security.rst
Added RST anchor to documentation. For reference in https://github.com/confluentinc/docs/pull/1915.
=> DOCS-1283 - Add anchor

ksql-cli/src/test/java/io/confluent/ksql/cli/SslFunctionalTest.java
- Jetty deprecation caused failure
- Build
=> fix broken build by ignoring deprecation

ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java, ksql-functional-tests/src/test/resources/query-validation-tests/join-with-custom-timestamp.json
See https://github.com/apache/kafka/pull/6754 
=> fix tests to account for apache/kafka commit 6754

ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateSourceProperties.java, ksql-parser/src/test/java/io/confluent/ksql/parser/tree/CreateSourcePropertiesTest.java
Fixes issue and added tests (see #2815)
New unit tests
=> fix create stream uses partitions for replicas (fixes #2815)

pom.xml
=> Update support-metrics-common artifact version

pom.xml
=> Update support-metrics-common artifact version (#2874)

ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/command/TestOptionsParserTest.java
- Fix a dead store since it was failing findbugs
- Ran test
=> fix dead store in TestOptionsParserTest

ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedAdminClient.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/TestMethods.java
AK changed... we need to change now too.
`mvn clean install` in progress now
=> update sandbox client to match the new AK API

docs/capacity-planning.rst, docs/concepts/ksql-architecture.rst, docs/installation/server-config/security.rst
This PR adds a few small notes gleaned from a recent KSQL confab.
=> KSQL-2569: Add notes on KSQL deployment

ksql-cli/pom.xml, ksql-package/pom.xml
This is to fix  transitive dependency issues while running system tests in ducker environment
=> Add kafka-log4j-appender artifact to ksql-cli, ksql-package modules

docs/capacity-planning.rst, docs/faq.rst, docs/installation/install-ksql-with-docker.rst, docs/installation/installing.rst
Improves navigation from installation topics to capacity planning and scaling.
=> KSQL-2092: Add links to Scaling KSQL section

docs/capacity-planning.rst, docs/concepts/ksql-architecture.rst
I munged the note markup in https://github.com/confluentinc/ksql/pull/2903.
=> KSQL-2658: Fix note markup

ksql-cli/pom.xml, ksql-package/pom.xml, pom.xml
=> Add kafka-log4j-appender artifact to parent pom dependencyManagement

ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogServerUtils.java
=> Return correctly parametrized processing log type

ksql-common/src/main/java/io/confluent/ksql/schema/connect/SchemaWalker.java, ksql-common/src/test/java/io/confluent/ksql/schema/connect/SchemaWalkerTest.java, ksql-serde/src/main/java/io/confluent/ksql/serde/json/JsonSerdeUtils.java
Prep work for some other minor clean up PRs that want to use the walker to build up state along the way.
`Mvn test`
=> Minor: SchemaWalker to support return values.

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java
- Test only Change
- Ran the test
=> change InsertValuesExecutorTest to use string keys

docs/developer-guide/syntax-reference.rst
Added some clarification to the `PARTITION BY` specification. See https://github.com/confluentinc/ksql/issues/1475.
=> Added clarification to docs for PARTITION BY

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java
A prep PR for a later PR making cleaning up implicit schema fields.
This PR refactors `InsertValuesExecutor` to be more explicit about implicit fields.  The main reason for this is that the later PR will change this class and run into NPath complexity checks. Hence refactoring in standalone PR to make it easier to review.
`mvn test`
=> Minor: Refactor `InsertValuesExecutor` to be more explicit about implicits

ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/StreamsListTableBuilder.java, ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/TablesListTableBuilder.java, ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
Fixes #2973 SHOW output should be alphabetically sorted 
For streams: https://github.com/confluentinc/ksql/commit/b24825c874ee7d8b3f0bb135e1726b04b5f49dfb#diff-d5b73c0cdd3196de0a30d80a55ece79bR469
For tables:
https://github.com/confluentinc/ksql/commit/b24825c874ee7d8b3f0bb135e1726b04b5f49dfb#diff-d5b73c0cdd3196de0a30d80a55ece79bR559
=> KSQL-2973 fixes #2973

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
Fixes : https://github.com/confluentinc/ksql/issues/2979
Manual testing is done.
=> MINOR: KSQL-2979 SPOOL should provide action feedback #2979

ksql-common/src/main/java/io/confluent/ksql/function/AggregateFunctionFactory.java, ksql-common/src/main/java/io/confluent/ksql/util/DecimalUtil.java, ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java, ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java, ksql-engine/src/main/java/io/confluent/ksql/function/UdfCompiler.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/DecimalMaxKudaf.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/MaxAggFunctionFactory.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/min/DecimalMinKudaf.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/min/MinAggFunctionFactory.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/sum/DecimalSumKudaf.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/sum/SumAggFunctionFactory.java, ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctAggFunctionFactory.java, ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/max/DecimalMaxKudafTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/min/DecimalMinKudafTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/sum/DecimalSumKudafTest.java, ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/DecimalTopKDistinctKudafTest.java, ksql-functional-tests/src/test/resources/query-validation-tests/decimal.json, ksql-functional-tests/src/test/resources/query-validation-tests/max-group-by.json, ksql-functional-tests/src/test/resources/query-validation-tests/min-group-by.json, ksql-functional-tests/src/test/resources/query-validation-tests/sum.json, ksql-functional-tests/src/test/resources/query-validation-tests/topk-distinct.json, ksql-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerializer.java, ksql-serde/src/test/java/io/confluent/ksql/serde/delimited/KsqlDelimitedDeserializerTest.java, ksql-serde/src/test/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerializerTest.java
* Support unary `-` and `+` for decimal columns
* Support for SUM, MIN, MAX and TopKDistinct
* New unit tests
* New QTT tests
=> Unary operators and UDAF support for DECIMAL fields

ksql-common/src/main/java/io/confluent/ksql/util/DecimalUtil.java, ksql-common/src/test/java/io/confluent/ksql/util/DecimalUtilTest.java, ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java, ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java, ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java, ksql-functional-tests/src/test/resources/query-validation-tests/cast.json, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Array.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Decimal.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Map.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/PrimitiveType.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Struct.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Type.java
This commit adds support for comparing decimals.
- Unit testing
- QTT tests
=> Support for casting with DECIMAL types

ksql-common/src/main/java/io/confluent/ksql/util/DecimalUtil.java, ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java, ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java, ksql-functional-tests/src/test/resources/query-validation-tests/cast.json, ksql-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerializer.java
As the description says, this is the inverse of the previous PR #2983. Change is pretty straightforward.
- unit testing
- QTT
=> casting from decimal to other data types

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
Remove never referenced properties. ! the below const are public
```
public static final String ARRAY = "ARRAY";	
public static final String MAP = "MAP";	
public static final String STRUCT = "STRUCT";
```
Source code still compile
=> remove unused public fields

docs/changelog.rst, docs/installation/upgrading.rst
Added some missing items to the change log.
=> docs: Updated the changelog for 5.3.

CONTRIBUTING.md, design-proposals/README.md, design-proposals/klip-4-custom-types.md
Update documentation about contributing KLIPs to make the process a cleaner and atomic. Also: fixed a bug in klip-4.
=> docs: update documentation around KLIPs

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlServerMainTest.java
This reverts commit 5eeae5d4af4a75a3b9fd82d9e41fdd69b65a7768.
=> Revert "feat: Enforce availability of the streams state directory. (#3038)"

ksql-functional-tests/README.md, ksql-functional-tests/src/test/java/io/confluent/ksql/test/QueryTranslationTest.java
Small fix on documentation
Code not modified
- [ X] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
=> docs: fix instructions for running query validation tests

ksql-functional-tests/src/main/java/io/confluent/ksql/test/TestFrameworkException.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/TestCaseNode.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/TopicNode.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCase.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/Topic.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/utils/SerdeUtil.java, ksql-functional-tests/src/test/java/io/confluent/ksql/engine/FakeInsertValuesExecutorTest.java, ksql-functional-tests/src/test/java/io/confluent/ksql/test/EndToEndEngineTestUtil.java, ksql-functional-tests/src/test/java/io/confluent/ksql/test/SchemaTranslationTest.java, ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/FakeKafkaServiceTest.java, ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestCaseTest.java, ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorUtilTest.java
With structured keys coming, it makes sense to always specify the key format. Plus, let's remove some code duplication.
=> refactor: lets just have a single constructor for the test topic (minor)

ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/EntityUtil.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java
(#3059) DESCRIBE functionality does not work with DECIMAL types. This fixes that and adds unit test coverage.
Unit test coverage.
=> fix: `DESCRIBE` now works for sources with decimal types (fixes #3059)

ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java, ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
Noticed this inconsistency while doing something else... quick fix.
Test added
=> fix: sqlformatter to correctly handle describe (MINOR)

ksql-functional-tests/README.md, ksql-functional-tests/src/test/resources/query-validation-tests/identifiers.json
Added 2 query validation tests to check for issue https://github.com/confluentinc/ksql/issues/1446
Updated documentation for running single query validation test
=> test: added unit tests for select from aliased source

docs/index.rst, docs/testing-tool.rst
=> docs: Fix broken link

ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ClusterTerminator.java
Super nit refactor: removing unnecessary comments in code and special casing of the exception handling.
`mvn test`
=> refactor: delete unnecessary comments and exception handling (MINOR)

docs/changelog.rst
Make the KSQL changelog topic title unique for improved SEO. 
=> DOCS-2111 - Make KSQL changelog title unique

ksql-execution/pom.xml, pom.xml
Adds a new module ksql-execution, which will be where the new execution plan stuff goes
n/a
=> feat: add a new module ksql-execution for the execution plan interfaces

ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateConnector.java
See subject
Regular build and tests
=> fix: use errorprone Immutable annotation instead of nashorn version

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java, ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java, ksql-engine/src/main/java/io/confluent/ksql/structured/SqlPredicate.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SqlPredicateTest.java
Spotting unnecessary code duplication while working in the area. Quick PR to fix...
`mvn test`
=> refactor: remove unnecessary code duplicate in SqlPredicate (MINOR)

ksql-common/src/main/java/io/confluent/ksql/metrics/ConsumerCollector.java, ksql-common/src/main/java/io/confluent/ksql/metrics/ProducerCollector.java, ksql-common/src/main/java/io/confluent/ksql/metrics/StreamsErrorCollector.java, ksql-engine/src/main/java/io/confluent/ksql/engine/TopicAccessValidatorFactory.java, ksql-engine/src/main/java/io/confluent/ksql/function/GeneratedAggregateFunction.java, ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java, ksql-engine/src/main/java/io/confluent/ksql/services/DefaultServiceContext.java, ksql-engine/src/main/java/io/confluent/ksql/services/KafkaClusterUtil.java, ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java, ksql-engine/src/main/java/io/confluent/ksql/services/LazyServiceContext.java, ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedServiceContext.java, ksql-engine/src/main/java/io/confluent/ksql/services/ServiceContext.java, ksql-engine/src/main/java/io/confluent/ksql/util/KafkaConsumerGroupClientImpl.java, ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTestUtil.java, ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java, ksql-engine/src/test/java/io/confluent/ksql/services/SandboxedAdminClientTest.java, ksql-engine/src/test/java/io/confluent/ksql/services/TestServiceContext.java, ksql-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java
=> chore: update code for new AK release (#3156)

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java, ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4, ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
Quick trival fix for missing capitalisation in SqlBase.g4.
Plus remove of some overrides that do the same as the base impl.
`mvn test`
=> chore: fix typo in SqlBase.g4 (MINOR)

docs/tutorials/basics-local.rst
=> Add anchor

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java, ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/ConnectorListTableBuilder.java, ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java, ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4, ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java, ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java, ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ListConnectors.java, ksql-parser/src/test/java/io/confluent/ksql/parser/tree/ListConnectorsTest.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/ConnectorList.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SimpleConnectorInfo.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListConnectorsExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListConnectorsExecutorTest.java
Add functionality to `SHOW CONNECTORS`
Unit testing and local integration testing:
```
ksql> SHOW CONNECTORS;
Connector Name  | Type   | Class
--------------------------------------------------------------------------
jdbc-connector2 | SOURCE | io.confluent.connect.jdbc.JdbcSourceConnector
jdbc-connector3 | SOURCE | io.confluent.connect.jdbc.JdbcSourceConnector
--------------------------------------------------------------------------
```
=> feat: add SHOW CONNECTORS functionality

package-lock.json, package.json
Fixes #3181
Prior to this change:
```
% npm install
npm WARN ksql No repository field.
npm WARN ksql No license field.
removed 9 packages, updated 21 packages and audited 453 packages in 1.219s
found 7 high severity vulnerabilities
run `npm audit fix` to fix them, or `npm audit` for details
```
With this change:
```
% npm install
npm WARN ksql No repository field.
npm WARN ksql No license field.
audited 456 packages in 1.027s
found 0 vulnerabilities
```
=> chore: update npm package dependencies to remove known vulnerabilities

docs/installation/server-config/index.rst
Physical, not logical link. ><
=> docs: actually add ksql-rbac to the toc (DOCS-2259)

docs/developer-guide/processing-log.rst, docs/installation/server-config/config-reference.rst
Distinguish between the KSQL processing log and the KSQL Server log.
=> docs: add note about KSQL Server logging config (KSQL-2940)

ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
Teeny tiny refactor to `EndToEndIntegrationTest` that was done while working on something else, but which I thought was worth committing rather than reverting.
=> refactor: clean up of test to ensure all queries are closed (MINOR)

ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java
Which will speed it up ever so slightly, but mainly just make it easier to understand.
=> test: remove unnecessary stream from `KsqlResourceFunctionalTest` (MINOR)

ksql-engine/src/test/java/io/confluent/ksql/util/PageViewDataProvider.java
Doesn't seem to be adversely affecting anything, but may as well correct it!
`mvn test`
=> test: page view data provider had wrong key field (MINOR)

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/StatementValidator.java
Use the compiler to check validators and executors are correctly typed.
=> refactor: type safe validators and executors (MINOR)

docs/developer-guide/connect.rst, docs/developer-guide/index.rst, docs/developer-guide/ksql-connect.rst, docs/developer-guide/syntax-reference.rst, docs/developer-guide/udf.rst, docs/installation/server-config/config-reference.rst, docs/tutorials/connect-integration.rst, docs/tutorials/index.rst, ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
Initial draft for KSQL-Connect documentation. Also minor other doc fixes I encountered while making this patch.
**NOTE**: I won't merge this until I have the embedded connect PR merged (which is about to come out)
`make html` and looked at the docs quickly
=> docs: add documentation for KSQL-Connect (initial draft)

ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java, ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
As description says - some clauses did not respect reserved words. Now they do!
=> fix: respect reserved words in more clauses for SqlFormatter (MINOR)

ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Query.java, ksql-parser/src/test/java/io/confluent/ksql/parser/tree/ParserModelTest.java, ksql-parser/src/test/java/io/confluent/ksql/parser/tree/QueryTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
It was used in tests only.
non-functional change
=> refactor: remove unnecessary Query constructor (MINOR)

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java, ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java, ksql-engine/src/main/java/io/confluent/ksql/analyzer/QueryAnalyzer.java, ksql-engine/src/main/java/io/confluent/ksql/engine/QueryEngine.java, ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerTest.java, ksql-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerTest.java, ksql-engine/src/test/java/io/confluent/ksql/testutils/AnalysisTestUtil.java
Quick tidy up - PR removes unnecessary code.
non functional change.
`mvn test`.
=> refactor: remove unnecessary passing of the Sql statement into `Into` (MINOR)

ksql-parser/src/main/java/io/confluent/ksql/parser/SchemaParser.java, ksql-parser/src/test/java/io/confluent/ksql/parser/SchemaParserTest.java
Minor change to make `SchemaParser` more DI friendly.
usual
=> refactor: make SchemaParser ready for dependency injection (MINOR)

.gitignore
Minor QOL change to prevent accidentally including logs in a commit
logs/ doesn't show up creating new logs:`git status`
=> feat: add logs/ to .gitignore (MINOR)

ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/avro/AvroSerdeSupplier.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/avro/ValueSpecAvroSerdeSupplier.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStream.java, ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroSerializerTest.java
Build broken after change due to unchecked warning: https://github.com/confluentinc/schema-registry/commit/c4b487923e0193db5083b17f2744838edd8b24e1
=> fix: address upstream change in KafkaAvroDeserializer

ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java
Test occasionally fail due to stale consumer metadata. This should fix this.
`mvn test`
=> test: reduce metadata refresh time on consumers to stabilise tests

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java, ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/TableRowsTableBuilder.java, ksql-cli/src/test/java/io/confluent/ksql/cli/console/table/builder/TableRowsTableBuilderTest.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/TableRowsEntityFactory.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/TableRowsEntityFactoryTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/StaticQueryFunctionalTest.java, ksql-rest-client/src/test/java/io/confluent/ksql/rest/entity/TableRowsEntityTest.java, ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java, ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/TableRowsEntity.java
Making it more generic...
Nothing in this PR except renames.
=> refactor: rename QueryResultEntity -> TableRowsEntity (MINOR)

ksql-engine/src/main/java/io/confluent/ksql/function/UdfCompiler.java, ksql-engine/src/test/java/io/confluent/ksql/function/UdfCompilerTest.java, ksql-udf/src/main/java/io/confluent/ksql/function/udaf/Udaf.java
Error message was missing the name of the annotation property they needed to set.
usual
=> fix: error message when UDAF has STRUCT type with no schema

ksql-engine/src/main/java/io/confluent/ksql/function/udaf/KudafAggregator.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java
Finally bit the bullet to fix the internals of this class.  
Type is heavily tested through current QTT tests.
=> refactor: simplify KudafAggregator internals (MINOR)

ksql-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java, ksql-engine/src/main/java/io/confluent/ksql/analyzer/ExpressionAnalyzer.java, ksql-engine/src/main/java/io/confluent/ksql/engine/rewrite/ExpressionTreeRewriter.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java, ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java, ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java, ksql-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java, ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/ColumnReferenceExp.java, ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/ExpressionVisitor.java, ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/TraversalExpressionVisitor.java, ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/VisitParentExpressionVisitor.java, ksql-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
This one was missed in recent change to use `ColumnReferenceExp`
=> refactor: correct visitor function name (MINOR)

ksql-engine/src/main/java/io/confluent/ksql/materialization/KsqlMaterialization.java, ksql-engine/src/main/java/io/confluent/ksql/materialization/MaterializedWindowedTable.java, ksql-engine/src/main/java/io/confluent/ksql/materialization/ks/KsMaterializedSessionTable.java, ksql-engine/src/main/java/io/confluent/ksql/materialization/ks/KsMaterializedWindowTable.java, ksql-engine/src/test/java/io/confluent/ksql/materialization/KsqlMaterializationTest.java, ksql-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializationFunctionalTest.java, ksql-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializedSessionTableTest.java, ksql-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializedWindowTableTest.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java
As requested/suggested by @agavra: https://github.com/confluentinc/ksql/pull/3340#discussion_r323943961
usual
=> refactor: static code to use Guava's `Range` class to describe bounds

ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/StaticQueryFunctionalTest.java
Fixes: #3441
Fix is to use different tmp directories per app.  Two instances should not be using the same dir anyway.
test-only change.
=> fix(3441): stabilize the StaticQueryFunctionalTest

ksql-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java, ksql-engine/src/main/java/io/confluent/ksql/engine/QueryEngine.java
This PR simplifies the logic in EngineExecutor.execute and QueryEngine for executing queries.
Previously the logic was somewhat convoluted with the call to create a logical plan occurring even if the statement was DDL (and with the redundant creation of a QueryEngine instance in this case).
I've simplified the logic so logical plan nodes are only created if the statement is a query or query container. Moreover, QueryEngine now is only concerned with queries and the instanceof checking has been moved out of QueryEngine into the EngineExecutor and simplified. The resulting logic is much clearer and easier to follow.
_Note for future: Ideally there would be no instanceof checking at all, but that would be another refactoring. This could be accomplished by the statements themselves knowing …
=> refactor: simplify logic for executing queries and ddl

docs/developer-guide/ksql-connect.rst, docs/developer-guide/ksql-testing-tool.rst, docs/developer-guide/serialization.rst
=> docs: fix doc build syntax issues

docs/developer-guide/syntax-reference.rst, ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToTimestamp.java, ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/TimestampToString.java
Fixes https://github.com/confluentinc/ksql/issues/3451 (See comment on issue for explanation.)
=> docs: fix example in timestamp <-> string docs

ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlan.java
The wrong Immutable annotation was being imported. This fixes it.
=> fix: Use the correct Immutable interface

ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java, ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenSpec.java, ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java, ksql-execution/src/main/java/io/confluent/ksql/execution/sqlpredicate/SqlPredicate.java, ksql-execution/src/test/java/io/confluent/ksql/execution/codegen/ExpressionMetadataTest.java
Address comment on https://github.com/confluentinc/ksql/pull/3469#discussion_r331273367 to make CodeGenSpec immutable.
=> refactor: make CodeGenSpec immutable (MINOR)

ksql-functional-tests/src/test/resources/query-validation-tests/case-expression.json
Removed noise, (e.g. fields that aren't needed), from the test and reformatted more inline with our default formatting of QTT tests
=> chore: remove noise from case-expression.json QTT test

design-proposals/README.md
intent for klip-9: Table Functions
N/A
=> docs: intent for klip-9: Table Functions

ksql-functional-tests/src/test/resources/rest-query-validation-tests/materialized-aggregate-static-queries.json, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java
=> fix(3524): improve pull query error message (MINOR)

ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java, ksql-functional-tests/src/test/resources/query-validation-tests/timestamp-to-string.json, ksql-functional-tests/src/test/resources/query-validation-tests/timestampformat.json
While answering some user questions I extended some of our test cases....
=> test: improve tz test coverage

ksql-engine/src/test/java/io/confluent/ksql/testutils/EmbeddedSingleNodeKafkaCluster.java
This commit brings together some recent tweaks done on master to improve the stability of integration tests.
=> test: improve stability of tests on older branches

design-proposals/klip-9-table-functions.md
Fixes: https://github.com/confluentinc/ksql/issues/3512
This PR contains a new KLIP - KLIP-9 proposal for table functions.
=> docs: klip-9: Table Functions

.github/ISSUE_TEMPLATE/feature---enhancement-request.md, .github/ISSUE_TEMPLATE/other.md, .github/ISSUE_TEMPLATE/question.md
Adding the following templates:
- Feature / Enhancement
- Question
- Generic issue
=> Updated issue templates

ksql-functional-tests/src/test/java/io/confluent/ksql/test/TopologyFileGenerator.java
This PR adds a link to the test required to run to create topology files
N/A
=> chore: Add link to test in javadoc

README.md
=> docs: Added links to new google groups and slack channel to README

docs/developer-guide/udf.rst
=> docs: improve docs for @Udf

docs-md/developer-guide/udf.md
Migrate new content from: https://github.com/confluentinc/ksql/pull/3737
=> docs: copy new annotation fields content in UDF reference (DOCS-2858)

design-proposals/README.md, design-proposals/klip-10-suppress.md
Opening a PR to reserve KLIP-10 and make public the intent to KLIP. Also update some of the statuses of previous PRs.
=> docs: intent for klip-10: add suppress to KSQL

.github/no-response.yml
=> chore: Update flag name for no-response bot

design-proposals/README.md, design-proposals/klip-11-DQL.md
=> docs: intent for klip-11: Redesign KSQL query language

docs/developer-guide/serialization.rst, docs/developer-guide/syntax-reference.rst, docs/developer-guide/udf.rst, ksql-engine/src/main/java/io/confluent/ksql/util/LimitedProxyBuilder.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/ExpectedRecordComparator.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/Record.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java, ksql-functional-tests/src/test/java/io/confluent/ksql/test/SchemaTranslationTest.java, ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java, ksql-functional-tests/src/test/resources/query-validation-tests/array.json, ksql-serde/pom.xml, ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java
Minor follow-ups based on my previous pr and @big-andy-coates' comments. Also some documentation.
`mvn clean install` and looked at the docs after `make html`
=> chore: follow-ups for numeric JSON decimal support and documentation

CONTRIBUTING.md
This PR updates CONTRIBUTING.MD to reflect the fact that the project now uses standard company coding style with no extra requirements for final args and local variables.
As discussed https://github.com/confluentinc/ksql/pull/3642
N/A
=> docs: Revert to standard google style

pom.xml
Remove jackson-databind version override in the main pom and inherit from the common pom.
Ran `mvn clean install` to verify no failures.
=> build: Inherit jackson from common pom

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DdlCommandExec.java, ksql-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java, ksql-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java, ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlPlan.java
Follows on from #3764
See comment: https://github.com/confluentinc/ksql/pull/3764#discussion_r342960222
usual
=> chore: drop legacy key field override from the ddl executor

ksql-common/src/main/java/io/confluent/ksql/util/WelcomeMsgUtils.java, ksql-common/src/test/java/io/confluent/ksql/util/WelcomeMsgUtilsTest.java
```
===========================================
=       _              _ ____  ____       =
=      | | _____  __ _| |  _ \| __ )      =
=      | |/ / __|/ _` | | | | |  _ \      =
=      |   <\__ \ (_| | | |_| | |_) |     =
=      |_|\_\___/\__, |_|____/|____/      =
=                   |_|                   =
=  Event Streaming Database purpose-built =
=        for stream processing apps       =
===========================================
```
=> chore: change CLI splash screen

docs-md/concepts/collections/streams.md, docs-md/concepts/collections/tables.md
=> docs: first draft of ksqlDB streams and tables topics (DOCS-2925, DOCS-2926)

Jenkinsfile
This will download any docker images this build depends on, such as cp-base-new
Testing will be done in this PR
=> build: ST-2519: Download the docker base image before building

Jenkinsfile
=> build: build docker artifacts with db names

ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java, ksql-engine/src/test/java/io/confluent/ksql/util/TopicProducer.java
Minor fix up while working in the test class
=> test: fix up CliTest and remove logic to add trailing semicolon (MINOR)

ksql-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java, ksql-execution/src/test/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatterTest.java, ksql-parser/src/main/java/io/confluent/ksql/parser/ExpressionFormatterUtil.java, ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
Minor: remove unused field. 
`mvn test`
=> refactor: remove unused `unmangleNames` var (MINOR)

docs-md/concepts/time-and-windows-in-ksql-queries.md, docs-md/developer-guide/index.md, docs-md/developer-guide/serialization.md, docs-md/stylesheets/extra.css, mkdocs.yml
Fixed a few problems with TOCs and old text.
Just docs.
=> Mdrogalis more docs

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java
=> chore: fix bad merge

ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/StreamedRow.java
Add a string for StreamedRow so that we can debug when some Jenkins unit tests that check equality fail.
Tested manually that toString works
=> chore: add toString to StreamedRow (MINOR)

ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/StreamedRow.java
Corollary to #3890 - I didn't realize there was this class I needed to handle as well.
=> chore: add toString to StreamedRow.Header (MINOR)

docs-md/operate-and-deploy/index.md, docs-md/operate-and-deploy/ksql-vs-ksqldb.md, mkdocs.yml
Outlines key differences and incompatibilities between KSQL and ksqlDB.
=> docs: add overview of key incompatibilities between KSQL and ksqlDB

CHANGELOG.md, README.md
^
README draft credits go to @derekjn !
Docs-only.
=> docs: add changelog and README for v0.6.0

Jenkinsfile
The promote to production workflow was not working because it was not logging into docker hub before trying to push the images. This separates the workflow so that first we authenticate with ECR and pull the images. Then login to docker hub and tag and push the images. 
This workflow can not be tested through the PR build so I did a replay of the build which failed when doing promote to production, and I inserted this new code into the Jenkinsfile and it was successful.
https://jenkins.confluent.io/job/confluentinc/job/ksql/job/ksql-db-release/36/console
=> Fix the promote to production workflow by logging into docker hub

pom.xml
See: https://github.com/jline/jline3/issues/408
Couldn't reproduce locally.
=> fix: some terminals dont work with JLine 3.11

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java
=> test: switch InteractiveStatmentExecutorTest to use mockito

README.md
Community Slack channels renamed.
=> Slack channels renamed

ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
The pull query test is occasionally failing. This looks to be a simply case of the timeout being too short.
e.g. https://jenkins.confluent.io/job/confluentinc/job/ksql/job/master/3684/testReport/junit/io.confluent.ksql.test.rest/RestQueryTranslationTest/shouldBuildAndExecuteQueries_pull_queries_against_materialized_aggregates___text_datetime_window_bounds_/
usual
=> test: fix flaky RQTT test

ksql-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java
Maybe fixes: #3973
We see occasional RQTT test failures due to topics from previous test cases not being deleted by the time the next test case tries to create them.
I'm not aware of any way to _know_ a topic marked for deletion has actually beeen deleted.
However, I noticed that the test code was not even waiting for the completion of the future returned from the `Admin` client's `deleteTopics` call.
Additionally, the java docs for `deleteTopics` suggests calling `listTopics` and wait util the topic name is no longer returned, so I've added this. However, I'm 99% sure this won't help as the `listTopics` call doesn't return topics marked for deletion.
=> test: maybe fix flaky test

design-proposals/README.md
@big-andy-coates as you suggested in the https://github.com/confluentinc/ksql/pull/4003#issuecomment-560380185 and following the [KLIP contribution](https://github.com/confluentinc/ksql/blob/master/design-proposals/README.md) process I create the intent PR for new KLIP.
Thank you.
None
=> docs: intent for klip-13: Introduce KSQL command to print connect worker properties to the console

ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java, ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutorTest.java, ksql-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
The test executor was testing that the expected result was the expected result, rather than the _actual_ result was the expected result.
Also, added some more logging to help track down intermittent failures.
=> test: fix bug in RQTT response matching logic (MINOR)

pom.xml
use [https] for Maven repositories
`mvn clean package`
=> build: use [https] instead of [http]

docs/changelog.rst
Update file metadata to optimize for inclusion in CP docs. 
=> docs: update KSQL changelog file formatting (DOCS-3055)

design-proposals/README.md
=> docs: intent for klip-15: new KSQLDB client and API

design-proposals/klip-14-rowtime-as-pseudocolumn.md
Proposal for switching `ROWTIME` to be a pseudo -column.  Read the proposal [here](https://github.com/confluentinc/ksql/blob/013a31707005a7e00338e25fd0ed3037426babe8/design-proposals/klip-14-rowtime-as-pseudocolumn.md)
=> docs: propose KLIP-14

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WebSocketSubscriber.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorTest.java
#4043 
Behavior also exists in 5.4
Verified websocket error message returned.
=> chore: porting #4043 to fix websocket exception on pull query disabled

docs-md/tutorials/basics-docker.md, docs-md/tutorials/basics-local.md, docs-md/tutorials/clickstream-docker.md, docs/includes/ksql-includes.rst, docs/tutorials/clickstream-docker.rst, ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
=> chore: change exit message to "exiting ksqlDB" (MINOR)

ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/SourceNode.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/matchers/MetaStoreMatchers.java, ksql-functional-tests/src/test/resources/query-validation-tests/key-field.json, ksql-functional-tests/src/test/resources/query-validation-tests/math.json, ksql-functional-tests/src/test/resources/query-validation-tests/serdes.json, ksql-functional-tests/src/test/resources/query-validation-tests/table-functions.json
With primitive keys coming the QTT test needs to be able to test the full schema is correct, not just the value schema.
=> test: have QTT support checking full schema of sources (MINOR)

docs-md/concepts/queries/index.md, docs-md/concepts/queries/pull.md, docs-md/concepts/queries/push.md, docs-md/developer-guide/ksqldb-reference/select-pull-query.md, docs-md/developer-guide/ksqldb-reference/select-push-query.md
Fixes https://github.com/confluentinc/ksql/issues/4011.
=> docs: update push and pull query topics with feedback (DOCS-3092)

ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamStreamJoin.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamTableJoin.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/TableTableJoin.java, ksql-rest-app/src/test/resources/ksql-plan-schema/schema.json, ksql-streams/src/main/java/io/confluent/ksql/execution/streams/KSPlanBuilder.java
Change `left` and `right` in join steps to `leftSource` and `rightSource`.
=> chore: fix join left right names

ksql-streams/src/main/java/io/confluent/ksql/execution/streams/GroupByParamsFactory.java, ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StepSchemaResolver.java, ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StepSchemaResolverTest.java
As per comment here: https://github.com/confluentinc/ksql/pull/4108/files#r357023751
usual
=> chore: simplify group by schema resolving code

ksql-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
Partial fix for : https://github.com/confluentinc/ksql/issues/4123
Pull query support for primitive keys.
More testing to come, but needs enhancements to test framework first.
Test case added for INT, other types coming.
=> chore: pull query support for primitive keys

ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlPlanV1Test.java, ksql-engine/src/test/java/io/confluent/ksql/engine/QueryPlanTest.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/AbstractStreamSource.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamFlatMap.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSource.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/TableSource.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/WindowedStreamSource.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/WindowedTableSource.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamAggregateTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamFilterTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamFlatMapTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamGroupByKeyTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamGroupByTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamSelectKeyTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamSelectTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamSinkTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamSourceTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamStreamJoinTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamTableJoinTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamWindowedAggregateTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/TableAggregateTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/TableFilterTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/TableGroupByTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/TableSelectTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/TableSinkTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/TableSourceTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/TableTableJoinTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/WindowedStreamSourceTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/WindowedTableSourceTest.java
Adds equals testers for all the plan POJOs
=> test: add equals testers for plan classes

Jenkinsfile
We should not be building the docker images in this repo unless doing a ksqldb build.
=> build: Disable building docker images

Jenkinsfile
For release builds this will publish the maven artifacts to an s3 staging bucket.
I tested this by replaying a ksql-db-release job using this new script. It successfully published the maven artifacts to the s3 bucket.
=> build: ST-2813: Publish maven artifacts to staging repo if doing a release build

Jenkinsfile
When running promote to production this will sync the maven artifacts from the staging s3 bucket to the release s3 bucket. I also added stages around the steps in the promote to production process so we can more easily identify what is happening.
This can't be tested with out running promote to production which releases artifacts to production. I did this manually though for the initial release and it worked.
=> build: ST-2813: Promote maven artifacts to release s3 bucket

docs-md/tutorials/embedded-connect.md
* Fix connector config nits
* Bump to 5.3.2 since JDBC connector is now at 5.3.2 so references to 5.3.1 didn't work
* Remove partitions from CT because the topic already exists
* Clarify that new topic is being created (vs the driverProfiles where the topic already exists)
* Add note re. Avro and JSON
=> docs: tweaks to embedded connector tutorial

ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanLoader.java
Remove an unused import (containing also a double semi-colon).
@spena Here from #4192.
Build is ok.
=> chore: remove unused import

docs-md/operate-and-deploy/installation/install-ksqldb-with-docker.md, docs-md/operate-and-deploy/installation/installing.md, docs/tutorials/docker-compose.yml, mkdocs.yml
Rewrites the installation docs to focus on Docker containers.
=> docs: refactor installation docs around Docker (DOCS-3009)

docs-md/developer-guide/ksqldb-reference/aggregate-functions.md
=> docs: add docs for COUNT_DISTINCT (MINOR)

ksql-functional-tests/src/test/resources/query-validation-tests/group-by.json, ksql-functional-tests/src/test/resources/query-validation-tests/partition-by.json
Fixes: https://github.com/confluentinc/ksql/issues/4107
=> test: ensure test cases for group by and partition by primitive key

ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java, ksql-functional-tests/src/test/resources/query-validation-tests/count.json, ksql-functional-tests/src/test/resources/query-validation-tests/table.json
and fixed small bug in test framework
=> test: added more table related test cases (MINOR)

config/ksql-production-server.properties, config/ksql-server.properties
=> fix: remove duplicate comment about Schema Regitry URL from sample server properties

design-proposals/klip-template.md
I've added a few sections to the KLIP template to encourage us think about execution milestones, scope, design, and testing up front. 
None. Docs only change.
=> docs: Updates to the KLIP-template

docs-md/developer-guide/syntax-reference.md, ksql-functional-tests/src/test/resources/query-validation-tests/quoted-identifiers.json
- add documentation around string constants
- add some test coverage to PARTITION BY with quoted identifiers
- ran the QTT test
=> docs: misc docs and tests (MINOR)

ksql-api/src/main/java/io/confluent/ksql/api/server/ApiServerConfig.java, ksql-api/src/main/java/io/confluent/ksql/api/server/Server.java, ksql-api/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java, ksql-api/src/test/java/io/confluent/ksql/api/ApiServerConfigTest.java, ksql-api/src/test/java/io/confluent/ksql/api/ApiTest.java, ksql-api/src/test/java/io/confluent/ksql/api/BufferedPublisherTest.java
Issue: https://github.com/confluentinc/ksql/issues/4330
This PR introduces a new config based on AbstractConfig for configuring the API server.
The current config param names and docs are kind of provisional as they're likely to change a fair bit as the server is integrated into the ksqlDB back end, so don't read too much into them right now.
API tests pass
=> feat: Use AbstractConfig for API server config

ksql-execution/src/main/java/io/confluent/ksql/execution/transform/sqlpredicate/SqlPredicate.java
See title... hopefully self explanatory!
`mvn test integration-test`
=> refactor: remove duplicate code from SqlPredicate

ksql-api/src/main/java/io/confluent/ksql/api/server/AcksSubscriber.java, ksql-api/src/main/java/io/confluent/ksql/api/server/BufferedPublisher.java, ksql-api/src/main/java/io/confluent/ksql/api/server/ReactiveSubscriber.java, ksql-api/src/test/java/io/confluent/ksql/api/BufferedPublisherTest.java, ksql-api/src/test/java/io/confluent/ksql/api/ReactiveSubscriberTest.java, ksql-api/src/test/java/io/confluent/ksql/api/TestUtils.java
Follow ups from PR https://github.com/confluentinc/ksql/pull/4354
Includes new test
=> chore: follow ups from PR 4354

ksql-api/src/test/java/io/confluent/ksql/api/ApiTest.java
Completes https://github.com/confluentinc/ksql/issues/4332
Convert usage of JUnit asserts to Hamcrest in ApiTest
=> chore: Hamcresterise all the things

ksql-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json
Disables one test case which is failing
mvn package
=> Fix RestQueryTranslationTest test to use UTC time zone.

ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java, ksql-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStoreTest.java
Upstream Streams change is causing master builds to fail.
`mvn test`
=> chore: fix upstream deprecation causing build failure

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/DataSourceNode.java, ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKSourceFactory.java, ksql-engine/src/test/java/io/confluent/ksql/planner/plan/DataSourceNodeTest.java, ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKSourceFactoryTest.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/SourceStep.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSource.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/TableSource.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/WindowedStreamSource.java, ksql-execution/src/main/java/io/confluent/ksql/execution/plan/WindowedTableSource.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/StreamSourceTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/TableSourceTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/WindowedStreamSourceTest.java, ksql-execution/src/test/java/io/confluent/ksql/execution/plan/WindowedTableSourceTest.java, ksql-functional-tests/src/test/resources/historical_plans/average_-_calculate_average_in_select/5.5.0_1579766275923/spec.json, ksql-rest-app/src/test/resources/ksql-plan-schema/schema.json, ksql-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java, ksql-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java, ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StepSchemaResolverTest.java
Drops the alias from the plan schema as its no longer required.
=> chore: drop alias from plan schema

ksql-api/src/test/java/io/confluent/ksql/api/ReactiveSubscriberTest.java
=> chore: fix flaky test

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/LagReportingAgent.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ClusterStatusResource.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/LagReportingAgentFunctionalTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java, ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/HostStoreLags.java, ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/StateStoreLags.java
Changes some lag APIs to return Optional rather than nullable values, per discussion here: https://github.com/confluentinc/ksql/pull/4417#pullrequestreview-352162375
Ran existing tests
=> refactor: Changes lag APIs to return Optional, per comments

ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
=> fix: fix compilation error due to `Format` refactoring

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
=> fix: rename stale to standby in KsqlConfig

ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
Removes an unnecessary timeout.
Ran tests
=> fix: Remove unnecessary timeout in PullQueryRoutingFunctionalTest

ksql-rest-model/src/main/java/io/confluent/ksql/rest/DefaultErrorMessages.java
https://github.com/confluentinc/ksql/pull/4486#issuecomment-584091547
Slight error message wording adjustment to make it clearer
=> chore: adjusting wording on transaction timeout error message

docs-md/developer-guide/test-and-debug/ksqldb-testing-tool.md, docs/developer-guide/ksql-testing-tool.rst, ksql-functional-tests/src/test/resources/test-runner/correct/from_docs/input.json, ksql-functional-tests/src/test/resources/test-runner/correct/from_docs/output.json, ksql-functional-tests/src/test/resources/test-runner/correct/from_docs/statements.sql, ksql-functional-tests/src/test/resources/testing_tool_tests.json
fixes: https://github.com/confluentinc/ksql/issues/4434
fixes: https://github.com/confluentinc/ksql/issues/4067
=> test: update tests and docs around testing tool and primitive keys

Jenkinsfile
Point to new ksqldb version (0.7.0) and use latest successful build of cp
=> fix: Update jenkinsfile for new release

docs-md/operate-and-deploy/installation/server-config/config-reference.md, ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
=> docs: update docs for klip-12 configs

ksql-cli/src/test/java/io/confluent/ksql/cli/BasicAuthFunctionalTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/filters/KsqlAuthorizationFilterTest.java
This mostly just swaps out standard library utilities for some internal Jersey utilities that have been removed in recent versions. Additionally, one API has been deprecated.
These are all changes to test code.
=> chore: api update for Jersey 2.30

docs-md/developer-guide/joins/partition-data.md, docs-md/tutorials/embedded-connect.md
Fixes #4521. Example statements still need to be tested. Also fixes a broken link.
=> docs: update embedded Connect topic for primitive keys (DOCS-3385)

docs-md/developer-guide/implement-a-udf.md
=> docs: update UDF topic with latest java code and pom.xml (DOCS-3386)

Jenkinsfile
=> build: remove image revision from promote path

docs-md/operate-and-deploy/installation/upgrading.md, mkdocs.yml
=> docs: add ksqlDb upgrade topic to TOC (DOCS-3396)

ksql-cli/src/test/java/io/confluent/ksql/cli/BasicAuthFunctionalTest.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/filters/KsqlAuthorizationFilterTest.java
This reverts commit 0dc8e648f6b2c97b6b77144ecabc8bb38cbcd339.
Temporary revert in order to unblock the build until the artifactory dependency issue is resolved.
=> chore: revert "API update for Jersey 2.30 (#4508)"

CHANGELOG.md
=> docs: add note in breaking changes about not skipping statements from command topic

ksql-api/src/test/java/io/confluent/ksql/api/utils/SendStream.java
=> fix: suppress findbugs warnings

docs-md/operate-and-deploy/installation/server-config/security.md
Content copied from https://github.com/confluentinc/ksql/pull/4617.
=> docs: copy security settings from rst to markdown topic (DOCS-3463)

docs/installation/server-config/security.rst
Missed a part in the docs that needed to be updated from previous PR
https://github.com/confluentinc/ksql/pull/3660
Docs only change
=> docs: add to security docs about transaction ACLs

ksql-functional-tests/src/main/java/io/confluent/ksql/test/utils/SerdeUtil.java, ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_elements_OK_-_PROTOBUF/5.5.0_1582662519759/spec.json, ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_elements_OK_-_PROTOBUF/5.5.0_1582662519759/topology, ksql-functional-tests/src/test/resources/query-validation-tests/elements.json
@big-andy-coates pointed out that we were missing tests for protobuf schema lookup. This PR adds it!
=> test: add a test for protobuf without schema

ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestPath.java, ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanLoader.java, ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCaseSpecNode.java, ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_elements_OK_-_PROTOBUF/5.5.0_1582662519759/plan.json, ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_elements_OK_-_PROTOBUF/5.5.0_1582662519759/spec.json
The `spec.json` in the 5.5.x branch has been split into a `spec.json` and `plan.json` in the master branch.
Fixes broken builds like: https://jenkins.confluent.io/job/confluentinc/job/ksql/job/master/4213/
=> chore: fix build failure due to bad merge from 5.5 branch

ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/ExpectedRecordComparator.java, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_coerce_column_types_that_are_not_directly_supported/6.0.0_1582714366811/plan.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_coerce_column_types_that_are_not_directly_supported/6.0.0_1582714366811/spec.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_coerce_column_types_that_are_not_directly_supported/6.0.0_1582714366811/topology, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_convert_enum_to_STRING/6.0.0_1582714366714/plan.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_convert_enum_to_STRING/6.0.0_1582714366714/spec.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_convert_enum_to_STRING/6.0.0_1582714366714/topology, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_convert_record_to_STRUCT/6.0.0_1582714366785/plan.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_convert_record_to_STRUCT/6.0.0_1582714366785/spec.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_convert_record_to_STRUCT/6.0.0_1582714366785/topology, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_filter_out_columns_with_unsupported_types/6.0.0_1582714366833/plan.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_filter_out_columns_with_unsupported_types/6.0.0_1582714366833/spec.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_filter_out_columns_with_unsupported_types/6.0.0_1582714366833/topology, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_support_arrays/6.0.0_1582714366737/plan.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_support_arrays/6.0.0_1582714366737/spec.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_support_arrays/6.0.0_1582714366737/topology, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_support_maps/6.0.0_1582714366763/plan.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_support_maps/6.0.0_1582714366763/spec.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_support_maps/6.0.0_1582714366763/topology, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_support_primitives/6.0.0_1582714366612/plan.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_support_primitives/6.0.0_1582714366612/spec.json, ksql-functional-tests/src/test/resources/historical_plans/avro_-_should_support_primitives/6.0.0_1582714366612/topology, ksql-functional-tests/src/test/resources/historical_plans/elements_-_should_coerce_column_types_that_are_not_directly_supported_-_AVRO/6.0.0_1582714371749/plan.json, ksql-functional-tests/src/test/resources/historical_plans/elements_-_should_coerce_column_types_that_are_not_directly_supported_-_AVRO/6.0.0_1582714371749/spec.json, ksql-functional-tests/src/test/resources/historical_plans/elements_-_should_coerce_column_types_that_are_not_directly_supported_-_AVRO/6.0.0_1582714371749/topology, ksql-functional-tests/src/test/resources/query-validation-tests/avro.json
Add explicit tests around Avro schema inference.
@agavra : would be good to have similar for new PB/JSON inference.
=> test: add more explicit tests around AVRO schema inference

design-proposals/README.md, design-proposals/klip-template.md
=> docs: intent for klip-22: Add consumer group id to CREATE STREAM and CREATE TABLE DSL

Jenkinsfile, maven-settings-template.xml
The internal artifact host was recently updated. This updates the relevant references in the release job config.
cf. #4574
=> chore: update release Jenkinsfile artifact host

ksql-rest-app/src/main/java/io/confluent/ksql/api/server/protocol/QueryResponseMetadata.java
This PR adds Immutability test which makes sure classes marked with @Immutable really are immutable.
It also removes @Immutable from 3 classes as making them @Immutable serves little purpose and we don't want to be forced to make too many copies in perf sensitive code.
Also please see https://github.com/confluentinc/ksql/pull/4410
=> test: Add ImmutabilityTest

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java, ksql-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientUtilTest.java, ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlRequest.java, ksql-rest-model/src/test/java/io/confluent/ksql/rest/entity/KsqlRequestTest.java
Revert the breaking api change
=> fix: change configOverrides back to streamsProperties

ksql-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java, ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java, ksql-engine/src/main/java/io/confluent/ksql/analyzer/ColumnReferenceValidator.java, ksql-engine/src/main/java/io/confluent/ksql/analyzer/RewrittenAnalysis.java, ksql-engine/src/main/java/io/confluent/ksql/engine/rewrite/AstSanitizer.java, ksql-engine/src/main/java/io/confluent/ksql/engine/rewrite/StatementRewriteForMagicPseudoTimestamp.java, ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java, ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java, ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java, ksql-engine/src/test/java/io/confluent/ksql/analyzer/ColumnReferenceValidatorTest.java, ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java, ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java, ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java, ksql-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java, ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/ColumnReferenceExp.java, ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/QualifiedColumnReferenceExp.java, ksql-execution/src/main/java/io/confluent/ksql/execution/function/UdafUtil.java, ksql-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java, ksql-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java, ksql-parser/src/main/java/io/confluent/ksql/parser/ColumnReferenceParser.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
Quick rename to make code more readable.
non-funcitonal
=> chore: rename ColRefExp getter (Minor)

ksql-benchmark/src/main/resources/log4j.properties, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_both_join_keys_in_projection/6.0.0_1583278618734/plan.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_both_join_keys_in_projection/6.0.0_1583278618734/spec.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_both_join_keys_in_projection/6.0.0_1583278618734/topology, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_rekey_-_AVRO/6.0.0_1583278618385/plan.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_rekey_-_AVRO/6.0.0_1583278618385/spec.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_rekey_-_AVRO/6.0.0_1583278618385/topology, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_rekey_-_JSON/6.0.0_1583278618459/plan.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_rekey_-_JSON/6.0.0_1583278618459/spec.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_rekey_-_JSON/6.0.0_1583278618459/topology, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_rekey_-_PROTOBUF/6.0.0_1583278618529/plan.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_rekey_-_PROTOBUF/6.0.0_1583278618529/spec.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_rekey_-_PROTOBUF/6.0.0_1583278618529/topology, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_right_join_key_in_projection/6.0.0_1583278618673/plan.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_right_join_key_in_projection/6.0.0_1583278618673/spec.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_-_right_join_key_in_projection/6.0.0_1583278618673/topology, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_rowkey_-_rekey_-_AVRO/6.0.0_1583278618121/plan.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_rowkey_-_rekey_-_AVRO/6.0.0_1583278618121/spec.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_rowkey_-_rekey_-_AVRO/6.0.0_1583278618121/topology, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_rowkey_-_rekey_-_JSON/6.0.0_1583278618231/plan.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_rowkey_-_rekey_-_JSON/6.0.0_1583278618231/spec.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_rowkey_-_rekey_-_JSON/6.0.0_1583278618231/topology, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_rowkey_-_rekey_-_PROTOBUF/6.0.0_1583278618312/plan.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_rowkey_-_rekey_-_PROTOBUF/6.0.0_1583278618312/spec.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_rowkey_-_rekey_-_PROTOBUF/6.0.0_1583278618312/topology, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_to_table_when_neither_have_key_field_and_joining_by_table_key_column/6.0.0_1583278622930/plan.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_to_table_when_neither_have_key_field_and_joining_by_table_key_column/6.0.0_1583278622930/spec.json, ksql-functional-tests/src/test/resources/historical_plans/joins_-_stream_to_table_when_neither_have_key_field_and_joining_by_table_key_column/6.0.0_1583278622930/topology, ksql-functional-tests/src/test/resources/query-validation-tests/joins.json, ksql-test-util/src/main/resources/log4j.properties
Plus remove some log spam caused by PB config types.
non-functional change,.
=> test: re-enable some QTT tests now that Primitive key work is in

ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_other_scalars/5.5.0_1582739203914/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_other_scalars/5.5.0_1582739203914/topology, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_other_scalars/5.5.0_1583365544933/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_other_scalars/5.5.0_1583365544933/topology, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_primitives/5.5.0_1582739203532/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_primitives/5.5.0_1582739203532/topology, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_primitives/5.5.0_1583365544793/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_primitives/5.5.0_1583365544793/topology, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_convert_enum_to_STRING/5.5.0_1583365544845/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_convert_enum_to_STRING/5.5.0_1583365544845/topology, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_convert_nested_types_to_STRUCT/5.5.0_1582739203881/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_convert_nested_types_to_STRUCT/5.5.0_1582739203881/topology, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_convert_nested_types_to_STRUCT/5.5.0_1583365544918/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_convert_nested_types_to_STRUCT/5.5.0_1583365544918/topology, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_filter_out_columns_with_unsupported_types/5.5.0_1582739203979/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_filter_out_columns_with_unsupported_types/5.5.0_1582739203979/topology, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_filter_out_columns_with_unsupported_types/5.5.0_1583365544960/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_filter_out_columns_with_unsupported_types/5.5.0_1583365544960/topology, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_support_arrays/5.5.0_1582739203846/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_support_arrays/5.5.0_1582739203846/topology, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_support_arrays/5.5.0_1583365544879/spec.json, ksql-functional-tests/src/test/resources/historical_plans/protobuf_-_should_support_arrays/5.5.0_1583365544879/topology, ksql-functional-tests/src/test/resources/query-validation-tests/protobuf.json
The protobuf corollary for #4635. See `protobuf.json` file (the rest is auto-generated).
NOTE: the enum test is disabled while I work something out with @rayokota 
=> test: add more coverage to protobuf schema lookup

ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java, ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java, ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java, ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java, ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java, ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java, ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
Similar to https://github.com/confluentinc/ksql/pull/4662 but for 5.3
=> fix: backport fixes from query close

docs-md/developer-guide/ksqldb-reference/scalar-functions.md
Docs were out-of-date for these functions.
N/A
=> docs: update ARRAY and MAP docs

docs-md/concepts/index.md, docs-md/concepts/processing-guarantees.md, docs-md/developer-guide/ksqldb-rest-api/query-endpoint.md, docs-md/operate-and-deploy/installation/server-config/config-reference.md, mkdocs.yml
=> docs: cherry-pick new processing guarantees topic (KSQL-3721)

ksql-engine/pom.xml, ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/ValueSpec.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCase.java, ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/conditions/PostConditions.java, ksql-parser/pom.xml, ksql-version-metrics-client/pom.xml, pom.xml
=> Fix broken 5.3.x

ksql-engine/pom.xml
=> fix: build

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/RegexpExtract.java, ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/RegexpExtractTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_extract_with_group/6.0.0_1584139441429/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_extract_with_group/6.0.0_1584139441429/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_extract_with_group/6.0.0_1584139441429/topology, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_extract_without_group/6.0.0_1584139441404/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_extract_without_group/6.0.0_1584139441404/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_extract_without_group/6.0.0_1584139441404/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/regex.json
https://github.com/confluentinc/ksql/issues/878
Based it off of these docs
https://prestodb.io/docs/current/functions/regexp.html
Going to generate the new topology plans after the re-name is done and I rebase.
Unit test for UDF
QTT test
=> feat: add REGEXP_EXTRACT UDF

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ProxyHandler.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
Fixes https://github.com/confluentinc/ksql/issues/4760
If the request contains a connection:close header, it appears Jetty sends back a response without content-length set. Vert.x doesn't like this as it expects content-length to be set for all non chunked responses.
This works around the issue by adding transfer-encoding:chunked if Jetty omits this.
Note that the ksql CLI doesn't seem to send connection:close so this issue only seems to affect the reproducer.
=> fix: add transfer-encoding:chunked header if Jetty omits this

docs-md/developer-guide/ksqldb-reference/scalar-functions.md, docs/developer-guide/syntax-reference.rst
docs for https://github.com/confluentinc/ksql/pull/4728
=> docs: add docs for REGEXP_EXTRACT function

ksqldb-docker/src/include/docker/run
Missed a spot in https://github.com/confluentinc/ksql/pull/4799
Verified the server actually starts this time, not just that logging is working 🤦‍♀
=> chore: rename config directory to ksqldb (again)

ksqldb-common/src/main/java/io/confluent/ksql/name/ColumnName.java, ksqldb-common/src/main/java/io/confluent/ksql/name/ColumnNames.java, ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/AggregateExpressionRewriter.java, ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/AstSanitizer.java, ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java, ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java, ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/FlatMapNode.java, ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java, ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/AggregateParamsFactory.java, ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamFlatMapBuilder.java, ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/AggregateParamsFactoryTest.java, ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StepSchemaResolverTest.java
In prep for extending what the new class does.
non-functional chnge.
=> refactor: move special ColumnName creation into util (MINOR)

ksqldb-rocksdb-config-setter/pom.xml, ksqldb-udf-quickstart/README.md, ksqldb-udf-quickstart/pom.xml, ksqldb-udf-quickstart/src/main/resources/archetype-resources/pom.xml
A few trailing rebranch changes...
=> chore: few rebranch changes

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
Adds some log messages when the command runner exits.
=> chore: add log msgs when the command runner exits

ksqldb-common/src/main/java/io/confluent/ksql/json/KsqlTypesSerializationModule.java, ksqldb-common/src/main/java/io/confluent/ksql/json/SqlTypeSchemaSerializer.java, ksqldb-engine/src/test/java/io/confluent/ksql/execution/json/PlanJsonMapperTest.java, ksqldb-parser/src/main/java/io/confluent/ksql/parser/json/KsqlTypesDeserializationModule.java, ksqldb-parser/src/main/java/io/confluent/ksql/parser/json/SqlTypeDeserializer.java, ksqldb-parser/src/test/java/io/confluent/ksql/parser/json/KsqlTypesSerdeModuleTest.java
=> fix: add deserializer for SqlType

ksqldb-common/src/main/java/io/confluent/ksql/json/KsqlTypesSerializationModule.java, ksqldb-common/src/main/java/io/confluent/ksql/json/SqlTypeSchemaSerializer.java, ksqldb-engine/src/test/java/io/confluent/ksql/execution/json/PlanJsonMapperTest.java, ksqldb-parser/src/main/java/io/confluent/ksql/parser/json/KsqlTypesDeserializationModule.java, ksqldb-parser/src/main/java/io/confluent/ksql/parser/json/SqlTypeDeserializer.java, ksqldb-parser/src/test/java/io/confluent/ksql/parser/json/KsqlTypesSerdeModuleTest.java
Cherry-pick https://github.com/confluentinc/ksql/pull/4830 into `0.8.x-ksqldb`
=> fix: add deserializer for SqlType (0.8.x-ksqldb)

CHANGELOG.md
Add additional fix picked up in 0.8.0 to the changelog.
=> docs: additional fix in 0.8.0 changelog (MINOR)

build-tools/pom.xml, ksql-api-reactive-streams-tck/pom.xml, ksql-benchmark/pom.xml, ksql-cli/pom.xml, ksql-common/pom.xml, ksql-console-scripts/pom.xml, ksql-docker/pom.xml, ksql-engine/pom.xml, ksql-etc/pom.xml, ksql-examples/pom.xml, ksql-execution/pom.xml, ksql-functional-tests/pom.xml, ksql-metastore/pom.xml, ksql-package/pom.xml, ksql-parser/pom.xml, ksql-rest-app/pom.xml, ksql-rest-client/pom.xml, ksql-rest-model/pom.xml, ksql-rocksdb-config-setter/pom.xml, ksql-serde/pom.xml, ksql-streams/pom.xml, ksql-test-util/pom.xml, ksql-tools/pom.xml, ksql-udf-quickstart/pom.xml, ksql-udf/pom.xml, ksql-version-metrics-client/pom.xml, pom.xml
=> bump hotfix version

docs-md/developer-guide/ksqldb-reference/scalar-functions.md
Change #4105 split ARRAYCONTAINS into ARRAY_CONTAINS and JSON_ARRAY_CONTAINS, but looks like the docs weren't updated...
=> docs: update ARRAY_CONTAINS docs

ksql-engine/pom.xml, ksql-version-metrics-client/pom.xml, pom.xml
Forgot to do this in https://github.com/confluentinc/ksql/pull/4871
=> chore: re-enable fail on warnings

Jenkinsfile
Bump version to 0.8.1 for the next patch release.
=> chore: bump ksqlDB version to 0.8.1

ksqldb-common/src/main/java/io/confluent/ksql/util/RetryUtil.java, ksqldb-common/src/test/java/io/confluent/ksql/util/RetryUtilTest.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
This is a followup to comments in PR #4889 
`mvn package`
=> refactor: Followup comments to PR 4889

ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
=> fix: logic when closing ksqlEngine fixed

docs-md/developer-guide/ksqldb-reference/print.md
Cherry-pick https://github.com/confluentinc/ksql/pull/4919.
=> docs: fix link to schema topic (DOCS-3784)

CHANGELOG.md
=> docs: add changelog for 0.8.1 release

ksql-common/src/main/java/io/confluent/ksql/util/timestamp/StringToTimestampParser.java, ksql-common/src/test/java/io/confluent/ksql/util/timestamp/StringToTimestampParserTest.java
fixes #4864, in a localized way, added a unit test case
Backporting fix from master
=> fix: handle leap days correctly during timestamp extraction (#4878)

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java, ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java, ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStoreTest.java
=> fix: Don't wait for streams thread to be in running state (#4908)

docs-md/faq.md, docs-md/operate-and-deploy/installation/installing.md, docs-md/operate-and-deploy/installation/server-config/config-reference.md, docs-md/operate-and-deploy/installation/server-config/integrate-ksql-with-confluent-control-center.md, docs-md/operate-and-deploy/installation/server-config/security.md, docs/installation/index.rst
URL is changing on docs.confluent.io so these docs must be updated. 
- merge along with related https://github.com/confluentinc/docs/pull/4128
=> DOCS-3736 - Change URL to KSQL cloud docs

ksqldb-common/src/test/java/io/confluent/ksql/util/KsqlRequestConfigTest.java
=> chore: correct improperly named test file

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
(this comment also fixes an `afterRun` bug)
OK I figured out what’s going on here - there’s a race condition in connect (kind-of) between creation of the connector and creating the tasks. In other words, it’s possible for us to have created the connector but for the tasks not to be created - the line where the backing store is updated is AbstractHerder:166
```
statusBackingStore.put(new TaskStatus(id, TaskStatus.State.RUNNING, workerId, generation()));
```
In this line I added a breakpoint with an evaluate-and-log `Thread.sleep(100)` to introduce a little delay to that function but without suspending the execution of the test. This caused the test to fail 100% of the time with the same error. Disabling this breakpoint allows the test to succeed nearly every time.
After this change was in, …
=> test: add eventually to fix flaky connect integration test

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorMetrics.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorMetricsTest.java
=> fix: When pull query metrics enabled, throws NPE

docs-md/operate-and-deploy/installation/install-ksqldb-with-docker.md, docs-md/operate-and-deploy/installation/installing.md, docs-md/tutorials/basics-docker.md, docs-md/tutorials/clickstream-docker.md, docs-md/tutorials/index.md, docs/includes/ksql-includes.rst, ksqldb-common/src/main/java/io/confluent/ksql/util/WelcomeMsgUtils.java, ksqldb-common/src/test/java/io/confluent/ksql/util/WelcomeMsgUtilsTest.java
=> chore: update copyright years for CLI (MINOR)

docs-md/developer-guide/syntax-reference.md
=> docs: fix STRUCT example in syntax-reference

docs-md/operate-and-deploy/installation/upgrading.md
=> docs: fix broken links in upgrade ksqlDB topic (DOCS-3844)

maven-settings-template.xml
It seems that we had a conflicts in the id of the repositories so it wasn't able to resolve all the dependencies. This fixes the issue.
Green build!
=> fix: change the repo id to fix the broken build

ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java, ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/QueriesTableBuilder.java, ksqldb-common/src/main/java/io/confluent/ksql/name/Name.java, ksqldb-common/src/main/java/io/confluent/ksql/query/QueryId.java, ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java, ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/context/QueryLoggerUtil.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
Removes an unused method from `Name` and a duplicate from `QueryId`
`mvn test`.
=> Remove unused / duplicate methods (MINOR)

design-proposals/klip-23-primary-keys-for-tables.md
KLIP for introducing PRIMARY KEY syntax.
It would be good to get this agreed and merged asap, as I'd like to get this in for the next release.
=> Klip 23 primary keys

docs-md/developer-guide/ksqldb-reference/aggregate-functions.md
Also fixes some in-page links.
=> docs: add TOC entry for LATEST_BY_OFFSET (DOCS-3901)

docs-md/requirements.txt
Cherry-pick from https://github.com/confluentinc/ksql/pull/5038.
=> docs: update requirement for new mkdocs version (DOCS-3903)

docs-md/requirements.txt
Try to force newest versions in the RTD build env.
=> docs: hail mary to fix broken docs build (DOCS-3905)

ksqldb-examples/src/main/java/io/confluent/ksql/datagen/DataGenProducer.java
Fixed a small nit for message formatting.
Very minor change
It would be really helpful if we could also include the list of available fields. e.g. `Key field does not exist: id. Available fields are a, b and c.`
=> chore: adds missing space for field key.

docs-md/requirements.txt, mkdocs.yml
Fixes breakage upgrading to Material v5.
=> docs: fix breaking changes to upgrade to Material 5

docs-md/requirements.txt, mkdocs.yml
from https://github.com/confluentinc/ksql/pull/5045.
* docs: fix breaking changes to upgrade to Material 5
* docs: fix upgrade
=> docs: cherry-pick fix breaking changes to upgrade to Material 5

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java, ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java, ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/ImmutableAnalysis.java, ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/PushQueryValidator.java, ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/QueryAnalyzer.java, ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/RewrittenAnalysis.java, ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/AstSanitizer.java, ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/DataSourceExtractor.java, ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/StatementRewriter.java, ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java, ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/PushQueryValidatorTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/DataSourceExtractorTest.java, ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json, ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java, ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultTraversalVisitor.java, ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java, ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java, ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/JoinedSource.java, ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java, ksqldb-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java, ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/JoinMatchers.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
Gets us one step closer to multi-way joins by adding support in the analysis phase. I moved the failure to the Logical Planner if you try to multi-way join (see the QTT test)
=> chore: add analysis/formatting around multi-way joins

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/ServerUtil.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ServerUtilTest.java
=> fix: allow trailing slash in listeners config (MINOR) (#5012)

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PreconditionFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestAppWaitingOnPrecondition.java
Same as https://github.com/confluentinc/ksql/pull/5047 (re-opened a new PR because of a GitHub mishap).
Same.
=> fix: make endpoints available while waiting for precondition

docs-md/tutorials/etl.md, docs-md/tutorials/materialized.md
Fixes a few issues referencing Debezium in the tutorials.
=> docs: fixes to Debezium

docs-md/tutorials/etl.md, docs-md/tutorials/materialized.md
from https://github.com/confluentinc/ksql/pull/5082
=> docs: cherry-pick fixes to Debezium topic

docs-md/developer-guide/joins/join-streams-and-tables.md
fixes #5071 - @JimGalasyn I'd love to have your opinion on the structure of this and the value of the content.
n/a
=> docs: n-way join docs

docs-md/operate-and-deploy/installation/commandTopicConsumer.py, docs-md/operate-and-deploy/installation/upgrading.md
From https://github.com/confluentinc/ksql/pull/5088
=> docs: cherry-pick script for dumping ksqlDB command topic (DOCS-4063)

docs-md/tutorials/etl.md
From https://github.com/confluentinc/ksql/pull/5085.
=> docs: cherry pick link to Debezium's MongoDB docs to live branch

Jenkinsfile
We are upgrading twist lock and they did a rebranding so the name of the commands we use in the jenkins plugin has changed. They also deprecated some options which I have removed. I will merge this PR during our maintenance window when we upgrade TwistLock on April 17th.
I will test this out to make sure it works during the maintenance period.
=> build: ST-3567: Refactor TwistLock scan commands to work with new version of plugin

ksqldb-benchmark/src/main/resources/log4j.properties, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestLoader.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestPath.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestRewriterTest.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanLoader.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanWriter.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/HistoricalTestingFunctionalTest.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorTest.java, ksqldb-functional-tests/src/test/resources/qtt_test_cases/correct/simple/6.0.0_1585182026527/plan.json, ksqldb-functional-tests/src/test/resources/qtt_test_cases/correct/simple/6.0.0_1585182026527/spec.json, ksqldb-functional-tests/src/test/resources/qtt_test_cases/correct/simple/6.0.0_1585182026527/topology, ksqldb-functional-tests/src/test/resources/qtt_test_cases/incorrect/topology_mismatch/6.0.0_1585182026527/plan.json, ksqldb-functional-tests/src/test/resources/qtt_test_cases/incorrect/topology_mismatch/6.0.0_1585182026527/spec.json, ksqldb-functional-tests/src/test/resources/qtt_test_cases/incorrect/topology_mismatch/6.0.0_1585182026527/topology, ksqldb-functional-tests/src/test/resources/qtt_test_cases/incorrect/value_schema_mismatch/6.0.0_1585182026527/plan.json, ksqldb-functional-tests/src/test/resources/qtt_test_cases/incorrect/value_schema_mismatch/6.0.0_1585182026527/spec.json, ksqldb-functional-tests/src/test/resources/qtt_test_cases/incorrect/value_schema_mismatch/6.0.0_1585182026527/topology, ksqldb-test-util/src/main/resources/log4j.properties
Add some tests around running of historic tests case.
usual.
=> test: Historic qtt

.readthedocs.yml
From https://github.com/confluentinc/ksql/pull/5131.
=> docs: cherry-pick .readthedocs.yml update to live branch (DOCS-4110)

docs-md/js/extra.js, docs-md/stylesheets/extra.css, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5022.
=> docs: cherry-pick version picker to 0.7.1-ksqldb branch (DOCS-4111)

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutor.java
Remove use of `Future` from code in favor of `CompletableFuture`
tests still pass
verified locally functionality still works
=> refactor: scatterGather now uses CompletableFuture

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/KsqlServerEndpoints.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/KsqlStatementsEndpoint.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/OldQueryEndpoint.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/TerminateEndpoint.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PortedEndpoints.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/EndpointResponse.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ServerInfoResource.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
This is a stacked PR, please only review the top commit(s)
Migrates the /info endpoint from Jetty to Vert.x
However I added an integration test as there wasn't one.
=> refactor: Migrate /info endpoint

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/KsqlServerEndpoints.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PortedEndpoints.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/LagReportingResource.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
This is a stacked PR. Please only review the top commit(s).
This PR migrates the /lag endpoint from Jetty to Vert.x
=> refactor: Migrate /lag endpoint to Vert.x

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/KsqlServerEndpoints.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PortedEndpoints.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/filters/KsqlAuthorizationFilter.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/HealthCheckResource.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
This is a stacked PR. Please only review the top commit(s).
This PR migrates the /healthcheck endpoint to Vert.x
=> refactor: Migrate healthcheck

ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java, ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java, ksqldb-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
=> fix: support quotes in explain statements (MINOR)

docs-md/js/extra.js
From https://github.com/confluentinc/ksql/pull/5152.
=> docs: cherry-pick fix for version picker for previous versions

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java, ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java, ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/ColumnReferenceValidator.java, ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/AstSanitizer.java, ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/ExpressionTreeRewriter.java, ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/ExpressionVisitor.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/TraversalExpressionVisitor.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/UnqualifiedColumnReferenceExp.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/VisitParentExpressionVisitor.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
Rename of method inline with naming pattern.
none
=> chore: correct method name (MINOR)

docs/developer-guide/create-a-stream.md
From https://github.com/confluentinc/ksql/pull/5171.
=> docs: cherry-pick: remove extraneous EMIT CHANGES clauses (DOCS-4159)

docs/concepts/schemas.md, docs/developer-guide/query-with-structured-data.md, docs/developer-guide/serialization.md, docs/developer-guide/test-and-debug/processing-log.md
From https://github.com/confluentinc/ksql/pull/5176.
=> docs: cherry-pick: remove TODO from Serialization topic (DOCS-4162)

docs/tutorials/etl.md, docs/tutorials/event-driven-microservice.md, docs/tutorials/materialized.md
Adds links to try other tutorials when you get to the end of one.
=> docs: cta for trying other tutorials

docs-md/concepts/ksqldb-and-kafka-streams.md, docs-md/concepts/schemas.md, docs-md/developer-guide/create-a-stream.md, docs-md/developer-guide/create-a-table.md, docs-md/developer-guide/ksqldb-reference/create-stream-as-select.md, docs-md/developer-guide/ksqldb-reference/create-stream.md, docs-md/developer-guide/ksqldb-reference/create-table-as-select.md, docs-md/developer-guide/ksqldb-reference/create-table.md, docs-md/developer-guide/ksqldb-reference/drop-stream.md, docs-md/developer-guide/ksqldb-reference/drop-table.md, docs-md/developer-guide/ksqldb-reference/scalar-functions.md, docs-md/developer-guide/ksqldb-rest-api/ksql-endpoint.md, docs-md/developer-guide/serialization.md, docs-md/developer-guide/syntax-reference.md, docs-md/faq.md, docs-md/operate-and-deploy/installation/installing.md, docs-md/operate-and-deploy/installation/server-config/avro-schema.md, docs-md/operate-and-deploy/installation/server-config/config-reference.md, docs-md/operate-and-deploy/installation/server-config/index.md, docs-md/tutorials/basics-docker.md, docs-md/tutorials/embedded-connect.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/4786.
* docs: update ksqlDB docs for Protobuf support (DOCS-3559)
* docs: add JSON_SR to lists and add a note  (DOCS-3559)
=> docs: cherry-pick update to ksqlDB docs for Protobuf support (DOCS-4167)

docs/concepts/functions.md, docs/developer-guide/implement-a-udf.md
From https://github.com/confluentinc/ksql/pull/5182.
=> docs: cheryy-pick: update ksql-udf references to ksqldb-udf (DOCS-3818)

docs/concepts/functions.md, docs/developer-guide/implement-a-udf.md
From https://github.com/confluentinc/ksql/pull/5184.
=> docs: cherry-pick: use CP version for ksqldb UDF artifacts (DOCS-3818)

docs/concepts/functions.md, docs/developer-guide/implement-a-udf.md
From https://github.com/confluentinc/ksql/pull/5186.
=> docs: cherry-pick: update site.cprelease references (DOCS-3818)

ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json
Moving multi-joins.json QTT test aware from ROWKEY naming. (Prep to minimise diff of following change).
=> chore: rename columns in multi-joins.json (MINOR)

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
Fixes flaky test due to race condition by asserting eventually.
Ran the test many times.
=> test: add assert eventually to flaky conenct integration test

docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/serialization.md, docs/developer-guide/syntax-reference.md, docs/faq.md, docs/operate-and-deploy/installation/server-config/avro-schema.md, docs/operate-and-deploy/installation/server-config/config-reference.md, docs/operate-and-deploy/installation/server-config/index.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5207.
=> docs: cherry-pick: add JSON_SR parity in ksqlDB docs (DOCS-3783)

docs/requirements.txt
Possibly fixes scroll jitter behavior seen in search.
=> docs: upgrade mkdocs to ease scroll jitter

docs/requirements.txt
From https://github.com/confluentinc/ksql/pull/5210.
=> docs: cherry pick: upgrade mkdocs to ease scroll jitter (DOCS-4206)

ksqldb-common/src/main/java/io/confluent/ksql/function/types/ParamTypes.java, ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java, ksqldb-common/src/test/java/io/confluent/ksql/util/DecimalUtilTest.java
Fix compilation error introduced in PR #5158
=> chore: fix compilation errors

ksqldb-rest-app/pom.xml, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/utils/KsqlPlanSchemaGenerator.java
Use sr's jackson-jsonschema version. Hard-code this for now to un-break build. Doing a follow-up
to move this to common or rest-utils.
=> fix: use sr's jackson-jsonschema version

docs/README.md
The docs/README.md instructions for building the docs locally don't quite work since the mkdocs.yml file is in the root directory rather than the docs folder. This PR updates the README instructions accordingly.
Built docs locally.
=> docs: update build instructions in docs/README.md (MINOR)

design-proposals/README.md
I'm planning to copy the proposed Java client interfaces in https://github.com/confluentinc/ksql/pull/5200 into a KLIP in order to get into the habit of introducing/updating public APIs via KLIPs.
=> docs: intent for klip-26: Java client interfaces

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PortedEndpoints.java
This PR adds some extra logging to help diagnose API call failures.
N/A
=> chore: added some extra logging on API failure

ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java, pom.xml
Woohoo! My bug report (https://unicode-org.atlassian.net/browse/CLDR-13549) was fixed and released, removing the hack here.
Ran the tests
=> chore: update ICU version for NumberFormatter fix

Jenkinsfile
We are migrating all of the credentials stored in Jenkins to Vault. This refactoring will now access the credentials from Vault. This does not include all of the credentials used by this script. Another PR will address the remaining credentials.
=> build: ST-3402: Refactored Jenkinsfile to get secrets from Vault instead of Jenkins credential store

docs/developer-guide/ksqldb-reference/scalar-functions.md, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/array/ArrayLength.java, ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/array/ArrayLengthTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_primitives/5.5.0_1587465836260/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_primitives/5.5.0_1587465836260/topology, ksqldb-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_structured/5.5.0_1587465836400/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_structured/5.5.0_1587465836400/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/array.json
From https://github.com/confluentinc/ksql/pull/5124.
=> docs: cherry-pick: backport array length UDF to 0.8.1-ksqldb (DOCS-4247)

docs/developer-guide/ksqldb-reference/scalar-functions.md, ksql-engine/src/main/java/io/confluent/ksql/function/udf/array/ArrayLength.java, ksql-engine/src/test/java/io/confluent/ksql/function/udf/array/ArrayLengthTest.java, ksql-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_primitives/5.5.0_1587465836260/spec.json, ksql-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_primitives/5.5.0_1587465836260/topology, ksql-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_structured/5.5.0_1587465836400/spec.json, ksql-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_structured/5.5.0_1587465836400/topology, ksql-functional-tests/src/test/resources/query-validation-tests/array.json
From https://github.com/confluentinc/ksql/pull/5124.
=> docs: cherry-pick: backport array length UDF to 0.7.1-ksqldb (DOCS-4247)

.env, docker-compose.yml, docs/concepts/ksqldb-architecture.md, down, ksqldb-docker/README.md, up
Commit adds utility `up` script to bring up docker images, wait for ksql to be responsive, and then load the cli.  `down` to bring everything down again.
`.env` file added with environment vars for setting docker version.
updated some outdated links too.
=> testing: updated docker-compose.yml (MINOR)

docs/developer-guide/serialization.md
Fixes documentation bug described in #5219.
=> docs: move protobuf to correct section

docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/5267.
=> docs: cherry-pick: move protobuf to correct section (DOCS-4215)

docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/5267.
=> docs: cherry-pick: move protobuf to correct section

docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/5222.
=> docs: cherry-pick update to serialization topic (DOCS-4215)

docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/5280.
=> docs: cherry-pick update to serialization topic (DOCS-4215) (#5280)

CONTRIBUTING.md, ksqldb-benchmark/src/main/resources/log4j.properties, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java, ksqldb-functional-tests/src/test/resources/query-validation-tests/null.json, ksqldb-test-util/src/main/resources/log4j.properties
This PR:
- Updates `CONTRIBUTING.md` to highlight the need for a KLIP for syntax changes, (as requested by @apurvam).
- Stops some spam logging in tests.
- Adds a test around nulls in join criteria.
=> chore: update CONTRIBUTING.md and others (MINOR)

docs/developer-guide/ksqldb-reference/create-table.md
From https://github.com/confluentinc/ksql/pull/5229.
=> docs: cherry pick: fix statement about key requirement in CREATE TABLE (DOCS-4268)

docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md
From https://github.com/confluentinc/ksql/pull/4191.
=> docs: cherry-pick: undocumented properties in ksql-endpoint (DOCS-4271)

docs/concepts/functions.md, docs/developer-guide/implement-a-udf.md
From https://github.com/confluentinc/ksql/pull/5182 and https://github.com/confluentinc/ksql/pull/5186.
=> docs: cherry pick: update ksql-udf references (DOCS-4273)

Jenkinsfile
We have a new helper method in jenkins-common, withVaultEnv, to make it easier to get secrets from Vault and set them as environment variables. I am just replacing the old code to use this new method.
=> build: ST-3402: Refactor jenkinsfile to use new helper method to get secrets from Vault

mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5309.
=> docs: cherry-pick: update copyright date to 2020 (DOCS-4283)

mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5309.
=> docs: update copyright date to 2020 (DOCS-4284)

docs/operate-and-deploy/installation/server-config/security.md
Fixes https://github.com/confluentinc/ksql/issues/5254
This docs change needs to be ported to the `0.9.x-ksqldb` once merged (cc @JimGalasyn -- thank you!).
Local verification of the new steps.
=> docs: fix basic auth docs example to pass required jar

docs/operate-and-deploy/installation/server-config/security.md
From https://github.com/confluentinc/ksql/pull/5307.
=> docs: cherry-pick: fix basic auth docs example to pass required jar

docs/README.md
From https://github.com/confluentinc/ksql/pull/5230.
=> docs: cherry-pick: update build instructions in docs/README.md (MINOR) (DOCS-4297)

docs/README.md
From https://github.com/confluentinc/ksql/pull/5230.
=> docs: update build instructions in docs/README.md (MINOR) (#5230)

docs/overrides/partials/integrations/analytics.html, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5321.
=> docs: cherry-pick: use GTM for analytics (DOCS-4303)

docs/overrides/partials/integrations/analytics.html, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5321.
=> docs: cherry pick: use GTM for analytics (DOCS-4303)

docs/overrides/partials/integrations/analytics.html, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5321.
=> docs: use GTM for analytics (#5321)

.env, docker-compose.yml, docs/concepts/ksqldb-architecture.md, down, ksqldb-docker/README.md, up
From https://github.com/confluentinc/ksql/pull/5245.
=> docs: cherry-pick: updated docker-compose.yml (MINOR) (DOCS-4295)

design-proposals/README.md, design-proposals/klip-26-java-client-interfaces.md
Add KLIP-26: Java client interfaces.
=> docs: add KLIP-26: Java client interfaces

docs/tutorials/basics-docker.md
Corrected docker image names in docs.  Needs merging to 5.5.x and master @JimGalasyn (feel free to merge!)
=> docs: update docker images ksql->ksqlDB

Jenkinsfile
=> chore: bump ksqlDB version to 0.10.0

.env, docker-compose.yml, docs/concepts/ksqldb-architecture.md, down, ksqldb-docker/README.md, up
From https://github.com/confluentinc/ksql/pull/5245.
=> docs: cherry-pick: updated docker-compose.yml

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java, ksqldb-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java, ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java, ksqldb-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ExplainExecutor.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutor.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ExplainExecutorTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
Most places don't use the string representation but the actual error, so minor refactor here.
non-funcitonal
=> refactor: return State object from QueryMetadata (MINOR)

CHANGELOG.md
From https://github.com/confluentinc/ksql/pull/5349.
=> docs: cherry pick: add upgrade note at the top of changelog (DOCS-4359)

CHANGELOG.md
From https://github.com/confluentinc/ksql/pull/5361.
=> docs: cherry-pick: Fix broken link in changelog.md (DOCS-4370)

CHANGELOG.md
Reverts confluentinc/ksql#5362
Accidentally went too far with MyPintMerge.
=> Revert "docs: cherry-pick: Fix broken link in changelog.md (DOCS-4370)"

CHANGELOG.md
Related to https://github.com/confluentinc/ksql/pull/5361.
=> docs: fix broken link in changelog.md (DOCS-4369)

ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java, ksqldb-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java, ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/5.5.0_1581572086154/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1585182000596/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1585912758104/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1588893905811/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/5.5.0_1581572086189/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1585182000661/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1585912758148/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1588893905952/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/5.5.0_1581572086226/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1585182000710/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1585912758193/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1588893906070/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1583419431528/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1588893908853/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_table_to_table_wrapped_single_field_value_schema_on_inputs/5.5.0_1581572097364/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_table_to_table_wrapped_single_field_value_schema_on_inputs/6.0.0_1588893930352/spec.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/collect-list.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/decimal.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/table.json, ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonSerializerTest.java, pom.xml
- Reapplies #5339 
- Fix warnings
=> Retry 6.0.x

docs/tutorials/embedded-connect.md, docs/tutorials/etl.md, docs/tutorials/materialized.md
Fixes issues with using embedded confluent-hub after 0.9.0's change to UBI.
=> docs: fixes breakage from confluent-hub

ksqldb-rest-app/pom.xml
We have updated kafka scala version to scala 2.13.  This PR to update mbknor-jackson-jsonschema jar to 2.13 compiled version.
=> MINOR: Update mbknor-jackson-jsonschema_2.12 artifact to mbknor-jackson-jsonschema_2.13

ksqldb-rest-app/pom.xml
=> MINOR: Use kafka.scala.version variable in pom file

docs/requirements.txt
From https://github.com/confluentinc/ksql/pull/5403.
=> docs: cherry-pick: update requirements in ksqlDB docs build (DOCS-4397)

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/StreamedQueryResultImplTest.java
One of our builds saw `StreamedQueryResultImplTest#shouldAllowSubscribeIfComplete()` fail with
```
Wanted but not invoked:
subscriber.onNext(row);
-> at io.confluent.ksql.api.client.impl.StreamedQueryResultImplTest.shouldAllowSubscribeIfComplete(StreamedQueryResultImplTest.java:195)
However, there was exactly 1 interaction with this mock:
subscriber.onSubscribe(
io.confluent.ksql.reactive.BasePublisher$Sub@6342d610
);
-> at io.confluent.ksql.reactive.BasePublisher.doSubscribe(BasePublisher.java:160)
```
which happened because after `subscription.request(1);` is called, the call to `onNext()` (which is verified) is async. This PR fixes the flaky test by having the assertion wait for `onNext()` to be called, rather than immediately checking whether `onNext()` has been called or not. …
=> test: fix flaky client test (MINOR)

docs/requirements.txt
From https://github.com/confluentinc/ksql/pull/5414.
=> docs: cherry-pick: Pin requirements in ksqlDB doc build (DOCS-4410)

docs/developer-guide/ksqldb-reference/select-push-query.md
System generated column aliases are now guaranteed to be unique.
Also raised https://github.com/confluentinc/ksql/issues/5428 while in the file.
doc change.
=> docs: update docs around column aliasing

docs/developer-guide/ksqldb-reference/scalar-functions.md, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Instr.java, ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/InstrTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_just_substring_-_JSON/6.0.0_1589881226238/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_just_substring_-_JSON/6.0.0_1589881226238/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_just_substring_-_JSON/6.0.0_1589881226238/topology, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_negative_position_-_JSON/6.0.0_1589881226304/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_negative_position_-_JSON/6.0.0_1589881226304/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_negative_position_-_JSON/6.0.0_1589881226304/topology, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_negative_position_and_occurrence_-_JSON/6.0.0_1589881226321/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_negative_position_and_occurrence_-_JSON/6.0.0_1589881226321/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_negative_position_and_occurrence_-_JSON/6.0.0_1589881226321/topology, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_position_-_JSON/6.0.0_1589881226269/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_position_-_JSON/6.0.0_1589881226269/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_position_-_JSON/6.0.0_1589881226269/topology, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_position_and_occurrence_-_JSON/6.0.0_1589881226286/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_position_and_occurrence_-_JSON/6.0.0_1589881226286/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/instr_-_test_instr_with_position_and_occurrence_-_JSON/6.0.0_1589881226286/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/instr.json
Implements #881
This adds implementation of INSTR function as described in https://docs.oracle.com/database/121/SQLRF/functions089.htm#SQLRF00651 (reported in #881)
I have added unit tests and did manual testing.
Please note that I am looking for initial feedback only. I am aware that functional tests and documentation needs to be added.
=> feat: INSTR function #881

docs/developer-guide/ksqldb-reference/aggregate-functions.md
From https://github.com/confluentinc/ksql/pull/5441.
=> docs: cherry-pick: fix broken link in Aggregations topic (DOCS-4425)

docs/developer-guide/ksqldb-reference/aggregate-functions.md, docs/developer-guide/ksqldb-reference/scalar-functions.md, docs/developer-guide/ksqldb-reference/table-functions.md
From https://github.com/confluentinc/ksql/pull/5444.
=> docs: cherry-pick fix for function references markdown (DOCS-4428)

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/QueryTranslationTest.java
Adds a system property that can be set to run QTT without historical test plans, which can be useful during development.
test-only change.
=> test: support running QTT only against latest set of tests

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatter.java
fixes: https://github.com/confluentinc/ksql/issues/5458
See issue log for details.
usual + manual
=> fix: avoid unnecessary warnings from PRINT

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
A bad merge with master in https://github.com/confluentinc/ksql/pull/5456 means an unused method that was previously removed slipped back in. This PR removes it.
Tests pass.
=> chore: remove unused method (MINOR)

docs/developer-guide/joins/index.md, docs/developer-guide/joins/synthetic-keys.md
Adds a placeholder doc needed to create the link for https://github.com/confluentinc/ksql/issues/5466.
doc only change.
=> docs: add place holder for up-coming docs on synthetic join keys

ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_session_start_stream/6.0.0_1590180402882/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_session_start_stream/6.0.0_1590180402882/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_session_start_stream/6.0.0_1590180402882/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/session-windows.json
Test case from https://stackoverflow.com/questions/61961255/ksql-windowed-aggregation-stream
usual
=> test: add test showing how to create a stream of session start events

LICENSE-ConfluentCommunity
Tested installed jars by `mvn install` locally.
=> ST-1323: Add license file so sources get attached

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
Currently any errors in forwarding pull queries to other nodes are only logged at debug, and the exception is swallowed. This makes it hard to diagnose user issues.
=> fix: Improve pull query error logging

docs/developer-guide/ksqldb-reference/scalar-functions.md
Basically a cherry-pick scraped from https://github.com/confluentinc/ksql/pull/5444, with functions that were added later removed.
=> docs: fix TOC in ksqlDB scalar functions topic (DOCS-4456)

docs/index.md
Removes dated recommendation on deployment modes.
=> docs: remove outdated recommendation

pom.xml
First stage for #5483 - this allows us to use the `mvn versions:set-property` command in our build pipeline to change the snapshot repo when we publish build tags.
=> build: reference plugin URL as property (MINOR)
