docs/concepts.md

added persistent information for streams and table

added persistent information for streams and table

---

ksql-core/src/main/java/io/confluent/ksql/function/KsqlAggFunctionDeterminer.java
ksql-core/src/main/java/io/confluent/ksql/function/KsqlFunctions.java
ksql-core/src/main/java/io/confluent/ksql/metastore/MetastoreUtil.java
ksql-core/src/main/java/io/confluent/ksql/util/SchemaUtil.java

Made small code quality improvements.

Small code quality improvements

---

ksql-core/src/main/java/io/confluent/ksql/QueryEngine.java
ksql-core/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-core/src/main/java/io/confluent/ksql/structured/QueuedSchemaKStream.java
ksql-core/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-core/src/main/java/io/confluent/ksql/structured/SchemaKTable.java

simplfying code around pipeline queue for passing select results

Extracted Pipeline into QueuePopulatorSchema

---

config/ksqlserver.properties
ksql-cli/src/main/java/io/confluent/ksql/cli/StandaloneExecutor.java
ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java
ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClientImpl.java
ksql-engine/src/main/resources/log4j.properties
ksql-engine/src/test/java/io/confluent/ksql/IntegrationTestHarness.java
ksql-engine/src/test/java/io/confluent/ksql/StreamsSelectAndProjectIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integtests/json/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/OrderDataProvider.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
pom.xml

#340 - extracting KSQLContext and started refactoring integration tests

0.1.x [340] started integration test refactoring

---

config/ksqlserver.properties
ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JoinIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/StreamsSelectAndProjectIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/ItemDataProvider.java

#375 - adding missing integration tests

TEST: adding stream-table join

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java

moved duplicate exceptions to one function for consistency and easier changes ! :)

Moved duplicate exceptions to one function

---

ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-serde/src/main/java/io/confluent/ksql/serde/WindowedSerde.java

i must have stricter compiler defaults in my ide or something
@hjafarpour @dguy

fix bad serde package declaration

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-cli/src/main/java/io/confluent/ksql/cli/commands/Local.java
ksql-cli/src/main/java/io/confluent/ksql/cli/commands/Remote.java
ksql-cli/src/main/java/io/confluent/ksql/cli/commands/Standalone.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/util/CliUtils.java

fix various findbugs warnings in cli module #412

fix findbugs warning in cli

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java

fix various warnings in ksql-common #412

fix findbugs in ksql-common

---

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java

As we are not changing the key during select, there is no point in using `map`. Using `mapValues` will avoid a re-partitioning event if the resulting stream is joined.

use mapValues instead of map in SchemaKStream.select

---

pom.xml

confluent-common provides the configuration for checkstyle, so we don't need to add it as a build plugin. We keep the separate config for the suppressions

remove checkstlye build plugin as it is provided by the parent pom

---

docs/concepts.md
docs/quickstart/quickstart-non-docker.md
docs/syntax-reference.md

For example, clarify that the REST interface is not (yet) officially supported.

Clarify the deployment modes

---

ksql-cli/src/main/java/io/confluent/ksql/util/CliUtils.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionMetadata.java
ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGenProducer.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java

more findbugs warnings. After this there will still be a few left, but they probably can be suppressed. #412

fix more findbugs warnings

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/AnalysisContext.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/QueryAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/planner/DefaultTraversalVisitor.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/SqlFormatterQueryRewrite.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DefaultTraversalVisitor.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/QuerySpecification.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Table.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java

Extract `QueryAnalyzer` from `QueryEngine`.
Removed redundant usages of `Optional` from `QuerySpecification`

extract QueryAnalyzer from QueryEngine

---

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/AbstractCreateStreamCommand.java
ksql-engine/src/test/java/io/confluent/ksql/integration/DelimUdfIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JoinIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/StreamsSelectAndProjectIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
ksql-serde/src/main/java/io/confluent/ksql/serde/DataSource.java
ksql-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedDeserializer.java

#434 - to provide coverage and validation. Includes extending IntegrationTestHarness to support other Serdes

Delimited integration test

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClientImpl.java
ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/PageViewDataProvider.java
ksql-engine/src/test/java/io/confluent/ksql/util/UserDataProvider.java
ksql-engine/src/test/resources/log4j.properties

This patch covers all the queries in the quickstart, including the 'plain' select statements.
I have noticed that the join between the pageviews stream and the users table sometimes results in 'null' values for the columns in the users table. @hjafarpour thinks that this is because the rocksdb store isn't ready when the join is executed, resulting in an empty user table and null values for the corresponding fields in the join.

KSQL-398: integration test covering quickstart scenarios

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JoinIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java

When creating the execution plan in `StructuredDataSourceNode` we do a `stream#map(..)` to add the key to the `GenericRow`. This causes the `repartitionRequired` flag to be set to true even though we haven't changed the key. In this case we don't want a repartition as it is unnecessary and also causes issues with the stream/table join, i.e., we end up with nulls when we shouldn't. 
As a temporary workaround, we use reflection to reset the `repartitionRequired` flag on the `KStream` so that joins and aggregations won't require an additional repartitioning. This can be removed once KIP-159 is in as part of AK 1.1

reset repartition flag after map

---

ksql-cli/src/main/java/io/confluent/ksql/cli/RemoteCli.java
ksql-cli/src/main/java/io/confluent/ksql/cli/commands/Remote.java
ksql-cli/src/test/java/io/confluent/ksql/cli/commands/RemoteTest.java
ksql-cli/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java

This patch adds the ability for the remote CLI to do basic http authentication with the KSQL server. The server side simply needs to be configured to support basic auth -- the code is already there.
There are some improvements we _should_ make: 
1. Currently, the username _and_ password can only be specified by the `--user` and `--password` cli arguments in remote mode.  We should add the option for entering the password on the cli and hiding the characters typed for additional security. This may be a nontrivial amount of additional work with the current code base though.
2. The password thus entered is sent to the server on an unsecure connection in plain text. We should use SSL for the connection, but that requires broader changes.
I see this is a first step toward basic security and …

Added basic auth capabilities to KSQL Remote cli

---

ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClientImpl.java

When we are about to create a topic and it already exists we should accept a replication factor that is >= the replication factor in config

change replication factor check when creating topics

---

ksql-cli/src/main/java/io/confluent/ksql/cli/commands/Remote.java

This patch hides the `--username` and `--password` cli flags since the server side auth components are not generally available. All the functionality is still available, but these flags will not be listed in the `help` commands of the CLI.

Hide user name and password command line flags 

---

ksql-cli/src/test/java/io/confluent/ksql/TestRunner.java

The `CliTest` still fails. This patch adds logging so that we know the actual results we got when it fails. It could be that no results are ever returned, or it could be that there is another error and error strings are returned. This patch will learn the cause of the failures.

Add list of actual results to CLITest output when it fails

---

ksql-cli/src/main/java/io/confluent/ksql/cli/StandaloneExecutor.java
ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java
ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java

The app id for persistent queries shouldn't have a time stamp suffix applied otherwise it will result in different app ids across different servers.

fix regression in app id creation

---

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/BrokerCompatibilityCheck.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/BrokerCompatibilityCheckTest.java

Add a `BrokerCompatibilityCheck` that will run when the app starts and throw an exception if the brokers aren't of a compatible version

add broker compatibility check

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommands.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RestoreCommandsTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java

When reading the previous command from the command topic also collect the terminated queryIds such that any query that has been terminated will not be re-run. It will still have its data in the metastore so that any dependent queries can reference it #482

Don't run terminated queries at startup #482

---

ksql-cli/src/main/java/io/confluent/ksql/Ksql.java
ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-cli/src/main/java/io/confluent/ksql/cli/RemoteCli.java
ksql-cli/src/main/java/io/confluent/ksql/cli/commands/AbstractCliCommands.java
ksql-cli/src/main/java/io/confluent/ksql/util/CliUtils.java
ksql-cli/src/test/java/io/confluent/ksql/util/CliUtilsTest.java
ksql-common/src/main/java/io/confluent/ksql/util/CommonUtils.java
ksql-common/src/test/java/io/confluent/ksql/util/CommonUtilsTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/exception/KsqlRestClientException.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/ErrorMessage.java

The goal here is to provide more useful error messaging
in the cli. This includes more informative messages for certain
errors, and leveraging exception causes to provide more info:
* Add a CommonUtils class for common utility methods. Currently,
this includes methods for printing error messages that can
include information about the errors/exceptions that caused
the exception for which a message is being generated.
* Print a more visible warning if the ksql server cannot be
contacted when the cli is started in remote mode.
* Wrap rest client errors in a new exception class
KsqlRestClientException, and provide a more context-specific error
message.

Print more informative error messages

---

ksql-common/src/main/java/io/confluent/ksql/metrics/ConsumerCollector.java
ksql-common/src/main/java/io/confluent/ksql/metrics/MetricCollector.java
ksql-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java
ksql-common/src/main/java/io/confluent/ksql/metrics/ProducerCollector.java
ksql-common/src/test/java/io/confluent/ksql/metrics/MetricCollectorsTest.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java

This is a first in a series of PRs to add operability metrics to ksql. After this PR, I plan on adding metrics for reporting the relative activity of various queries, the aggregate error rate, and the total throughput across all streams in the system.
Note that there are concurrency issues when reading the `size` of the various structures which track the present queries. This may lead to incorrect readings some of the time, but won't violate the integrity of the system. I think this is preferable to adding excessive synchronization.

Add metrics which report the number of running queries

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommands.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RestoreCommandsTest.java

During startup when reading and executing the prior commands we need to update the metastore for tables/streams that are subsequently dropped so that dependent commands can also execute, i.e. if we have
create stream s1 as select ...
create stream s2 as select * from s1
terminate query 'csas_s1'
drop s1
when we restart we should still have s2 running
#531

don't execute dropped streams/tables, but update metastore

---

docs/quickstart/README.md
docs/quickstart/docker-compose.yml
docs/quickstart/quickstart-non-docker.md

Updated the docs based on the new query id format.

Fixed minor style issues in the docs.

---

docs/quickstart/quickstart-docker.md
ksql-cli/src/main/java/io/confluent/ksql/cli/commands/Local.java

With this patch, we can use schema registry in the quickstart docker images. We would need to update the https://github.com/confluentinc/ksql/blob/master/docs/quickstart/quickstart-docker.md so that we update the `exec` command to:
```
docker-compose exec ksql-cli ksql-cli local --bootstrap-server kafka:29092 --schema-registry-url schema-registry:8081
```

Add ability to specify the schema registry url to the CLI in local mode.

---

docs/examples.md

See individual commits for changes.

Minor docs improvements

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java

Close QueryMetadata objects created during ddl verification.
This in turn closes KafkaStreams, which *should* stop the
producer thread. This is currently not happening due to:
https://issues.apache.org/jira/browse/KAFKA-6383
There is a PR open to fix that issue:
https://github.com/apache/kafka/pull/4343

KSQL-493: Fix producer thread leak

---

ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java

`BaseMetricsReporter` was refactored and therefore we need to update `KsqlVersionChecker` to be compatible with the new version of `KsqlVersionChecker`.

Fixed the issue with BaseMetricsReporter.

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockApplication.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockStreamedQueryResource.java

KSQL-235: dont block on socket read
Avoid blocking on socket reads from the cli when
streaming a query response. The read cannot be interrupted,
so the user cannot abort the query via ctl-c until then next
response chunk arrives. Instead, have read poll the input
stream periodically and sleep interruptably between poll
attempts.

KSQL-235:  dont block on socket read

---

ksql-engine/src/main/java/io/confluent/ksql/util/SerDeUtil.java
ksql-engine/src/test/java/io/confluent/ksql/util/SerDeUtilTest.java

With this PR KSQL will be able to handle union field types that were generated by connect for nullable fields. For instance, here is an example of the type connect creates:
"name": "table",
"type": [
"null",
"string"
],
KSQL will use `string` as the type of this field.

Support avro types for nullable fields  generated by Connect.

---

ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java
ksql-engine/src/main/java/io/confluent/ksql/util/GenericRowValueTypeEnforcer.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionTypeManagerTest.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetastoreUtil.java
ksql-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerializer.java

This PR will unify schema checking and uses schema type in all places that we compare schemas.

Refactoring to use schema type for comparison.

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-cli/src/test/java/io/confluent/ksql/TestResult.java
ksql-cli/src/test/java/io/confluent/ksql/TestRunner.java
ksql-cli/src/test/java/io/confluent/ksql/TestTerminal.java

The isReady method of the InputStreamReader used to poll the
input stream for transient queries never gives any indication
that socket was closed by the remote server. Since stream queries
only terminate on error from the server or client side abort,
look out for an error row and stop processing the query when
one is received.

Fix queries with limit

---

bin/ksql-print-metrics
ksql-tools/pom.xml
ksql-tools/src/assembly/development.xml
ksql-tools/src/assembly/package.xml
ksql-tools/src/assembly/standalone.xml
ksql-tools/src/main/java/io/confluent/ksql/tools/PrintMetrics.java
ksql-tools/src/main/java/io/confluent/ksql/tools/printmetrics/ArgumentParseException.java
ksql-tools/src/main/java/io/confluent/ksql/tools/printmetrics/PrintMetrics.java
ksql-tools/src/main/java/io/confluent/ksql/tools/printmetrics/PrintMetricsException.java
pom.xml

Add a module for ksql command line tools. Include a tool for
printing ksql metrics exposed as mbeans.

Add ksql-tools

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java

Combine variable declartion and intiaztiona together.

[Minor] Fix Variable initialization

---

ksql-examples/src/main/java/io/confluent/avro/random/generator/Generator.java
ksql-examples/src/main/resources/inventory.avro
ksql-examples/src/main/resources/product.avro
ksql-examples/src/main/resources/purchase.avro

update datagen so iteration works properly and add schemas to use for testing

---

ksql-engine/src/main/java/io/confluent/ksql/function/udf/json/JsonExtractStringKudf.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java

Allows access to retrieval of JSON node when in array or complex nested objects.
```
CREATE STREAM sample_2 AS SELECT EXTRACTJSONFIELD(message, '$.log.logs[0].entry') FROM sample;
```
Previously the above query returned null because [jsonNode](https://fasterxml.github.io/jackson-databind/javadoc/2.4/com/fasterxml/jackson/databind/JsonNode.html#get(int)) would only access an index of an array node when using an `int` which was not being catered for in the current release.
Two tests have been updated to check this change both "tokenises" correctly using an array accessor and that it integrates into the jsonFormatTest when used in an actual query.

[BUG] jsonNode array index access for EXTRACTJSONFIELD

---

bin/ksql-run-class
bin/ksql-server-start

We inadvertantly changed ksql-run-class to ignore parameters for the shell
script by popping the class off after parsing parameters rather than before.

Expect ksql-run-class parameters after the class name

---

bin/ksql-server-start

Fix erroneous '$' in the usage message for ksq-server-start script

---

ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java

[minor] Test syntax and query termination

---

ksql-tools/pom.xml
ksql-tools/src/main/java/io/confluent/ksql/tools/printmetrics/PrintMetrics.java

Get rid of the sun jconsole dependency for ksql-tools. We were using
this to figure out the JMX URL for the ksql service. Instead, require
the user of PrintMetrics to provide the JMX port as a parameter

Remove jconsole dependency for ksql-tools.

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlBareOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/PlanTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/StructuredDataSourceNodeTest.java

* Use overloaded mapValues from KIP-149 to remove the resetRepartitionFlag function.
* Use mapValues than map that does not need to access the key at all.

Use mapValues overloads from KIP-149

---

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateStreamCommand.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateTableCommand.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/QueuedSchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java

When building the kafka streams app for aggregates, dont rekey the
stream if grouping by the key. This avoids expensive repartitioning
in one case where it is not required.

Dont rekey streams for aggregate if group by key

---

ksql-engine/src/main/java/io/confluent/ksql/structured/SelectValueMapper.java

When running the clickstream demo I have been seeing loads of Null-Ptr exceptioins in the ksql.logs.
This is caused by an upstream table expiring window data.
SRC: CREATE TABLE CLICK_USER_SESSIONS AS SELECT username, count(*) AS events FROM USER_CLICKSTREAM window SESSION (300 second) GROUP BY username;
DEST: CREATE TABLE CLICK_USER_SESSIONS_TS AS SELECT rowTime AS event_ts, * FROM CLICK_USER_SESSIONS;
In this case, when a user-session finishes in CLICK_USER_SESSIONS it emits the 'null' and causes the NullPtr in SelectValueMapper for Node: CLICK_USER_SESSIONS_TS

detect cdc delete event

---

ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java

Objects which are `.equals()` MUST have the same `.hashCode()`.

Fix hash code equals contract

---

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java

fixed param passing when using ```PRINT 'clickstream' FROM BEGINNING INTERVAL 10;```

fix bad param passing when using sample or interval

---

ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClientImpl.java
ksql-engine/src/test/java/io/confluent/ksql/util/KafkaTopicClientTest.java

Currently, when a `CREATE STREAM AS` or `CREATE TABLE AS` statement is submitted to a KSQL cluster with multiple nodes, the statement is written to the command topic first. Each node reads from the command topic and executes the statement independently.
The last stage of executing the physical plan is to create the output topic for the new stream or table. In this method, we first check whether the topic exists, and if not it is created. 
However, there is a race condition when multiple nodes are executing the same statement. Each one will find the topic doesn't exist and all of them will try to create it simultaneously. Only one will succeed, and the rest will fail with a `TopicExistsException`. We should not treat this exception as an error, but instead just validate that the parameters …

Fix race condition when multiple nodes try to create the same topic

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestConfigTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

See #772
Throw an exception with the config documentation rather than getting an `IndexOutOfBounds`

Check that listener config is provided when the rest server is started

---

docs/concepts.rst

Fixes #807 
Docs talk about running KSQL server with no arguments, to start using default settings, but the code won't allow this. Both the script and the java app will fail if the properties file are not supplied.
Plus the docs state that `application.id` must be set, but this is no longer the case.
So, we either need to change the code or the docs.... this PR changes the docs to match the code.
I've also pulled the part about custom command topics into the server specific section, which makes more sense to me.

Update client-server mode docs.

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/QueuedSchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/resources/query-validation-tests.json

Fixes #799 
I have been able to reproduce the bug with the query validation test as well as the integration test. Both are included here, though we probably should remove the integration test before merge.
The problem is that when you select specific fields with a partition by, the new key clobbers the second field of the output. The reason is that the schema passed to the `KStream` object in `KsqlStructuredDataOutputNode` has the `ROWKEY`, and `ROWTIME` fields removed. However, inside the `KStream.selectKey` method that's executed due to the `PARTITION BY` clause, we write the new key at column 1 of the value (where the `ROWKEY` would be), hence clobbering it.  
We should not overwrite the key field since it doesn't always exist in the schema. 
I am still trying to figure out why the …

Don't clobber columns when executing partition by

---

bin/ksql-run-class

KSQL requires a large newgen space for memory allocated and freed
as it processes each record. Use a 1:1 old-new ratio.

Set old/new ratio to 1

---

bin/ksql-run-class

KSQL requires a large newgen space for memory allocated and freed
as it processes each record. Use a 1:1 old-new ratio.

Set old/new ratio to 1 (#826)

---

ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/IntegerMaxKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/MaxAggFunctionFactory.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/min/IntegerMinKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/min/MinAggFunctionFactory.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/sum/IntegerSumKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/sum/SumAggFunctionFactory.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/max/IntegerMaxKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/min/IntegerMinKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/sum/IntegerSumKudafTest.java

Our internal udafs(sum, min,max) will support integer type.
Later we should implement these UDAFs similar to topk with generics.
This fixes https://github.com/confluentinc/ksql/issues/730

Added integer support for the current udafs.

---

ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java

* Fix some issues with comparison op codegen
Use the right operations for the various operand types:
- For non-boolean scalars, use (<= && >=) to check for equality.
== does a reference check rather than a value check. .equals
requires the argument to be of the same type as the object, so
equality comparisons between different types dont work. (e.g.
BIGINT and INT).
- For boolean scalars, only support == and !=. Implement using
Boolean.compare
- For Strings, use .equals for == and !=, and compareTo for other
operators.
- For array/map, only support == and != and implement using
.equals
This patch also includes handling of null operands. The implemented
behaviour is informed by Postgres semantics for null operands. For
every operator other than IS DISTINCT FROM, return false if either …

Fix some issues with comparison op codegen (#751)

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Options.java

ksql command prompt prints out incorrect usage.

---

ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/util/ArrayUtil.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/IntTopkKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/StringTopkKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/IntTopkDistinctKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/ArrayUtilTest.java

Fix for #880.
PR looks to:
- early out of `aggregate` even earlier.
- remove unnecessary array creation `Merger`
- reduce size of required array in `Merger`
- zip the two source arrays together, taking advantage of the fact the source topK arrays are already sorted.
- remove unused code from `ArrayUtil`
Note: This change does rely on the fact that the source arrays passing into the `Merger` are already sorted.  I assume that the `Merger` will always be passed source arrays created by itself, and so this is a safe assumption.

More optimization on TopK functions.

---

ksql-cli/src/main/java/io/confluent/ksql/Ksql.java

Currently we require ksql server url to be specified when starting KSQL cli. To keep the quick start and integration with confluent CLI simple this PR will use `http://localhost:8080` as the default server url when the cli is called without any args. If there is args in starting the cli the server url should be specified.

Set the default server url if CLI starts with no args

---

ksql-engine/src/main/java/io/confluent/ksql/util/KafkaConsumerGroupClientImpl.java

Fixes #740 
The `ConsumerGroupCommand` which we use to list groups instantiates its own admin client instance. The only way to configure this instance is to pass the configurations through a file.
This patch creates a temporary file, dumps the admin client properties to it, and then passes this file as an argument to the consumer group command.
I tested that this actually works against a secure cluster. Not sure what tests to add as part of this patch. Unit tests would require extensive mocking, which seems to be low ROI given that the use of the `ConsumerGroupCommand` itself is on the deprecation path. See #642 .
I am open to creative suggestions for low cost testing of this change.

Enable 'SHOW TOPICS' to work with secure kafka clusters

---

ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/DoubleMaxKudaf.java
ksql-engine/src/test/resources/query-validation-tests.json

It uses `Double.MIN_VALUE` as the inital value. This is a positive number so doesn't behave as anticipated.
Fixes #908

DoubleMaxKudaf doesn't work correctly

---

ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToTimestampTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/TimestampToStringTest.java

Use the local time to assert test correctness, otherwise, tests will fail because of using UTC.
This fixes #919

Ksql 919 assert correct conversion in string time udfs

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClientImpl.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java

Have streams choose a state store name for windowed aggregates, instead of providing
a name with a timestamp. This ensures that each KSQL server will pick the same name.
Sneak in a change to pass the causing AdminClient exception when throwing KsqlException
from KafkaTopiClient

Use the default state store name for windowed aggregates

---

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-common/pom.xml
ksql-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java
ksql-engine/pom.xml
ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JoinIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/StreamsSelectAndProjectIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
ksql-metastore/pom.xml
ksql-parser/pom.xml
ksql-serde/pom.xml

This includes one minor fix to the MetricsCollector to make it correctly
robust to reuse across tests that are both aware of its initialization/cleanup
and those that are not.

Fix integration test annotations and remove maven-surefire-plugin overrides

---

ksql-cli/src/test/java/io/confluent/ksql/TestRunner.java

Both the `CliTest.testSelectLimit` and `CliTest.testSelectStar` fail occasionally. From the stack traces we see that only some of the results are populated before hitting the timeout. This suggests that bumping the timeout might help stabilize the test.
```
java.lang.AssertionError: CLI test runner command result mismatch expected: [[ORDER_1, ITEM_1], [ORDER_2, ITEM_2], [ORDER_3, ITEM_3]], actual: [[ORDER_1, ITEM_1]]
at io.confluent.ksql.CliTest.selectWithLimit(CliTest.java:215)
at io.confluent.ksql.CliTest.testSelectLimit(CliTest.java:354)
Caused by: java.lang.AssertionError: Condition not met within timeout 10000. Did not get the expected result '[[ORDER_1, ITEM_1], [ORDER_2, ITEM_2], [ORDER_3, ITEM_3]], in a timely fashion.
at io.confluent.ksql.CliTest.selectWithLimit(CliTest.java:215) …
```

Bump timeout for CliTest

---

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DDLCommandExec.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

This fixes a regression. Don't include the exception stack in DDL error message. 
This fixes #840 
Before this fix if we had an error in DDL statement we would see the following in CLI:
ksql> drop table pageviews_original;
io.confluent.ksql.util.KsqlException: Incompatible data source type is STREAM, but statement was DROP TABLE
at io.confluent.ksql.ddl.commands.DropSourceCommand.run(DropSourceCommand.java:50)
at io.confluent.ksql.ddl.commands.DDLCommandExec.executeOnMetaStore(DDLCommandExec.java:60)
at io.confluent.ksql.ddl.commands.DDLCommandExec.execute(DDLCommandExec.java:54)
at io.confluent.ksql.rest.server.resources.KsqlResource.executeDDLCommand(KsqlResource.java:608)
at io.confluent.ksql.rest.server.resources.KsqlResource.lambda$registerDdlCommandTasks$11(KsqlResource.java:585)
at …

KSQL-840 Fix Regression in DDL error message, don't show the exception stack.

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java

Today, when we receive a POST request to run a new query, we first write
the command to a the command topic and then wait until it is consumed
from the topic, parsed, analyzed, and started, before sending the
response to the client.
The code that parses, analyzes, and runs the query happens in a
background thread.
The thread handling the REST request only waits for a second for the
whole process to complete before returning an error. This is too short
since the execution involves creating the sink topics, making sure that
they have the right replication factor, etc.
Would be better to bump the wait time to something like 5 seconds to
ensure robust execution. Keeping a high timeout is not very risky, since
we would not have too many concurrent POST requests to execute queries
anyawy. Our …

Bump the timeout for waiting for commands to be executed after being read from the command topic.

---

docs/quickstart.rst
docs/tutorials/index.rst

Internal staging server: http://staging-docs.confluent.io.s3-website-us-west-2.amazonaws.com/PR/768/4.1.x/ksql/docs/quickstart.html

DOCS-345 - Add docker instructions variant to KSQL quickstart

---

ksql-examples/src/main/resources/datagen.properties

Added an optional properties file for data-gen that can be used to register interceptors when KSQL is used with CE.

KSQL-758-Add an optional properties file for data-gen 

---

ksql-engine/src/test/resources/query-validation-tests/count.json
ksql-engine/src/test/resources/query-validation-tests/partition-by.json

Because of the restructuring of the query validation tests from 4.1.x and master, some of the manual conflict resolutions were lost when fixing up master after some bad merges. This PR adds back the lost tests.

Add back tests which were lost in the fixup on master

---

docs/tutorials/clickstream-docker.rst
docs/tutorials/clickstream-local.rst
ksql-clickstream-demo/Dockerfile
ksql-clickstream-demo/demo/clickstream-analysis-dashboard.json
ksql-clickstream-demo/demo/clickstream-analysis-dashboard.sh
ksql-clickstream-demo/demo/clickstream-schema.sql
ksql-clickstream-demo/demo/drop-clickstream-schema.sql
ksql-clickstream-demo/demo/elastic-dynamic-template.sh
ksql-clickstream-demo/demo/ksql-connect-es-grafana.sh
ksql-clickstream-demo/demo/ksql-tables-to-grafana.sh

Fix for #835
Changes:
- Upgrade grafana and elastic
- Install connect transformer to extract record timestamp and expose to elastic
- update grafana install script to parse new variable URL
- updated docs to be explicit about versions

Update Clickstream to no longer need the duplicate _TS streams and tables.

---

docs/key-constraints.rst
docs/syntax-reference.rst

First pass at key constraints doc. Explains that the key should be
STRING/VARCHAR and match the message key. We could expand this to
other data types so long as the user is sure that the key is the
utf-8 encoded representation of the value, but that may be confusing.

Key constraints

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestConfigTest.java

Currently, the command topic is composed of the following:
`_confluent-ksql-<ksql.service.id>`.
By default, this means the command topic is `_confluent-ksql-ksql_`.
This isn't a very helpful name for the command topic.
This patch adds a `_command-topic` suffix to the command topic. This
menas that the default command topic would be
`_confluent-ksql-ksql__command_topic`.
If you set the `ksql.service.id` to be `production` then your command
topic would be `_confluent-ksql-production_command_topic`.
Seems like a more operator friendly name for a very important topic.

Add _command_topic as the default suffix for the command topic.

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java

Currently when cancelling topic printing in Cli, after Topic printing ceased is shown the topic content is not immediately stopped and continues to show a few rows.
We should close the topic response immediately after the printing is cancelled.

 Close topic printing immediately after it is cancelled in Cli

---

docs/includes/ksql-includes.rst
docs/tutorials/basics-local.rst

- ksql-cli local --> ksql
- Get rid of redundant cli start instructions
- fix some typos that prevent the cli welcome msg from rendering

Fix local quickstart docs

---

ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java

Bad merge was by me at [eea96453](https://github.com/confluentinc/ksql/commit/eea96453dea11cec678c4d8b8b0f868471ef55c7).
MetastoreUtil doesn't exist on master.

Fix bad merge which retained a reference to MetastoreUtil 

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java

As part of my triaging / investigating #1055 I've added a new `shouldSupportDroppingAndRecreatingJoinQuery` to the `EndToEndIntegrationTest`.
While in there, I found the existing tests verbose and hard to understand, with some tests testing many things. So I've refactored the test a little to make it cleaner and clearer.

Enhance end-to-end integration test.

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java
ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java

Fix for #950 
This PR explicitly adds the SSL config names to the KSQL configuration, extends the `ksql.schema.registry.` prefix to allow SSL overrides specific to the SR to be supplied, and then wires this all up to configure the `SslSocketFactory` used by the SR Client.
For example, where the same SSL configuration is needed from the Schema Registry as for the Kafka brokers, then config like this can be used:
```
ksql.schema.registry.url=https://some.secure.url
security.protocol=SSL
ssl.truststore.location=/etc/kafka/secrets/kafka.client.truststore.jks
ssl.truststore.password=confluent
```
Where SR requires different configuration, it also supports overrides:
```
ksql.schema.registry.url=https://some.secure.url
ksql.schema.registry.security.protocol=SSL …
```

Support SR SSL configuration without the use of environment variables.

---

ksql-common/src/main/java/io/confluent/ksql/metrics/ConsumerCollector.java
ksql-common/src/main/java/io/confluent/ksql/metrics/MetricCollector.java
ksql-common/src/test/java/io/confluent/ksql/metrics/ConsumerCollectorTest.java

Rename messages-per-sec in the consumer interceptor to c-messages-per-sec
so that it has a different name from the corresponding stat in the producer
interceptor.

messages-per-sec -> c-messages-per-sec

---

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClient.java
ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClientImpl.java
ksql-engine/src/test/java/io/confluent/ksql/util/FakeKafkaTopicClient.java
ksql-engine/src/test/java/io/confluent/ksql/util/KafkaTopicClientTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockKafkaTopicClient.java

Fixes #910 
In the future, we can add a `SHOW TOPICS ALL;` command to include the internal topics. But for GA, it might make sense to not show them through KSQL at all -- they add little value.

Filter out internal topics in SHOW TOPICS

---

docs/includes/ksql-includes.rst
docs/tutorials/basics-docker.rst
docs/tutorials/basics-local.rst
docs/tutorials/docker-compose.yml

Since we no longer have a `ksql-cli local` mode, we need to start the server separately, and then have the cli connect to it. 
This updates the documentation and the docker-compose.yml to introduce a `ksql-server` container which runs the server.

Updates to make the docker quickstart work in CP 4.1

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/ServerInfo.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/ServerInfoTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java

Return the schema of the data being produced by a query in its
EXPLAIN output.
Return overridden properties a query is using in its EXPLAIN
output.
Include the KSQL service id in the response from /info

Return more stuff from the rest API

---

ksql-engine/src/test/java/io/confluent/ksql/testutils/secure/SecureKafkaHelper.java

This is an internal class which recently changed (moved to a different package), which would break our build.
let's drop the dependency for now.

Don't depend on the internal 'PlainSaslServer' class from kafka

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-cli/src/test/resources/log4j.properties

The `CliTest.testSelectLimit` still fails occasionally on Jenkins. The problem is that there are no logs for the run since the log files are not accessible on jenkins. This patch adds a logging configuration to redirect the logs to Stdout
Another notable thing from recent failures is only some of the expected outputs are printed. There is a point in the code where we abort reading from the server if the response stream contains a non-null error. If we get a spurious error, then it would explain the test failures. So this patch adds a log line at the point where we stop reading. 
With this, we should be able to better diagnose the root cause of the failures.

Add logging to the CliTest

---

docs/installation/server-config/security.rst

- Fix heading levels, (Kafka SSL section should be subsection of Secure Kafka)
- Consistent heading names
- Moving C3 monitors to the bottom

Minor security docs tweaks

---

docs/includes/ksql-includes.rst
docs/installation/installing.rst

Fixes current formatting. 
Now looks like:

Formatting for CLI start command

---

docs/tutorials/basics-docker.rst
docs/tutorials/clickstream-docker.rst

- Remove java 1.8 requirement from docker quickstart
- Update clickstream version from `0.5` to `4.1.0`

Remove Java requirements and fix clickstream version

---

docs/includes/ksql-includes.rst
docs/installation/installing.rst
docs/installation/upgrading.rst
docs/tutorials/basics-docker.rst
docs/tutorials/basics-local.rst
docs/tutorials/clickstream-docker.rst

This should help existing KSQL users to upgrade more easily from Dev Preview releases to KSQL GA. 
We have been doing a lot of 1-1 Q&A already in the public KSQL Slack community (`#ksql` channel at https://launchpass.com/confluentcommunity), but this doesn't scale.  Better have proper information available in the docs.

Add upgrade guide for developer preview releases

---

docs/tutorials/docker-compose.yml

*IMPORTANT*: This PR should only be merged once the KSQL 4.1.0 images (tag) are available. The latest KSQL images on Docker Hub have the tag `4.1.x-rc1` now.

[WIP - DON'T MERGE YET] Update docker-compose.yml for KSQL 4.1 and CP 4.1

---

docs/tutorials/docker-compose.yml

The previous fix #1161 didn't update the jar versions for datagen, which meant that the pageviews and users topics were not created. 
Longer term, we need a more streamlined way to do this. Also, the 4.1.1-SNAPSHOT versions are not technically correct, but it is less pressing right now. WE can get the right version in a separate PR and take more time doing it.

Bump jar versions for datagen

---

docs/faq.rst
docs/includes/ksql-includes.rst
docs/installation/installing.rst
docs/tutorials/basics-docker.rst
docs/tutorials/basics-local.rst
docs/tutorials/clickstream-docker.rst

Adds back in items commited to the wrong branch:
https://github.com/confluentinc/ksql/pull/1150 (fe83ea0a88087f9ef23c2e63d66904db962cba87)
https://github.com/confluentinc/ksql/pull/1152 (1e6e169c6207ea48a5eaba4feed6290499785559)
https://github.com/confluentinc/ksql/pull/1156 (7b85f658d0c74a30c7ac52cae187d950cf9d0a3a)
https://github.com/confluentinc/ksql/pull/1172/commits/def5f4732ce7ad7e92ec14549cdf96220d1a9c def5f4732ce7ad7e92ec14549cdf96220d1a9cc1

Cherry-picks changes from 4.1.x that are not in 4.1.0-post

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/StructuredDataSourceNodeTest.java
ksql-engine/src/test/resources/query-validation-tests/table-update-delete.json

Changelog topics for tables can contain tombstone records with null values to
indicate that a given key is deleted from a table. KSQL implements tables by
building a KStream over the changelog topic, applying some transformations for
adding columns (one of which Kafka Streams only supports for KStreams), and
then reducing the result into a KTable. The problem is that Kafka Streams
filters out null values in the reduce and aggregation processors for
GroupedKStreams. This patch works around this problem by mapping to
Optional<GenericRow> just before grouping and aggregating into the final
KTable, and then implementing an aggregator for handling Optional.EMPTY as
a tombstone
Fixes #1169

Fix handling of table tombstones

---

ksql-engine/src/test/java/io/confluent/ksql/testutils/EmbeddedSingleNodeKafkaCluster.java

Current embedded test kafka cluster fails with a error when trying to run a test more than once in the IDE. This PR fixes this.

Allow tests with Kafka cluster to be run more than once in IDE.

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriterTest.java

Fix race condition when limit statements are used. The exception thrown when limit is reached causes the QueryStreamWriter to exit its loop, even if more rows available on the queue.
Causes: Test Failed: CliTest.testSelectLimit
Causes #656: LIMIT clause is not honoured accurately
Fixed so that any pending rows are drained before handling the exception.
Fixes #656

Fix flakey CliTest and issue with LIMIT clause not being honoured.

---

ksql-engine/src/test/java/io/confluent/ksql/util/KafkaTopicClientImplIntegrationTest.java

Topic creation is async, via ZK, but the test wasn't taking this into account. Leading to occasional failures where the test managed to check for existance of the topic _before_ the broker had picked up the new topic from ZK.

Minor: Fix flakey KafkaTopicClient integration tests

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlServerMainTest.java

Currently the app zombies in a bad state should there be a start up error, (e.g. bind exception on the port).
This change contains to parts:
1. Fix the reason why the app was zombie-ing, (the app was not being stopped, which left non-daemon jetty thread still running.
2. Add explicit `System.exit` call to _ensure_ app shuts down in the future, even if a future change means a non-daemon thread is left running on startup error.
Fixes #1178

Shutdown cleaning should there be an error on start up.

---

README.md

Somehow the intro blurb for KSQL diverged from 4.1.x to master. This patch makes them consistent.

MINOR: Make README ksql blurb consistent with the one on 4.1.x

---

docs/includes/ksql-supported-versions.rst
docs/index.rst
docs/installation/installing.rst

Would appear here (mockup):
----
----
We have this information already at https://docs.confluent.io/current/installation/versions-interoperability.html#ksql, but (a) this is very hard to find because it's very much out of your way when your are browsing the KSQL chapter in the docs and (b) this information (think: the code/text itself) should also be part of the KSQL GH repo.
We can address, in a separate PR, where we can use a better `includes` setup so that we don't duplicate this text/information in our various .rst files.

Add version compatibility information to KSQL docs

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ListQueries.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ListStreams.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ListTables.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/FieldSchemaInfo.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescriptionEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescriptionList.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionList.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/TablesList.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KafkaTopicsListTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KsqlTopicsListTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java

This patch decouples source and query descriptions. SourceDescription
now describes a single data source (stream or table). The fields specific
to queries are pulled out into QueryDescription. QueryDescription also
includes the sources read from and written to.
This patch also makes it so that SourceDescription and QueryDescription are
not KsqlEntities. A KsqlEntity should be used to return the result of executing
a ksql statement (we should probably also change that name at some point, but
this patch refrains from doing so for the sake of keeping the diff manageable.).
With this change we can return a SourceDescription as part of a composition that
itself is a KsqlEntity.
Finally, add support for a DESCRIPTIONS flag to SHOW, which returns descriptions
instead of the more concise listing …

SourceDescription cleanup + listing with descriptions

---

docs/syntax-reference.rst

Fixes #1214 
Questions coming up on community slack channel on the resolution of timestamps in KSQL.

Clarify that KSQL timestamps are in milliseconds.

---

ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java

Causes: https://jenkins.confluent.io/job/confluentinc/job/ksql/job/4.1.x/389/testReport/junit/io.confluent.ksql.integration/SecureIntegrationTest/shouldRunQueryAgainstKafkaClusterOverSsl/

Fix flaky test, caused by async topic creation.

---

ksql-engine/src/test/java/io/confluent/ksql/testutils/EmbeddedSingleNodeKafkaCluster.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriterTest.java

Cherry picked from master branch, (original PR: #1173)
Fix for flakey test: CliTest.testSelectLimit
(cherry picked from commit 7ee6f8b)
Just want to check:

Cherry  pick fix for flakey 'CliTest.testSelectLimit' test into 4.1.x

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/RootDocument.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/RootDocumentTest.java

PR contains two fixes:
- Fix relating to #1081: Root `/` redirect currently forces a redirect based on the listener uri defined in the config e.g. `http://localhost:8088/info`, where as it should redirect using the current part, e.g. `http://127.0.0.1:8088` should redirect to `http://127.0.0.1:8088/info`, not `http://localhost:8088`.  (This fixes the redirect in #1081, but probably not the underlying issue with K8).
- Fix redirect when 'uiEnabled' but no UI: current impl was redirecting from root '/' to /index.html' even if there was no UI war or expanded UI files available.

Fix Rest API redirects.

---

docs/api.rst
docs/index.rst

First cut of the 5.0 API docs. For now this just includes documentation
for the /ksql, /query, and /status endpoints. Also some functionality,
e.g. LIST EXTENDED is left out.

5.0 API docs

---

docs/api.rst
docs/index.rst

HTTP API docs for 4.1. These docs are limited to the /ksql and /query endpoints. We can add docs for the other endpoints in our 5.0 API docs.

API documentation

---

ksql-engine/src/test/java/io/confluent/ksql/testutils/ZooKeeperEmbedded.java

There is a race condition in the test lib of ZK. When creating a new `TestingServer` the lib first finds three free ports to use, it then passes this information to different threads, which then bind to these ports. This is a race condition: something else can grab any one of these ports between the point it finds them and binds to them, resulting in a `BindException` - which we are seeing occasionally.
Handle the error by retrying.

Work around a race condition in the test ZK instance.

---

docs/api.rst

Remove usage of API versioning from the 5.0 docs. Those changes didn't make the preview release

Rm versioning docs

---

ksql-cli/src/main/java/io/confluent/ksql/Ksql.java
ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-cli/src/test/java/io/confluent/ksql/cli/RemoteCliSpecificCommandTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientTest.java

- Move the position of the warning, on startup, if the CLI can not connect to the server, to _after_ the welcome message to make it more obvious, and make it an "ERROR".
- Application now exists on startup, with a suitable message, if the server address is not a valid URL. (It will continue if it is a valid URL, but can't connect).
- The `server` command now reports an error if it can't connect to the server. (Useful for support to ensure CLI can connect).
- The `server http://new-server:port` command now validates the passed in server details are a valid URL. If they are not, it reports an error and does NOT update internal state. If they are valid the internal state is updated, the connection is tested and a confirmation message is returned to the user.
- Refactored KsqlRestClient …

Better reporting of invalid serverAddress or connection issues in CLI

---

docs/installation/server-config/config-reference.rst

The production configuration docs had wrong prefixes. This fixes them.
None. Docs only change.

Fix production config docs

---

ksql-engine/src/main/java/io/confluent/ksql/physical/AddTimestampColumn.java

punctuate is removed in ValueTransformer in https://github.com/apache/kafka/pull/4993

Remove deprecated punctuate

---

docs/installation/server-config/security.rst
ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java

Update docs to reflect that the `DESCRIBE` ACL is _not_ required on the `__consumer_offsets` topics for KSQL to work.
Reviewed under https://github.com/confluentinc/ksql/pull/1252

The DESCRIBE ACL on the __consumer_offsets topic is not required.

---

bin/ksql-run-class

* Configure GC logging correctly when running with Java 10 (port of https://github.com/apache/kafka/pull/4895)
* Use ExplicitGCInvokesConcurrent instead of DisableExplicitGC (port
of https://github.com/apache/kafka/pull/3371)
Ran ./bin/ksql with Java 10 and verified that the JVM was able to start.

Fix run class to work with Java 10 and use ExplicitGCInvokesConcurrent

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/JLineReader.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/JLineTerminal.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/JLineReaderTest.java

Currently we don't log commands starting with spaces to the CLI history. This is considered bad UX. This patch changes a setting in the underlying JLine3 library we use so that we log commands which start with a space.
Added a test case which ensures that commands with a leading space are saved to history.

Don't ignore leading spaces when saving history

---

ksql-examples/pom.xml
ksql-examples/src/test/java/io/confluent/ksql/datagen/GeneratorTest.java
ksql-examples/src/test/java/io/confluent/ksql/datagen/util/ResourceUtil.java

System tests are failing locally due to a change in the DataGen that saw the internal Avro-Random-Generator code being swapped out for an external library. Unfortunately, the external library was missing functionality: the ability to generate STRING fields using iterators.
This PR updates to a new version of the avro-random-generator, to which STRING iteration have been added, and adds a test to detect any similar future errors.
Added unit tests to ensure all avro schema with the examples project are supported by avro-random-generator.

Fix system tests (ish)

---

ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java
ksql-engine/src/test/resources/query-validation-tests/extract-json-field.json

Without the postfixing the code generator shares UDF instances, causing for strange results. e.g. #1328.
So, for example, without this change an expression such as:
```
CONCAT(EXTRACTJSONFIELD(source, '$.name'), EXTRACTJSONFIELD(source, '$.version')) 
```
Will be converted the following approx Java code (casts removed for readability):
```
CONCAT.evaluate(
EXTRACTJSONFIELD.evaluate(TEST_SOURCE, "$.name"), 
EXTRACTJSONFIELD.evaluate(TEST_SOURCE, "$.version")
);
```
Where the same `EXTRACTJSONFIELD` usf instance is called twice, meaning it can't cache results of, for example, parsing the json path.  With the change the java code looks like this:
```
CONCAT_0.evaluate(
EXTRACTJSONFIELD_1.evaluate(TEST_SOURCE, "$.name"), 
EXTRACTJSONFIELD_2.evaluate(TEST_SOURCE, "$.version")
);
```
Meaning …

Post fix udf instance names to ensure they are unique.

---

docs/api.rst
docs/includes/ksql-includes.rst
docs/syntax-reference.rst
docs/tutorials/clickstream-docker.rst
ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-clickstream-demo/non-docker-clickstream.md
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlBareOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/OutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/QueuedSchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/OutputNodeTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/StreamedRow.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriter.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockStreamedQueryResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriterTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java

Limit clauses spam the logs with errors and warnings (#1215), is tracked per-partition, and is not documented (#697).
This PR addresses these issues.
- no longer spams the logs with errors, (fixes #1215)
- limit is now _across_ partitions, not _per_ partition.
- server can now send a 'final message' to the CLI, e.g. 'Limit Reached', (rather than using an error message to terminate the receive loop).
- LIMIT added to the docs, (fixes #697)
- Added suitable unit tests.

Fix the way `LIMIT` clauses are handled

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/Flow.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PollingSubscription.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PrintPublisher.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamPublisher.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStream.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriter.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WebSocketSubscriber.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/PollingSubscriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriterFormatTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WebSocketSubscriberTest.java

Refactors the websocket endpoint to not pause between batches of data and drain the queue on error
Uses constructs loosely borrowed from the jdk9 Flow (aka reactive-streams) api

Refactor WebSocket endpoints and add support for print topic

---

bin/ksql-run-class
docs/tutorials/docker-compose.yml

In the `ksql-examples` docker image, we can't run the `ksql-datagen` script directly because the class path isn't configured to look for jars in the right directory. Hence running that script will fail with a `ClassNotFoundException`. 
This patch updates the run script to include jars from the `ksql-examples` directory if it exists. It also updates the `docker-compose` quickstart to not reference the jars directly, but instead reference the run script. 
I built the images locally, and then ran `docker-compose up -d` after updating the docker compose file to reference the new images. The quickstart works.
Also`ksql-datagen` can be now be accessed directly in the container, for example:
```bash
amehta-macbook-pro-2:tutorials apurva$ docker run -it 243c79eefd69  ksql-datagen
Schema file not …
```

Add ksql-examples to the class path when running ksql-datagen

---

Jenkinsfile
cp-ksql-server/pom.xml

When #1322 merged onto master, it retained the incorrect `4.1.2-SNAPSHOT` version,  breaking the build. This  PR fixes the build.
`mvn -U clean package -DskipTests` now works.

HOTFIX: Bump POM version for cp-ksql-server

---

cp-ksql-server/pom.xml
pom.xml

Currently packaging is blocked because this fails to build during the packaging job because it tries to build an empty jar. This patch disables building jars for the docker image module.
None.

Skip building jars for the ksql cp docker image.

---

ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/FunctionArguments.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java

Last change broke behavior of functions where the value is extracted from an array. This fixes that case. Note: needs a follow up PR to add tests for the same with Maps
Ran tests that were failing

handle array subsrcipts when generating function args

---

pom.xml

Packaging is failing because cp-ksql-server can't build becasue it can't find monitoring interceptors. This is likely a bug in packaging, but disabling this module for now to unblock the preview release.
None.

Remove cp-ksql-server from the build to unblock packaging

---

ksql-engine/src/test/java/io/confluent/ksql/testutils/EmbeddedSingleNodeKafkaCluster.java
ksql-engine/src/test/java/io/confluent/ksql/testutils/secure/ClientTrustStore.java
ksql-engine/src/test/java/io/confluent/ksql/testutils/secure/SecureKafkaHelper.java

Kafka recently enabled server id verification by default for all tls connections.
This breaks our secure integration test, which doesn't include a valid common or
dns name in its certs. Furthermore, since some of the embedded services listen on
local addresses other than localhost and lo/lo0, we can no longer statically generate
the certs for the test. This patch explicitly disables the check for all the test
clients.

Disable server identification verification for SecureIntegrationTest

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/EntityQueryId.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/RunningQuery.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/EntityQueryIDTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

Adds an EntityQueryId class to represent Query IDs in the API. We don't
use the existing QueryId class as its fairly decoupled from the API and
should be free to change as we evolve how query ids are generated. On the
other hand the representation of the id in the API must not change.
Fixes #1234

Wrap api query id strings in a class

---

ksql-common/src/main/java/io/confluent/ksql/function/UdfFactory.java
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/function/UdfFactoryTest.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java

Current a statement such as `select concat('foo',1) from blah;` results in NPE:
```java.lang.NullPointerException```
With this change it results in:
```Function 'CONCAT' does not accept parameters of types:[STRING, INT64]```
Replaces #1399 (Rebased onto 5.0 branch)
Added unit test + manual testing.

Avoid NPE if not function exists that handles required types.

---

checkstyle/suppressions.xml
ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStreamAsSelect.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DefaultAstVisitor.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/HoppingWindowExpression.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/SessionWindowExpression.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/SimpleGroupBy.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Table.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/TumblingWindowExpression.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Window.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/WindowExpression.java
ksql-parser/src/test/java/io/confluent/ksql/parser/rewrite/StatementRewriterTest.java

This is a new feature to rewrite the queries using changing the AST. This will be used in supporting struct type.
We added a new visitor that visits an AST and creates a copy of it. To rewrite a query you can inherit from this visitor and override the methods that you need.
Some changes had to be made in the AstVistor and some nodes so we can create the full tree.
Unit test for query rewrite class.

Added query rewrite feature using AST.

---

checkstyle/suppressions.xml
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfMetricProducer.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/PluggableUdf.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderUtil.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfMetricProducerTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionTypeManagerTest.java

Adds collection of metrics for UDFs if the config `ksql.udf.collect.metrics` is set to `true`. The default is `false`.
As it stands the metrics are global (rather than per query) as they are intended for testing purposes rather than production, i.e., i think the overhead may be too much to collect them on every invocation.
Added unit tests to ensure the metrics get added or not added depending on the configuration. Add tests to ensure the metrics are collected.

Collect metrics for UDFs

---

ksql-common/src/main/java/io/confluent/ksql/function/udf/Udf.java
ksql-common/src/main/java/io/confluent/ksql/function/udf/UdfDescription.java
ksql-engine/src/main/java/io/confluent/ksql/function/Blacklist.java
ksql-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfCompiler.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/PluggableUdf.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfCompilerTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java

Follow up from https://github.com/confluentinc/ksql/pull/1366

UDF tidy ups

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/QueryAnalyzer.java
ksql-engine/src/test/java/io/confluent/ksql/QueryTranslationTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AggregateAnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/LogicalPlanBuilder.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SqlPredicateTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionTypeManagerTest.java
ksql-engine/src/test/resources/query-validation-tests/sink-topic-naming.json

Added a new KsqlConig.KSQL_OUTPUT_TOPIC_NAME_PREFIX_CONFIG = "ksql.output.topic.name.prefix";
This allows users to specify a prefix to be applied to the names of any output topics that are created from statements without an explicit topic name supplied.
e.g.
Given `ksql.output.topic.name.prefix=my-first-prefix`
```
CREATE STREAM S AS ...  -- will use Kafka topic with name 'my-first-prefix-S'
CREATE STREAM S WITH(KAFKA_TOPIC='foo') AS ... -- will use Kafka topic with name 'foo'
```
This is useful for users of interactive KSQL clusters wanting to set up Kafka ACLs on a prefixed resource pattern in the Kafka cluster to allow users to create and use output topics. e.g. in the above example, an ACL could be set up to allow KSQL to create/write to any topic prefixed with 'my-first-prefix-'. …

Prefixed output topics

---

checkstyle/suppressions.xml
ksql-metastore/src/test/java/io/confluent/ksql/util/MetaStoreFixture.java
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStream.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStreamAsSelect.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTable.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTableAsSelect.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropTable.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/InsertInto.java
ksql-parser/src/main/java/io/confluent/ksql/util/DataSourceExtractor.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/rewrite/StatementRewriterTest.java

This PR makes changes in our AST so we can handle dot notation to access nested fields in struct correctly.
Previously we assumed that we have only one dot, stream/table name.column name. How we will be able to have more than one dot in a dereferenced node.
This is based on the previous PR for Query rewrite.
We also check for ambiguity resulting from having columns with the same name as the stream/table name.

Updated AST builder to handle dot notation.

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/resources/query-validation-tests/joins.json
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Join.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/WithinExpression.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/WithinExpressionTest.java

Based on discussions, we decided to use the `WITHIN` keyword to define the join window in stream stream joins rather than `SPAN` which is what #1417 implemented.
This patch changes `SPAN` to `WITHIN` everywhere, and also moves the `WITHIN` clause to before the join criteria. 
The mechanism was simple:
1. Update the grammar. Fix all the resulting compile failures.
2. Run tests, fix failures.
3. Grep the code base for `SPAN`, `Span`, and `span` and rename appropriate usages to `WITHIN`, `Within`, and `within` respectively. This takes care of error messages, log lines, variable names, etc.
Updated tests to check for `WITHIN` instead of `SPAN`.

Rename SPAN to WITHIN everywhere

---

ksql-engine/src/main/java/io/confluent/ksql/util/KafkaConsumerGroupClientImpl.java

Note that this class is internal in Kafka and we should migrate to
the the AdminClient, which is a public API, as soon as possible.

Handle rename of KafkaConsumerService to ConsumerService

---

ext/resource-blacklist.txt
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksql-engine/src/test/java/io/confluent/ksql/function/BlacklistTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksql-engine/src/test/resources/resource-blacklist.txt

Add a new config option `ksql.extension.dir` to configure the directory where UDFs and any future extensions should be loaded from.
Added new test to make sure it works

Add config for ext dir

---

Jenkinsfile
cp-ksql-server/include/etc/confluent/docker/configure
ksql-clickstream-demo/Dockerfile
ksql-examples/Dockerfile
pom.xml

Now that the circular dependency packaging issue has been worked around, let's re-enable the build of the cp-ksql-server docker image.
This patch also fixes the logging for cp-ksql-server so that it is actually controlled by the log4j config.
Finally, this patch drops the use of standalone jars from the `ksql-clickstream-demo` and `ksql-examples` docker images as the use of standalone jars is discouraged.
The log out put of cp-ksql-server includes timestamps, as expected:
```bash
$ docker logs -f `container-id`
[2018-06-21 00:31:16,558] INFO Server up and running (io.confluent.ksql.rest.server.KsqlServerMain:61)
[2018-06-21 00:31:16,559] INFO Waiting 10078 ms for the monitored service to finish starting up... (io.confluent.support.metrics.BaseMetricsReporter:206)
[2018-06-21 00:31:26,639] …
```

Renable the build of the cp-ksql-server docker image

---

ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGenProducer.java

Minor tweak to the output from datagen, now:
- includes timestamp of the messages sent to Kafka
- outputs successfully sent messages to Standard.out, not err.
- outputs a message before starting.

Output more info to help with debugging system tests.

---

docs/installation/server-config/security.rst
ksql-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java
ksql-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java

Currently, the we don't pass any schema registry configurations in the ksql config file onto the schema registry client. This means we can't configure basic auth for the schema registry client through ksql. This patch enables passing basic auth parameters to the schema registry client
Added a unit test which checks that the config parameters with the `ksql.schema.registry` prefix are passed on to the underlying schema registry client.

Pass schema registry client configs onto the schema registry client

---

ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java

Don't throw exception when the ext dir doesn't exist and trying to load udfs. Just log and skip

don't bomb on non-existing plugin dir

---

ksql-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java
ksql-serde/src/main/java/io/confluent/ksql/serde/avro/AvroDataTranslator.java
ksql-serde/src/main/java/io/confluent/ksql/serde/avro/KsqlAvroTopicSerDe.java
ksql-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectDataTranslator.java
ksql-serde/src/main/java/io/confluent/ksql/serde/connect/DataTranslator.java
ksql-serde/src/main/java/io/confluent/ksql/serde/connect/KsqlConnectDeserializer.java
ksql-serde/src/main/java/io/confluent/ksql/serde/connect/KsqlConnectSerializer.java
ksql-serde/src/test/java/io/confluent/ksql/serde/avro/AvroDataTranslatorTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlGenericRowAvroSerializerTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/connect/ConnectDataTranslatorTest.java

This patch updates the avro serdes to convert invalid avro field names before serializing.
As part of this change, we've moved the code that sets struct schema names, along with the
code that sets invalid field names into a translator that does avro-specific things called
AvroDataTranslator.

Convert invalid avro field names before serializing

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java

Renamed the DdlCommandTask to  KsqlStatementTask. The previous name was misleading since it is not just DDL but also DML.

Rename DdlCommandTask to KsqlStatementTask in KsqlResources class.

---

ksql-parser/src/main/java/io/confluent/ksql/parser/ExpressionFormatter.java
ksql-parser/src/test/java/io/confluent/ksql/parser/ExpressionFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java

Add a space between the field name and type when generating sql string
from expression

Fix spacing in struct schema string

---

ksql-engine/pom.xml
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java

Update the version of fast-classpath-scanner to 3.1.6 which supports java 9+.
One fix in `UDFLoader` so that it works with the built-in UDFs
Fixes #1523
Ran build on java 10 & java 8

Java 10 support

---

ext/resource-blacklist.txt
ksql-engine/src/main/java/io/confluent/ksql/function/Blacklist.java
ksql-engine/src/test/java/io/confluent/ksql/function/BlacklistTest.java

- Reduce log level to WARN when can't load the blacklist file.
- Update blacklisting such that no classes are blacklisted if the file is not found or can't be loaded.
- Change the default file such that it allows everything.
Fixes #1515
Updated unit test

Reduce log level when loading blacklist to INFO from ERROR

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java

This patch fixes a problem in KsqlConfig where monitoring interceptor
configs were not included in streams configs. The fix involves including
configs for which we could not resolve a type in the streams config map.
Such configs are passed to streams but filtered from the secret-obfuscating
calls.

Include monitoring interceptor config in streams configs

---

ksql-examples/src/assembly/package.xml

Today, the system tests run downstream of packaging. This can be evidenced by lines like this in the system test output:
```
python -m muckrake_runner.run_tests muckrake/tests/ --aws --num-workers 40 --install-type tarball --resource-url https://s3-us-west-2.amazonaws.com/jenkins-confluent-packages/5.0.x/48/archive/5.0/confluent-5.0.0-SNAPSHOT-2.11.tar.gz --results-root /home/jenkins/workspace/st-confluent-platform_5.0.x-CR42KGVJVSIDOZSYD6BWYUIUM3NQVDLBM2BHHPXMVWKP2V3SVVBA/results --parallel
```
As mentioned here (https://github.com/confluentinc/muckrake/pull/570#discussion_r196894404) our hard coding of the path for the schema files would be a problem with from-package system test runs.
That is indeed a problem. But the larger problem is that the schema files are not packaged at all …

Include example schemas in the packaging build

---

ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java

Fixes #1545 .
The `PhysicalPlanBuilder` assumes that the list of interceptors is a modifiable list. This is an unsafe assumption which is no longer true. 
This patch simply copies the existing list into a modifiable LinkedList which should always be modifiable.
Added an integration test which ensures that the list of interceptors can be modified by the `PhysicalPlanBuilder`.

Ensure that the list of interceptors is modifiable before mutating it

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksql-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java
ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java

Fixes #707, #1555, helps with #713
Existing error message is ambiguous and too generic. Has led to lots of confusion in the community. This is intended to address that. 
Two error conditions are handled, with the current/new messages as below: 
```
ksql> create stream twitter with (kafka_topic='twitter_avro_03',value_format='avro');
Unable to verify the AVRO schema is compatible with KSQL. Map key must be of type STRING
```
```
ksql> create stream twitter with (kafka_topic='twitter_avro_03',value_format='avro');
KSQL does not currently support the Avro schema for topic twitter_avro_03.
Reason: Map key must be of type STRING
Please see https://github.com/confluentinc/ksql/issues/ to see if this particular reason is already
known, and if not log a new issue. Please include the full Avro …
```

Improve error messages for Avro/SR interaction. 

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksql-serde/src/main/java/io/confluent/ksql/serde/avro/AvroDataTranslator.java
ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlGenericRowAvroSerializerTest.java

The avro serializer should provide a namespace in the avro schemas that it generates.
This ensures that users can compile the schema into a class that can be imported from
their own java code. Without the namespace, the generated code is placed in the default
package, and cannot be imported.

Specify a namespace for avro schemas

---

docs/syntax-reference.rst

Update the docs to indicate that array index starts from 0.
Many SQL systems have array index starting from 1 but some others like Hive have array index starting at 0. 
This is the current behavior. We can discuss about if we want to change this to start from 1.

Update docs to state array index starts from 0

---

docs/faq.rst

Fixes [Document communication pathways for KSQL server/client](https://confluentinc.atlassian.net/browse/KSQL-510).
Cribbed from @miguno's slide deck. Doesn't address @cotedm's first ask about security and SSL, but I think this other topic does a good job with that: [Configuring Security for KSQL](http://staging-docs.confluent.io.s3-website-us-west-2.amazonaws.com/5.0.0/ksql/docs/installation/server-config/security.html).

KSQL-510: Add FAQ sections for data, metadata, and server info

---

ksql-engine/src/main/java/io/confluent/ksql/structured/SqlPredicate.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SqlPredicateTest.java
ksql-engine/src/test/resources/query-validation-tests/project-filter.json

Instead of writing to log just return false for null rows in KsqlPredicate.
This fixes #680 .
Integration test was added.

Return false for null rows in predicate.

---

docs/installation/upgrading.rst
ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/utils/TestUtils.java

Currently some of the KSQL metrics don't have ksql service id. This PR adds the KSQL service id to these metrics making sure they are unique. 

Add service id to ksql metric names

---

ksql-engine/src/test/resources/query-validation-tests/project-filter.json
ksql-parser/pom.xml
ksql-parser/src/main/java/io/confluent/ksql/parser/ExpressionFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksql-parser/src/test/java/io/confluent/ksql/parser/ExpressionFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/util/ParserUtilTest.java

SqlFormatter quotes column names if they conflict with words reserved by our
grammar. This patch moves that logic to a utility class, and calls the utility
from ExpressionFormatter so that the same is done for struct fields
Fixes #1536
Unit test for ExpressionFormatter

Quote struct fields with reserved names

---

docs/syntax-reference.rst
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/resources/query-validation-tests/joins.json

SchemaKStream.select may get a QualifiedNameReference as the expression
in a select call. The logic that looks for and preserves the key field in
the resulting SchemaKStream needs to handle expressions of this type. It
also needs to handle cases where the key field name is fully qualified, as
happens with joins.
Fixes #1686. Fixes #1550 .

Handle QualifiedNameReference when selecting stream/table keys

---

docs/syntax-reference.rst
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/resources/query-validation-tests/joins.json

Verify that table joins use the key in the join criterion
Fixes #1712 
Added unit tests to JoinNodeTest

Verify that table joins use the key in the join criterion

---

ksql-parser/src/test/java/io/confluent/ksql/parser/tree/HoppingWindowExpressionTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/TumblingWindowExpressionTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/util/TimeWindowsMatcher.java

upstream change to KStreams saw `equals` and `hashcode` removed from `TimedWindows`. Fixed by adding EasyMock matcher.
ran tests.

Fix the build failures caused by upstream KStreams change.

---

ksql-engine/src/main/java/io/confluent/ksql/function/UdfCompiler.java

The UDF compiler outputs all generated code at debug when run. This is spamming the logs when you run associated tests, making issues harder to track down.
Now that UDFs are in and stable, let's downgrade the output to TRACE.

Downgrade UDF compiler output to trace to stop it spamming the  build logs

---

ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
ksql-engine/src/test/resources/log4j.properties
ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java
ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonSerializer.java

`UdfInfTest` was talking over 5 minutes to run!  By changing it to only start Kafka / ZK once and to only wait for the expected number of messages, it now runs in under 50s.
Change is a test.

Speed up Integration test

---

docs/installation/installing.rst

Fixes description of Docker images in the KSQL installation topic.

KSQL-1478: Update Docker section to link to Hub images and config options

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java

Updates the `StreamedQueryResource` to accept the `application/vnd.ksql.v1+json` content type and bring it in line with the `KsqlResource`. 
Fixes #1748 .
Added an integration test to verify that we accept all permissible values for the `Content-Type` header.

Fix content type of streamed query resource

---

ksql-engine/src/test/resources/query-validation-tests/project-filter.json
ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java

This is a bug fix patch for #1784 .
Switching back to using `if` statement fixes the issue.
Previously we used statements like the following:
```
return node.getLocation()
.map(location ->
new ArithmeticBinaryExpression(location, node.getType(),
(Expression) process(node.getLeft(), context),
(Expression) process(node.getRight(), context)))
.orElse(new ArithmeticBinaryExpression(node.getType(),
(Expression) process(node.getLeft(), context),
(Expression) process(node.getRight(), context)));
```
This results in execution of both map and orElse arguments which results in exponential visits of the AST nodes.
By changing it to `if` we just run the block that we need.

Switching back to good old if statement!

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/util/KafkaConsumerGroupClient.java
ksql-engine/src/main/java/io/confluent/ksql/util/KafkaConsumerGroupClientImpl.java
ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClient.java
ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClientImpl.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/KafkaConsumerGroupClientTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/testutils/EmbeddedSingleNodeKafkaCluster.java
ksql-engine/src/test/java/io/confluent/ksql/util/FakeKafkaTopicClient.java
ksql-engine/src/test/java/io/confluent/ksql/util/KafkaTopicClientImplIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/KafkaTopicClientImplTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KafkaTopicsListTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockKafkaTopicClient.java

Changed the KafkaConsumerGroupClientImpl to use the new AdminClient.
Other updates to KSLQEngine and KafkaTopicClient so that we share the admin client
Fixes #642 
Run existing tests

Change KafkaConsumerGroupClient to use AdminClient

---

docs/installation/installing.rst
docs/installation/server-config/index.rst
docs/tutorials/clickstream-docker.rst

Removes the last hard-coded line number references to `ksql-includes.rst`, which means replacing start-line/end-line syntax with start-after/end-before syntax,

KSQL-1590: Replace hard-coded line number includes with symbols

---

ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java

Fix for #1425
Harden syntax to:
- _Not_ have optional stream name as the first entry in a select statement.
- _Require_ a `FROM` statement, rather than it being optional, but resulting in NPE if missing.
- _Not_ having supporting multiple sources in the `FROM` statement.
Manual tested.  
Output from the statement in issue #1425, which is an invalid statement, is now a much more helpful message, rather than an NPE:
```
ksql> select message\
from ratings;
line 1:27: mismatched input ';' expecting {',', 'FROM', 'INTO'}
Caused by: org.antlr.v4.runtime.InputMismatchException
```

Harden allowed SELECT syntax

---

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/test/util/TestKsqlRestApp.java
ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

Enhanced `EmbeddedSingleNodeKafkaCluster` to allow others to inject additional Jaas Config. (Required by other places this is used), and made it so the config can be changed between tests.
Plus, as this class is now exposed to other projects... also hide the constructor and forced used of builder, as this gives us move control.
Also, removed some unnecessary dependencies from `TestKsqlRestApp`.

EmbeddedSingleNodeKafkaCluster to support additional Jaas Config

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java

Fixed a leak where an admin client is not closed.
This was spamming the logs of tests a lot with lines lines:
```
[2018-09-12 16:28:50,033] WARN [AdminClient clientId=adminclient-8] Connection to node 0 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:671)
[2018-09-12 16:28:50,534] WARN [AdminClient clientId=adminclient-5] Connection to node 0 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:671)
[2018-09-12 16:28:50,965] WARN [AdminClient clientId=adminclient-8] Connection to node 0 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:671)
[2018-09-12 16:28:51,573] WARN [AdminClient clientId=adminclient-5] Connection to node 0 could not be established. …
```

Fix leaked admin client

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-cli/src/test/java/io/confluent/ksql/CliTest.java

Fixes #1846
fix issue with parsing SQL files where there is trailing white space after command continuation character '\'.
Added test + manual

Minor: fix issue with parsing SQL files with trailing white space.

---

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java

Checkstyle should comments come in pairs.
If you disable a rule with a comment, but then don't add another comment to turn it back on, then it will be disabled for the rest of the file.  While this is't a problem in this case, I think it is _safer_ to always pair up the comments as this makes it less likely someone will cut & paste the single comment somewhere where it _does_ matter that its not being closed.
Another alternative to suppression comments, which I've just found, is to use annotations. I think this is probably a better approach than comments as its auto-closing, e.g.
```
@SuppressWarnings("checkstyle:methodlength")
public void someLongMethod() throws Exception {
}
```
Scratch that, the IDE plugins don't like suppression filters :(
none - I'm living dangerously

Checkstyle comments come in pairs.

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java

Change the console print command so that it responds to ctrl-c in a timely fashion
Fixes: #1759
Manual testing - loaded up topic and continuous production. Ensured that printing exits almost immediately.

Stop printing the topic output promptly

---

ksql-engine/src/main/java/io/confluent/ksql/function/udaf/sum/DoubleSumKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/sum/LongSumKudaf.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/sum/BaseSumKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/sum/DoubleSumKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/sum/IntegerSumKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/sum/LongSumKudafTest.java

Fix NPE in Long and Double Sum aggregators when a null value is encountered. Rather than throwing an NPE just return the existing aggregate.
Fixes: #1892
Added unit test to ensure all sum aggregators handle null

Handle null in sum aggregates

---

docs/installation/server-config/avro-schema.rst

Expanded discussion of how to use STRUCTS will be addressed in another PR for the [KSQL Syntax Reference](https://docs.confluent.io/current/ksql/docs/syntax-reference.html) page.

DOCS-800: Update note about Avro schemas with nested fields

---

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java

The `CliTest` was temporarily ignored as it was flakey. However, the whole test class was ignored rather than the two flakey tests.  Better to just ignore the minimum we can, (and for as short a time as we can).
Looks like we've already got a regression on `testPrint`... :(
It is a test change.

Enable CLI tests

---

ksql-package/pom.xml

#1875 removed ksql-clickstream-demo, but the dependency in ksql-package wasn't removed.
If you have cached artifacts available, including as we do in CI, this can be easy to miss because the dependency will still be resolved *despite* the fact that the build in this same repository no longer generates it.
Removed all local caches and artifact repositories other than a cache of maven central, built with target `package`, and things all work and don't resolve any clickstream assets other than some avro schemas.

Remove ksql-clickstream-demo dependency from packaging module

---

docs/developer-guide/syntax-reference.rst
docs/index.rst

Forgot to remove references to moved topics in the root index.rst, causing build breakage. Also changed path to the `includes` directory.

KSQL-1656: Fix build error caused by moving topics

---

ksql-engine/src/test/resources/query-validation-tests/simple-struct.json
ksql-serde/pom.xml
ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java
ksql-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonDeserializerTest.java
pom.xml

This PR fixes the regression we had after adding struct support. 
We can now define a struct field as varchar which results in reading the whole filed as a json string.
This will help users to either choose to define a struct structure over a field or use it as string and use `EXTRACTJSONFIELD` udf to fetch specific field.
Note that this will only work for streams/tables with JSON format and is not intended to be used on AVRO format.
This is a fix for #1562 
Unit and integration tests were added.

Struct fields can be read as string.

---

docs/developer-guide/syntax-reference.rst

This patch adds docs that provide info on the metrics returned by describe. The
naming on the failed messages isn't a typo. The only failure we count today is
deserialization failure, and it updates a metric without the the consumer- prefix.
We should fix that, but not on the 5.0.0-post branch

Add docs that describe metrics returned by describe extended

---

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/CommandStatusEntity.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

There are two changes in this PR. (Sorry! `KsqlResourceTest` was just annoying me ;)).
1. Hide the SSL configuration. It's no longer listed in `show properties` and can no longer be `set`.
1. Refactored `KsqlResourceTest` to make the tests more succinct / readable.
I also want to call out the change to `AvroUtil` where I've removed a line:
```
streamsProperties.put(DdlConfig.AVRO_SCHEMA, avroSchemaString);
```
I've removed it because:
- it smells: it's mutating a param passed in that comes from the top level `KsqlResource.handleKsqlStatements`, where it can modify the state passed to future calls.
- it doesn't seem that anything reads the property, ever.
- no tests fail when I remove it.
Let me know if you know of a reason why that's there!
Tests + manual

Hide ssl configs and refactor KsqlResourceTest

---

ksql-package/pom.xml

#1929 removed the dependency on ksql-examples transitively. This means that the `ksql-datagen` tool would no longer work in the packaged ksql artifact, but would fail with the message `Error: Could not find or load main class io.confluent.ksql.datagen.DataGen`.
This also caused the system tests to fail because the test data could not be generated. 
This patch fixes the dependency so that ksql datagen continues to work.
`mvn package` and then checked that `ksql-datagen` worked in the artifact `ksql-package/target/ksql-package-5.1.0-SNAPSHOT-package.tgz`

Add ksql-examples to the ksql package artifact so that datagen continues to work

---

ksql-common/src/main/java/io/confluent/ksql/util/StringUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/StringUtilTest.java
ksql-engine/src/test/resources/query-validation-tests/timestampformat.json

Cherry-pick from master so this is fixed on 5.0.1

#1439 TIMESTAMP_FORMAT does not respect escaping (#1781)

---

docs/developer-guide/udf.rst

Fix doc build warnings by replacing `.. code:: txt` blocks with `::` vanilla text blocks..

KSQL-1708: Fix plaintext code blocks with ::

---

docs/tutorials/docker-compose.yml

About 9 weeks back the commit 47f29cc9 fixed Docker image version references to consistently refer to `5.0.0`, but only in branch `5.0.0-post`.
This was apparently never merged back into `master`.  This PR fixes the inconsistency.

Use version 5.0.0 for KSQL server image

---

docs/installation/installing.rst
docs/tutorials/basics-docker.rst
docs/tutorials/clickstream-docker.rst

Replace `.. code:: bash` blocks with `::` blocks to fix doc build warnings.

KSQL-1709: Replace plaintext code blocks with ::

---

docs/installation/server-config/security.rst

Replace `.. code: bash` blocks with `::` blocks.

KSQL-1707: Fix doc build warnings

---

docs/installation/server-config/config-reference.rst

Replaced `.. code:: bash` blocks with `::` blocks for plaintext.

KSQL-1710: Fix doc build warnings

---

docs/includes/ksql-includes.rst

Use the `codewithvars` block for the KSQL CLI banner to get the version correct.

KSQL-1712: Update KSQL CLI banner block to use codewithvars

---

Jenkinsfile

The hardcoded tag won't work for other branches. Switch to auto-computed tag from https://github.com/confluentinc/jenkins-common/pull/75
Ran test job with new jenkins-common and it correctly use the branch name (https://jenkins.confluent.io/job/mzheng-test-multibranch-pipeline/job/remove-use@4.1.x/1/console). As for PR, it's hard to test Jenkinsfile stuff for PR, but it should work.

Remove hardcoded tag and use default from dockerfile

---

docs/includes/ksql-includes.rst

Rename `create-a-stream-and-table` label to `create-a-stream-and-table-inc`.

KSQL-1718: Fix duplicate label in sql-includes.rst

---

docs/includes/ksql-includes.rst
docs/tutorials/basics-docker.rst
docs/tutorials/basics-local.rst

Remove prepended `__` from labels, which were generating malformed links.

KSQL-1718: Fix build warnings in ksql-includes.rst

---

docs/developer-guide/syntax-reference.rst
docs/tutorials/examples.rst

Some labels had drifted around and become detached from their corresponding headings. Also, re-added the command-line section which seems to have gotten lost in the transition from `4.1.2-post`.

KSQL-1723: Fix misplaced labels

---

ksql-common/src/main/java/io/confluent/ksql/metrics/TopicSensors.java
ksql-common/src/test/java/io/confluent/ksql/metrics/TopicSensorsTest.java

Switch the format for the timestamp on statistics to be unambiguous.  Output is now:
```
Local runtime statistics
------------------------
...    last-message: 2018-10-06T16:17:17.782Z
```
Fixes #2002
Added test.

Display stats timestamps in unambiguous format.

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/test/resources/query-validation-tests/sum.json

This is a temporary fix for handling literal as arguments in aggregate functions. This fixes #1895. 
We had the limitation of having at most two arguments for aggregate functions where the second one is literal. This patch fixes the regression but does not remove the limitation. 
Removing the limitation needs more thorough work that should be done in future.
added integration tests.

Fix the regression for literal aggregate argument.

---

ksql-common/src/main/java/io/confluent/ksql/errors/LogMetricAndContinueExceptionHandler.java
ksql-common/src/main/java/io/confluent/ksql/metrics/ConsumerCollector.java
ksql-common/src/main/java/io/confluent/ksql/metrics/MetricCollector.java
ksql-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java
ksql-common/src/main/java/io/confluent/ksql/metrics/MetricUtils.java
ksql-common/src/main/java/io/confluent/ksql/metrics/ProducerCollector.java
ksql-common/src/main/java/io/confluent/ksql/metrics/StreamsErrorCollector.java
ksql-common/src/test/java/io/confluent/ksql/metrics/ConsumerCollectorTest.java
ksql-common/src/test/java/io/confluent/ksql/metrics/MetricCollectorsTest.java
ksql-common/src/test/java/io/confluent/ksql/metrics/ProducerCollectorTest.java
ksql-common/src/test/java/io/confluent/ksql/metrics/StreamsErrorCollectorTest.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksql-engine/src/test/resources/query-validation-tests/average.json
ksql-metastore/src/main/java/io/confluent/ksql/metastore/StructuredDataSource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionTest.java

This patch refactors the metrics collection code a bit, and fixes some
bugs along the way:
Clean up the MetricCollector interface. The functions that actually collect
metrics can be left out of this interface - they are specific to the type of
collector. It really should just be an interface for MetricCollectors to
query metrics values from.
Rather than codifying the different metrics into their own functions, access
them by string constants. This reduces the boilerplate needed for adding new
metrics.
Move error collection metrics into a new collector - StreamsErrorCollector.
StreamsErrorCollector is invoked directly from the streams error handler. There
is an instance for each running streams app that has hit an error. This change
ensures that error metric counts are associated with …

Metrics refactor + fix a couple issues

---

ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java

This corrects the expected parameter type supplied to KTable groupby in the `shouldGroupKeysCorrectly` test. The previous PR https://github.com/confluentinc/ksql/pull/2035 could not be properly validated because of upstream dependency issues.
All `mvn package` tests pass.

MINOR: Corrects expected groupby parameter type in test.

---

docs/includes/ksql-includes.rst
docs/tutorials/basics-docker.rst

There were a few wonky indents and also a bug I introduced when I refactored `start-after/end-before` symbol names.

KSQL-1760: Fix text block indents and incorrect include symbols

---

ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/RegisterTopicCommand.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/StructuredDataSourceNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/KsqlTopic.java
ksql-metastore/src/test/java/io/confluent/ksql/metastore/MetastoreTest.java
ksql-metastore/src/test/java/io/confluent/ksql/util/MetaStoreFixture.java
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

Added a new flag to the ksql topic in the metastore indicating if it is used as a sink topic in KSQL or not.
Only topics corresponding to the sink stream/tables that are created using CSAS/CTAS statements will have true value for the flag.
Added unit test.

Added `isKsqlSink` flag to the KSQL topics in the metastore.

---

pom.xml

We need the new version to be able to bump to a later version of commons-collections, which in turn has several security vulnerabilities. 
```
Apache Commons Collections 3.2.1 apachecommonscollections1429984 2051354 CVE-2017-15708 High confluent-5.0.0-2.11.tar.gz/confluent-5.0.0/share/java/ksql commons-collections-3.2.1.jar Retired
Apache Commons Collections 3.2.1 apachecommonscollections1429984 2051354 CVE-2017-15708 High confluent-5.0.0-2.11.tar.gz/confluent-5.0.0/share/java/ksql commons-collections-3.2.1.jar Divest
Apache Commons Collections 3.2.1 apachecommonscollections1429984 2051354 CVE-2015-6420 High confluent-5.0.0-2.11.tar.gz/confluent-5.0.0/share/java/ksql commons-collections-3.2.1.jar Retired
Apache Commons Collections 3.2.1 apachecommonscollections1429984 2051354 …
```

Bump airline version to 2.6.0

---

docs/developer-guide/syntax-reference.rst
ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-common/src/main/java/io/confluent/ksql/util/timestamp/StringToTimestampParser.java
ksql-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/DateToString.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToDate.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToTimestamp.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/TimestampToString.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/DateToStringTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToDateTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToTimestampTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/TimestampToStringTest.java
ksql-engine/src/test/resources/query-validation-tests/datestring.json
ksql-engine/src/test/resources/query-validation-tests/stringdate.json
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

Added `stringtodate` and `datetostring` UDFs to convert to and from a formatted date string and an integer representing days since epoch. This format is used by Kafka Connect to represent Date objects with no time or time zone component.
In a separate commit on the same PR I also updated `stringtotimestamp` and `timestamptostring` to use the new UDF api and to support dynamically supplied format patterns.
Added tests for all new functionality and ran locally. Generated and views updated docs locally.

 Added stringtodate and datetostring UDFs

---

docs/capacity-planning.rst
docs/faq.rst
docs/installation/installing.rst
docs/installation/server-config/avro-schema.rst
docs/installation/server-config/config-reference.rst
docs/installation/server-config/security.rst
docs/syntax-reference.rst
docs/tutorials/examples.rst

In-page TOCs aren't necessary now, since the docs site has floating in-page nav in the right column. Remove all `.. contents::` blocks.

Remove in-page TOCs

---

docs/tutorials/index.rst

The Clickstream demo repo has moved from `quickstart-demos` to `examples`.

DOCS-909: Update link to examples repo in GitHub

---

docs/developer-guide/syntax-reference.rst
ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
ksql-common/src/main/java/io/confluent/ksql/util/timestamp/StringToTimestampParser.java
ksql-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/DateToString.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToDate.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToTimestamp.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/TimestampToString.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/DateToStringTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToDateTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToTimestampTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/TimestampToStringTest.java
ksql-engine/src/test/resources/query-validation-tests/datestring.json
ksql-engine/src/test/resources/query-validation-tests/stringdate.json
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

Added `stringtodate` and `datetostring` UDFs to convert to and from a formatted date string and an integer representing days since epoch. This format is used by Kafka Connect to represent Date objects with no time or time zone component.
In a separate commit on the same PR I also updated `stringtotimestamp` and `timestamptostring` to use the new UDF api and to support dynamically supplied format patterns.
This is #1890 cherry picked for the 5.1.x branch.
Added tests for all new functionality and ran locally. Generated and views updated docs locally.

Added stringtodate and datetostring UDFs for 5.1.x

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java

This patch updates KsqlConfig to preserve originals when mergine the
config with the persisted configs. This ensures that udf settings get
applied

Preserve originals when merging configs

---

docs/developer-guide/syntax-reference.rst
docs/tutorials/examples.rst
ksql-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/placeholder/PlaceholderTableUdaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/window/WindowEndKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/window/WindowSelectMapper.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/window/WindowStartKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/ProjectNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/QueuedSchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SelectValueMapper.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/SelectExpression.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderUtil.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/placeholder/PlaceholderTableUdafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/window/WindowEndKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/window/WindowSelectMapperTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/window/WindowStartKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/ProjectNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SelectValueMapperTest.java
ksql-engine/src/test/resources/query-validation-tests/window-bounds.json

* add WindowStartTime UDAF
(cherry picked from commit 82b603d)
Original PR: #1993

Add WindowStart and WindowEnd UDFs (#1993)

---

ksql-common/src/main/java/io/confluent/ksql/function/AggregateFunctionArguments.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/test/java/io/confluent/ksql/function/KudafUndoAggregatorTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfCompilerTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/TopKDistinctTestUtils.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java

While working on the group by stuff I noticed the weird pattern in `AggregateFunctionArguments` where it is passed a map in its constructor, only get a single value from it using another passed in arg:
```
public AggregateFunctionArguments(
final Map<String, Integer> expressionNames,
final List<String> args) {
this.udafIndex = expressionNames.get(args.get(0));  <-- only use of expressionNames, which can be moved into the calling code. 
this.args = ImmutableList.copyOf(args);
}
```
So, changed this to just take the index!
Also noticed that the `AggregateNode` wasn't deduplicating non-aggregate source fields. This line of code:
```
.filter(e -> !internalNameToIndexMap.containsKey(e.toString()))
```
Was trying to de-dup by matching the string form of an expression to the internal column name …

Clean up aggregate function and remove duplicate columns from aggregate select mapper

---

ksql-common/src/main/java/io/confluent/ksql/util/RetryUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/RetryUtilTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/test/util/TestKsqlRestApp.java

This patch changes CommandRunner to retry commands when it hits an error that
may not be hit by other KSQL servers. If it just ignores such errors, the servers
in a cluster could become inconsistent. The number of retries is controlled by a
config that defaults to INT_MAX. We set it to a lower number for tests to ensure
we dont accidentally hang while running tests.
Unit tests

Retry commands on unexpected exceptions

---

ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/QueryTranslationTest.java
ksql-engine/src/test/java/io/confluent/ksql/SchemaTranslationTest.java
ksql-engine/src/test/java/io/confluent/ksql/TopologyFileGenerator.java

This PR looks to change the names of two types used by the QueryTranslationTest (and the schema one) to better suit what they are, avoiding confusion.
* `TestCase` has been renamed `JsonTestCase` as it holds the Json node containing a test case.
* `Query` has been renamed `TestCase` as that it was it is - the set of data pertaining to one test case.

Minor: Rename objects in QueryTranslationTest to avoid confusion

---

docs/developer-guide/syntax-reference.rst

This is a cherry pick to add the removed commit. This brings back the following PR to the upper branches: #1832 
(git cherry-pick 74e47d54bf20c25cc88a118640d25d1e0e07229b)

Currently we don't support AS for aliasing stream/table.

---

docs/faq.rst
docs/includes/ksql-includes.rst
docs/tutorials/basics-docker.rst
docs/tutorials/clickstream-docker.rst
docs/tutorials/examples.rst

Left in the `$` char for commands that require editing, like:
```
.. code:: bash
$ KSQL_OPTS="-Djavax.net.ssl.trustStore=<path-to-trust-store> -Djavax.net.ssl.trustStorePassword=<store-password>" ksql-server-start <path-to-confluent>/etc/ksql/ksql-server.properties
```
Also, left in the `ksql>` prompt where it makes sense, and removed it from pure query strings that you might actually copy.

Remove $ chars and ksql> prompts for example commands

---

findbugs/findbugs-exclude.xml

This is a workaround for the following issue using spotbugs and Java 11
https://github.com/spotbugs/spotbugs/issues/756

disable spotbugs false-positive with Java 11

---

ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/TopicConsumer.java

A couple of issues were causing this test to be unstable:
- `testPrint` wasn't ensuring its test thread was stopped, so it could continue to output during other tests.
- terminateQuery wasn't reliable.  Code now parses the error message to get query ids. (https://github.com/confluentinc/ksql/issues/2177 would help here). 
- Consumers used by different tests were using the same consumer group, which led to issues with timeouts and general instability in the group.
I'll look to cherry pick these fixes into 5.1. and 5.0

Fix flaky CliTest

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockApplication.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

Related to PR #2184, which fixes the same thing in master. This is a more minimal change to fix a flaky: `KsqlRestClientTest.shouldInterruptScannerOnClose`.
The PR also makes a change to `MockApplication` to swallow any exceptions while stopping. This is because it occasionally throws a `TimeoutException`.  As it is test only code and a quick debug didn't flag up anything obvious, I've changed the code to swallow the issue.
Test only change.  Ran it over a thousand times without failure.

5.0.x fix flaky

---

ksql-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java

We're seeing the occasional failure of integration tests due to ZK timeouts. The default is 6 seconds, which is pretty low.  We're not testing Kafka / ZK here, so this PR increases the timeout to 30s to allow for overloaded / low spec build servers and long GCs.

Increase ZK timeout to stabalise integration tests.

---

docs/developer-guide/syntax-reference.rst

Somewhere along the way, some text in the CSAS and CTAS sections got removed, so it put it back. What's weird is that the missing text wasn't missing on the live site; also the CSAS properties table was ONCE AGAIN MUNGED. I don't know how many times I've fixed that. So I'm at a loss to explain these things. :(

KSQL-1957: Add links to new topics; also restore missing CSAS and CTAS text

---

ksql-cli/src/main/java/io/confluent/ksql/Ksql.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/test/util/TestKsqlRestApp.java
ksql-version-metrics-client/pom.xml
ksql-version-metrics-client/src/main/avro/KsqlVersionMetrics.avsc
ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/ActivenessRegistrar.java
ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java
ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionCheckerAgent.java
ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/collector/BasicCollector.java
ksql-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/KsqlVersionCheckerAgentTest.java
ksql-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/VersionCheckerIntegrationTest.java
ksql-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/collector/BasicCollectorTest.java

This PR brings the version checker improvement to 5.1.x. The improvements were initially merged into master but we want to include it in 5.1 release.
The original PR that was merged into master is #2020 .

Bring version checker improvements to 5.1.x

---

ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionMetadataTest.java

Use a thread-local to store the parameter array built by ExpressionMetadata
to pass in to the expression evaluator. This patch also includes a unit test
for ExpressionMetadata, with a test to ensure we build the parameters in a
thread-safe way.
Unit test for ExpressionMetadata

Make ExpressionMetadata thread-safe

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java

Currently, if you execute a RUN SCRIPT where the script contains a persistent query, then try to restart the KSQL server, the server will fail to restart. This happens because recent changes we introduced to the recovery logic result in the server attempting to start the persistent query created by the RUN SCRIPT twice, resulting in the following error:
```
[2018-12-12 19:59:46,205] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:47)
java.lang.IllegalStateException: Can only set StateListener in CREATED state. Current state is: REBALANCING
at org.apache.kafka.streams.KafkaStreams.setStateListener(KafkaStreams.java:332)
at java.util.Optional.ifPresent(Optional.java:159)
at io.confluent.ksql.util.QueryMetadata.start(QueryMetadata.java:183)
at …
```

MINOR: Fix bug encountered when restoring RUN SCRIPT command.

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/CommentStripper.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/JLineReader.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/KsqlLineParser.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/CommentStripperTest.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/JLineReaderTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java

Following on from @vcrfxia insights in the last pr: https://github.com/confluentinc/ksql/pull/2214#pullrequestreview-180072120, this PR adds more improvements to the way the CLI handles inline comments.
It can now handle something like this example being cut and paste into the CLI:
```sql
SELECT -- a comment
-- another comment
foo, -- cos we really like comments
-- can't get enough of 'em
bar -- love'em
-- best thing since sliced bread
FROM -- better than fake news
x;
```
To support I've enhanced the `CommentStripper` to handle multi-line statements with embedded comments.
I've also had to switch the `JLineReader` to _not_ replace new lines with spaces. So if the input contains multiple lines, so does the output. But the parser is fine with this.  History also still works, though a single …

More improvements to the way CLI handles comments in multi-line statements

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java

Effectively re-opens https://github.com/confluentinc/ksql/pull/2263, which was reverted as it was merged prematurely.

MINOR: Fix bug encountered when restoring RUN SCRIPT command. (again)

---

docs/developer-guide/syntax-reference.rst
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/count/CountKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/DoubleMaxKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/LongMaxKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/min/DoubleMinKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/min/LongMinKudaf.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/count/CountKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/max/DoubleMaxKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/max/IntegerMaxKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/max/LongMaxKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/min/DoubleMinKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/min/IntegerMinKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/min/LongMinKudafTest.java

Fixes #2244 by adding the appropriate checks to ignore `null` values.
- add `null` checks to min and max UDAFs for `Double` and `Long` and count UDAF so `null` values do not impact those aggregations.
- Change min and max UDAFs for `Double` and `Long` to use `Math.min()` and `Math.max()` to be consistent with `Integer` UDAFs.
- add documentation for aggregate function handling of `null` values.
Unit tests added to test `null` values for each combination where checks were added. 
Manual testing building ksql-server and client:
- tested original `min(<column>)`, `max(<column>)`,  and `count(<column>) for `Double` with `null` columns and verified no longer encountering `NullPointerException` and that correct value is returned.
- verify that `count(*)` returns count of all rows, including …

Add null checks to min, max, and count UDAFs

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlRestException.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KsqlErrorMessageMatchers.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlRestExceptionMatchers.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/CommandStoreUtilTest.java

Add some matchers for `KsqlRestException` and `KsqlErrorMessage`
(Mainly as an example of how to do this)

Minor: add Hamcrest matchers for KsqlRestException and KsqlErrorMessage

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java

Remove the map in `getRestoreCommands` as it is not used anymore

[MINOR]: remove unused map from command store `getRestoreCommands`

---

ksql-test-util/pom.xml

Tests that import `TestKsqlRestApp` on 5.1.x need the dependency on easymock (same as it's imported on `master` branch currently
_Ran unit tests on this repo as well as dependent repos importing `TestKsqlRestApp`_

MINOR: Backport easymock dependency on ksql-test-util to 5.1.x

---

ksql-engine/src/test/java/io/confluent/ksql/function/InternalFunctionRegistryTest.java

As discussed in https://github.com/confluentinc/ksql/pull/1492, UDF names must be registered in uppercase. This test case will verify that such new UDFs are correctly registered.
A new test case is added that verifies UDF names are registered with uppercase letters.
New unit test.

Add test to verify built-in UDF names are registered in uppercase

---

ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/MaskKeepLeftKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/MaskKeepRightKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/MaskLeftKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/MaskRightKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/Masker.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/string/MaskKeepLeftKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/string/MaskKeepRightKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/string/MaskLeftKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/string/MaskRightKudfTest.java

Move duplicated validateParams() method to the Masker class.
This commit is part of the PR-1504 (https://github.com/confluentinc/ksql/pull/1504)
Do minor cleanup on the mask classes by removing a duplicated validation method, and move it
to the Masker class.
All unit tests passed locally.

minor cleanup of string-masking UDF param handling

---

docs/developer-guide/syntax-reference.rst
ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/resources/query-validation-tests/between.json

This is standard SQL that users would expect to be supported, which
makes queries that compare ranges easier to read. See #1004 
Introduce support for BETWEEN, for queries such as 
```
SELECT * FROM topic WHERE field BETWEEN valA AND valB
```
The BETWEEN operation follows convention in that the range is *inclusive* of the endpoints. Any `null` values will immediately fail the between range (in either the field or either of the endpoints). Similar to comparisons, either literals or field references may be used in the limits.
*Open Question:* Should we support comparisons with dates?
- Unit testing
- Integration testing with `between.json`

Add KSQL support for BETWEEN in predicates #1004.

---

ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/QueryTranslationTest.java
ksql-engine/src/test/java/io/confluent/ksql/SchemaTranslationTest.java

The new parameter accepts a list of comma separated JSON test files to execute. This parameter allows developers to specify their own tests to execute and make debugging faster.
Example:
Execute a single test called 'sum.json'
`mvn test -pl ksql-engine -Dtest=QueryTranslationTest -Dksql.test.files=sum.json`
Execute multiple tests called 'sum.json' and 'substring.json'
`mvn test -pl ksql-engine -Dtest=QueryTranslationTest -Dksql.test.files=sum.json,substring.json`
Execute all tests:
`mvn test -pl ksql-engine -Dtest=QueryTranslationTest`
The same parameter works for `SchemaTranslationTest`.
The same QueryTranslationTest and SchemaTranslationTest validate that all tests are executed.
I also executed the example commands manually to verify they are working correctly.

Add a QueryTranslationTest command parameter to specify tests to execute

---

docs/developer-guide/syntax-reference.rst
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/SplitKudf.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/string/SplitKudfTest.java
ksql-engine/src/test/resources/query-validation-tests/split.json

This fixes https://github.com/confluentinc/ksql/issues/2349
A new UDF function SPLIT(string, delimiter) is added that splits a string into an array of substrings using the given delimiter. The below behavior is similar (if not identical) to other RDBMS that handle the split() function.
Example:
Having a record with col1 using the string 'x-y-z', the following spit() method creates the array [x, y, z]:
`SELECT split(message, '-')[0] as s1 , split(message, '-')[2] as s2 FROM stream;`
|s1| s2|
|---|---|
|x|z|
The UDF split() only accepts literals as delimiter. Regular expressions use a different API implementation, so we could leave such behavior in a future REGEX_SPLIT() or something.
If the delimiter is found at the beginning of the string, end of the string, or there are contiguous …

Add UDF split() that splits a message by a given delimiter.

---

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java

This fixes https://github.com/confluentinc/ksql/issues/2032
Any type of arithmetic expression inside a CAST() function that uses different parameters types than the one to return for casting resulted in an error while attempting to do the type conversion.
Example:
- ROWTIME is a BIGINT column to be cast to DOUBLE
Works
```
ksql> SELECT CAST(ROWTIME AS DOUBLE) - CAST(ROWTIME AS DOUBLE) FROM ATM_TXNS_GESS_02 ;
0.0
0.0
```
Doesn't work:
ROWTIME is a BIGINT column to be cast to DOUBLE
```
ksql> SELECT CAST((ROWTIME - ROWTIME) AS DOUBLE) FROM ATM_TXNS_GESS_02 ;
Code generation failed for SelectValueMapper
Caused by: Line 1, Column 55: Assignment conversion not possible from type "long" to type "java.lang.Double"
```
The reason is that SqlToJavaVisitor.visitArithmeticBinary() was always …

Allow CAST() to evaluate numeric arithmetic expressions

---

docs/developer-guide/udf.rst
ksql-engine/pom.xml
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/DateToString.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToDate.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToTimestamp.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/TimestampToString.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/SplitKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/Substring.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksql-udf/src/main/java/io/confluent/ksql/function/udf/UdfParameter.java

If the class file was compiled with java8's `-parameter` flag, the name of the parameter will be inferred from the method declaration. This reduces clutter when reading/writing UDF classes.
- Unit tests

Remove requirement for "value" parameter in UdfParameter annotation

---

ksql-cli/src/test/java/io/confluent/ksql/cli/BasicAuthFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java

This fixes the flakiness of `WindowingIntTest`, which used to produce records with a fixed timestamp that resolved to `Sunday, September 9, 2001 1:46:45.001 AM`. This caused issues because topic retention defaults to 7 days and log compaction could happen while we were running the test, thereby deleting the messages before we could poll them. This fix dynamically assigns a time that ensures the messages are not cleaned up.
- I tried to change the topic retention to infinite for the orders stream, but the problem is that KStreams creates some of the internal topics and piping through that config would be out of scope. 
- I also tried setting the config to use the time it was appended to the log instead of produce record timestamp, but this breaks the unit tests that verify …

fix flaky retention bug in WindowingIntTest

---

docs/developer-guide/processing-log.rst
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogServerUtils.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/ProcessingLogServerUtilsTest.java

- Fix the log4j config examples in the docs for logging to Kafka to
use the name kafka_appender to avoid clashing with the appender we
use for kafka libraries.
- Document how the default processing log topic name is computed
- Return a PreparedStatement from processingLogStreamCreateStatement
instead of a String
- Switch the auto create configs to boolean
- Add a test to verify we dont create the log topic if not configured

Fix late/missed review comments/feedback from processing logger prs

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java

Fixes: #2420 
Without this PR calling `KsqlEngine.parseStatements(sql)` will throw if the `sql` contains a TERMINATE statement that _should_ terminate any queries required by a later `DROP STREAM` statement.
This PR fixes this.
Manual and added tests.

Support related TERMINATE and DROP in single parse request.

---

ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java
ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/FilterNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlBareOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/PlanNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/ProjectNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/FilterNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlBareOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/OutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/ProjectNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/StructuredDataSourceNodeTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionTest.java

When building the physical plan, we pass around KsqlConfig as well as the overridden
properties supplied by the client. This is unnecessary, since KsqlConfig has already
been updated to reflect the property overrides. This patch cleans this up so that we
just use KsqlConfig.
No new functionality so the existing tests should suffice.

Clean up how we pass configs around when building the physical plan

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/CommandStatusEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/Errors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/CommandStoreUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/CommandStoreUtilTest.java

Fixes: #2197
This PR adds support for multi-line rest requests where later non-distributed statements are dependant on former distributed statements, e.g.
```sql
CREATE STREAM S AS SELECT * FROM SOMETHING;
DESCRIBE S;
```
Here the CSAS call is distributed to the command topic and then the `DESCRIBE` call is handled by the rest api. This change ensures the CSAS statement has been processed by the main engine thread _before_ processing the `DESCRIBE` call.
Tests added and manual

Rest API: support for multi-line interdependent requests.

---

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateStreamCommand.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateTableCommand.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/RegisterTopicCommand.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateStreamCommandTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateTableCommandTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/RegisterTopicCommandTest.java

This fixes https://github.com/confluentinc/ksql/issues/2374
If a Stream already exists with the same name, the error message returned uses the term Topic, which is incorrect.
```
ksql> CREATE STREAM PCAP (layers struct<frame struct<frame_frame_interface_id varchar>>) WITH (KAFKA_TOPIC='localPCAP', VALUE_FORMAT='JSON');
Topic already registered: PCAP
```
This patch changes the message to be:
```
ksql> CREATE STREAM PCAP (layers struct<frame struct<frame_frame_interface_id varchar>>) WITH (KAFKA_TOPIC='localPCAP', VALUE_FORMAT='JSON');
Stream already exists: PCAP
```
One test case added to the `CreateStreamCommandTest` class.

Display correct message error when a stream is already created.

---

docs/developer-guide/api.rst
docs/developer-guide/processing-log.rst
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ClusterTerminator.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogServerUtils.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/ClusterTerminatorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/ProcessingLogServerUtilsTest.java

Extends the cluster cleanup handler to take a list of topics managed by the ksql
cluster that must be deleted when the cluster terminates. This gets initialized to
include the command topic, as well as the processing log topic if one is configured.
added a unit test

Include processing log topic in cluster cleanup

---

docs/changelog.rst
docs/developer-guide/syntax-reference.rst
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksql-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/url/UrlDecodeParamKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/url/UrlEncodeParamKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/url/UrlExtractFragmentKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/url/UrlExtractHostKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/url/UrlExtractParameterKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/url/UrlExtractPathKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/url/UrlExtractPortKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/url/UrlExtractProtocolKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/url/UrlExtractQueryKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/url/UrlParser.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlDecodeParamKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlEncodeParamKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlExtractFragmentKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlExtractHostKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlExtractParameterKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlExtractPathKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlExtractPortKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlExtractProtocolKudfTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/url/UrlExtractQueryKudfTest.java
ksql-engine/src/test/resources/query-validation-tests/url.json
ksql-udf/src/main/java/io/confluent/ksql/function/udf/UdfDescription.java

Adds a new suite of URL processing functionalities to KSQL. These functionalities primarily target use cases involving clickstream data, but any data munging involving URIs can be benefitted from first-class support of these methods.
This was previously #1492 but was restructured to (1) target 5.1.x and (2) change usage of `KUdf` to `@UdfDescription`.
- Unit tests for each new UDF
- Added url.json to the QueryTranslationTest
- Checkstyle tests
- Ran full integration-test

Introducing a new family of url functions. replaces #1492

---

docs/changelog.rst
docs/developer-guide/syntax-reference.rst
ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-parser/pom.xml
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/PrintTopic.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Query.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/QuerySpecification.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PollingSubscription.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PrintPublisher.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriter.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/PollingSubscriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/PrintSubscriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamingTestUtils.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriterTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
pom.xml

See discussion on #1316 - this adds support to "early terminate" PRINT queries. This is especially helpful for starters and for demos.
Fixes #1316 
- Unit Testing
- Various tests with CLI: `PRINT 'topic' FROM BEGINNING LIMIT 1`, `PRINT 'topic' FROM BEGINNING INTERVAL 2 LIMIT 2`, `PRINT 'topic' FROM BEGINNING LIMIT ALL`, (failure case) `PRINT 'topic' FROM BEGINNING LIMIT FOOBAR`
Checked through C3 that the LIMIT/INTERVAL statements work - set deubg log statement and issued the following two queries:
```
PRINT 'pageviews' FROM BEGINNING LIMIT 3;
PRINT 'pageviews' FROM BEGINNING INTERVAL 2 LIMIT 3;
```
And got the following results:
```
[2/1/19 11:55:07 AM PST, 1, {"viewtime": 1, "userid": "User_4", "pageid": "Page_73"}
, 2/1/19 11:55:07 AM PST, 11, {"viewtime": 11, "userid": "User_3", …
```

Support LIMIT clause for PRINT statements. Resolves #1316

---

ksql-benchmark/README.md
ksql-benchmark/src/main/java/io/confluent/ksql/benchmark/SerdeBenchmark.java

This PR adds instructions around how to run the serde JMH benchmarks, and also records results from 20 runs on an r5.xlarge EC2 instance. This PR also adjusts some of the benchmark parameters (specifically, the number of forks and iterations) so that `SerdeBenchmark.java` now only takes 24 minutes to run.
Only non-documentation change is the tweaking of benchmark parameters.

Add ksql-benchmark README (baseline results and how to run)

---

ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/SingleColumn.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java

Consider stream `X` with fields `A` and `B`. Previously, the following semantics would hold:
```java
// Statement statement = resolve("SELECT * FROM X");
print(SqlFormatter.formatSql(statement));
> SELECT X.ROWTIME "ROWTIME", X.ROWKEY "ROWKEY", X.A "A", X.B "B" FROM X X;
```
The new behavior replaces all of the select items that came from a `*` with `*`, for example:
```java
// Statement statement = resolve("SELECT *, A AS ONE FROM X");
print(SqlFormatter.formatSql(statement));
> SELECT *, X.A "ONE" FROM X X;
```
In order to support #2436, we need to make sure that `SELECT *` statements do not expand to include ROWKEY/ROWTIME. Fixing the root cause of this behavior is tricky and perhaps backwards incompatible (see discussion https://github.com/confluentinc/ksql/pull/2436#discussion_r257433 …

Preserve '*' when formatting a 'SELECT *' statement

---

config/ksql-server.properties
config/log4j-rolling.properties
docs/changelog.rst
docs/developer-guide/processing-log.rst

Adds default configs for the processing logger that enables the log to write to kafka.
This way, when you use ksql out-of-the-box, it should just work.
Also adds a release note

Release notes + default configs for processing logger

---

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/AbstractCreateStreamCommand.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandIdAssigner.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandQueue.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

Three minor changes contained in this patch:
1. Remove validation from CommandIDAssigner since it doesn't really make sense to have it there and this validation was already being done in various other places.
2. Add tests to ensure removed code didn't affect functionality (and increased coverage)
3. Added javadoc to `CommandQueue` interface
Added new unit tests

Remove validation and dependency on metastore from CommandIDAssigner

---

ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java

Currently, the way KSQL determines the value of `delete.topic.enable` for a given Kafka cluster is by getting a list of broker configs and returning whether there exists a config called `delete.topic.enable` with value `true`. This means if `delete.topic.enable` isn't included the list of configs returned by the broker, KSQL will not try to delete topics. However, it's better that KSQL make an attempt to delete topics in this case, especially since the default value of `delete.topic.enable` for brokers is true.
This PR updates KSQL to use the config value if `delete.topic.enable` is present in the list of broker configs, otherwise `true` (the default value of the config).
Unit tests and manual.

Minor: default to true when delete.topic.enable is not returned with broker configs

---

ksql-engine/src/main/java/io/confluent/ksql/function/udf/json/ArrayContainsKudf.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/json/ArrayContainsKudfTest.java
ksql-engine/src/test/resources/query-validation-tests/arraycontains.json

Fixes #1960
This fixes an issue when using ARRAYCONTAINS() with an ARRAY inside a STRUCT.
For example, this below stream with a `STRUCT<colours ARRAY<VARCHAR>>` field.
```
ksql> CREATE STREAM NESTED_ARRAY_TEST (id BIGINT, first_name VARCHAR, last_name VARCHAR, email VARCHAR, preferred STRUCT<colours ARRAY<VARCHAR>>) WITH (kafka_topic='nested_array_test', value_format='JSON');
```
If a SELECT ... ARRAYCONTAINS(PREFERRED->COLOURS,'Pink') ... is used, then the following error happens:
```
ksql> SELECT FIRST_NAME, PREFERRED->COLOURS FROM NESTED_ARRAY_TEST WHERE ARRAYCONTAINS(PREFERRED->COLOURS,'Pink');
Failed to generate code for filterExpression:ARRAYCONTAINS(FETCH_FIELD_FROM_STRUCT(NESTED_ARRAY_TEST.PREFERRED, 'COLOURS'), 'Pink') schema:org.apache.kafka.connect.data.SchemaBuilder@76ea44ac …
```

Allow ArrayContainsKudf to search values on arrays inside a struct.

---

ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/AbstractCreateStreamCommandTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateStreamCommandTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateTableCommandTest.java
ksql-engine/src/test/java/io/confluent/ksql/schema/inference/DefaultSchemaInjectorTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/ExpressionFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Array.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Map.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/PrimitiveType.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Struct.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Type.java
ksql-parser/src/main/java/io/confluent/ksql/util/TypeUtil.java
ksql-parser/src/test/java/io/confluent/ksql/parser/ExpressionFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/rewrite/StatementRewriterTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/util/TypeUtilTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

This PR is nothing more than a rename of the `KsqlType` enum to `SqlType`.  Why? Because the enum is a list of the SQL types we support, and so should IMHO have a name to match.
KSQL has three main type systems:
- SQL, e.g. `INT` `BIGINT`, `DOUBLE`, `MAP`, etc.
- Logical, corresponding `Schema` mappings for the above type, with all fields optional.
- Schemas relating to serialization, e.g. the Connect schema, Avro schema, etc.
Historically, the lines and naming between these type systems was pretty blurred in the code, and I think this simple rename helps clarify these are specifically SQL types and not some other KSQL type.
Are you convinced? :D
Well, it compiles...

Minor: Rename `KsqlType` to `SqlType`

---

docs/capacity-planning.rst
docs/faq.rst
docs/includes/ksql-supported-versions.rst
docs/index.rst
docs/installation/check-ksql-server-health.rst
docs/installation/installing.rst
docs/installation/server-config/avro-schema.rst
docs/installation/server-config/config-reference.rst
docs/installation/server-config/security.rst
docs/operations.rst
docs/quickstart.rst
docs/syntax-reference.rst
docs/troubleshoot-ksql.rst
docs/tutorials/basics-docker.rst
docs/tutorials/basics-local.rst
docs/tutorials/examples.rst
docs/tutorials/generate-custom-test-data.rst
docs/tutorials/index.rst

For the first use of "Kafka" on a page, per new [Naming Guidelines](https://www.confluent.io/apache-guidelines#naming_guidelines).

KSQL-2261: Replace 'Apache Kafka' literals with token

---

docs/changelog.rst
docs/concepts/ksql-architecture.rst
docs/faq.rst
docs/installation/upgrading.rst

This patch adds documentation about upgrade compatibility:
- Release notes that raise the new compatibility config topic for headless mode
- Upgrade docs that specify the properties that must be set for headless mode when
upgrading. Note that docs for the individual configs are omitted since they really
should just be internal properties

Add docs about upgrade compatibility

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java
ksql-engine/src/test/resources/query-validation-tests/multiple-avro-maps.json
ksql-serde/src/main/java/io/confluent/ksql/serde/avro/AvroDataTranslator.java
ksql-serde/src/main/java/io/confluent/ksql/serde/avro/KsqlAvroTopicSerDe.java
ksql-serde/src/test/java/io/confluent/ksql/serde/avro/AvroDataTranslatorTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlGenericRowAvroSerializerTest.java

This patch adds names to map schemas when serializing avro. Internally,
the avro converter will use this name to name the map entry type. This
fixes the issue where, when a schema has multiple maps with different
types, avro errors out because the same name is used for different
map entry record schemas

Adds a name to map schemas

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java

There was inconsistent behavior with PRINT TOPIC. Now if you `SET 'auto.offset.reset'='earliest'`, the command will show the topics from the beginning! Full behavior described in #791.
- Local testing - the below was done without producing anything to the topic
```
===========================================
=        _  __ _____  ____  _             =
=       | |/ // ____|/ __ \| |            =
=       | ' /| (___ | |  | | |            =
=       |  <  \___ \| |  | | |            =
=       | . \ ____) | |__| | |____        =
=       |_|\_\_____/ \___\_\______|       =
=                                         =
=  Streaming SQL Engine for Apache Kafka® =
===========================================
Copyright 2017-2018 Confluent Inc.
CLI v5.3.0-SNAPSHOT, Server v5.3.0-SNAPSHOT located at …
```

PRINT now respects auto.offset.reset in CLI (fixes #791)

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java
ksql-engine/src/test/resources/query-validation-tests/multiple-avro-maps.json
ksql-serde/src/main/java/io/confluent/ksql/serde/avro/AvroDataTranslator.java
ksql-serde/src/main/java/io/confluent/ksql/serde/avro/KsqlAvroTopicSerDe.java
ksql-serde/src/test/java/io/confluent/ksql/serde/avro/AvroDataTranslatorTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlGenericRowAvroSerializerTest.java

This patch adds names to map schemas when serializing avro. Internally,
the avro converter will use this name to name the map entry type. This
fixes the issue where, when a schema has multiple maps with different
types, avro errors out because the same name is used for different
map entry record schemas
This is a backport of #2504 . The main difference here is that we're
setting the current default of the compatibility-breaking config change
to false. This way users don't break compatibility when upgrading headless
mode across bugfix releases. If a user needs the fix then they can set the
config explicitly in their properties file.
- Unit tests for avro serde
- QTT

Adds a name to map schemas (#2504)

---

ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/main/java/io/confluent/ksql/streams/JoinedFactory.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java
ksql-engine/src/test/resources/query-validation-tests/project-filter.json

This patch changes SqlToJavaVisitor to escape quotes in string literals. This
protects code gen against java code injection attacks. The patch also includes
a query-validation-test that demonstrates how one might inject java code
unit test + qvt

Escape quotes in string literals

---

docs/developer-guide/syntax-reference.rst
docs/installation/cli-config.rst
docs/installation/server-config/config-reference.rst
docs/installation/upgrading.rst
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

Docs update for the default partition and replica count for sink topics in queries.

Added docs for sink topic partitions and replica defaults.

---

ksql-common/src/main/java/io/confluent/ksql/util/timestamp/StringToTimestampParser.java
ksql-common/src/test/java/io/confluent/ksql/util/timestamp/StringTimestampExtractorTest.java
ksql-common/src/test/java/io/confluent/ksql/util/timestamp/StringToTimestampParserTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToTimestampTest.java

See #2499 for full description of the problem - when we use `parseDefaulting`, java's time modules force that ChronoField to be used (it doesn't know how to resolve defaults between `DAY_OF_YEAR` and `DAY_OF_MONTH`).
This PR reverses the approach (see [this stack overflow discussion](https://stackoverflow.com/questions/49812003/java-time-datetimeformatter-parsing-with-flexible-fallback-values)) by first constructing a time unit with defaults and then filing in anything that was parsed from the format instead of trying to "parse best" from an incomplete timestamp string.
Previously was #2520 
- Unit tests

Support more date formats (Fixes #2499)

---

bin/ksql-server-start

The server's log4j properties file is `log4j-rolling.properties`, so that's the file we should check existence for, not `log4j-silent.properties` (which is for datagen).
File is still found correctly.

Minor: fix typo in finding server log4j properties file

---

ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java

There's a call to `KsqlStructuredDataOutputNode.cloneWithDoCreateInto` in `PhysicalPlanBuilder` that looks to serve no purpose. I've looked back at where this flag comes from and everything looks like it should always do the right thing already.  This may be because of some of my earlier refactors.
Hence this PR drops the unnecessary call and removes the method.
Ran the usual tests.

Minor: Drop unnecessary `cloneWithDoCreateInto`

---

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/KsqlTopic.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/StructuredDataSource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlTopicInfo.java

KsqlTopic had a fields called 'topicName` which referred to the name of `KsqlTopic` object and another field, `kafkaTopicName` which refers to the name of the kafka topic associated with this KsqlTopic. `topicName` has cause mistakes and was used instead of kafkaTopicName before. This change clarifies the `topicName` field name indicating that it is not `kafkaTopicName`!

Rename `topicName` to `ksqlTopicName` in KsqlTopic class.

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

Disable WADL since we don't have the jaxb runtime. A good reminder about inheritance
being freaking evil. This is fixed in rest-util's Application, but we override this method.

Disable WADL

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlExecutionContext.java
ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/QueryCapacityUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/QueryCapacityUtilTest.java

In #2502 I introduced `KsqlExecutionContext#getPersistentQueries` API which obviates the need for `numberOfPersistentQueries`.
- Ran existing unit tests

Minor: remove unnecessary numberOfPersistentQueries API

---

checkstyle/suppressions.xml

This allows older branches to pass checkstyle with updated versions. It's not meant to be merged up through subsequent branches, but rather is the temporary way out since multiple refactors were performed in newer branches to clean this up.

Disable NPathComplexity for newer checkstyle compatibility on older branches

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java

Fix for #2586: UDFs not being passed their config.
PR:
- ensures UDFs get passed their configs.
- add `KsqlConfig` tests to cover cloning config with overrides
- add functional test to ensure this works end-to-end.
The issue is that the `cloneWithPropertyOverwrites` uses the `values()` of the original config, not the `originals()`.  While the former passes along _all_ the original configs, whether known or unknown, the latter call filters out any unknown config values, (causing the bug), and also includes any default values, (which aren't necessary).  The UDF config has prefixed freeform names, so would never be included in `values()`.
Looks to be a low risk change.  
I've looked for other uses of `values()` as well.  There are only two. One looks legit, and the other is unused. (I'll …

5.2 fix for UDFs not being passed their config.

---

ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

We occasionally see tests failing due to the Kafka Controller thread losing connection to the broker.  The default timeout on the socket is 30 seconds. The default timeout on tests is 30 seconds.  This PR drops the socket timeout to 20 seconds in order to give tests timeout to detect the dead connection and recover _before_ the test times out.

Decrease Kafka Controller socket timeout in tests.

---

ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/QueryTranslationTest.java
ksql-engine/src/test/java/io/confluent/ksql/SchemaTranslationTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/AvroSchemaInferenceTest.java
ksql-engine/src/test/resources/query-validation-tests/elements.json
ksql-engine/src/test/resources/query-validation-tests/key-field.json
ksql-metastore/src/test/java/io/confluent/ksql/metastore/StructuredDataSourceMatchers.java

Add the changes to QTT and STT and the new keyField tests added in this PR: https://github.com/confluentinc/ksql/pull/2574 to the 5.2 branch.
This will mean we'll get 'expected topology' files for these tests for the 5.2 branch, which will be useful for detecting breaking changes in the structured key work.

5.2 keyfield tests

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

Drop the unused `clone` method from `KsqlConfig`
Usual

Minor: Drop the unused `clone` method from `KsqlConfig`

---

ksql-engine/src/main/java/io/confluent/ksql/function/udaf/sum/DoubleSumKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/sum/IntegerSumKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/sum/LongSumKudaf.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/sum/BaseSumKudafTest.java
ksql-engine/src/test/resources/query-validation-tests/sum.json

Fixes #2490
UDAF `SUM()` currently throws NPE if asked to `undo` a `null` value.   
This PR primarily fixes:
- the NPE in the variants of SUM.
In addition it ensures each impl of `SUM` has:
- The `undo` function is next to the `aggregate` function for each comparison.
- consistent names for the `valueToAdd` in the `aggregate` function and the `valueToUndo` in the `undo` function.
- consistent ordering of parameters being added together in `aggregate` and `undo` functions.
Added unit and JSON test.

Make SUM UDAF handle undos of null values.

---

ksql-engine/src/test/java/io/confluent/ksql/TopologyFileGenerator.java
ksql-engine/src/test/resources/query-validation-tests/README.md

The old QueryTranslationTest variable `CURRENT_TOPOLOGY_VERSION` was removed in https://github.com/confluentinc/ksql/pull/2335 but some docs references to it slipped through the cracks. This PR cleans up those old references.
Targeting `5.2.x` as this is a docs-only change.
None, docs-only.

Minor: clean up references to CURRENT_TOPOLOGY_VERSION

---

docs/installation/server-config/security.rst

The newly-added docs around configuring KSQL for HTTPS mention setting `ssl.client.auth=required` for configuring mutual auth, but [the config is a boolean](https://github.com/confluentinc/rest-utils/blob/fa71eb6dee284530fb9b27b703e16063aa73d9b3/core/src/main/java/io/confluent/rest/RestConfig.java#L411) so it should be `ssl.client.auth=true` instead.
Specifically, setting `ssl.client.auth=required` results in
```
io.confluent.common.config.ConfigException: Invalid value required for configuration ssl.client.auth: Expected value to be either true or false
at io.confluent.common.config.ConfigDef.parseType(ConfigDef.java:286)
at io.confluent.common.config.ConfigDef.parse(ConfigDef.java:249)
at io.confluent.common.config.AbstractConfig.<init>(AbstractConfig.java:78)
at …
```

Minor: fix error in SSL config docs.

---

ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java
ksql-engine/src/test/resources/query-validation-tests/group-by.json
ksql-engine/src/test/resources/query-validation-tests/joins.json

Enhance join and group-by tests to cover the values stored in internal topics.  Thereby hopefully catching any non-backwards compatible changes to the schema/data stored in these intermediate topics.
Note: you may notice that the key within the internal topics in the `join.json` tests are a bit funky. This is because they are the internal `WindowKeySchema` of Kafka Streams.
Note2: This PR requires https://github.com/confluentinc/schema-registry/pull/1068 to be merged before all tests will pass.

Enhance join and group-by tests to cover the values stored in internal topics.

---

ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/FilterNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlBareOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/PlanNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/ProjectNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/QueuedSchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedTable.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/ProjectNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/StructuredDataSourceNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-metastore/src/test/java/io/confluent/ksql/metastore/model/StructuredDataSourceMatchers.java

The `keyField` of the nodes and streams involved in building a query can be null. (Yes, even on tables!).  Switch the implementation to make this explicit, but using `Optional`.
(This is another quick refactor to improve things before we add in Structured Keys)
None functional change,.

Minor: Mark the `keyField` of structured and plan nodes optional.

---

ksql-engine/src/main/java/io/confluent/ksql/function/udaf/BaseNumberKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/DoubleMaxKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/IntegerMaxKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/LongMaxKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/min/DoubleMinKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/min/IntegerMinKudaf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/min/LongMinKudaf.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/max/DoubleMaxKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/max/IntegerMaxKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/max/LongMaxKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/min/DoubleMinKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/min/IntegerMinKudafTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/min/LongMinKudafTest.java
ksql-engine/src/test/resources/query-validation-tests/max-group-by.json
ksql-engine/src/test/resources/query-validation-tests/min-group-by.json

See #2599. This PR fixes behavior around nulls in `MAX` and `MIN` UDAFs. It also slightly cleans it up by having a base class for all of them.
- Unit Testing
- QTT

Return null for max/min if all inputs are null (Fixes #2599)

---

docs/installation/server-config/security.rst

With the introduction of the record processing log topic, the docs around required Kafka ACLs need to be updated. Otherwise, KSQL fails to start with the following error when ACLs are enabled:
```
[2019-03-25 18:03:11,579] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:53)
io.confluent.ksql.exception.KafkaResponseGetFailedException: Failed to guarantee existence of topic default_ksql_processing_log
at io.confluent.ksql.services.KafkaTopicClientImpl.createTopic(KafkaTopicClientImpl.java:100)
at io.confluent.ksql.services.KafkaTopicClient.createTopic(KafkaTopicClient.java:53)
at io.confluent.ksql.rest.util.ProcessingLogServerUtils.maybeCreateProcessingLogTopic(ProcessingLogServerUtils.java:81)
at io.confluent.ksql.rest.server.KsqlRestApplication.buildApplication(Ksq …
```

Minor: Update required ACLs to account for record processing log topic

---

docs/installation/server-config/security.rst

The docs for configuring basic HTTP auth for KSQL recommend specifying the JAAS file location as a parameter in the server config, but this doesn't work since [we exclude configs prefixed with `java.`](https://github.com/confluentinc/ksql/blob/5.1.x/ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/ServerOptions.java#L39) when loading server configs. This PR updates the docs to recommend passing the JAAS file location as a JVM parameter instead, which does work.
I've targeted `5.1.x` as the docs for configuring basic auth were only introduced in 5.1 (i.e., they're not present on `5.0.x`), but I'm unfamiliar with how our `-post` branches work. Perhaps this correction should target one of the 5.1 `-post` branches instead? cc @JimGalasyn 
Docs-only change. Manually tested both the …

Minor: Correct docs for configuring basic HTTP auth

---

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-engine/src/main/java/io/confluent/ksql/util/GenericRowValueTypeEnforcer.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/PrimitiveType.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/EntityUtil.java

This refactor is needed to avoid disabling check-style CyclomaticComplexity rules in a future patch for decimal types (#842).
It only moves methods that have several if/case conditions into static variables that map those if/case conditions into a result.
No new tests are necessary. Current unit tests verify these changes.

Refactor code to void check-style CyclomaticComplexity rules

---

docs/developer-guide/syntax-reference.rst
ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/properties/LocalPropertyValidator.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/PropertyValidator.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/RequestValidator.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/client/properties/LocalPropertiesTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/client/properties/LocalPropertyValidatorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KsqlRequestTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/PropertyValidatorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/RequestValidatorTest.java

This patch changes the behavior for SET/UNSET command so only the properties in a predefined whitelist can be configured using these commands and the command would fail user tries to config any other property.
Currently user can run these command with many properties that should not be configurable by users. For instance, user should not be able to issue the following command:
```
ksql> set 'ksql.service.id` = 'foo';
```
Currently we have only 4 configurable session properties, but we can add more in this PR if reviewers have convincing suggestion! :) 
So as of now the properties that user can set/unset from client are the following:
- ksql.sink.window.change.log.additional.retention
- ksql.streams.commit.interval.ms
- auto.offset.reset  
- group.id  
Any other property that is used in …

Whiteliste configs for set/unset commands.

---

ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/Versions.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WebSocketSubscriber.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WebSocketSubscriberTest.java
ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

Improve the Rest API test to include:
- Kafka ACLs
- Print topic
- Actually streaming back results of websocket requests.
To do this I had to extend some test classes to better support secure cluster and ACLs.
Also exposed more error information when things fail.
This was done as part of investigating a user's issue where they were seeing a 'not authorised to use group' error message when doing a PRINT topic where the Kafka cluster is secured by ACLs. The tests added look to prove there is no requirement for ACLs on consumer groups for the PRINT command.  Likely, the user is running into a known issue with older versions of Kafka. (See https://issues.apache.org/jira/browse/KAFKA-6774).
Usual

Improve the Rest API test

---

docs/developer-guide/udf.rst
ksql-common/src/main/java/io/confluent/ksql/function/KsqlFunction.java
ksql-common/src/main/java/io/confluent/ksql/function/UdfFactory.java
ksql-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/function/UdfFactoryTest.java
ksql-common/src/test/java/io/confluent/ksql/function/UdfIndexTest.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfCompiler.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfTemplate.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/PluggableUdf.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfCompilerTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfTemplateTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/TestUdf.java
ksql-engine/src/test/java/io/confluent/ksql/security/ExtensionSecurityManagerTest.java

As part of #2503, this add supports for defining UDFs with variable arguments. To accomplish this there were three main changes:
* Ability for `UdfFactory` to resolve conflicts between vararg and non-vararg functions. This is done in a new class called `UdfIndex` (Implementation is described inline)
* Our coercion mechanism in `UdfTemplate` needs to be able to coerce arrays
* `SchemaUtil` needs to support parameterized array types
* (See below) Move built-in UDFs that use varargs (e.g. `Concat`) to the new UDF style
* Update DescribeFunction to show information on whether or not a function is varargs
- Unit tests
- Moving `ConcatKudf` to new annotation based Udfs and adding QTT tests to cover (since lots of test files will be affected, I will commit this in a follow-up PR)

Add support for varargs in UDFs (Fixes #1509)

---

ksql-engine/src/test/resources/expected_topology/5_3_0_pre/joins_-_stream_stream_inner_join_all_fields
ksql-engine/src/test/resources/query-validation-tests/joins.json

New test to cover hole in current testing - test for join with `SELECT *` i.e. pulling in all fields from both sides of the join.

Minor: Add test covering a join that selects all fields from both sides of join

---

design-proposals/README.md
design-proposals/klip-1-improve-udf-interfaces.md

View the rendered version here: https://github.com/agavra/ksql/blob/udf_klip/design-proposals/klip-1-improve-udf-interfaces.md

KLIP-1: Improve UDF Interfaces

---

ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/Retry.java
ksql-engine/src/test/java/io/confluent/ksql/integration/StreamsSelectAndProjectIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java

see #2620  - I removed the `RetryTest` because this version of Ksql did not import mockito and other things required to run it. I don't want to spend too much time doing random backports and this is a test-only change.

(Backport to 4.1.x) add auto-retry to ZK failures

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java
ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriteForStruct.java
ksql-parser/src/main/java/io/confluent/ksql/util/DataSourceExtractor.java
ksql-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java

Quick PR to tidy up `DataSourceExtractor` as I'm working in the area.
- Removed Unused fields and methods from `DataSourceExtractor`.
- Removed unused use of `DataSourceExtractor` from `StatementRewritterForStruct`
- Moved instantiation into the only place its used: `AstBuilder`. Thereby removing the possibility the builder is passed an inappropriate extractor.
- Refactored `AstBuilder` to using internal visitor, rather than expose it as part of its API.
- Refactored common code into `ParserUtil`.
Reviewers notes:
- Review `DataSourceExtractor` first.
- Then `DefaultKsqlParser` to see how `DataSourceExtractor` was created.
- Then `AstBuilder` to how it now is used.  Note: the Github diff is whack. Very little code has changed, its just been indented, as its now within an inner class. …

Minor: Tidy up of `DataSourceExtractor`

---

docs/developer-guide/udf.rst
ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-common/src/main/java/io/confluent/ksql/function/KsqlFunction.java
ksql-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/Elt.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/Field.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/string/EltTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/string/FieldTest.java
ksql-engine/src/test/resources/query-validation-tests/elt-field.json
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/ArgumentInfo.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeFunctionExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/FunctionInfoTest.java

Proof of concept for variadic functions. This PR introduces the following changes:
* Introduce `ELT`, which is based on specification in SQL (see [mysql#elt](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_elt))
* Introduce `FIELD`, which is based on specification in SQL (see [mysql#field](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_field))
* Introduce variadic syntax to `DESCRIBE FUNCTION`, which will append `[]` to any such argument (in line with other SQL systems).
* Replace references of "vararg" with "variadic" to stay inline with other SQL systems
- New Unit tests
- QTT tests
- Ran it using new/old servers and new/old CLIs
```
ksql> DESCRIBE FUNCTION ELT;
Name        : ELT
Overview    : ELT() returns the Nth element of the list of …
```

Introduce ELT/FIELD methods using VARIADIC and update DESCRIBE FUNCTION

---

ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java
ksql-examples/src/test/java/io/confluent/ksql/datagen/DataGenTest.java

Ensure command line schema registry URL is passed.
This is a regression caused by https://github.com/confluentinc/ksql/pull/2584

KSQL-2422: Ensure command line schema registry URL is passed

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/topic/DefaultTopicInjector.java
ksql-engine/src/main/java/io/confluent/ksql/topic/TopicProperties.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/FakeKafkaTopicClient.java
ksql-engine/src/test/java/io/confluent/ksql/topic/DefaultTopicInjectorTest.java
ksql-parser/src/main/java/io/confluent/ksql/util/WithClauseUtil.java
ksql-parser/src/test/java/io/confluent/ksql/util/WithClauseUtilTest.java

This PR refines KSQL's topic management story by moving topic creation outside of the physical plan construction. Topics are now _expected_ to already exist with the correct configuration at the time of physical plan construction. The physical plan won't fail if the topic does not exist, but the query will. This is equivalent to deleting a topic while a query is running.
* Any running queries will not be affected since the topic for them has already been created
* Any new queries will have the topic created for them before enqueuing the topic.
* Recovery will fail to issue a query if the topic that query outputs to was deleted. I think this is OK without introducing a config flag because it's likely an unintended consequence, and the metastore will still be properly working. NOTE that …

Create topics before executing commands

---

ksql-benchmark/pom.xml
pom.xml

There's no reason to ever install or deploy the ksql-benchmark module, so this PR disables those maven goals for the module accordingly.
Manually verified that the benchmarks jar is no longer installed.

Minor: do not install/deploy benchmark module

---

ksql-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedServiceContext.java
ksql-engine/src/main/java/io/confluent/ksql/util/Sandbox.java
ksql-engine/src/main/java/io/confluent/ksql/util/SandboxUtil.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/RequestValidator.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/RequestValidatorTest.java

Adds an annotation `@Sandbox` which will allow us to check to make sure that we are getting Sandbox clients at certain call sites - specifically the validation work on the rest server.
This addresses @rodesai's comment on #2634.
- Unit testing

add @Sandbox annotation to ensure that some calls are sandboxed

---

ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java

Add some simple newlines to make the usage output for the datagen cli
more readable. The new output looks like this:
```usage: DataGen 
[help]
[bootstrap-server=<kafka bootstrap server(s)> (defaults to localhost:9092)]
[quickstart=<quickstart preset> (case-insensitive; one of 'orders', 'users', or 'pageviews')] 
schema=<avro schema file> 
[schemaRegistryUrl=<url for Confluent Schema Registry> (defaults to http://localhost:8081)]
format=<message format> (case-insensitive; one of 'avro', 'json', or 'delimited')
topic=<kafka topic name>  
key=<name of key column> 
[iterations=<number of rows> (defaults to 1,000,000)] 
[maxInterval=<Max time in ms between rows> (defaults to 500)] 
[propertiesFile=<file specifying Kafka client properties>
```
_Describe the testing strategy. Unit and …

Make the output of usage of datagen prettier

---

docs/developer-guide/processing-log.rst
ksql-common/src/main/java/io/confluent/ksql/logging/processing/ProcessingLogMessageSchema.java
ksql-common/src/main/java/io/confluent/ksql/util/ErrorMessageUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/ErrorMessageUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SelectValueMapper.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SqlPredicate.java
ksql-engine/src/main/java/io/confluent/ksql/util/EngineProcessingLogMessageFactory.java
ksql-engine/src/test/java/io/confluent/ksql/util/EngineProcessingLogMessageFactoryTest.java
ksql-serde/src/main/java/io/confluent/ksql/serde/util/SerdeProcessingLogMessageFactory.java
ksql-serde/src/test/java/io/confluent/ksql/serde/util/SerdeProcessingLogMessageFactoryTest.java

Java exceptions can have a chain of causing exceptions that contain valuable
context about why an exception was thrown. KSQL has an ErrorUtils utility
class for building error messages from the cause chain. In this patch, we
add a utility function to that class which returns the cause error msg chain
as a list, and include this list in the record processing log as a new field
for deserialization and processing errors.
Fixes #2567 
Unit tests
Manual tests

Add cause for errors logged to processing log

---

config/ksql-server.properties
docs/developer-guide/api.rst
docs/installation/installing.rst
docs/installation/server-config/config-reference.rst
docs/operations.rst
docs/troubleshoot-ksql.rst
ksql-examples/src/main/resources/ksql-server.properties

This PR updates the the default KSQL server config listener from localhost to 0.0.0.0, in order to prevent users from being tripped up when connecting KSQL and Confluent Control Center, even with the documentation [here](https://docs.confluent.io/current/ksql/docs/installation/server-config/integrate-ksql-with-confluent-control-center.html#when-ksql-and-c3-run-on-different-hosts). The drawback is that 0.0.0.0 is less secure than localhost, but there is precedent for defaulting to 0.0.0.0 in other components (e.g., in [Schema Registry](https://github.com/confluentinc/schema-registry/blob/87d505d7c7985da64feddadc20dcaf6b703ff503/config/schema-registry.properties#L22)) and users will need to switch away from either when working in a secure production environment anyway.
Configs/docs-only …

Minor: update default listener from localhost to 0.0.0.0

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStream.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamTest.java

Fixes #2639
This fixes the issue when a topic has one single value with one column.
```
ksql> print 't1' from BEGINNING;
com.fasterxml.jackson.databind.node.IntNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode
```
The issue is that `PRINT` was selecting a JSON format to display the above value (which is a valid JSON value), however, the `PRINT` format was expecting to use an `ObjectNode` which expects a `key:value` format.
The fix is easy. Just to prevent using JSON if the value is not an `ObjectNode`. It will fall back to the STRING format instead.
Add a test to `TopicStreamTest`
Manually verified in KSQL CLI
```
ksql> print 't1' from BEGINNING;
Format:STRING
4/12/19 9:55:55 AM CDT , NULL , 1000
```

PRINT does not deserialize a DELIMITED topic with one integer column

---

docs/tutorials/docker-compose.yml

Image versions in the KSQL docker quickstart haven't been bumped since 5.0.0. As identified in https://github.com/confluentinc/ksql/issues/2685, this is breaking the docker quickstart since 5.2 due to an incompatibility between the 5.2 CLI and the 5.0 server (root cause investigation still underway). In the meantime, this PR fixes the quickstart by bumping the server version, and also bumps dependency versions too.
This PR is targeted at 5.1.0-post. I will update the versions for each branch as the PR is merged forward.
Fixes https://github.com/confluentinc/ksql/issues/2685
Manual verification that the quickstart still works with 5.1.0 and 5.2.1.

Minor: bump docker quickstart image versions

---

docs/concepts/ksql-architecture.rst

The current table of supported KSQL operations in our docs says "CREATE and DROP a stream or table" and "Start and stop a query" are both supported in headless mode, but this is misleading since headless mode doesn't support `TERMINATE` or `DROP` statements. This PR updates the table to clarify this.

Minor: clarify operations supported in headless mode

---

ksql-engine/src/test/java/io/confluent/ksql/TopologyFileGenerator.java

#2642 caused `TopologyFileGenerator` to fail because it is not run in the same directory that can access `udf-example.jar`. This change does two things:
- changes it from a `main` method that executes using `user.dir=../target/..` to a JUnit test, which will execute in the proper test directory
- adds a test that will be run every time to make sure that future changes will not cause the generator to fail
- ran the generator

Fix broken topology generator and add test

---

ksql-engine/src/test/resources/query-validation-tests/joins.json

Added some tests to document existing handling of key fields in joins.  There are a couple of issues there.  The tests include some 'legacy downstream query' tests which will be used to prove any fixes / changes don't change the topologies of pre-existing persistent queries or the data in the metastore in non-backwards compatible ways.

Minor: Add key field checks to the join json tests.

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-common/src/test/java/io/confluent/ksql/json/JsonMapperTest.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/json/JsonExtractStringKudf.java
ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/CommandStatusEntityTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/FunctionInfoTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KsqlRequestTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/SchemaDescriptionFormatTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java

This PR:
- updates JsonMapper to ignore unknown fields, so that even if the `@JsonIgnoreProperties(ignoreUnknown = true)` is forgotten/missed on certain types, we still have forward compatibility when new fields are introduced. This change is motivated by https://github.com/confluentinc/ksql/issues/2685.
- cleans up references to JsonMapper: non-test code should use JsonMapper rather than creating new ObjectMappers, and should not reconfigure the JsonMapper.
I've chosen not to remove existing `@JsonIgnoreProperties(ignoreUnknown = true)` annotations from types despite these annotations no longer being needed with this change, for the sake of being explicit. If folks prefer they be removed I'm happy to do so.
Added small unit test for JsonMapper. Existing tests continue to pass.

Minor: update JsonMapper to ignore unknown fields

---

docs/developer-guide/processing-log.rst
ksql-common/src/main/java/io/confluent/ksql/logging/processing/ProcessingLogMessageSchema.java
ksql-common/src/main/java/io/confluent/ksql/util/ErrorMessageUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/ErrorMessageUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SelectValueMapper.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SqlPredicate.java
ksql-engine/src/main/java/io/confluent/ksql/util/EngineProcessingLogMessageFactory.java
ksql-engine/src/test/java/io/confluent/ksql/util/EngineProcessingLogMessageFactoryTest.java
ksql-serde/src/main/java/io/confluent/ksql/serde/util/SerdeProcessingLogMessageFactory.java
ksql-serde/src/test/java/io/confluent/ksql/serde/util/SerdeProcessingLogMessageFactoryTest.java

* Add cause for errors logged to processing log
Java exceptions can have a chain of causing exceptions that contain valuable
context about why an exception was thrown. KSQL has an ErrorUtils utility
class for building error messages from the cause chain. In this patch, we
add a utility function to that class which returns the cause error msg chain
as a list, and include this list in the record processing log as a new field
for deserialization and processing errors.
* Docs

Add cause for errors logged to processing log (#2662)

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/resources/query-validation-tests/insert-into.json

For some reason KsqlStructuredDataOutputNode is rebuilding the sink topic serde
for queries that write avro. There is no reason to do this, and in the case of
INSERT INTO from a json source actuall results in an NPE, because the schema name
isn't set in the properties. Instead of doing this rebuild, we should just use
the serde the analyzer computed for us.
Unit test and QVT

Don't do unnecessary rebuild of sink topic serde for avro

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/util/CliUtils.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/JsonMapper.java

This is a backport of https://github.com/confluentinc/ksql/pull/2704 to 5.0.x, which is needed in order for 5.0 servers to be compatible with 5.2+ CLI versions. (See https://github.com/confluentinc/ksql/issues/2685 as example motivation.)
Manual verification that the 5.0 server with this change is now compatible with the 5.2 CLI. Existing tests continue to pass. I chose not to backport unit tests from https://github.com/confluentinc/ksql/pull/2704 since active development no longer happens on 5.0.x, but am happy to do so if others think this is desirable.

Minor: update JsonMapper to ignore unknown fields (5.0.x)

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

1. `KsqlRestApplication` is a Jetty `Server`. As part of its `stop` functionality, it waits for any opened network connections to wrap up (default wait time is one second). 
2. In `QueryStreamWriter`, we use the admin client to cleanup internal topics.
3. In `KsqlRestApplication`, we close the engine, which in turn closes the KafkaTopicClient, which in turn closes the admin client.
3 and 2 are racey. If we close the KsqlEngine before the `QueryStreamWrtier` is done whatever it is doing, it will fail with `org.apache.kafka.common.errors.TimeoutException: The AdminClient thread is not accepting new calls.`
Since we wrap that call with a retry, it will retry forever: 
```java
executeWithRetries(() -> adminClient.listTopics().names());
```
That is, until `super.stop()` is called, which will …

fix race condition in RestApiTest shutdown: fixes flaky test in 5.0.x

---

ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/model/KeyField.java
ksql-metastore/src/test/java/io/confluent/ksql/metastore/model/KeyFieldTest.java

In the current code the `LogicalPlanner` creates an immutable `KsqlStructuredDataOutputNode` when building persistent queries. When the `PhysicalPlanBuilder` calls `buildStream` on the node it uses a builder to create another copy of itself and tweak its parameters, creating a slightly different `KsqlStructuredDataOutputNode` to associate with the return value.
No other node follows this pattern. This complicates both `KsqlStructuredDataOutputNode` and other parts of the code. So... this PR does away with the builder from `KsqlStructuredDataOutputNode`.
Added unit tests to ensure the schema doesn't change in the resulting `QueryMetadata`.

Remove the need for a builder in `KsqlStructuredDataOutputNode`

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/StructuredDataSourceNodeTest.java

In the current code base the schema passed to `StructuredDataSourceNode` has fully qualified field names, i.e. the field names are prefixed with the source name, if the query is not a join, but has unqualified field names if the query is a join.
This PR looks to standardize on always using fully qualified field names for the schema in `StructuredDataSourceNode`. Consistency here makes reasoning about the code easier and will help fixing bugs such as https://github.com/confluentinc/ksql/issues/2525.
QTT and added suitable unit tests.

StructuredDataSourceNode to always use fully qualified schema

---

docs/developer-guide/syntax-reference.rst

This is a fix for @rmoff's ticket, DOCS-700, to clarify TIMESTAMP_FORMAT. I copied and updated the description out of the four CREATE sections into a new section near the top of the page.

DOCS-700: Add section on timestamp formats to KSQL syntax reference

---

ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedAdminClient.java
ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java

Partially revert changes to switch KSQL over to use new `incrementalAlterConfigs` admin client functionality (#2737).
This new functionality is only available on new Kafka Brokers and so would unnecessarily restrict compatible KSQL - Kafka versions.
Instead, we use the new API and if its not available we fallback to the older API.
The older API has issues with race conditions and overwriting secret properties. 

Revert change to switch KSQL over to use new `incrementalAlterConfigs` admin client functionality.

---

ksql-engine/src/test/resources/query-validation-tests/join-with-custom-timestamp.json
ksql-engine/src/test/resources/query-validation-tests/joins.json

The recent change in kstream uses the greater timestamp of the join records from left and right in the result message. This PR updates our join tests to expect the correct timestamp.
Note that this patch is only for join tests. There will be separate PRs for other test failures namely changes in the generated streams topology.

Updated the join tests to expect the greater timestamp for the result.

---

ksql-engine/src/test/java/io/confluent/ksql/EndToEndEngineTestUtil.java

This PR is a temp work around to allow a green build without the need to revert anything or disable any tests.
What it attempts to do is standardize the topology graphs, removing any changes brought about by the recent Kafka version update.
It looks to address two issues.  See below.
**NOTE**: this is just a short term fix to get the build green.  We should investigate more and if there are _compatible_ changes in the topologies, we should change the expected topologies files - this is a safer long term fix than on-the-fly manipulation of the topologies.
Most nodes in the topology have a number tagged on the end of them, e.g. `KSTREAM-MAPVALUES-0000000001`.  The node numbers is used to make each step unique. The actual number isn't important and sometimes changes between KStream version …

Fix build: Add code to QTT to massage the topologies to remove descrepances

---

ksql-engine/src/main/java/io/confluent/ksql/function/UdfCompiler.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfTemplate.java
ksql-engine/src/test/java/TestUdfWithNoPackage.java

There's an issue with javapoet when it tries to resolve type names for classes in the default package (see #2721). This circumvents it by just using the canonical name directly.
NOTE: The root cause will be fixed in a future version of javapoet: https://github.com/square/javapoet/pull/723
- unit testing
- ran it with a custom udf package

support udf imports with no package (fixes #2721 targets 5.2.x)

---

docs/installation/server-config/config-reference.rst
docs/installation/server-config/index.rst

This PR adds environment variables for the KSQL Server image that correspond with settings in [KSQL Configuration Parameter Reference](https://docs.confluent.io/current/ksql/docs/installation/server-config/config-reference.html). For internal ticket KSQL-2539.

KSQL-2539: Add Docker env variables to KSQL config settings topic

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
pom.xml

Fixes #2640 CTRL+C sometimes throws a JsonEOFException from the CLI
Refer to : https://github.com/confluentinc/ksql/pull/2717
I add some exception.printStackTrace()
https://github.com/confluentinc/ksql/blob/589a0817b99cabaf1af79ac64c93f98332ea0786/ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java#L379

fixes #2640 CTRL+C sometimes throws a JsonEOFException from the CLI

---

ksql-common/src/main/java/io/confluent/ksql/logging/processing/NoopProcessingLogContext.java
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedProducer.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/services/SandboxedProducerTest.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/model/KsqlStream.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/model/KsqlTable.java
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/InsertValues.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/InsertValuesTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java

This is the first of a few PRs that implement #2693 (Insert Values), which is split across the following 4 PRs:
1. **Introduce syntax and basic functionality for insert values**
2. Introduce new semantics for `CREATE STREAM`/`CREATE TABLE`
3. Documentation PR (leaving for the end so that nobody uses it until it is more complete)
If those 3 PRs are done before 5.3, we can add more functionality (like non-literal support for `INSERT VALUES`)
This PR contains the following changes:
- `INSERT INTO ... VALUES` syntax in `SqlBase.g4` and corresponding parsing/formatting code
- `InsertValuesExecutor` to produce data into the underlying topics
- Some helpful methods in `SchemaUtil`
- Unit testing
Local Testing:
```sql
ksql> SELECT * FROM PAGEVIEWS;
1556037848196 | 1 | Page_23 | 1556037847931 | …
```

Introduce Syntax & Executor for InsertValues

---

ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksql-engine/src/main/java/io/confluent/ksql/topic/TopicProperties.java
ksql-engine/src/test/java/io/confluent/ksql/services/FakeKafkaTopicClient.java
ksql-engine/src/test/java/io/confluent/ksql/topic/TopicPropertiesTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/KafkaTopicClientImplIntegrationTest.java

As part of the work to support INSERT VALUES (#2693) we need to be able to create topics without supplying the replication factor for CT/CS statements. This is part one of that change, the actual creating of the topics will happen in a follow-up PR to keep things simple.
__NOTES:__ 
1. This PR allow does not change any existing behavior with regards to CTAS/CSAS because a replication factor is always supplied. 
2. I am going to follow-up with submitting a KIP to AK that will change admin client API to accept no replication factor. (https://cwiki.apache.org/confluence/display/KAFKA/KIP-464%3A+Defaults+for+AdminClient%23createTopic)
- The usual works + new integration test

Create topics with default replication factor if no replicas are specified

---

ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java

Don't go through KafkaConfig constants... it appears to break deploying KSQL:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.kafka.common.config.ConfigDef.defineInternal(Ljava/lang/String;Lorg/apache/kafka/common/config/ConfigDef$Type;Ljava/lang/Object;Lorg/apache/kafka/common/config/ConfigDef$Importance;Ljava/lang/String;)Lorg/apache/kafka/common/config/ConfigDef;
at kafka.server.KafkaConfig$.<init>(KafkaConfig.scala:1104)
at kafka.server.KafkaConfig$.<clinit>(KafkaConfig.scala)
at kafka.server.KafkaConfig.DeleteTopicEnableProp(KafkaConfig.scala)
at io.confluent.ksql.services.KafkaTopicClientImpl.isTopicDeleteEnabled(KafkaTopicClientImpl.java:286)
at io.confluent.ksql.services.KafkaTopicClientImpl.<init>(KafkaTopicClientImpl.java:75)
at …
```

Don't use Scala file KafkaConfig for constants

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/statement/Injectors.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTestUtil.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutorFactory.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

Porting the Injectors enum change from #2712 to its own PR so that I can expedite it and focus on just the Set/Unset reactor in the other PR.
- The usual, no functional changes here

Introduce Injectors enum to group together common Injector chains

---

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksql-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java

1. Fix issue with AVRO during validation where the sandbox client was failing to register
2. Bring back upcasting because otherwise we can't type Long literals (timestamp will parse to int). These follow implicit conversion rules in SQL SERVER: https://docs.microsoft.com/en-us/sql/t-sql/data-types/media/lrdatahd.png?view=sql-server-2017 
3. Inject a Binder into the TestKsqlResource so that we can make sure we use the correct ServiceContext for each request
- New integration tests, unit tests
- Manual testing
```
ksql> create stream p4 (author varchar, title varchar) with (kafka_topic='publications', key='author', value_format='avro', partitions=2);
Message
Stream created
ksql> insert into p4 (author, title) values ('C.S. Lewis', 'The Silver Chair');
ksql> SELECT * FROM …
```

fix some issues with INSERT INTO

---

pom.xml

Fixes #2350 -> upgrade the jLine version
Manual testing

Upgrade JLine version to 3.11.0

---

docs/changelog.rst
docs/developer-guide/index.rst
docs/developer-guide/serialization.rst
docs/developer-guide/syntax-reference.rst
docs/faq.rst
ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/json/ValueSpecJsonSerdeSupplier.java
ksql-functional-tests/src/test/resources/query-validation-tests/schemas.json
ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java
ksql-serde/src/main/java/io/confluent/ksql/serde/util/SerdeUtils.java
ksql-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonDeserializerTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/util/SerdeUtilsTest.java

Following on from #2793, I've added tests to cover how KSQL handles schemas with only a single MAP field in them with the JSON format.
#2793 say KSQL able to deserialize JSON and AVRO messages where the value was not a JSON Object or Avro Record, but a top-level primitive or array, or in the case of Avro, map.
As JSON does not support a map type directly there handling is more tricky and has some ambiguity.  KSQL already serializes `MAP` columns as JSON objects, and hence can deserialize a JSON object into a `MAP` column.
If the schema of a stream or table only contains a single `MAP` column, e.g.
```sql
CREATE TABLE FOO (BAR MAP<STRING, INT>) WITH (FORMAT='JSON', ...);
```
Then there is potential for KSQL to deserialize a JSON object directly into the map field `BAR`, e.g. if it …

Test JSON top-level maps and add documentation about serialization formats

---

ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTestUtil.java

The `QueryTranslationTest` and many others make use of `KsqlEngineTestUtil` to run queries and execute statements.  This test class currently follows the pattern used by the rest-api of building a sandbox, executing statements and, if they pass that, executing them on the engine for real.
This is test code, there is no real benefit from first validating the statements in a sandbox. It's just eating up time in our tests.  22% of time when running the QTT is taken up by executing in the sandbox!
This PR drops the validation step from `KsqlEngineTestUtil`, speeding up QTT and other tests.

Minor: Speed up tests by _not_ executing queries twice.

---

docs/developer-guide/syntax-reference.rst
ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/properties/LocalPropertyValidator.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/PropertyValidator.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/RequestValidator.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/client/properties/LocalPropertyValidatorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/RequestValidatorTest.java

This PR removes the changes made in #2618 since we decided to hold this feature back for the time being. Some of the changes including change of some of the properties in the tests remains since we still don't want to configure any property from the CLI.

Removed the whitelist check.

---

CONTRIBUTING.md

When reading `CONTRIBUTING.md` file, there are some typo and incorrect links with markdown.
This PR is for fixing them.
No tests, as it's the `CONTRIBUTING.md` file

Typo and fix links in CONTRIBUTING file

---

ksql-functional-tests/src/test/resources/query-validation-tests/session-windows.json
ksql-functional-tests/src/test/resources/query-validation-tests/window-bounds.json

Change window timestamps on tombstones to be the timestamp of the last source record to update the row. This is inline with an upstream change in KStreams.
However, I'm looking for confirmation from the streams team that this is intentional. It doesn't seem correct to me...

Fix the build: KStreams has changed the timestamp on tombstones

---

ksql-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java
ksql-engine/src/main/java/io/confluent/ksql/services/DefaultServiceContext.java
ksql-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/context/KsqlRestContext.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/context/KsqlRestServiceContextFactory.java

As part of the work that injects a user context credentials into KSQL for impersonation, this PR injects the context to create an impersonated `SchemaRegistryClient`. This is done by passing the HTTP headers to the `SchemaRegistryClientFactory` from the `KsqlRestServiceContextFactory` class.
An impersonated `SchemaRegistryClient` will access the AVRO schema with the current REST user credentials. If denied, then KSQL throws the error coming from the SR client.
A follow-up PR will be next that provides better error messages and pass the impersonated SR client to the right code places.
Regression testing by running current tests.
Local functional tests that infer a stream schema with authorized and unauthorized users.

Create a SchemaRegistryClient using the injected REST context properties

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/security/KsqlDefaultSecurityExtension.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/security/KsqlSecurityExtension.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java

This PR adds a `KsqlSecurityExtension` interface and a configuration that can be used to provide a security context to the `KsqlRestApplication`.
The configuration name is `ksql.security.extension.class` and accepts an implementation of `KsqlSecurityExtension`. This extension is initialized and REST endpoints registered when the `KsqlRestApplication.configureBaseApplication()` method is called when the server is started.
There is no default security for KSQL. Only a dummy implementation that is used internally to provide basic functionality to the `KsqlRestApplication`.
Unit tests that verify `KsqlRestApplication` is initializing, registering, and closing the security extension.
I have my implementation that was called during my local functional tests.

Use a KsqlSecurityExtension to register REST endpoints authorization

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/DataSourceNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/FilterNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlBareOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/OutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/PlanNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/PlanNodeId.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/ProjectNode.java

The nodes of the logical query model are annotated with Jackson `@JsonProperty` and other such annotations.  These, as far as I can tell, are not used anywhere by the code.  There are also no tests to test things (de)serialize to/from JSON, and PRs regularly change constructor parameters, etc.
The annotations are just noise and cause confusion, e.g. people worried about changing constructor args for fear of breaking JSON compatibility.
Hence, this PR removes them.
All tests pass.

Minor: Remove unused Jackson annotations from query logical model

---

ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksql-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java

The previous names produced a statically named beans, and embedded the
service ID in the bean attribute. With this patch, we embed the service
id in the bean name, and use statically named attributes.
In this patch, we publish under both the new scheme and the old scheme.
The old scheme will be removed in a later ksql version.
- Unit testing
- Manually verified

Switch metric names to a format that can be consumed by datadog

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java

Current INSERT INTO values includes the ROWTIME and ROWKET in the message value. This PR removes these columns from the value side.
Tests were updated accordingly.
This fixes #2857

Updated the InsertValuesExecutor along with the tests.

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlExecutionContext.java
ksql-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksql-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ExplainExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/RequestValidator.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/ClusterTerminationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/RequestValidatorTest.java

After 6ac8c48766ce98c49624e6f619ed64a3268f9639 the service context that is passed to the engine context does not match that which was passed to `RequestValidator`. This fixes this to make sure that it uses the right service context.
- `KsqlResourceFuncitonalTest` is updated to include an end-to-end topic creation

Pipe serviceContext down to EngineContext (Fixes #2853)

---

ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java

When using the DataGen tool if there is an exception beyond an `ArgumentParseException`,  the `DataGen#main` method prints only the exception message.  It would be more helpful in solving the issue to print the stacktrace to the console.
Reproduced an error and observed stacktrace on console

MINOR: When an error other than a parse exception print the stacktrace

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java

This PR fixes an issue with the `ServiceContext` not closed on WebSocket sessions.
When a new WS session is opened, the `onOpen` call creates a new `ServiceContext` that might contain the Session user credentials to access Kafka resources. Once the WS session is closed, this `ServiceContext` must be closed in the `onClose` method.
I learned that the whole `WSQueryEndpoint` configured in the `KsqlRestApplication#registerWebSocketEndpoints` is created every time a new Session is opened. So, it was enough to store the `ServiceContext` as a Class member scope so it can be accessed from the `onClose` method. This is similar to the `subscriber` class member variable.
Update the `WSQueryEndpoint` test case.

Close ServiceContext when Session is closed

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java

Seems that PR #2858 did not make it to 5.3.x branch and the branch was cut before the PR was merged. This PR back ports the changes from that PR into 5.3.x so we will have it in the next release.

Backport insert into values bug fix

---

ksql-cli/src/test/java/io/confluent/ksql/CliTest.java

This test was improved in later versions to be made more stable. Backporting has low ROI, so disabling the test.
ran unit tests to ensure it is excluded

disable CliTest in 4.1.x

---

ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedAdminClient.java
ksql-test-util/src/main/java/io/confluent/ksql/test/util/TestMethods.java

Back out changes made in #2896 as upstream changes made [for KIP-460](https://github.com/apache/kafka/pull/6686) are not in the Confluent Kafka snapshot.
This will need putting back in once they are.
`mvn clean install -U`

Fixing the build. (Backing out KIP-460 changes until they come through)

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java

NOTE: https://github.com/confluentinc/ksql/pull/2896 is included in this PR, but that will be merged soon, look only at the last commit (bc545ec)
See #2895 - this will make it easier to terminate queries without following up with a SHOW QUERIES. 
`mvn clean install` and local testing:
```
ksql> create stream s1 (author varchar, title varchar) with (kafka_topic='publications', key='author', value_format='json', partitions=1);
Message
Stream created
ksql> create stream s2 as select * from s1;
Message
-----------------------------------------------
Stream created and running with id: CSAS_S2_0
-----------------------------------------------
```
Note that there are still more improvements to be done that are out of scope for this PR:
- it is possible that the …

Expose QueryID in CSAS/CTAS/INSERT response (Fixes #2895)

---

ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/command/TestOptionsParserTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/elements.json
ksql-functional-tests/src/test/resources/query-validation-tests/sink-partitions-replicas.json

There's a bit of code the the functional tests module that takes the JSON input records in the QTT tests and, if the input value is a `Map`, converts the map keys to upper-case.
It should not be doing this - input data should be left as is.  KSQL will upper-case the field names when deserializing. But the source data in our tests should support being any case. By upper-casing the source data being published to Kafka we could hiding issues with case-sensitivity in our code.  To put this another way - the source data our users will be passing to KSQL will include lower/mixed cased field names, so our test cases should cover the same!
This will become even more important when we support unwrapped map values. (Hence the PR).  With unwrapped map values the keys are NOT fields. With the current …

Minor: QTT should not upper case map keys

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java

One of our soak clusters recently encountered a series of websocket errors such as:
```
2019-05-24 21:56:55,845] ERROR websocket error in session 69 (io.confluent.ksql.rest.server.resources.streaming.WSQueryEndpoint:200)
java.util.concurrent.TimeoutException: Idle timeout expired: 300000/300000 ms
at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.jav …
```

Minor: close websocket session on error

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/ClusterTerminationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java

Small PR to simplify the use of `RestIntegrationTestUtil` by creating the client inside the test.
This doesn't change the run time of the test and makes the tests cleaner.

Minor: Simplify `RestIntegrationTestUtil`

---

ksql-engine/pom.xml
pom.xml

Upstream changes in KS have broken our build. These look to be compatibility breaking changes.  They are looking into it.  For now, we pin the version.
Issue to review: #2915
`mvn test`

Fix the build by temporarily pinning kstreams version

---

ksql-common/src/main/java/io/confluent/ksql/util/RetryUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/RetryUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/services/LazyServiceContext.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopic.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerPrecondition.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/Errors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ServerInfoResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/state/ServerState.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/state/ServerStateDynamicBinding.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/state/ServerStateFilter.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogServerUtils.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/ServerInfoResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/state/ServerStateDynamicBindingTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/state/ServerStateFilterTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/state/ServerStateTest.java

Refactor the server setup to first create all the resources and start
accepting requests before initializing and replaying the command topic.
While the command topic is being initialized/replayed, KSQL requests
will return an error indicating that the server is initializing.
As part of this change, I've consolidated this initializing state and
the terminating state (entered when a TERMINATE request is received)
into a single state machine tracked under the package
io.confluent.ksql.rest.server.state. This package also has a request
filter that ensures that requests are only served when the server is
in READY state.
Finally, this patch adds support for checking preconditions before
initializing the server. The preconditions are provided in config
via the ksql.rest.server.preconditions …

Add support for checking external preconditions while still serving

---

ksql-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/function/UdfIndexTest.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java

Drop `SchemaUtil.getSchemaTypeAsSqlType` in favour of more fully featured `SqlSchemaFormatter`.
The latter outputs the full schema of complex types, e.g. `STRUCT<A INT, B DOUBLE`, rather than just `STRUCT`.
Enhanced tests in the only place the old method was used to show now more useful schema info.

Minor: Drop use of `SchemaUtil.getSchemaTypeAsSqlType` 

---

ksql-common/src/main/java/io/confluent/ksql/schema/connect/SchemaWalker.java
ksql-common/src/test/java/io/confluent/ksql/schema/connect/SchemaWalkerTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/EntityUtil.java
ksql-serde/src/main/java/io/confluent/ksql/serde/avro/AvroDataTranslator.java
ksql-serde/src/main/java/io/confluent/ksql/serde/json/JsonSerdeUtils.java

Refactor `EntityUtil` to make use of new `SchemaWalker`.
This involved a small enhancement to `SchemaWalker` to allow it to return a different type for fields, which will make sense in a lot of cases.
`mvn test`.

Minor: Refactor `EntityUtil` to make use of new `SchemaWalker`

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceCommand.java
ksql-engine/src/main/java/io/confluent/ksql/engine/QueryEngine.java
ksql-engine/src/main/java/io/confluent/ksql/serde/SerdeOptions.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceCommandTest.java
ksql-engine/src/test/java/io/confluent/ksql/serde/SerdeOptionsTest.java

Moves the building of sets of `SerdeOption`s into one place. This has pros and cons. But I think it makes the code around SerdeOptions a little easier to understand, find and test.  The con would be that if more areas are added that need to build serde options then this class grows, as its essentially a God class.
Thoughts? Is this an improvement or not?
`mvn test`

Minor: Move serde option manipulation into one place.

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFactoryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java

One of the tests in the rest-app module was creating an instance of KSQLEngine and not closing it. This resulted in failure of other tests since the metric names were in use. This PR fixes the test by closing the instance.
It also removes some unnecessary mocks.

Fixing some rest-app module tests.

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java

The version checker agent in the headless mode was picking the empty properties. This PR corrects this bug along with adding a test for it.
This will be merged after #2947

Using the correct props for the version checker in the headless mode.

---

docs/developer-guide/serialization.rst
docs/developer-guide/syntax-reference.rst

Following on from the discussion in the [`WRAP_SINGLE_VALUE` PR](https://github.com/confluentinc/ksql/pull/2899#issuecomment-498827407), this PR adds documentation around the `null` handling of unwrapped single values.
Docs only change.

Docs around null handling for unwrapped single-field schemas.

---

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/SqlTypeTest.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceCommand.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfCompiler.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorFunctionalTest.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/FieldNode.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/SourceNode.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/TestCaseNode.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/KeyFieldDeserializer.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/TableElement.java
ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercer.java
ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/SchemaConverters.java
ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/SqlValueCoercer.java
ksql-parser/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java
ksql-parser/src/test/java/io/confluent/ksql/schema/ksql/SchemaConvertersTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java

The upcast checks done as part of the `INSERT VALUES` work coerce values by inspecting the  Connect schema types to see the value can be coerced / upcast.  This PR looks to change this to use our own SQL type system to work out if values can be upcast / coerced.
(Part of some back burner work to move core KSQL away from the Connect schema type, as it will not be sufficient when we have quoted identifiers).
`mvn test`

Upcast checks should use SQL schema.

---

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/AuthorizationTopicAccessValidatorTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/StreamsSelectAndProjectIntTest.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/DataSourceNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-engine/src/test/java/io/confluent/ksql/topic/SourceTopicsExtractorTest.java
ksql-engine/src/test/java/io/confluent/ksql/topic/TopicCreateInjectorTest.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/model/StructuredDataSource.java
ksql-metastore/src/test/java/io/confluent/ksql/metastore/model/MetaStoreMatchers.java
ksql-metastore/src/test/java/io/confluent/ksql/metastore/model/StructuredDataSourceTest.java
ksql-metastore/src/test/java/io/confluent/ksql/util/MetaStoreFixture.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/RequestValidatorTest.java

Correct test cases that create sources with logical schemas that do NOT have implicit fields. Current prod code always uses schemas with implicit fields, so should the tests.
This is prep work from a later PR which will clean up implicits handling.
Note: most, if not all, of these `.withImplicits` and the addition of `ROWKEY`/`ROWTIME` to tests will be removed again in a later PR.  The purpose of this PR is to: 
1) Fix up any tests that have the wrong result due to using the wrong schema, 
2) Keep these fixes out of the main PR that is coming so its easier to review.
3) Give me a set of tests for my later PR that are using the correct schemas and correct results.
Only two none-test files are changed:
- StructuredDataSource: has a check in it to ensure instances are created with a schema …

Minor: Correct tests to ensure sources have correct schemas

---

ksql-common/src/main/java/io/confluent/ksql/function/AggregateFunctionFactory.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdafAggregateFunctionFactory.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/count/CountAggFunctionFactory.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/max/MaxAggFunctionFactory.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/min/MinAggFunctionFactory.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/sum/SumAggFunctionFactory.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopKAggregateFunctionFactory.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctAggFunctionFactory.java
ksql-engine/src/test/java/io/confluent/ksql/function/InternalFunctionRegistryTest.java

This change delays creating a `KsqlAggregateFunction` until `getProperAggregateFunction` is called. This is necessary because when I introduce the corresponding Decimal Aggregate Functions, I need to know the argument schema when I create it. 
- No functionality changes, passes `mvn clean install`

Minor: refactor AggregateFunctionFactory for future decimal support

---

ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksql-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java

Adds a new metric `liveness-indicator` that always has value 1. As the name suggests, the new metric simply indicates the KSQL engine is up and emitting metrics. 
Added unit test.

Minor: Add liveness indicator metric

---

ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercer.java
ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/SqlValueCoercer.java
ksql-parser/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java

Adds support to insert into for DECIMAL types.
Unit testing and CLI testing
```sql
ksql> create stream s2 (ticker varchar, value decimal(4,2)) with (kafka_topic='s2', value_format='avro', partitions=1);
Message
Stream created
ksql> insert into s2 values ('msft', 'msft', 12.23);
ksql> insert into s2 values ('cnfl', 'cnfl', '22.33');
ksql> insert into s2 values ('cnfl', 'cnfl', 22);
ksql> SELECT * FROM S2;
1560458488849 | msft | msft | 12.23
1560458504014 | cnfl | cnfl | 22.33
1560458649743 | cnfl | cnfl | 22.0
^CQuery terminated
```

INSERT VALUES support for DECIMAL type

---

docs/changelog.rst
docs/installation/server-config/config-reference.rst
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/ServiceInfo.java
ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutorFactory.java

Adds a new config `ksql.metrics.tags.custom` which allows users to add custom tags to KSQL engine metrics. The value of the config is a string of semicolon-separated key-value pairs of tags to add. For example, passing the value `key1:value1;key2:value2` adds two tags to each metric, one with name `key1` and value `value1`, the other with name `key2` and value `value2`. The default value for the config is the empty string which results in no custom tags being added.
The config currently only applies to the new metrics format (see https://github.com/confluentinc/ksql/pull/2831), but if preferable I can add the custom tags to the old format as well.
Also unsure whether this change is worth adding to the either the changelog or the server config docs. Thoughts?

Add config for custom metrics tags

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/ExpressionAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/DataSourceNode.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerTest.java
ksql-parser/src/main/java/io/confluent/ksql/util/DataSourceExtractor.java

Minor PR in prep for later PR to clean up implicits in schemas.
This PR moves all `DataSourceNode` creation into `Analyzer` and has the `Analysis` track `DataSourceNode`s rather than `StructuredDataSource`s.
This has the benefit that both the node's and the source's schema are available to the `Analyzer` and others, stopping them having to replicate the operations the node does to the source's schema, i.e. removes code duplication.
The `Analyzer` already created the `DataSourceNode`s for any join, now it does so for non-joins too.
The PR also simplifies `DataSourceExtractor`.
`mvn test`

Minor: Have `Analyzer` create and track `DataSourceNode` 

---

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/main/java/io/confluent/ksql/util/ComparisonUtil.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/ComparisonUtilTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionTypeManagerTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/decimal.json

Support comparisons (`<,<=,=,<>,>=,>` and `IS DISTINCT FROM`) between DECIMALs and other numeric types.
- new QTT and unit tests

Comparison support for DECIMAL type

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/ServiceInfo.java
ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlMetric.java
ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlMetricsExtension.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java

Introduces a new interface `KsqlMetricsExtension` for users to specify custom metrics to be emitted alongside the default engine JMX metrics. Users may point the `ksql.metrics.extension` config at their custom implementation in order to emit custom metrics.
Manual + unit tests.

Add extension for custom metrics

---

bin/ksql-run-class

Allow security plugins path to the start of the classpath to ensure that plugins and their dependencies take precedence.

Add confluent-security to classpath to enable security plugins

---

ksql-engine/pom.xml
ksql-version-metrics-client/pom.xml

Fix ksql packaging by adding explicit kafka core jar. The error seen is:
> Exception in thread "main" java.lang.NoClassDefFoundError: kafka/admin/AdminOperationException
>     at io.confluent.ksql.version.metrics.KsqlVersionChecker.<init>(KsqlVersionChecker.java:41)
>     at io.confluent.ksql.version.metrics.KsqlVersionCheckerAgent.start(KsqlVersionCheckerAgent.java:76)
>     at io.confluent.ksql.rest.server.KsqlRestApplication.start(KsqlRestApplication.java:207)
>     at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:65)
This is as a result of https://github.com/confluentinc/kafka/commit/72ff0d2bba.
Manual verification.

Add explicit kafka core dependency for support metrics

---

ksql-engine/pom.xml
ksql-version-metrics-client/pom.xml
ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/KsqlVersionChecker.java

BaseMetricsReporter in support-metrics-common is being updated to avoid dependency on core in components like KSQL which don't use ZK. This PR reflect the changes to the base class.
Manual testing of KSQL startup without core jars.

Remove core dependency added for support metrics workaround

---

ksql-common/src/main/java/io/confluent/ksql/util/DecimalUtil.java
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/DecimalUtilTest.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/decimal.json

Supports math between decimals and other numbers. The implicit conversions follow Postgres:
- Decimal/Int math will convert Int to Decimal(10, 0) and then follow the decimal math conversions
- Decimal/Long math will convert Long to Decimal(19, 0) and then follow the decimal math conversions
- Decimal/Double math will convert the decimal to a floating point and then use floating point math rules
All of these operations leverage the previous casting work, this PR just introduces the constant conversions from Int/Long to decimal.
- Unit testing
- QTT

decimal math with other numbers

---

design-proposals/README.md
design-proposals/klip-4-custom-types.md

**Author**: agavra | 
**Release Target**: 5.4 | 
**Status**: In Discussion | 
**Discussion**: https://github.com/confluentinc/ksql/pull/2894
**tl;dr:** *Introduce a feature that makes custom types easier to work with in KSQL by aliasing
complex type declarations.*
Kafka often contains very complex nested data structures and it is common to see schemas nested with
other schemas. It is desirable to be able to define this custom schema in KSQL once and reference it
in all future statements. For example, imagine the following schema declarations:
```sql
CREATE TYPE ADDRESS AS STRUCT<number INTEGER, street VARCHAR, city VARCHAR>;
CREATE TYPE PERSON AS STRUCT<firstname VARCHAR, lastname VARCHAR, address ADDRESS>;
CREATE TYPE COMPANY AS STRUCT<name VARCHAR, headquarters ADDRESS>;
```
With this …

docs: KLIP-4 custom types

---

design-proposals/klip-5-internal-schemas-for-KSQL-engine.md

**Author**: hjafarpour |
**Release Target**: 5.4 |
**Status**: In Discussion |
**Discussion**:
**tl;dr:** *Introduce the internal schemas for KSQL engine to decouple the internal identifier names from the
external field names so KSQL can handle any field name in the input data.*
Currently when users declare the schema for a stream or table, KSQL engine uses the provided schema
to perform query processing on the stream or table data. This means that the engine uses the same
names in the schema fields to refer to the schema fields in computations such as expression evaluation
or filter evaluation. We generate Java code to evaluate such expressions which imposes certain
restrictions on variable naming. However, requiring user schemas to comply with variable naming
requirements in Java limits …

docs: Klip-5: Internal Schemas for KSQL Engine

---

.gitignore
CONTRIBUTING.md
commitlint.config.js
package-lock.json
package.json
pom.xml

Let's adopt [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) for our commit messages so we can automatically generate high-quality changelogs. This PR adds [commitlint](https://github.com/conventional-changelog/commitlint) as a pre-commit check so that (after running `npm install`), commits that do not follow the Conventional Commit specification will be rejected locally. This PR also adds `npm install` into our Maven build process so that running `mvn package` runs `npm install`.
Because our repository uses the "Squash and Merge" GitHub option for merging commits, the commit messages that actually matter for changelog generation are the ones we get from squashing, rather than the individual commits that go into each PR. GitHub defaults commit messages for …

build: add commitlint for conventional commits

---

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/ExpressionAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/SourceSchemas.java
ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/SourceSchemasTest.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/elements.json
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java

As was requested in a[ previous PR by @hjafarpour,](https://github.com/confluentinc/ksql/pull/2962#pullrequestreview-249045767) this PR looks to move the creation of `JoinNode` and `DataSourceNode` out of the `Analyzer` and into the `LogicalPlanner`. The `LogicalPlanner` is now responsible for creating all logical node types.
Main changes:
* Rather than creating the `JoinNode` the `Analyzer` now builds a `JoinInfo`, which is stored in `Analysis`. `LogicalPlanner` uses this info to build the `JoinNode`.
* Rather than creating the `DataSourceNode` the `Analyzer` now stores a `AliasedDataSource` in `Analysis`. `LogicalPlanner` uses this info to build the `DataSourceNode`(s).
* `Analyzer` resolves all the columns in a `SELECT *`  using the schemas of all the source(s) involved, rather than …

refactor: Move logical plan node creation into the LogicalPlanner (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java

On a `selectKey` the old code looks up the index of the new key field in the value schema per-row processed. This index is constant and can be pre-calculated just the once.
`mvn test`

perf: Only look up index of new key field once, not per row processed (MINOR)

---

CONTRIBUTING.md
pom.xml

Following up on https://github.com/confluentinc/ksql/pull/3008/, this PR does two things:
- removes `npm install` from our Maven build, since I couldn't find a way to get Husky to use the local npm installed by maven-frontend-plugin. To enable commitlint, users should have `npm` and run `npm install` from the KSQL root directory, rather than relying on `mvn package`.
- adds a section on commitlint to CONTRIBUTING.md.
`mvn clean package` and manual testing of commitlint.

build: remove `npm install` from `mvn package`

---

ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/engine/SqlFormatInjector.java

#3027 discovered some pretty bad holes in our QTT tests - namely our production environment executes a query _after_ it was formatted, but QTT tests execute the pre-formatted query. This change is a stop-gap bandaid that makes sure that all of our tests that go through the EndToEndExecutionUtil will use the formatted query.
- ran all the tests. the windowed QTT tests failed before applying #3027 but succeeded afterwards.

test(qtt): add test coverage in QTT for the SqlSchemaFormatter

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlServerMainTest.java

Kafka Streams needs a local folder to write state related files. The default in CP is `/var/lib/kafka-streams`. This folder should exists and KSQL server should have write access to it. 
This PR enforces this when KSQL server starts. If the folder does not exist or is not writable, the server will show appropriate message and won't start.
Unit tests were added.

feat: Enforce availability of the streams state directory.

---

ksql-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksql-common/src/main/java/io/confluent/ksql/schema/connect/SqlSchemaFormatter.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/FormatOptions.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/PersistenceSchema.java
ksql-common/src/test/java/io/confluent/ksql/schema/connect/SqlSchemaFormatterTest.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksql-engine/src/main/java/io/confluent/ksql/physical/QuerySchemas.java
ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorFunctionalTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/ExpressionFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksql-parser/src/test/java/io/confluent/ksql/parser/util/ParserUtilTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeFunctionExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogServerUtils.java
ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java

While working in the area I noticed `ParserUtil` has two sets of the parsers reserved words. Let's remove one.  The only difference between the two is that one includes just literals and the other literals and symbols.  AFAICT symbols are never reserved words. Symbols are things like: `DIGIT_IDENTIFIER` and `QUOTED_IDENTIFIER`. 
`SqlSchemaFormatter` takes an optional set of reserved words.  `ParserUtil` now exposes a function to check if a word is reserved or not. So I've refactored the formatter to take a predicate.  While doing so I've removed the default constructor and static instances, which didn't take the set of reserved words, and just assumed none were reserved. This is a potentially dangerous assumption, that could lead to bugs. Hence removing this and creating instances where …

refactor: improve reserve words handling

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlServerMainTest.java

Currently KSQL server fails if the streams state directory does not exist. With this PR, KSQL server will try to create the folder if it does not exist.
Some of the error messages were also improved.
Unit tests were updated.

fix: Create the streams state directory if it does not exist.

---

ksql-common/src/main/java/io/confluent/ksql/configdef/ConfigValidators.java
ksql-common/src/test/java/io/confluent/ksql/configdef/ConfigValidatorsTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceCommandTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateStreamCommandTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateTableCommandTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorTest.java
ksql-engine/src/test/java/io/confluent/ksql/topic/TopicCreateInjectorTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateSourceProperties.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStream.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTable.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/CreateSourcePropertiesTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/ParserModelTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

Switching `CreateSourceProperties` over to use ConfigDef removes a lot of code, (and hence potential bugs), and we open up the scope to be able to generate our docs off this in the future.
The main driver behind this change is that I'd like to use the same pattern for C*AS statements, and I'd like common props, e.g. `VALUE_FORMAT` to be defined in one place, which is easily possible with `ConfigDef`.
suitable tests added.

refactor: switch create source properties over to config def

---

ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamPublisher.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriterTest.java

KSQL supports two types of queries:
- Persistent queries, e.g. `CREATE STREAM X as SELECT * FROM Y;`
- Transient queries, e.g. `SELECT * FROM Y;`
And has two subclasses of `QueryMetadata`:
- `PersistentQueryMetadata`
- `QueuedQueryMetadata`
This PR just renames the second one to `TransientQueryMetadata` to better reflect _what_ it is and to therefore make the code easier for noobs to understand.
None. It's just a rename,

refactor: rename queued query metadata to transient query metadata

---

ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java

- commas now placed after each projection field on same line
- fixed unit tests to reflect new format
_Fixes #3014, to place commas on the same line as the field_
_Fixed unit tests and also verified on ksql commandline and confluent UI locally._

fix: misplaced commas when formatting CTAS statements

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-version-metrics-client/pom.xml
ksql-version-metrics-client/src/main/java/io/confluent/ksql/version/metrics/collector/BasicCollector.java
ksql-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/collector/BasicCollectorTest.java

Use local version checker and change a test case to fix the build. 
Also had to change the kafka streams state directory back to `/tmp/kafka-streams` in the `KsqlResourceTest.shouldListDefaultKsqlProperty`, since that is the new default upstream.
Build passes

fix: Update version checker to use new dependencies

---

ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java
ksql-examples/src/main/java/io/confluent/ksql/datagen/ProducerFactory.java

Data Gen to use main `Format` enum rather than its own...
`mvn test` and started datagen.

refactor: datagen to use main format enum (Minor)

---

docs/developer-guide/query-with-structured-data.rst
docs/includes/ksql-includes.rst
ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/KafkaTopicsListTableBuilder.java
ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KafkaTopicInfo.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KafkaTopicsList.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListTopicsExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KafkaTopicsListTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListTopicsExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

We've already removed `REGSITER TOPIC` and `DELETE TOPIC` syntax, but the
CLI still reports if a topic is registered or not.  Let's tidy this up.
This PR removes the `Registered` column from the `show topics` command as there is not 'registered topic' functionality any more.
Also see related #3072
`mvn test`.

fix: remove last of registered topics stuff from api / cli (MINOR)

---

ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ClusterTerminator.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/ClusterTerminationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/ClusterTerminatorTest.java

Part of the work to remove this functionality from the metastore
`mvn test`

refactor: switch cluster terminator off metastore get all ksql topics (MINOR)

---

ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ShowColumns.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/ShowColumnsTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java

In the CLI you can still do:
```
DESCRIBE TOPIC foo;
```
Which will only work if `foo` is a registered topic.
Registered topic functionality has been removed, but this functionality was missed - let's remove it. 
Also see related #3068
`mvn test`.

fix: drop describe topic functionality (MINOR)

---

ksql-functional-tests/src/test/java/io/confluent/ksql/test/EndToEndEngineTestUtil.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/TopologyFileGenerator.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/TopologyFileGeneratorTest.java

Because the class name does not end in `Test` mvn surefire ignore it. So lets move the test into a test file.
This highlights we've got test cases with `/` in their name, which when used in a path, results in a `DirectoryDoesNotExist` exception, so let's replace the `\` with a `_`.

fix: ensure topology generator test runs in build (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksql-engine/src/main/java/io/confluent/ksql/topic/TopicDeleteInjector.java
ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ClusterTerminator.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/ClusterTerminatorTest.java

The `delete.topic.enable` configuration check done during the `DROP STREAM DELETE TOPIC` command is unnecessary. This check is hiding the real error if a user cannot delete the topic when dropping the stream. Actually, the drop stream delete topic does not fail if the flag is set to False.
To fix the problem, I removed the `delete.topic.enable` check, and rely on the `TopicDeletionDisableException` thrown when attempting to delete the topic. For `DROP STREAM DELETE TOPIC`, an error will be displayed in the console about the delete.topic.enable. 
For Cluster termination, the exception is ignored, and let KSQL continue with the cluster termination and cleanup of any other internal state.
Added a few test cases to validate the changes.
Verify the `DROP STREAM DELETE TOPIC` works as expected …

fix: Remove delete.topic.enable check

---

docs/changelog.rst
docs/installation/server-config/config-reference.rst
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/ServiceInfo.java
ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutorFactory.java

Backport changes from https://github.com/confluentinc/ksql/pull/2971 to `5.3.x`.

feat: add config for custom metrics tags (5.3.x)

---

ksql-engine/src/main/java/io/confluent/ksql/function/udaf/array/CollectListUdaf.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/array/CollectListUdafTest.java
ksql-engine/src/test/resources/query-validation-tests/collect-list.json

Same as https://github.com/confluentinc/ksql/pull/3093, but retargeted at an earlier branch.
(The only difference between these diffs and the ones in https://github.com/confluentinc/ksql/pull/3093 are that the old query translation test framework (used in 5.1) required all messages to have timestamps. I will remove these timestamps from 5.2 and later via a manual merge after this PR is submitted.)
Updated unit tests and added query translation tests.

fix: `COLLECT_LIST` can now be applied to tables

---

docs/developer-guide/api.rst
ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlWarning.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionList.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/CommandStatusEntityTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KafkaTopicsListTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KsqlTopicsListTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

This patch adds a mechanism for returning warnings in KsqlEntity for
successful api responses. This patch also adds some warnings for source
listings. Now, when a client tries to list or describe a source, and ksql
is unable to get the details of the backing topic from kafka, a result is
returned that includes 0-values for the underlying topic info (partitions,
replicas), and includes response warnings about the issue with Kafka.

feat(rest server): add warnings when listing fails with kafka error

---

ksql-engine/src/main/java/io/confluent/ksql/topic/TopicDeleteInjector.java
ksql-engine/src/test/java/io/confluent/ksql/topic/TopicDeleteInjectorTest.java

When handling DELETE TOPIC, check that other sources don't use the topic
before deleting. This is an optimistic check - the user could still delete
topics out from under us, and its not safe racing against concurrent statements.
But, we've seen single users kick themselves this way in the past, so this should
help in those cases.

fix: check for other sources using a topic before deleting

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/engine/TopicAccessValidatorFactory.java
ksql-engine/src/test/java/io/confluent/ksql/engine/TopicAccessValidatorFactoryTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

Adds a config called ksql.access.validator.enable for enabling the
topic access validator. The possible values for this config are "on",
"off", and "auto". "on" is used to enable the validator, "off"
is used to disable it, and "auto" can be set to have ksql query kafka
properties to auto-discover whether or not the validator can be used (
this is the behaviour before this patch, and is the current default
value for this setting). This config is useful for enabling the validator
when using ksql against multi-tenant kafka, where ksql will not have
access to the broker's configs.
This patch also switches the topic validator factory test to use mockito
for mocking, instead of easymock.

feat: add config for enabling topic access validator

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java

Noticed this was missing when working on the new field type. This PR adds the key fields to the `LogicalSchema.toString` output.  This will soon be important as the type of `ROWKEY` may be different.
Usual.

fix: logicalSchema toString() to include key fields (MINOR)

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Options.java

Exposes the --user/--password command-line options when executing `ksql --help`. I don't know why they were hidden if there is nothing to secure by hiding them.
Verify `ksql --help` exposes the parameters:
```
> ksql --help
...
--password <password>, -p <password>
If your KSQL server is configured for authentication, then provide
your password here. The username must be specified separately with
the -u/--user flag
...
--user <userName>, -u <userName>
If your KSQL server is configured for authentication, then provide
your user name here. The password must be specified separately with
the -p/--password flag
...
```

fix: expose user/password command line options

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/filters/KsqlAuthorizationFilter.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java

Fix a logging issue in the Authorization filter which was displaying the `Principal` object instead of the user name.

fix: authorization filter is logging incorrect username

---

ksql-engine/src/main/java/io/confluent/ksql/exception/KafkaDeleteTopicsException.java
ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksql-engine/src/main/java/io/confluent/ksql/topic/TopicDeleteInjector.java
ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
ksql-engine/src/test/java/io/confluent/ksql/topic/TopicDeleteInjectorTest.java

https://github.com/confluentinc/ksql/issues/3048
Added new exception class that can store corresponding error messages that can occur while trying to delete a topic.
Wrote some helper functions in TopicDeleteInjector in order to reduce cyclomatic complexity.
Unit tests
Testing using KSQL CLI
Deleting subjects with schema registry and using kafka-topics to delete topics.

fix: drop succeeds even if missing topic or schema

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/pom.xml
ksql-engine/src/main/java/io/confluent/ksql/services/ConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/DefaultServiceContext.java
ksql-engine/src/main/java/io/confluent/ksql/services/LazyServiceContext.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedServiceContext.java
ksql-engine/src/main/java/io/confluent/ksql/services/ServiceContext.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/SandboxConnectClientTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/SandboxedServiceContextTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/TestServiceContext.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListTopicsExecutorTest.java
pom.xml

This PR introduces a client that can issue requests to connect and wires it through the `ServiceContext` as well as make the necessary `pom.xml` changes. This is part 1 of a few PRs for connect integration and an effort to keep them small.
Unit testing for the new components, but there isn't actually any new functionality that is introduced with this change.

feat(ksql-connect): introduce ConnectClient for REST requests

---

ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/Placeholder.java

This patch adds a dummy placeholder class to ksql-execution. For some reason,
when the jar is empty maven complains about the jar being replaced when its built
by multiple maven targets (e.g. `mvn package install`). This will be cleaned up when
we start moving code into this project.

fix: dummy placeholder class in ksql-execution

---

ksql-engine/src/main/java/io/confluent/ksql/exception/KafkaDeleteTopicsException.java
ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java

javafx is not in OpenJDK, replacing usage of JavaFx with our internal Pair class.

fix: remove non-standard JavaFx usage of Pair

---

ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java

SqlToJavaVisitor only needs to deal with expressions, so this patch has
it implementExpressionVisitor. This patch also adds some missing test
cases to its unit test for handling unsupported type constructors.
Finally, we simplify the tests a bit by having them just parse expressions
(instead of whole statements).
This patch depends on https://github.com/confluentinc/ksql/pull/3126, so review that first.

refactor: implement ExpressionVisitor in SqlToJava

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/ExpressionAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java
ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ExpressionTreeRewriter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/VisitParentExpressionVisitor.java

This patch adds an abstract base visitor for ExpressionVisitor, called
VisitParentExpressionVisitor, which provides a default implementation of
each visit call that just delegates to a visit to the parent type. E.g.
visitBooleanLiteral calls visitLiteral calls visitExpression. This is
basically what the existing AstVisitor does for the AST. This patch also
migrates the expression-only visitors that inherit from AstVisitor to
VisitParentExpressionVisitor
Just a refactor, so no new tests.

refactor: add VisitParentExpressionVisitor

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java
ksql-engine/src/test/java/io/confluent/ksql/testutils/ExpressionParseTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionTypeManagerTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/VisitorUtil.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ExpressionVisitor.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/TraversalExpressionVisitor.java

This patch refactors AggregateAnalyzer and ExpressionTypeManager to implement
ExpressionVisitor. ExpressionTypeManager implements ExpressionVisitor directly,
and now has impls for unsupported expressions (which throw). AggregateAnalyzer
implements ExpressionVisitor by inheriting from TraversalExpressionVisitor, an
abstract base which implements a traversal of the expression tree by default.

refactor: AggregateAnalyzer/ExpressionTypeManager impl ExpressionVisitor

---

ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateConnector.java
ksql-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/CreateConnectorTest.java

As part 2 of a series of PRs related to connect integration, this one adds syntax for `CREATE (SOURCE | SINK) CONNECTOR`. This does not wire in anything, these statements will parse but nothing more.
Unit testing

feat(ksql-connect): introduce syntax for CREATE CONNECTOR (syntax only)

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/KafkaConfigStore.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/KafkaConfigStoreTest.java

Our standalone module goes through `KafkaConfigStore`, which in turn uses `ImmutableMap`. The `ImmutableMap` requires all values in a map to be non-null. Since we added a few configurations with `null` defaults - we need to filter them out here.
Updated tests to remove the `filterNullEntries` and manually spun up KSQL standalone.

fix: filter null entries before creating KafkaConfigStore

---

ksql-package/pom.xml

The KSQL testing tool wasn't added to the `ksql-package` module, which meant that it will not be in the tarball, or rpms, or debs. This patch adds it.
`ksql-functional-tests.jar` now exists in the built package, where previously it did not. 
```
amehta-macbook-pro-3:ksql-package-5.4.0-SNAPSHOT-package apurva$ find . -name "*functional*"
./share/java/ksql/ksql-functional-tests-5.4.0-SNAPSHOT.jar
amehta-macbook-pro-3:ksql-package-5.4.0-SNAPSHOT-package apurva$ pwd
/Users/apurva/workspace/confluent/ksql/ksql-package/target/ksql-package-5.4.0-SNAPSHOT-package
amehta-macbook-pro-3:ksql-package-5.4.0-SNAPSHOT-package apurva$
```

fix: add ksql-functional-tests to the ksql package

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerPrecondition.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/Errors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/state/ServerState.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/state/ServerStateTest.java

Instead of only receiving an error string from precondition checks, receives a KsqlErrorMessage object that can be directly passed along to anyone who checks serverState while it's in State.Initializing
Fixed unit tests that broke and ran them to verify they passed
Tested in CPD

refactor: allow for more specific error messages to be sent when the server is unavailable

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/ConnectorInfoTableBuilder.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/ErrorEntityTableBuilder.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/ConnectorInfoEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/CreateConnectorEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/ErrorEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ConnectExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ConnectExecutorTest.java

Wires in the two previous connect prs #3137 and #3139 by introducing the following classes:
- `ErrorEntity` represents an error response from an external service
- `ConnectorInfoEntity` represents a response from connect describing a connector
- `ConnectExecutor` handles a `CreateConnector` statement
- Basic unit tests
- End-to-end testing
```
ksql> CREATE SOURCE CONNECTOR `jdbc-connector6` WITH("connector.class"='io.confluent.connect.jdbc.JdbcSourceConnector',"tasks.max"='1',"connection.url"='jdbc:postgresql://localhost:5432/almog.gavra',"mode"='bulk',"topic.prefix"='jdbc2-',"transforms"='createKey,extractString',"transforms.createKey.type"= 'org.apache.kafka.connect.transforms.ValueToKey', "transforms.createKey.fields"='username',"transforms.extractString.type"='org.apache.kafka.connect. …
```

feat(ksql-connect): wiring for creating connectors

---

docs/concepts/ksql-architecture.rst
docs/installation/server-config/config-reference.rst
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

Doc change to call out that the service id should ideally end in a `-` or `_` to make reading the internal topic names easier.
Prompted by https://github.com/confluentinc/ksql/pull/3085
doc only change.

docs: call out that service id should end in separator char

---

docs/developer-guide/serialization.rst
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerPrecondition.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/Errors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/state/ServerState.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/state/ServerStateTest.java

tldr: messed up a pint merge from 5.3.x to master, so reverted the merge, but now pint won't be able to pick up on the changes involved in that merge now. This manually applies the two changes from that merge to master.
Original merge:https://github.com/confluentinc/ksql/commit/b1d424189dcaed362c9aa8c2ed2b065b7dda749c
Revert: https://github.com/confluentinc/ksql/commit/4cfafa5d5c8892b07ead780d1e56bb47e1331794
Changes:
https://github.com/confluentinc/ksql/commit/2b8725ec976d295e9318fb7aafbae9324e8b8677
https://github.com/confluentinc/ksql/commit/828418e647d2cf760a995e0a6a5fb64bf1474d4a

chore: Fix merge revert

---

docs/developer-guide/syntax-reference.rst

The docs for `INSERT VALUES` currently suggest using double-quotes around string literals but this results in a parsing error:
```
ksql> INSERT INTO foo (col1, col2) VALUES ("test", "test2");
line 1:38: mismatched input '"test"' expecting {')', 'NULL', 'TRUE', 'FALSE', STRING, INTEGER_VALUE, DECIMAL_VALUE}
Statement: INSERT INTO foo (col1, col2) VALUES ("test", "test2");
Caused by: line 1:38: mismatched input '"test"' expecting {')', 'NULL', 'TRUE',
'FALSE', STRING, INTEGER_VALUE, DECIMAL_VALUE}
Caused by: org.antlr.v4.runtime.InputMismatchException
```
Single-quotes is the way to go:
```
ksql> INSERT INTO foo (col1, col2) VALUES ('test', 'test2');
```
This PR updates the docs accordingly.
None, docs-only change.

docs: fix quotes in INSERT VALUES examples

---

docs/developer-guide/query-with-structured-data.rst
docs/developer-guide/syntax-reference.rst
docs/includes/ksql-includes.rst
docs/tutorials/basics-control-center.rst
ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/KafkaTopicsListTableBuilder.java
ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ListTopics.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/ListTopicsTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KafkaTopicInfoExtended.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KafkaTopicsList.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KafkaTopicsListExtended.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListTopicsExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KafkaTopicsListExtendedTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListTopicsExecutorTest.java

Fixes #1268
BREAKING CHANGE: "SHOW TOPICS" no longer includes the "Consumers" and
"ConsumerGroups" columns. You can use "SHOW TOPICS EXTENDED" to get the
output previous emitted from "SHOW TOPICS". See below for examples.
This change splits "SHOW TOPICS" into two commands:
1. "SHOW TOPICS EXTENDED", which shows what was previously shown by
"SHOW TOPICS". Sample output:
```
ksql> show topics extended;
Kafka Topic                                                                                   | Partitions | Partition Replicas | Consumers | ConsumerGroups
--------------------------------------------------------------------------------------------------------------------------------------------------------------
_confluent-command …
```

feat: Add SHOW TOPICS EXTENDED

---

ksql-common/src/main/java/io/confluent/ksql/links/DocumentationLinks.java
ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplier.java
ksql-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java
ksql-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplierTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/KsqlTestingToolTest.java

Fixes a few error messages caused by SchemaRegistry authorization errors. 
For instance, this error was displayed when attempting to create an AVRO stream without SR schem access:
```
ksql> create stream avro with (kafka_topic='avro', value_format='avro');
Schema registry fetch for topic avro request failed.
Caused by: Unrecognized token 'User': was expecting ('true', 'false' or 'null')
at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line:
1, column: 6]; error code: 50005
```
The new fixed error just adds a new line at the end of an old SR access error. In a secured SR environment, SR returns an authorization error even if the Subject does not exist.
```
ksql> create stream avro with (kafka_topic='avro', value_format='avro');
Avro schema for message values on …
```

fix: incorrect SR authorization message is displayed

---

docs/developer-guide/syntax-reference.rst
ksql-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToTimestamp.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SqlPredicate.java
ksql-functional-tests/src/test/resources/query-validation-tests/rowtime.json
ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriteForRowtime.java
ksql-parser/src/test/java/io/confluent/ksql/parser/rewrite/StatementRewriteForRowtimeTest.java

Because the `ROWTIME` is stored as a Long, the user either has to pass in Long values or use  `STRINGTOTIMESTAMP` function to make queries using `ROWTIME`, for example:
`ROWTIME > STRINGTOTIMESTAMP('1970-01-01', 'yyyy-mm-dd')`
`ROWTIME BETWEEN 156469222000 AND 1564692253275`
This change wraps datestrings with `STRINGTOTIMESTAMP` so the user can directly pass datestrings for querying:
`ROWTIME > '1970-01-01'`
`ROWTIME BETWEEN '1970-01-01 08:00:00' AND ''1970-01-01 10:00:00`
Wrote tests for several types of expressions.

Wrap timestamps in ROWTIME expressions with STRINGTOTIMESTAMP

---

docs/developer-guide/syntax-reference.rst

I added a paragraph in the docs about how alias are assigned to columns in the SELECT clause.
This is in regard to issue #2401 .
No testing, changes are only on docs.

docs: describe how aliases are assigned to columns in SELECT clause

---

config/ksql-server.properties
ksql-common/src/main/java/io/confluent/ksql/properties/with/CreateConfigs.java
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/connect/ConnectConfigService.java
ksql-engine/src/main/java/io/confluent/ksql/connect/ConnectPollingService.java
ksql-engine/src/main/java/io/confluent/ksql/connect/Connector.java
ksql-engine/src/main/java/io/confluent/ksql/connect/Connectors.java
ksql-engine/src/main/java/io/confluent/ksql/connect/KsqlConnect.java
ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/TopicSchemaSupplier.java
ksql-engine/src/main/java/io/confluent/ksql/services/ConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxConnectClient.java
ksql-engine/src/test/java/io/confluent/ksql/connect/ConnectConfigServiceTest.java
ksql-engine/src/test/java/io/confluent/ksql/connect/ConnectPollingServiceTest.java
ksql-engine/src/test/java/io/confluent/ksql/connect/ConnectorTest.java
ksql-engine/src/test/java/io/confluent/ksql/connect/ConnectorsTest.java
ksql-engine/src/test/java/io/confluent/ksql/connect/KsqlConnectTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java

This PR implements the most bare-bones mechanism to automatically import tables created from a JDBC connector. It should be noted that this PR is *incremental* and is the minimum chunk that I felt I could implement and put out in a single PR. See the Future Work section for upcoming PRs. Because of this, there are lots of limitations - BUT if you look at the testing done section it makes for a pretty 💣 💥  demo! What's left makes it much more robust.
There are two main services introduced:
- `ConnectConfigService` is in charge of listening to the `connect-configs` topic (value configurable) and polling /connectors endpoint, extracting "known" connector configurations, passing them to the `ConnectPollingService`. As of now, only JDBC source connector is a known connector.
- …

feat(ksql-connect): poll connect-configs and auto register sources

---

ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/cmd/RemoteServerSpecificCommandTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java

BREAKING CHANGE: Previously CLI startup permissions were based on whether the user has access to `/info`, but now it's based on whether the user has access to `/`. This change implies that if a user has permissions to `/` but not `/info`, they now have access to the CLI whereas previously they did not.
The CLI currently makes a call to `GET /info` to validate if a client can connect to the KSQL server. If the server is not authorized to access the endpoint, then the CLI displays the correct access error (or any other access) on the console.
With the introduction of the KSQL security extensions, these REST endpoints might have different access restrictions. For instance, the `GET /info` call might be opened to any authenticated user to get information about the KSQL server (such as KSQL …

fix: validate CLI using REST / instead of REST /info

---

design-proposals/README.md
design-proposals/klip-8-interactive-queries.md

**Author**: derekjn | 
**Release Target**: 5.4+ | 
**Status**: In Discussion | 
**Discussion**: [#530](https://github.com/confluentinc/ksql/issues/530)
Let’s begin by explicitly defining what is meant by the term “interactive query”:
> An interactive query in KSQL is a SELECT query issued against a KSQL table that runs until completion, returning a finite set of rows as a result. In other words, an interactive query is identical to a SQL query run against a traditional database.
Interactive queries are thus not currently possible in KSQL--all KSQL queries are streaming queries. This can often be surprising to users who have familiarity with other SQL-based systems.
Before exploring what the addition of interactive queries could look like in KSQL, it is important to first understand the …

docs(klip): klip-8: Interactive Queries

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-common/src/main/java/io/confluent/ksql/util/KsqlAuthorizationException.java
ksql-engine/src/main/java/io/confluent/ksql/engine/AuthorizationTopicAccessValidator.java
ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksql-engine/src/test/java/io/confluent/ksql/engine/AuthorizationTopicAccessValidatorTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java

KSQL-1444
KSQL-2891
Updated the createTopic and deleteTopic error handlers to catch TopicAuthorizationException which is returned when ACLs aren't set.
Created a util for generating ACL error messages 
```CREATE STREAM ASDFASDF(age BIGINT) WITH (KAFKA_TOPIC='new_topic', PARTITIONS=1, VALUE_FORMAT='DELIMITED');```
(Old error message):
```
Failed to guarantee existence of topic new_topic Caused by: Not authorized to access topics: [Authorization failed.]
```
(New error message): 
```
Authorization denied to Create on topic(s): [new_topic]
```
__________________________________________________________
```DROP STREAM SOURCE_TOPIC DELETE TOPIC;```
(Old error message): 
```
Could not delete the corresponding kafka topic: test_topic Caused by: Failed to clean up topics: test_topic
```
(New error …

refactor: improved error message for CREATE, DESCRIBE, and DELETE when no ACLs set for topic

---

ksql-engine/src/test/java/io/confluent/ksql/engine/SqlFormatInjector.java
ksql-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksql-functional-tests/src/test/resources/query-validation-tests/ensure-formatter.json
ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ListStreams.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ListTables.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/TerminateQuery.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java

Co-authored-by: Sergio Peña <sergio@confluent.io>
This reinstates #3037 into the current code path for the new testing tool. It also fixes some issues:
- `SqlFormatInjector` was allowing statements that cannot be parsed to go through in order to appease some tests. This is no longer the case
- `SqlFormatter` adds some formatting for statements that don't need it, but go through the testing path
- #3216 is applied (thanks @spena co-authored)
- `SqlFormatter` now properly escapes identifiers nested in structs
- `ensure-formatter.json` was added to make sure that a future refactor does not skip this code path
- unit testing
- `ensure-formatter.json`

fix: the QTTs now run through SqlFormatter & various other formatting fixes

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/Help.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-engine/src/main/java/io/confluent/ksql/connect/Connector.java
ksql-engine/src/main/java/io/confluent/ksql/connect/Connectors.java
ksql-engine/src/main/java/io/confluent/ksql/services/ConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxConnectClient.java
ksql-engine/src/test/java/io/confluent/ksql/connect/ConnectConfigServiceTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/SandboxConnectClientTest.java
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DescribeConnector.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/DescribeConnectorTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/ConnectorDescription.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutorTest.java

Implements functionality to describe a connector.
Unit testing and local test:
```
ksql> DESCRIBE CONNECTOR "jdbc-connector2";
Name                 : jdbc-connector2
Type                 : io.confluent.connect.jdbc.JdbcSourceConnector
State                : RUNNING
WorkerId             : 10.200.7.69:8083
Task ID | State   | Error Trace
---------------------------------
0       | RUNNING |
---------------------------------
Source Name           | Kafka Topic | Type
---------------------------------------------
JDBC_CONNECTOR2_USERS | jdbc2-users | TABLE
---------------------------------------------
```

feat: add DESCRIBE functionality for connectors

---

docs/faq.rst

Remove FAQ about configuring retention time for KSQL sink topics as KSQL doesn't currently support this, i.e., the answer in the FAQ is wrong. We should add the FAQ back in once KSQL actually supports this functionality. 
Related issues:
- https://github.com/confluentinc/ksql/issues/2346
- https://github.com/confluentinc/ksql/issues/408#issuecomment-399073255

docs: remove FAQ about setting retention time

---

ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/SqlFormatInjector.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksql-functional-tests/src/test/resources/query-validation-tests/ensure-formatter.json
ksql-parser/src/main/java/io/confluent/ksql/parser/ExpressionFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ListStreams.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ListTables.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/SetProperty.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/TerminateQuery.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/UnsetProperty.java
ksql-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksql-parser/src/test/java/io/confluent/ksql/parser/ExpressionFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/util/ParserUtilTest.java

This is a backport from https://github.com/confluentinc/ksql/pull/3222

Fix quoted reserved identifier 5.3

---

ksql-engine/pom.xml
ksql-engine/src/main/java/io/confluent/ksql/connect/ConnectConfigService.java
ksql-engine/src/main/java/io/confluent/ksql/connect/ConnectPollingService.java
ksql-engine/src/main/java/io/confluent/ksql/services/ConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxConnectClient.java
ksql-engine/src/test/java/io/confluent/ksql/connect/ConnectConfigServiceTest.java
ksql-engine/src/test/java/io/confluent/ksql/connect/ConnectPollingServiceTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ConnectExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListConnectorsExecutorTest.java
pom.xml

- Retry behavior to `DefaultConnectClient`
- Improved Logging
- Better synchronization between `ConnectConfigService` and `ConnectPollingService` (one now triggers the other)
Unit testing

feat: some robustness improvements for Connect integration

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/Table.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/ErrorEntityTableBuilder.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java

Do some pretty printing and wrapping to make sure that error messages aren't an eye sore.
**Before:**
**After:**

feat: format error messages better (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/engine/AuthorizationTopicAccessValidator.java
ksql-engine/src/main/java/io/confluent/ksql/exception/KsqlTopicAuthorizationException.java
ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksql-engine/src/test/java/io/confluent/ksql/engine/AuthorizationTopicAccessValidatorTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java

KsqlAuthorizationException changed to KsqlTopicAuthorizationException. KsqlAuthorizationException too ambiguous since it could apply to both SchemaRegistry auth failures and also Kafka auth failures.
Verify error messages still same

refactor: change KsqlAuthorizationException to KsqlTopicAuthorizationException

---

ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/avro/ValueSpecAvroSerdeSupplier.java
ksql-functional-tests/src/test/resources/test-runner/correct/multi_join/input.json
ksql-functional-tests/src/test/resources/test-runner/correct/multi_join/output.json
ksql-functional-tests/src/test/resources/test-runner/correct/multi_join/statements.sql

Testing tool Avro serde can now handle ValueSpec object even when the higher level object is passed. Also added one more test for multiple joins.

fix: fix a bug in testing tool serde

---

ksql-execution/src/main/java/io/confluent/ksql/execution/plan/DefaultExecutionStepProperties.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamAggregate.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamFilter.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamGroupBy.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamMapValues.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSink.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/TableFilter.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/TableMapValues.java

JDK 12 removes nashorn - I'm pretty sure the intention was to use errorprone annotation.

fix: replace nashorn @Immutable with errorprone for JDK12 (MINOR)

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/Errors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ErrorResponseUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java

Some AuthorizationExceptions can be wrapped with another exception so created a util that would check root cause of thrown exceptions to ensure the correct response is returned.
Current sample 500 response:
```
{
"@type": "statement_error",
"error_code": 50000,
"message": "Failed to Create Kafka topic: [new_topic]\nCaused by: Not authorized to access topic: [new_topic]",
"stackTrace": [],
"statementText": "CREATE STREAM Test_Topic(age BIGINT) WITH (KAFKA_TOPIC='new_topic', PARTITIONS=1, VALUE_FORMAT='DELIMITED');",
"entities": []
}
```
Updated 403 response:
```
{
"@type": "generic_error",
"error_code": 40301,
"message": "Authorization denied to Create on topic(s): [new_topic]",
"stackTrace": []
}
```
Unit tests
Local Ksql server testing using Postman
```
//Initialization
CREATE STREAM …
```

refactor: errorCode 40301 returned when KsqlTopicAuthorizationException/TopicAuthorizationException thrown

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/DropConnectorTableBuilder.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-engine/src/main/java/io/confluent/ksql/services/ConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxConnectClient.java
ksql-engine/src/test/java/io/confluent/ksql/connect/ConnectConfigServiceTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientTest.java
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropConnector.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/DropConnectorEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DropConnectorExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DropConnectorExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListConnectorsExecutorTest.java

Pretty straightforward, `DROP CONNECTOR` will now delete a connector.
- Unit Tests
- Local Testing
```
ksql> CREATE SOURCE CONNECTOR `jdbc-connector2` WITH("connector.class"='io.confluent.connect.jdbc.JdbcSourceConnector',"connection.url"='jdbc:postgresql://localhost:5432/almog.gavra',"mode"='bulk',"topic.prefix"='jdbc2-', "key"='username');
Message
-----------------------------------
Created connector jdbc-connector2
-----------------------------------
ksql> DROP CONNECTOR "jdbc-connector2";
Message
-------------------------------------
Dropped connector "jdbc-connector2"
-------------------------------------
```

feat: add DROP CONNECTOR functionality

---

ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java
ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGenProducer.java
ksql-examples/src/test/java/io/confluent/ksql/datagen/DataGenFunctionalTest.java
ksql-examples/src/test/java/io/confluent/ksql/datagen/DataGenTest.java

Resurrecting some ancient enhancements to datagen so that we can use it
to generate load:
- Add a flag to disable printing each row
- Add a flag to control the number of threads producing data
- Add a flag to control the total message rate (msgs/second) across all the
threads. The rate limiting is implemented using a token bucket.

feat: enhance datagen for use as a load generator

---

config/connect.properties
config/ksql-server.properties
config/log4j-rolling.properties
config/log4j.properties
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/ConnectExecutable.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/MultiExecutable.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/MultiExecutableTest.java

Enables KSQL to start a Connect distributed worker embedded in the KSQL server. The configuration is specified in `ksql.connect.worker.config`, which behaves identically to a normal connect worker.
Local testing and some minor unit test coverage

feat: spin up a connect worker embedded inside the KSQL JVM

---

ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedKafkaTopicClient.java
ksql-engine/src/test/java/io/confluent/ksql/services/FakeKafkaTopicClient.java
ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/SandboxedKafkaTopicClientTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockKafkaTopicClient.java

This PR adds a validation option to the sandboxed topic client to ensure a user have permissions to create a topic before creating the topic in the sandbox. 
This allows the `RequestValidator` to validate CSAS requests when the user does not have permissions to create the sink topic.
- Added unit tests
- Verified manually with debugging that RequestValidator fails if user does not have permissions on the delegated kafka topic client.

feat: validate createTopic permissions on SandboxedKafkaTopicClient

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/ServiceInfo.java
ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksql-engine/src/main/java/io/confluent/ksql/internal/QueryStateListener.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTestUtilTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/integration/TestKsqlContext.java
ksql-engine/src/test/java/io/confluent/ksql/internal/QueryStateListenerTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestAppTest.java

Previously starting a second instance of KSQL in a test would result in a clash on the metrics name. This is now avoided by providing a unique metrics group name prefix per test instance.
The default naming remains the same.
This is needed to allow future tests to run multiple instances, e.g. to test routing between instances for point queries work.
Suitable tests added.
`mvn test`

test: allow concurrent instances of KSQL to run in tests

---

ksql-engine/src/main/java/io/confluent/ksql/engine/AuthorizationTopicAccessValidator.java
ksql-engine/src/test/java/io/confluent/ksql/engine/AuthorizationTopicAccessValidatorTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java

`print <topic>` returns a 200 response with a not too specific error message when trying to print a topic the user doesn't have Read permissions for. Updated to return 403 response, 40301 error code, and a more specific error message.
Old response
`Not authorized to access topics: [qwerqwerqwerqwerqtly]`
New response
```
{
"@type": "generic_error",
"error_code": 40301,
"message": "Authorization denied to Read on topic(s): [qwerqwerqwerqwerqtly]",
"stackTrace": []
}
```
Unit test
Local testing

feat: improved error message and updated error code for PrintTopics command

---

ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksql-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java

Fixes the INSERT VALUES authorization error message. It will now print something like this:
```
ksql> insert into t1(id) values (1);
Authorization denied to Write on topic(s): [t1]
```
- Added unit tests
- Verified manually from CLI

fix: fix auth error message with insert values command

---

ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java

Remove dead code that looks to be left over from when `ServerState` was added.  Previously, this flag was used to detect cluster termination, which I'm assuming is now handled by `ServerState`.
@rodesai / @hjafarpour  - would be good for you if you could confirm cluster termination functionality was not compromised when this code became dead.

refactor: remove dead code (MINOR)

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/Errors.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java

When the command fails due to TopicAuthorizationException for InsertInto, a KsqlAuthorizationException is wrapped with a KsqlException
```
ksql> INSERT INTO TESTSTREAM (ROWTIME, ROWKEY, age) VALUES ( 1234, 'KEY', 4);
Failed to insert values into stream/table: TESTSTREAM
```
This is missing a `Caused by:` second line in the error message. This was due to the function
accessDeniedFromKafka only using the message of the top level exception passed into it instead of the entire exception. Updated the function to match the badRequest function (`Caused by:` will now show up)
```
ksql> INSERT INTO TESTSTREAM (ROWTIME, ROWKEY, age) VALUES ( 1234, 'KEY', 4);
Failed to insert values into stream/table: TESTSTREAM
Caused by: Authorization denied to Write on topic(s): [qwerqwerqwerqwerqtly]
```
unit …

fix: fixed how wrapped KsqlTopicAuthorizationException error messages are displayed

---

ksql-test-util/pom.xml
ksql-test-util/src/main/java/io/confluent/ksql/test/util/ZooKeeperEmbedded.java
ksql-test-util/src/test/java/io/confluent/ksql/test/util/ZooKeeperEmbeddedTest.java

This change disables the Zookeeper Admin Server that would otherwise be started by `ZookeeperEmbedded`.
The admin server defaults to using port 8080, which causes a port clash if two tests/instances are running on the same machine.
On a port clash the admin server fails to start, which causes Zookeeper to fail too.

test: disable ZK admin server

---

ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java

`LogicalPlanner` was still using the Connect `SchemaBuilder` to build `LogicalSchema`s. We now have a builder for `LogicalSchema`. This PR switches `LogicalPlanner` over to use this builder.
To facilitate this I've enhanced `ExpressionTypeManager` to be able to work in both legacy Connect `Schema`s and the new KSQL `SqlType`.  Once ever use is switched over from Connect we can remove the old `Schema` method.
`mvn test`

refactor: remove the use of Connect schema from LogicalPlanner

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java

The change means the AggregateNode only builds the aggregate functions once.
Before it would build them first to get the return type needed to build the schema, then again to pass to the `aggregate` function.
This change reverses the order of these two steps, so now the schema can be built using the same aggregate function instances that will be later passed to `aggregate`.
`mvn test`

refactor: build aggregate functions only once

---

ksql-common/src/main/java/io/confluent/ksql/function/KsqlAggregateFunction.java
ksql-engine/src/main/java/io/confluent/ksql/function/BaseAggregateFunction.java
ksql-engine/src/test/java/io/confluent/ksql/function/BaseAggregateFunctionTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/InternalFunctionRegistryTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfCompilerTest.java

To aid migration away from Connect's Schema type `KsqlAggregateFunction` now exposes its return type as it's `SqlType`, as well as the existing `Schema`.
The latter can be removed once all usage has been flipped to the new method.
`mvn test`

refactor: expose KsqlAggregateFunction return type as SqlType

---

ksql-engine/src/main/java/io/confluent/ksql/function/udaf/KudafAggregator.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/KudafUndoAggregator.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedTable.java
ksql-engine/src/test/java/io/confluent/ksql/function/KudafUndoAggregatorTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/group-by.json

`KsqlAggregator`, and its sister `KsqlUndoAggregator` are passed a `aggValToValColumnMap` which always has values that match their keys and where the keys start at zero and are monotonically increasing, e.g. {0->0, 1->1}.   This is pretty pointless and makes the code harder to read - hence this change removes this complexity.
`mvn test`

refactor: remove the pointless valToVal map passed to KsqlAggregator

---

ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java

Find bugs issue to do with incorrect number of arguments to String.format.
Of course, we all know you shouldn't use String.format in log lines anyway ;)
`mvn test`

fix: find bugs issue in KafkaTopicClientImpl

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java

The `internalNameToIndexMap` map in `AggregateNode`'s `InternalSchema` class only ever contains mappings such as `{"KSQL_INTERNAL_COL_0" -> 0, "KSQL_INTERNAL_COL_1" -> 1}`.  This adds complexity to the code therefore makes it harder to understand what is going on.  This change removes this mapping and instead gets the index from the number at the end of the column name.
`mvn test`

refactor: remove pointless internal column name to index map

---

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropTypeCommand.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/DropTypeCommandTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/DropType.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandIdAssigner.java

Drops a previously registered type. This does not affect any previously issued commands or custom types (e.g. if I have `CREATE TYPE B AS STRUCT<A>` and `A` is `STRING`, dropping `A` will not affect `B`, which remains `STRUCT<STRING>`)
- Unit testing
- E2E Manual Testing (after merging #3280)
```
ksql> CREATE TYPE ADDRESS AS STRUCT<number INTEGER, street VARCHAR, city VARCHAR>;
Message
-------------------------------------------------------------------------------------------------
Registered alias ADDRESS with SQL type STRUCT<`NUMBER` INTEGER, `STREET` STRING, `CITY` STRING>
-------------------------------------------------------------------------------------------------
ksql> SHOW TYPES;
Type Name | Schema
---------------------------------------------------------------------------------- …
```

feat: add ability to DROP custom types

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/SchemaConverters.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/types/SqlStruct.java
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/types/SqlStructTest.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java
ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SelectValueMapper.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SelectValueMapperFactory.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SelectValueMapperFactoryTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SelectValueMapperTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionMetadataTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionTypeManagerTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

In the current code the code for baking the select expressions into java code is in the `Selection` class that is nested inside `SchemaKStream`.   The baked `ExpressionMetadata` is then used to build a `SelectValueMapper`.
However, I'll soon need to build the `SelectValueMapper` as part of the work for static queries. Hence I'm pulling out the baking code into a new `SelectValueMapperFactory` class, which can be called from both places.
New tests added.
`mvn test`

refactor: Bake select mapper (minor)

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/SchemaConverters.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/SchemaConvertersTest.java

The Java to Sql schema converter should handle converting `HashMap` -> `MAP` and `ArrayList` -> `ARRAY` etc, not just the interface types themselves.
`mvn test`

fix: schema converters should handle List and Map impl (MINOR)

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/Field.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/FieldTest.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/ExpressionFormatterUtil.java
ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/util/IdentifierUtil.java
ksql-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksql-parser/src/test/java/io/confluent/ksql/parser/util/ParserUtilTest.java
ksql-parser/src/test/java/io/confluent/ksql/util/IdentifierUtilTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeFunctionExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogServerUtils.java

As part of the work around quoted identifiers, we need to be able to properly escape not just reserved words - but anything that doesn't parse as a proper identifier. I accomplished this by using the `identifier` rule to parse an identifier instead of trying to hack our own rules by creating the set of reserved words. 
The new code is all in `IdentifierUtil` and I removed the old code in `ParserUtil`.
- unit testing
- end to end tests after my implementation of quoted identifiers prototype

fix: improve escaping of identifiers

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java

Prints the error message alongside the connector if there is one.
- Unit testing

feat: include error message in DESCRIBE CONNECTOR (MINOR)

---

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java

removing unused methods - I'm trying to clean up usage around aliased fields
ran `SchemaUtilTest`

chore: remove unused methods in SchemaUtil (MINOR)

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/TypeListTableBuilder.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ListTypes.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/TypeList.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListTypesExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/EntityUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListTypesExecutorTest.java

Pretty straightforward. Allows users to list all of their custom types. Note that nested custom types will show up resolved.
- Unit Testing
- E2E local testing
```
ksql> CREATE TYPE PERSON AS STRUCT<name VARCHAR, address ADDRESS>;
Message
--------------------------------------------------------------------------------------------------------------------------------------------------
Registered custom type with name 'PERSON' and SQL type STRUCT<`NAME` STRING, `ADDRESS` STRUCT<`NUMBER` INTEGER, `STREET` STRING, `CITY` STRING>>
--------------------------------------------------------------------------------------------------------------------------------------------------
ksql> SHOW TYPES;
Type Name | Schema
------------------------------------------------------------------------------------- …
```

feat: add SHOW TYPES to list all custom types

---

ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

`SimpleAclAuthorizer` has been deprecated under KIP-504 (https://github.com/apache/kafka/commit/364794866f82d2d99f7a610d699478d5055688f0). To avoid build breaks when this commit is merged into Confluent Kafka, this PR suppresses deprecation warnings for SimpleAclAuthorizer. Since the replacement authorizer API is likely to change, it will be better to update the code to use the new AclAuthorizer later on.
Verified that build succeeds with the changes.

MINOR: Suppress deprecation warning for SimpleAclAuthorizer

---

ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java
ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGenProducer.java

BREAKING CHANGE: If no value is passed for the KSQL datagen option `iterations`, datagen will now produce indefinitely, rather than terminating after a default of 1,000,000 rows.
This change is valuable because previously there was no way to specify that datagen should produce indefinitely. This PR adds this ability, and updates it to be the default behavior. (Users can still use the old behavior of terminating the process after a fixed number of rows by passing that number via `iterations`.)
Manual.

feat: add option for datagen to produce indefinitely (MINOR)

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/DataException.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/Field.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/FieldName.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/types/SqlArray.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/types/SqlDecimal.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/types/SqlMap.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/types/SqlPrimitiveType.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/types/SqlStruct.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/types/SqlType.java
ksql-common/src/main/java/io/confluent/ksql/types/KsqlStruct.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/FieldNameTest.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/FieldTest.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/types/SqlArrayTest.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/types/SqlDecimalTest.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/types/SqlMapTest.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/types/SqlPrimitiveTypeTest.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/types/SqlStructTest.java
ksql-common/src/test/java/io/confluent/ksql/types/KsqlStructTest.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java

This PR introduces the start of our own internal replacement for Connect's `Struct` class. Introducing... `KsqlStruct.
To facilitate this I've pulled `FieldName` out of `Field` and I've added a `validateValue` function to each `SqlType` to do deep validation that a value matches a schema.
Suitable tests added.
`mvn test`

refactor: start of our own internal Struct class

---

config/ksql-server.properties
docs/installation/install-ksql-with-docker.rst
docs/installation/installing.rst
docs/installation/server-config/config-reference.rst
docs/operations.rst
docs/troubleshoot-ksql.rst
docs/tutorials/docker-compose.yml

Fixes #3309 by adding the IP6 equiv of `http://0.0.0.0:8088` - the server will no listen on all IP6 interfaces too.
Manual testing - can run server with just the IP6 listener and still connect using default CLI server of `http://localhost:8088`

fix: ensure default server config works with IP6 (fixes #3309)

---

config/ksql-server.properties
docs/installation/installing.rst
docs/installation/server-config/config-reference.rst
docs/tutorials/docker-compose.yml

Follow up to: https://github.com/confluentinc/ksql/pull/3310
`listeners=http://0.0.0.0:8088,http://[::]:8088` change in the previous PR will cause the server initialization to fail with:
```
...
[2019-09-09 12:49:35,916] INFO Starting server (io.confluent.ksql.rest.server.KsqlServerMain:75)
[2019-09-09 12:49:36,043] INFO Adding listener: http://0.0.0.0:8088 (io.confluent.rest.Application:241)
[2019-09-09 12:49:36,061] INFO Adding listener: http://[::]:8088 (io.confluent.rest.Application:241)
[2019-09-09 12:49:36,230] INFO jetty-9.4.18.v20190429; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 1.8.0_202-ea-b03 (org.eclipse.jetty.server.Server:370)
[2019-09-09 12:49:36,265] INFO DefaultSessionIdManager workerName=node0 …
```

fix: revert default listeners value and update docs

---

ksql-common/src/main/java/io/confluent/ksql/json/JsonMapper.java
ksql-common/src/main/java/io/confluent/ksql/json/KsqlTypesSerializationModule.java
ksql-common/src/main/java/io/confluent/ksql/json/LogicalSchemaSerializer.java
ksql-common/src/test/java/io/confluent/ksql/json/LogicalSchemaSerializerTest.java
ksql-rest-client/pom.xml
ksql-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksql-rest-client/src/main/java/io/confluent/ksql/rest/client/json/KsqlTypesDeserializationModule.java
ksql-rest-client/src/main/java/io/confluent/ksql/rest/client/json/LogicalSchemaDeserializer.java
ksql-rest-client/src/test/java/io/confluent/ksql/rest/client/json/LogicalSchemaDeserializerTest.java

Our `LogicalSchema` type already has a `toString` that outputs the SQL schema, e.g. `[id INTEGER, name STRING]`.
This PR adds custom Jackson models with custom serializers and deserializers to handle marshalling the `LogicalSchema` via JSON.
(This will be needed soon for static queries, which will share their schema).
`mvn test`

feat(static): add custom jackson JSON serde for handling LogicalSchema

---

ksql-common/src/main/java/io/confluent/ksql/types/KsqlStruct.java
ksql-common/src/test/java/io/confluent/ksql/types/KsqlStructTest.java

Iterating across the values and their schemas is a common pattern, so lets add a method to facilitate.
Usual

feat(static): add forEach() to KsqlStruct (MINOR)

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/types/SqlStruct.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/types/SqlStructTest.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfCompiler.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/SourceNode.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/KeyFieldDeserializer.java
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/parser/SchemaParser.java
ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/SqlTypeParser.java
ksql-parser/src/test/java/io/confluent/ksql/schema/ksql/SqlTypeParserTest.java

The main purpose of this PR is to ensure we can parse an empty `STRUCT`, i.e. one without any fields.  This is a valid edge case as we have the potential for either the key or value part of a schema to not have any fields, and such parts are represented as STRUCT.
So, for example, when we're responding to a static query request we include the schemas of the key and value in the response. Such schemas may have no fields.  Our parser should be able to handle this.
So....
1. I've updated the syntax to allow a `STRUCT` with out fields `STRUCT< >`
1. I've updated `SqlStruct`'s `toString` to include a space between the `<` and `>`, as otherwise the lexer interprets `<>` as `NEQ`.
1. I've added suitable tests.
Also, while in there I've renamed `TypeContextUtil` to `SqlTypeParser`, as that's what …

fix: should be able to parse empty STRUCT schema (MINOR)

---

ksql-engine/src/test/java/io/confluent/ksql/integration/Retry.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java

We've had `RestQueryTranslationTest` fail a few times due to:
```
**Caused by: org.apache.kafka.common.errors.TopicExistsException: Topic 'test_topic' already exists.**
```
According to @big-andy-coates:
> There's a race condition inherent in Kafka when deleting topics.
When you delete a topic it is delete async. Once the delete has been requested the topic info is no longer available.  So no way of knowing when it's been deleted.  Any attempt to recreate causes a 'topic exists' exception.
This PR simply puts a band-aid around that by retrying if there's a `TopicExistsException`.
- Ran the test successfully locally and saw the log line: 
```
[2019-09-11 10:46:29,830] WARN Retrying test after 5 SECONDS due to: Failed to create topic:test_topic (io.confluent.ksql.integration.Retry:135)
```

fix: band-aid around RestQueryTranslationTest

---

ksql-test-util/src/test/java/io/confluent/ksql/test/util/ZooKeeperEmbeddedTest.java

To fix build failure: https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/ksql/job/PR-3326/1/testReport/junit/io.confluent.ksql.test.util/ZooKeeperEmbeddedTest/shouldSupportMultipleInstancesRunning/
This now matches the timeout we use in our EmbeddedKafka.

test: increase session timeout on ZK test

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopic.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/QueuedCommand.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/utils/TestUtils.java

Breaking down the PR at https://github.com/confluentinc/ksql/pull/3330 into smaller pieces, this one focuses on the simpler task of adding new offset values  and flags to the command objects. Validation will be done at a later date after more offline discussion. This PR is a precursor to updating the query id generating code for interactive mode.
The flag in Command is to indicate whether or not a command should use the old query id generation or use the new offset based query id. This is needed to ensure that if a server is relying on a command topic with old commands, the old commands will still follow the same pattern for query id generation and query ids are maintained if the server needs to restore.
The field in QueuedCommand represents the offset that the command was read from, it's …

feat: add offset to QueuedCommand and flag to Command

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/PrintTopicValidatorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/QueryValidatorTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/Errors.java

If someone issues a `PRINT` or `SELECT` statement to the normal HTTP `/ksql` endpoint it returns an error. The previous error talked about `RUN SCRIPT`, which is misleading. We don't even have `RUN SCRIPT` anymore.
> RUN SCRIPT cannot be used with the following statements: 
>      * PRINT
>      * SELECT
New error message just tells users to target such statements to the websocket endpoint `/query`
> The following statement types should be issued to the websocket endpoint '/query':
>          * PRINT
>          * SELECT
`mvn test`

fix: improve error message on query or print statement on /ksql (MINOR)

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/SqlBaseType.java
ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksql-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/KsqlTestingToolTest.java
ksql-parser/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java

Fixes https://github.com/confluentinc/ksql/issues/3348
* Fixes NPE when trying to INSERT integer into String field
* Improves error message when such an insert fails. New error message is:
```
ksql> CREATE STREAM S2 (ID string) WITH (kafka_topic='test_topic', value_format='JSON');
Message
Stream created
ksql> insert into s2(id) values (1);
Failed to insert values into stream/table: S2. Expected type STRING for field ID but got INTEGER(1)
ksql>
```
* Simplified / refactored DefaultSqlValueCoercerTest and make sure all combinations are covered
Improved and completed DefaultSqlValueCoercerTest

Fix: NPE when coercing on INSERT + improve err msg + better coercion test coverage

---

ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java

To work around the inherent race condition between state stores warming up and static query requests the test executor has a retry look on static queries to give KS time to process messages.
Previously, this retry look was only around the first static query.  However, it's possible that the KS has processed enough input to meet the expected output of the first static query, but not the second.  Hence, to stabilise this test the executor must retry each static query in turn, thereby ensuring KS has time to process the input required to meet each static query's expected response.
Ran tests many 100's of times locally.

test: stabilise RQTT (MINOR)

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-functional-tests/README.md
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/PostConditionsNode.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/KafkaStreamsInternalTopicsAccessor.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/conditions/PostConditions.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksql-functional-tests/src/test/resources/query-validation-tests/key-field.json
ksql-functional-tests/src/test/resources/query-validation-tests/partition-by.json

Note: this PR is based of the [QTT blacklist PR](https://github.com/confluentinc/ksql/pull/3365) - review that first. 
While investigating recent RQTT build failures I noticed that the queries that involved a `GROUP BY ROWKEY` were going through a repartition topic - which is unnecessary and costly.
This PR fixes the issue and adds a new compatibility breaking config to ensure old queries continue to maintain the repartition step to avoid data loss.
Tests added.

Avoid unnecessary repartition of stream on `GROUP BY ROWKEY`

---

ksql-functional-tests/README.md
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/PostConditionsNode.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/KafkaStreamsInternalTopicsAccessor.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/conditions/PostConditions.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/partition-by.json

Extended QTT to allow test cases to supply a regex pattern of topic names that should NOT be created.
I've added this as I think we have a bug where `GROUP BY ROWKEY` is doing a repartition.  I know I had this working correctly previously, but without an explicit statement in the test to ensure the repartition topic is NOT created, it's possible to have such repartitions reintroduced.
`mvn test`.

Qtt topic blacklist

---

ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json

Fixes #3347 
- When inserting into a TABLE with a key, and specifying the key field but not the rowkey, we ensure that the rowkey is set to the string form of the key
- When inserting into a TABLE with a key and specifying both the rowkey and the key, we check that the rowkey matches the string form of the key
Added several new RQTT tests to test various combinations of inserting with rowkey and key for different types.

Fix: Consistency between inserted rowkey and key values when inserting into a table with a key

---

ksql-engine/src/main/java/io/confluent/ksql/structured/GroupByMapper.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/test/java/io/confluent/ksql/structured/GroupByMapperTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSelectKey.java
ksql-execution/src/main/java/io/confluent/ksql/execution/util/StructKeyUtil.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamSelectKeyBuilder.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamSelectKeyBuilderTest.java

Moves rekeying from SchemaKStream and into an execution plan builder.
Added tests for step builder

feat: move selectKey impl to plan builder

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/StaticQueryFunctionalTest.java

Seeing occasional test failures:
```
java.lang.AssertionError:
Failed to terminate queries. lastError:Unknown queryId: CTAS_ID_18_0
at io.confluent.ksql.rest.integration.StaticQueryFunctionalTest.cleanUp(StaticQueryFunctionalTest.java:136)
```
This was because the test tries to stop all queries and drop all source ON BOTH instances.  But they're communicating through the command topic, so its only needed on one!
`mvn test`.

test: harden the StaticQueryFunctionalTest (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/streams/StreamsFactories.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlBareOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/streams/GroupedFactoryTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/ExecutionStep.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamGroupBy.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamGroupByKey.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/GroupByMapper.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/GroupedFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamGroupByBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/TableGroupByBuilder.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/GroupByMapperTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamGroupByBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/TableGroupByBuilderTest.java

This patch moves the code for regrouping streams/tables into plan
builders. This also required adding a new execution step for
groupByKey, which we missed the first go-round.
Adds tests for the new grouped step builders.

feat: move groupBy into plan builders

---

ksql-engine/src/main/java/io/confluent/ksql/services/KafkaClusterUtil.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/filters/KsqlAuthorizationFilter.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ServerMetadataResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/filters/KsqlAuthorizationFilterTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/ServerMetadataResourceTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/ServerClusterId.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/ServerMetadata.java
ksql-rest-model/src/test/java/io/confluent/ksql/rest/entity/ServerClusterIdTest.java
ksql-rest-model/src/test/java/io/confluent/ksql/rest/entity/ServerMetadataTest.java

This new path (`/metadata`) will replace the `/info` path in the next KSQL major release. It is added to have a standard API between Confluent components that show information about the current cluster.
For now, this path displays the following:
```
/metadata
{
"version": "5.4.0-SNAPSHOT",
"clusterId": {
"id": "",
"scope": {
"kafka-cluster": "H6tCQq0zSWan9_L-TZHa9A",
"ksql-cluster": "default_"
}
}
}
/metadata/id
{
"id": "",
"scope": {
"kafka-cluster": "H6tCQq0zSWan9_L-TZHa9A",
"ksql-cluster": "default_"
}
}
```
Follow-up PRs:
- Call `/metadata` instead of `/info` from the KSQL CLI
- Add documentation about the new path
- Remove the `/info` path in KSQL 6.x (pending Issue)
- Added unit tests
- Manual verification

feat: add REST /metadata path to display KSQL server information (replaces /info)

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/DataSourceNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSink.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/TableSink.java
ksql-execution/src/main/java/io/confluent/ksql/execution/util/SinkSchemaUtil.java
ksql-execution/src/test/java/io/confluent/ksql/execution/util/SinkSchemaUtilTest.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/KeySerdeFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamSinkBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/TableSinkBuilder.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamSinkBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/TableSinkBuilderTest.java

This patch moves stream and table sinks (SchemaKX.into) into execution
plan builders. This change also moves computation of the rowkey/rowtime
indexes to be excluded from the output into the plan builder.
Added unit tests for step builders.

feat: move setup of the sink to plan builders

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/main/java/io/confluent/ksql/streams/StreamsFactories.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/streams/JoinedFactoryTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamStreamJoin.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamTableJoin.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/TableTableJoin.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/JoinedFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/KsqlValueJoiner.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamStreamJoinBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamTableJoinBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/TableTableJoinBuilder.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/KsqlValueJoinerTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamStreamJoinBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamTableJoinBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/TableTableJoinBuilderTest.java

Moves code for joining kstreams/ktables out of SchemaKStream/Table
and into execution plan builders. Also moves KsqlValueJoiner into
ksql-streams, so that it can be used from the plan builders. Also
adds a buildKeySerde API for building both windowed and unwindowed
keys, since most of the plan builders dont have type information
for the key.
Added unit tests for step builders

feat: move joins to plan builder

---

ksql-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java
ksql-test-util/src/test/java/io/confluent/ksql/test/util/ZooKeeperEmbeddedTest.java

Build failures such as:
https://jenkins.confluent.io/job/Confluentinc%20Contributors/job/ksql/job/PR-3379/7/testReport/junit/io.confluent.ksql.test.util/ZooKeeperEmbeddedTest/shouldSupportMultipleInstancesRunning/
Where caused by too short a timeout on the latch in the test.  Test running in Jenkins failed in this case because it tool 12 seconds for ZK to create its log !!! 
Aligned the tests timeouts with `KafkaEmbedded` and increased the connection timeout in that to help stabilize Kafka based tests on Jenkins, (which still sometimes wig out due to ZK issues)

test: align ZK test's timeouts with what we use in our `KafkaEmbedded`

---

ksql-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksql-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriteForStruct.java
ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java
ksql-parser/src/test/java/io/confluent/ksql/parser/rewrite/StatementRewriteForStructTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/rewrite/StatementRewriterTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ExplainExecutorTest.java

Fixes: #3356
KSQL uses a statement rewritter to convert STRUCT field dereferences into `FETCH_FIELD_FROM_STRUCT` function calls.  The rewrite is done for `Query`, `C*AS` and `INSERT INTO` statements, but was missing `EXPLAIN`.
It is valid to execute `EXPLAIN` on a query string, e.g.  `EXPLAIN SELECT address->street FROM Y;`.  It is therefore important that the query within the `EXPLAIN` statement has the same rewrites applied to it as would be applied should the statement be executed directly.
Suitable unit tests added.

fix(3356): struct rewritter missed EXPLAIN

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/QueryAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/StaticQueryValidator.java
ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/ProjectNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedTable.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/StaticQueryValidatorTest.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/ProjectNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java

Quick refactor of parts of `Analysis` class to improve code quality:
- Switch the class from using `null`s to explicit `Optional`s.
- Switch from having two collections for selects and their aliases, to a single that holds both. (less to pass around, no way they can be of different sizes, etc).
Take a look at `Analysis` to see the changes to this class. This is the core of the change. Everything else is just changes to take into account the changes to this class.
non-functional change for the most part

refactor: harden Analysis class

---

ksql-common/src/main/java/io/confluent/ksql/name/Name.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/FormatOptions.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/SourceSchemas.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerFunctionalTest.java
ksql-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java

We don't ever actually need to compare ignoring case because `ParserUtil` will parse anything unquoted into upper case.
This patch also includes some very minor refactors and javadoc improvements.

feat: remove equalsIgnoreCase from all Name classes (MINOR)

---

ksql-engine/src/test/java/io/confluent/ksql/function/KudafUndoAggregatorTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/UdafUtil.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udaf/KudafAggregator.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udaf/KudafInitializer.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udaf/KudafUndoAggregator.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udaf/window/WindowSelectMapper.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/AggregateParams.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/AggregateParamsTest.java

Extend the recent internal refactor of `KudafAggregator` (to use a list of functions, rather than a map), out to the place its built from.
usual

refactor: switch `KudafAggregator` to take List of functions

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java

Issuing a static query with `WINDOWSTART` bounds of the form `WHERE a < WINDOWSTART AND WINDOWSTART < b` returns in the error:
```
Server failed to execute statement
statement: 
reason: Unsupported WINDOWSTART bounds: [GREATER_THAN]
Static queries currently require a WHERE clause that:
- limits the query to a single ROWKEY, e.g. `SELECT * FROM X WHERE ROWKEY=Y;`.
- limits the time bounds of the windowed table. This can be: 
+ a single window lower bound, e.g. `WHERE WINDOWSTART = z`, or
+ a range, e.g. `WHERE a < WINDOWSTART AND WINDOWSTART < b
WINDOWSTART currently supports operators: [EQUAL, GREATER_THAN_OR_EQUAL, LESS_THAN]
WINDOWSTART currently comparison with epoch milliseconds or a datetime string in the form: yyyy-MM-dd'T'HH:mm:ss.SSS
```
This PR updates the error message to show …

fix: typo in static query WHERE clause example

---

ksql-common/src/test/java/io/confluent/ksql/json/LogicalSchemaSerializerTest.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/TableElements.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/TableElementsTest.java
ksql-rest-client/src/main/java/io/confluent/ksql/rest/client/json/LogicalSchemaDeserializer.java
ksql-rest-client/src/test/java/io/confluent/ksql/rest/client/json/LogicalSchemaDeserializerTest.java
ksql-rest-client/src/test/java/io/confluent/ksql/rest/entity/TableRowsEntityTest.java

Following on from #3422, which saw `LogicalSchema` enhanced to support arbitrary key & value column orders...
A query might contain key and value columns in any order. Hence the `TableElements` class has been changed to:
- not fail if key columns come after value columns
- not change the order of columns
When serializing a logical schema across the wire, (which is currently only used for static queries), we should't yet serialize the ROWTIME meta column. This is mainly because static queries don't support it, and our syntax doesn't support meta columns, i.e. you can't have a `CREATE TABLE X (ROWTIME BIGINT META, ...`. So if we did include it in the serialized form, we wouldn't be able to parse it.
usual

feat(static): unordered table elements and meta columns serialization

---

.gitignore

This PR adds '/ksql-functional-tests/src/test/resources/**/scratch.json' to .gitignore so you can maintain a local QTT query file for playing around that won't be added to git.
Manually tested it worked.

feat: Ignore local scratch QTT file called scratch.json from git

---

ksql-common/src/main/java/io/confluent/ksql/properties/with/CommonCreateConfigs.java
ksql-common/src/main/java/io/confluent/ksql/serde/Delimiter.java
ksql-common/src/test/java/io/confluent/ksql/serde/FormatInfoTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceAsProperties.java
ksql-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceProperties.java
ksql-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerdeFactory.java
ksql-serde/src/test/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerdeFactoryTest.java

This PR renames Delimiter.of(String) to Delimiter.parse(String)
Run test suite

fix: rename Delimiter.of(String) to Delimiter.parse(String)

---

docs/installation/server-config/config-reference.rst

Docs now call out that the deprecated sink properties `ksql.sink.partitions` and `ksql.sink.replicas` affect not only `CREATE STREAM AS SELECT` and `CREATE TABLE AS SELECT` commands, but also `CREATE STREAM` and `CREATE TABLE` commands that create topics.

docs: deprecated sink properties affect CREATE STREAM/TABLE commands

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/StaticQueryValidator.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/StaticQueryValidatorTest.java
ksql-functional-tests/src/test/resources/rest-query-validation-tests/materialized-aggregate-static-queries.json

At the moment static queries do not support returning ROWTIME as this information is not available in the response for KS IQ. So this PR explicitly handles cases where ROWTIME appears in the projects and gives a better error message than just `unknown column`.
In the future, we _may_ choose to support this by always including ROWTIME in the value of the changelog topic, but this is out of scope for this initial MVP.
Suitable tests added.

feat(static): fail on ROWTIME in projection

---

ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/avro/AvroSerdeSupplier.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/avro/ValueSpecAvroSerdeSupplier.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStream.java
ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroSerializerTest.java

https://github.com/confluentinc/ksql/pull/3372 was merged in order to unblock our build due to an upstream change in SR https://github.com/confluentinc/schema-registry/commit/c4b487923e0193db5083b17f2744838edd8b24e1
That SR change has been reverted in https://github.com/confluentinc/schema-registry/commit/ca4f640542316f0bf915ac3ada65ea508147a7e0
so we need to undo the previous fix in order for the build to work.

fix: address upstream change in KafkaAvroDeserializer (revert previous fix)

---

ksql-common/src/main/java/io/confluent/ksql/util/timestamp/PartialStringToTimestampParser.java
ksql-common/src/test/java/io/confluent/ksql/util/timestamp/PartialStringToTimestampParserTest.java
ksql-engine/src/main/java/io/confluent/ksql/engine/rewrite/StatementRewriteForRowtime.java
ksql-engine/src/test/java/io/confluent/ksql/engine/rewrite/StatementRewriteForRowtimeTest.java
ksql-functional-tests/src/test/resources/rest-query-validation-tests/materialized-aggregate-static-queries.json
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java

With the change you no longer need to supply the full datetime when adding bounds on `WindowStart`.  You can drop precision on the right as much as you like, all the way until you have only a year. For example,
```sql
SELECT * FROM AGGREGATE WHERE '2020-02-23T23:45' <= WindowStart AND WindowStart < '2020-02-23T24' AND ROWKEY='10';
```
Numeric timezones are now also supported
```sql
SELECT * FROM AGGREGATE WHERE ROWKEY='10' AND WindowStart='2020-02-23T22:45:12.000-0100';
```
cc @derekjn ,  @MichaelDrogalis 
usual

feat(static): support for partial datetimes on `WindowStart` bounds

---

ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenUtil.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksql-execution/src/main/java/io/confluent/ksql/execution/sqlpredicate/SqlPredicate.java
ksql-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java

This patch ensures that all generated code uses valid Java identifiers instead of arbitrary column names by generating `varX` where `X` is the column index for the parameter being passed in. Note that the only "real" changes in this PR are in `SqlToJavaVisitor` and `CodeGenRunner` (both of which are single line changes).
As part of this change I also:
- `Column` also has an index
- `LogicalSchema.Builder` tracks Column Indices
- `LogicalSchema` uses the builder to do internal copies to maintain unique indices (when copying metadata/keys into value)

feat: use coherent naming scheme for generated java code

---

ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java

The fifth and final PR for [KIP-307](https://github.com/apache/kafka/pull/6413) is getting merged today.  This PR adds the following overload  `KGoupedTable.aggregate(Initializer, Aggregator, Aggregator, Named`).  
This causes an error with the `SchemaKGroupedTableTest` when executing `mockKGroupedTable.aggregate(any(), any(), any(), any()))` method.  The compiler can't disambiguate the 4th argument, as it's either a `Materialized` or a `Named` object.  This PR fixes the test.
Update this PR build is passing now and can be merged once approved. 
I updated the test and ran the entire KSQL test suite, all tests passed.

fix: fix test for KIP-307 final PR

---

ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/main/java/io/confluent/ksql/util/KafkaStreamsUncaughtExceptionHandler.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/KsqlUncaughtExceptionHandler.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java

Currently, there's no way to bring back a thread that dies due to exception. This PR adds a UncaughtExceptionHandler to the CommandRunner thread which will take down the server when the thread dies due to an unknown exception. the executorService was also changed to execute() because submit() doesn't call UncaughtExceptionHandler.
https://stackoverflow.com/questions/1838923/why-is-uncaughtexceptionhandler-not-called-by-executorservice
Example: if the CommandRunner thread encounters problems when polling the commandTopic, the exception returned isn't being handled currently and the thread will die. The server is then left in a state where it can't process any more commands now that the thread is dead. The only way to restore functionality is to just restart the entire server. 
This PR also …

feat: add KsqlUncaughtExceptionHandler and new KsqlRestConfig for enabling it

---

ksql-engine/src/main/java/io/confluent/ksql/materialization/ks/KsMaterializedWindowTable.java
ksql-engine/src/test/java/io/confluent/ksql/materialization/KsqlMaterializationTest.java
ksql-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializedSessionTableTest.java
ksql-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializedWindowTableTest.java
ksql-functional-tests/src/test/resources/rest-query-validation-tests/materialized-aggregate-static-queries.json
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java

This PR has two parts.
The first commit makes it possible to have WHERE clause bounding WINDOWSTART using the following comparison types:
- `>`
- `>=`
- `=`
- `<`
- `>=`
Some of which were already supported in certain situations, but are now all full supported.
The second commit removes the requirement to have a bound on WINDOWSTART at all for windowed tables. With no bounds, all windows are returned.
e.g.
```sql
-- get all windows for a key:
SELECT * FROM X WHERE ROWKEY=Y;
-- upper and lower bounds on window start exclusive:
SELECT * FROM X WHERE ROWKEY=Y AND '2019' < WINDOWSTART AND WINDOWSTART < '2020';
-- upper and lower bounds on window start inclusive:
SELECT * FROM X WHERE ROWKEY=Y AND '2019' <= WINDOWSTART AND WINDOWSTART <= '2020';
```
cc @derekjn ,  @MichaelDrogalis 
usual

feat(static): allow windowed queries without bounds on rowtime

---

ksql-engine/src/test/java/io/confluent/ksql/materialization/KsqlMaterializationTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksql-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java
ksql-functional-tests/src/test/resources/rest-query-validation-tests/materialized-aggregate-static-queries.json
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/TableRowsEntity.java

With this PR you can now have `ROWKEY` in the projection of a static query, e.g.
```sql
SELECT ROWKEY, ID FROM X WHERE ROWKEY=10;
```
This involves more hacking about in `StaticQueryExecutor`, which will be refactored into something more manageable.  Deadlines, deadlines!
cc @derekjn ,  @MichaelDrogalis 

feat(static): support ROWKEY in the projection of static queries

---

ksql-common/src/main/java/io/confluent/ksql/util/timestamp/PartialStringToTimestampParser.java
ksql-common/src/test/java/io/confluent/ksql/util/timestamp/PartialStringToTimestampParserTest.java

Improved error handling around invalid tz. Plus improved error message now mentioned optional tz.
usual

fix: better error message if tz invalid in datetime string

---

ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

Found another place in the test code where the ZK timeouts where set to defaults that are too low for the build servers
This should help with build failures such as this one: https://jenkins.confluent.io/job/confluentinc/job/ksql/job/master/3349/testReport/junit/io.confluent.ksql.materialization.ks/KsMaterializationFunctionalTest/shouldQueryMaterializedTableForAggregatedStream/

test: stabilize integration tests

---

ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java

There's a block of code in the RQTT that looks set up to wait for all relevant state stores to be warm but as implemented only waits for the first one. This PR updates the block to wait for all of them.
Motivated by the following flaky test failure (observed in Jenkins): This test ([link](https://github.com/confluentinc/ksql/blob/d83c7878494583d6000146e4cb82a81d67e5f1eb/ksql-functional-tests/src/test/resources/rest-query-validation-tests/materialized-aggregate-static-queries.json#L207)) failed with
```
Response mismatch at index 3 on key: rows
Expected: is <[[10, 12345, 13456, 2], [10, 24456, 24456, 1]]>
but: was <[[10, 12345, 13456, 2]]>
```
without waiting for this timeout ([link](https://github.com/confluentinc/ksql/blob/d83c7878494583d6000146e4cb82a81d67e5f1eb/ksql-functional-tests/src …

test: fix RQTT to wait for all state stores to be warm (MINOR)

---

ksql-engine/src/test/java/io/confluent/ksql/function/KudafUndoAggregatorTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udaf/KudafUndoAggregator.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udaf/window/WindowSelectMapper.java
ksql-execution/src/test/java/io/confluent/ksql/execution/function/udaf/window/WindowSelectMapperTest.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/AggregateParams.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/AggregateParamsTest.java

This patch refactors KudafUndoAggregator and WindowSelectMapper to
accept a list of functions rather than a map from index to function.

refactor: pass function list to undo/window-select

---

ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java

This test waits only up to 15 seconds for the topic to be created. ZK can take 10+ seconds to initialize.
Switching test to use `assertThatEventually` with its default timeout of 30 seconds.
Should hopefully reduce the chance of failures such as: https://jenkins.confluent.io/job/confluentinc-pr/job/ksql/job/PR-3462/1/

test: stabilize security integration tests

---

ksql-common/src/main/java/io/confluent/ksql/util/timestamp/PartialStringToTimestampParser.java
ksql-common/src/test/java/io/confluent/ksql/util/timestamp/PartialStringToTimestampParserTest.java
ksql-functional-tests/src/test/resources/rest-query-validation-tests/materialized-aggregate-static-queries.json

With this change the ROWTIME rewriter and static queries will use UTC by default for datetime strings, if not explicit timezone is provided.
USual

feat(static): switch partial datetime parser to use UTC by default

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStream.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamTest.java

Fixes https://github.com/confluentinc/ksql/issues/3450.
Currently when `print topic` encounters a JSON record with an empty value, a NullPointerException is thrown:
```
[2019-10-03 10:17:52,063] ERROR Exception encountered while writing to output stream (io.confluent.ksql.rest.server.resources.streaming.TopicStreamWriter:122)
java.lang.NullPointerException
at com.fasterxml.jackson.databind.node.ObjectNode.setAll(ObjectNode.java:408)
at io.confluent.ksql.rest.server.resources.streaming.TopicStream$Format$3$1.print(TopicStream.java:182)
at io.confluent.ksql.rest.server.resources.streaming.TopicStream$RecordFormatter.lambda$format$1(TopicStream.java:76)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeli …
```

fix: fix NPE when printing records with empty value (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceFactory.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropTypeFactory.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/RegisterTypeFactory.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/DropSourceFactoryTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/DropTypeFactoryTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/RegisterTypeFactoryTest.java

This patch is a follow up to a previous commit which moved the logic
for initializing DDL commands out of the command pojos and into
`CommandFactories`. One of the follow-ups to that work was to make the
initialization logic more modular rather than just dumping it all into
`CommandFactories`. In this patch, we move this logic out into separate
factory classes for the different ddl types. `CommandFactories` now
just routes arbitrary ddl statements to the right factory.
Refactored the unit tests as well to align with the new structure.

refactor: split out ddl creation from CommandFactories

---

ksql-engine/src/main/java/io/confluent/ksql/materialization/ks/KsMaterializedWindowTable.java
ksql-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializedWindowTableTest.java

KS does not like negative, so switch 'all windows' lower time boundary to `0L` rather than `Long.MIN_VALUE`.
Manual and usual

fix: Kafka Streams does not like negative time

---

docs/capacity-planning.rst
docs/concepts/ksql-and-kafka-streams.rst
docs/concepts/ksql-architecture.rst
docs/concepts/time-and-windows-in-ksql-queries.rst
docs/developer-guide/aggregate-streaming-data.rst
docs/developer-guide/api.rst
docs/developer-guide/create-a-stream.rst
docs/developer-guide/create-a-table.rst
docs/developer-guide/implement-a-udf.rst
docs/developer-guide/join-streams-and-tables.rst
docs/developer-guide/ksql-testing-tool.rst
docs/developer-guide/partition-data.rst
docs/developer-guide/query-with-arrays-and-maps.rst
docs/developer-guide/query-with-structured-data.rst
docs/developer-guide/serialization.rst
docs/developer-guide/syntax-reference.rst
docs/developer-guide/transform-a-stream-with-ksql.rst
docs/developer-guide/udf.rst
docs/includes/csas-snippet.sql
docs/includes/ctas-snippet.sql
docs/includes/ksql-includes.rst
docs/installation/server-config/avro-schema.rst
docs/installation/server-config/config-reference.rst
docs/operations.rst
docs/troubleshoot-ksql.rst
docs/tutorials/basics-control-center.rst
docs/tutorials/clickstream-docker.rst
docs/tutorials/examples.rst
docs/tutorials/examples.sql
docs/tutorials/generate-custom-test-data.rst

Updated the demo inline with recent changes to KSQL including:
- push queries now need `EMIT CHANGES`.
- added pull query example
- `PRINT` is now case-sensitive and does not require quotes.
- formatting of tables has changed
- etc

docs: start updating docs to include `EMIT CHANGES` for push queries

---

ksql-engine/src/main/java/io/confluent/ksql/materialization/ks/KsStateStore.java
ksql-engine/src/test/java/io/confluent/ksql/materialization/ks/KsStateStoreTest.java

Addressing outstanding comment in previous PR: https://github.com/confluentinc/ksql/pull/3340#discussion_r323964589 and https://github.com/confluentinc/ksql/pull/3340#discussion_r323966550
Unfortunately, it is not possible to avoid the `Thread.yield` call by use of the state listener on `KafkaStreams` as this can only be a single listener and can only be set when the instance is created. 
Hence this PR only addresses the second bit, about the race condition. 
usual

fix: race condition in KsStateStore

---

ksql-engine/src/test/java/io/confluent/ksql/materialization/ks/KsStateStoreTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

The message incorrectly stated that KSQL treats unquoted topic names as uppercase. This is not the case.
Also, the suggested alternative was just the opposite case to the supplied, which is fairly arbitrary, e.g. if the user issues `print PageView` and the topic does not exist the error message will suggest `pAGEvIEW`, even though no such topic exists.
With this change the error message will include any other topics that exist in the cluster with the same name,  but different case.
New error message looks like:
```bash
ksql> print PageVIEWS;
Could not find topic 'PageVIEWS', or the KSQL user does not have permissions to list the topic. Topic names are case-sensitive.
Did you mean:
print pageviews;
print PageViews;
ksql>
```
Test class switched from EasyMock to Mockito and suitable test …

fix: improve print topic error message when topic does not exist

---

ksql-cli/src/main/java/io/confluent/ksql/Ksql.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/TopologyFileGenerator.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestConfigTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockApplication.java

The Streams config `application.id` is set in the physical plan builder (and is unique for each query), so there's no point setting it to some default, unused value in the CLI or at the time of server creation. This PR cleans up the unused, legacy code.
`mvn clean package`

refactor: remove unused setting of application id (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/AbstractStreamSource.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/PlanBuilder.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/WindowedStreamSource.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/KSPlanBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamSourceBuilder.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamSourceBuilderTest.java

This patch splits StreamSource into StreamSource and WindowedStreamSource.
This way, we can build a strongly typed source stream without doing unchecked
casts.
Refactor, so no new tests

refactor: split up streamsource step

---

docs/tutorials/examples.rst

The `>` line prefixes are just rendered when being used interactively. The correct command (which can be copied and pasted into a terminal) goes without.

docs: remove incorrect prompt prefix in bash example

---

ksql-common/src/main/java/io/confluent/ksql/function/UdfFactory.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdafAggregateFunctionFactory.java

`UdfIndex` is not thread-safe, and is used in two place in the codebase where it could be accessed by different threads: `UdfFactory` and `UdfAggregateFunctionFactory`.
This PR adds synchronization to `UdfFactory` and `UdfAggregateFunctionFactory' to make this access thread-safe.
Currently `addFunction` is always called (in clock time) before `getFunction`. (Although this access pattern is not enforced in the class).
Note that this doesn't make the access safe, because there is no obvious happens-before relationship between the actions on a thread calling `addFunction` and another thread calling `getFunction`. 
There could be an accidental happens-before due to the way threads are currently started in the server but relying on this is fragile. By synchronizing we guarantee a …

fix: make sure use of non-threadsafe UdfIndex is synchronized

---

ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksql-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java
ksql-functional-tests/src/main/java/io/confluent/ksql/engine/StubInsertValuesExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java

The name of this class looks to have accidentally renamed in a previous PR, which was looking to rename some test classes. However, this is a production class.
Just a rename.

chore: fix accidental rename of `InsertValuesExecutor` (MINOR)

---

ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/KSPlanBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamJoinedFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamStreamJoinBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamsFactories.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamAggregateBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamGroupByBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamStreamJoinBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamTableJoinBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamToTableBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/TableAggregateBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/TableGroupByBuilderTest.java

This PR introduces the `StreamJoined` object from [KIP-479](https://cwiki.apache.org/confluence/display/KAFKA/KIP-479%3A+Add+StreamJoined+config+object+to+Join).  Specifically this PR
1. Removes use of the now deprecated `KStream#join(KStream,....Joined)` methods in favor of `KStream#join(KStream,....StreamJoined)`
2. Keeps the name of the stores so none of the expected topologies needed changing.  This was a judgment call on my part, and the KSQL team will need to let me know their preferences.
I updated existing tests.  Since this PR does not introduce new behavior, I felt that updating the current tests is sufficient.
EDIT: I ran the `QueryTranslationTest`, `ksql-engine`, and `ksql-streams` tests locally and all passed.

fix: changes required for compatibility with KIP-479

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/DataSourceNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/FilterNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedTable.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/DataSourceNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/FilterNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java

Clean up unused code from the structured package after moving
that functionality to the execution plan builders:
- cleans up key serdes from schemakX
- cleans up unused parameters from schemakX interfaces
- cleans up unit tests

refactor: clean up structured package

---

ksql-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-common/src/test/java/io/confluent/ksql/metrics/MetricCollectorsTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

Allows addition of MetricsReporters to MetricCollectors by specifying the type of reporter with the config "ksql.metric.reporters" and passing any other configs necessary to the server properties file. The corresponding MetricsReporter jar file must be specified in the ClassPath in order for this to work.
Unit test

feat: add configurable MetricsReporter to MetricCollectors

---

config/log4j.properties
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/ClusterTerminateRequest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlRequest.java

While working with KSQL server logs I noticed that the logs output by rest-utils is not of much use:
```
[2019-10-03 09:22:06,518] INFO 10.16.50.25 - - [03/Oct/2019:07:22:05 +0000] "POST /ksql HTTP/1.1" 200 16820  1298 (io.confluent.rest-utils.requests:60)
```
All it tells us is the time of the request, the status code and the size of the payload.  What it does not tell us is what was in the request. This would be useful when debugging!
With this change we get logs like:
```
[2019-10-09 22:34:06,193] INFO Received: KsqlRequest{ksql='CREATE STREAM TEST (ID INT) WITH (kafka_topic='test_topic', value_format='JSON');INSERT INTO TEST (ROWTIME, ROWKEY, ID) VALUES (1234, 'key', 10);', streamsProperties={}, commandSequenceNumber=Optional.empty} …
```

feat: add request logging

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ServerMetadataResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/filters/KsqlAuthorizationFilterTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/ServerClusterId.java
ksql-rest-model/src/test/java/io/confluent/ksql/rest/entity/ServerClusterIdTest.java

To be consistent with other Confluent platforms, the `/metadata` and `/metadata/id` paths were renamed to `/v1/metadata` and `/v1/metadata/id`.
Also, the `/v1/metadata/id` modified the output to this:
```
{
"scope": {
"path": [],
"clusters": {
"kafka-cluster": "ywqBIQ3PSU-K_5ttFkivCQ",
"ksql-cluster": "default_"
}
},
"id": ""
}
```
The kafka/ksql clusters ID are wrapped inside a `clusters` section. The `path` is also included, which for now is empty.
- Updated unit tests
- Run manual tests

feat: change /metadata REST path to /v1/metadata

---

ksql-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksql-engine/src/main/java/io/confluent/ksql/services/ServiceContextFactory.java
ksql-engine/src/test/java/io/confluent/ksql/embedded/KsqlContextTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/TestServiceContext.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/services/RestServiceContextFactory.java

This patch passes along the auth header that is used to the connect client so that we can forward it to the connect cluster when making requests.
I setup RBAC following https://github.com/confluentinc/examples/tree/5.3.0-post/security/rbac and then tried to run KSQL locally to create a connector:
```sql
ksql> CREATE SOURCE CONNECTOR `datagen-pageviews` WITH(  "connector.class"='io.confluent.connect.jdbc.JdbcSourceConnector',  "connection.url"='jdbc:postgresql://localhost:5432/almog.gavra',  "mode"='timestamp',  "timestamp.column.name"='created_at',  "topic.prefix"='jdbc-',  "key"='username',  "table.whitelist"='users');
Error
------------------------
Unauthorized operation
------------------------
```
In another shell, run 
```sh
confluent iam rolebinding create --principal User:ksqlcli …
```

feat: pass auth header to connect client for RBAC integration

---

ksql-engine/src/main/java/io/confluent/ksql/embedded/KsqlContext.java
ksql-engine/src/test/java/io/confluent/ksql/embedded/KsqlContextTest.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/ProcessingLogServerUtilsTest.java

This is part1 to replace the `ExecutionContext.execute(statement)` for `ExecutionContext.execute(serviceContext, statement)`. 
For this part, I made changes only in the following classes:
- TestExecutorUtil
- ListSourceExecutorTest
- ProcessingLogServerUtilsTest
- KsqlRestApplication
- KsqlContext
How to review?
- Each commit made changes only on one of the above classes for easy review.

refactor: replace ExecutionContext execute(stmt) for execute(ctx, stmt) (PART 1)

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlExecutionContext.java
ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

This is part2 of https://github.com/confluentinc/ksql/pull/3530.
This PR replaces the rest of the classes using `ExecutionContext.execute(stmt)` for `ExecutionContext.execute(ctx, stmt)`, and finally removes the method from the `ExecutionContext` interface.

refactor: remove ExecutionContext.execute(stmt) completely

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescriptionFactory.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ExplainExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java

Fixes #3208
With this commit the status of any persistent query is exposed as part of the response from `EXPLAIN <some-query-id>;`
For example,
```
ksql>EXPLAIN CSAS_ID_0_1;
ID                   : CSAS_ID_0_1
SQL                  : CREATE STREAM ID_0 WITH (KAFKA_TOPIC='ID_0', PARTITIONS=1, REPLICAS=1) AS SELECT *
FROM ORDER_KSTREAM ORDER_KSTREAM
EMIT CHANGES;
Status               : REBALANCING
Field       | Type
-----------------------------------------
ROWTIME     | BIGINT           (system)
ROWKEY      | VARCHAR(STRING)  (system)
ORDERTIME   | BIGINT
ORDERID     | VARCHAR(STRING)
ITEMID      | VARCHAR(STRING)
ORDERUNITS  | DOUBLE
TIMESTAMP   | VARCHAR(STRING)
PRICEARRAY  | ARRAY<DOUBLE>
KEYVALUEMAP | MAP<STRING, DOUBLE>
-----------------------------------------
...
```
Note the new …

feat: expose query status through EXPLAIN

---

ksql-common/src/main/java/io/confluent/ksql/schema/Operator.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/SqlBaseType.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/SqlBaseTypeTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksql-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/case-expression.json
ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercer.java
ksql-parser/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java

Fixes: #3405, #3344
This commit enhances the processing of `CASE` statements so that both `THEN` and the default return types can be `NULL`.
At least one branch must be non-null so that KSQL can determine the result type of the statement.
All non-null branches must have the same result schema, i.e. we don't (yet) do any implicit casting of numeric types.
The commit also improves some error messages by using KSQL types rather than connect schema types so that error messages use, for example, `BIGINT` rather than `Schema{INT64}`.
Usual

fix: support NULL return values from CASE statements

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/StaticQueryExtecutorTest.java

As part of the pull query work the `QueryValidator` class was removed, but a test class for it remained. This commit cleans that up.

refactor: rename test as test subject no longer exists (MINOR)

---

ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlRequest.java
ksql-rest-model/src/test/java/io/confluent/ksql/rest/entity/KsqlRequestTest.java

Any config of type LIST would not be coerced properly by `KsqlRequest`.
e.g. setting `set 'consumer.interceptor.classes'='io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor';`
would see the value coerced to a LIST containing a single value of '[io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor]', rather than `io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor`.
This commit resolves this issue. No other `ConfigDef.Type` should have a similar issue, as they are all single value.
mvn test

fix: fix parsing issue with LIST property overrides

---

ksql-common/src/main/java/io/confluent/ksql/config/KsqlConfigResolver.java
ksql-common/src/test/java/io/confluent/ksql/config/KsqlConfigResolverTest.java
ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java

Fixes: #2279
KSQL should allow any property to be passed to producers and consumers as the can be used to initialize things such as interceptors.
We can not know ahead of time what the properties a custom interceptor needs, hence we can't exclude any settings we see.
tests added.

fix: be more lax on validating config

---

ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksql-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java

Fixes: #3021
Tables do not support rows with `null` keys, so we should not allow users to insert rows with `null` keys.
tests added

fix: do not allow inserts into tables with null key

---

ksql-functional-tests/README.md
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/KsqlVersion.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/TestCaseNode.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/VersionBoundsNode.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/KsqlTestingTool.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCase.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilder.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/VersionBounds.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/VersionedTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/SchemaTranslationTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/loader/ExpectedTopologiesTestLoader.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/model/KsqlVersionTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/joins.json

This commit allows a new `versions` element to be added to test cases that controls the `min` and `max` versions of KSQL the test case is valid for.
This allows us to make known backwards-compatible changes to KSQL that would previously have caused an existing test to fail, e.g. changing the name of the internal topics.  With this commit we can mark the old test as only valid up to the last version and create a new version of the test for, with a min version, to test versions going forward
e.g.
```json
[{
"name": "stream stream left join",
"versions": {
"max": "5.3"
},
...
],
"inputs": [
...
],
"outputs": [
{"topic": "_confluent-ksql-some.ksql.service.idquery_CSAS_LEFT_OUTER_JOIN_0-KSTREAM-JOINTHIS-0000000008-store-changelog", "value": {"ROWTIME": 0, "ROWKEY": "0", "ID": …
```

test: extend test framework to allow bounds on KSQL version

---

ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksql-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java
ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercer.java
ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/SqlValueCoercer.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java

Fixes #3610
Partially Fixes #3591
Add support for arbitrary expressions in `INSERT VALUES`, which will allow:
- negative numbers
- arrays/maps
- UDFs
- All the other fun things you can imagine!
- RQTT tests 
- Unit testing
- local testing
```
ksql> CREATE STREAM complex (a ARRAY<INTEGER>, m MAP<STRING, INTEGER>) WITH (value_format='JSON', partitions=1, KAFKA_TOPIC='complex');
Message
Stream created
ksql> INSERT INTO complex (a, m) VALUES (AS_ARRAY(1, -1), AS_MAP(AS_ARRAY('key'), AS_ARRAY(1)));
ksql> SELECT * FROM complex;
Table 'COMPLEX' is not materialized. KSQL currently only supports static queries on materialized aggregate tables. i.e. those created by a 'CREATE TABLE AS SELECT <fields>, <aggregate_functions> FROM <sources> GROUP BY <key>' style …
```

feat: expression support for insert values

---

ksql-benchmark/src/main/java/io/confluent/ksql/benchmark/UdfInvokerBenchmark.java

This PR contains a new JMH benchmark for Udf invocations. It was created to compare before and after performance for https://github.com/confluentinc/ksql/pull/3566.
As this PR is stacked on https://github.com/confluentinc/ksql/pull/3566 it will contain the changes for that PR too, so please just review the file `UdfInvokerBenchmark.java`
N/A

feat: Udf Invoker benchmark

---

ksql-engine/src/main/java/io/confluent/ksql/connect/supported/JdbcSource.java

Rename a method that triggers a checkstyle error.
N/A

refactor: renamed method to avoid checkstyle error

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/StaticQueryValidator.java
ksql-functional-tests/src/test/resources/rest-query-validation-tests/materialized-aggregate-static-queries.json
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java

Switch the help messages returned to users on invalid pull queries to use the push vs pull query names.
usual.

docs: use push/pull naming in help messages

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/FlatMapNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udtf/KudtfFlatMapper.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamFlatMap.java
ksql-execution/src/test/java/io/confluent/ksql/execution/function/udtf/KudtfFlatMapperTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/explode.json
ksql-functional-tests/src/test/resources/query-validation-tests/table-functions.json
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamFlatMapBuilder.java

Fixes #3513
This is the first PR in a stack.
This PR provides the implementation of multiple table functions.
New QTT tests as appropriate

feat: Support multiple table functions in queries

---

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udtf/KudtfFlatMapper.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udtf/TableFunctionApplier.java
ksql-functional-tests/src/test/resources/query-validation-tests/table-functions.json

Fixes https://github.com/confluentinc/ksql/issues/3514
This is the 2nd PR in a stack. Please note this PR is stacked on https://github.com/confluentinc/ksql/pull/3685, so please don't review commits from the previous PR again.
With this PR table functions can now be arbitrarily complex expressions.
New QTT test

feat: Implement complex expressions for table functions

---

ksql-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/ConnectExecutable.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/client/RestResponse.java
ksql-test-util/src/main/resources/log4j.properties

Add integration tests for the connect/ksql integration point (CREATE/DROP/SHOW/DESCRIBE CONNECTOR).
- Test only change 😄 (and some cosmetic changes)

test: add integration tests for Connect/Ksql

---

config/ksql-production-server.properties
docs/installation/server-config/config-reference.rst
ksql-common/src/main/java/io/confluent/ksql/config/KsqlConfigResolver.java
ksql-common/src/test/java/io/confluent/ksql/config/KsqlConfigResolverTest.java
ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java

Fixes #817
- Adds new property file for production settings
- Changes to allow topic prefixed streams configs such as min.insync.replicas
- Unit tests added
- Verfied locally that the property file, creates topics with correct configuration
```
[kafka]$ bin/kafka-topics.sh --bootstrap-server localhost:9092 --topic _confluent-ksql-default_query_CTAS_ORDER_QUANTITIES_12-Aggregate-aggregate-changelog,_confluent-ksql-default_query_CTAS_ORDER_QUANTITIES_12-Aggregate-groupby-repartition --describe
...
Topic: _confluent-ksql-default_query_CTAS_ORDER_QUANTITIES_12-Aggregate-groupby-repartition	PartitionCount: 1	ReplicationFactor: 3	Configs: min.insync.replicas=2,cleanup.policy=delete,segment.bytes=52428800,retention.ms=-1
Topic: _confluent-ksql-default_query_CTAS_ORDER_QUANTITIES_12-Aggregate-grou …
```

fix: allow streams topic prefixed configs

---

ksql-benchmark/src/main/java/io/confluent/ksql/benchmark/UdfInvokerBenchmark.java
ksql-common/src/main/java/io/confluent/ksql/function/FunctionRegistry.java
ksql-engine/src/main/java/io/confluent/ksql/embedded/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdafLoader.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoaderUtil.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdtfLoader.java
ksql-engine/src/main/java/io/confluent/ksql/function/UserFunctionLoader.java
ksql-engine/src/test/java/TestUdfWithNoPackage.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdtfLoaderTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutorFactory.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java

This is the 4th PR in a stack. The previous PR is https://github.com/confluentinc/ksql/pull/3687. please don't review the commits from the previous PR you will see in here.
This PR refactors UdfLoader to be more manageable - it was becoming a sprawling mega-class that did too much and suffered from poor cyclomatic complexity.
There is more or less zero new code in this PR - it pretty much extracts existing code to new classes and does some renaming.
Now:
* UdfLoader loads udfs
* UdafLoader loads udafs
* UdtfLoader loads udtfs
* UserFunctionLoader is the corordinator for the overall loading process
* FunctionLoaderUtils contains static util functions used by the different loaders
* UdfLoader Passes checkstyle cyclomatic complexity check (previously it didn't)

Refactor: Split UdfLoader into multiple files

---

ksql-functional-tests/src/test/resources/query-validation-tests/quoted-identifiers.json
ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/util/DataSourceExtractor.java
ksql-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java

Fixes #1466 
Fixes #2171 
Fixes #2176  
Fixes two of the long-running issues around quoted identifiers and source names:
- `AstBuilder` and `DataSourceExtractor` no longer force upper case even when the source name is quoted
- `ParserUtil` enforces that source names match state store requirements (topic naming convention)
- `sourceName` is used directly in our grammar to give strong typing in the code
- went through a ton of tickets and manually tried reproducing them, fixed them as they went
- QTT tests
- Unit tests
```sql
ksql> CREATE STREAM `foo-bar` (id VARCHAR) WITH (kafka_topic='foo', value_format='JSON', partitions=1);
Message
Stream created
ksql> INSERT INTO `foo-bar` (id) VALUES ('123');
ksql> CREATE STREAM `foo-too` AS SELECT * FROM `foo-bar`; …
```

fix: quoted identifiers for source names

---

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamFlatMap.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/KSPlanBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamFlatMapBuilder.java

Minor refactor to have the flat map exec step store the function call
rather than the applier.

refactor: store function expr in flatmap step

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/TableRowsEntityFactory.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/TableRowsEntityFactoryTest.java

Fixes #3617 
`TableRowsEntityFactory.createRows` was throwing a NPE when a column of a row was null.
Added extra tests to check if a column of different types is NULL.
CLI output for  query: `ksql> SELECT * FROM METRICS_TABLE WHERE ROWKEY='fetch_latency_ms|+|cluster_xyz|+|topic_3|+|null';`
**Previous** output: `Server Error`
**After** changes output: 
```
ROWKEY STRING KEY                               | WINDOWSTART BIGINT KEY | METRICS_NAME STRING | CLUSTER STRING | TOPIC_NAME STRING | ENV STRING | AVG_VALUE DOUBLE
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
fetch_latency_ms|+|cluster_xyz|+|topic_3|+|null | 1572304800000          | fetch_latency_ms    | cluster_xyz …
```

fix: Don't throw NPE on null columns

---

ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksql-functional-tests/src/test/resources/query-validation-tests/table-functions.json

This PR changes the logic plan so that any filter node gets applied before a flat map node.
Non functional change but I've added a new QTT test for a table function with a where clause anyway.

fix: apply filter before flat mapping in logical planner

---

docs-md/installation/server-config/config-reference.md

Migrate new content from https://github.com/confluentinc/ksql/pull/3691.

docs: copy new recommended KSQL server config (DOCS-2816)

---

docs-md/developer-guide/partition-data.md
mkdocs.yml

Migrate content from https://github.com/confluentinc/ksql/pull/3401.

docs: migrate partitioning topic to markdown (DOCS-2776)

---

ksql-common/src/main/java/io/confluent/ksql/schema/connect/SqlSchemaFormatter.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/FormatOptions.java
ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-parser/src/main/java/io/confluent/ksql/util/IdentifierUtil.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/util/IdentifierUtilTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogServerUtils.java

`IdentifierUtils::needsQuotes` is used by various code that formats SQL text to decide what identifiers to wrap in quotes. Before this change, this just included reserved identifiers. However, identifiers that include lower-case characters should also be quoted. Otherwise, when the parser parses them it will convert them to upper-case.

fix: include lower-case identifiers among those that need quotes

---

docs/developer-guide/join-streams-and-tables.rst

The existing example is broken in that, assuming orders arrive before shipments, then `late_orders` will contain an entry for every order as soon as the order arrives (before the shipment has been processed) so `late_orders` is really all orders which is misleading. The late orders example is difficult to fix as true identification of late orders requires waiting two hours after the order has arrived and KSQL doesn't support this kind of time-delay/suppression operation today. As a result, this PR updates the example to compute `shipped_orders` instead.

docs: update broken stream-stream join example

---

ksql-engine/src/main/java/io/confluent/ksql/function/UdafLoader.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksql-engine/src/main/java/io/confluent/ksql/function/UdtfLoader.java
ksql-engine/src/main/java/io/confluent/ksql/function/UserFunctionLoader.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java

This PR is a copy of https://github.com/confluentinc/ksql/pull/3702 which has been closed due to a corrupt Jenkins workspace.
Please note this is a stacked PR. Please don't review changes from other PRs in the stack. 
This PR cleans up the loading of functions. The code has been simplified by replacing grungy stream logic with good old fashioned for loops. I've also extracted a couple of other things out to new functions to aid clarity.

refactor: clean up loading of UDFs/UDTFs/UDAFs

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/Column.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/ColumnRef.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/ExpressionAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/SourceSchemas.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DdlCommandExec.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/DataSourceNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/ExpressionAnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/DataSourceNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/joins.json
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java

`LogicalSchema` has a couple of methods that find columns:
* `findColumn(ColumnRef)` finds a column in the schema that 'matches' the supplied `ColumnRef`
* `finaValueColumn(ColumnRef)` as above, but only searching value columns
* `valueColumnIndex(ColumnRef)` returns the index of the column in the value columns that 'matches' the supplied `ColumnRef`.
The reason 'matches' in the list above is in quotes is because it doesn't do what you might think. The matching logic only takes the `SourceName` of a column into account if both the schema column and the supplied `ColumnRef` have a source name.  If either does not have a source, then the source is ignored!
For example, the test below would fail on the master branch without this PR:
```java
@Test
public void shouldFindExactColumn() {
// …
```

Refactor: Remove fuzzy logic used in `LogicalSchema.findXXX` methods

---

ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlErrorMessage.java
ksql-rest-model/src/test/java/io/confluent/ksql/rest/entity/KsqlErrorMessageTest.java

As part of the refactor of `KsqlErrorMessage` to no longer inherit from [rest-util's `ErrorMessage`](https://github.com/confluentinc/rest-utils/blob/f4b871c578777cacdb6487445a66a745f0077308/core/src/main/java/io/confluent/rest/entities/ErrorMessage.java), the JSON serialization was inadvertently changed in a backwards-incompatible way: the field that was previously serialized as `error_code` is now being serialized as `errorCode`. This PR reverts back to using `error_code` to avoid the backwards incompatibility.

chore: fix incompatible serialization of KsqlErrorMessage

---

ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java

The test was failing because the materialized state store was not warm when the pull query was issued.
Example failed build: https://jenkins.confluent.io/job/confluentinc/job/ksql/job/5.4.x/7/

test: fix flaky CliTest

---

.github/no-response.yml

This adds the config file for the no-response bot which automatically closes issues. https://github.com/probot/no-response
Issues that are labelled with 'more-info-needed' and which haven't had a response for 30 days will be closed.
Tested the bot on a personal repo. Seemed to work ok.

feat: Config file for the no-response bot 

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/Column.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java

Following on from #3748, with legacy key fields now gone, (#3764), we can now drop the final use of `Column.matches`.
usual

refactor: remove final uses of fuzzy `Column.matches`

---

docs/developer-guide/implement-a-udf.rst
docs/developer-guide/index.rst
docs/developer-guide/syntax-reference.rst
docs/developer-guide/table-functions.rst
docs/developer-guide/udf.rst

This PR is a copy of https://github.com/confluentinc/ksql/pull/3705 which was closed due to a corrupt Jenkins workspace
Fixes #3509 #3510
This PR contains the docs for the new table function functionality. It includes:
New syntax reference for built in table functions
New syntax reference for new UDFs
New section in dev guide on table functions
Extended page on UDFS to include table functions
Extended page on "implement a udf" to include table functions.

docs: New docs for table functions

---

ksql-common/src/main/java/io/confluent/ksql/config/ImmutableProperties.java
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutorTest.java

Adds a flag to make sure that allows servers to disable ad-hoc pull queries.
- Unit testing
- E2E testing:
```
ksql> SET 'ksql.pull.queries.enable'='true';
Cannot override property 'ksql.pull.queries.enable'
ksql> SELECT * FROM ALERTS;
Pull queries are disabled on this KSQL server - please enable ksql.pull.queries.enable
```

feat: add flag to disable pull queries (MINOR)

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/ConnectExecutable.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/Executable.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/ExecutableApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/ExecutableServer.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/MultiExecutable.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlServerMainTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/MultiExecutableTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockApplication.java

https://github.com/confluentinc/rest-utils/pull/155 enabled a single `ApplicationServer` to handle multiple applications. This patch makes KSQL use the same pattern. In order to do that I needed to:
- Change `Executable` methods to no longer clash with `LifeCycle` methods because their public usage was deprecated in `Application`
- Add an `ExecutableServer` which delegates `Executable` methods to the corresponding `LifeCycle` methods on `ApplicationServer`
- Make `KsqlRestApplication` no longer depend on having `ApplicationServer` internally; instead it is created externally. The `setServer` is handled in the `registerApplication` method
**Disclaimer**: I don't know if I love this change, but let's get it through so that master is unblocked. Afterwards (sometime next week hopefully) I'll …

chore: remove deprecated Application methods

---

docs/developer-guide/udf.rst
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/StatusResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StatusResourceTest.java

In the theme of cleaning up the code base:
With the current name, the StatementExecutor class used by CommandRunner to execute commands containing statements from the command topic is confusing because there's also a StatementExecutor interface that's being used in the RequestHandler which is completely unrelated to the StatementExecutor class.
https://github.com/confluentinc/ksql/blob/master/ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
https://github.com/confluentinc/ksql/blob/master/ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StatementExecutor.java 
Renaming the StatementExecutor class so the intended usage is clearer.
Refactor only

refactor: rename CommandRunner's StatementExecutor to InteractiveStatementExecutor (MINOR)

---

ksql-cli/Dockerfile
ksql-rest-app/Dockerfile

Copy the full jars into the docker image instead of using standalone. When we use standalone it doesn't use all of the dependencies so there isn't access to all of the UDFs (for example). This also helps with licensing. 
Built a docker image and smoke tested.

chore: change the Dockerfiles to copy all jars instead of standalone

---

ksql-functional-tests/README.md
ksql-functional-tests/src/test/java/io/confluent/ksql/test/QueryTranslationTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/loader/ExpectedTopologiesTestLoader.java

The docs around setting which topology versions to run when running the QTT test were wrong. The syntax is `-Dtopology.versions="5_0,5_3_0"`, not `-Dtopology.versions="5.0,5.3.0"`, i.e. the supplied versions must match the name of the folders under the `expected-topologies` directory.
Plus, there was no way that I could find to just run the latest version of the tests, so I've added the ability to set `-Dtopology.versions=latest-only`.

test: correct docs and extend QTT to allow it to run only against latest

---

Jenkinsfile
ksql-cli/pom.xml
ksql-rest-app/pom.xml
pom.xml

This will allow us to control the building and testing of docker images using the docker maven plugin. Previously these docker images were not being built so this functionality was fully disabled. Since each pom in this repo does not have a dockerfile the standard property for skipping the docker image builds does not work.
Verified that the default behavior remains the same and the docker images will not build. I also tested that when enabled the docker images build successfully.

ST-2519: Use a property to control the building of docker images.

---

Jenkinsfile

The ksql-db-release branch only contains a Jenkinsfile and is only used for building ksqldb and the docker images. This script will first check out the ksql master branch, then modify the project version to use the ksqldb release version, and then will change the parent pom versions to the provided beta version so that all confluent platform dependencies use beta versions. It also provides an option for performing a release build which will commit and tag the ksql repo so we can reproduce them. There is also an option for promoting the docker images from ECR to docker hub.
Note: There are two entries in this script that are for testing only. One is to use snapshots instead of the beta build, since we don't have a successful beta build with docker images yet I am going to commit it like …

build: ST-2519: Initial commit of the ksqldb release script. 

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/util/TabularRow.java
ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-cli/src/test/java/io/confluent/ksql/util/TabularRowTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/Flow.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryPublisher.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisherTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/StreamedRow.java

fixes: #3672 by providing alternative way of issuing pull queries that does NOT log
fixes: #3806
We should look to include #3819 as part of this fix.
Makes pull queries available on the `/query` RESTful and Websocket endpoints, in the same way that push queries are.
Note: this change does not _remove_ pull query support from the `/ksql` endpoint, nor does it switch the CLI over to use
the `/query` endpoint. The CLI continues to use the `/ksql` endpoint for pull queries.
Push and pull queries to the `/query` rest endpoint now return the schema of the rows in the first message.
This is required as the 'DESCRIBE' that CLI was previously running to get column headers doesn't work for pull queries yet. (Known issue: #3495).
This is similar to the pattern used by the websocket endpoint, which …

fix: pull queries available on `/query` rest & ws endpoint

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java

Fixes: #3847
This means we lose the richer column information for pull queries, e.g.
Where as you would of seen:
```
ksql> SELECT * FROM AGG_TABLE WHERE ROWKEY='ITEM_1';
+------------------------------------------------+-----------------------------------------------+
|ROWKEY STRING KEY                               |COUNT BIGINT                                   |
+------------------------------------------------+-----------------------------------------------+
|ITEM_1                                          |1                                              |
Query terminated
```
You now see:
```
ksql> SELECT * FROM AGG_TABLE WHERE ROWKEY='ITEM_1';
+------------------------------------------------+-----------------------------------------------+
|ROWKEY …
```

chore: switch CLI over to use `/query` endpoint for pull queries

---

ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializationFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java

Addresses #3542 . Don't build transformations for every request on the same state store but rather built them only the first time. 
Two follow up issues: #3855 and #3854 

refactor: cache transformations in PersistentQueryMetadata

---

Jenkinsfile

Use SSH credentials to push tag to GitHub.
Ran a release build, checked on GitHub that the tag was created. I'll be deleting this tag soon as it's not a real release: https://github.com/confluentinc/ksql/releases/tag/v0.6.0-ksqldb

build: push release tags using Jenkins ssh keys

---

ksql-engine/src/main/java/io/confluent/ksql/embedded/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/services/DefaultServiceContext.java
ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksql-engine/src/main/java/io/confluent/ksql/services/ServiceContextFactory.java
ksql-engine/src/test/java/io/confluent/ksql/embedded/KsqlContextTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/MemoizedSupplierTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/TestServiceContext.java
ksql-engine/src/test/java/io/confluent/ksql/util/KafkaTopicClientImplIntegrationTest.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutorFactory.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/services/RestServiceContextFactory.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

Fixes #3663 
When RBAC is not enabled, a new service context with kafka, sr, ksql clients is created PER request. With this PR, we will reuse the default SchemaContext created when the ksql REST application starts in the case of not enabled RBAC.
Open issues that need to resolved after the release: Should we make the `SchemaRegistryClient` lazy as well? Issue #3852 
Added tests to `StreamedQueryResourceTest` and `MemoizedSupplierTest`

refactor: Lazy initialization of clients (admin, sr, ksql, connect)

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryPublisher.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WebSocketSubscriber.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/EntityUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisherTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WebSocketSubscriberTest.java

fixes: #3848
Pull queries never return metadata columns, i.e. `ROWTIME`.
Likewise, push queries never return metadata or key columns, (unless they've been copied into the value schema, which means they're now value columns).
Unfortunately, this is not represented in the schemas built for these queries:
* the schema held in the push query's `TransientQueryMetadata` contains both meta and key columns: this is incorrect and must be removed before returning the schema from the websocket endpoint.
* the schema held in the pull query's `TableRowsEntity`  contains meta columns: this is incorrect and must be removed before returning the schema from the websocket endpoint.
Conversely, the rest endpoint looks to already be returning the correct schema.
This commit is a temporary fix to the schemas …

chore: fix issue with pull queries returning incorrect schema from ws

---

ksql-execution/src/main/java/io/confluent/ksql/services/DisabledKsqlClient.java
ksql-execution/src/main/java/io/confluent/ksql/services/SimpleKsqlClient.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/StaticQueryExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/services/DefaultKsqlClient.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/services/ServerInternalKsqlClient.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/StreamedRow.java

The previous PR missed moving the proxy call made by pull queries when the required data is on another KSQL node.  This PR moves the proxy call over to `/query`.
Due to tight time constraints, this PR may be suboptimal.
Fixes: #3847
usual

chore: switch pull query proxy call to use /query endpoint

---

ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json
ksql-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java

Fixes: #3864
This PR re-enabled the RQTT tests for pull queries that was temporarily disabled.   The test framework needed to be extended to support using the /query endpoint, now pull queries have been moved there.
The fix I've implemented extends the test executor so that it can handle the response from both the admin (/ksql) and the query endpoints.  To achieve this I had to wrap the existed responses in something to differentiate between the two response types.
`mvn test`

Enable pull query RQTT tests

---

Jenkinsfile

When creating the release tag we do not want to force push it for two reasons. One, we shouldn't be over writing a release tag that we previously created. Two, force pushing a tag causes issues for other people when they try to pull the latest changes from this repo if they already had that tag synced.
None. Will test this when we do the first official release of ksql-db or we can test it after we push the change to do a test run.

Do not force push the release tag

---

ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-common/src/main/java/io/confluent/ksql/config/ImmutableProperties.java
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/security/KsqlAuthorizationValidatorFactory.java
ksql-engine/src/main/java/io/confluent/ksql/services/DefaultServiceContext.java
ksql-engine/src/test/java/io/confluent/ksql/security/KsqlAuthorizationValidatorFactoryTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/DistributingExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java

fixes #3863
- Added `ksql.query.pull.skip.access.validator` to control if pull queries work without validation
- By default, Pull queries error out, if auth validation is needed
- Replaced DUMMY_VALIDATOR with Optional<> interface for KsqlAuthorizationValidatorFactory
- Fixed some tests, added test cases

feat: add config to disable pull queries when validation is required

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java

5.4.x branch is failing due to:
```
17:16:57  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project ksql-rest-app: Compilation failure
17:16:57  [ERROR] /tmp/confluent/ksql/ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java:[217,31] cannot find symbol
17:16:57  [ERROR]   symbol:   method same(io.confluent.ksql.rest.entity.CommandId)
17:16:57  [ERROR]   location: class io.confluent.ksql.rest.server.computation.CommandStoreTest
17:16:57  [ERROR] 
17:16:57  [ERROR] -> [Help 1]
```
This should fix that.

chore: fix command store test missing import

---

ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescriptionFactory.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionFactory.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WebSocketSubscriber.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/EntityUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/EntityUtilTest.java

The `buildSourceSchemaEntity` used to take a boolean indicating if only the value fields should be taken into account, or the whole schema. With recent changes, the schema passed is now correct and we should always take all fields into account, i.e. where before we were only using the value columns, now the passed schema only has value columns.
This commit removes the `valueSchemaOnly` param from `buildSourceSchemaEntity` and cleans up calling code and tests.
usual

refactor: simplify EntityUtil (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DdlCommandExec.java
ksql-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksql-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/DdlCommandExecTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/ddl/commands/CreateSourceCommand.java
ksql-execution/src/main/java/io/confluent/ksql/execution/ddl/commands/CreateStreamCommand.java
ksql-execution/src/main/java/io/confluent/ksql/execution/ddl/commands/CreateTableCommand.java
ksql-rest-app/src/test/resources/ksql-plan-schema/schema.json

Cleans up the sql text from the ddl command in `KsqlPlan`. Part of a larger
effort to trim down KsqlPlan.

refactor: clean up sql text from ddl commands

---

ksql-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksql-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryPublisher.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

First part of fix for https://github.com/confluentinc/ksql/issues/3859
This commit fixes the schema of `TransientQueryMetadata`, (the query metadata used for push queries), so that it only has value columns.  This makes the _schema_ stored in the metadata match the _data_ returned by push queries.
Previously, the schema contained meta and key columns, which push queries don't return.
Note: When you issue a `SELECT * FROM FOO EMIT CHANGES` style push query, the current impl copies the key and meta columns into the value, so its still only returning value columns.
This allows us to remove a temporary fix in `PushQueryPublisher` that was also removing key and meta columns.
`mvn test`

refactor: transient queries should only have value columns in schema

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlExecutionContext.java
ksql-engine/src/main/java/io/confluent/ksql/embedded/KsqlContext.java
ksql-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/ConfiguredKsqlPlan.java
ksql-engine/src/test/java/io/confluent/ksql/embedded/KsqlContextTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTestUtil.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ExplainExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryPublisher.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

This patch adds interfaces to build and execute plans in the KSQL engine
API, and changes StatementExecutor to use these interfaces to run statements.
It also exposes a method executeQuery that the query endpoint can use to build
transient queries.

feat: expose execution plans from the ksql engine API

---

ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/SelectValueMapperTest.java

Test was failing because the pull query was return heads, but no row, but this was enough to pass the assertThatEventually line. But this line should actually of been waiting of the store to return the value.
Fixes broken 5.4.x build: https://jenkins.confluent.io/job/confluentinc/job/ksql/job/5.4.x/92/
and master build: https://jenkins.confluent.io/job/confluentinc/job/ksql/job/master/3680/

Flaky test

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgent.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/ServerUtil.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogServerUtils.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/ServerUtilTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/ProcessingLogServerUtilsTest.java

https://github.com/confluentinc/ksql/issues/3768
As part of https://github.com/confluentinc/ksql/pull/3660 , there was a lot of duplicated transaction code put into `KsqlRestApplication.maybeCreateProcessingLogStream()` which isn't ideal. This is the only place in the code where we put a command into the command topic without going through the KsqlResource. This refactor changes `maybeCreateProcessingLogStream()` to use the KsqlResource instead of directly enqueueing the command.
This also fixes a bug where if the create processing log stream command fails to be committed, the aborted command would be left in the command topic and the processing log would never be created since the commandQueue isn't empty.
Updated unit tests and did some local testing

refactor: change processing log stream create to use KsqlResource

---

docs-md/developer-guide/create-a-table.md
docs-md/developer-guide/syntax-reference.md
docs-md/operate-and-deploy/installation/install-ksqldb-with-docker.md
docs-md/operate-and-deploy/installation/server-config/integrate-ksql-with-confluent-control-center.md
docs-md/tutorials/basics-local.md

Scrub the last six instances of `\'` that Pandoc injected during the conversion from reStructuredText.
Also checked the escaped double-quotes, and they’re all legit (compared with the .rst source).

docs: scrub remaining escaped quote chars in ksqlDB docs (DOCS-3001)

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

because they may be case sensitive or contain invalid chars.
Noticed this when looking at `insert-values.json` RQTT test, which adds a quoted source name.

test: when deleting sources we should quote identifiers

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RequestHandler.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

fixes: #3363
Issue was that the `prepare` call is throwing if the meta-store doesn't contain the sources in a statement.
Given a request contains a later statement that depends on an earlier statement, e.g.
```sql
CREATE STREAM FOO (...) WITH (...);
CREATE STREAM BAR AS SELECT *
```
The KSQL correctly validates the statements, because it updates the sandboxed copy of the meta-store as it goes.
However, when it comes to executing the statement it once against `prepares` the statement. Only this time its using the true meta-store and that is only updated by the command runner thread.  This can mean that the first statement is correctly written to the command topic, but if the next statement is `prepare`'d before the command runner thread executes the statement and updates the meta-store, …

fix: fix issues with multi-statement requests failing to validate

---

ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

The old way of creating ACLS through the `SimpleAclAuthorizer` was async:
1. the authorizer writes direct to ZK.
2. the brokers ZK listener fires.
3. the broker loads the ACL changes.
This was causing occasional test failures.
This commit switches our tests to use the sync ACL operations available through the Admin client.
It also moves us away from the deprecated `SimpleAclAuthorizer` to the new `AclAuthorizer`.
Example failed build: https://jenkins.confluent.io/job/confluentinc/job/ksql/job/5.4.x/94/

test: fix flaky test - caused by async ACL creation

---

mkdocs.yml

Pages on docs.ksqldb.io currently render with an incorrect `<link rel="canonical" ...>` tag. This corrects the respective setting in the docs-building configuration.
I built the docs site locally and inspected the generated tags:
```
.../ksql/_build/html$ cat index.html | grep canonical
<link rel="canonical" href="https://docs.ksqldb.io/en/latest/">
```
```
.../ksql/_build/html/concepts$ cat index.html | grep canonical
<link rel="canonical" href="https://docs.ksqldb.io/en/latest/concepts/">
```

docs: update docs site url to match canonical root.

---

docs-md/developer-guide/ksqldb-reference/create-stream-as-select.md

Migrate from : https://github.com/confluentinc/ksql/pull/3982.

docs: migrate syntax reference change from .rst to .md docs (DOCS-3028)

---

ksql-engine/src/main/java/io/confluent/ksql/function/udtf/Cube.java
ksql-engine/src/test/java/io/confluent/ksql/function/udtf/CubeTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/cube.json

The `cube` UDTF takes as argument a list of d columns and creates up tp 2^d rows (excludes duplicates created by `null` values in the input). Normally, `cube` is as an aggregate operator (extension to `Group By`) used in multi-dimensional data. It is a popular feature supported by all [RDBMSs](https://www.postgresql.org/docs/current/cube.html) and [Spark](https://jaceklaskowski.gitbooks.io/mastering-spark-sql/spark-sql-multi-dimensional-aggregation.html#cube), [Flink](https://ci.apache.org/projects/flink/flink-docs-stable/dev/table/sql.html#aggregations) As we don't have support for `Grouping Sets` yet, this UDTF enables us to achieve the same result in two steps: First, apply the `cube` UDTF to create all combinations, then apply aggregations on the result.
Example:
`SELECT …

feat: Add Cube UDTF

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/EntityUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/EntityUtilTest.java

The order of columns was unintentionally getting changed so that key columns can before value columns. This is incorrect.  A user can choose which order the columns are returned, e.g
```sql
SELECT COUNT, ROWKEY from Foo...
```
usual

fix: schema column order returned by websocket pull query (MINOR)

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/Column.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/SimpleColumn.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/ColumnMatchers.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/ColumnTest.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlBareOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/UdafUtil.java
ksql-metastore/src/test/java/io/confluent/ksql/metastore/model/KeyFieldTest.java
ksql-metastore/src/test/java/io/confluent/ksql/metastore/model/MetaStoreModelTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/TableRowsEntityFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamSelectKeyBuilder.java

Prep work for primitive keys
As previously discussed, finally done:
* Removes the private `NamespacedColumn` in favour of adding a `Namespace` field to the existing `Column` type.
* Removes the `LogicalSchema.valueColumnIndex` in favour of adding a `index` fields to the existing `Column` type.
* Removes the overloaded factory methods in `Column`, (used almost exclusively in tests), in favour of using custom hamcrest matchers, and for the few remaining production uses, specific factory methods.
* Adds a `SimpleColumn` interface to, hopefully, make it clear that `valueColumns(scheam.key())` only adds columns with matching type and name, not namespace or index.
`mvn test`

refactor: expose namespace and index on `Column`

---

checkstyle/checkstyle.properties
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/MaskKeepLeftKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/MaskKeepRightKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/MaskKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/MaskLeftKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/MaskRightKudf.java
ksql-engine/src/main/java/io/confluent/ksql/function/udf/string/Masker.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/string/MaskerTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlExceptionMapper.java

and fix up / remove any outstanding todos
one new github issue to track outstanding todo:
https://github.com/confluentinc/ksql/issues/3993
I've also completed the other todos in the `MASK` UDFs by adding appropriate parameter descriptions.
While in there I, and looking at #3993, I noticed we didn't currently validate the passed string contained only a single character.  An empty STRING would result an exception, while a multi-character string would be accepted, but only the first character would be used.  In the interest of 'failing hard and failing fast' these edge cases are no explicitly tested.   The main reason for adding this is to make any switch to a `CHAR` type parameters, (again see #3993), easier, as we know existing use only has a single char being passed.
Locally, if you have …

chore: turn on checkstyle rule to detect todo comments (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/PullQueryValidator.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java

fixes: https://github.com/confluentinc/ksql/issues/3521

chore: robin's requested message changes (MINOR)

---

ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java
ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGenProducer.java
ksql-examples/src/test/java/io/confluent/ksql/datagen/DataGenTest.java

remove `maxInterval` from `DataGen.Arguments` and print deprecation message to a user
Fixes #3565
BREAKING CHANGE: The maxInterval parameter for ksql-datagen is now deprecated. Use msgRate instead.
None
@vcrfxia, @apurvam could you guys please take a look?
Thank you

chore: deprecate maxInterval parameter for ksql-datagen

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/Column.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenSpec.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/ExpressionMetadata.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udtf/KudtfFlatMapper.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udtf/TableFunctionApplier.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/LogicalSchemaWithMetaAndKeyFields.java
ksql-execution/src/main/java/io/confluent/ksql/execution/transform/select/SelectValueMapper.java
ksql-execution/src/main/java/io/confluent/ksql/execution/transform/sqlpredicate/SqlPredicate.java
ksql-execution/src/test/java/io/confluent/ksql/execution/codegen/ExpressionMetadataTest.java
ksql-execution/src/test/java/io/confluent/ksql/execution/function/udtf/KudtfFlatMapperTest.java
ksql-execution/src/test/java/io/confluent/ksql/execution/transform/select/SelectValueMapperTest.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/GroupByMapper.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/GroupByMapperTest.java

Part of the primitive key work.
Switch the select mapper to get key columns from the key of the Kafka message
`mvn test`

refactor: get ROWKEY from key of Kafka record in topology steps

---

.gitignore

Minor change to prevent accidentally including `.vscode` folder in a commit
When VSCode devs add `.vscode` folder and they use java extensions, .vscode/ and .factorypath don't show up.

chore: add .vscode/ and .factorypath to .gitignore

---

ksql-engine/src/main/java/io/confluent/ksql/connect/supported/Connectors.java
ksql-engine/src/main/java/io/confluent/ksql/connect/supported/JdbcSource.java
ksql-engine/src/test/java/io/confluent/ksql/connect/supported/ConnectorsTest.java
ksql-engine/src/test/java/io/confluent/ksql/connect/supported/JdbcSourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ConnectExecutorTest.java

fixes #4036
See description on #4036 - just adds a default
- new unit tests

chore: add default key.converter=StringConverter to all connectors (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksql-engine/src/main/java/io/confluent/ksql/engine/QueryPlan.java
ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlan.java
ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedTable.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKSourceFactory.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/main/java/io/confluent/ksql/util/PlanSummary.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/PlanSummaryTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/PlanBuilder.java
ksql-rest-app/src/test/resources/ksql-plan-schema/schema.json
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StepSchemaResolver.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StepSchemaResolverTest.java

The goal here is to clean up the query plan schema as part of the work to
get to the plan schema proposed in https://github.com/confluentinc/ksql/pull/3969
Firstly, we flatten PhysicalPlan into QueryPlan in the plan schema. QueryPlan now
stores the properties it needs from PhysicalPlan, rather than holding a reference to
PhysicalPlan. This gives us a flatter, simpler, plan schema
This patch also cleans up the summary form the serialized plan by building it from
the execution plan, rather than by SchemaKStream. This is better because it gives
us a more accurate summary (previously we would skip some steps), simplifies
SchemaKStream, and simplifies the schema of the serialized plan.
The summary is built by a new class called PlanSummary, which walks the execution
plan and builds up the …

Clean up query plan schema

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WebSocketSubscriber.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorTest.java

If the pull query enable config is set to false and a user tries to send a pull query to the websocket, instead of getting back a clear error message, they'll see this.
```
HTTP/1.1 101 Switching Protocols
Date: Thu, 05 Dec 2019 00:02:03 GMT
Connection: Upgrade
Sec-WebSocket-Accept: qGEgH3En71di5rrssAZTmtRTyFk=
Upgrade: WebSocket
?"?KSQL excetion: KsqlRestException
```
That's because in `PullQueryExecutor`, we throw a `KsqlRestException`. `KsqlRestException` doesn't set the message for the exception which is a problem since in `WSQueryEndpoint` on this line, we return the exception.message to the user.
`SessionUtil.closeSilently(session, CloseCodes.CANNOT_ACCEPT, e.getMessage());`
This PR improves the exception message slightly, but it's still getting cut off by the char limit.
The …

chore: change pull query disabled exception from KsqlRestException to KsqlException

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunnerStatusMetric.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerStatusMetricTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

https://github.com/confluentinc/ksql/pull/3962 changes the commandRunner to never skip a command if it's gone through the transaction protocol. We need to expose some metric that can be used to alert if the commandRunner thread is stuck on a particular command.
This PR introduces a JMX metric for the commandRunner thread status.
Cherry-picked https://github.com/confluentinc/ksql/pull/3962 to this branch for testing.
Put `CREATE STREAM qwerqweq(age BIGINT) WITH (KAFKA_TOPIC='foo',  VALUE_FORMAT='DELIMITED');` into the command topic
Deleted topic foo
Started server
Watched the metric value in JConsole, after 15 seconds it went from RUNNING to ERROR since it was stuck processing the above command.
Created topic foo with zookeeper
The server completed start up and the metric value went back …

feat: add JMX metric for commandRunner status

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksql-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/DataSourceNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKSourceFactory.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/DataSourceNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKSourceFactoryTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/AbstractStreamSource.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSource.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/TableSource.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/WindowedStreamSource.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/WindowedTableSource.java
ksql-rest-app/src/test/resources/ksql-plan-schema/schema.json
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StepSchemaResolverTest.java

Cleans up offset reset from plan steps. All streams now default to
starting from the end. All tables now default to starting from the
first record. The reset can be overridden in the config.

refactor: clean up offset reset from plan steps

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/ConnectorListTableBuilder.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListConnectorsExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListConnectorsExecutorTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/SimpleConnectorInfo.java

fixes #3538 
Often, it's nice to get a bird's eye view of what is going on with all of your connectors. This PR changes `LIST CONNECTORS` to show the status (whether or not it is running) as well as a quick summary of the task states (e.g. `RUNNING (1/2 tasks RUNNING)`)
- Unit/Integration Tests

feat: add connector status to LIST CONNECTORS

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

BREAKING CHANGE: As a follow up to the transactional produce PR, now that every command that's enqueued has been validated against all previous commands, commands shouldn't be skipped when executing from the command topic.
Existing command topics commands may have conflicting commands in them and could cause the server to never start up, so a new flag is introduced for transactionally produced commands to indicate that only they shouldn't be skipped since they've gone through the transactional produce protocol.
A follow up PR will add a JMX metric that will indicate the health of the commandRunner. In addition, after https://github.com/confluentinc/ksql/blob/master/design-proposals/klip-6-execution-plans.md is completed, the chance of the commandRunner getting stuck should decrease.
mvn …

feat: never skip command in CommandRunner thread

---

design-proposals/README.md
design-proposals/klip-13-introduce-KSQL-command-to-print-connect-worker-properties-to-the-console.md

The PR introduce KLIP for adding `KSQL` command for printing connect worker configuration.
This is my first Improvement(Enhancement) Proposal ever written, so I could miss lot of things. Any feedback on content and style is highly appreciated.
Thank you

docs: klip-13: Introduce KSQL command to print connect worker properties to the console

---

ksql-engine/src/main/java/io/confluent/ksql/query/KafkaStreamsBuilderImpl.java
ksql-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java

Fixes https://github.com/confluentinc/ksql/issues/4079
It looks like from the original PR https://github.com/confluentinc/ksql/pull/3425/files to master, there was some refactoring done with how the Streams app is created which inadvertently changed the UncaughtExceptionHandler's behavior. The refactor changed https://github.com/confluentinc/ksql/pull/3425/files#diff-ef0765548f1131d562da8a8ef9edad73R285 was doing. The UncaughtExceptionHandler needs to be set for PersistentQueries (It's set in `QueryStreamWriter.java` for transient), which is why previously there's an explicit call in the `buildPlanForStructuredOutputNode` method (this was the pre-refactor method for creating PersistentQueries). The refactor resulted in `setUncaughtExceptionHandler()` being moved to the …

fix: UncaughtExceptionHandler not being set for Persistent Queries

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgent.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgentTest.java

The healthcheck endpoint currently checks connectivity to Kafka by issuing `list topics extended;`, but for purposes of checking connectivity it's sufficient to simply issue `list topics;` so we should do that instead to impose less load on Kafka.
Manual verification that the healthcheck continues to report a failed connection if Kafka is unavailable.

chore: issue regular LIST TOPICS from healthcheck, not extended (MINOR)

---

docs-md/developer-guide/query-with-structured-data.md
docs-md/faq.md
docs-md/operate-and-deploy/installation/install-ksqldb-with-docker.md
docs-md/operate-and-deploy/installation/installing.md
docs-md/operate-and-deploy/installation/server-config/config-reference.md
docs-md/operate-and-deploy/installation/server-config/index.md
docs-md/operate-and-deploy/installation/server-config/security.md
docs-md/tutorials/basics-docker.md
docs-md/tutorials/basics-local.md
docs-md/tutorials/clickstream-docker.md

Two docs changes:
- update references to `cp-ksql-server` and `cp-ksql-cli` docker images to `ksqldb-server` and `ksqldb-cli` instead, as `cp-ksql-server:0.6.0` and `cp-ksql-cli:0.6.0` don't exist
- remove docs on configuring monitoring interceptors with ksqlDB as ksqlDB docker images are not bundled with Confluent monitoring interceptors so the examples are broken (and confusing users, e.g., https://stackoverflow.com/questions/59214334/ksqldb-select-from-stream-results-in-io-confluent-monitoring-clients-interc)

docs: fix docker image names + remove monitoring interceptor docs

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/QueryAnalyzer.java
ksql-functional-tests/src/test/resources/query-validation-tests/table-functions.json

Explicitly disallows use of table sources with table functions.
Fixes https://github.com/confluentinc/ksql/issues/4033
Added QTT test

fix: Explicitly disallow table functions with table sources, fixes #4033

---

ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/RepartitionNode.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/key-schemas.json
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java

fixes: https://github.com/confluentinc/ksql/issues/3534
First of a few commits to start introducing support for primitive keys in different query types.
This commit opens the door for CT/CS statements with primitive keys, (`STRING`, `INT`, `BIGINT`, `BOOLEAN` and `DOUBLE`), and for using those sources in non-join, non-aggregate and non-partition-by queries.
Example queries added to `key-schemas.json`, which is a good place to start reviewing.

chore: primitive keys for simple queries

---

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-functional-tests/src/test/resources/query-validation-tests/partition-by.json

fixes #4053 
Previously, if we were to join on a non-rowkey field in the source schema, and then partition by the original rowkey, the second operation was ignored. This fixes the issue by making sure that the alias is correct. This is a temporary fix and will need to be changed when we change how we handle aliasing.
- new QTT tests
- checked for unnecessary repartitions

fix: properly set key when partition by ROWKEY and join on non-ROWKEY

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedTable.java
ksql-engine/src/test/java/io/confluent/ksql/function/KudafUndoAggregatorTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udaf/KudafAggregator.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/udaf/KudafUndoAggregator.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamAggregate.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamWindowedAggregate.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/TableAggregate.java
ksql-rest-app/src/test/resources/ksql-plan-schema/schema.json
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/AggregateParamsFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StepSchemaResolver.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamAggregateBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/TableAggregateBuilder.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/AggregateParamsFactoryTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StepSchemaResolverTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamAggregateBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/TableAggregateBuilderTest.java

This patch cleans up the aggregation step to specify a list of
non-aggregate column references instead of a count of non-aggregate
columns.
Part of the work to get us on the schema in #3969

refactor: nicer spec for aggregation steps

---

ksql-functional-tests/src/test/resources/query-validation-tests/simple-struct.json
ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java

fixes #3664
The JSON standard does not guarantee ordering and it is inefficient to do the sort. This is a small optimization in that regard.

chore: the KsqlJsonDeserializer no longer guarantees ordering (MINOR)

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java

Fixes https://github.com/confluentinc/ksql/issues/4114
Cause: https://github.com/confluentinc/ksql/issues/4114#issuecomment-564769317
This other commit already fixes the problem by removing the config that was being set to null anyways.
https://github.com/confluentinc/ksql/commit/289324117070123a8b4ab686774b6a409b8a5e09#diff-7848c43dbebc7bc8c45c12b2c1e2689cR247
This fix should still go in to prevent something like this from breaking headless mode again. Keys can't be null because the KsqlConfig would throw an exception if they weren't so we only need to check value.
Spun up headless mode

fix: headless server no longer throws NPE on null configs

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

Updated `QueryMetadata#close` method to use `KafkaStreams#close(Duration.ofXXX)` vs. the no-arg version.  When calling `KafkaStreams#close()` the default timeout is set to `Long.MAX_VALUE` so the `close` call will block forever.
Updated the existing tests

chore: Update KafkaStreams.close to take a duration parameter

---

design-proposals/README.md
ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/PropertiesListTableBuilder.java
ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/table/builder/PropertiesListTableBuilderTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListPropertiesExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListPropertiesExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/PropertiesList.java

Implementation of KLIP-13 Introduce KSQL command to print connect worker properties to the console
`(LIST|SHOW) PROPERTIES` command is extended to print embedded connect worker properties
N/A
Do we need integration test that touch file system to read connect worker properties file, or it would be better hide the fact that its properties come from file system?
Edited:
This is how it looks in the terminal on my machine
```
ksql> SHOW PROPERTIES;
Property                                               | Default override | Effective Value
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bootstrap.servers                                      | SESSION          | …
```

feat: implemention of KLIP-13

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionFactory.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutorTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java
ksql-rest-model/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionTest.java

Adds the SQL statement used to create a source to the `SourceDescription` object that's returned in the rest response.
This makes it easier for users to retrieve a statement for a Stream/Table in case they need to update and recreate the object. Instead of reconstructing the statement from the output of a `DESCRIBE` (which might not be very convenient with large schemas), they can just copy and paste it from the console/rest response.
The statement field is only present in the CLI console for `EXTENDED` commands.
This PR is done with the assumption that if a `UPDATE`/`ALTER` command is introduced later, `getSqlExpression()` would return the updated SQL statement that would be able to recreate that source. (Currently it just returns the original statement)
Updated console tests
Spun up …

feat: add source statement to SourceDescription

---

ksql-engine/pom.xml
ksql-engine/src/main/java/io/confluent/ksql/function/UdafTypes.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/count/CountDistinct.java
ksql-engine/src/test/java/io/confluent/ksql/function/udaf/count/CountDistinctKudafTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/count-distinct.json
pom.xml

Adds `COUNT_DISTINCT` to the ksqlDB UDAF suite with the following limitations:
- the syntax is note `COUNT(DISTINCT <expr>)` because we don't have support for this type of syntax yet
- the performance is likely bottlenecked by the throughput of array copies and auto/unboxing, I'm going to benchmark this to see if it's significant in the grand scheme of things (array copies of 2k ints may or may not be significant)
- the space overhead is (java Integer object size) 16 x 2731=43,696 bytes ~ 44kB per key
Also while making this change it looks like it was unnecessary to artificially restrict our UDAF framework from using generics.
- unit testing
- QTT testing

feat: add COUNT_DISTINCT and allow generics in UDAFs

---

ksql-engine/src/main/java/io/confluent/ksql/planner/plan/DataSourceNode.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/PlanSourceExtractorVisitorTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/joins.json
ksql-metastore/src/test/java/io/confluent/ksql/util/MetaStoreFixture.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/JoinParamsFactory.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/JoinParamsFactoryTest.java

Fixes: https://github.com/confluentinc/ksql/issues/4094
BREAKING CHANGE: Some existing joins may now fail and the type of `ROWKEY` in the result schema of joins may have changed.
When `ROWKEY` was always a `STRING` it was possible to join an `INTEGER` column with a `BIGINT` column.  This is no longer the case. A `JOIN` requires the join columns to be of the same type. (See https://github.com/confluentinc/ksql/issues/4130 which tracks adding support for being able to `CAST` join criteria).
Where joining on two `INT` columns would previously have resulted in a schema containing `ROWKEY STRING KEY`, it would not result in `ROWKEY INT KEY`.
*NOTE*: a fair few tests needed to be fixed as they were now doing invalid joins or expecting a STRING key.  I also removed some tests that were failing …

Adds support for using primitive types in joins.

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListTopicsExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListTopicsExecutorTest.java

https://github.com/confluentinc/ksql/issues/1284
Because we lower case all the keys when filtering out internal topics in the return, Kafka topics that differ only by casing will get overwritten in the list returned.
I'm not sure exactly why the `.toLowerCase()` is present, it's been there since late 2017 though.
Unit Test
Did a `show topics` command in the CLI

fix: show topics doesn't display topics with different casing

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java

As described in https://github.com/confluentinc/ksql/issues/4114, the ksqlDB server from the latest release fails to start in headless mode. This bug eluded our integration tests for headless mode because the integration test currently mocks the KafkaConfigStore which updates the KSQL config passed to the StandaloneExecutor (the mock does not perform these updates). This PR switches the integration test to use an actual KafkaConfigStore instance, rather than a mock, to avoid similar bugs in the future.

test: do not mock config store in StandaloneExecutor integration test

---

ksql-common/src/main/java/io/confluent/ksql/json/StructSerializationModule.java
ksql-common/src/test/java/io/confluent/ksql/json/StructSerializationModuleTest.java

fixes #4118
Decimals are not properly displayed in the CLI:
```sql
ksql> SELECT * FROM NESTED_DECIMALS EMIT CHANGES;
+------------------------------+------------------------------+------------------------------+
|ROWTIME                       |ROWKEY                        |VAL                           |
+------------------------------+------------------------------+------------------------------+
|1576622159874                 |null                          |{DEC=2.1}                     |
```
- unit test
- local testings

fix: decimals in structs should display as numeric

---

ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamTest.java

As part of adding support to Schema Registry for additional schema
types beyond Avro, some methods on SchemaRegistryClient will be
overloaded.  This change is to disambiguate these method calls in
the KSQL tests.

test: disambiguate some Schema Registry methods

---

docs-md/developer-guide/syntax-reference.md
docs/developer-guide/syntax-reference.rst
ksql-engine/src/main/java/io/confluent/ksql/engine/rewrite/ExpressionTreeRewriter.java
ksql-engine/src/test/java/io/confluent/ksql/engine/rewrite/ExpressionTreeRewriterTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenSpec.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenUtil.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksql-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java
ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/CreateStructExpression.java
ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/ExpressionVisitor.java
ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/StructExpression.java
ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/TraversalExpressionVisitor.java
ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/VisitParentExpressionVisitor.java
ksql-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksql-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
ksql-execution/src/test/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatterTest.java
ksql-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/create-struct.json
ksql-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json
ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercer.java
ksql-parser/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java

fixes #2147 
I was trying to debug an issue (#3874) but to my chagrin I was incapable of finding anyway to produce a struct with a decimal in it to a kafka topic. So I wrote this. What is this? This is the ability to create `STRUCT` types directly from KSQL - a long awaited feature! 
The syntax is up for debate (cc @hjafarpour @blueedgenick @rmoff) though I'd rather not go too far on that tangent as it's a long awaited feature. At the moment I chose ~`{(identifier expression (, identifier expression)*)?}`~ `STRUCT((expression AS identifier (, expression AS identifier)*)?`
Here's how it's used (note that the examples use the old syntax):
**INSERT VALUES:**
```sql
ksql> CREATE STREAM decimals (col0 STRUCT<val DECIMAL(2,1)>) WITH (kafka_topic='decimals', partitions=1, value_format='AVRO'); …
```

feat: add support for inline struct creation

---

ksql-engine/src/main/java/io/confluent/ksql/query/id/SpecificQueryIdGenerator.java
ksql-engine/src/test/java/io/confluent/ksql/query/id/SpecificQueryIdGeneratorTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

This patch changes up how we generate query IDs to play nice with
planned commands. Before this change, statements would get the current
offset as their query id. However planned commands get their query IDs
before being enqueued, so they should really get the _next_ expected
offset as their ID. This patch changes up the id generation to work
this way. The next ID is set _after_ statements/plans are executed,
and is set to the next expected offset.

fix: change query id generation to work with planned commands

---

CONTRIBUTING.md
docker-compose.yml

Added a sample docker-compose file with some steps for how to use. Brings up multi-node KSQL with dependants. 
Only outstanding issue is it doesn't look like community members can build docker images locally, as they won't have access to a AWS based docker repo, right?   Does anyone know a way around this, or plans to make this publicly available? cc @apurvam @rodesai @agavra 
manually checked it all works.

docs: add basic docker-compose file and instructions

---

ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenSpec.java
ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/CreateStructExpression.java

see description
ran the ImmutabilityTest

fix: immutability in some more classes (MINOR)

---

ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksql-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksql-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/fetch-field-from-struct.json
ksql-functional-tests/src/test/resources/query-validation-tests/simple-struct.json

When upgrading from 5.3->5.4 commands that were already written into the command topic would fail with "Cannot find function FETCH_FEILD_FROM_STRCUT". The reason is that we made structs stop rewriting with that UDF and instead inlined it's usage and prevent people from using that function externally. This re-introduces the change into 5.4. so that upgrades are possible.
NOTE: This will not be merged to master and master will be considered a breaking upgrade from 5.4
- verified the problem by running 5.3 and issuing a command with struct access
- upgraded to 5.4 and checked if it can recover; before this fix it cannot and after it can

fix: reintroduce FetchFieldFromStruct as a public UDF

---

ksql-streams/src/test/java/io/confluent/ksql/execution/streams/timestamp/MetadataTimestampExtractionPolicyTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/timestamp/TimestampExtractionPolicyFactoryTest.java

UsePreviousTimeOnInvalidTimeStamp is deprecated now. The alternative is UsePartitionTimeOnInvalidTimestamp

chore: use UsePartitionTimeOnInvalidTimestamp instead of UsePreviousTimeOnInvalidTimeStamp

---

ksql-functional-tests/src/main/java/io/confluent/ksql/engine/StubInsertValuesExecutor.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/TopicNode.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/json/ValueSpecJsonSerdeSupplier.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/kafka/KafkaSerdeSupplier.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/Record.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilder.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/Topic.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopicInfoCache.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/utils/SerdeUtil.java
ksql-functional-tests/src/test/java/io/confluent/ksql/engine/StubInsertValuesExecutorTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/SchemaTranslationTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestCaseBuilder.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/RecordTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/StubKafkaServiceTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorUtilTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/serdes.json
ksql-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

Enhanced the test framework to work with test cases with `BIGINT` and `DOUBLE` keys. This was previously failing due to Jackson deserializing the JSON describing the expected values into to `INT` and `DECIMAL`.
To achieve this I've started to tidy up the mess in the test framework. Specifically, we no longer track the serde to use in the `Topic` class, as this is constructed when parsing the test cases. Doing so was problematic as it was hard to know what serde should be used just from the test case text.  The serde to use is now determined by looking at the format of sources in the metastore once the SQL statements have been executed.
Also includes some additional test cases for pull queries working with primitive keys, and pulling out the code that determines the format / serde to use …

test: enhance test framework to support primitive keys

---

ksql-common/src/main/java/io/confluent/ksql/json/LogicalSchemaSerializer.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/PlanSummaryTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/timestamp/MetadataTimestampExtractionPolicyTest.java

They are not needed and stop the string representation being easily used, e.g. to build the schema in a CS/CT statement. Invariably, code has to strip or replace the square brackets, e.g. `LogicalSchemaSerializer`
Example output:
```sql
-- old
[ROWKEY STRING KEY, V0 INTEGER, V1 VARCHAR]
-- new
ROWKEY STRING KEY, V0 INTEGER, V1 VARCHAR
```
usual.

chore: drop square brackets from string representation of logical schema (MINOR)

---

docs/installation/server-config/integrate-ksql-with-confluent-control-center.rst

Per field feedback, "Currently, the basic auth is not supported between KSQL and C3 UI ... Can we please remove this from the current doc?"

docs: remove basic auth section from server-config (DOCS-3140)

---

ksql-common/src/main/java/io/confluent/ksql/function/FunctionRegistry.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/AggregateExpressionRewriter.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/FlatMapNode.java
ksql-engine/src/test/java/io/confluent/ksql/function/InternalFunctionRegistryTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/KudafUndoAggregatorTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksql-engine/src/test/java/io/confluent/ksql/function/UdtfLoaderTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/UdafUtil.java
ksql-execution/src/main/java/io/confluent/ksql/execution/function/UdtfUtil.java
ksql-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksql-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
ksql-execution/src/test/java/io/confluent/ksql/execution/function/UdafUtilTest.java
ksql-execution/src/test/java/io/confluent/ksql/execution/transform/sqlpredicate/SqlPredicateTest.java
ksql-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java
ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeFunctionExecutor.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/AggregateParamsFactoryTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StepSchemaResolverTest.java

Use FunctionName to specify the name of a function, not String, in FunctionRegistry
Fixes https://github.com/confluentinc/ksql/issues/3626
Updated all relevant tests

refactor: Use FunctionName not String in FunctionRegistry API

---

ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopologyAndConfigs.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/QueryTranslationTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/TopologyFileGenerator.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/TopologyFileGeneratorTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/TopologyFileRewriter.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/loader/ExpectedTopologiesTestLoader.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestLoader.java

Temporarily add back expected topology tests, until we make the
full switchover to the new query plan based tests

chore: add back expected topology tests

---

ksql-engine/src/main/java/io/confluent/ksql/security/KsqlSecurityContext.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/context/KsqlSecurityContextBinder.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/context/KsqlSecurityContextBinderFactory.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/HealthCheckResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/services/ServerInternalKsqlClient.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/context/KsqlSecurityContextBinderFactoryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/services/ServerInternalKsqlClientTest.java

**Notice:** This refactor is part of implementing a KSQL authorization cache to enable Pull Queries https://github.com/confluentinc/ksql/issues/4158
The KSQL authorization cache being implemented in https://github.com/confluentinc/ksql/issues/4158 requires the authenticated username to use it as part of the cache key. This username must be passed from the REST requests down to the KSQL permission validator. To do so, this PR replaces the current `ServiceContext` binder (which only injects a user impersonated ServiceContext object) with a new `KsqlSecurityContext` binder which wraps the authenticated REST or WS username and the current user impersonated ServiceContext into one context.
This `KsqlSecurityContext` is passed down to the KSQL permission validator where it will be used by the …

refactor: inject a KsqlSecurityContext to REST requests

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java

CLI-specific commands (including `run script`) may be optionally terminated with a semicolon. However, the KSQL CLI doesn't currently support trailing whitespace for CLI-specific commands terminated with a semicolon, which leads to confusing behavior in some of our demos, as many of them include `run script` commands terminated with semicolons and newlines. For example:
```
ksql> RUN SCRIPT '/usr/share/doc/clickstream/clickstream-schema.sql';
```
(with a new line at the end) results in
```
Failed to read file: /usr/share/doc/clickstream/clickstream-schema.sql;
Caused by: /usr/share/doc/clickstream/clickstream-schema.sql;
```
since the presence of the newline causes the semicolon to fail to be stripped, and it gets attached to the end of the filename argument as a result.
This PR fixes the …

fix: CLI commands may be terminated with semicolon+whitespace (MINOR)

---

ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/KsqlVersion.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCase.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/PlannedTestRewriterTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/PlannedTestsUpToDateTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestGenerator.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestLoader.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestPath.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestRewriter.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestUtils.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanLoader.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanWriter.java

This patch adds a rewriter tool for rewriting test topologies
in the event that the streams topology changes in a backwards
compatible way.

feat: add test topology rewriter

---

ksql-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java
ksql-test-util/src/main/java/io/confluent/ksql/test/util/TestMethods.java

Up stream changed, (new `register` methods added to `SchemaRegistryClient`), caused build failure. This commit fixes them.
Test now passes.

test: fix build issue caused by new register method on SR client

---

ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksql-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamTest.java
ksql-test-util/src/main/java/io/confluent/ksql/test/util/TestMethods.java

Schema Registry has added some new APIs as a result of adding
pluggable schema support.  This PR fixes tests which relied on older
APIs.

test: Fix Schema Registry tests after new SR API changes

---

ksql-common/src/test/java/io/confluent/ksql/serde/FormatInfoTest.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksql-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/key-schemas.json
ksql-functional-tests/src/test/resources/query-validation-tests/serdes.json
ksql-serde/src/main/java/io/confluent/ksql/serde/GenericKeySerDe.java
ksql-serde/src/main/java/io/confluent/ksql/serde/GenericRowSerDe.java
ksql-serde/src/main/java/io/confluent/ksql/serde/KsqlSerdeFactories.java
ksql-serde/src/main/java/io/confluent/ksql/serde/SerdeFactories.java
ksql-serde/src/test/java/io/confluent/ksql/serde/GenericKeySerDeTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/GenericRowSerDeTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/KsqlSerdeFactoriesTest.java

fixes: https://github.com/confluentinc/ksql/issues/4113
Added QTT tests to ensure sensible error messages are output from `CT`/`CS` and `CTAS`/`CSAS` statements where the key format, (currently always `KAFKA`), does not support the Sql type of the key column, e.g. the `KAFKA` format does not support `BOOLEAN`, `DECIMAL`, `MAP`, ARRAY` or `STRUCT` types.
Error message will look something like:
```
Key format does not support key schema.
format: KAFKA
schema: Persistence{schema=STRUCT<ROWKEY MAP<VARCHAR, INT>> NOT NULL, unwrapped=false}
reason: The 'KAFKA' format does not support type 'MAP'
```
This PR is all about adding tests.

chore: ensure sensible error on use of unsupported primitive key type

---

ksql-functional-tests/src/test/java/io/confluent/ksql/test/loader/ExpectedTopologiesTestLoader.java

don't load current qtt test case from the legacy loader (ExpectedTopologiesTestLoader).
The new loader (PlannedTestLoader) already loads these, and ExpectedTopologiesTestLoader
will soon be removed.

fix: don't load current qtt test case from legacy loader

---

ksql-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java
ksql-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/context/KsqlSecurityContextBinder.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/context/KsqlSecurityContextBinderFactory.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/services/RestServiceContextFactory.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/context/KsqlSecurityContextBinderFactoryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java

Using this singleton, locally on my Mac I'm able to increase the performance in a simple benchmark we have from 10k qps to about 14.5k qps.
I factored the context to be a singleton because the call to the constructor of `KsqlSchemaRegistryClientFactory` calls `sslFactory.configure()` which is an expensive operation.  By doing this, sslFactory.configure isn't done for every request, which saves a lot of work.
Ran `mvn clean package integration-test`

perf: Improves pull query performance by making the default schema service a singleton

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerFunctionalTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/joins.json

Fixes: https://github.com/confluentinc/ksql/issues/4241
Self-joins are not yet supported. Previously they resulted in an confusing error message:
>  Invalid topology: Topic <something> has already been registered by another source.
They not result in:
> Can not join 'something' to 'something': self joins are not yet supported.
Tests added.

fix: better error message on self-join

---

ksql-benchmark/src/main/java/io/confluent/ksql/benchmark/SerdeBenchmark.java
ksql-benchmark/src/main/resources/log4j.properties
ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java
ksql-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonDeserializerTest.java

Fixes: https://github.com/confluentinc/ksql/issues/4238
For complex types, the current deserialization error can be a bit lacking, as it does not include details of which field causes the error.  This commit enhances the JSON deserializer to include the JSON path of where the error occurred in the error message.
Error message will now look something like:
```json
{
"ROWTIME": 1578332584042,
"ROWKEY": null,
"LOGGER": "processing.<QUERY ID>.KsqlTopic.source.deserializer",
"LEVEL": "ERROR",
"TIME": 1578332584041,
"MESSAGE": {
"type": 0,
"DESERIALIZATIONERROR": {
"ERRORMESSAGE": "Error deserializing JSON message from topic: <TOPIC NAME>",
"RECORDB64": "<RECORD>",
"CAUSE": [
"Can't coerce string to type. targetType: BIGINT, path: $.colA.fieldB[3].x"
]
},
"RECORDPROCESSINGERROR": null, …
```

fix: include path of field that causes JSON deserialization error

---

config/connect.properties.template
ksql-rest-app/Dockerfile
ksql-rest-app/src/include/docker/configure
ksql-rest-app/src/include/docker/run

With this patch, docker users will be able to configure their embedded connect cluster using env variables prefixed with `KSQL_CONNECT_`.
Spun up ksqldb using the following docker compose:
```yml
ksqldb-server:
image: placeholder/confluentinc/ksql-rest-app:local.build
hostname: ksqldb-server
container_name: ksqldb-server
depends_on:
- broker
- schema-registry
ports:
- "8088:8088"
environment:
KSQL_BOOTSTRAP_SERVERS: "broker:9092"
KSQL_HOST_NAME: ksqldb-server
KSQL_LISTENERS: "http://0.0.0.0:8088"
KSQL_CACHE_MAX_BYTES_BUFFERING: 0
KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling2.properties …
```

feat: allow environment variables to configure embedded connect

---

design-proposals/klip-15-new-api-and-client.md

This PR introduces klip-15 - proposal for a new client and API updates.
N/A

docs: klip-15 New client and API

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java

Fixes: https://github.com/confluentinc/ksql/issues/4269
usual

fix: add logging during restore

---

ksql-cli/src/main/java/io/confluent/ksql/Ksql.java
ksql-cli/src/main/java/io/confluent/ksql/cli/Options.java
ksql-cli/src/test/java/io/confluent/ksql/cli/commands/OptionsTest.java

If the `-p` or `--password` parameters are not provided when using authentication, then the CLI will ask the user to enter the password on the prompt:
```
$  ./bin/ksql --user user1 http://localhost:8088
Enter password:
```
BREAKING CHANGE
The old behavior requires a user to type `--user` and `--password` parameters for authentication. This change makes `--password` optional.
This behavior provides an extra security to users who do not want to type the password in plaintext in the console. The `Enter password:` prompt will not echo the password.
* Added unit tests for the Options
* Tested manually

feat: ask for password if -p is not provided

---

ksql-common/src/main/java/io/confluent/ksql/SchemaNotSupportedException.java
ksql-functional-tests/src/test/resources/query-validation-tests/average-udaf.json
ksql-serde/src/main/java/io/confluent/ksql/serde/GenericKeySerDe.java
ksql-serde/src/main/java/io/confluent/ksql/serde/GenericRowSerDe.java
ksql-serde/src/test/java/io/confluent/ksql/serde/GenericKeySerDeTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/GenericRowSerDeTest.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/AggregateBuilderUtils.java

See https://github.com/confluentinc/ksql/issues/4294
`AVG` doesn't work with `DELIMITED` format and the error message isn't great.
Example statements that cause the error:
```sql
-- Given:
CREATE STREAM INPUT (VALUE integer) WITH (kafka_topic='test_topic', value_format='DELIMITED');
-- When:
CREATE TABLE OUTPUT AS SELECT avg(value) AS avg FROM INPUT group by ROWKEY;
```
Old error message:
```
ksql> CREATE TABLE OUTPUT AS SELECT avg(value) AS avg FROM INPUT group by ROWKEY;
CREATE TABLE OUTPUT AS SELECT avg(value)Value format does not support value schema.
format: DELIMITED
schema: Persistence{schema=STRUCT<KSQL_INTERNAL_COL_0 INT, KSQL_INTERNAL_COL_1 VARCHAR, KSQL_AGG_VARIABLE_0 STRUCT<SUM INT, COUNT BIGINT>> NOT NULL, unwrapped=false}
reason: The 'DELIMITED' format does not support type …
```

fix: report clearer error message when AVG used with DELIMITED

---

Jenkinsfile

The builds were failing because the twist lock scan was running but since we no longer build docker images from this repo it could not find any images to scan. This will disable running twist lock scan, as well as cleaning and trying to publish docker images.

build: Do not run twist lock scan and other docker image operations since we no longer build images in this repo

---

ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplier.java
ksql-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplierTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java

In preparation for leveraging JSON/Protobuf support for Schema Registry, this PR swaps over the code to use `ParsedSchema`, the new abstraction for accessing schemata stored in Schema Registry.
- Unit Tests updates
- Local smoke testing (registered a schema, pulled a schema)

chore: migrate to use ParsedSchema for SchemaRegistryClient

---

docs-md/tutorials/embedded-connect.md
docs-md/tutorials/index.md
mkdocs.yml

This PR adds a tutorial for running embedded Connect. For the time being, it makes the most sense to leave this tutorial in the docs (rather than the quickstart) since it's somewhat long. Once we iron out some of the kinks around running embedded Connect, we will consider reworking the quickstart to use embedded Connect by default.

docs: add embedded Connect tutorial

---

design-proposals/README.md
design-proposals/klip-12-pull-high-availability.md

**Author**: Vicky Papavasileiou, Vinoth Chandar | 
**Release Target**: 5.5 | 
**Status**: _In Discussion_
**Discussion**: _link to the design discussion PR_
**tl;dr:** Enables high-availability for Ksql pull queries, in case of server failures. Current 
design for handling failure of an active ksql server, incurs an unavailability period of several 
seconds (10+) to few minutes due to the Streams rebalancing procedure. This work is based on new 
Kafka Streams APIs, introduced as a part of [KIP-535](https://cwiki.apache.org/confluence/display/KAFKA/KIP-535%3A+Allow+state+stores+to+serve+stale+reads+during+rebalance), 
which allow serving stale data from standby replicas to achieve high availability, while providing 
eventual consistency. 
Stateful persistent queries persist their state in …

docs: KLIP 12 - Implement High-Availability for Pull queries

---

ksql-engine/src/main/java/io/confluent/ksql/query/BlockingQueryQueue.java
ksql-engine/src/main/java/io/confluent/ksql/query/BlockingRowQueue.java
ksql-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksql-engine/src/main/java/io/confluent/ksql/query/TransientQueryQueue.java
ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/query/TransientQueryQueueTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/TransientQueryMetadataTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriterTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

fixes: https://github.com/confluentinc/ksql/issues/4296
The produce side not calls `offer` in a loop, with a short timeout, to try and put the row into the blocking queue. When the consume side closes the query, e.g. on an `EOFException` if the user has closed the connection, the query first closes the queue; setting a flag the producers are checking on each loop; causing any producers to exit the loop. Then it can safely close the KS topology.
Added unit tests and manual testing

fix: deadlock when closing transient push query

---

config/log4j-rolling.properties

Avoids logging every request to come in at the Jetty level since that hurst pull query performance.  Before this change, on my Mac, I was getting 14k qps and with this change, I'm getting 30k.
Fixes #4306 
Ran benchmarks.

perf: Avoids logging INFO for rest-util requests, since it hurts pull query performance

---

ksql-cli/src/main/java/io/confluent/ksql/Ksql.java
ksql-cli/src/main/java/io/confluent/ksql/cli/Options.java
ksql-cli/src/test/java/io/confluent/ksql/cli/commands/OptionsTest.java

Fixes NPE when running the CLI with no arguments. Was throwing NPE on line:
```java
if (!options.getUserName().isEmpty() && !options.isPasswordSet()) {
```
in Ksql.java, as `options.getUserName()` was returning `null`.
Refactored so that username and password are never null, only empty.
Also refactored so that server will default to `http://localhost:8088`, even if other params are supplied.  Previously, it only defaulted to this if no params supplied.
Added tests and manual

fix: fix NPE in CLI if not username supplied

---

ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java

This just improves the error message. Better this than an `IndexOutOfBoundsException`.

test: RQTT should fail if expecting more responses than statements (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/ExpressionAnalyzer.java
ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/ExpressionAnalyzerTest.java
ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/joins.json

fixes #4130 
This PR introduces the ability to do arbitrary expressions in join conditions as long as on each side of the equality exactly one join source is used, and both join sources are represented. As an added bonus, this feature actually removes more code than it adds!
To implement this, I simply removed all repartition logic from the `JoinNode` and instead added a repartition step (reusing the recently introduced `RepartitionNode`) to each of the source nodes. This path is _always_ hit, if no repartition is required then the repartition node simply returns the same source as was passed into it. Now, the `JoinNode` always joins on the keys of its input.
To review, I recommend first looking at the `Analyzer` which has been simplified just to check the condition outlined above. Then, …

feat: expression support in JOINs

---

ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksql-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json

Fixes: https://github.com/confluentinc/ksql/issues/4123
Add test cases to test push queries work with non-windowed primitive keys

test: push queries work with non-windowed primitive keys

---

CONTRIBUTING.md

I followed the instructions to build and run locally, and fatal errors weren't written to stdout - took me a while to realise why the process was just exiting :) Found the error in the `ksql.log` log in the logs folder.

docs: add note re. logs folder for server output

---

pom.xml

This patch pins the jetty client version to the jetty version specified
by confluent/common to fix the test failures in the `RestApiTest`
integration test. These tests are currently failing due to an issue
with the client version maven picks by default.

fix: pin the jetty client version

---

ksql-package/pom.xml
ksql-package/src/assembly/package.xml

Fixes https://github.com/confluentinc/ksql/issues/3387
Adds the necessary dependencies on the KSQL package so ksql-test-runner can run without issues.
Executed a ksql-test-runner test from withing the `ksql-package-5.5.0-SNAPSHOT-package/bin` directory. The test passed.
```
ksql/ksql-package/target/ksql-package-5.5.0-SNAPSHOT-package/bin$ ./ksql-test-runner -s /tmp/statements.sql -i /tmp/input.json -o /tmp/output.json | grep 'Test passed'
>>> Test passed!
```

fix: add ksql-test-runner deps to ksql package lib

---

ksql-cli/src/main/java/io/confluent/ksql/Ksql.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/QueriesTableBuilder.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescriptionFactory.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionFactory.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionFactoryTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ExplainExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/RunningQuery.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java
ksql-rest-model/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionTest.java

While testing the primitive keys stuff manually I can across a couple of issues, inconsistencies, poor UX and bugs, which this commit looks to fix.
This commit:
1. exposes the window type of the key of a query/source, i.e. `HOPPING`, `TUMBLING` `SESSION` or none.
2. makes the status of a query easier to find, so users can quickly know if a query has failed or is running.
3. fixes a bug that meant the statement text of a query was not displayed in the CLI.
BREAKING CHANGE: The response from the RESTful API has changed for some commands with this commit: the `SourceDescription` type no longer has a `format` field. Instead it has `keyFormat` and `valueFormat` fields.
Response now includes a `state` property for each query that indicates the state of the query.
e.g.
```json
{
"queryString" : …
```

fix: report window type and query status better from API

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListConnectorsExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListConnectorsExecutorTest.java

fixes #4321
If no tasks of a connector are running, make sure that the status is `WARNING` instead of `RUNNING`
added a unit test

chore: change RUNNING to WARNING when all connector tasks fail (MINOR)

---

ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksql-execution/src/main/java/io/confluent/ksql/services/DisabledKsqlClient.java
ksql-execution/src/main/java/io/confluent/ksql/services/SimpleKsqlClient.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/HeartbeatAgent.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ClusterStatusResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/HeartbeatResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/services/DefaultKsqlClient.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/services/ServerInternalKsqlClient.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/HeartbeatAgentFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/HeartbeatAgentTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/ClusterStatusResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/HeartbeatResourceTest.java
ksql-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksql-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/ClusterStatusResponse.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/HeartbeatMessage.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/HeartbeatResponse.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/HostInfoEntity.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/HostStatusEntity.java

Initial implementation of heartbeat mechanism as part of #3959 
Added two new endpoints, `/heartbeat` used for registering received heartbeats and `/clusterStatus` used for reporting current cluster status. All the logic is in `HeartbeatHandler`. 
**Determining whether server is UP or Down**
Currently, the policy to decide whether a node is UP or DOWN is simplistic and will need to evolve: If a server misses more than `KSQL_HEARTBEAT_MISSED_THRESHOLD_CONFIG` it is marked as DOWN. However, if it receives even one heartbeat before the window closes, it will be marked as UP. So, it may miss all heartbeats except the last and still be marked as UP. We want to update this by counting the received heartbeats as well and having a threshold on them as well. We will update the policy after …

feat: Implementation of heartbeat mechanism as part of KLIP-12

---

docs-md/developer-guide/syntax-reference.md
docs/developer-guide/syntax-reference.rst

Migrate the new inline struct content from the rst docs to the markdown docs. Remove the obsolete note about not being able to create structs inline. Also, edit and re-arrange a bit.

docs: migrate new struct content to md docs (DOCS-3240)
