config/ksql-production-server.properties
config/ksql-server.properties
ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/schema/registry/DefaultSchemaRegistryClient.java
ksql-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java
ksql-engine/src/main/java/io/confluent/ksql/services/ServiceContextFactory.java
ksql-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/DefaultErrorMessages.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/ErrorMessages.java

Fixes #4319 
Removed default URL for SR from KsqlConfig
Implemented a new `DefaultSchemaRegistryClient` that's used when the URL is `""`
```
ksql> CREATE STREAM pageviews_avro WITH (KAFKA_TOPIC='pageviews', VALUE_FORMAT='AVRO');
Schema registry fetch for topic pageviews request failed.
Caused by: KSQL is not configured to use a schema registry. To enable it, please
set ksql.schema.registry.url
```
Unit test
Verified logs weren't being spammed when closing queries

feat: add a DefaultSchemaRegistryClient and remove default for SR url in KsqlConfig

---

ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocator.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocatorTest.java

- apache/kafka trunk Streams code has deprecated this already
- This change prevents an upcoming ksql build break
Build locally with a cherry-picked AK trunk and build seems to pass

refactor: supress warnings for metadataForKey

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlSchemaRegistryNotConfiguredException.java
ksql-engine/src/main/java/io/confluent/ksql/schema/registry/DefaultSchemaRegistryClient.java
ksql-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java
ksql-engine/src/main/java/io/confluent/ksql/services/ServiceContextFactory.java
ksql-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/DefaultErrorMessages.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/Errors.java
ksql-rest-model/src/test/java/io/confluent/ksql/rest/ErrorsTest.java

Previous PR to add a default SR client broke some downstream builds. This refactors the change in order to keep the old interface for `KsqlSchemaRegistryClientFactory`. Custom error messages moved to being handled only in rest endpoint
Spun up a server
```
ksql> CREATE STREAM pageviews_avro WITH (KAFKA_TOPIC='pageviews', VALUE_FORMAT='AVRO');
Schema registry fetch for topic pageviews request failed.
Caused by: KSQL is not configured to use a schema registry. To enable it, please
set ksql.schema.registry.url
ksql> 
```
unit test

refactor: move custom schema registry not configured error messages to rest endpoints

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/PushQueryValidator.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/PushQueryValidatorTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/hopping-windows.json
ksql-functional-tests/src/test/resources/query-validation-tests/session-windows.json
ksql-functional-tests/src/test/resources/query-validation-tests/tumbling-windows.json
ksql-functional-tests/src/test/resources/query-validation-tests/windowed-source.json
ksql-functional-tests/src/test/resources/test-runner/correct/aggregate/output.json
ksql-functional-tests/src/test/resources/test-runner/correct/aggregate/statements.sql

BREAKING CHANGE: Disallows persistent push queries of windowed tables.
We can revert when streams adds support for loading these with a windowed
state store. Note that we still allow transient queries on windowed tables, as
these are useful for testing the results of a persistent push query that creates
a windowed table.

chore: don't allow persistent push query of windowed table (MINOR)

---

ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java

Trivial PR to apply some requested feedback I missed on PR https://github.com/confluentinc/ksql/pull/4313, as I merged it before submitting the change.
Also requested was manual testing of the new single-line SQL in the tables.  This has been done.  I can report that the terminal handles wrapping the text perfectly, (well, iTerm2 on mac does anyway!). Resizing the window allows the user to choose how much wrapping they want or don't want, dynamically.

test: missed requested change (trivial)

---

ksql-common/src/main/java/io/confluent/ksql/serde/FormatInfo.java
ksql-common/src/test/java/io/confluent/ksql/serde/FormatInfoTest.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-functional-tests/src/test/resources/query-validation-tests/delimited.json
ksql-serde/src/test/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerializerTest.java

fixes #4200
The `VALUE_DELIMITER` only makes sense in the context of `DELIMITED` format and today we throw an error if it is set in any other format. This PR removes that error and just ignores it if it is set on a non-delimited stream. This way:
1. users can issue commands that take a delimited topic and turn it into another format
2. if they go back to delimited (e.g. delimited->json->delimited) it will maintain the original source delimiter
Alternatively, we can just not pipe the delimiter and use the default if going from a non-delimited format back to delimited.
- updated unit tests
- updated qtt
- local end-to-end testing

fix: do not throw error if VALUE_DELIMITER is set on non-DELIMITED topic

---

ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java

Removed deprecated Kafka API causing master builds to fail.
No required.

fix: remove deprecated Acl API

---

ksql-common/src/main/java/io/confluent/ksql/serde/FormatInfo.java
ksql-common/src/test/java/io/confluent/ksql/serde/FormatInfoTest.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-functional-tests/src/test/resources/query-validation-tests/delimited.json

Reverting #4366 and instead preventing delimiters from being piped through across non-delimited formats (see #4368 for an alternative solution) after discussing with @big-andy-coates.
- Updated the unit tests (kept the QTT tests testing the converting from DELIMITED->JSON/AVRO)

fix: delimiters reset across non-delimited types (reverts #4366)

---

ksql-engine/pom.xml
ksql-engine/src/main/java/io/confluent/ksql/function/UserFunctionLoader.java

fixes #1788
FastClasspathScanner has been EOL'd, ClassGraph is the new and improved shiny alternative. Migrating to it improves the speed of class-scanning slightly.

chore: migrate to ClassGraph (speed up UDF loading time)

---

ksql-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/rewrite/ExpressionTreeRewriterTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksql-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java
ksql-execution/src/main/java/io/confluent/ksql/execution/expression/tree/DecimalLiteral.java
ksql-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksql-execution/src/test/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatterTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/floating-point.json
ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksql-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java

Fixes build failures in https://github.com/confluentinc/ksql/pull/4364.
Previously, `DecimalLiteral` was the only literal type where the contained java type did not reflect the literal type. `DoubleLiteral` has a `double` field, `StringLiteral` a `String` field, `IntegerLiteral` an `int` field, etc.  But `DecimalLiteral` contained a `String` field.
While this works with the legacy code for persistent and push queries, (which tend to 'toString' everything), this is actually causing issues with pull queries, which pass the result of `Literal.getValue` to the `SqlValueCoercer`.  The coercer will happily coerce an `INT`, `BIGINT` or `DECIMAL` to a `DOUBLE`. But it won't convert a `STRING` to a `DOUBLE`. Because `DecimalLiteral.getValue` was returning a `String` the coercion failed.  This …

refactor: make decimal literals actual decimals

---

ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKSourceFactory.java
ksql-engine/src/main/java/io/confluent/ksql/util/PlanSummary.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/SourceStep.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSource.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/TableSource.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/WindowedStreamSource.java
ksql-execution/src/main/java/io/confluent/ksql/execution/plan/WindowedTableSource.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StepSchemaResolver.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java

why?
* Removed `Abstract`: while the class is abstract that does not mean it needs `Abstract` in the class name. We wouldn't put `Final` in the name of a `final` class. Names should describe what things are, not what attributes they have.  This makes code that uses the type easier to read.
* Remove `Stream`: as it is also the base class for tables, not just streams.
* Add `Step`: to more clearly disambiguate from `DataSource`, which is the source in the metastore.

chore: rename `AbstractStreamSource` to `SourceStep`

---

ksql-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/ddl/commands/CreateSourceCommand.java
ksql-execution/src/test/java/io/confluent/ksql/execution/ddl/commands/CreateSourceCommandTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/elements.json
ksql-metastore/src/main/java/io/confluent/ksql/metastore/model/StructuredDataSource.java
ksql-metastore/src/test/java/io/confluent/ksql/metastore/model/StructuredDataSourceTest.java
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/SingleColumn.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/SingleColumnTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/TableRowsEntityFactory.java

BREAKING CHANGE: `WINDOWSTART` and `WINDOWEND` are now reserved system column names. Any query that previously used those names will need to be changed: for example, alias the columns to a different name.
These column names are being reserved for use as system columns when dealing with streams and tables that have a windowed key.
In the fullness of time we may allow custom names for these columns. However, in the short term we're going to be using hardcoded names.
Suitable test unit / QTT tests added.

fix: reserve `WINDOWSTART` and `WINDOWEND` as system column names

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/PushQueryValidator.java
ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/PushQueryValidatorTest.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/conditions/PostConditions.java
ksql-functional-tests/src/test/resources/query-validation-tests/joins.json
ksql-functional-tests/src/test/resources/query-validation-tests/windowed-source.json

Fixes: https://github.com/confluentinc/ksql/issues/4389
Previously, KSQL did nothing to validate a join between two sources had keys with compatible windowing.
* it did not check that both sources were either windowed or non-windowed.  Joining a non-windowed source to a windowed source will never result in any output as the binary keys can never match.
* it did not check that both sources had compatible window types. Session windows include both window start and end times in the serialized key, where as hopping and tumbling windows only serialize the window start. For this reason, session windowed sources can only be joined with other session windowed sources. Hopping and tumbling windowed sources can only be joined with other hopping and tumbling windowed sources.
This commit adds these …

Correctly validate joins between windowed and non-windowed sources

---

ksql-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksql-common/src/test/java/io/confluent/ksql/function/UdfFactoryTest.java
ksql-common/src/test/java/io/confluent/ksql/function/UdfIndexTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/explode.json

When a UDF/UDAF/UDTF is called with incorrect parameters the user is informed by the error:
```
Function 'Foo' does not accept parameters of types:[STRING, STRING]
```
This is all well and good, but KSQL could be more helpful!  The message is now:
```
Function 'Foo' does not accept parameters (STRING, STRING).
Valid alternatives are:
FOO(STRING)
FOO(STRING text, INT len)
FOO(STRING text, INT start, INT len)
For detailed information on a function run: DESCRIBE FUNCTION <Function-Name>;
```
`mvn test` and manual

fix: include valid alternative UDF signatures in error message (MINOR)

---

ksql-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/SchemaConverters.java
ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-common/src/test/java/io/confluent/ksql/function/UdfIndexTest.java
ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksql-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
ksql-functional-tests/src/test/resources/query-validation-tests/udf-implicit-cast.json

fixes #4400 
fixes #3791 
This PR adds functionality to automagically cast parameters when calling into a user defined function.
**Review Guide**:
1. Look at `SchemaUtil#areCompatible` which now supports implicit casting to determine whether or not a sqltype and param type are compatible
2. Look at `UdfIndex` which now first checks the strict compatibility, and if it finds nothing will check the implicit cast compatibility
3. Look at `SqlToJavaVisitor`, which will perform the implicit casts when the arguments are not the exact types
- unit tests
- QTT tests
- ran the scenario described in #4400 to make sure that it works

feat: support implicit casting in UDFs

---

ksql-api/src/test/java/io/confluent/ksql/api/tck/BufferedPublisherVerificationTest.java
ksql-api/src/test/java/io/confluent/ksql/api/tck/ReactiveSubscriberBlackboxVerificationTest.java
ksql-api/src/test/java/io/confluent/ksql/api/tck/ReactiveSubscriberWhiteboxVerificationTest.java

Following some local failures in `ReactiveSubscriberWhiteboxVerificationTest` on loaded local machine.

test: increase timeouts to avoid flaky tests

---

ksql-package/pom.xml
ksql-package/src/assembly/package.xml

Fixes #3387
Backported https://github.com/confluentinc/ksql/pull/4272
Adds the necessary dependencies on the KSQL package so ksql-test-runner can run without issues. 
Executed a ksql-test-runner test from withing the ksql-package-5.3.3-SNAPSHOT-package/bin directory. The test passed.

fix: add ksql-test-runner deps to ksql package lib (#4272)

---

ksql-benchmark/src/main/java/io/confluent/ksql/benchmark/SerdeBenchmark.java
ksql-common/src/main/java/io/confluent/ksql/serde/Format.java
ksql-common/src/main/java/io/confluent/ksql/serde/FormatInfo.java
ksql-common/src/test/java/io/confluent/ksql/serde/FormatInfoTest.java
ksql-common/src/test/java/io/confluent/ksql/serde/KeyFormatTest.java
ksql-common/src/test/java/io/confluent/ksql/serde/ValueFormatTest.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/topic/TopicFactory.java
ksql-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksql-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-engine/src/test/java/io/confluent/ksql/topic/TopicDeleteInjectorTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
ksql-execution/src/test/java/io/confluent/ksql/execution/builder/KsqlQueryBuilderTest.java
ksql-functional-tests/src/test/resources/historical_plans/average_-_calculate_average_in_select/5.5.0_1579766275923/spec.json
ksql-functional-tests/src/test/resources/query-validation-tests/delimited.json
ksql-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json
ksql-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceAsProperties.java
ksql-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceProperties.java
ksql-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourceAsPropertiesTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourcePropertiesTest.java
ksql-rest-app/src/test/resources/ksql-plan-schema/schema.json
ksql-serde/src/main/java/io/confluent/ksql/serde/KsqlSerdeFactories.java
ksql-serde/src/test/java/io/confluent/ksql/serde/GenericRowSerDeTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/KsqlSerdeFactoriesTest.java

The `FormatInfo` class is serialized as part of the execution plan and contains one-off fields that are specific to a given format (e.g. `delimiter` for the DELIMITED format). This PR instead changes it to use a map of properties that is more flexible to use for any format going forward.
Reviewing note: almost all of the changes in this PR are test changes, look at `FormatInfo` and `schema.json` to see the important changes.
- updated corresponding unit tests

refactor: generalize FormatInfo in prepration for more formats

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/LagReportingAgentFunctionalTest.java

Removes unnecessary @AfterClass cleanup since this is setup across tests.  This was the source of flakiness.

fix: Remove unncecessary @AfterClass cleanup in LagReportingAgentFunctionalTest which is causing flakiness

---

docs/installation/server-config/index.rst

This is the .rst port of https://github.com/confluentinc/ksql/pull/4361.

docs: add note about KSQL headless mode and Avro schemas (DOCS-1487)

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/QueriesTableBuilder.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/RunningQuery.java

Fixes https://github.com/confluentinc/ksql/issues/4344
Renames columns and adds a new column in order to have both the sink Kafka Topic and the sink Stream/Table displayed
```
ksql> show queries;
Query ID    | Status  | Sink Name | Sink Kafka Topic | Query String                                                                                                                                
-----------------------------------------------------------------------------------------------------------------------------------------------------
CSAS_FOO4_2 | RUNNING | FOO4      | FOO4             | CREATE STREAM FOO4 WITH (KAFKA_TOPIC='FOO4', PARTITIONS=1, REPLICAS=1) AS SELECT *FROM KSQL_PROCESSING_LOG KSQL_PROCESSING_LOGEMIT CHANGES; 
CSAS_FOO3_4 | RUNNING | FOO3      | BAZ …
```

feat: add new and rename show queries columns for sink Kafka Topic and Stream/Table

---

docs-md/operate-and-deploy/installation/installing.md
docs-md/tutorials/docker-compose.yml

I munged the CP version while working on the ksqlDB version, d'oh.

docs: fix tutorial stack file versions in master (DOCS-3330)

---

docs-md/developer-guide/syntax-reference.md
docs-md/tutorials/basics-docker.md
docs-md/tutorials/basics-local.md

Fixes: https://github.com/confluentinc/ksql/issues/4143
This PR updates the docs to reflect the new primitive key functionality and some code changes to update DataGen.
* ksqlDB now supports the following primitive key types: `INT`, `BIGINT`, `DOUBLE` as well as the existing `STRING` type.
The key type can be defined in the CREATE TABLE or CREATE STREAM statement by including a column definition for `ROWKEY` in the form `ROWKEY <primitive-key-type> KEY,`, for example:
```sql
CREATE TABLE USERS (ROWKEY BIGINT KEY, NAME STRING, RATING DOUBLE) WITH (kafka_topic='users', VALUE_FORMAT='json');
```
* ksqlDB currently requires the name of the key column to be `ROWKEY`. Support for arbitrary key names is tracked by https://github.com/confluentinc/ksql/issues/3536.
* ksqlDB currently requires keys …

Docs for primitive key support

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/DistributingExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/DefaultErrorMessages.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/ErrorMessages.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/Errors.java

Addresses https://github.com/confluentinc/ksql/issues/4453
Moved `transactionalProducer.initTransactions()` out of the same try catch block as the rest of the transaction operations. 
Added more specific error message. (added as a pluggable one for scenarios where it doesn't make sense to advise the user to set their Kafka configs)
This isn't ideal currently as there are other reasons for a TimeoutException to be returned from `initTransaction` but until https://issues.apache.org/jira/browse/KAFKA-9511 is worked on, I think this is the best we can  do.
Unit test
Spun up a Kafka without setting the required configs, got the error message when issuing a DDL to the server.
```
ksql> CREATE STREAM source_ab (myFixedField1 varchar, eventPayload varchar) WITH (kafka_topic='topic_a', PARTITIONS …
```

feat: better error message when transaction to command topic fails to initialize by timeout

---

ksql-api/pom.xml

fix: Remove duplicate maven dependencies that cause warnings during build

---

ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksql-engine/src/main/java/io/confluent/ksql/analyzer/ColumnReferenceValidator.java
ksql-engine/src/test/java/io/confluent/ksql/analyzer/ColumnReferenceValidatorTest.java

As all it does is validate columns exist and aren't ambiguous.
Name's been confusing / bugging me for a while.

refactor: rename `ExpressionAnalyzer` -> `ColumnReferenceValidator` (Minor)

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java

On shutdown we're trying to close the Kafka Consumer from a different thread to the one that is using the consumer. Kafka Consumers are single threaded.
Hence we must close the consumer on the same thread as the one polling.
Fixes the following exception on shutdown:
```
[2020-02-07 15:10:44,646] ERROR Exception while waiting for CommandRunner thread to complete (io.confluent.ksql.rest.server.KsqlRestApplication:350)
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2422)
at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2305)
at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2260)
at …
```

fix: exception on shutdown of ksqlDB server (MINOR)

---

ksql-functional-tests/src/test/resources/query-validation-tests/system-columns.json
ksql-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksql-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json
ksql-parser/src/main/java/io/confluent/ksql/parser/tree/SingleColumn.java
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-parser/src/test/java/io/confluent/ksql/parser/tree/SingleColumnTest.java

fixes: https://github.com/confluentinc/ksql/issues/4458
Tests added to cover use of all system columns in:
- MVs, a.k.a persistent queries: disallows unaliased system columns in select
- pull queries: allows unaliased system columns in select
- push queries: allows unaliased system columns in select
Note: You still can't alias a column to a system column name in a push/pull query, i.e. you can't do:
```sql
SELECT someCol AS ROWTIME FROM FOO;
```
Note: I also refactored `KsqlParserTest.java` to use (mostly) hamcrest matchers.
Usual.

chore: add tests covering use of system columns in projection

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/HeartbeatAgent.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/HeartbeatAgentTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/MaximumLagFilterTest.java

Currently, when a single host exists, lag doesn't get reported.  This ensures lag always gets reported.  Also changes the default to not filter if there is no lag data.

fix: Fixes the single host lag reporting case

---

ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java

Lost the root cause for an error during recent refactors. Using the `ErrorMessageUtil.buildErrorMessage(`) to get back the specificity of the error message.
before
```
ksql> CREATE STREAM KS_ORDERS WITH (KAFKA_TOPIC='KS_ORDERS', VALUE_FORMAT='AVRO');
Schema registry fetch for topic KS_ORDERS request failed.
```
after
```
ksql> CREATE STREAM KS_ORDERS WITH (KAFKA_TOPIC='KS_ORDERS', VALUE_FORMAT='AVRO');
Schema registry fetch for topic KS_ORDERS request failed.
Caused by: KSQL is not configured to use a schema registry. To enable it, please
set ksql.schema.registry.url
```

fix: print root cause in error message

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ClusterStatusResource.java

Fix flaky test in master. Changed streams api to nested loops to make reasoning about the code easier.
Ran `HeartbeatAgentFunctionalTest` 60 times.

fix: ConcurrentModificationException in ClusterStatusResource

---

docs-md/developer-guide/create-a-stream.md
docs-md/developer-guide/create-a-table.md
docs-md/developer-guide/ksqldb-reference/print.md
docs-md/developer-guide/query-with-structured-data.md
docs-md/tutorials/basics-docker.md
docs-md/tutorials/basics-local.md
docs/includes/ksql-includes.rst
ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksql-cli/src/test/java/io/confluent/ksql/cli/SslFunctionalTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-engine/src/test/java/io/confluent/ksql/util/ItemDataProvider.java
ksql-engine/src/test/java/io/confluent/ksql/util/KafkaTopicClientImplIntegrationTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PrintPublisher.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PrintTopicUtil.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStream.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriter.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/PrintSubscriptionTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamingTestUtils.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriterTest.java
ksql-serde/src/main/java/io/confluent/ksql/serde/kafka/KafkaSerdeFactory.java
ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

Fixes: https://github.com/confluentinc/ksql/issues/4258
This change makes `PRINT TOPIC` output not just the format of the value, but also the key.
Output used to look like:
```
Format:JSON
{"ROWTIME":1544042630406,"ROWKEY":"1","type":"key1","data":{"timestamp":"2018-12-21 23:58:42.1","field-a":1,"field-b":"first-value-for-key1"}}
...
```
The old version tried to represent the whole row as a JSON Object, or Avro record, etc.  Going forward this doesn't make sense as there are two formats at play: key and value, and they are generally different. 
It now looks like:
```
Key format: KAFKA (STRING)
Value format: JSON
rowtime: 02/10/2020 20:26:44 GMT, key: "1", value: {"type":"key1","data":{"timestamp":"2018-12-21 23:58:42.1","field-a":1,"field-b":"first-value-for-key1"}}
...
```
Note: the 'Key …

chore: Primitive Keys comes to PRINT TOPIC

---

docs-md/operate-and-deploy/installation/upgrading.md

chore: update upgrade notes for 0.7

---

design-proposals/klip-15-new-api-and-client.md

Update KLIP to bring up to date wrt current development and latest PR comments
N/A

docs: Bring KLIP-15 up to date

---

ksql-api/src/test/java/io/confluent/ksql/api/TestInsertsSubscriber.java

Should fix CME in test as internal list is exposed outside synchronization

test: copy list to prevent ConcurrentModificationException

---

docs-md/concepts/schemas.md
docs-md/developer-guide/joins/partition-data.md
docs-md/developer-guide/ksqldb-reference/print.md
docs-md/developer-guide/ksqldb-reference/select-push-query.md

This PR copies over the new serialization content from PR #4478 that belongs in v0.7.0 docs, which are published out of the `5.5.x` branch (for tools support). The content that hasn't been copied stays in `master` and will be published in v0.8.0.

docs: copy new serialization content to 5.5.x branch (DOCS-3399)

---

ksql-api/src/test/java/io/confluent/ksql/api/ApiTest.java

We saw a flaky failure of `ApiTest#shouldStreamInserts()` at the following assertion: https://github.com/confluentinc/ksql/blob/75bf29aa5582849f229d8effad87e5fa8362993f/ksql-api/src/test/java/io/confluent/ksql/api/ApiTest.java#L552
This PR attempts to fix the flakiness by switching to `assertThatEventually`, since `InsertSubscriber` methods are async. The corresponding changes are made in a couple other tests as well.
Will wait to get a clean build once Jenkins is unblocked.

test: fix flaky insert API tests (MINOR)

---

ksql-engine/src/test/java/io/confluent/ksql/util/ItemDataProvider.java
ksql-engine/src/test/java/io/confluent/ksql/util/OrderDataProvider.java
ksql-engine/src/test/java/io/confluent/ksql/util/PageViewDataProvider.java
ksql-engine/src/test/java/io/confluent/ksql/util/UserDataProvider.java

Tests that rely on the `TestDataProvider`s assume the provided data are ordered according to the order specified in the data providers, but this guarantee is not provided by `HashMap`. This leads to flaky failures such as this one from `5.2.x`:
```
testInsertIntoAvro
A test failure has occurred at Tue Feb 11 20:21:01 2020 UTC.
Module: io.confluent.ksql.integration.StreamsSelectAndProjectIntTest
org.junit.ComparisonFailure: expected:<ITEM_[1]> but was:<ITEM_[2]>
at io.confluent.ksql.integration.StreamsSelectAndProjectIntTest.testInsertIntoAvro(StreamsSelectAndProjectIntTest.java:381)
```
where the test was expecting the first record to be `ITEM_1` but received `ITEM_2` instead.
This PR fixes such flaky failures by switching to a map implementation that does guarantee order.
`mvn package`

test: data providers should be ordered (MINOR)

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java

We've seen three flaky failures for the test `RestApiTest#shouldExecutePushQueryOverRest` over the past two days, each with the following stacktrace:
```
java.lang.AssertionError: 
Expected: is "{\"finalMessage\":\"Limit Reached\"}]"
but: was ""
at io.confluent.ksql.rest.integration.RestApiTest.shouldExecutePushQueryOverRest(RestApiTest.java:234)
```
The [test](https://github.com/confluentinc/ksql/blob/31e75acb161f82e8ea14babed0acfe80b604bee0/ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java#L220) issues a push query with `LIMIT` clause to the HTTP streaming endpoint and expects four rows to be returned: a header row, two rows of data, and a footer indicating that the limit has been reached. The test first parses the JSON response to check that four rows are …

test: fix flaky RestApiTest#shouldExecutePushQueryOverRest (MINOR)

---

ksql-udf-quickstart/src/main/resources/archetype-resources/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java

Test depends on timezone, so was failing in US.

test: fix timezone issue in `RecordFormatterTest`

---

CONTRIBUTING.md

The command we instruct contributors to use for testing local builds fails as of 2559b2fd, which added the `ksql-docker` project.
`mvn clean install checkstyle:check integration-test`
This fails with:
`Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.0.2:jar (default-jar) on project ksql-docker: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them`
[The below is copied from a similar change in an internal project]
I believe there are two factors leading to the error. The first is addressed by this PR. The second, related factor explains why the command was working until the `ksql-docker `project was added.
Including both the `install` and `integration-test` commands causes the `package` phase to execute twice. This …

chore: update contributing test command

---

ksql-docker/pom.xml

Dependencies required by `ksql-test-runner` are not present in the artifacts copied to Docker images. cf. #4584 
I built the Docker image locally via
`mvn -Pdocker package -pl ksql-docker -DskipTests -Dspotbugs.skip -Dcheckstyle.skip -Ddockerfile.skip=false -Dskip.docker.build=false -Ddocker.upstream-tag=master-latest -Ddocker.tag=local.build -Ddocker.upstream-registry='368821881613.dkr.ecr.us-west-2.amazonaws.com/'`
Then I ran the repro steps in #4584, using the `placeholder/confluentinc/ksql-docker:local.build` image built above.
The reported exception was not thrown.

fix: add functional-test dependencies to Docker module

---

ksql-functional-tests/src/test/java/io/confluent/ksql/test/QueryTranslationTest.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestLoader.java

Switch QTT around so that it always runs the tests against the latest version first, then looks to test against historic versions.
Why? When running locally to test changes it makes more sense, to me at least!, to test that current functionality works as expected before testing to ensure there is no backwards compatibility issues.  Though I appreciate this could be a person thing.

test: run latest QTT tests first

---

ksql-api/src/main/java/io/confluent/ksql/api/impl/Utils.java
ksql-api/src/main/java/io/confluent/ksql/api/plugin/BlockingQueryPublisher.java
ksql-api/src/main/java/io/confluent/ksql/api/plugin/KsqlServerEndpoints.java
ksql-api/src/main/java/io/confluent/ksql/api/plugin/PullQueryPublisher.java
ksql-api/src/main/java/io/confluent/ksql/api/server/ApiServerConfig.java
ksql-api/src/main/java/io/confluent/ksql/api/server/BasePublisher.java
ksql-api/src/main/java/io/confluent/ksql/api/server/ConnectionQueryManager.java
ksql-api/src/main/java/io/confluent/ksql/api/server/ErrorCodes.java
ksql-api/src/main/java/io/confluent/ksql/api/server/InsertsStreamHandler.java
ksql-api/src/main/java/io/confluent/ksql/api/server/PushQueryHolder.java
ksql-api/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java
ksql-api/src/main/java/io/confluent/ksql/api/server/Server.java
ksql-api/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksql-api/src/main/java/io/confluent/ksql/api/server/protocol/QueryResponseMetadata.java
ksql-api/src/main/java/io/confluent/ksql/api/spi/QueryPublisher.java
ksql-api/src/test/java/io/confluent/ksql/api/ApiServerConfigTest.java
ksql-api/src/test/java/io/confluent/ksql/api/ApiTest.java
ksql-api/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksql-api/src/test/java/io/confluent/ksql/api/MaxQueriesTest.java
ksql-api/src/test/java/io/confluent/ksql/api/TestQueryPublisher.java
ksql-common/src/main/java/io/confluent/ksql/configdef/ConfigValidators.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/ApiIntegrationTest.java

Provides an upper limit on the number of push queries that can be running in the server at any one time.
Push queries are expensive as they own their own Kafka streams topology and associated threads. We can't have too many in the server at once.
Added new test

feat: Provide upper limit on number of push queries

---

ksql-api/src/main/java/io/confluent/ksql/api/plugin/BlockingQueryPublisher.java
ksql-api/src/main/java/io/confluent/ksql/api/plugin/InsertsSubscriber.java
ksql-api/src/main/java/io/confluent/ksql/api/plugin/KsqlServerEndpoints.java
ksql-api/src/main/java/io/confluent/ksql/api/server/AcksSubscriber.java
ksql-api/src/main/java/io/confluent/ksql/api/server/BufferedPublisher.java
ksql-api/src/main/java/io/confluent/ksql/api/server/PushQueryHandle.java
ksql-api/src/main/java/io/confluent/ksql/api/server/QuerySubscriber.java
ksql-api/src/test/java/io/confluent/ksql/api/perf/BasePerfRunner.java
ksql-api/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java
ksql-api/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksql-api/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksql-api/src/test/java/io/confluent/ksql/api/perf/RunnerUtils.java
ksql-api/src/test/java/io/confluent/ksql/api/plugin/BlockingQueryPublisherTest.java
ksql-api/src/test/java/io/confluent/ksql/api/tck/BlockingQueryPublisherVerificationTest.java

Implements https://github.com/confluentinc/ksql/issues/4279
This is a stacked PR so please just review commits from "perf runner" and later
This PR introduces a simple perf tool for rough perf testing of our new API.
It's a simple tool that does not pretend to be perfect or a general purpose performance tool, but it's really useful for quickly running some tests in your IDE to get a rough idea of the overhead of the new API machinery. This can be used as first pass for tuning the server.
There's a base class called PerfRunner where all the magic happens. Then you subclass this for your particular test.
The PR also contains some changes to various buffer sizes and the like, tuned by running this perf tool.

feat: Simple perf tool for new API

---

ksql-api/src/main/java/io/confluent/ksql/api/server/Server.java
ksql-api/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksql-api/src/test/java/io/confluent/ksql/api/ApiTest.java
ksql-api/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksql-api/src/test/java/io/confluent/ksql/api/TlsTest.java

To avoid bind exceptions, test servers should use available server port.

fix: Tests should use free port for servers

---

ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksql-execution/src/main/java/io/confluent/ksql/execution/util/EngineProcessingLogMessageFactory.java
ksql-execution/src/test/java/io/confluent/ksql/execution/util/EngineProcessingLogMessageFactoryTest.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/GroupByParamsFactory.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StepSchemaResolver.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/StreamGroupByBuilder.java
ksql-streams/src/main/java/io/confluent/ksql/execution/streams/TableGroupByBuilder.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/GroupByParamsFactoryTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/StreamGroupByBuilderTest.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/TableGroupByBuilderTest.java

Logs errors in groupby to the processing logger.
Added unit tests for the group by mappers to ensure they log correctly.

feat: log groupby errors to processing logger

---

ksql-common/src/main/java/io/confluent/ksql/logging/processing/ProcessingLogMessageSchema.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/ProcessingLogServerUtilsTest.java
ksql-serde/src/main/java/io/confluent/ksql/logging/processing/LoggingDeserializer.java
ksql-serde/src/main/java/io/confluent/ksql/serde/util/SerdeProcessingLogMessageFactory.java
ksql-serde/src/test/java/io/confluent/ksql/logging/processing/LoggingDeserializerTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/util/SerdeProcessingLogMessageFactoryTest.java

Adds the topic name to deserialization error processing log messages

feat: add the topic name to deserialization errors

---

ksql-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java
ksql-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStoreTest.java

StoreQueryParams was renamed to StoreQueryParameters in Kafka Streams which broke the build.
This fixes it.

fix: StoreQueryParameters name change

---

ksql-rest-app/src/test/java/io/confluent/ksql/api/perf/BasePerfRunner.java
ksql-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java
ksql-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksql-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksql-rest-app/src/test/java/io/confluent/ksql/api/perf/RunnerUtils.java

I somehow managed to remove all the perfrunner classes in the recent move of the ksql-api package.
This adds them back in. They were already approved in https://github.com/confluentinc/ksql/pull/4590

chore: Add perfrunner classes back in that got lost

---

ksql-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksql-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-serde/src/main/java/io/confluent/ksql/serde/avro/KsqlAvroSerdeFactory.java
ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroDeserializerTest.java
ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroSerializerTest.java

These code bits are about to be deprecated so we're proactively stopping to use them.

chore: remove soon to be deprecated usage of schemaregistry (MINOR)

---

ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/KafkaStreamsInternalTopicsAccessor.java

Master broke because the internals of the Kafka Streams TopologyTestDriver class changed and we rely on internal fields in our class KafkaStreamsInternalTopicsAccessor.
I have put a band-aid on it for now, but we should find a better way of doing this that does not rely on private fields of dependencies.

fix: patch KafkaStreamsInternalTopicsAccessor as KS internals changed

---

ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatter.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java

fixes #4516 
Adds support for `PRINT TOPIC` for protobuf topics
Unit testing and manual:
```
ksql> PRINT print_proto FROM BEGINNING;
Key format: UNDEFINED
Value format: PROTOBUF
rowtime: 2/19/20 9:40:02 AM PST, key: <null>, value: COL1: "a" COL2: 2 COL3: "c"
^CTopic printing ceased
```

chore: support PROTOBUF for PRINT TOPIC

---

ksql-cli/src/main/java/io/confluent/ksql/cli/console/CliConfig.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/util/TabularRow.java
ksql-cli/src/test/java/io/confluent/ksql/util/TabularRowTest.java

Allow column width to be explicitly specified in tabular cli output. By default, column width is determined based on the terminal width and the number of columns. With these changes, the width of each column may be optionally overridden:
```
ksql> SET CLI COLUMN-WIDTH 10
```
Given a customized value, subsequent renderings of output use the setting:
```
ksql> SELECT * FROM riderLocations
>  WHERE GEO_DISTANCE(latitude, longitude, 37.4133, -122.1162) <= 5 EMIT CHANGES;
+----------+----------+----------+----------+----------+
|ROWTIME   |ROWKEY    |PROFILEID |LATITUDE  |LONGITUDE |
+----------+----------+----------+----------+----------+
```
The default behavior can be re-enabled using:
```
ksql> SET CLI COLUMN-WIDTH 0
```
Existing and added unit tests
Built Docker image and smoke tested …

feat: support custom column widths in cli

---

pom.xml

Streams is a little unstable at the moment, so this patch pins our kafka and confluent dependencies
to the tip of the current _release_ branch (5.5.x). Kafka is in code-freeze right now, so this branch
should be pretty stable.

chore: pin confluent dependencies to last released version

---

ksql-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/JLineTerminal.java
ksql-cli/src/main/java/io/confluent/ksql/cli/console/KsqlTerminal.java
ksql-cli/src/test/java/io/confluent/ksql/TestTerminal.java

Simply renders error messages displayed in the CLI in red (see #892 ). 
@rmoff - this is for you ;-)

feat: display errors in CLI in red text

---

ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorTest.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/KafkaStreamsInternalTopicsAccessor.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/PlannedTestGeneratorTest.java
ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_value_elements_OK_-_AVRO/6.0.0_1582711670275/plan.json
ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_value_elements_OK_-_AVRO/6.0.0_1582711670275/spec.json
ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_value_elements_OK_-_AVRO/6.0.0_1582711670275/topology
ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_value_elements_OK_-_JSON_SCHEMA/6.0.0_1582711670325/plan.json
ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_value_elements_OK_-_JSON_SCHEMA/6.0.0_1582711670325/spec.json
ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_value_elements_OK_-_JSON_SCHEMA/6.0.0_1582711670325/topology
ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_value_elements_OK_-_PROTOBUF/6.0.0_1582711670295/plan.json
ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_value_elements_OK_-_PROTOBUF/6.0.0_1582711670295/spec.json
ksql-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_value_elements_OK_-_PROTOBUF/6.0.0_1582711670295/topology
ksql-functional-tests/src/test/resources/historical_plans/elements_-_with_invalid_or_reserved_words_in_schema_-_JSON/6.0.0_1582711670237/plan.json
ksql-functional-tests/src/test/resources/historical_plans/elements_-_with_invalid_or_reserved_words_in_schema_-_JSON/6.0.0_1582711670237/spec.json
ksql-functional-tests/src/test/resources/historical_plans/elements_-_with_invalid_or_reserved_words_in_schema_-_JSON/6.0.0_1582711670237/topology
ksql-functional-tests/src/test/resources/query-validation-tests/elements.json

fixes: https://github.com/confluentinc/ksql/issues/4566
With this change users can now supply just the key schema and use schema inference to get the value columns. For example, if the key is an `INT` serialized using Kafka's `IntegerSerializer` and the value is an Avro record with the schema stored in the Scheme Registry, then such a stream can be registered in ksqlDB with a statement such as:
```sql
-- note: only the key columns are provided between the first set of brackets
-- the value columns will be inferred from the Avro schema in the Schema Registry
CREATE STREAM users (ROWKEY INT KET) WITH (kafka_topic='users', value_format='avro');
```
QTT tests added.

fix: support partial schemas

---

ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java

Fixes a couple issues with terminate:
- don't throw if the query doesn't get into NOT_RUNNING state. This can
happen when streams threads are stuck pending shutdown.
- make terminate idempotent

fix: idempotent terminate that can handle hung streams

---

ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/TransientQueryMetadataTest.java

Co-authored-by: Rohan <desai.p.rohan@gmail.com>
fixes #4654
See the description in the ticket above. This makes it so that we don't cleanup topics for persistent queries on closing the engine (but we do for transient).
- Unit tests
- Manual testing to ensure we can't reproduce the bug.

fix: don't cleanup topics on engine close

---

ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java

Fixes #4639
StreamsMetadata exposes the internal list which can change while iterating over it resulting in a concurrent modification exception. I create an immutable copy of it.
Unfortunately, I cannot reproduce this bug locally.

fix: Return immutable list of streams metadata

---

ksql-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java
ksql-engine/src/test/java/io/confluent/ksql/util/TransientQueryMetadataTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java

fix: backport fixes from query close

---

config/ksql-production-server.properties
config/ksql-server.properties
ksql-cli/src/main/java/io/confluent/ksql/cli/console/cmd/Help.java
ksql-cli/src/test/java/io/confluent/ksql/cli/console/cmd/RemoteServerSpecificCommandTest.java
ksql-common/src/main/java/io/confluent/ksql/links/DocumentationLinks.java
ksql-engine/src/main/java/io/confluent/ksql/services/KafkaClusterUtil.java
ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java

Logged error was:
```
...
Caused by: io.confluent.ksql.util.KsqlServerException: Could not get Kafka cluster configuration!
at io.confluent.ksql.services.KafkaClusterUtil.getConfig(KafkaClusterUtil.java:77)
at io.confluent.ksql.services.KafkaTopicClientImpl.getConfig(KafkaTopicClientImpl.java:309)
at io.confluent.ksql.services.KafkaTopicClientImpl.isTopicDeleteEnabled(KafkaTopicClientImpl.java:298)
... 21 more
Caused by: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
```
and is now:
```
...
Caused by: io.confluent.ksql.util.KsqlServerException: Could not get Kafka cluster configuration. Please ensure the ksql principal has DESCRIBE_CONFIGS rights on the Kafka cluster.
See https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/server-co …
```

chore: better error when missing DESCRIBE_CONFIGS acl

---

Jenkinsfile

For ksql-db-release job parameters, currently any GIT_REVISION is ignored unless RELEASE_BUILD is true. For pre-release validation, we should be able to run a non-release job at a given sha. The principal thing we want to avoid is creating an unnecessary tag, which happens when RELEASE_BUILD is true.
This PR allows the provided revision to also be used when RELEASE_BUILD is false.

chore: if provided, always use revision param in CI release job

---

CHANGELOG.md

* The referenced tag does not actually exist yet. I will be pushed once we finalize the release and push the Docker images to Docker Hub.
* I targeted master because 5.5.x lacks the commit for the `0.7.0` changelog additions. I figure we can cherry-pick that commit and the squash for this PR into 5.5.x.

chore: update CHANGELOG for 0.7.1

---

Jenkinsfile

Prepares the CI release build for the next version. This does not actually create the release.

chore: bump release version to 0.7.1-SNAPSHOT

---

ksql-engine/src/main/java/io/confluent/ksql/function/udf/json/JsonArrayContains.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/ConfigTopicKeyTest.java

This is to allow an upgrade to Jackson 2.10.x

chore: Remove use of deprecated Jackson API

---

ksql-benchmark/src/main/resources/log4j.properties
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksql-test-util/src/main/resources/log4j.properties

This change improves the error message returned by the testing tool & QTT when a test case is expected to throw an exception but doesn't.
Old message was:
```
java.lang.AssertionError: test did not generate any queries.
Expected: is not an empty collection
but: was <[]>
failed test: key-schemas - KEY key field name
in file: query-validation-tests/key-schemas.json
```
New message is:
```
java.lang.AssertionError: Expected test to throw(an instance of io.confluent.ksql.util.KsqlStatementException and statement text a string containing "CREATE STREAM INPUT (KEY STRING KEY, ID bigint) WITH (kafka_topic='input',value_format='JSON');" and exception with message a string containing "'KEY' is an invalid KEY column name. KSQL currently only supports KEY columns named ROWKEY.")
failed test: …
```

test: improve error msg & remove log spam (MINOR)

---

ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestCase.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestCaseBuilder.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestCaseNode.java
ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java

RQTT test cases can now have a properties section, just like QTT test cases, e.g.
```json
"properties": {
"ksql.some.thing": "whateva"
}
```

test: extend RQTT to support properties (MINOR)

---

ksql-common/src/main/java/io/confluent/ksql/properties/with/CreateConfigs.java
ksql-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceProperties.java
ksql-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourcePropertiesTest.java

Our use of query plans means we no longer need this...
`AVRO_SCHEMA_ID` is still likely to be baked into sql statement of query plans held within the command topic of existing cluster, as it is also backed in the historic plans in our QTT tests. 
However, it is never parsed.  The whole point of the plan is that we can change our syntax and not need to maintain backwards compatibility of the syntax!
`mvn test`

chore: remove legacy AVRO_SCHEMA_ID

---

ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksql-functional-tests/src/test/resources/query-validation-tests/timestamp-extractor.json

Re-enabling this test after allowing tests to continue past building the queries even if an expected exception is present in the case that it has defined input records.
Ran the test

test: enable the timestamp format failure test

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/DistributingExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

If you kill the commandRunner thread and then issue a control statement, we'll fail to enqueue the statement because the commandRunner hasn't caught up to the command topic. The error is not great because `CommandStore.waitForCommandConsumer()` is returning a `KsqlRestException` which doesn't have an error message associated with it, which results in this
```
ksql> create stream foo8(age BIGINT) with (Kafka_Topic='foo', VALUE_FORMAT='json');
Could not write the statement 'create stream foo8(age BIGINT) with (Kafka_Topic='foo', VALUE_FORMAT='json');' into the command topic: null
Caused by: io.confluent.ksql.rest.server.resources.KsqlRestException
```
Changing the error thrown to `KsqlServerException` so the error message can get displayed.
_Describe the testing strategy. Unit and …

fix: fix the error message for failing to wait for CommandRunner to catch up in DistributingExecutor

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatter.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java

fixes #4555 by adding support for `JSON_SR` in the print topic format detection
unit tests, end-to-end testing:
```
ksql> print jsonsr from beginning;
Key format: ...
Value format: JSON_SR or KAFKA_STRING
rowtime: 3/4/20 2:34:43 PM PST, key: <null>, value: {"FOO":"123","BAR":123}
```

chore: add print topic support for JSON_SR

---

ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java

Fixes an NPE when a user accidentally uses an input topic name in the output records section of a test case, e.g.
```json
{
"name": "ooops - cut & paste error",
"CREATE STREAM INPUT (a DECIMAL(4,2), b DOUBLE) WITH (kafka_topic='input', value_format='AVRO');",
"CREATE STREAM OUTPUT AS SELECT (a + b) AS RESULT FROM INPUT;"
],
"inputs": [
{"topic": "input", "key": "0", "value": {"A": "10.01", "B":  5.1}}
],
"outputs": [
{"topic": "input", "key": "0", "value": {"RESULT": 15.11}},
{"topic": "TEST2", "key": "0", "value": {"RESULT": 5.01}},
{"topic": "TEST2", "key": "0", "value": {"RESULT": 10.01}}
]
}
```
Note: the reference to `input` in the `outputs`? This was causing an NPE. It now causes an error along the lines of:
```
Topic `input`: expected 1 message, got 0.
```
Usual

test: avoid NPE if user puts input topic name in output

---

ksql-engine/src/main/java/io/confluent/ksql/function/udf/array/ArrayLength.java
ksql-engine/src/test/java/io/confluent/ksql/function/udf/array/ArrayLengthTest.java
ksql-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_primitives/6.0.0_1583509764019/plan.json
ksql-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_primitives/6.0.0_1583509764019/spec.json
ksql-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_primitives/6.0.0_1583509764019/topology
ksql-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_structured/6.0.0_1583509764141/plan.json
ksql-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_structured/6.0.0_1583509764141/spec.json
ksql-functional-tests/src/test/resources/historical_plans/array_-_array_length_-_structured/6.0.0_1583509764141/topology
ksql-functional-tests/src/test/resources/query-validation-tests/array.json

fixes: https://github.com/confluentinc/ksql/issues/4724
`ARRAY_LENGTH` returns the length of any array passed to it, or `0` if null is passed.
Note, postgres's version takes a second `INT` parameter, which identifies which dimension to measure.  The ksql version does not support this. It can be added later.
Do we want this in 5.5?  cc @apurvam @derekjn @MichaelDrogalis ?
Usual. Unit + QTT.

feat: add ARRAY_LENGTH UDF

---

ksql-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplIntegrationTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtils.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtilsTest.java

fixes: https://github.com/confluentinc/ksql/issues/4708
* Changed the code to only log about `Creating topic _confluent-ksql-4_command_topic with replication factor of 1 which is less than 2` if its actually creating to the command topic, otherwise log different message, (UX improvement)
* Fixed the code to not log `Corrected retention.ms on ksql internal topic. topic:_confluent-ksql-4_command_topic, retention.ms:9223372036854775807` when retention already correctly set, (bug fix).
The bug on the retention logging was that the code that checks to see if a change needs applying was comparing `Long.MAX_VALUE` with a String holding the same value.  Changed code to compare like for like.
* Refactored test to not use EasyMock while I was in there.
unit tests updated.

fix: stop logging about command topic creation on startup if exists (MINOR)

---

docker-compose.yml
docs-md/tutorials/embedded-connect.md
ksql-docker/Dockerfile
ksql-docker/README.md
ksql-docker/src/assembly/package.xml

Fixes https://github.com/confluentinc/ksql/issues/4558
This PR:
- adds `confluent-hub` to the ksqlDB docker image
- updates the embedded Connect tutorial to showcase the new usage
- moves instructions for building ksqlDB docker images into ksql-docker/README.md
- updates the instructions to use the publicly available base image, so community members can follow the instructions to build docker images as well
- updates some copy-paste vestiges of "ksql-rest-app" to "ksql-docker" where appropriate
Ran through the new version of the embedded Connect tutorial.

feat: add confluent-hub to ksqlDB docker image

---

ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksql-functional-tests/src/test/resources/historical_plans/elements_-_should_allow_ROWKEY_as_value_column/6.0.0_1583762137584/plan.json
ksql-functional-tests/src/test/resources/historical_plans/elements_-_should_allow_ROWKEY_as_value_column/6.0.0_1583762137584/spec.json
ksql-functional-tests/src/test/resources/historical_plans/elements_-_should_allow_ROWKEY_as_value_column/6.0.0_1583762137584/topology
ksql-functional-tests/src/test/resources/query-validation-tests/elements.json
ksql-functional-tests/src/test/resources/query-validation-tests/system-columns.json
ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java

With the work to allow key column names other than ROWKEY, suddenly `ROWKEY` is actually not a system column. It's just the default name of the key column. It shouldn't be treated any differently to any other key column name.
This change removes `ROWKEY` as a system column. This results in a few error messages changing, but little else.
Note: use of any key column name is still guarded by the `KsqlConfig.KSQL_ANY_KEY_NAME_ENABLED` feature flag.
usual

chore: do not reserve ROWKEY as system column name

---

ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/StreamedRow.java

Improve the error message reported by RQTT when the row count does not match to include the expected and actual rows. This should aid tracking down issues when tests fail on the build server.
Test only chage.

test: include rows in row count mismatch error message in RQTT

---

ksql-engine/src/main/java/io/confluent/ksql/connect/Connector.java
ksql-engine/src/main/java/io/confluent/ksql/connect/supported/JdbcSource.java
ksql-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksql-engine/src/test/java/io/confluent/ksql/connect/ConnectorTest.java
ksql-engine/src/test/java/io/confluent/ksql/connect/supported/JdbcSourceTest.java
ksql-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientTest.java
ksql-execution/src/main/java/io/confluent/ksql/services/ConnectClient.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutorTest.java

After KIP-558 and starting with Apache Kafka version 2.5, Kafka Connect adds a new 'topics' endpoint per connector to discover the set of topics a connector is using during runtime. Using this new endpoint will allow ksqlDB to get a more accurate view of a connector's active topics. The code is refactor to no longer depend on listing the topics with an adminclient when describing a connector in ksqlDB
Details on active topics tracking here: 
https://cwiki.apache.org/confluence/display/KAFKA/KIP-558%3A+Track+the+set+of+actively+used+topics+by+connectors+in+Kafka+Connect
Existing unit tests were adjusted to test the new functionality.

Use the new topics endpoint in Connect REST API to describe the topics of a connector

---

ksql-engine/pom.xml
ksql-version-metrics-client/pom.xml
pom.xml

After upgrading to junit 4.13, a lot of tests are failing because `junit#assertThat` and junit rule `ExpectedException` were deprecated. Disabling failing on warnings in tests, at least until the underlying issues are resolved.

build: disable -Werror compiler argument in tests

---

docs-md/concepts/processing-guarantees.md

Forgot to add this to the previous commit.

docs: add note about EOS semantics (KSQL-3721)

---

ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonSerializerTest.java

One of our serializers has a fix for correctly formatting decimals,
the other one doesnt. So update the json test cases to reflect this

fix: fix the half-fixed json decimal tests

---

bin/ksql-run-class
ksqldb-docker/Dockerfile

Two fixes to the Docker image:
- The directory that jars need to be copied to needs to be one of the jars that gets added to the classpath here: https://github.com/confluentinc/ksql/blob/bfc90e1df75eb026f444212d98a4399b314322a6/bin/ksql-run-class#L28 or else the server fails to start with `Error: Could not find or load main class io.confluent.ksql.rest.server.KsqlServerMain`. This PR undoes the change that updated the directory name from `ksql-rest-app` to `$ARTIFACT_ID` since the artifact ID is ksqldb-docker, which is not in the list.
- Our docker images place config files in `/etc/ksql` whereas ksql-run-class was recently updated to look for log4j configs in `/etc/ksqldb` instead, so server logs were not properly printed. This PR reverts the change to ksql-run-class for the sake of …

fix: docker image directories in light of renames (MINOR)

---

docs-md/concepts/functions.md
docs/developer-guide/udf.rst

Which doesn't exist. Replace with `@UdfSchemaProvider`, which does.

docs: fix reference to @SchemaProvider

---

docs-md/concepts/functions.md

The current example UDTF in our docs is broken since the class annotation is incorrect, as pointed by a user in the Community Slack: https://confluentcommunity.slack.com/archives/C6UJNMY67/p1584336800321900?thread_ts=1584180894.313000&cid=C6UJNMY67
This PR fixes the typo. Targeting the `0.7.1-docs` branch under the assumption that this branch is the one that's currently live in the docs, but this fix also needs to be ported around to the other branches (master, 5.5.x, probably also 5.4.x) -- @JimGalasyn would you mind helping with that? (Thanks in advance!)
UPDATE: Targeting `master` in light of review comment below.

docs: fix annotation in UDTF example (MINOR)

---

docs-md/concepts/time-and-windows-in-ksqldb-queries.md

Updates the example for configuring windowed aggregation retention period to be a persistent query, since window retention doesn't really make sense for transient queries. The rest of the examples in the file are still transient queries so there's a bit of an inconsistency here but I think this is still an improvement.

docs: update window retention example to be persistent (MINOR)

---

docs-md/developer-guide/ksqldb-reference/aggregate-functions.md
docs/developer-guide/syntax-reference.rst
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafLoader.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/latest/LatestByOffset.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/latest/LatestByOffsetUdafTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_latest_by_offset/6.0.0_1584458743188/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_latest_by_offset/6.0.0_1584458743188/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_latest_by_offset/6.0.0_1584458743188/topology
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_latest_by_offset_with_nulls/6.0.0_1584458743310/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_latest_by_offset_with_nulls/6.0.0_1584458743310/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_latest_by_offset_with_nulls/6.0.0_1584458743310/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/latest-offset-udaf.json

Please see https://github.com/confluentinc/ksql/issues/3985
Implements latest_by_offset() UDAF which computes the latest value for a column. Latest being defined as offset order.
Added new unit test and QTT test

feat: Implement latest_by_offset() UDAF

---

bin/ksql-run-class
ksqldb-docker/Dockerfile

Undoes the second change in https://github.com/confluentinc/ksql/pull/4785 in favor of fixing forward since we'd like the config directory to be named `ksqldb` rather than `ksql`. @agavra will take care of making the analogous update for CP docker images and updating docs to reference the new directory.
Built local image and verified server logging works as expected.

chore: rename config directory to ksqldb (MINOR)

---

docs-md/developer-guide/ksqldb-reference/create-stream-as-select.md
docs-md/developer-guide/ksqldb-reference/insert-into.md
docs-md/developer-guide/syntax-reference.md
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_join/6.0.0_1584453227211/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_join/6.0.0_1584453227211/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_join/6.0.0_1584453227211/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/insert-into.json

Improve the docs to make it clear that, like GROUP BY, any PARTITION BY clause is applied after any JOIN or WHERE, but before the SELECT.
Also, include optional JOIN clause in INSERT INTO docs, as joins are supported, (QTT test added to prove this).
Doc only change.

docs: call out PARTITION BY applied before SELECT

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java

https://github.com/confluentinc/ksql/issues/4788
Issue a `list streams;` request to the server first in order to see if the processing log stream is already present or not
Unit test
Started up server back to back and the exception doesn't show up anymore

fix: only create processing log stream if it doesn't exist

---

ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/Errors.java

Return a more specific error code on shutdown.
BREAKING CHANGE: return a 50303 in the error code msg (instead of 50300) for shutdown errors

fix: better error code on shutdown

---

Jenkinsfile

This will delete all of the docker images on the jenkins node after building. If we don't do this and only cleanup the CP images then we never pull down the latest version of the base os image. This issue may never really affect this builds, but better to be safe and just delete everything. Also, leaving images on the machine after this builds could affect other builds.
This has been tested with building the CP images.

build: ST-3227: Cleanup up all docker images after building

---

CHANGELOG.md

docs: add changelog for 0.8.0 release

---

ksqldb-common/src/main/java/io/confluent/ksql/json/KsqlTypesSerializationModule.java
ksqldb-common/src/main/java/io/confluent/ksql/json/SqlTypeSchemaSerializer.java
ksqldb-engine/src/test/java/io/confluent/ksql/execution/json/PlanJsonMapperTest.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/json/KsqlTypesDeserializationModule.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/json/SqlTypeDeserializer.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/json/KsqlTypesSerdeModuleTest.java

Add SerDe for the `SqlType` which is used in `RegisterTypeCommand`. Without this the command topic was able to serialize, but not deserialize, that type of command.
Locally registered types. We need to add QTT tests for this and other tests, but I'm posting the PR to get early reviews.

fix: add deserializer for SqlType

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlRequestConfig.java
ksqldb-common/src/test/java/io/confluent/ksql/util/KsqlRestConfigTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PropertyExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/PropertyOverriderTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/SessionProperties.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/KsqlRequestTest.java

Breaking up https://github.com/confluentinc/ksql/pull/4572 into smaller PR's
This PR adds an isInteralRequest flag to both KsqlRequestConfig and SessionProperties for use in any future scatter gather patterns among cluster servers.
Unit tests

feat: add internal request to KsqlRequestConfig and SessionProperties

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgent.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/HealthCheckResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgentTest.java

Use a faster connectivity check for Kafka health check. The new approach uses the describeTopics() call to get metadata information from the KSQL command topic. If the describe does not fail, then Kafka is considered healthy.
Unit tests
Manual test
Healthy
```
sergio@pop-os:~/Development/ksql$ curl -X "GET" "http://localhost:8088/healthcheck" -H "Content-Type: application/vnd.ksql.v1+json; charset=utf-8" | jq .
{
"isHealthy": true,
"details": {
"metastore": {
"isHealthy": true
},
"kafka": {
"isHealthy": true
}
}
}
```
Kafka not healthy
```
$ curl -X "GET" "http://localhost:8088/healthcheck" -H "Content-Type: …
```

feat: use describeTopics() for Kafka healtcheck probe

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerStatusMetricTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java

Fixes: https://github.com/confluentinc/ksql/issues/4652
Add a new variable to CommandRunner that keeps track of the last time the command topic was polled. If there's too long of a duration between the current time when `CommandRunner.checkCommandRunnerStatus` is called and the last poll, that means the thread is in `ERROR` state.
Killed the command runner thread and watched the metric. It transitioned to error state after 15 seconds.

fix: CommandRunner metric has correct metric displayed when thread dies

---

docs-md/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/nulls/Coalesce.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/IfNullKudf.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/nulls/CoalesceTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/null.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json

The `COALESCE` function takes one or more parameters and returns the first that is non-null.
All parameters must be of the same type.
This function supersedes the existing `IFNULL` function, which only worked for strings and one accepted two parameters.
Note: also added docs for the `ARRAY_LENGH` I added recently, as I seemed to of missed adding docs!
QTT + unit tests added.

feat: add COALESCE function

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java

fixes: https://github.com/confluentinc/ksql/issues/4852
If processing data with NULL key or values, (generally keys), then PRINT TOPIC would output a long list of possible formats for the key, i.e. ALL the possible formats for the key.  This isn't really very useful.
The cause was that no data had been processed, so no formats had been rejected.
This commit changes the behaviour in the situation where no data has been processed to output a shorter message, for example:
```
ksql> print Topic_with_null_keys from beginning;
Key format: ¯\_(ツ)_/¯ - no data processed
Value format: JSON or KAFKA_STRING
rowtime: 23/03/20 12:45:33 GMT, key: <null>, value: {"NAME": "bob"}
```
Unit tests updated + manual testing.

fix: avoid long possible format lists on PRINT TOPIC for nulls

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ClusterStatusResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/ClusterStatusResourceTest.java

Currently, ClusterStatusResource returns the last received lags, even for dead hosts.  This change ensures we only show lags for living hosts.
#4833 

fix: Returns empty lag info for a dead host rather than last received lags

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/HighAvailabilityTestUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/MaximumLagFilterTest.java

Previously, this would include hosts with no lag information.  This reverses that.  This means that there will be a couple seconds of downtime for a host when it starts up.  We're taking other efforst to fix this.
Also, makes PullQueryRoutingFunctionalTest more reliable by waiting on the lag report request to finish.

fix: Filter out hosts with no lag info by default

---

Jenkinsfile

This fixes an issue discovered by @vcrfxia in which she found that the config.isPrJob variable was not being set or available in the job method so all of the logic based on that config variable being present was not working as expected. It turns out that none of the config variables that get set during jobConfig were available.
Due to my misunderstanding of the variable scope the final config object was not available in the job method. The config object does not get passed to the job method via runJob. It is actually referencing it directly from the Jenkinsfile. So all of the calls in the job method to config were actually referencing the original declaration of that object and not what was returned after jobConfig processed all the configs. This is because the variable name used for the …

build: Fix for config object not being referenced correctly in the job method.

---

ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/DropSourceFactoryTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/ddl/commands/DropSourceCommand.java
ksqldb-functional-tests/src/test/resources/historical_plans/drop_source_-_drop_an_existing_stream_should_succeed/6.0.0_1585158673084/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/drop_source_-_drop_an_existing_stream_should_succeed/6.0.0_1585158673084/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/drop_source_-_drop_an_existing_stream_should_succeed/6.0.0_1585158673084/topology
ksqldb-functional-tests/src/test/resources/historical_plans/drop_source_-_drop_if_exists_a_non-existing_stream_should_succeed/6.0.0_1585158673119/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/drop_source_-_drop_if_exists_a_non-existing_stream_should_succeed/6.0.0_1585158673119/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/drop_source_-_drop_if_exists_a_non-existing_stream_should_succeed/6.0.0_1585158673119/topology
ksqldb-functional-tests/src/test/resources/historical_plans/drop_source_-_drop_if_exists_an_existing_stream_should_succeed/6.0.0_1585158673144/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/drop_source_-_drop_if_exists_an_existing_stream_should_succeed/6.0.0_1585158673144/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/drop_source_-_drop_if_exists_an_existing_stream_should_succeed/6.0.0_1585158673144/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/drop_source.json
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

Fixes https://github.com/confluentinc/ksql/issues/4473
`DROP STREAM <stream>` should **fail** if <stream> does not exist. 
`DROP STREAM IF EXISTS <stream>` should **succeed** if <stream> does not exist. 
Verified manually
```
$ curl -X POST http://localhost:8088/ksql \
>      -H "Content-Type: application/vnd.ksql.v1+json; charset=utf-8" \
>      -d @<(cat <<EOF
> {
>   "ksql": "drop stream if exists test;",
>   "streamsProperties": {}
> }
> EOF
> )
[{"@type":"currentStatus","statementText":"drop stream if exists test;","commandId":"stream/TEST/drop","commandStatus":{"status":"SUCCESS","me …
```

fix: 'drop (stream|table) if exists' fails if source does not exist

---

ksqldb-common/src/main/java/io/confluent/ksql/util/RetryUtil.java
ksqldb-common/src/test/java/io/confluent/ksql/util/RetryUtilTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java

Often when the server is starting up, it waits for preconditions to be met.  If the preconditions can't be met, it tries indefinitely.  If the server shuts down, the JVM will not stop due to this unending preconditions effort.
This change allows the preconditions to be interrupted during shutdown so that the application and JVM exit properly. 
Fixes #4779 
`mvn package`

fix: If startup hangs (esp on preconditions), shutdown server correctly

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslClientAuthFunctionalTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslFunctionalTest.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientTest.java

This PR builds on top of https://github.com/confluentinc/ksql/pull/4891, which attempts to fix https://github.com/confluentinc/ksql/issues/4885.
The changes in https://github.com/confluentinc/ksql/pull/4891 reveal another bug:
The client props passed by the CLI to the rest client come from: https://github.com/confluentinc/ksql/blob/b0669a044b53407fba3ceb11bddee73e69c0006f/ksqldb-cli/src/main/java/io/confluent/ksql/Ksql.java#L124 and are immutable: https://github.com/confluentinc/ksql/blob/b0669a044b53407fba3ceb11bddee73e69c0006f/ksqldb-common/src/main/java/io/confluent/ksql/properties/PropertiesUtil.java#L95 which means a `java.lang.UnsupportedOperationException` is thrown when the code tries to execute
```
clientProps.put(KsqlClient.TLS_ENABLED_PROP_NAME, "true");
```
as in …

fix: Infer TLS based on scheme of server string

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/ImmutableAnalysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/RewrittenAnalysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/DataSourceExtractor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/StatementRewriter.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/topic/SourceTopicsExtractor.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/StatementRewriterTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultTraversalVisitor.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/Join.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/JoinedSource.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/JoinMatchers.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/JoinTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/JoinedSourceTest.java

fixes #1612
Simply adds the syntax for multi-way joins, but still fails if users try to use it. The message, however, is now clearer:
```
Invalid join criteria specified; KSQL does not support multi-way joins.
```
All existing tests pass, and I added a unit and QTT test to make sure that the new message is returned in the case of a multi-way join.

chore: add syntax for multi-way joins

---

ksqldb-common/src/main/java/io/confluent/ksql/util/timestamp/StringToTimestampParser.java
ksqldb-common/src/test/java/io/confluent/ksql/util/timestamp/StringToTimestampParserTest.java

fixes #4864, in a localized way, added a unit test case
unit tests, also tested using an end-end example with some sample data containing leap days

fix: handle leap days correctly during timestamp extraction

---

ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksql-engine/src/main/java/io/confluent/ksql/util/QueuedQueryMetadata.java
ksql-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java

Like https://github.com/confluentinc/ksql/pull/4819/files but for 5.1
Backports these fixes
https://github.com/confluentinc/ksql/pull/4643
https://github.com/confluentinc/ksql/pull/4658
I don't think it's possible to backport the KsqlEngineTest since 5.1.x is when it was still using EasyMock, so there's no `Spy` option for the `topicClient`.

fix: don't cleanup topics on engine close (#4658)

---

docs-md/concepts/ksqldb-and-kafka-streams.md
docs-md/concepts/ksqldb-architecture.md
docs-md/operate-and-deploy/capacity-planning.md
docs-md/operate-and-deploy/installation/install-ksqldb-with-docker.md

We're trying to consolidate headless and interactive mode. For a while, we've started to recommend switching to interactive mode to take advantage of pull queries. We should make this our official recommendation to stop contradicting ourselves in the docs.

docs: stop recommending headless mode

---

bin/ksql

Starting up ksql in the 5.5.x packages causes the following if the base dir isn't properly set:
```
log4j:ERROR Could not read configuration file from URL [file:/etc/ksql/log4j-file.properties].
java.io.FileNotFoundException: /etc/ksql/log4j-file.properties (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at java.io.FileInputStream.<init>(FileInputStream.java:93)
at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
at …
```

fix: rename ksqldb in normal logging path (MINOR)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStoreTest.java

When forwarding to standby is enabled as part of HA, we were still waiting for streams thread to reach running state. I moved the waiting to happen only when forwarding to standby is not enabled.
Confirmed it works as expected via experiments on EC2 cluster

fix: Don't wait for streams thread to be in running state

---

docs-md/operate-and-deploy/installation/server-config/security.md

Same change as https://github.com/confluentinc/ksql/pull/4906, for the new markdown docs.

docs: remove extraneous ACLs from ksqlDB security topic (DOCS-3787)

---

docs-md/operate-and-deploy/installation/server-config/security.md
docs/installation/server-config/security.rst
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java

Removed unnecessary ACLs from an integration test
Removed ACL commands from docs
Experimented more with what ACLs are necessary to get the server running, and realized that permissions for `__consumer_offsets` and `__transaction_state` were unnecessary.
test still passes

chore: remove unecessary acls for starting up server

---

ksql-common/src/main/java/io/confluent/ksql/properties/LocalPropertyValidator.java
ksql-engine/src/main/java/io/confluent/ksql/properties/PropertyOverrider.java

fixes #4930 
Reverts #2618 from headless and `RUN SCRIPT` execution path to be consistent with interactive mode (local property settings).
End-to-end local testing

fix: remove immutable properties from headless mode

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java

fixes: https://github.com/confluentinc/ksql/issues/4939
Change to SQL syntax to not allow GROUP BY and PARTITION BY on boolean expressions. Only value expressions will be allowed.
usual

fix: do not allow GROUP BY and PARTITION BY on boolean expressions

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java

When using `INSERT INTO` with a nonexistent column, return a helpful error message instead of `null`.
```
ksql> CREATE STREAM test_stream (x VARCHAR, y INTEGER) WITH (kafka_topic='test_topic', key='x', value_format='json', partitions=1);
ksql> INSERT INTO test_stream (x, nonexistent) VALUES ('x', 0);
Failed to insert values into 'TEST_STREAM'. Column name `NONEXISTENT` does not exist.
```
Fixes #3838
Fixes #4253
Wrote new unit test

fix: throw error when column does not exist during INSERT INTO

---

ksqldb-common/src/main/java/io/confluent/ksql/logging/processing/NoopProcessingLogContext.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/GroupByParamsFactory.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/GroupByParamsFactoryTest.java

quick refactor of `GroupByParamsFactory` while correcting the name of the key column. The two inner classes were incorrectly using `ROWKEY` as the key column name, not the name of the key in the schema, which can now be things other than `ROWKEY`. This wasn't causing any issues (yet) as the key column name is not persisted (yet).  But good to clean it up.
usual

chore: correct key column names in GROUP BY key struct

---

docs-md/developer-guide/create-a-stream.md
docs-md/developer-guide/create-a-table.md
docs-md/developer-guide/ksqldb-reference/describe.md
docs-md/developer-guide/query-with-structured-data.md
docs-md/developer-guide/test-and-debug/generate-custom-test-data.md
docs-md/developer-guide/test-and-debug/processing-log.md
docs-md/tutorials/basics-docker.md
docs/developer-guide/create-a-stream.rst
docs/developer-guide/create-a-table.rst
docs/developer-guide/processing-log.rst
docs/developer-guide/query-with-structured-data.rst
docs/developer-guide/syntax-reference.rst
docs/includes/ksql-includes.rst
docs/tutorials/generate-custom-test-data.rst
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/EntityUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WebSocketSubscriberTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/EntityUtilTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/FieldInfo.java

fixes: https://github.com/confluentinc/ksql/issues/4928
The server response when describing a source schema now includes `fieldType='SYSTEM'` or `fieldType='KEY'` to differentiate system columns, i.e. ROWTIME, and key columns from value column.
Old output:
```
Field   | Type
-------------------------------------
ROWTIME | BIGINT           (system)
ROWKEY  | VARCHAR(STRING)  (system)
IP      | VARCHAR(STRING)  (key)
KBYTES  | BIGINT
-------------------------------------
```
New output:
```
Field   | Type
-------------------------------------
ROWTIME | BIGINT           (system)
ROWKEY  | VARCHAR(STRING)  (key)
IP      | VARCHAR(STRING)  (key)
KBYTES  | BIGINT
-------------------------------------
```
The default is no field type. This design decision was taken as the `FieldInfo` pojo is …

chore: decouple CLI from ROWKEY

---

ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java

A bug was introduced during fixing the API change introduced by #4597 whereby instead of the actual `requestProperties` a `Collections.emptyMap` was being passed.  
Verified it works locally

fix: Pass correct request configs when making pull query request

---

config/connect.properties.template
config/ksqldb-server.properties.template

In some distributions of python, dict doesn't have `iteritems` (I saw this when building the docker image for ubi8). This changes it to just use `items()`
This is the same change that was applied to ksql-images, and is being ported here. I will later have ksql-images depend on this file.
Also built the images in ksql-images and made sure both ubi8 and deb9 worked

build: change the build template not to use iteritems (MINOR)

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/table/builder/QueriesTableBuilderTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/RunningQuery.java

Format multiline queries correctly when running `SHOW QUERIES`.
```
ksql> CREATE STREAM S3 AS
SELECT * FROM S1
EMIT CHANGES;
ksql> SHOW QUERIES;
Query ID   | Status  | Sink Name | Sink Kafka Topic | Query String
CSAS_S2_73 | RUNNING | S2        | S2               | CREATE STREAM S2 WITH (KAFKA_TOPIC='S2', PARTITIONS=2, REPLICAS=1) AS SELECT * FROM S1 S1 EMIT CHANGES;
```
Fixes #4900
Wrote new unit tests

fix: output valid multiline queries when running SHOW QUERIES

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestConfigTest.java

unresolvable.host, r.host, and some *.host URLs are valid hosts in some machines. The `KsqlRestConfigTest#shouldThrowIfOnGetInterNodeListenerIfFirstListenerSetToUnresolvableHost` was failing in my machine because an expected exception was not thrown for the unresolvable host.
This fix replaces .host for _host to make it invalid
See *.host issues:
```
$ ping local.host
PING local.host (23.202.231.169) 56(84) bytes of data.
64 bytes from a23-202-231-169.deploy.static.akamaitechnologies.com (23.202.231.169): icmp_seq=1 ttl=53 time=45.1 ms
$ ping r.host
PING r.host (23.217.138.110) 56(84) bytes of data.
64 bytes from a23-217-138-110.deploy.static.akamaitechnologies.com (23.217.138.110): icmp_seq=1 ttl=55 …
```

test: fix issue with unresolvable host test

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorTest.java

Adds the use of a rate limiter for pull queries, to allow for capping QPS.  Fails immediately if limit is reached.
Fixes #4445 
`mvn package`

feat: Adds rate limiting to pull queries

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/simple-struct.json
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListFunctionsExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

FETCH_FIELD_FROM_STRUCT was removed releases ago. This commit removes the latest references.

chore: remove remaining refs to FETCH_FIELD_FROM_STRUCT (Minor)

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LagReportingAgent.java

Quick refactor to avoid returning null from `getAllLocalStorePartitionLags`.  In general the KSQL code does not return nulls. These means, as someone working on the code, you don't need to constantly check if the method you're calling can return null, and you don't need to litter the code with null checks. Things are also much less likely to fail with NullPointerExceptions.
In this case, the method can simply return an empty map, and the result is the same. Where a distinction is needed between a result and no result, then return `Optional<>`.
usual

refactor: avoid returning null

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/ColumnReferenceValidator.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/ColumnReferenceValidatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/elements.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/key-field.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json

This commit moves the checking for unknown column references in PARTITION BY clauses into the `Analyzer`, alongside the same checks done for other clause types.
It also improves the error message thrown from the `ColumnReferenceValidator` to include:
- the type of clause the bad reference was found in, e.g. PARTITION BY, SELECT, etc.
- the location, e.g `Line: 3, Col: 24`
These two bits of information should help users more quickly identify where their error is.
Note: the QTT tests that throw such errors have misaligned locations. This is because QTT reformats the tests to ensure `SqlFormatter` has coverage.  This does not happen for the normal flow.  This was tested manually:
```
ksql> CREATE STREAM REPARTITIONED AS select ID + '_new' AS ID_new, NAME from TEST partition by ID_NEW;
Line: …
```

chore: unify PARTITION BY validation & improve error msg

---

docs-md/developer-guide/ksqldb-reference/aggregate-functions.md

Remove the dead links to `WindowStart` and `WindowEnd` UDAFs. (These were removed a release or two ago)

docs: remove dead links to window bounds udafs

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksqldb-examples/src/main/java/io/confluent/ksql/datagen/RowGenerator.java
ksqldb-examples/src/test/java/io/confluent/ksql/datagen/RowGeneratorTest.java

This commit removes any use of `ROWKEY` from the DataGen app. This is being done as part of the work to allow any key column names, (https://github.com/confluentinc/ksql/issues/3536).
This is a compatible change as the key column name is not persisted in the data sent to Kafka. Hence the output doesn't change.
Usual

chore: remove ROWKEY from datagen

---

docs-md/tutorials/basics-docker.md
docs/includes/ksql-includes.rst
ksqldb-common/src/main/java/io/confluent/ksql/query/QueryId.java
ksqldb-common/src/test/java/io/confluent/ksql/query/QueryIdTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

fixes: #5003
The query id passed to `TERMINATE <queryId>` is currently case-sensitive. So, for example, 
```
TERMINATE CSAS_A_0;
```
May work, but:
```
TERMINATE csas_a_0;
```
Won't.
CSAS and CTAS create queries with upper case ids.  However, `INSERT INTO` creates mixed case queries, e.g. `InsertQuery_3`.  Again, users must get the case right to terminate them.
SQL is meant to be case-insensitive by default!   Hence this change switches terminate to be case-insensitive.
Because the command topics of users will contain existing queries with query ids in upper and mixed case, we need to be a little careful any fix doesn't stop users from terminating historic queries or meaning restores leave previously terminated queries running. There is also another open PR that we need to ensure works …

fix: query id for TERMINATE should be case insensitive

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/ServerUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ServerUtilTest.java

fixes #4668
See the description in the issue, we should allow listener IPs with trailing slash (e.g. `http://localhost:8080/`)
Unit testing

fix: allow trailing slash in listeners config (MINOR)

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/JLineReader.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/KsqlLineParser.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/UnclosedQuoteChecker.java
ksqldb-cli/src/main/java/io/confluent/ksql/util/CmdLineUtil.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/UnclosedQuoteCheckerTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/util/CmdLineUtilTest.java

This allows support for unclosed quotes in comments. e.g. "SELECT -- It's a comment ".
There's actually a lot of code now that reparses the same line.  The better longer term solution is to have a single parser and not delegate to DefaultParser, but I wanted to avoid making this too complex, since this fixes a small bug.
#4075  
`mvn package`

fix: Allows unclosed quote characters to exist in comments

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlPlan.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlPlanV1.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

fixes: https://github.com/confluentinc/ksql/issues/4923
Previously, on a restart, each ksqlDB node would build a query topology for each previously submitted persistent queries, i.e. CREATE TABLE AS SELECT, CREATE STREAM AS SELECT or INSERT INTO statement, _even if the associated query has already been terminated_.
Building the query topology takes a reasonable amount of time. By avoiding building these topologies for terminated queries the restart time will be much reduced for clusters with a lot of historic commands in the command topic.
A more complete solution to this problem is to move to a compacted topic for storing commands: https://github.com/confluentinc/ksql/pull/4659
Usual.
I didn't take the approach suggested in #4923 by @rodesai :
> the fix should be simple - just store a …

feat: speed up restarts by not building topologies for terminated queries

---

docs/installation/upgrading.rst

Working draft for migration instructions.
Also fixes some indentation issues.

docs: migration instructions for KSQL 5.4 to ksqlDB 5.5 (DOCS-3744)

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/engine/StubInsertValuesExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/Record.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilder.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopicInfoCache.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/stubs/StubKafkaRecord.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/engine/StubInsertValuesExecutorTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/SchemaTranslationTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestUtils.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestCase.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestCaseBuilder.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/RecordTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/StubKafkaServiceTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json

Simplification of the test framework code.
This change replaces the `Topic` field in the `Record` class with just the topic's name. This is all that is every required anyway.  This simplifies the model and allows a lot of code to be removed.
usual.

refactor: refactor QTT to remove Topic from Record

---

ksqldb-docker/Dockerfile

Our Docker images used to use a Debian base image, but we're now moving to UBI for the base image instead. The changes in this PR are necessary because
> the debian images were run as root, but the ubi8 base image runs using another user “appuser” which does not have root or sudo privileges. so it doesn’t have permission to [run the chmod command on line 22]
Quote and debugging courtesy of @elismaga .
Built an image locally, verified the server comes up and accepts statements. Also tried using confluent-hub for good measure.

chore: update dockerfile for ubi base image

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryStatusCount.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/QueryStatusCountTest.java

The `QueryStatusCount` getter returns `Map<KsqlQueryStatus, Integer>` but the creator expects `Map<KafkaStreams.State, Integer>` which means deserialization fails for `KsqlQueryStatus.UNRESPONSIVE` since that's not a valid `KafkaStreams.State`:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: 
Cannot deserialize Map key of type `org.apache.kafka.streams.KafkaStreams$State` from String "UNRESPONSIVE": not a valid representation, problem: (com.fasterxml.jackson.databind.exc.InvalidFormatException) Cannot deserialize Map key of type `org.apache.kafka.streams.KafkaStreams$State` from String "UNRESPONSIVE": not one of the values accepted for Enum class: [CREATED, NOT_RUNNING, RUNNING, ERROR, REBALANCING, PENDING_SHUTDOWN]
```
This PR updates the creator to match the …

fix: json creator for QueryStatusCount should match getter (MINOR)

---

ksqldb-docker/README.md

After the Dockerfile update to support UBI base images (https://github.com/confluentinc/ksql/pull/5025) the local Docker build instructions started failing with
```
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (package) on project ksqldb-docker: Could not build image: unable to convert uid/gid chown string to host mapping: can't find uid for user appuser: no such user: appuser
```
because the base image specified in the README was still on Debian. This PR updates the README to use a UBI base image to avoid the failure.
There are plans in the works for creating a new upstream image/tag to one that will always have the latest base image (e.g., `confluentinc/cp-base-new:ubi-latest` or `confluentinc/ksqldb-base:latest`). This is a temporary fix to unblock …

chore: update base docker image tag to be UBI (MINOR)

---

ksqldb-docker/README.md

As a followup to https://github.com/confluentinc/ksql/pull/5061, @elismaga has kindly helped us create a new docker image tag for our base docker images so we can update the tag with new version behind the scenes without needing to update our docs each time. This PR updates our README instructions for building local docker images accordingly.
Built local docker image with new base image tag.

docs: update docker README build instructions to new base image tag (MINOR)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ApiServerConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/KSqlCorsHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/KsqlCorsHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/CorsTest.java

This PR adds CORS support for ksqlDB in the absence of Jetty.
In KsqlRestApplication I've tried to maintain compatibility with the existing way CORS is configured.
This is a stacked PR, please only review the top commit(s)
Added new test class

feat: CORS support for Vert.x based ksqlDB

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/AuthenticationPluginHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ApiServerConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/KsqlCorsHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerUtils.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/AuthTest.java

This PR extends the unauthed paths for AuthenticationPluginHandler to support wildcards. This make it compatible with authentication.skip.paths in rest-utils config.
This is a stacked PR, please just review the top commit.
Added new test

feat: Support wildcards for unauthed paths

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/AuthTest.java

If basic auth handler is configured along with auth plugin, then make sure the basic auth handler is used if auth type = basic.
This is a stacked PR, please review top commit(s).
Added/updated tests

chore: Make sure basic auth handler is called when plugin is configured

---

ksqldb-execution/src/main/java/io/confluent/ksql/services/DisabledKsqlClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java

fixes #4873 
This is a stacked PR, please just review the top commit(s).
This PR fixes a couple of issues that make it hard to diagnose ksqlDB server startup issues.
1. Exceptions thrown from startup currently aren't logged, making it hard to diagnose startup issues
2. NPE thrown from StreamQueryResource.closeMetrics
N/A

fix: Catch server startup exceptions

---

ksqldb-common/src/main/java/io/confluent/ksql/util/VertxUtils.java
ksqldb-execution/src/main/java/io/confluent/ksql/services/DisabledKsqlClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PortedEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ProxyHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
pom.xml

This is a stacked PR, please review only the top commit.
This fixes a bug where we were setting transfer-encoding: chunked in the ProxyHandler for HTTP2 request which have a connection:close header. This is illegal.
Added new test.

fix: Don't set chunked transfer encoding for HTTP2 proxy

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslClientAuthFunctionalTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslFunctionalTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/DefaultKsqlClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/RestServiceContextFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeWithTlsFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/services/TestDefaultKsqlClientFactory.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientTest.java

Fixes https://github.com/confluentinc/ksql/issues/5055
In a previous non functional change we replaced the Jetty based HTTP client with a Vert.x based one.
However there were no existing integration tests that tested with a TLS configured cluster, so a bug whereby the internal client wasn't being configured with TLS properly wasn't exposed.
This PR fixes things so the internal client works ok with TLS.
Added a new integration test which tests a cluster configured with TLS.

fix: Make sure internal client is configured for TLS

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/RewrittenAnalysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/JoinTree.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/JoinTreeTest.java

Introduces the `JoinTree` class, which contains the algorithm for constructing a join tree from a list of join information. This PR does not enable any new behaviors.
Unit testing

chore: add JoinTree in preparation for multi-way join support

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PreconditionFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestAppWaitingOnPrecondition.java

The current order of events when starting the ksql rest app is:
1. Start Jetty server
1. Start vert.x server, including proxy handler to proxy requests to Jetty server
1. Initialize ksql, including waiting for preconditions, creating command topic, etc.
1. Configure Jetty port on vert.x server in order for vert.x server to proxy requests to Jetty
As a consequence, ksql is unable to serve requests made to Jetty endpoints if we're blocked waiting for preconditions. (We'd hit an internal server error since vert.x tries to proxy the request but there's no Jetty port configured yet.) This is a regression from before the proxy handler was introduced. This PR fixes the regression by updating the order of events to become:
1. Start Jetty server
1. Start vert.x server, including proxy handler to …

fix: make endpoints available while waiting for precondition

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PortedEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/Server.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerStateHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/AuthTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/CorsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ServerStateTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/BasePerfRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ClusterTerminationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java

The old (Jetty) server uses a filter ([link](https://github.com/confluentinc/ksql/blob/master/ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/state/ServerStateFilter.java)) to reject requests if the `ServerState` is not `READY`, but this functionality was not ported over to the new API server. This PR introduces a new handler to the new (vert.x) server to carry over this behavior.
This PR is stacked on https://github.com/confluentinc/ksql/pull/4985 so only the most recent commits need to be reviewed.
~~Something weird is going on with how the `KsqlClient` parses responses from the new API server as the newly added test in `ClusterTerminationTest` passes on `master` and also if `SERVER_PORTED_ENDPOINTS` is set to false, but fails when ported endpoints are enabled. The specific …

fix: reject requests to new API server if server is not ready

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/QueriesTableBuilder.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeWithTlsFunctionalTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryStatusCount.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/RunningQuery.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/QueryStatusCountTest.java

https://github.com/confluentinc/ksql/pull/4875 changed the `state` field to return a string representation of all host query statuses. However, the C3 UI expects a single status in the `state` field and wouldn't be able to properly render multiple host query statuses right now.
Changed `getState` in RunningQuery and QueryDescription classes to return a single status based on the aggregated query statuses.
Unit Tests

refactor: return single status based on aggregate results in state field

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/JoinTree.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json

fixes #1891 
This PR wraps up the loose ends around supporting multiple joins, leaving as an extension #5062. A vast majority of this PR is just `multi-joins.json` which has somewhat extensive coverage on multi-joins - though a lot of it just depends on the correctness of joins which are covered in `joins.json`.
- `multi-joins.json` and some more unit tests
- **NOTE**: there are no historical tests because I wrote all of these tests with `ksql.any.key.name.enabled:true`

feat: support multi-way joins

---

ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestConfigTest.java

fixes #4668 
unit testing, local testing spinning up a node with trailing slash and ran a query

fix: support trailing slashes in listener URLs

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/PlanSummary.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/PlanSummaryTest.java

`StreamGroupByKey` steps resulted in a `null` op type, but now resolve correctly to `GROUP_BY`. In the future, unsupported types will result in an exception.
usual

fix: replace 'null' in explain plan with correct op type (MINOR)

---

ksqldb-benchmark/pom.xml
ksqldb-engine/pom.xml
ksqldb-execution/pom.xml
ksqldb-parser/pom.xml
ksqldb-streams/pom.xml
ksqldb-version-metrics-client/pom.xml
pom.xml

Use `mvn compile -Dcompile.warnings-flag=""` to disable warnings as errors.

chore: allow -Werror to be overridden in compile phase

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/RewrittenAnalysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/JoinTree.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/JoinTreeTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json

fixes #5062 
This change uses the `JoinTree` to track the equivalence of the join criteria across the different join stages, then uses that information to decide whether or not a repartition is necessary. This opens the door to using different expressions (and non-matching expressions) on different parts of the join.
- unit testing
- QTT tests

feat: add multi-join expression support

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PortedEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/Server.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ClusterStatusResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/HeartbeatResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ServerInfoResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java

This is a stacked PR so please only review the top commit(s).
This PR migrates the /heartbeat and /clusterStatus endpoints to Vert.x
It also removes the JAX-RS annotations from already ported endpoints.

refactor: Migrate /heartbeat and /clusterStatus endpoints

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PortedEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/StatusResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java

This is a stacked PR, please only review the top commit(s).
This PR migrates the /status endpoint from Jetty to Vert.x
I added a couple of integration test cases because there were no tests for this API!

refactor: Migrate /status endpoint to vert.x

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PortedEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ServerMetadataResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java

This is a stacked PR, please only review top commit(s).
This PR migrates the server metadata endpoints ( /v1/metadata and /v1/metadata/id )from Jetty to Vert.x.
Also, there were zero integration tests for these endpoints so I added them.
Non functional change, but I added some new tests.

refactor: Migrate server metadata endpoints

---

ksql-common/src/main/java/io/confluent/ksql/schema/connect/SqlSchemaFormatter.java
ksql-common/src/main/java/io/confluent/ksql/schema/ksql/FormatOptions.java
ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorTest.java
ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksql-parser/src/main/java/io/confluent/ksql/util/IdentifierUtil.java
ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksql-parser/src/test/java/io/confluent/ksql/util/IdentifierUtilTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/ProcessingLogServerUtils.java

Backport https://github.com/confluentinc/ksql/pull/3723
Fixes https://github.com/confluentinc/ksql/issues/5032

fix: include lower-case identifiers among those that need quotes (#3723)

---

ksqldb-rocksdb-config-setter/src/main/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBConfig.java
ksqldb-rocksdb-config-setter/src/main/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBConfigSetter.java
ksqldb-rocksdb-config-setter/src/test/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBConfigSetterTest.java
ksqldb-rocksdb-config-setter/src/test/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBConfigTest.java

Allows more precise configuration of rocks bounds. Rather than a general
bound config, allow configuring the sizes of cache and memtables, and
allow configuring whether memtable usage is charged to cache.

BREAKING CHANGE: minor: allow more precise configuration of rocks bounds

---

docs/developer-guide/ksqldb-reference/show-queries.md
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/QueriesTableBuilder.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/table/builder/QueriesTableBuilderTest.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksqldb-engine/src/main/java/io/confluent/ksql/KsqlExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/TransientQueryMetadataTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescriptionFactory.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ExplainExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/RunningQuery.java

Addresses https://github.com/confluentinc/ksql/issues/4308
There's a known issue where if no persistent queries are running in a multi node environment and a transient query is running on node A, that transient query won't show up in `Show queries` executed to other nodes.
https://github.com/confluentinc/ksql/issues/4910
```
Query ID                                                            | Query Type | Status    | Sink Name | Sink Kafka Topic | Query String                                                                                                                                  
---------------------------------------------------------------------------------------------------------------------------------------------
CSAS_TEST_0 …
```

feat: transient queries added to show queries output

---

docs/js/extra.js

The docs version picker does not select the current version when on the 0.7.1-ksqldb url. This fixes the logic to choose the dropdown's default selection based on the url.
Tested locally with dummy pages under `/en/0.7.1-ksqldb/`, `/en/0.8.1-ksqldb/`, `/en/latest/` to mimic the deployed docs.

docs: fix version picker for previous versions

---

mkdocs.yml

From https://github.com/confluentinc/ksql/pull/5156.

docs: cherry-pick bump CP version in ksqlDB Standalone docs (DOCS-4152)

---

ksqldb-common/src/main/java/io/confluent/ksql/function/TableFunctionFactory.java
ksqldb-common/src/main/java/io/confluent/ksql/function/UdfFactory.java
ksqldb-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksqldb-common/src/test/java/io/confluent/ksql/function/UdfIndexTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafAggregateFunctionFactory.java

fixes #5129 
ensures that lookups for UDAFs in the UdfIndex do not support implicit casting. Previously, the UDF index would find a match but it would fail later on with a cryptic error message.
Unit testing and end to end testing:
```sql
ksql> SELECT COLLECT_LIST(amount) FROM transactions GROUP BY rowkey EMIT CHANGES;
Function 'collect_list' does not accept parameters (DECIMAL(12, 2)).
Valid alternatives are:
collect_list(BOOLEAN val)
collect_list(DOUBLE val)
collect_list(INT val)
collect_list(BIGINT val)
collect_list(VARCHAR val)
For detailed information on a function run: DESCRIBE FUNCTION <Function-Name>;
```

fix: do not allow implicit casting in UDAF function lookup

---

design-proposals/klip-25-removal-of-with-key-syntax.md

This KLIP proposes the removal of the confusing and soon to be redundant 'WITH(KEY)' syntax.
Previously track by https://github.com/confluentinc/ksql/issues/3537.

docs: add klip 25 - removal of WITH(KEY) syntax

---

pom.xml

Now that 5.5 is released we shouldn't be pinning to snapshots.
local build

build: pin streams to 5.5.0 instead of 5.5.0-SNAPSHOT

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/CloseQueryHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ErrorCodes.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/InsertsStreamHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerUtils.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/Http2OnlyStreamTest.java

Implements: https://github.com/confluentinc/ksql/issues/4604
Reject access to the new streaming endpoints when attempted using HTTP1.1.
Added new tests

feat: Do not allow access to new streaming endpoints using HTTP1.x

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/EndToEndEngineTestUtil.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanLoader.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java

QTT tests normally output the test name that failed, (making it easy to copy and search for it). However, tests that throw exceptions when building do not.  This commit fixes this.
test only change,

test: have QTT report test name when exception thrown

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/AsValue.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/AsValueTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/as_value.json

Part of [klip-24](https://github.com/confluentinc/ksql/pull/5115).
A Udf that indicates that a key column in a projection should be copied into a value column, for example:
```sql
-- Given:
CREATE STREAM INPUT (ID INT KEY, V0 INT, V1 INT) WITH (kafka_topic='input', value_format='JSON');
-- When:
CREATE STREAM OUTPUT AS SELECT ID, AS_VALUE(ID) AS ID_COPY, V1 FROM INPUT;
-- Then:
-- resulting schema: ID INT KEY, ID_COPY INT, V1 INT
```
Note, the UDF doesn't actually _do_ anything as yet. It requires the request of klip-24 to enable its true purpose.
Documentation for this PR will be done along with all the klip-24 / any-key-name work. This is tracked by: https://github.com/confluentinc/ksql/pull/4686
usual

chore: add AS_VALUE Udf

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/JoinTree.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/JoinTreeTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json

fixes: https://github.com/confluentinc/ksql/issues/5202
This change ensures the appropriate repartition step is added when an outer join is combined with a later join type in the same query.
Usual

chore: fix outer join handling in multi-way joins

---

ksqldb-common/src/test/java/io/confluent/ksql/schema/ksql/SchemaConvertersTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdtfLoader.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdtfLoaderTest.java
ksqldb-udf/src/main/java/io/confluent/ksql/function/udf/Udf.java

fixes #5164
replaces #5190 
This change (1) eagerly resolves the return type if possible to fail early if a function cannot be loaded and (2) skips resolving the java type to a sql type if the udf annotation contains the `schema` field.
Thanks @stevenpyzhang for exploring the issue!
Lots of new unit tests and end-to-end testing with the UDF linked in the ticket.

fix: use schema in annotation as schema provider if present

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/ddl/commands/RegisterTypeCommand.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksqldb-functional-tests/src/test/resources/historical_plans/create-type_-_create_nested_type/6.0.0_1588107644049/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/create-type_-_create_nested_type/6.0.0_1588107644049/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/create-type_-_create_nested_type/6.0.0_1588107644049/topology
ksqldb-functional-tests/src/test/resources/historical_plans/create-type_-_create_simple_type/6.0.0_1588107643993/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/create-type_-_create_simple_type/6.0.0_1588107643993/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/create-type_-_create_simple_type/6.0.0_1588107643993/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/create-type.json

Add QTT tests to the `CREATE TYPE` commands. In order to do that, however, we needed to modify the test util to run these commands when creating the test topics.
Ran the tests

 test: add test coverage to create-type

---

docs-md/developer-guide/ksqldb-reference/create-table.md

As of KSQL 5.4 and ksqlDB 0.6.0, the old requirement that `CREATE TABLE` statements had to specify the `KEY` property was dropped (see https://github.com/confluentinc/ksql/pull/2746), and the relevant docs were updated accordingly, except this statement which remains in the docs for `CREATE TABLE`:
```
When creating a table from a Kafka topic, ksqlDB requries the message key	
to be a `VARCHAR` aka `STRING`. If the message key is not of this type	
follow the instructions in "Key Requirements".
```
which misleading makes it sound as if the `KEY` property is still required for tables.
This PR removes the confusing statement.
@JimGalasyn could you help cherry-pick this to older branches? It's not needed on master since it's already been removed on master as part of …

docs: remove confusing statement about key requirement in CREATE TABLE (MINOR)

---

CHANGELOG.md

From https://github.com/confluentinc/ksql/pull/5240.

docs: cherry-pick: update link to old KSQL changelog (DOCS-4220)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java

/chc/* endpoints need to be accessible from a browser which will enforce the cross origin policy, so we need cors handler in front of it to provide the cors headers.
Manual testing

fix: Move Cors handler in front of /chc handlers

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ErrorCodes.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerUtils.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/protocol/PojoCodec.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/protocol/PojoDeserializerErrorHandler.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/PojoCodecTest.java

Fixes https://github.com/confluentinc/ksql/issues/4996
^ by switching from `DatabindCodec.mapper` to the JSON mapper used for the existing APIs. This also means we no longer fail to deserialize on unknown properties, which is nice to have for forward compatibility (in case we evolve the API to add additional properties in the future). The relevant unit test was updated accordingly.
Added unit test.

fix: /query-stream endpoint should serialize Struct (MINOR)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java

fixes: https://github.com/confluentinc/ksql/issues/5246
PRINT topic in 0.8.x output rowtime in UTC. Current impl outputs in local timezone. This commit changes it back to UTC.
usual

chore: print topic should output rowtime in UTC

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/syntax-reference.md

Fixes links to the Operators topic.

docs: fix broken links in syntax reference (DOCS-4236)

---

docs/developer-guide/syntax-reference.md

From https://github.com/confluentinc/ksql/pull/5259.

docs: cherry-pick: fix broken links in syntax reference (DOCS-4236)

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/RewrittenAnalysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/AstSanitizer.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/StatementRewriter.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/RepartitionNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/PullQueryValidatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/AstSanitizerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/StatementRewriterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSelectKey.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/plan/StreamSelectKeyTest.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/PartitionBy.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/PartitionByTest.java
ksqldb-rest-app/src/test/resources/ksql-plan-schema/schema.json
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/PartitionByParamsFactory.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StepSchemaResolver.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamSelectKeyBuilder.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/PartitionByParamsFactoryTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StepSchemaResolverTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StreamSelectKeyBuilderTest.java

The KLIP-24 work removes the need for alias support on partition by clauses, e.g. `PARTITION BY x AS y`.
Note: this feature was never enabled in a released version.
usual

chore: remove defunct alias support for PARTITION BY

---

docs/developer-guide/ksqldb-reference/create-table.md

From https://github.com/confluentinc/ksql/pull/5229.

docs: cherry-pick: fix statement about key requirement in CREATE TABLE (DOCS-4268)

---

ksqldb-common/src/main/java/io/confluent/ksql/function/types/StructType.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/TestUdf.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/function/UdfUtil.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/function/UdfUtilTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/struct-udfs_-_Output_struct/6.0.0_1588882528086/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/struct-udfs_-_Output_struct/6.0.0_1588882528086/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/struct-udfs_-_Output_struct/6.0.0_1588882528086/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/struct-udfs.json
ksqldb-udf/src/main/java/io/confluent/ksql/function/udf/UdfSchemaProvider.java

fixes #5286 
This PR allows resolution to a ParamType of `StructType` for udf methods that have the java return type of Connect's `Struct` class. The user experience isn't great, as they need to specify the return of the udf using `SqlType` but the return object as a Connect `Struct` but that will be follow-up work.
**NOTE**: The fix is the two lines in UdfUtil, the rest is testing
Unit tests

fix: allow structs in schema provider return types

---

mkdocs.yml

From https://github.com/confluentinc/ksql/pull/5309.

docs: cherry-pick: update copyright date to 2020 (DOCS-4284)

---

.env
docker-compose.yml
docs/concepts/ksqldb-architecture.md
down
ksqldb-docker/README.md
up

From https://github.com/confluentinc/ksql/pull/5245.
* testing: updated docker-compose.yml
Commit adds utility `up` script to bring up docker images, wait for ksql to be responsive, and then load the cli.  `down` to bring everything down again.
`.env` file added with environment vars for setting docker version.
updated some outdated links too.

docs: cherry-pick: updated docker-compose.yml (MINOR) (DOCS-4295)

---

docs/overrides/partials/integrations/analytics.html
mkdocs.yml

Updates docs site analytics to match ksqldb.io's configuration. This overrides a specific mkdocs-material partial to insert the code.
The mkdocs configuration now specifies a Google Tag Manager account. I did not change the property name from `google_analytics` because it would have involved a cascade of overrides to the theme files.
Tested with a local docs build and GTM preview mode.

docs: use GTM for analytics

---

docs/js/analytics.js
docs/overrides/partials/integrations/analytics.html
mkdocs.yml

In #5321, the docs analytics implementation was moved to a template override. We have found that this can produce inconsistent output across build configurations. This PR moves the implementation to a script include, which should produce the same behavior across builds.
Verified by building the docs locally and with a test docs site version.

docs: add analytics outside theme

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/KsqlArray.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/KsqlObject.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Row.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/RowImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/util/RowUtil.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/RowImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/util/RowUtilTest.java

This PR is stacked on https://github.com/confluentinc/ksql/pull/5327 -- only the new commits should be reviewed.
This PR adds support for the decimal type in various interfaces, and also adds the `Row#isNull()` method based on feedback from https://github.com/confluentinc/ksql/pull/5236. Additional unit test coverage was added to `RowImplTest.java` (and will be carried over into integration test coverage in `ClientTest.java` in a future PR).
Manual + added unit tests.

chore(client): first class decimal support in client interfaces

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1583419431528/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1588893908853/spec.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/decimal.json
ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonSerializerTest.java
pom.xml

- drop cp/kaka versions from pom.xml and just use the ones from common
- fix usage of ssl factory

chore: build ksqlDB against 6.0.0

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1583419431528/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1588893908853/spec.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/decimal.json
ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonSerializerTest.java
pom.xml

This reverts commit 67ea30b2e1e4d5ef2dd110a71e22f68072682eeb.
Reverting this commit as it breaks master. It seems to change the version of Kafka/KS that we build against, and the current ksqlDb master code does not build against that version. Specifically the ProcessorContext interface has changed from generic (old version) to non generic (newer version) - this results in compiler warnings and our build is configured to fail on warnings.
N/A

chore: Revert "build ksqlDB against 6.0.0 (#5339)"

---

ksqldb-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java
ksqldb-examples/src/main/java/io/confluent/ksql/datagen/ProducerFactory.java

Fixes: https://github.com/confluentinc/ksql/issues/4481
Now value delimiter can be specified when using datagen with delimited format.
Manually tested

fix: Allow value delimiter to be specified for datagen

---

ksqldb-api-reactive-streams-tck/src/test/java/io/confluent/ksql/api/tck/BlockingQueryPublisherVerificationTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/KsqlExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/BlockingRowQueue.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/LimitedQueueCallback.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/TransientQueryQueue.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/LimitedQueueCallbackTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/TransientQueryQueueTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/BlockingQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/endpoints/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PushQueryHandle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriterTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

A change went in a while ago that created a transient query without creating `TransientQueryMetadata`. Instead is inline-subclassed the abstract `QueryMetadata` class, and replicated the logic for handling limits.
The direct subclassing of `QueryMetadata` is not ideal. All transient queries should be `TransientQueryMetadata`.
The replication of the limit handling logical is also not ideal.
This change fixes both of these issues.
`mvn verify`

refactor: unify TransientQuery metadata

---

CHANGELOG.md

Add a note at the top of the Changelog to warn users who upgrade from ksqlDB < 0.7 to read and follow the upgrade instructions.

docs: add upgrade note at the top of changelog

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/KudafByOffsetUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/earliest/EarliestByOffset.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/latest/LatestByOffset.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/earliest/EarliestByOffsetUdafTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/latest/LatestByOffsetUdafTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestGeneratorTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset/6.0.0_1588701853940/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset/6.0.0_1588701853940/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset/6.0.0_1588701853940/topology
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset/6.0.0_1589303205454/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset/6.0.0_1589303205454/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset/6.0.0_1589303205454/topology
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_all_nulls/6.0.0_1588701854211/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_all_nulls/6.0.0_1588701854211/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_all_nulls/6.0.0_1588701854211/topology
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_all_nulls/6.0.0_1589303205666/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_all_nulls/6.0.0_1589303205666/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_all_nulls/6.0.0_1589303205666/topology
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_nulls/6.0.0_1588701854095/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_nulls/6.0.0_1588701854095/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_nulls/6.0.0_1588701854095/topology
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_nulls/6.0.0_1589303205588/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_nulls/6.0.0_1589303205588/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/earliest-offset-udaf_-_earliest_by_offset_with_nulls/6.0.0_1589303205588/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/earliest-offset-udaf.json

Fixes https://github.com/confluentinc/ksql/issues/5268
Implements earliest_by_offset() UDAF which computes the earliest value for a column. Earliest being defined as offset order.
Note for the reviewer:
- The implementation is taken from the latest_by_offset() code https://github.com/confluentinc/ksql/pull/4782, and modified to return the earliest offset. Expect similar concerns and questions commented in the mentioned PR.
Added new unit test and QTT test

feat: implement earliest_by_offset() UDAF

---

Jenkinsfile

The git credential environment variable was using the user name and password, and should be user and access token. This bug was introduced when migrating the secrets to Vault. This caused the git push tag operation to fail.

build: ST-3402: Fix git credential to use the access token

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgent.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgentTest.java

The healthcheck agent should be issuing requests that indicate it's an internal request, this is so that the `show queries` request doesn't trigger a scatter gather.
unit test

chore: add internal request property to healthcheck requests

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/ddl/commands/CreateSourceCommand.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/ddl/commands/CreateSourceCommandTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/key-field.json

fixes: https://github.com/confluentinc/ksql/issues/5333
The error message being returned to the user if the key field identified via `WITH(KEY)` syntax had a different SQL type to ROWKEY column was misleading as it talked about `WITH(KEY)` being deprecated and didn't mention `PRIMARY KEY`s on tables.  This is mainly due to the 'any key name' feature being pulled from the 0.9 release.  This change reverts the error message to the old version and adds in the PRIMARY KEY bit.
test updated.

fix: improve error message on key field type mismatch

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/StreamedQueryResultImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/StreamedQueryResultImplTest.java

A recently added test:
```
@Test
public void shouldReturnFromPollOnError() throws Exception {
// Given
// Poll for a minimal amount of time to ensure PollableSubscriber is subscribed
queryResult.poll(1, TimeUnit.NANOSECONDS);
CountDownLatch latch = new CountDownLatch(1);
new Thread(() -> {
queryResult.poll();
latch.countDown();
}).start();
// When
handleQueryResultError();
// Then
awaitLatch(latch);
}
```
is flaky due to the following race condition: if `handleQueryResultError();` executes before the call to `queryResult.poll();` begins, then `queryResult.poll();` will fail and the test will fail. However, ensuring that the call to `queryResult.poll();` begins before `handleQueryResultError();` is called is nontrivial since `queryResult.poll();` is a blocking call that will only terminate …

test: fix racy client test (MINOR)

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java

^ via the `/close-query` endpoint. This PR also adds a test to check that `StreamedQueryResult` objects are properly completed when the underlying query is terminated.
Unit tests.

feat(client): support push query termination in Java client

---

docs/operate-and-deploy/installation/server-config/config-reference.md
docs/operate-and-deploy/installation/server-config/index.md

Hopefully add more improvements to the docs improvements @AlanConfluent already made around the listener config. 
* fixed some spelling mistakes.
* hopefully added more clarification of _when_ the advertised listener config should be set.
* added a link from the config help page to the new, more detailed, docs Alan added
* hopefully made it clear that resolvable hostnames can be used as an alternative to IP addresses.
* Added a "In this setup..." paragraph to each of the four configurations to more easily allow comparison.

docs: improved docs around listener config

---

docs/tutorials/materialized.md

Changes the Docker Compose file for the materialized view tutorial to allow more connectors to be added without changing the env var. Doesn't need to be backported to previous versions.

docs: widen plugin path for tutorial

---

pom.xml

Update the version so it includes this fix for using the plugin with shallow git repos 
https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/290
`git clone https://github.com/confluentinc/ksql --depth 1 `
run `mvn install`
this would previously fail without updating the version

chore: update git commit id plugin version

---

config/ksql-server.properties
ksqldb-common/src/main/java/io/confluent/ksql/query/ErrorStateListener.java
ksqldb-common/src/main/java/io/confluent/ksql/query/QueryError.java
ksqldb-common/src/main/java/io/confluent/ksql/query/QueryErrorClassifier.java
ksqldb-common/src/test/java/io/confluent/ksql/query/QueryErrorClassifierTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/QueryStateListener.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/KafkaStreamsBuilderImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/MissingTopicClassifier.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/KafkaStreamsUncaughtExceptionHandler.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/QueryStateListenerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/MissingTopicClassifierTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

This PR introduces JMX metrics that drill query errors down into more specific categories: `UNKNOWN`, `USER` and `SYSTEM` (open to better names) when an uncaught error is raised from KafkaStreams.
There's a lot in this PR, I can split it up if it helps the review but it's not that many lines of code so I figured it's digestible with a little guide:
- `QueryError` a throwable paired with a classification of that error (see above)
- `ErrorStateListener` extends `StateListener` to add an additional method that reacts to `QueryError` when its raised
- `QueryErrorClassifier` classifies exceptions; it also supports chaining so we can easily introduce other ones
- `MissingTopicClassifier` will check if any required topics are missing, and if so classifies the error as `USER`
- I moved …

feat: expose JMX metric that classifies an error state

---

docs/requirements.txt

Something changed in the last couple of days, because the build is choking on a requirement for python-dateutil.

docs: update requirements in ksqlDB docs build (DOCS-4396)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ResponseOutputStream.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java

Previously there was no back pressure on writes from the legacy streaming API to the response. This could mean that writes buffered in memory if the client was slow which could lead to unbounded memory usage.
This PR blocks the writer thread if the response is full and unblocks it when it is drained to provide some synchronous back pressure to the caller.
Manually tested.

fix: Block writer thread if response output buffer is full

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/BatchedQueryResult.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/BatchedQueryResultImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ExecuteQueryResponseHandler.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/QueryResponseHandler.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/StreamQueryResponseHandler.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java

This PR addresses the issue raised in https://github.com/confluentinc/ksql/pull/5236#issuecomment-628997138: the current method signature
```
public interface Client {
/**
* Execute a query (push or pull) and receive all result rows together, once the query has
* completed.
*
* @param sql statement of query to execute.
* @return query result.
*/
CompletableFuture<BatchedQueryResult> executeQuery(String sql);
...
}
```
with
```
public interface BatchedQueryResult {
List<String> columnNames();
List<ColumnType> columnTypes();
String queryID();
List<Row> rows();
}
```
doesn't work in terms of exposing the query ID so users can terminate queries issued via `executeQuery()` since by the time the user has the BatchedQueryResult (in order to get the query ID) the query must already have …

fix(client): expose query ID from executeQuery() return type

---

docs/requirements.txt

Pins package versions in requirements.txt to prevent future breakage in the doc build caused by plugin updates.

docs: pin requirements for ksqlDB doc build (DOCS-4408)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java

https://github.com/confluentinc/ksql/pull/3490
Previously, we were only adding configurable metrics reporters to interactive mode, this makes it so that headless mode will also add the metrics reporters.
Unit tests

chore: add configurable metrics reporter to headless mode and unit tests

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/InternalEndpointHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisherTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

When doing pull queries, we do a QPS check.  At the moment, we only check at the initial client request, regardless of whether it gets forwarded.  This makes it easy to reason about the total cluster QPS.
To do this, we utilize a request property, `request.ksql.query.pull.skip.forwarding`.  This PR adds the additional requirement that if `ksql.internal.listener` is in use, the request must be internal to be considered a forwarded request.
This prevents a user from setting `request.ksql.query.pull.skip.forwarding` explicitly.
`mvn package`.  Also tested manually.

feat: Pull Queries: QPS check utilizes internal API flag to determine if forwarded

---

ksqldb-api-client/pom.xml
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/StreamedQueryResultImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/util/JsonMapper.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryResponseMetadata.java

It's super important that the Java client doesn't depend on too many 3rd party deps, in particular commonly used ones such as Google/Apache/Guava stuff as the chance of version classes when the Java client is used in a user's app becomes higher. This can give the user a real headache and results in a poor user experience and potential bad sentiment towards the project.
Most of the work in removing deps has already been done by @vcrfxia , this just removes a bit more.

chore: Remove some more unneeded deps from client

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java

Ensures each RQTT run uses a unique state directory, otherwise parallel runs can interfere with each other.

test: stop RQTT runs from clashing (MINOR)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/MissingTopicClassifier.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/RegexClassifier.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/RegexClassifierTest.java

This change introduces the ability to use config to classify errors as one of `UNKNOWN`, `USER` or `SYSTEM` (see #5374 for more information) via regex patterns. 
Tested with:
```properties
ksql.error.classifier.regex.1=USER .*task directory .* doesn't exist and couldn't be created.* 
```
And saw the following in the logs:
```
[2020-05-19 10:48:46,336] ERROR Unhandled exception caught in streams thread _confluent-ksql-default_query_CTAS_COUNTS_0-49406875-bc65-4fe2-9932-640c88dac8ae-StreamThread-3. (io.confluent.ksql.engine.KsqlEngine:43)
org.apache.kafka.streams.errors.ProcessorStateException: task directory [/tmp/kafka-streams/_confluent-ksql-default_query_CTAS_COUNTS_0/1_0] doesn't exist and couldn't be created
...
[2020-05-19 10:48:46,968] WARN Classified error for queryId …
```

feat: introduce RegexClassifier for classifying errors via cfg

---

docs/developer-guide/joins/partition-data.md
docs/developer-guide/ksqldb-reference/insert-values.md
docs/developer-guide/syntax-reference.md
docs/operate-and-deploy/installation/server-config/avro-schema.md
docs/operate-and-deploy/installation/upgrading.md
docs/tutorials/basics-docker.md
docs/tutorials/examples.md

Copy edit for docs content in https://github.com/confluentinc/ksql/pull/5363.

docs: copy edit WITH(KEY) doc changes (DOCS-4374)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/table-functions.md

A lot of the right sidebars that pre-populate the table of contents were messed up for function references. I fixed that and made the code snippets more readable.

Fix markdown for function references

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/windowed-source.json

A WINDOW clause is only valid if there is no matching GROUP BY. Before this change, if user submitted a query without a GROUP BY it would silently be ignored, which is poor UX. With this change an helpful error message is displayed.
See the QTT test for an example.
usual

fix: fail on WINDOW clause without matching GROUP BY

---

ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/ImmutableTester.java
ksqldb-test-util/src/test/java/io/confluent/ksql/test/util/ImmutableTesterTest.java

Tester now correctly handles wildcards with immutable upper bounds, e.g. `ImmutableList<? extends SomeImmutableType>`.

test: enhance ImmutableTester to support wildcards (MINOR)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java

Not only does the `/query-stream` endpoint default to `auto.offset.reset=earliest`, it currently doesn't allow the user to specify `auto.offset.reset=latest` since the endpoint hardcodes putting `auto.offset.reset=earliest` into the properties map, which overrides any user specification for the property value.
This PR fixes the issue in a really hacky way. The solution is brittle since it requires checking for all possible aliases of the `auto.offset.reset` property. Ideally we'd evaluate the properties first and then apply the override but that would involve changes to the engine.
Added an integration test.

fix: allow setting auto.offset.reset=latest on /query-stream endpoint

---

design-proposals/klip-10-suppress.md

**Author**: agavra | 
**Release Target**: 5.5 | 
**Status**: _In Discussion_ | 
**Discussion**: _link to the design discussion PR_
**tl;dr:** _There have been many requests from the community to be able to the control continuous 
refinement policy of underlying KStreams applications. `KTable#suppress` allows such
control and should be given corresponding KSQL syntax._

docs: klip-10 add suppress to KSQL

---

ksqldb-common/src/main/java/io/confluent/ksql/links/DocumentationLinks.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/DataSourceNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PlanNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/UserRepartitionNode.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json

partial fix for: https://github.com/confluentinc/ksql/issues/5466
This change adds the doc link to the error message reported when a projection fails to include the synthetic join key column.
usual

chore: add a link to docs when synth join key missing from projection

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/KsqlArray.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/KsqlObject.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/StructuredTypesDataProvider.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/KeyValueExtractor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java

Three changes in this PR:
(1) Prior to this PR, inserting a row with a complex column type (array, map, or struct) via /inserts-stream would fail since the SqlValueCoercer can't handle JsonArray or JsonObject. This PR fixes the bug.
(2)  This PR adds server-side and client-side test coverage for complex types including decimal, array, and map. A follow-up PR will add coverage for struct as well.
(3) Besides (1), the only other non-test change in this PR is in response to https://github.com/confluentinc/ksql/pull/5448#discussion_r429314072: rather than serializing BigDecimal as double on the client, we instead serialize BigDecimal as string in order to avoid loss of precision. The drawback is we now have an inconsistency where the decimal type is treated differently in terms of allowable …

fix: /inserts-stream endpoint now accepts complex types

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/BatchedQueryResult.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/BatchedQueryResultImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java

The query ID future was not being completed if the executeQuery() request failed. This PR fixes the issue. The new behavior is for the query ID future to be failed with the same exception as the BatchedQueryResult.
Added verification in unit and integration tests.

fix(client): fail queryID future if executeQuery() request fails (MINOR)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/InsertError.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlErrorMessage.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlStatementErrorMessage.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/KsqlErrorMessageTest.java

Fixes: https://github.com/confluentinc/ksql/issues/5398
As a general rule servers should log internal errors but not expose internal stack traces to clients. Sending stack traces to clients can create a security risk - stack traces expose implementation details of servers - libraries used, class names, private IP, paths, etc, that can potentially be used to compromise the server or leak information that the server administrator does not want to be public.
Updated tests

fix: Remove stacktrace from error message

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

The config name is `ksql.timestamp.throw.on.invalid` not `ksql.timestamp.skip.invalid`. Updated docstring accordingly.
Non-functional change

chore: fix typo in config docstring (MINOR)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/RequestValidator.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/QueryCapacityUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/RequestValidatorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/QueryCapacityUtilTest.java

Fixes https://github.com/confluentinc/ksql/issues/5454
**Problem**
Users were not able to execute the maximum number of queries allowed. It was always limit -1 queries permitted.
**Reason**
The `RequestValidator` class is checking if the user exceeded the maximum number of queries after the queries are validated and registered in the sandboxed query registry. This check was comparing the current values in the query registry + the new queries to execute. 
For instance, if the limit = 1 and there are no queries running, then the check was comparing 1 (new query added to the registry after validation) + 1 (new query already validated) > 1.
**Fix**
Check if the current values in the query registry exceeded the limit without adding again the new queries to execute. 
- Unit tests
- Manual tests

fix: KSQL does not accept queries when running QueryLimit - 1 queries

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/array/ArrayMax.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/array/ArrayMin.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/array/ArraySort.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/array/ArrayMaxTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/array/ArrayMinTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/array/ArraySortTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_max/6.0.0_1590779902575/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_max/6.0.0_1590779902575/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_max/6.0.0_1590779902575/topology
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_min/6.0.0_1590779902895/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_min/6.0.0_1590779902895/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_min/6.0.0_1590779902895/topology
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_sort_asc/6.0.0_1590779903355/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_sort_asc/6.0.0_1590779903355/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_sort_asc/6.0.0_1590779903355/topology
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_sort_desc/6.0.0_1590779903881/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_sort_desc/6.0.0_1590779903881/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-min-max-sort_-_array_sort_desc/6.0.0_1590779903881/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/array-min-max-sort.json

Three new UDFs for array manipulation: 
- array_min
- array_max
- array_sort
Docs updated.
Accompanying unit and QTT tests added.

feat: new UDFs for array max/min/sort

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/Cli.java

Fixes a bug where execution of a query from the console can cause a connection closed exception if executed very quickly after a previous query was terminated.
This is extremely unlikely to happen in real usage, but does happen intermittently in the test suite.
Fixes test

fix: Retry on connection closed

---

config/ksql-production-server.properties
config/ksql-server.properties

Sets all Kafka producers used by ksqlDB to use snappy compression to reduce the size across the wire and on-disk in the Kafka brokers. There is a slight hit to CPU load. However, its rare that turning compression on reduces throughput: almost universally it increases it.
Ensures this was flowing through to the producers

feat: turn on snappy compression for produced data

---

ksqldb-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java

https://github.com/apache/kafka/pull/8691/files
JMX reporter constructor deprecated

chore: update JmxReporter constructor due to deprecation

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/FilterNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/FinalProjectNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/FlatMapNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/OutputNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PreJoinProjectNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/ProjectNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/RepartitionNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/SingleSourcePlanNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/FinalProjectNodeTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/PreJoinProjectNodeTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/ProjectNodeTest.java

This change removes some duplication by adding an abstract `SingleSourcePlanNode` class to handle the common case of nodes that only have a single source node.
It also simplifies `PreJoinProjectNode` by moving the creation of the schema and select expressions into the class itself, removing the need to validate they match,
and simplifies the `FinalProjectNode`  by also removing unnecessary validation that the schema matches the selects, which is not needed as the class builds these.
The `PreJoinProjectNode` could also be simplified more as its not actually mutating the data, only the schema of the data, but this is left to another PR.
usual

refactor: remove duplicate code & unneeded validation from logical plan

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/context/QueryLoggerUtil.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationFactory.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationFactoryTest.java

This changes Pull Queries to use a fixed logger name rather than use the query id.  KSQL otherwise gets OOM Errors after doing high QPS for half an hour, due to creating so many unique loggers.
This is because both in the class `io.confluent.common.logging.StructuredLoggerFactory` and in the `slf4j` Logger factory itself, they keep a ConcurrentMap of name -> Logger to reuse loggers.  After many, many queries, you eventually get OOMs if you create a new one every pull query.
Fixes #5527 
Profiled memory before and after change.

fix: Prevent memory leaks caused by pull query logging

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryPublisher.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java

fixes: https://github.com/confluentinc/ksql/issues/5541
While push queries over http, and push queries over the new WS API, were both doing the right thing, missing test coverage on the old WS API allowed a change to go in that caused the old WS API to return a schema containing the key columns, even through the data does not.
usual

chore: push query websocket response should not include key columns

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Encode.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/EncodeTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_ascii/6.0.0_1591057476889/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_ascii/6.0.0_1591057476889/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_ascii/6.0.0_1591057476889/topology
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_base64/6.0.0_1591057476914/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_base64/6.0.0_1591057476914/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_base64/6.0.0_1591057476914/topology
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_hex/6.0.0_1591057476851/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_hex/6.0.0_1591057476851/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_hex/6.0.0_1591057476851/topology
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_null/6.0.0_1591203258645/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_null/6.0.0_1591203258645/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/encode_-_encode_null/6.0.0_1591203258645/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/encode.json

Fixes #5493
Add `encode` udf that encodes a string from an input encoding to another output encoding
QTT and Junit

feat: Add encode udf

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/LPad.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/RPad.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/LPadTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/RPadTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_all_args_from_record_-_JSON/6.0.0_1591214175122/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_all_args_from_record_-_JSON/6.0.0_1591214175122/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_all_args_from_record_-_JSON/6.0.0_1591214175122/topology
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_literal_args_-_JSON/6.0.0_1591214175189/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_literal_args_-_JSON/6.0.0_1591214175189/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_literal_args_-_JSON/6.0.0_1591214175189/topology
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_all_args_from_record_-_JSON/6.0.0_1591214175269/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_all_args_from_record_-_JSON/6.0.0_1591214175269/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_all_args_from_record_-_JSON/6.0.0_1591214175269/topology
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_literal_args_-_JSON/6.0.0_1591214175330/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_literal_args_-_JSON/6.0.0_1591214175330/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_literal_args_-_JSON/6.0.0_1591214175330/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/string-lpad-rpad.json

Simple string-padding functions based on the RDBMS stalwarts of the same names.
- `LPad(input_str, target_len, padding_str)`
- `RPad(input_str, target_len, padding_str)`
Docs, unit tests, QTT, historical plans for the above.

feat: new string UDFs LPad, RPad

---

ksqldb-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/test/java/io/confluent/ksql/metrics/MetricCollectorsTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java

Follow up to
https://github.com/apache/kafka/pull/8691/files
Updated unit tests to pass

feat: create MetricsContext for ksql metrics reporters

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PrintPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java

PRINT topic tries to determine the format of a topic's key and value.  Sometimes it can mis-detect the key. For example, if the key is a string, and the first value is `Die Hard` (as bytes) then it would interpret this as a `BIGINT` as its eight bytes.  Once it seems more rows it will likely work out the key is a `STRING`, (assuming at least one key is not 8bytes long.
With this change PRINT will process the whole batch of messages retrieved from the broker to determine the formats and only then output them. This makes it much more likely it will output the first few rows with the right formats, at the cost of formatting all the rows in the batch, even if the user only wanted to see one or two.
A good example of this can be seen in our own [Tumbling Windows …

fix: improve print topic

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtils.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtilsTest.java

There may be a bug with Kafka's handling of `Long.MAX_VALUE` as a topic retention. This PR is defensive in setting it to the documented value for infinite retention: `-1`
Unit testing, and spun up a new ksql server:
```
Topic: _confluent-ksql-default__command_topic	PartitionCount: 1	ReplicationFactor: 1	Configs: min.insync.replicas=1,cleanup.policy=delete,segment.bytes=1073741824,retention.ms=-1,unclean.leader.election.enable=false
```

fix: set retention.ms to -1 instead of Long.MAX_VALUE

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json

fixes: https://github.com/confluentinc/ksql/issues/5558
Tracked the issue down to a missing test case: can recreate the above issue by having a group by on the current key, i.e. no repartition needed, with the key in the projection.
usual

chore: fix regression in group by query is key in projection

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_udafs_only_in_having_(stream-_table)/6.0.0_1591618121193/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_udafs_only_in_having_(stream-_table)/6.0.0_1591618121193/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_udafs_only_in_having_(stream-_table)/6.0.0_1591618121193/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json

Note: stacked on top of https://github.com/confluentinc/ksql/pull/5566. Review that first!
fixes: #5557
Previously, a query such as:
```sql
CREATE TABLE OUTPUT AS
SELECT ID FROM INPUT
GROUP BY ID
HAVING SUM(COUNT) > 10;
```
Would have resulted in a schema of `ROWKEY STRING KEY, ID INT`. With the introduction of the 'any key name' feature the `ID` in the projection is no longer a value column: its a key column, so the resulting schema is: `ID INT KEY`, i.e. it has no value columns.
ksqlDB currently doesn't support data sources with no value columns. Hence the 'fix' here is to reject the above query with the error `The projection contains no value columns.`.  A longer term fix may be to support sources with no value columns: #5564.
The change includes tests to ensure transient push queries …

Agg no value columns

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestGeneratorTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestRewriterTest.java

We've two 'tests' that should never be enabled in the main build.  This change adds meta-tests to ensure that they are not enabled.

test: add meta tests to ensure user error

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtils.java

A misconfigured internal topic is something that can cause problems to a ksql cluster (e.g. missing retention on the command topic). This patch bumps of the level to WARN to make the message stand out a little more.
No functionality change

chore: change log level of re-configure internal topic to WARN

---

ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java

fixes: https://github.com/confluentinc/ksql/issues/5578
Pull queries on streams are not supported. So let's tell the user.
**Note: fix will be merging to 6.0.0 branch**
usual

chore: fix error msg for pull queries on streams

---

docs/tutorials/embedded-connect.md

The embedded connect tutorial was mostly updated for the new key syntax changes in https://github.com/confluentinc/ksql/pull/5363 but a spot was missed.
Ran through tutorial with new image.

docs: fix embedded connect tutorial for key syntax changes (MINOR)

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Chr.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/ChrTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_decimal_code_-_AVRO/6.0.0_1591421496995/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_decimal_code_-_AVRO/6.0.0_1591421496995/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_decimal_code_-_AVRO/6.0.0_1591421496995/topology
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_decimal_code_-_JSON/6.0.0_1591421497086/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_decimal_code_-_JSON/6.0.0_1591421497086/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_decimal_code_-_JSON/6.0.0_1591421497086/topology
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_text_code_-_AVRO/6.0.0_1591421497142/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_text_code_-_AVRO/6.0.0_1591421497142/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_text_code_-_AVRO/6.0.0_1591421497142/topology
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_text_code_-_JSON/6.0.0_1591421497199/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_text_code_-_JSON/6.0.0_1591421497199/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_codepoint_from_text_code_-_JSON/6.0.0_1591421497199/topology
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_multiple_invocations_-_AVRO/6.0.0_1591421497279/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_multiple_invocations_-_AVRO/6.0.0_1591421497279/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_multiple_invocations_-_AVRO/6.0.0_1591421497279/topology
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_multiple_invocations_-_JSON/6.0.0_1591421497385/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_multiple_invocations_-_JSON/6.0.0_1591421497385/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/chr_-_multiple_invocations_-_JSON/6.0.0_1591421497385/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/chr.json

A new UDF, `CHR`, to turn a number representing a unicode codepoint into a single-character string. Very useful for dealing with non-printable characters (tab, CR, LF, ...) in strings or those characters not easily represented in your local codepage.
New Unit and QTT tests with historical plans

feat: add CHR UDF

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/SplitToMap.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/SplitToMapTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/split-to-map_-_split_to_map/6.0.0_1591481024082/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/split-to-map_-_split_to_map/6.0.0_1591481024082/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/split-to-map_-_split_to_map/6.0.0_1591481024082/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/split-to-map.json

New UDF  `split_to_map(input, entryDelimiter, kvDelimiter)` to build a map from a string. 
Useful for taking messages from upstream systems and converting them into a more structured and usable format.
New Unit & QTT tests.

feat: new split_to_map udf

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/array/ArrayJoin.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/array/ArrayJoinTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_custom_delimiters/6.0.0_1591955240274/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_custom_delimiters/6.0.0_1591955240274/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_custom_delimiters/6.0.0_1591955240274/topology
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_default_delimiter/6.0.0_1591953360045/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_default_delimiter/6.0.0_1591953360045/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_default_delimiter/6.0.0_1591953360045/topology
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_empty_or_null_delimiter/6.0.0_1591955240399/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_empty_or_null_delimiter/6.0.0_1591955240399/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_empty_or_null_delimiter/6.0.0_1591955240399/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/arrayjoin.json

This PR implements the UDF / scalar function ARRAY_JOIN as requested in (#5028). It creates a flat string representation of all the elements contained in the given array.
There are unit tests with several applications of the UDF to verify that it follows the expected behaviour as discussed in the linked issue.

feat: implements ARRAY_JOIN as requested in (#5028)

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/StructuredTypesDataProvider.java
ksqldb-parser/src/main/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercer.java
ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksqldb-parser/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/InsertsStreamEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/InsertsSubscriber.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/KeyValueExtractor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerUtils.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java

Fixes https://github.com/confluentinc/ksql/issues/5620 and adds a lot more test coverage, not only for structs for also for other nested types: array of arrays, array of maps, array of structs, map of arrays, map of maps, map of structs, etc.
This fix turned out to be a lot larger than I had hoped in order to accommodate the following constraints of the /inserts-stream endpoint:
- column names are case-insensitive (unless quoted)
- struct field names are case-insensitive (unless quoted)
- map keys are case-sensitive
- struct and map types are both represented as JsonObject (KsqlObject for client)
- strings and doubles may be coerced to decimal types only for the /inserts-stream endpoint, not other uses of DefaultSqlValueCoercer. This constraint is required as JsonObject does not support …

fix: /inserts-stream endpoint now supports nested types

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaClusterUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/security/KsqlAuthorizationValidatorFactoryTest.java

Old version of kafka brokers (e.g. AK 1.1.0) don't support this describe operation and will cause the ksqlDB cluster to fail to startup. This PR prevents that.
Unit testing & hit debug point to make sure that the branch was being hit

fix: don't fail if broker does not support AuthorizedOperations

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/array/ArrayJoin.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/array/ArrayJoinTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_custom_delimiters/6.0.0_1591955240274/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_custom_delimiters/6.0.0_1591955240274/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_custom_delimiters/6.0.0_1591955240274/topology
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_default_delimiter/6.0.0_1591953360045/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_default_delimiter/6.0.0_1591953360045/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_default_delimiter/6.0.0_1591953360045/topology
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_empty_or_null_delimiter/6.0.0_1591955240399/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_empty_or_null_delimiter/6.0.0_1591955240399/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/arrayjoin_-_join_flat_arrays_with_primitive_ksqldb_types_and_empty_or_null_delimiter/6.0.0_1591955240399/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/arrayjoin.json

feat: implements ARRAY_JOIN as requested in (#5028) (#5474)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactory.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactoryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

fixes: https://github.com/confluentinc/ksql/issues/5643
Ensures all commands written to the command topic can be deserialized before writing them.
A non-deserializable command causes the command runner thread to die.
Even restarting the server won't help as the server will stop when it hits the non-deserializable command again.
This adds some level of protection.
(I know I'd previously been against this, but ... meh... maybe I was wrong ;) )
Submitting a statement to the server which the server finds it can't deserialize now results in an error and the command is, importantly, not added to the command queue:
```bash
ksql> CREATE TABLE OUTPUT as SELECT 1 as k, count(1) AS ID FROM INPUT group by 1;
Did not write the command to the command topic as it could not be deserialized. This is a …
```

fix: ensure only deserializable cmds are written to command topic

---

docs/developer-guide/test-and-debug/processing-log.md

The target moved 14 days ago when cp-demo was refactored.
Cherry-pick to master, 0.10.0-ksqldb, 0.9.0-ksqldb, 0.8.1-ksqldb, and 0.7.1-ksqldb.

docs: fix broken link to log4j-secure.properties (DOCS-4649)

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamAggregate.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamFlatMap.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamGroupBy.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSelect.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamWindowedAggregate.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/TableAggregate.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/TableGroupBy.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/TableSelect.java
ksqldb-functional-tests/src/test/resources/historical_plans/count_-_auto-incrementing_id/6.1.0_1592505898364/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/count_-_auto-incrementing_id/6.1.0_1592505898364/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/count_-_auto-incrementing_id/6.1.0_1592505898364/topology
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_zero_non-agg_columns_(stream)/6.1.0_1592505909615/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_zero_non-agg_columns_(stream)/6.1.0_1592505909615/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_zero_non-agg_columns_(stream)/6.1.0_1592505909615/topology
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_zero_non-agg_columns_(table)/6.1.0_1592505909879/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_zero_non-agg_columns_(table)/6.1.0_1592505909879/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_zero_non-agg_columns_(table)/6.1.0_1592505909879/topology
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_zero_non-agg_columns_(windowed_stream)/6.1.0_1592505909663/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_zero_non-agg_columns_(windowed_stream)/6.1.0_1592505909663/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_zero_non-agg_columns_(windowed_stream)/6.1.0_1592505909663/topology
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_clone_row_with_null_value/6.1.0_1592505929318/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_clone_row_with_null_value/6.1.0_1592505929318/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_clone_row_with_null_value/6.1.0_1592505929318/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/count.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/null.json

fixes:  https://github.com/confluentinc/ksql/issues/5643
Adds support for a `GROUP BY` query where there are no source columns used in the query, e.g.
```sql
CREATE TABLE OUTPUT as SELECT 1 as k, count(1) AS ID FROM INPUT group by 1;
```
This was previously failing as it ran into an issue deserializing the query plan due to `nonAggColumns` not being present in the plan.
usual

fix: support GROUP BY with no source columns used

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/connect/SqlSchemaFormatter.java
ksqldb-common/src/test/java/io/confluent/ksql/schema/connect/SqlSchemaFormatterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorFunctionalTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/create-struct_-_empty_struct_creation/5.5.0_1581572087372/spec.json

Previously, empty structs would be formatted as `STRUCT<>` in the `SqlSchemaFormatter` (which for some reason is used independently of `SqlFormatter`, we should dig into that) which would cause parsing to fail because `<>` is it's own symbol for "not equal to".
This code path was not used in master after https://github.com/confluentinc/ksql/pull/4637 so it was no longer happening. That change has a relatively large surface area, so for the backport I am making the most targeted change possible to address the edge case.
Added a unit test, which fails before this fix.

fix: allow empty structs in schema inference

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/SystemAuthenticationFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/utils/TestUtils.java

Slows heartbeating which was making SSL handshakes timeout.
Also, adds a new ephemeral port picker.  This is useful for picking a port at random to avoid teardown/setup issues that can cause flakiness.
Ran test.

test: Fixes test SystemAuthenticationFunctionalTest by slowing heartbeating

---

design-proposals/klip-28-create-or-replace
design-proposals/klip-28-create-or-replace.md

https://github.com/agavra/ksql/blob/aed31a2478e49956e469d11e11bccf74ef5c472c/design-proposals/klip-28-create-or-replace

docs: KLIP-28 introduce CREATE OR REPLACE

---

docs/developer-guide/ksqldb-clients/java-client.md

- server endpoint links will be added back once the server endpoint docs have been merged
- API links will be added back once the API docs have been published and I've verified the paths for these new docs.

docs: remove server endpoint + API links from client docs (MINOR)

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/StatementRewriter.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionNameValidator.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/StatementRewriterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/FunctionNameValidatorTest.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateAsSelect.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateSource.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStream.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStreamAsSelect.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTable.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTableAsSelect.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/CreateSourceTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/CreateStreamAsSelectTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/CreateStreamTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/CreateTableAsSelectTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/CreateTableTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

Adds the syntax for `CREATE OR REPLACE`
Unit testing and end-to-end UX testing:
```
ksql> CREATE OR REPLACE STREAM FOO (id VARCHAR) WITH (KAFKA_TOPIC='foo', VALUE_FORMAT='json', partitions=1);
Failed to prepare statement: CREATE OR REPLACE is not yet supported.
```

chore: add CREATE OR RPLEACE to the syntax

---

ksqldb-common/src/main/java/io/confluent/ksql/links/DocumentationLinks.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/PullQueryValidator.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java

fixes: https://github.com/confluentinc/ksql/issues/3615
Simplifies the error message when an invalid pull query is issued. Importantly, the phase
```
Add EMIT CHANGES if you intended to issue a push query.
```
Is the second line in every case. Hopefully calling out what needs to be done if the user meant to issue a push query.
Usual

fix: simplify pull query error message

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java

We're getting periodic build failures in master due to the timeout being to tight (10 seconds).  Increasing to 30 seconds.

test: increase RQTT timeout

---

docs/developer-guide/ksqldb-clients/java-client.md

From https://github.com/confluentinc/ksql/pull/5668.

docs: cherry-pick: remove server endpoint + API links from client docs (MINOR) (DOCS-4734)

---

docs/concepts/queries/pull.md
docs/developer-guide/ksqldb-reference/select-pull-query.md
ksqldb-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializationFunctionalTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/MaterializedWindowedTable.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedSessionTable.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedWindowTable.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedSessionTableTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedWindowTableTest.java

fixes: https://github.com/confluentinc/ksql/issues/5666
Pull queries can now reference WINDOWEND in their WHERE clause, (assuming the source is windowed):
```sql
SELECT * FROM T
WHERE id = 10
AND 134874632 <= WINDOWSTART AND WINDOWEND < 134891111;
```
usual

feat: support WINDOWEND in WHERE of pull queries

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

Also remove some extraneous backtick chars.

docs: move ARRAY_JOIN scalar function in TOC (DOCS-4745)

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientOptionsImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ColumnTypeImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/RowImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/StreamInfoImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/TableInfoImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/TopicInfoImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ClientImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ClientOptionsImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ColumnTypeImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/RowImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/StreamInfoImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/TableInfoImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/TopicInfoImplTest.java

Context: https://github.com/confluentinc/ksql/pull/5671#discussion_r444563599

chore: add equals, hashCode, and toString methods to client interface impls

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java

We've seen some flaky failures of the recently added `ClientIntegrationTest#shouldListQueries()` integration test. This PR temporarily disables the test while I investigate offline, in order to not affect master (and PR) builds.
N/A

test: temporarily disable flaky test while it's being investigated

---

docs/developer-guide/ksqldb-clients/java-client.md

Adds back the links that were removed in https://github.com/confluentinc/ksql/pull/5668, now that the server endpoint docs and client API docs are both live.
@JimGalasyn we'll need to cherry-pick this to 0.10.0-ksqldb once it's merged. I'm happy to help if you're swamped -- LMK :)

docs: add back server endpoint + API links to client docs (MINOR)

---

docs/developer-guide/ksqldb-clients/java-client.md

Cherry-pick https://github.com/confluentinc/ksql/pull/5699 to live docs branch.

docs: cherry-pick "add back server endpoint + API links to client docs"

---

docs/developer-guide/joins/partition-data.md
docs/developer-guide/ksqldb-clients/java-client.md

From https://github.com/confluentinc/ksql/pull/5708.

docs: cherry-pick: fix broken links in ksqldb-clients content (DOCS-4757)

---

docs/developer-guide/ksqldb-clients/java-client.md

^ to link to docs rather than API docs. I think it's preferable to keep the users within the actual docs, especially since the docs for each section link to the relevant API docs page as well. 

docs: update links in client docs (MINOR)

---

docs/developer-guide/ksqldb-clients/java-client.md

The example pom in the Java client docs doesn't work out of the box since it doesn't specify where to find the client jar. This PR adds the necessary repos.
Docs-only change. Followed example with new pom (and fresh .m2) to ensure dependency is found.

docs: add maven repo to Java client docs example

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java

Fix the master build by switching ksqlDB code to use the non-deprecated streams config
none

chore: switch to non-deprecated streams config

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/SearchedCaseFunction.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/helpers/SearchedCaseFunctionTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/case-expression_-_as_param_to_UDAF/6.1.0_1593191100221/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/case-expression_-_as_param_to_UDAF/6.1.0_1593191100221/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/case-expression_-_as_param_to_UDAF/6.1.0_1593191100221/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/case-expression.json

fixes: https://github.com/confluentinc/ksql/issues/5700
usual

fix: support CASE statements returning NULL

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java

The recently added ClientIntegrationTest#shouldListQueries() previously sometimes failed because queries started (and terminated) by other tests took time to actually be removed from the server's metastore, as this process is async after termination. This caused ClientIntegrationTest#shouldListQueries() to fail because the test checked that there was only one query in the metastore. This PR fixes the flakiness by switching to assertThatEventually() instead of assertThat().
Test-only change. Ran the test a bunch of times locally and didn't see any failures.

test: fix flaky ClientIntegrationTest#shouldListQueries() (MINOR)

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryIdUtil.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlBareOutputNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/OutputNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/QueryIdUtilTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/FunctionNameValidatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlBareOutputNodeTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/testutils/AnalysisTestUtil.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateAsSelect.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStreamAsSelect.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTableAsSelect.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/InsertInto.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/Sink.java

This is a minor refactor which moves queryID generation outside of the physical plan into a place that is better suited for "replace" style queries which reuse the existing queryID. The query id generation is now done in `EngineExecutor` (there is also no queryId generation in `QueryMetadata` anymore.
Non-functional change, moved unit tests as appropriate.

refactor: move queryID generator out of physical plan

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PlanNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/PlanNodeTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_matching_columns_in_both_sides_=_select_left.__and_right.__with_WHERE/6.0.0_1593039433111/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_matching_columns_in_both_sides_=_select_left.__and_right.__with_WHERE/6.0.0_1593039433111/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_matching_columns_in_both_sides_=_select_left.__and_right.__with_WHERE/6.0.0_1593039433111/topology
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_scoped_include_all_columns/6.0.0_1593098410884/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_scoped_include_all_columns/6.0.0_1593098410884/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_scoped_include_all_columns/6.0.0_1593098410884/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json

https://github.com/confluentinc/ksql/issues/5503
This fixes a regression introduced in 0.10.
The implications of this are not that it crashes the command runner thread, as the original ticket states. Instead, the implications are that queries a users could previously run will now fail. Existing running queries will not be affected.
Affected queries will be any using combining:
* A join
* with a projection using a scoped 'all columns', e.g. a A.*
* with a where clause
e.g.
```sql
SELECT A.*, B.Id
FROM A
JOIN B ON A.Id = B.userId
WHERE A.x < 10;
```
Such queries now work.
Usual

fix: query w/ scoped all columns, join and where clause

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

Fixes missing constructor in the reference docs.

docs: fix incorrect code in array_contains reference

---

config/ksql-server.properties
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/OldApiUtils.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ResponseOutputStream.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/Server.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java

Fixes https://github.com/confluentinc/ksql/issues/5724
The ksqlDB CLI currently uses the old query streaming API at /query.
When terminating a query from the CLI, the connection is closed. The close is detected in the QueryStreamWriter poll loop which causes it to flush the OutputStream. This causes a write to be called on the underlying ResponseOutputStream, but because the channel isn't available for writing writeQueueFull() returns true and the thread is blocked until it times out (previously 60 seconds). This means that, previously, if you start and terminate queries quite rapidly, it takes 60 seconds for each ones state to be cleared up on the server. 
This PR changes the blocking in ResponseOutputStream so it can return more quickly if the stream is closed. It also changes the …

fix: make sure old query stream doesn't block on close

---

CHANGELOG.md
docs/operate-and-deploy/installation/upgrading.md

Add some upgrade notes for 0.9 to 0.10 around changes in sql syntax.
Note: this also pulls in the 0.10 changelog to the branch, as this was easier having to change the upgrade notes in one branch and the changelog notes in the master branch.
Note: most of the docs added here are already available in the master branches CHANGELOG.md. All I’ve done is move them into the upgrading.md in the 6.0 branch.
@JimGalasyn not sure if this needs merge to any -post branches to be picked up by the micro site?

docs: add upgrade notes for 0.9 - 0.10

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java

fixes #5553 
This commit makes sure that `C*` statements do not overwrite existing schemas in schema registry and instead only check compatibility with a declared schema, if a declared schema is present.
**NOTE**: if you `INSERT INTO` a stream, all bets are off (i.e. another schema will be registered under the schema value, but that is not a regression as this is a serializer-specific behavior) 
Unit tests, and manual testing (registered the same source with a subset schema and confirmed there's only one version in schema registry)

fix: do not overwrite schemas from a CREATE STREAM/TABLE

---

ksql-engine/src/main/java/io/confluent/ksql/function/udf/json/ArrayContainsKudf.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/ConfigTopicKeyTest.java

Port of https://github.com/confluentinc/ksql/pull/4671 to the 5.4.x release branch, required by upgrades in jackson and avro described in: confluentinc/common#269
Relying on existing tests

chore: Remove use of deprecated Jackson API in 5.4.x

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/ConnectSerdeSupplier.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/Record.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopicInfoCache.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/model/RecordNodeTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestJsonMapperTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_AVRO_should_not_trim_trailing_zeros/6.1.0_1593789506560/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_AVRO_should_not_trim_trailing_zeros/6.1.0_1593789506560/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_AVRO_should_not_trim_trailing_zeros/6.1.0_1593789506560/topology
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_DELIMITED_should_not_trim_trailing_zeros/6.1.0_1593789506587/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_DELIMITED_should_not_trim_trailing_zeros/6.1.0_1593789506587/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_DELIMITED_should_not_trim_trailing_zeros/6.1.0_1593789506587/topology
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_SR_should_not_trim_trailing_zeros/6.1.0_1593789506613/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_SR_should_not_trim_trailing_zeros/6.1.0_1593789506613/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_SR_should_not_trim_trailing_zeros/6.1.0_1593789506613/topology
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1583419431528/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1589910855902/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_should_not_trim_trailing_zeros/6.1.0_1593789506599/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_should_not_trim_trailing_zeros/6.1.0_1593789506599/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_should_not_trim_trailing_zeros/6.1.0_1593789506599/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/decimal.json

fixes: https://github.com/confluentinc/ksql/issues/4710
Fixes the `JSON` / `JSON_SR` formats to not remove trailing zeros from decimal values, e.g. `14.7600` should be processed and seriailized as `14.6700` and _not_ `14.67`.
usual

fix: ksqlDB should not truncate decimals

---

ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/ddl/commands/CreateSourceCommand.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/ddl/commands/CreateSourceCommandTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_stream_without_key/6.1.0_1593781702978/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_stream_without_key/6.1.0_1593781702978/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_stream_without_key/6.1.0_1593781702978/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/elements.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/table-functions.json
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java

fixes: #5723
UDTFs didn't work with new keyless streams. This change fixes this.
Plus, adds an error message if you try and create a windowed stream without a key. This previously resulted in an NPE during processing.
usual

Keyless udtf

---

pom.xml

Running:
`mvn --batch-mode versions:set-property -Dproperty=kafka.version -DnewVersion=<version> -DgenerateBackupPoms=false`
does nothing currently since the property doesn't exist. Adding the property so we can override it manually when needed.
Ran the command above and verified the kafka version was set to what was specified

chore: add kafka.version as property

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/topic/TopicCreateInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/topic/TopicCreateInjectorTest.java

Fixes https://github.com/confluentinc/ksql/issues/5554
BREAKING CHANGE: ksqlDB now creates windowed tables with cleanup policy "compact,delete", rather than "compact". Also, topics that back streams are always created with cleanup policy "delete", rather than the broker default (by default, "delete").
Unit tests + manual.

fix: windowed tables now have cleanup policy compact+delete

---

pom.xml

- Confluent repackaged version fixes CVE-2019-17571
- `common/pom.xml` excludes default log4j as a transitive dependency, and the repackaged version must be explicitly added.
Ref: https://github.com/confluentinc/common/pull/270

fix: SEC-1034: log4j migration to confluent repackaged version

---

ksqldb-common/src/main/java/io/confluent/ksql/util/ErrorMessageUtil.java
ksqldb-common/src/test/java/io/confluent/ksql/util/ErrorMessageUtilTest.java

Addresses: https://github.com/confluentinc/ksql/issues/5599
Error message is now
```
ksql> show topics;
Error issuing POST to KSQL server. path:/ksql
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException:
Connection refused: localhost/127.0.0.1:8088
Caused by: Could not connect to the server. Please check the server details are
correct and that the server is running.
```
I don't think the dedup function was working as intended so I updated it. 
Manual verification

chore: ErrorMessageUtil dedups error messages properly

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/Server.java
pom.xml

Fixes: https://github.com/confluentinc/ksql/issues/5799
This PR:
1. Upgrades to Vert.x 3.9.1. This depends on Netty 4.1.49.Final which includes code which allows the backported ALPN implementation that is present in JDK 1.8.0_252 to be used. This means that if the user has configured ksqlDB for TLS and does not have OpenSSL installed and is using an up to date version of Java 8 then ksqlDB will successfully fall back to using the JDK TLS implementation and the ALPN implementation that was backported to Open JDK 1.8.0_252 from OpenJDK 9. Users with older versions of Java 8 should update their Java 8 version.
2. Logs a warning if OpenSSL is not installed. It's preferable to use OpenSSL for performance reasons. Most systems will have this pre-installed, but if not a warning will be logged so …

fix: Allow backported ALPN to be used and warn if no OpenSSL

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-common/src/main/java/io/confluent/ksql/query/QueryId.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/CommandStatus.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/CommandStatusEntityTest.java

This PR adds QueryId into CommandStatus in order to expose QueryId from CommandStatusEntity.
Motivation is as follows: When a CSAS/CTAS/INSERT INTO command is executed from the CLI, the user sees a message containing the ID of the newly created query:
```
ksql> create stream log_copy as select * from ksql_processing_log;
Message
---------------------------------------
Created query with ID CSAS_LOG_COPY_0
---------------------------------------
```
We'd like to also return the query ID from the Java client. However, the server response doesn't directly expose the query ID at the moment. Instead, the way the CLI prints that message is by directly printing the status message returned from the server, which happens to contain the query ID if the command status is `EXECUTED`. We could have …

feat: expose query ID in CommandStatusEntity (MINOR)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFunctionalTest.java

The expected error message for this test has changed as of a result of https://github.com/confluentinc/schema-registry/pull/1536. Here's the relevant switch statement in ksqlDB: https://github.com/confluentinc/ksql/blob/bb2918508f8451c9cea93736b65f0c71cc074ff1/ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplier.java#L73-L80

test: fix SR test in light of updated error code (MINOR)

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/ExecuteStatementResult.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/DdlDmlRequestValidators.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/DdlDmlResponseHandlers.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ExecuteStatementResultImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ExecuteStatementResultImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java

This PR is stacked on https://github.com/confluentinc/ksql/pull/5775 and https://github.com/confluentinc/ksql/pull/5814 -- only the [latest commit (`feat(client): return query ID when persistent query started via Java client`)](https://github.com/confluentinc/ksql/pull/5816/commits/c2a032ec529494ee99a8673d62e3cfddf1088a85) needs to be reviewed.
This PR uses the new query ID field added to CommandStatusEntity in https://github.com/confluentinc/ksql/pull/5814 to return the query ID for persistent queries started with the `executeStatement()` method of the Java client. This is useful so client apps can easily terminate new persistent queries. The javadocs on the new `ExecuteStatementResult` interface explain the new behavior in more detail.
Added unit and integration tests.

feat(client): return query ID when persistent query started via Java client

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/decimal.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactory.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactoryTest.java

fixes: #5784
Error message is no longer:
```
Caused by: java.lang.RuntimeException: Unexpected BYTES type null
```
It is now:
```
The 'PROTOBUF' format does not support type 'DECIMAL'. See #5762.
```
usual

 fix: better error on DECIMAL type with PROTOBUF format

---

ksqldb-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutorFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFactoryTest.java

- lower case the resource type
- adds the following configs to ksqlConfig when initializing KSQL for either headless or interactive mode so that all components get the same base set of labels
```
metrics.context.resource.kafka.cluster.id
metrics.context.resource.type
metrics.context.resource.cluster.id
metrics.context.resource.version
metrics.context.resource.commit.id
```
Rechecking labels present in the staging URL for Druid

chore: update KSQL metrics context labels

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/ddl/commands/KsqlTopic.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/timestamp/TimestampColumn.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/model/DataSource.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/model/StructuredDataSource.java
ksqldb-metastore/src/test/java/io/confluent/ksql/metastore/model/StructuredDataSourceTest.java

The next step in the `CREATE OR REPLACE` saga, this validates that the upgrades are compatible from a schema perspective. It does not yet implement the physical plan check to make sure that we allow the topology evolution.
More unit testing

chore: add validation to the metastore for create or replace

---

ksqldb-serde/src/main/java/io/confluent/ksql/logging/processing/LoggingDeserializer.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/StaticTopicSerde.java
ksqldb-serde/src/test/java/io/confluent/ksql/logging/processing/LoggingDeserializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/StaticTopicSerdeTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/RegisterSchemaCallback.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/RegisterSchemaCallbackTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java

fixes #5673 
replaces #5812 
This commit takes a different approach to fixing the issue described in the two links above; we will hardcode the serializer for source tables to use the changelog topic, and we allow the deserializer to fallback to the source topic if it fails to deserialize using the changelog topic.
This fixes the issue by obviating https://github.com/apache/kafka/pull/8902/ - all queries that were created before #5781 was merged will always pass in the changelog topic to their state store serde. This means that:
1. we will never register a schema to the user's subject unless they use `INSERT INTO`
2. we will be able to deserialize events in the state store if the schema ID for the event is in either subject
3. if we ever encounter an event we could not serialize using the …

fix: always use the changelog subject in table state stores

---

ksqldb-engine/src/main/java/io/confluent/ksql/topic/TopicCreateInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/topic/TopicCreateInjectorTest.java

Fixes https://github.com/confluentinc/ksql/issues/5605
Previously, ksqlDB was not configuring topic retention when creating topics for windowed tables. This PR fixes that.
Unit tests + manual.

fix: configure topic retention based on retention clause for windowed tables

---

docs/tutorials/event-driven-microservice.md

Fixes https://github.com/confluentinc/ksql/issues/5827
Increases the window retention of our event-driven tutorial so that the fixed timestamps won't be deleted by the log cleaner.

docs: updates tutorial for longer retention spans

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/BackupReplayFile.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopic.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicBackup.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicBackupImpl.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicBackupNoOp.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/QueuedCommand.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/BackupReplayFileTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicBackupImplTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicBackupTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicTest.java

Implements KLIP-31: Metastore Backups - https://github.com/confluentinc/ksql/pull/5741
Add a metastore backup service that replays the command_topic to a local file. This local file will be useful to users who desire to restore their command_topic in case of accidental topic disasters.
Two new configs are added to enable backups (see `KsqlConfig`):
- `ksql.enable.metastore.backup` to enable the metastore backup
- `ksql.metastore.backup.location` to specify the location of the backup
Two new classes are created:
- `CommandTopicBackup`
- `BackupReplayFile`
The `CommandTopicBackup` is the service used to backup command topic records through the `writeRecord` method. It is called by the `CommandTopic` class on each record read by the Kafka consumer (see `getRestoreCommands` and …

feat: Replay command topic to local file to backup KSQL Metastore

---

design-proposals/klip-31-metastore-backups.md

Request for comment of KLIP-31.

docs: klip-31: Metastore Backups

---

ksqldb-docker/Dockerfile

The PR reverts https://github.com/confluentinc/ksql/pull/5829, as we've decided to leave confluent-hub in both the standalone and CP images.
Image builds.

chore: revert "remove confluent-hub from ksqlDB image"

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/topic/TopicCreateInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/topic/TopicCreateInjectorTest.java

Backport https://github.com/confluentinc/ksql/pull/5743 and https://github.com/confluentinc/ksql/pull/5835 to complete the feature implemented in https://github.com/confluentinc/ksql/pull/4733/files.
Unit tests have also been backported. Also did a manual sanity check.

chore: backport windowed table topic retention fixes

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/array/ArrayRemove.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/array/ArrayRemoveTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/array-remove_-_array_remove_with_all_primitive_types/6.1.0_1594957049270/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-remove_-_array_remove_with_all_primitive_types/6.1.0_1594957049270/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-remove_-_array_remove_with_all_primitive_types/6.1.0_1594957049270/topology
ksqldb-functional-tests/src/test/resources/historical_plans/array-remove_-_array_remove_with_complex_types/6.1.0_1594957049604/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-remove_-_array_remove_with_complex_types/6.1.0_1594957049604/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-remove_-_array_remove_with_complex_types/6.1.0_1594957049604/topology
ksqldb-functional-tests/src/test/resources/historical_plans/array-remove_-_array_remove_with_literal_array/6.1.0_1594957049161/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-remove_-_array_remove_with_literal_array/6.1.0_1594957049161/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-remove_-_array_remove_with_literal_array/6.1.0_1594957049161/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/array-remove.json

Just when you thought there couldn't possibly be any more array UDFs required...
`array_remove( array, element)` removes all elements equal to `element` from `array`.
Unit & QTT tests plus historical plans for the same.
Scalar-functions doc page updated.

feat: new array_remove udf

---

docs/developer-guide/index.md
docs/developer-guide/ksqldb-reference/drop-stream.md
docs/developer-guide/ksqldb-reference/drop-type.md
docs/developer-guide/ksqldb-reference/index.md
docs/developer-guide/ksqldb-reference/print.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-pull-query.md
docs/developer-guide/ksqldb-reference/select-push-query.md
docs/developer-guide/ksqldb-reference/show-topics.md
docs/developer-guide/quick-reference.md
docs/developer-guide/syntax-reference.md
mkdocs.yml

Add a topic that collects all of the ksqlDB keywords, statements, and commands into a single list that shows syntax and also can be an index into the reference content. Similar to [SQL Quick Reference from W3Schools](https://www.w3schools.com/sql/sql_quickref.asp). Plus assorted minor bug fixes that I encountered along the way.

docs: add quick reference guide for ksqlDB SQL syntax

---

docs/developer-guide/index.md
docs/developer-guide/ksqldb-reference/drop-stream.md
docs/developer-guide/ksqldb-reference/drop-type.md
docs/developer-guide/ksqldb-reference/index.md
docs/developer-guide/ksqldb-reference/print.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-pull-query.md
docs/developer-guide/ksqldb-reference/select-push-query.md
docs/developer-guide/ksqldb-reference/show-topics.md
docs/developer-guide/syntax-reference.md
mkdocs.yml

* docs: add quick reference guide for syntax
* docs: move new quick-reference page to ref section

docs: cherry-pick: add quick reference guide for ksqlDB SQL syntax (DOCS-4923)

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/MissingTopicClassifier.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/RegisterSchemaCallback.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/RegisterSchemaCallbackTest.java

It is possible that due to #5823 we will attempt to register the same schema over and over again when a de-serialization failure happens if the schemas are incompatible. This PR limits the number of attempts to one.
Unit testing

chore: do not try to re-register schema multiple times on failure

---

docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md

Leftover from the big conversion to markdown.

docs: fix link in ksql-endpoint topic (DOCS-4916)

---

docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/developer-guide/ksqldb-reference/quick-reference.md

From https://github.com/confluentinc/ksql/pull/5862.

docs: cherry-pick: clarify syntax for KEY in CS statement (DOCS-4934)

---

docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/developer-guide/ksqldb-reference/quick-reference.md

From https://github.com/confluentinc/ksql/pull/5863.

docs: cherry-pick: clarify syntax for KEY in CS statement (DOCS-4935)

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java

We shouldn't be using `listTopics` to determine whether or not a single topic exists. This PR changes it to use the `describeTopics` API to check for only a single topic.
Unit tests

chore: dont list all topics to determine single topic existence (MINOR)

---

docs/developer-guide/ksqldb-clients/java-client.md
mkdocs.yml

Until we're able to publish beta CP dependencies for standalone ksqlDB releases to a stable repo, we'll have to update the dependency version on each release. This PR pulls the version into a mkdocs variable to make this easier (and make it so we're less likely to forget).
This needs to be cherry-picked to `0.11.x-ksqldb`. I'll do that once this PR is approved and merged.

docs: update beta CP dependencies for 0.11.0 (MINOR)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicBackupImpl.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicBackupImplTest.java

Creates the KSQL metastore backups directory if it does not exist. It also checks the existing directory is readable and writeable. 
Unit tests

fix: create the metastore backups directory if it does not exist

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/RewrittenAnalysis.java
ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/RewrittenAnalysisTest.java

When `EMIT FINAL` is used appropriately on a windowed aggregation, but no grace period specified, the previous behavior made the default grace period to be 24h. This patch changes this default to 0.
Created `RewrittenAnalysisTest` and added relevant unit tests

fix: change default grace period to zero

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/OldApiUtils.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/StreamingOutput.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

Fixes https://github.com/confluentinc/ksql/issues/5881.
The bug is that the close callback passed to the QueryStreamWriter/TopicStreamWriter sets a flag (`connectionClosed`) that causes the `write()` loop to end and close the underlying Kafka Streams app/Kafka consumer, but when HTTP/2 is used, `write()` is never called so this doesn't happen even though the `connectionClosed` flag is set. This PR fixes the bug by introducing a new method, `closeWithoutWrite()`, that directly closes the underlying Kafka Streams app/Kafka consumer and is called when the 405 response is returned (upon discovering an HTTP/2 request to the /query endpoint for a request type that requires an HTTP streaming response).
Manual + integration tests.

fix: close query on invalid use of HTTP/2 with /query endpoint

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/OldApiUtils.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/StreamingOutput.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamWriter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

Backport https://github.com/confluentinc/ksql/pull/5883 to 6.0.x
Manual + integration tests.

fix: close query on invalid use of HTTP/2 with /query endpoint (6.0.x)

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/ReplaceIntTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/ExecutionStep.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamFilter.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSelect.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSink.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSource.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestUtils.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/upgrades.json
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java

This PR introduces the physical plan validation framework for query upgrades, and the most basic set of validations for stream upgrades involving filters/selects. To avoid making this PR too large, all other upgrades are omitted. 
The validation strategy is documented in `ExecutionStep#validateUpgrade`
QTT tests to make sure that expected upgrades succeed/fail respectively.

chore: introduce physical plan upgrade validation for basic upgrades

---

docs/developer-guide/ksqldb-clients/java-client.md

The Java client docs are geared towards usage with standalone ksqlDB. This PR adds a note for how the client may be used with CP, and also backports a minor clarification from master.
I'm going to merge this change forward into master after merging to 6.0.x, even though it should NOT go live until CP 6.0 is released. This should be fine since CP 6.0 is scheduled for before ksqlDB 0.12.0.

docs: add note for java client CP pom

---

docs/developer-guide/ksqldb-reference/operators.md
docs/developer-guide/syntax-reference.md

Puts STRUCT content under one heading, plus various other tweaks.

docs: consolidate STRUCT content in syntax reference (DOCS-4995)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/ConnectExecutable.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/Executable.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MultiExecutable.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlServerMainTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/MultiExecutableTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

Couple changes related to application lifecycle management. Firstly, adds a shutdown handler
that gracefully shuts down the service when the jvm determines its time to shut down (e.g.
when it receives a termination signal). Secondly, this patch reorganizes some of the startup,
steady-state, and shutdown code to make shutdown easier to reason about. Specifically, all
these methods are now called from the same thread, so both the thread-safety and order of
execution are guaranteed. All the shutdown hook does is notify the main thread and then wait
for it to exit.
unit test to ensure shutdown handler is called
manual testing of shutdown process

fix: adds a handler to gracefully shutdown

---

ksqldb-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java

Note, this is a testing only change.
This PR changes the deprecated `RETRIES` config and instead uses the recommended `DELIVERY_TIMEOUT_MS` configuration. See https://cwiki.apache.org/confluence/display/KAFKA/KIP-572%3A+Improve+timeouts+and+retries+in+Kafka+Streams and 
```java
/**
* <code>retries</code>
* @deprecated since 2.7
*/
@Deprecated
public static final String RETRIES_CONFIG = CommonClientConfigs.RETRIES_CONFIG;
private static final String RETRIES_DOC = "(Deprecated) Setting a value greater than zero will cause the client to resend any record whose send fails with a potentially transient error."
+ " Note that this retry is no different than if the client resent the record upon receiving the error."
+ " Allowing retries without setting <code>" + …
```

build: temporarily suppress deprecation warnings for RETIRES config

---

Jenkinsfile

This PR updates the release job to override the `ksql_db_version` from the Jenkinsfile with the build param `KSQLDB_VERSION`, if specified. This will allow us to bump `ksql_db_version` to the next release version as soon as the release branch for the ongoing release is cut, while also allowing the release manager to cut new RCs for the ongoing release. By bumping `ksql_db_version` as soon as a release branch is cut, nightly builds from master will be tagged with the next release version rather than the current one, avoiding confusion where the latest tag for a particular RC (0.11.0, currently) may have been cut from master rather than the relevant release branch.
This PR also bumps the next release version to 0.12.0 accordingly, since the 0.11.x branch has already been cut.
Jenkins …

chore: add build param for overriding ksqlDB version (MINOR)

---

ksqldb-engine/src/test/java/io/confluent/ksql/integration/JoinIntTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java

There's some weird behavior going on in the `JoinIntTest`, but I'm fixing it here to unblock the master branch for now. 
Essentially we have a stream of events that are produced using a timestamp extractor that extracts timestamps equal to the offset within the stream. Since there are 8 events in the stream, the max timestamp is `8L` and the first timestamp is `1L`. The raw time on these events (without the extractor) is `System.currentTimeInMillis()` There is also a table that is produced with `System.currentTimeInMillis() - 500` to ensure that the join events show up "before" the stream events. The problem is that when the timestamp extractor is applied, the table events are no longer "before" the stream events.
The weird part, is that it works if we set the timestamp to anything less …

test: fix JoinIntTest by changing generated timestamp for table source

---

docs/how-to-guides/use-connector-management.md
mkdocs.yml

I release a new version of Voluble once in a while. Seems good to make this a var so people get the latest fixes.

docs: make the version of Voluble a var

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/ExecutorUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/ExecutorUtilTest.java

The retry behavior was causing all `isTopicExists` calls where the topic is expected not to exist to hang for 2.5s (5x 500ms)
Unit test ensures only is called once.

chore: dont retry isTopicExists on UnknownTopicOrPartitionException

---

ksqldb-common/src/main/java/io/confluent/ksql/properties/PropertiesUtil.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryMonitor.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/KafkaStreamsBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/KafkaStreamsBuilderImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/MaterializationProviderBuilderFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/QueryMonitorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/PersistentQueryMetadataTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/TransientQueryMetadataTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

Fixes https://github.com/confluentinc/ksql/issues/5897
This PR adds a new global thread, `CommandMonitor`, that monitors all persistent queries registered in the system and restarts those that have failed for any reason (system, user,  unknown reasons). Restarting queries automatically in the background helps reduce the effort of users to terminate the queries and re-create the stream/table/insert manually.
The query restart uses an exponential backoff time (in milliseconds) to wait before retrying another restart. For now, the initial backoff time is hard-coded to 10 seconds, and it is being incremented exponentially on every restart (10s, 20s, 40s, ...) up to the maximum backoff time. The maximum backoff time may be configured using `ksql.query.retry.backoff.max.ms` and is set to 2 …

feat: add service to restart failed persistent queries

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java

KSQL should treated unauthorized topics as not existing. Recently, there was a change in the `KafkaTopicClientImpl.isTopicExists()` that causes the method to throw a TopicAuthorizationException if the topic does not exist. This code used to call the `listTopicNames().contains(topic)` which wasn't including the topic thus returning false when it is not authorized to see it.
Added unit test

chore: isTopicExists should not throw if topic has denied authorization

---

ksqldb-api/pom.xml
ksqldb-api/src/main/java/io/confluent/ksql/api/impl/Utils.java

fix security vulnerabilities caused by having netty v4.1.42, which is coming from vertx version 3.8.4. 
the minimum required netty-codec version is 4.1.46 to fix the vulnerability, which requires the vertx version to be upgraded to 3.9.x.
```
[INFO] --------------------< io.confluent.ksql:ksqldb-api >--------------------
[INFO] Building ksqldb-api 5.5.2-SNAPSHOT                               [16/26]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.0.2:tree (default-cli) @ ksqldb-api ---
[INFO] io.confluent.ksql:ksqldb-api:jar:5.5.2-SNAPSHOT
[INFO] +- io.vertx:vertx-core:jar:3.9.1:compile
[INFO] |  +- io.netty:netty-common:jar:4.1.49.Final:compile
[INFO] |  +- io.netty:netty-buffer:jar:4.1.49.Final:compile
[INFO] | …
```

chore: bump vertx version to 3.9.1

---

docs/developer-guide/ksqldb-reference/operators.md
docs/developer-guide/syntax-reference.md
docs/tutorials/examples.md

From https://github.com/confluentinc/ksql/pull/5949.

docs: cherry-pick: update syntax reference for base-one index (DOCS-5057)

---

docs/developer-guide/ksqldb-reference/operators.md
docs/developer-guide/syntax-reference.md
docs/tutorials/examples.md

From https://github.com/confluentinc/ksql/pull/5949.

docs: cherry-pick: update syntax reference for base-one index (DOCS-5058)

---

ksqldb-docker/README.md

Add some instructions on how to use the locally built docker images with the repo's docker-compose file.

docs: add instructions on how to use locally created docker images

---

ksqldb-execution/src/main/java/io/confluent/ksql/logging/processing/RecordProcessingError.java
ksqldb-execution/src/test/java/io/confluent/ksql/logging/processing/RecordProcessingErrorTest.java

This change removes code that was dropping the first 'cause' of a processing logger error.
Found this when investigating https://github.com/confluentinc/ksql/issues/5707.
I *think* the code previously did this because the `errorMsg` was taken from the first 'cause' of the passed in `Exception`. However, the code now accepts a custom `errorMsg`, which may not match the first 'cause' of the supplied exception.
For example:
```java
// Old code:
} catch (final Exception e) {
// msg.errorMsg is first line of of 'e.cause',
// msg.cause is all other lines of 'e.cause'
final ErrorMessage msg = RecordProcessingError.recordProcessingError(e, row);
...
}
// New code:
} catch (final Exception e) {
// msg.errorMsg is "Error doing something"
// msg.cause drops first line of 'e.cause' ... which is …
```

fix: avoid losing cause of processing errors

---

docs/tutorials/event-driven-microservice.md

It's a bit "lucky" that the event-driven microservices tutorial works right now. The CTAS statement that creates the anomalies tables (https://docs.ksqldb.io/en/latest/tutorials/event-driven-microservice/#create-the-anomalies-table) doesn't specify a window grace period, so the default of 23 hours is used. However, the timestamps of the seeded transaction events (https://docs.ksqldb.io/en/latest/tutorials/event-driven-microservice/#seed-some-transaction-events) contain out of order data with timestamps by differ by up to 6 days. As a result, if the source stream is created with 1 partition rather than 8, the grace period means the window that's supposed to accumulate 3 events (according to the tutorial) will have closed after just the first event, and the possible_anomalies table will be …

docs: update event-driven microservices example data timestamps

---

ksqldb-common/src/main/java/io/confluent/ksql/properties/DenyListPropertyValidator.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/test/java/io/confluent/ksql/properties/DenyListPropertyValidatorTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/WSQueryEndpointTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

Added a new configuration `ksql.properties.overrides.denylist` to specify which server properties cannot be overridden by the KSQL clients/users.
There is currently an internal hard-coded list of properties that cannot be overriden. However, there are KSQL admins that also want other properties to be in the list. To make this dynamic, this new denylist property allow those admins to specify which properties should not be overridden, without making changes in the code.
The only disadvantage on this dynamic property over the hard-coded is the validation happens only until executing a DDL or query statements.
- Added unit tests
- Verify the CLI manually
```
ksql> set 'ksql.streams.num.stream.threads'='4';
Successfully changed local property 'ksql.streams.num.stream.threads' from '4' to '4'. …
```

feat: New ksql.properties.overrides.denylist to deny clients configs overrides

---

docs/reference2/sql-syntax/lexical-structure.md

I cribbed and edited the content from the existing operators topic, then picked up some details from the ANTLR grammar.

docs: add operators section to lexical structure topic (DOCS-5067)

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-common/src/main/java/io/confluent/ksql/query/QueryError.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/QueryStateListenerTest.java

The current list of query errors displayed in the Console and API only includes an error message and the error type. This PR adds the timestamp when the error was generated.

chore: Add query error timestamp to QueryError list, and return on API

---

ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/DropTypeFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/DropTypeFactoryTest.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/DropType.java

Add support for `IF EXISTS` on the `DROP TYPE` command. 
New syntax:
```
DROP TYPE [IF EXISTS] <type_name>;
```
If the `IF EXISTS` is specified, then the command should not throw any error if the type does not exist.
Verified manually
```
ksql> drop type address;
Type ADDRESS does not exist.
ksql> drop type if exists address;
Message                       
-------------------------------
Type 'ADDRESS' does not exist 
-------------------------------
```
The above works similar to `DROP STREAM [IF EXISTS]`
```
ksql> drop stream a;
Source A does not exist.
ksql> drop stream if exists a;
Message                    
----------------------------
Source `A` does not exist. 
----------------------------
```

feat: Support [IF EXISTS] on DROP TYPE command

---

docs/developer-guide/ksqldb-reference/drop-type.md
docs/developer-guide/ksqldb-reference/index.md
docs/developer-guide/ksqldb-reference/quick-reference.md

KSQL added support for `DROP TYPE [IF EXISTS]` here: https://github.com/confluentinc/ksql/commit/431c2ff651a455d1c327616fa7f8bd005ffe79f4
This PR adds the new `IF EXISTS` reference in all the doc type docs.
Not necessary

docs: add DROP TYPE [IF EXISTS] docs

---

docs/reference2/sql-syntax/lexical-structure.md

First attempt at a table that collects all of the ksqlDB keywords. I scraped these from our ANTLR spec, and I suspect some of them aren't in play yet. The table is big enough that we might want it to have its own page.

docs: add keywords table

---

CHANGELOG.md
docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/table-functions.md

Adds a 'Since' field to each function reference indicating which community release the method was introduced in.
Partital fix for https://github.com/confluentinc/ksql/issues/5900.  CP release info still needs adding. But this is a start.
For functions that have been there from start or from before community releases started on current numbering schema, 'Since' is just set to '-'.  (The idea being that anyone adding new functions, who may cut and paste and existing one as a template, will then update the Since info).
Doc only change.

docs: annotation function docs when funcs introduced

---

config/ksql-server.properties
ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionMetrics.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafAggregateFunction.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafLoader.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdtfLoader.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UserFunctionLoader.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/FunctionMetricsTest.java

fixes: https://github.com/confluentinc/ksql/issues/5890
Fixes an NPE thrown when the second instance of a UDAF is initialized. The NPE was being thrown due to a bug in the code that failed to initialise the sensor fields in the `UdafAggregateFunction` class if the sensor already existed.
The commit also refactors the code used to add function invocation metrics such that all three function types: UDF, UDTF and UDAF, use the same function to register metrics.
Unit tests added to ensure this single code path doesn't throw an NPE or return null on the subsequent invocation.
Also added `ksql.udf.collect.metrics` metric to the server config file, so users are more likely to be able to find it and try it out.
Moved UDTF functions out of the `ksql-udf` group and into `ksql-udtf` group. Having …

fix: NPE when udf metrics enabled

---

ksqldb-functional-tests/README.md
mkdocs.yml

Two miscellaneous docs changes:
- The example QTTs in the QTT README don't pass as written. This PR fixes the examples.
- The join synthetic keys topic (https://docs.ksqldb.io/en/0.10.1-ksqldb/developer-guide/joins/synthetic-keys/) isn't part of the docs index so the table of contents on the left (on the live page) shows the overview nav rather than more useful links. This PR fixes this by adding the topic to the docs index.
The synthetic-keys topic was introduced in 0.10.0, which is why this PR targets 6.0.x (aka 0.10.x). I'll cherry-pick to the live docs branches for 0.10.0, 0.10.1, and 0.11.0 once merged (and also 0.11.x for consistency).

docs: QTT readme fixes + add synthetic key topic to index (MINOR)

---

CHANGELOG.md
docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/table-functions.md

From https://github.com/confluentinc/ksql/pull/5954.
Adds a 'Since' field to each function reference indicating which community release the method was introduced in.
Partital fix for https://github.com/confluentinc/ksql/issues/5900.

docs: cherry-pick: annotation function docs when funcs introduced (DOCS-5076)

---

CHANGELOG.md
docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/table-functions.md

From https://github.com/confluentinc/ksql/pull/5954.
Adds a 'Since' field to each function reference indicating which community release the method was introduced in.
Partital fix for https://github.com/confluentinc/ksql/issues/5900.

docs: cherry-pick: annotation function docs when funcs introduced (DOCS-5078)

---

ksqldb-common/src/main/java/io/confluent/ksql/function/AggregateFunctionInitArguments.java
ksqldb-common/src/main/java/io/confluent/ksql/function/ParameterInfo.java
ksqldb-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksqldb-common/src/test/java/io/confluent/ksql/function/ParameterInfoTest.java
ksqldb-common/src/test/java/io/confluent/ksql/function/UdfIndexTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafAggregateFunctionFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafFactoryInvoker.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafLoader.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafTypes.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdafAggregateFunctionFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdafTypesTest.java

As well as an expression, UDAFs support constants being passed. However, prior to this change it was not possible to register a UDAF that have variants that have no constants and constants, or indeed with different constant types.  For example:
```java
@UdafDescription(
name = "LATEST_BY_OFFSET",
description = LatestByOffset.DESCRIPTION,
author = KsqlConstants.CONFLUENT_AUTHOR
)
public final class LatestByOffset {
...
// Version taking no constants:
@UdafFactory(description = "return the latest value of an integer column",
aggregateSchema = "STRUCT<SEQ BIGINT, VAL INT>")
public static Udaf<Integer, Struct, Integer> latestInteger() {
return latest(STRUCT_INTEGER);
}
// Version taking one constant:
@UdafFactory(description = "return the last N values of an integer column",
aggregateSchema = …
```

feat: support UDAFs with and without init Args with same param type

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/5996.

docs: cherry-pick: add release blog links to changelog (DOCS-5103)

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/generic/GenericExpressionResolver.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/generic/GenericRecordFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/generic/KsqlGenericRecord.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/generic/GenericRecordFactoryTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/transform/sqlpredicate/SqlPredicate.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json

This PR breaks up the `InsertValuesExecutor` into separate classes and adds more unit testing. The motivation is because I plan to reuse `GenericRecordFactory` for YATT (see #5965).
No functional changes, all copy-pasta - but I added unit tests anyway.

refactor: break up InsertValuesExecutor for easier reuse in testing tool

---

docs/operate-and-deploy/installation/upgrading.md

From https://github.com/confluentinc/ksql/pull/5993.
* docs: remove obsolete admonitions from upgrade guide (DOCS-5100)
* docs: update one admonition to 0.8.0

docs: cherry-pick: remove obsolete admonitions from upgrade guide (DOCS-5110)

---

docs/operate-and-deploy/installation/upgrading.md

From https://github.com/confluentinc/ksql/pull/5993.
* docs: remove obsolete admonitions from upgrade guide (DOCS-5100)
* docs: update one admonition to 0.8.0

docs: cherry-pick: remove obsolete admonitions from upgrade guide (DOCS-5111)

---

docs/concepts/schemas.md
docs/developer-guide/create-a-stream.md
docs/developer-guide/create-a-table.md
docs/developer-guide/index.md
docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/developer-guide/serialization.md
docs/operate-and-deploy/installation/server-config/avro-schema.md

From https://github.com/confluentinc/ksql/pull/6006.

docs: cherry-pick: copy edits for new schema inference content (DOCS-5115)

---

docs/concepts/schemas.md
docs/developer-guide/create-a-stream.md
docs/developer-guide/create-a-table.md
docs/developer-guide/index.md
docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/developer-guide/serialization.md
docs/operate-and-deploy/installation/server-config/avro-schema.md

From https://github.com/confluentinc/ksql/pull/6006.

docs: cherry-pick: copy edits for new schema inference content (DOCS-5117)

---

docs/concepts/schemas.md
docs/developer-guide/create-a-stream.md
docs/developer-guide/create-a-table.md
docs/developer-guide/index.md
docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/developer-guide/serialization.md
docs/operate-and-deploy/installation/server-config/avro-schema.md

From https://github.com/confluentinc/ksql/pull/6006.

docs: cherry-pick: copy edits for new schema inference content (DOCS-5116)

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/QueryAnalyzer.java
ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerTest.java

I found in the `QueryAnalyzer` code an invalid validator call to pull/push queries.
See the first `QueryAnalyzer` that calls another `QueryAnalyzer` constructor with push, then pull validators. But the constructor accepts pull, then push validators. Also the if condition in the `analyze` is calling a different validator.
```
public QueryAnalyzer(
final MetaStore metaStore,
final String outputTopicPrefix,
final Set<SerdeOption> defaultSerdeOptions
) {
this(
new Analyzer(metaStore, outputTopicPrefix, defaultSerdeOptions),
new PushQueryValidator(),
new PullQueryValidator()
);
}
@VisibleForTesting
QueryAnalyzer(
final Analyzer analyzer,
final QueryValidator pullQueryValidator,
final QueryValidator pushQueryValidator
) {
...
}
public Analysis analyze(...) {
...
if (query.isPullQuery()) { …
```

refactor: Call the correct pull/push query validator

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryMonitor.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/QueryStateListener.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/QueryMonitorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/QueryStateListenerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java

Fixes https://github.com/confluentinc/ksql/issues/6009
Use the config `ksql.query.status.running.threshold.seconds` to specify a threshold when stop tracking query error retries and set the query as healthy and running. All past query errors will be cleared after the threshold time expires.
I also took the time to make some minor improvements to the query monitor code.
Add unit tests

fix: set restarted query as healthy during a time threshold

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/protobuf.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactory.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactoryTest.java

fixes: https://github.com/confluentinc/ksql/issues/5994
Fixes a unintuitive error should user set `WRAP_SINGLE_VALUE=false` with `PROTOBUF` format.

fix: protobuf format does not support unwrapping

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/Column.java
ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksqldb-common/src/main/java/io/confluent/ksql/util/DecimalUtil.java
ksqldb-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksqldb-common/src/test/java/io/confluent/ksql/util/DecimalUtilTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/FinalProjectNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/ImplicitlyCastResolver.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/SelectionUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/FinalProjectNodeTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/ImplicitlyCastResolverTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_implicitly_casts/6.1.0_1597343542697/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_implicitly_casts/6.1.0_1597343542697/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_implicitly_casts/6.1.0_1597343542697/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/insert-into.json

Fixes https://github.com/confluentinc/ksql/issues/5285
Allows implicitly casting of numeric literals to decimals when executing an `INSERT/SELECT` statement. A conversion from one literal type to another is done in the `SelectionUtil.buildSelectExpressions()` method, which uses the `ImplicitlyCastResolver` to cast a supported type if necessary. 
A conversion of column schema is used Instead of just allowing the schema during the validation in the `EngineExecutor.validateExistingSink()`. The reason is that SchemaRegistry/AVRO does not allow some type of conversions, like INT/BIGINT -> DECIMAL as they are incompatible.
The validation in the `EngineExecutor.validateExistingSink()`` is required only for DECIMAL -> DECIMAL of different precision and scale. `ImplicitlyCastResolver` can only …

fix: allow implicit cast of numbers literals to decimals on insert/select

---

ksqldb-api-client/pom.xml

This is required in order for the maven javadoc plugin to succeed in Jenkins on Java 11. (Otherwise the build fails with
```
[2020-08-12T18:17:23.095Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:javadoc (default-cli) on project ksqldb-api-client: An error has occurred in Javadoc report generation: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
```
).
This PR also updates the whitespace char in the client pom so the latest versions-maven-plugin version doesn't fail with
```
[2020-08-11T07:05:38.051Z] [ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.8.1:set (default-cli) on project ksqldb-parent: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.8.1:set …
```

chore: add source config to javadoc plugin (MINOR)

---

ksqldb-common/src/main/java/io/confluent/ksql/parser/NodeLocation.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/DirectiveParser.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/SqlTestReader.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/TestDirective.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/TestStatement.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/parser/SqlTestReaderTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/parser/TestDirectiveTest.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AssertTable.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AssertStatement.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AssertStream.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AssertValues.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AssertTableTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/AssertStreamTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/AssertValuesTest.java

This PR puts in all of the parsing skeleton required for YATT (see #5965). Specifically:
1. Introduces `SqlTestReader`, the main parser that parses sql tests statement by statement
1. The `TestStatement` class wraps the three different types of statements supported by the reader (engine statements, asserts, directives)
1. The `TestDirective` class models a directive comment (e.g. `--@test: test1`)
1. The `AssertStatement` class and subclasses model the different types of `ASSERT` statements that are parseable as of this PR
Other than that, some minor changes were added to `SqlBase.g4` and elsewhere to better support this change.
Unit tests

test: parsing for SQL-driven testing tool

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/KsqlTestException.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/AssertExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/TestDriverPipeline.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/loader/TestLoader.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/SqlTestLoader.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/SqlTestReader.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/TestDirective.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/TestStatement.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/parser/SqlTestReaderTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/parser/TestDirectiveTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/asserts.json
ksqldb-functional-tests/src/test/resources/sql-tests/test.sql
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java

First draft at the fully implemented `KsqlTester` (see #5965). Review guide:
* Start by looking at `test.sql` to see how the testing tool works end-to-end
* Then look at `KsqlTesterTest` to see the full test in action. I'm planning on refactoring this further when I make it a standalone tool, but given that I want this to test query upgrades I'm leaving this in a little bit of a rougher state for now
* Look at `SqlTestLoader` to see how we load tests
* Look at `AssertExecutor` to look at asserting mechanism. I'm planning on improving the assertion mechanism to leverage the `SELECT` formatting of rows when I make this tool public, but for now it just compares the Generic representation of rows directy
* The rest is piping/formatting exceptions/etc...
- `test.sql` tests this end to end

feat: introduce the sql-based testing tool (YATT)

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTlsMutualAuthTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTlsTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslClientAuthFunctionalTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ListenersTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TlsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeWithTlsFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/SystemAuthenticationFunctionalTest.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/secure/KeyStoreUtil.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/secure/ServerKeyStore.java

The `TlsTest` tended to fail locally when running other tests in parallel. Investigation showed this is due to shared state in `ServerKeyStore`: the path to the key store.  The test needed to write a bad cert and then assert requests failed, but if another test ran it would override the bad cert with a good one.

test: fix flaky test due to static state

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java

Lots at a more verbose level (debug) when vertx hits a ClosedChannelException.
This can happen due to a client error, so don't log so verbosely.

chore: dont log at error level when on ClosedChannelException

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/AssertExecutor.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java
ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/filters.sql
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AssertTombstone.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java

This PR does two things:
- add support for tombstone assertions (`ASSERT NULL VALUES ... KEY`) to the sql testing tool
- add `filters.json` to test creating or replacing with regards to filters
- `filters.json` is self-testing

test: add filters.sql and assert tombstone

---

docs/developer-guide/ksqldb-reference/drop-connector.md
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/WarningEntityTableBuilder.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/DropConnector.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DropConnectorExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DropConnectorExecutorTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/WarningEntity.java

Fixes #5988
Added `IF EXISTS` keyword to the `DROP CONNECTOR` command. 
Previously, this error message would have shown if the connector does not exist:
```
Error                                   
-----------------------------------------
{
"error_code" : 404,
"message" : "Connector FOO not found"
} 
-----------------------------------------
```
With this change, if the `IF EXISTS` keyword is used, the response is:
```
Message                         
---------------------------------
Connector 'FOO' does not exist. 
---------------------------------
```
If the `IF EXISTS` keyword is not used, the response is the original error response.
I added a new `Entity` class called `WarningEntity` that prints a message without the Error header. It could also be used in other similar situations, …

feat: Support IF EXISTS keyword on DROP CONNECTOR

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

(also) fixes #6078 
In the existing code, `CREATE OR REPLACE` statements aren't handled correctly by the compactor because it did not account for the possibility of multiple queries with the same (valid) query ID existing.
This PR changes the algorithm to make it resilient to these types of changes.
Added tests to `RecoveryTest`, manual testing.

fix: properly handle restore on CREATE OR REPLACE

---

docs/developer-guide/test-and-debug/processing-log.md
ksqldb-common/src/main/java/io/confluent/ksql/logging/processing/ProcessingLogMessageSchema.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/logging/processing/ProcessingLogServerUtilsTest.java
ksqldb-serde/src/main/java/io/confluent/ksql/logging/processing/LoggingSerializer.java
ksqldb-serde/src/main/java/io/confluent/ksql/logging/processing/SerializationError.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/GenericKeySerDe.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/GenericRowSerDe.java
ksqldb-serde/src/test/java/io/confluent/ksql/logging/processing/LoggingDeserializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/logging/processing/LoggingSerializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/logging/processing/SerializationErrorTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/GenericKeySerDeTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/GenericRowSerDeTest.java

Fixes https://github.com/confluentinc/ksql/issues/5364
Two changes in this PR (corresponding to the first two commits):
- add serialization exceptions to the processing log: currently deserialization exceptions are logged but serialization exceptions aren't
- throw a more informative error message in the event that serialization exceptions are caused by UDFs with return types with non-optional schemas, since the error message from Connect (`Struct schemas do not match.`) isn't particularly actionable by users.
Added unit tests. Manual testing underway.

feat: add serialization exceptions to processing logger

---

docs/developer-guide/api.md
docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md
docs/developer-guide/ksqldb-rest-api/query-endpoint.md
docs/developer-guide/ksqldb-rest-api/streaming-endpoint.md

This came up while I was updating the [CCloud/ksqlDB quickstart](https://docs.confluent.io/current/quickstart/cloud-quickstart/ksql.html#access-a-ksql-cloud-application-in-ccloud-with-an-api-key).

docs: update example curl commands (DOCS-5203)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/suppress.json
ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/filters.sql

Disabling the suppression buffer by default. We're doing this because there currently isn't a straightforward way for us to size the buffer, which resides exclusively in memory. Our previous attempts (#5969) is a little misleading because it sizes the buffer per-partition, meaning that users could easily overuse the available memory and take down a ksqlDB node.
Follow-ups include writing a feature that allows the suppression buffer to spill to disk.
Update unit tests.

chore: disable suppress by default

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/DefaultErrorMessages.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java

```
ksql> show streams;
Stream Name         | Kafka Topic                 | Format 
------------------------------------------------------------
KSQL_PROCESSING_LOG | default_ksql_processing_log | JSON   
TEST                | TEST                        | JSON   
TEST1               | TEST1                       | JSON   
------------------------------------------------------------
WARNING: The server has encountered an incompatible entry in its log and cannot process further DDL statements.
This is most likely due to the service being rolled back to an earlier version.
```
Done by adding a KsqlWarning to the existing warnings list for each `KsqlEntity` returned from the server.
Alternatively, we could just add a separate `WarningEntity` to the `KsqlEntityList` returned from the server …

feat: add Ksql warning to KsqlResource response when CommandRunner degraded

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorTest.java

Currently, if a user tries to issue a pull query to a server for which `ksql.pull.queries.enable=false`, a 500 is returned when the response code should actually be 4xx. This PR changes the error code to 400 by switching the type of exception thrown. 
The usual.

chore: update response code on pull queries disabled to be 4xx (MINOR)

---

Jenkinsfile

Temporary change for 0.12.0 release since the Maven artifact version we'd like to use for our Streams dependency doesn't have associated base docker images. This change will be reverted after the 0.12.0 release as the value of having separate variables is low.
PR builder will verify images build. The only thing not covered by the PR builder in terms of testing is the downstream CCloud image build. Manual inspection shows the Maven artifact dependency version is the correct one to pass to the job.

chore: temporarily split CP dep version into maven and docker deps

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/test/java/io/confluent/ksql/util/TabularRowTest.java
ksqldb-common/src/main/java/io/confluent/ksql/util/TabularRow.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/AssertExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/TestDriverPipeline.java

fixes #6057
This patch adds more readable output to the testing tool.
Ran a faulty test, here's a sample output:
```
io.confluent.ksql.test.KsqlTestException: Test failure for assert `ASSERT VALUES BAR (ROWTIME, ID, COL1) VALUES (2, 2, 1)` (Line: 98, Col: 15):
Expected record does not match actual.
+------------------+------------------+------------------+------------------+
|.                 |ROWTIME           |ID                |COL1              |
+------------------+------------------+------------------+------------------+
|EXPECTED          |2                 |2                 |1                 |
|ACTUAL            |1                 |1                 |1                 |
```

chore: leverage SELECT * style formatting for testing tool

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/SqlTestReader.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/parser/SqlTestReaderTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/asserts.json
ksqldb-functional-tests/src/test/resources/sql-tests/test-script.sql
ksqldb-functional-tests/src/test/resources/sql-tests/test.sql
ksqldb-functional-tests/src/test/resources/test-script.sql
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4

fixes #6114 
Allows the testing tool to accept `RUN SCRIPT`, which allows advanced CI/CD use cases where the scripts get deployed directly to production.
- Unit testing
- a new test case in `test.sql` using `test-script.sql`

chore: support RUN SCRIPT in KsqlTester

---

ksqldb-common/src/main/java/io/confluent/ksql/properties/with/CommonCreateConfigs.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/AssertExecutor.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/AssertExecutorMetaTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java
ksqldb-functional-tests/src/test/resources/sql-tests/test.sql

fixes #6112 - implements this functionality into the KsqlTester
added tests in `test.sql`

chore: support ASSERT STREAM and ASSERT TABLE in KsqlTester

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCase.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanLoader.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksqldb-functional-tests/src/test/resources/historical_plans/serdes_-_serialization_should_produce_primitive_schema_for_unwrapped/6.1.0_1599053522062/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/serdes_-_serialization_should_produce_primitive_schema_for_unwrapped/6.1.0_1599053522062/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/serdes_-_serialization_should_produce_primitive_schema_for_unwrapped/6.1.0_1599053522062/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/serdes.json
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/Format.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSchemas.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectFormat.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/connect/ConnectFormatTest.java

fixes: #6134
Fixes an issue where the wrong schema is registered for unwrapped primitive values. The registered schema  incorrectly still has the value column wrapping in a record.
As part of this work `AvroSchemas` is now package private, and `AvroFormat` is used in its place in the code.
usual

 fix: wrong value schema being registered for unwrapped primitives 

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Encode.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/EncodeTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/encode.json
ksqldb-functional-tests/src/test/resources/test-runner/correct/from_docs/input.json

Earlier, the encode udf would not recognize hex strings of types belong to {0x, X'...', x'...'} while converting to ascii, utf8 and base 64 and would give nulls. Now it recognizes them and converts them accordingly from hex to other formats. Behavior is similar to https://dev.mysql.com/doc/refman/8.0/en/hexadecimal-literals.html
Unit + query-validation-tests + manual

feat: Adds support for 0x, X'...', x'...' type hex strings in udf:encode

---

docs/developer-guide/test-and-debug/processing-log.md
ksqldb-common/src/main/java/io/confluent/ksql/logging/processing/ProcessingLogMessageSchema.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/logging/processing/ProcessingLogServerUtilsTest.java
ksqldb-serde/src/main/java/io/confluent/ksql/logging/processing/DeserializationError.java
ksqldb-serde/src/main/java/io/confluent/ksql/logging/processing/LoggingDeserializer.java
ksqldb-serde/src/main/java/io/confluent/ksql/logging/processing/LoggingSerdeUtil.java
ksqldb-serde/src/main/java/io/confluent/ksql/logging/processing/LoggingSerializer.java
ksqldb-serde/src/main/java/io/confluent/ksql/logging/processing/SerializationError.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/kafka/KafkaSerdeFactory.java
ksqldb-serde/src/test/java/io/confluent/ksql/logging/processing/DeserializationErrorTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/logging/processing/LoggingDeserializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/logging/processing/LoggingSerializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/logging/processing/SerializationErrorTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/StaticTopicSerdeTest.java

Fixes https://github.com/confluentinc/ksql/issues/5627
Currently, there's nothing in the processing log message for (de)serialization errors to indicate whether it was the record key or value that failed to serialize/deserialize. This PR adds a new field to the relevant processing log message schemas called "component" with value "key" or "value" to indicate so.
Not in love with the name "component" but couldn't think of anything better. Suggestions appreciated!
Also fixes a typo in the Kafka deserializer error message that indicated the wrong format (delimited).
Unit + manual.

feat: clarify key or value in (de)serialization processing log messages

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksqldb-test-util/src/main/resources/log4j.properties

Tests derived from `BaseApiTest` can generate multiple exceptions in the logs unnecessarily, making it harder to debug issues, because they attempt to close `server` and `client` multiple times.  This change resolves this.
Additionally, our test logs are full of log lines about unknown configs being passed to `XxxxConfig` classes. This warning can be safely ignored (and is), so we shouldn't need to see it in the logs.
usual

test: avoid noise in test logs (MINOR)

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/MissingTopicClassifier.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/MissingTopicClassifierTest.java

Improves the `MissingTopicClassifier` to leverage the new Kafka Streams exception that is thrown instead of making a call out to kafka. This is more reliable, as kafka state sometimes believes topics have not been deleted when they actually have been.
Unit testing, and manual testing.

fix: missing topic classifier now uses MissingSourceTopicException

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/FileWatcher.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TlsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/FileWatcherTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/secure/KeyStoreUtil.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/secure/ServerKeyStore.java

fixes an issue where the TlsTest was failing because the file watcher wasn't detecting the change of the Tls cert from valid to invalid.  This was because of a limitation of JDK 8, which has only second resolution for `FileTime`, meaning the `WatchService` can miss updated made to files that existed before the watch was registered, if the update happened after the watch was started and the updated didn't change the last modified time, i.e. the last modified time both before and after the update was in the second second.
The fix is to insert a sleep to ensure at least one whole second has elapsed.
In production code, this one second window of bad behaviour is highly unlikely to be hit, and there's no real way to solve it, except upgrading to JDK 9.
Usual

test: stabilise TlsTest

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/FileWatcherTest.java

Fixes the following:
```
[2020-09-10T20:28:42.115Z] [ERROR] Possible null pointer dereference in io.confluent.ksql.api.server.FileWatcherTest.willStopIfDirectoryDeleted() due to return value of called method [io.confluent.ksql.api.server.FileWatcherTest, io.confluent.ksql.api.server.FileWatcherTest] Method invoked at FileWatcherTest.java:[line 113]Known null at FileWatcherTest.java:[line 113] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
```
n/a

chore: fix master findbugs issue (MINOR)

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaConsumerGroupClientImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedKafkaConsumerGroupClient.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/ExecutorUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/FakeKafkaConsumerGroupClient.java
ksqldb-execution/src/main/java/io/confluent/ksql/services/KafkaConsumerGroupClient.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/stubs/StubKafkaConsumerGroupClient.java

fixes #1283
Before this PR, we don't clean up consumer groups that are leftover which makes it really annoying for users to look into their existing consumer groups. This PR adds cleanup on close for persistent and transient queries.
The unfortunate part, is that the consumer group API takes a while to update when the last consumer has left the group (specifically, the `heartbeat.interval.ms` which is default to 3 seconds, needs to pass after the last consumer leaves the group). To account for this, I've taken the external resource cleanup out of the main execution path so that the UI doesn't hang when we terminate a query.
Unit testing, and manual testing to make sure the resources are cleaned up.

fix: delete zombie consumer groups 🧟

---

docs/developer-guide/ksqldb-reference/create-connector.md
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateConnector.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/CreateConnectorTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ConnectExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ConnectExecutorTest.java

Fixes #5992 
Added IF EXISTS to the create connector portion of the grammar and made necessary code changes ,
Basically added a check in `ConnectExecutor` , to call /connectors endpoint and find if connector is already created
Added unit tests and did manual testing

feat: Support for IF EXISTS on CREATE CONNECTOR

---

design-proposals/klip-33-key-format.md

KLIP adding `KEY_FORMAT` and other things to the language.

docs: klip-33 key format

---

ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/DdlCommandExec.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/RegisterTypeFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/StatementRewriter.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/DdlCommandExecTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/RegisterTypeFactoryTest.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/TypeRegistry.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/TypeRegistryImpl.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/RegisterType.java

Added support for new syntax: `CREATE TYPE [IF NOT EXISTS] foo AS bar`. Addresses #5991 
If `IF NOT EXISTS` is included in the query, then creating a type that already exists will return the following message:
```
Message
--------------------------------------------
FOO is already registered with type STRING
--------------------------------------------
``` 
If not, then this error will be thrown:
```
Cannot register custom type 'WOW' since it is already registered with type: STRING
```
Added unit tests and manually tested

feat: Support IF NOT EXISTS on CREATE TYPE

---

debian/confluent-ksqldb.postinst
debian/confluent-ksqldb.spec.in

When installing ksqlDB using RPM/DEB packages, the `/var/lib/kafka-streams` directory cannot be created because lack of write permissions in `/var/lib`. To fix this, this PR creates the streams directory during the RPM installation.

fix: create /var/lib/kafka-streams directory on RPM installation

---

ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectDataTranslator.java

fixes #6189 
fixes #6190 
Wooohoo!! I was able to figure out a way to get this gain without introducing a cache 😂 that means we get _even better_ performance than what I suggested in #6106 because we don't need to hash `Schema` objects as cache keys.
----
Previously, were were creating a case insensitive field map per-record, and always calling `toUpperCase` on every field - even if the case-sensitive version would have been matched. Looking into the performance profile (detailed in #6106) it revealed that these two points together where taking up a large chunk of time. 
There are two schemas in play: the ksql schema and the value schema (taken from schema registry). The original code created a mapping from expected field name (case-insensitive) to the value field. Then, for each ksql …

feat: substantially improve avro deserialization performance

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java

If the server is running and we delete the command topic, we should throw an exception from the command consumer when it tries to poll the new command topic. Previously the value was set to `LATEST` since it was default
Delete command topic after server is up.
Recreate the command topic
```
Exception in thread "CommandRunner" org.apache.kafka.clients.consumer.OffsetOutOfRangeException: Fetch position FetchPosition{offset=4, offsetEpoch=Optional[0], currentLeader=LeaderAndEpoch{leader=Optional[stevenz-mbp13.lan:9092 (id: 0 rack: null)], epoch=0}} is out of range for partition _confluent-ksql-default__command_topic-0
at org.apache.kafka.clients.consumer.internals.Fetcher.handleOffsetOutOfRange(Fetcher.java:1358)
at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch( …
```

chore: set auto.offset.reset to none for command topic consumer

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtils.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtilsTest.java

We'll set config overrides for internal topics
```
if (topicClient.addTopicConfig(name, INTERNAL_TOPIC_CONFIG)) 
```
if the topic already exists and the configs don't match.
`unclean.leader.election.enable` wasn't being set to false in the event the topic is already present
NOTE: `min.insync.replicas` isn't being set if the topic already exists, only when the server creates the internal topic, should we add code to also set this value?
Created command topic without setting any configs.
```
/kafka-topics --zookeeper localhost:2181 --describe --topic _confluent-ksql-default__command_topic
Topic: _confluent-ksql-default__command_topic	PartitionCount: 1	ReplicationFactor: 1	Configs: 
Topic: _confluent-ksql-default__command_topic	Partition: 0	Leader: 0	Replicas: 0	Isr: 0	Offline: 
```
Start up …

chore: make sure unclean leader election is set to false

---

config/connect.properties
docs/how-to-guides/use-connector-management.md
docs/tutorials/etl.md
docs/tutorials/event-driven-microservice.md
docs/tutorials/materialized.md

fixes #6131
fixes #6132
This change removes references to `AvroConverter` as the key converter. Note that this does nothing to fix the underlying issue (#4524) but simply makes the documentation and defaults consistent with what we implement.
n/a

docs: update key converters to avoid AvroConverter references

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroFormat.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/avro/AvroFormatTest.java

fixes issue where using a column name in ksqlDB that was incompatible with Avro, e.g. one that starts with a numeric, either wasn't detected at the time the statement was issued (in the case of C* statements), or returned a ambiguous error message (in the case of C*AS statements).
Usual

fix: improve error handling of invalid Avro identifier

---

ksqldb-benchmark/README.md
ksqldb-benchmark/src/main/java/io/confluent/ksql/benchmark/SerdeBenchmark.java
ksqldb-benchmark/src/main/resources/schemas/single-key.avro
ksqldb-benchmark/src/test/java/io/confluent/ksql/benchmark/SerdeBenchmarkTest.java

fixes: https://github.com/confluentinc/ksql/issues/6211
Enhances the serde benchmarks beyond just testing `AVRO` and `JSON` formats via the `GenericRowSerde` to include `KAFKA`, `DELIMITED` and `PROTOBUF` formats and test key serde via the `GenericKeySerde`.
```
Benchmark                                (params)  Mode  Cnt  Score   Error  Units
SerdeBenchmark.deserialize   single-key/Delimited  avgt    2  2.784          us/op
SerdeBenchmark.deserialize       single-key/Kafka  avgt    2  0.045          us/op
SerdeBenchmark.deserialize        single-key/JSON  avgt    2  0.200          us/op
SerdeBenchmark.deserialize        single-key/Avro  avgt    2  0.550          us/op
SerdeBenchmark.deserialize  impressions/Delimited  avgt    2  2.840          us/op
SerdeBenchmark.deserialize …
```

test: extend serde benchmark to include all formats and key serde

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatterTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/cast_-_struct_to_struct_with_same_schema/6.1.0_1600377904990/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/cast_-_struct_to_struct_with_same_schema/6.1.0_1600377904990/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/cast_-_struct_to_struct_with_same_schema/6.1.0_1600377904990/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/cast.json

Previously, the second argument in `CAST` was not getting fully processed in the `ExpressionFormatter`, causing field cases to not be preserved when casting to structs. This PR fixes that.
Fixes #5973 
Manually tested, added a unit test

fix: format cast arguments with passed context

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/math/Round.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/RoundTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/math_-_round_with_large_DECIMAL_values_-_AVRO/6.1.0_1600280487284/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/math_-_round_with_large_DECIMAL_values_-_AVRO/6.1.0_1600280487284/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/math_-_round_with_large_DECIMAL_values_-_AVRO/6.1.0_1600280487284/topology
ksqldb-functional-tests/src/test/resources/historical_plans/math_-_round_with_large_DECIMAL_values_-_DELIMITED/6.1.0_1600280487241/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/math_-_round_with_large_DECIMAL_values_-_DELIMITED/6.1.0_1600280487241/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/math_-_round_with_large_DECIMAL_values_-_DELIMITED/6.1.0_1600280487241/topology
ksqldb-functional-tests/src/test/resources/historical_plans/math_-_round_with_large_DECIMAL_values_-_JSON/6.1.0_1600280487303/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/math_-_round_with_large_DECIMAL_values_-_JSON/6.1.0_1600280487303/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/math_-_round_with_large_DECIMAL_values_-_JSON/6.1.0_1600280487303/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/math.json

fixes: https://github.com/confluentinc/ksql/issues/6233
Fixes the scale of the decimals values returned by the variant of the `ROUND` method that takes a decimal and a required number of decimal places to round to.
This fixes a bug where the output could not be serialized to Avro.
Usual

fix: scale of ROUND() return value

---

ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/JoinIntTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/HealthCheckResourceTest.java
ksqldb-udf-quickstart/src/main/resources/archetype-resources/pom.xml
ksqldb-udf-quickstart/src/main/resources/archetype-resources/src/test/java/ReverseUdfTests.java
ksqldb-udf-quickstart/src/main/resources/archetype-resources/src/test/java/SummaryStatsUdafTests.java
ksqldb-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/VersionCheckerIntegrationTest.java

Some of our dependencies require Junit5 to run (namely usage of Kafka's `TestUtil`) as of https://github.com/confluentinc/kafka/commit/7d0086e0c35d827a46e82956f42af57f6a6539f1. While I was at it, I cleaned up the maven architype as well.

chore: remove junit5 references

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/utils/TestUtils.java

After query execution plans were introduced by [KLIP 6](https://github.com/confluentinc/ksql/blob/master/design-proposals/klip-6-execution-plans.md), we required users to migrate existing statements rather than performing in-place upgrades when upgrading from ksqlDB 0.7.0 to ksqlDB 0.8.0, and also when migrating from Confluent Platform KSQL 5.4 to ksqlDB 5.5. 
As a result, the engine no longer needs to support legacy `C*`, `C*AS`, `INSERT INTO`, and `DROP` source commands that do not have execution plans in the command topic.
New unit tests + existing tests pass.

chore: drop support for executing legacy DDL/DML

---

mkdocs.yml

Prep for the 0.13.x-ksqldb branch cut.

docs: bump docs version to 0.13.0 (DOCS-5440)

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/TestCaseNode.java
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_deserialize_DELIMITED_with_WRAP_SINGLE_VALUE_false/6.1.0_1599861951568/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_format/6.1.0_1600714522363/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/kafka_-_BIGINT/6.1.0_1597874026416/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/kafka_-_DOUBLE/6.1.0_1597874026426/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/kafka_-_Default_single_value_wrapping/6.1.0_1597874026383/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/kafka_-_INT/6.1.0_1597874026407/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/kafka_-_STRING/6.1.0_1597874026396/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/kafka_-_Unwrapped_single_values/6.1.0_1599861974669/spec.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/delimited.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/formats.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/kafka.json

Some QTT test cases used `input` rather than `inputs` and `output` rather than `outputs`. Previously, QTT would have detected this mistake, but the check has been removed.
This change adds back in the check to ensure a test case provides at least one of:
- an expected exception
- input messages
- output messages
The change also corrects the bad tests and their historic plans

test: correct bug in QTT that meant some tests were ignored

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgent.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgentTest.java

I deleted the command topic and checked to see what exception is returned when the describe topic operation is done with the AdminClient for the healthcheck agent. Updated catch blocks to account for this
```
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
at io.confluent.ksql.rest.healthcheck.HealthCheckAgent$KafkaBrokerCheck.check …
```

chore: update healthcheck behavior when command topic is missing

---

design-proposals/README.md
design-proposals/klip-36-grace-stream-stream-joins.md

See: https://github.com/confluentinc/ksql/issues/6152
Formatted: https://github.com/agavra/ksql/blob/klip-36/design-proposals/klip-36-grace-stream-stream-joins.md

docs: klip-36: grace period for stream-stream joins

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/kafka/KafkaSerdeSupplier.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopicInfoCache.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/serde/kafka/KafkaSerdeSupplierTest.java

Moves the coercion required by the Kafka Serde _into_ the Kafka Serde used by QTT.
Previously, this was handled by `TopicInfoCache`. However, it's only the `KAFKA` format that needs this, (as it has specific serde for different primitive types).  Moving it into `KafkaSerdeSupplier` simplifies the code path for other formats.
Usual

test: move QTT coercion into Kafka test serde

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/insert-into.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/table.json

The historical plans now capture all records send to internal topics, so there is no need for the QTT test cases to detail the internal messages. Removing them makes the tests easier to read.

test: drop internal topics from QTT test cases

---

ksqldb-functional-tests/README.md
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/SourceNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/matchers/MetaStoreMatchers.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/model/SourceNodeTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/formats.json

Addresses https://github.com/confluentinc/ksql/pull/6194#discussion_r490670303 by adding value format into the sources post-condition check of QTT, and updating the new tests to use the sources post-condition check rather than the topics post-condition check.
Test-only change. Verified that tests fail if the specified source value format does not match what's expected.

test: support source value format in QTT post conditions (MINOR)

---

ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json

Fixes https://github.com/confluentinc/ksql/issues/6216
Add RQTT tests with non-Kafka formats. No changes were needed to the RQTT framework. This PR just adds a few tests as sanity checks going forward.
The tests aren't super useful as sanity checks since RQTT doesn't support the post-conditions check that QTT does which would allow us to verify the key and value formats of the created sources. This means an (unlikely) bug could be introduced into the RQTT executor which always hardcodes a particular key format and these tests would still pass. I don't think it's worth introducing a post-conditions check to RQTT, though, since that's the job of QTT not RQTT.
Tests pass.

test: add RQTT for non-KAFKA key format (MINOR)

---

ksqldb-engine/src/main/java/io/confluent/ksql/serde/InternalFormats.java
ksqldb-engine/src/main/java/io/confluent/ksql/serde/SerdeOptionsFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedTable.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksqldb-engine/src/test/java/io/confluent/ksql/serde/SerdeOptionsFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedStreamTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/Formats.java

fixes: https://github.com/confluentinc/ksql/issues/6209
Ensure internal changelog and repartition topics set `SerdeFeature.UNWRAP_SINGLES` if the key format supports both unwrapping and wrapping.  This is done to avoid ambiguity, which may cause compatibility issues once wrapped keys are supported.
Usual

chore: unwrap single keys on internal topics

---

ksqldb-engine/src/test/java/io/confluent/ksql/util/StructuredTypesDataProvider.java
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_SR_should_not_trim_trailing_zeros/6.0.0_1593789506613/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1583419431528/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1588893908853/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_scale_in_data_less_than_scale_in_type/6.0.0_1589910855902/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_JSON_should_not_trim_trailing_zeros/6.0.0_1593789506599/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_different_types/5.5.0_1581572089881/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_different_types/6.0.0_1588893912305/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_different_types/6.0.0_1589910859868/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_array_params/5.5.0_1581572104153/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_array_params/6.0.0_1588893946476/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_array_params/6.0.0_1589910892972/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_map_params/5.5.0_1581572104170/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_map_params/6.0.0_1588893946500/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_map_params/6.0.0_1589910892992/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_return_vals/5.5.0_1581572104193/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_return_vals/6.0.0_1588893946522/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_return_vals/6.0.0_1589910893013/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_simple_params/5.5.0_1581572104135/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_simple_params/6.0.0_1588893946443/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/table-functions_-_test_udtf_-_simple_params/6.0.0_1589910892938/spec.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/decimal.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/explode.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/table-functions.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonDeserializerTest.java

It is the responsibility of the format to ensure the data returned matches the required schema. This includes the scale of decimals. The JSON format was not correctly setting the scale of decimals when deserializing. For example, give:
```sql
CREATE STREAM S (ID INT KEY, PRICE DECIMAL(10,2) WITH (kafka_topic='S', formats='JSON');
```
The above creates a stream with a single value column `PRICE` which should have a scale of `2`, i.e. two decimal places.
If the data in tbe Kafka record's value was to have too small a scale, e.g.
```json
{
"price": 12
}
```
or
```json
{
"price": 12.1
}
```
Then the deserializer was returning the decimal as provided, i.e. `12` or `12.1`. However, this is incorrect as the schema of the column states is has a scale of two. So all values for the column should …

fix: JSON format to set correct scale of decimals

---

maven-settings-template.xml

This is needed in order to generate HTML API docs from javadocs on Java client interfaces from release tags, rather than release branches. The former is preferred so that the version displayed on the HTML docs will be the release version (e.g., 0.12.0) rather than the master version (e.g., 6.1.0-SNAPSHOT). See https://github.com/confluentinc/ksql/pull/6323 for an example of the difference.

chore: add ksqldb staging repo to release maven settings (MINOR)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/6318.
* docs: link to ksqlDB 0.12.0 blog post (DOCS-5489)
* docs: add missing link to 0.11.0 blog post

docs: cherry-pick: link to ksqlDB 0.12.0 blog post (DOCS-5495)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/6318.
* docs: link to ksqlDB 0.12.0 blog post (DOCS-5489)
* docs: add missing link to 0.11.0 blog post

docs: cherry-pick: link to ksqlDB 0.12.0 blog post (DOCS-5500)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/6318.
* docs: link to ksqlDB 0.12.0 blog post (DOCS-5489)
* docs: add missing link to 0.11.0 blog post

docs: cherry-pick: link to ksqlDB 0.12.0 blog post (DOCS-5496)

---

CHANGELOG.md

chore: Fix changelog to include CREATE OR REPLACE for 0.12.0, which was cut from earlier changelogs

chore: Fix changelog to include CREATE OR REPLACE for 0.12.0, which was cut from earlier changelogs

---

docs/developer-guide/create-a-stream.md
docs/developer-guide/create-a-table.md
docs/developer-guide/ksqldb-clients/java-client.md
docs/developer-guide/ksqldb-reference/describe.md
docs/developer-guide/test-and-debug/processing-log.md
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/StreamInfo.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/TableInfo.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/AdminResponseHandlers.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/StreamInfoImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/TableInfoImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/StreamInfoImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/TableInfoImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/JLineReader.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/StreamsListTableBuilder.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/TablesListTableBuilder.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SourceInfo.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/SourceInfoTest.java

fixes: https://github.com/confluentinc/ksql/issues/6218
Updates a few places in the rest api, cli and the new Java client to specify the key format as well as the value format.
Unfortunately, the value format was called `format`.  This change introduces a `keyFormat` and `valueFormat` to hold the two formats, but both the CLI and new Java client are backwards compatible with the old JSON schema.
Also in this commit, streams also indicate if there key is windowed.  This means the key is serialized using the windowed serializer. It is possible to have a stream over a topic with a windowed key. Now the CLI and Java client expose this info.
Main change was to `show tables` and `show streams` response.  Previously, these returned
```
ksql> show streams;
Stream Name | Kafka Topic | Format …
```

chore: ensure CLI works with other key formats

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json

fixes: https://github.com/confluentinc/ksql/issues/6213
Add code to throw a useful error message if a join has incompatible key formats. QTT test added too.
Usual

chore: fail joins where the key format differs

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerFunctionalTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/formats.json
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceAsProperties.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourceAsPropertiesTest.java

Wire up `KEY_FORMAT` and `FORMAT` explicitly provided in C*AS statements.
See https://github.com/confluentinc/ksql/pull/6292#pullrequestreview-497613436
usual

chore: wire up key_format in C*AS statements

---

docs/developer-guide/serialization.md
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_BIGINT_-_key/6.1.0_1601555627743/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_BIGINT_-_key/6.1.0_1601555627743/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_BIGINT_-_key/6.1.0_1601555627743/topology
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_BOOLEAN_-_key/6.1.0_1601555627700/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_BOOLEAN_-_key/6.1.0_1601555627700/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_BOOLEAN_-_key/6.1.0_1601555627700/topology
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_DECIMAL_-_key/6.1.0_1601555627789/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_DECIMAL_-_key/6.1.0_1601555627789/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_DECIMAL_-_key/6.1.0_1601555627789/topology
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_DOUBLE_-_key/6.1.0_1601555627757/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_DOUBLE_-_key/6.1.0_1601555627757/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_DOUBLE_-_key/6.1.0_1601555627757/topology
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_INT_-_key/6.1.0_1601555627728/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_INT_-_key/6.1.0_1601555627728/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_INT_-_key/6.1.0_1601555627728/topology
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_STRING_-_key/6.1.0_1601555627776/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_STRING_-_key/6.1.0_1601555627776/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_STRING_-_key/6.1.0_1601555627776/topology
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_keyless/6.1.0_1601555628104/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_keyless/6.1.0_1601555628104/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/delimited_-_keyless/6.1.0_1601555628104/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/delimited.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/formats.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/KeyFormatUtils.java

feat: support for `DELIMITED` key format

---

docs/developer-guide/serialization.md
docs/operate-and-deploy/installation/server-config/config-reference.md
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/serde/InternalFormats.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/none/NoneSerdeSupplier.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/utils/SerdeUtil.java
ksqldb-functional-tests/src/test/resources/historical_plans/none_-_as_key_format_of_keyless_stream/6.1.0_1601581259035/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/none_-_as_key_format_of_keyless_stream/6.1.0_1601581259035/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/none_-_as_key_format_of_keyless_stream/6.1.0_1601581259035/topology
ksqldb-functional-tests/src/test/resources/historical_plans/none_-_in_CSAS_from_keyless_stream/6.1.0_1601581259075/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/none_-_in_CSAS_from_keyless_stream/6.1.0_1601581259075/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/none_-_in_CSAS_from_keyless_stream/6.1.0_1601581259075/topology
ksqldb-functional-tests/src/test/resources/historical_plans/none_-_in_CSAS_partitioning_by_null/6.1.0_1601581259089/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/none_-_in_CSAS_partitioning_by_null/6.1.0_1601581259089/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/none_-_in_CSAS_partitioning_by_null/6.1.0_1601581259089/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/none.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/Format.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/FormatFactory.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/KeyFormatUtils.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/none/NoneFormat.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/none/NoneFormatTest.java

fixes: #6221
Introduce a `NONE` format, used to indicate the key data, in key-less streams, should not be deserialized.
There's a piece of follow up work to make joins involving key-less streams with `NONE` key format work.  This will be done under https://github.com/confluentinc/ksql/issues/6213.
usual

feat: `NONE` format for key-less streams

---

ksqldb-benchmark/src/main/java/io/confluent/ksql/benchmark/SerdeBenchmark.java
ksqldb-engine/src/main/java/io/confluent/ksql/execution/json/PlanJsonMapper.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/BackupReplayFile.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopic.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicBackupImpl.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/BackupReplayFileTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicBackupImplTest.java

This PR fixes an issue with backups re-created over and over again on every server restart. 
The cause was that sometimes the command topic comes with command properties (originalProperties) with nulls and empty values. When the backup serializes those properties to write them as JSON in the file, the nulls and empty are missing. Later, when restarting the server, the command properties read from command topic are not equals from the ones found in the backup file; so a new backup file is created.
The fix makes sure to include nulls and empty properties in the backup file. It also adds a header to include the version of the backup file. When the backup file do not contain a version header (during an …

fix: backup files are re-created on every restart

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgent.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/HealthCheckResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgentTest.java

https://github.com/confluentinc/ksql/issues/6308
Exposes command runner health in the healthcheck endpoint
Issued a request to healthcheck endpoint
Unit test

feat: add commandRunnerCheck to healthcheck detail

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/TopicNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/Topic.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/SchemaTranslationTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/StubKafkaServiceTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorUtilTest.java

Partial work for #6222 - this PR supports _writing_ to schema registry (and ensuring compatibility) for formats that support schema inference. This PR also includes most of the piping we need to test it in QTT, but I haven't actually written any of those tests until we have `AVRO` key formats wired up.
Unit testing

chore: wire in auto-register for key schemas

---

docs/index.md

Add links to CP content on the overview page. Also fixes heading levels, so the in-page TOC renders.

docs: add links to CP content (DOCS-5556)

---

CHANGELOG.md
docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/6347.

docs: Cherry-pick 0.10.2 changelog to CP6.0 live branch (DOCS-5549)

---

design-proposals/README.md
design-proposals/klip-38-variable-substitution.md

Add KLIP-38 to support variable substitution in ksqlDB.

docs: KLIP-38 for Variable Substitution

---

pom.xml

The following AK commit: https://github.com/apache/kafka/pull/9156 seems to have broken the `KsMaterializationFunctionalTest#shouldIgnoreHavingClause` test. I'm not entirely sure why, but while we're looking into that I'm pinning AK to the earlier microversion to unblock our master
Ran the test

chore: fix build by pinning AK to 6.1.0-23-ccs

---

ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/TerminateQuery.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandIdAssigner.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

fixes #6390
this PR now properly handles `TERMINATE ALL`. I checked to see if I could do this without "hacking" the fact that the `QueryId` is `ALL` but it would require parsing the statement, which would require quite a few changes (like passing the engine into the compactor, which doesn't sound right). Anything else (changing the `CommandId`) is not backwards compatible.
Unit test

fix: recovery hangs when using TERMINATE ALL

---

pom.xml

Reverts confluentinc/ksql#6396 because it breaks the main confluent packaging build.

chore: revert "fix build by pinning AK to 6.1.0-23-ccs"

---

docs/developer-guide/ksqldb-reference/select-pull-query.md
docs/developer-guide/ksqldb-reference/select-push-query.md

Trying to fix pint merge conflict by making 6.0.x the same as master. I'll need to undo this once pint merge is clear.

docs: fix merge conflict from the other side (DOCS-5620)

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/WindowData.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/Record.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/SchemaTranslationTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/model/RecordNodeTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/KsqlTestingToolTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/RecordTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json

Adds coverage for AVRO in QTT tests. In order to support decimal (and in future when we want to compare structs) I needed to change the test framework to compare the `JsonNode` instead of the java-ified value, piggy-backing on the existing value comparison framework.
Ran the QTT tests :)

chore: qtt coverage for avro primitive keys

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplier.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/TopicSchemaSupplier.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplierTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_deserialize_anonymous_struct_-_value_-_inference/6.1.0_1602822758149/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_deserialize_anonymous_struct_-_value_-_inference/6.1.0_1602822758149/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_deserialize_anonymous_struct_-_value_-_inference/6.1.0_1602822758149/topology
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_deserialize_anonymous_struct_-_value_-_no_inference/6.1.0_1602822758088/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_deserialize_anonymous_struct_-_value_-_no_inference/6.1.0_1602822758088/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_deserialize_anonymous_struct_-_value_-_no_inference/6.1.0_1602822758088/topology
ksqldb-functional-tests/src/test/resources/historical_plans/serdes_-_deserialize_and_serialize_unwrapped_struct/6.1.0_1602822838224/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/serdes_-_deserialize_and_serialize_unwrapped_struct/6.1.0_1602822838224/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/serdes_-_deserialize_and_serialize_unwrapped_struct/6.1.0_1602822838224/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/serdes.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/SchemaTranslator.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectFormatSchemaTranslator.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/connect/ConnectFormatSchemaTranslatorTest.java

Fixes https://github.com/confluentinc/ksql/issues/6444
The cause of the bug is that the DefaultSchemaInjector always unwraps struct schemas (assuming that they're wrapped), ignoring any serde features that should cause it to not do so (specifically, `wrap_single_value=false`). This PR fixes the bug by passing serde features into the schema translator, which is admittedly hacky and ugly but I couldn't think of a way around this. 
QTT

fix: support unwrapped struct value inference

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-rocksdb-config-setter/src/main/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBMetrics.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/metrics/RocksDBMetricsCollector.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/metrics/RocksDBMetricsCollectorTest.java

This patch adds a pattern for computing/reporting metrics that return aggregates
of the rocksdb metrics added by KIP-607. Additionally, this particular PR adds the
following metrics:
num-running-compactions-total: the total number of running compactions
estimate-num-keys-total: an estimate of the total number of rocksdb keys
block-cache-usage-total: total memory usage of all block cache
block-cache-pinned-usage-total: total memory used by pinned blocks
estimate-table-readers-mem-total: estimate of the total table readers mem
ksqlDB registers for notification about new rocksdb metrics by creating a
MetricsReporter implementation called RocksDBMetricCollector. The metrics
system calls into MetricsReporter.metricChange when a new metric is added.
RocksDBMetricCollector looks out for rocksdb …

feat: add aggregated rocksdb metrics

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/delimited.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/json.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/kafka.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/GenericKeySerDe.java

Fixes https://github.com/confluentinc/ksql/issues/6447. This feature is currently hidden behind the `ksql.key.format.enabled` feature flag. I'm amazed this "just worked"... huge props to @big-andy-coates for setting up the codebase well!
Lots of QTT.

feat: support non-primitive types as keys

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java

Fixes #6407 . Minor change that involves not cloning. Basically, reverting to previous behavior.
Ran pull query benchmarks and verified we get 3K qps. Also, checked flamegraph.

fix: fixes performance regression in pull queries introduced by sessionConfig

---

Jenkinsfile
build-tools/pom.xml
debian/Makefile
ksqldb-api-client/pom.xml
ksqldb-api-reactive-streams-tck/pom.xml
ksqldb-benchmark/pom.xml
ksqldb-cli/pom.xml
ksqldb-common/pom.xml
ksqldb-console-scripts/pom.xml
ksqldb-docker/pom.xml
ksqldb-engine/pom.xml
ksqldb-etc/pom.xml
ksqldb-examples/pom.xml
ksqldb-execution/pom.xml
ksqldb-functional-tests/pom.xml
ksqldb-metastore/pom.xml
ksqldb-package/pom.xml
ksqldb-parser/pom.xml
ksqldb-rest-app/pom.xml
ksqldb-rest-client/pom.xml
ksqldb-rest-model/pom.xml
ksqldb-rocksdb-config-setter/pom.xml
ksqldb-serde/pom.xml
ksqldb-streams/pom.xml
ksqldb-test-util/pom.xml
ksqldb-tools/pom.xml
ksqldb-udf-quickstart/pom.xml
ksqldb-udf/pom.xml
ksqldb-version-metrics-client/pom.xml
pom.xml

Setting the jenkins config to use nano versioning. No longer need to define upstream repos as we now define downstream repos which will be automated in the future. Removed all of the snapshot versions and replaced with nano versions. Updated all of the dependency versions. Updated the make file so the rpm version parsing works with nano versioning, and applied the batch mode option to all maven commands so we don't get download progress and color codes in the CI logs.
These changes will be merged during phase two of the nano versioning roll out.

ST-3461: Nano versioning

---

pom.xml

The packaging build is failing because of warnings while compiling ksqldb-rest-module. These warnings do not happen locally or during the repo CI build. I am temporarily disabling the option to make these warnings fail the build. We will need to figure out why this only happens during packaging builds and then we can re-enable it.
```
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ ksqldb-rest-model ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 84 source files to /tmp/confluent-artifacts-ZKaAVl/ksqldb/ksqldb-rest-model/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] No SupportedSourceVersion …
```

build: temporarily disabling warnings as errors during compile

---

ksqldb-engine/src/main/java/io/confluent/ksql/topic/TopicDeleteInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/topic/TopicDeleteInjectorTest.java

addresses https://github.com/confluentinc/ksql/pull/6449/files/437ef4bf08a9020d23f315306711d8e090e473aa#r506760845 (actually uses the closer 🤦 )

chore: fix typo in use of closer

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandQueue.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/DistributingExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

Attempts to cleanup and state associated with a command id when a transaction for that command fails to commit properly.
Fixes #6340 
Ran unit tests

fix: Properly clean up state when executing a command fails

---

docs/developer-guide/ksqldb-reference/quick-reference.md

Removes `IN` from docs—not supported yet.

docs: remove non-existent `IN` syntax from docs

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/KsqlVersion.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/model/KsqlVersionTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanLoader.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCasePlanLoaderTest.java

POM now has version set to `6.1.0-0`, which `KsqlVersion` couldn't handle.  This causes any attempt to generate new historical QTT test cases to fail.
- Updated `KsqlVersion` to be able to handle new format.
- Added unit test for new format.
- Added unit test to test against latest version in POM, so we pick this up earlier next time.
Usual

test: fix KsqlVersion so it supports new version format

---

ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/metrics/RocksDBMetricsCollector.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/metrics/RocksDBMetricsCollectorTest.java

adds more rocksdb metrics. they are free to add, we only pay the cost of collecting them if we query
jmx. Plus, they are pretty aggressively throttled, so collection should be very infrequent.
tested on a local ksql server

chore: add more aggregated rocksdb metrics

---

ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1594233263741/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.1.0_1594164260142/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1594233263917/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.1.0_1594164260318/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1594233264114/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.1.0_1594164260506/spec.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/collect-list.json

One of several PRs to fix the broken master build. Full set needed for green build: [#6487, #6486,#6494]
There seems to have been an upstream change that means intermediate output is no longer being suppressed.  This is only affecting a single QTT test, (and its historic versions) The test was previously:
```json
{
"name": "collect_list string table",
"format": ["AVRO", "JSON", "PROTOBUF"],
"CREATE TABLE TEST (ID BIGINT PRIMARY KEY, VALUE varchar) WITH (kafka_topic='test_topic', value_format='{FORMAT}');",
"CREATE TABLE S2 as SELECT ID, collect_list(value) as collected FROM test group by id;"
],
"inputs": [
{"topic": "test_topic", "key": 0,"value": {"VALUE": "foo"}},
{"topic": "test_topic", "key": 100,"value": {"VALUE": "baz"}},
{"topic": "test_topic", "key": 0,"value": …
```

test: fix QTT tests after upstream change

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/table/builder/ListVariablesTableBuilder.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/DefineVariable.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/ListVariables.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/UndefineVariable.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListVariablesExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/VariableExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListVariablesExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/VariableExecutorTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/SessionProperties.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/VariablesList.java

This is part of [KLIP-38 - Variable Substitution](https://github.com/confluentinc/ksql/blob/master/design-proposals/klip-38-variable-substitution.md
)
Variable substitution will have a follow-up PR.
It adds a syntax to interact with session variables:
- DEFINE <name> = '<value>';
- UNDEFINE <name>;
- (LIST | SHOW) VARIABLES
^ The KLIP proposed the use of `DEFINE` to list values. But I saw the `SHOW` more appropriate as we have SHOW and LIST syntax for other entities. I will change the KLIP after variable substitution is merged.
The syntax is added on the server-side and CLI-side. 
For the server-side, the variable scope is seen per-request. i.e. 
```
Request 1 will return the variables `x` and `y`.
{ 
statement: "
DEFINE x = '1';
DEFINE y = '2';
SHOW VARIABLES;
"
}
Request 2 will return …
```

feat: new syntax to interact with session variables (define/undefine/show variables)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

Ensures the `ExecutorService` in `PullQueryExecutor` is shutdown with the app.
This omission shouldn't cause issues in prod, but does in tests. Each test that starts the `PullQueryExecutor` was creating 100 threads and leaving them running.  Over the entire build that's a LOT of threads!
Usual

chore: fix leaked executor

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

Fixes the `TestKsqlRestApp` so that you can shut it down and restart it and submit new requests without it failing because it 'timed out waiting for previous command to be handled', because it's not resetting the `lastCommandSequenceNumber` when the server is restarted.
This means you can configure intellj to run RQTT until failure.  Which is useful!

test: allow RQTT to 'run until failure' (MINOR)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/AppInfo.java

Fix NPE on startup when running locally.

chore: avoid NPE on startup if 'git.properties' missing (MINOR)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/AuthenticationPluginHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/KsqlAuthorizationProviderHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProvider.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/AuthTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/Http2OnlyStreamTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/MaxQueriesTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ServerStateTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TlsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProviderTest.java

Fixes https://github.com/confluentinc/ksql/issues/6479
Context:
There are endpoints in `KsqlServerEndpoints` that do not require a security context initialized. Some of these endpoints do not require authentication, so a security context should not be initialized because there is no `Principal` authenticated. 
The current Vert.x code in `KsqlServerEndpoints` attempted to initialize the security context on endpoints where the user was not authenticated. This caused an error when calling these endpoints even with valid credentials. The fix was just to prevent initializing the security contexts, which is unnecessary.
Verified manually with Confluent RBAC library.
* `User:ksql` has valid credentials and has authorization to the server.
* `User:user1` has valid credentials …

fix: Internal Server Error for /healthcheck endpoint in RBAC-enabled

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerFunctionalTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json

Relates to https://github.com/confluentinc/ksql/issues/6484.
Currently, the error message for a query such as 
```
CREATE STREAM joined AS 
SELECT * 
FROM A
LEFT JOIN B b1 ON A.b1_id = b1.id
LEFT JOIN B b2 ON A.b2_id = b2.id;
```
is `Can not join 'B' to 'B': self joins are not yet supported.` which is misleading since the query is not actually a self-join. This PR updates the error message to `N-way joins do not support multiple occurrences of the same source. Source: 'B'`
Unit + QTT.

chore: clarify self-join error message for n-way joins (MINOR)

---

docs/concepts/time-and-windows-in-ksqldb-queries.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-push-query.md
docs/operate-and-deploy/installation/server-config/config-reference.md
docs/reference/sql/appendix.md

fixes #6517 - we can revert this PR when we're ready to re-introduce suppress after finishing the AK side of the change

docs: remove references to EMIT FINAL

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksqldb-common/src/main/java/io/confluent/ksql/properties/LocalProperties.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/test/java/io/confluent/ksql/properties/LocalPropertiesTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/KsqlExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksqldb-parser/pom.xml
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/VariableSubstitutor.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/exception/ParseFailedException.java
ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/VariableSubstitutorTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RequestHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/RequestValidator.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/RequestHandlerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/RequestValidatorTest.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
pom.xml

This is part of [KLIP-38 - Variable Substitution](https://github.com/confluentinc/ksql/blob/master/design-proposals/klip-38-variable-substitution.md)
It implements variable substitution on SQL statements, both the Server-side and CLI-side. Variables are referenced in statements with the `${}` characters. For instance:
For the CLI-side, the scope is per-session. The following example will create the `s1` stream that reads from topic `t1`.
```
ksql> define topicName = 't1';
ksql> define streamName = 's1';
ksql> create stream ${streamName} with (kafka_topic='${topicName}');
```
For the server-side, the variable scope is seen per-request. The following example will create the `s1` stream that reads from topic `t1`.
Request 1 will create stream `s1` from topic `t1`:
```
{ 
statement: "
define …
```

feat: support variable substitution in SQL statements

---

design-proposals/klip-38-variable-substitution.md
docs/developer-guide/index.md
docs/developer-guide/variable-substitution.md

Add documentation for how to use variable substitution.
Merge after https://github.com/confluentinc/ksql/pull/6504 is merged.

docs: update KLIP-38 and add Docs for Variables in ksqlDB

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java

Fixes https://github.com/confluentinc/ksql/issues/6367
Whenever a request is sent to either query endpoint, `DefaultApiSecurityContext.create(routingContext)` is called and a new service context is created. We're not closing the service context created in `createQueryPublisher` which causes the admin client created as part of the join query to never get closed, thus leaking the admin client thread.
Manual testing with debugger, the number of admin client threads don't go up after repeatedly issuing join queries to the `query-stream` endpoint

fix: clean up leaked admin client threads when issuing join query to query-stream endpoint

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/KsqlRequestExecutor.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/cmd/RunScript.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/cmd/RunScriptTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/VariablesList.java

There are three fixes in this PR:
* fix: allow '-e' parameter to use variable substitution
* fix: SHOW VARIABLES is not working with RUN SCRIPT and '-f' parameter
* fix: RUN SCRIPT and '-f' parameter do not handle PRINT/SELECT queries
Added unit tests and verified manually

fix: '-e/-f' CLI parameters are not handling session variables correctly

---

build-tools/pom.xml
ksqldb-api-client/pom.xml
ksqldb-api-reactive-streams-tck/pom.xml
ksqldb-benchmark/pom.xml
ksqldb-cli/pom.xml
ksqldb-common/pom.xml
ksqldb-console-scripts/pom.xml
ksqldb-docker/pom.xml
ksqldb-engine-common/pom.xml
ksqldb-engine/pom.xml
ksqldb-etc/pom.xml
ksqldb-examples/pom.xml
ksqldb-execution/pom.xml
ksqldb-functional-tests/pom.xml
ksqldb-metastore/pom.xml
ksqldb-package/pom.xml
ksqldb-parser/pom.xml
ksqldb-rest-app/pom.xml
ksqldb-rest-client/pom.xml
ksqldb-rest-model/pom.xml
ksqldb-rocksdb-config-setter/pom.xml
ksqldb-serde/pom.xml
ksqldb-streams/pom.xml
ksqldb-test-util/pom.xml
ksqldb-tools/pom.xml
ksqldb-udf-quickstart/pom.xml
ksqldb-udf/pom.xml
ksqldb-version-metrics-client/pom.xml
licenses/licenses.html
pom.xml

Merging master into 6.1.x in https://github.com/confluentinc/ksql/pull/6538 accidentally overrode maven versions on the 6.1.x branch with those on master as well. This PR restores the proper versions.
Built locally with https://github.com/confluentinc/ksql/commit/f2b8d8397106110a51ec73a1c9601667775a6a7f reverted, as the branch builder is expected to fail otherwise.

chore: fix maven version on 6.1.x (MINOR)

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/KsqlRequestExecutor.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/cmd/RunScript.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/cmd/RunScriptTest.java

PR https://github.com/confluentinc/ksql/pull/6537 added a fix in RUN SCRIPT and '-f' parameter to allow the use of SELECT/PRINT statements. However, this causes the RUN SCRIPT to override variables and properties from the current CLI session, something wasn't supposed to do.
This PR fixes the issue with RUN SCRIPT by reverting the change (no PRINT/SELECT support), but leaving the PRINT/SELECT support with the '-f' command parameter. It is a temporary fix for 0.14 and 6.1.
A follow-up PR should be done for 0.15 to allow RUN SCRIPT support PRINT/SELECT, but without overriding variables and properties from the CLI (as KLIP-38 specifies).

fix: avoid RUN SCRIPT to override CLI session variables/properties

---

pom.xml

Reverts https://github.com/confluentinc/ksql/pull/6543 in order to stabilize the build again. We can reapply when we're ready to cut the 0.14 RC.
Will wait for build to pass before merging.

chore: revert "bump AK version to 6.1.0-beta201006024150-hf-1 (#6543)"

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicBackupImpl.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/restore/KsqlRestoreCommandTopic.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicBackupImplTest.java

Fix four findbugs (and clean up code a little)
question is... why is our build not failing, given we have findbugs errors?  Could it be that spotbugs is missing this check?
Update:
Ran `mvn spotbugs:check` locally without this fix and spotbugs did not report any issues... which is bad!
Here's an example of the error in question:
```java
throw new KsqlException(String.format(
"Invalid CommandId string (line %d): %s",
n, new String(record.getLeft(), StandardCharsets.UTF_8), e
));
```
Note how `e` is unintentionally being passed as a third parameter to `String.format` rather than as a second parameter to the exception constructor.
Findbugs does find this error.

chore: fix findbugs errors

---

docs/developer-guide/ksqldb-clients/contributing.md

Fixes https://github.com/confluentinc/ksql/issues/6562.
This needs to be cherry-picked to 0.12.0-ksqldb and 0.13.x-ksqldb. I'll do that once this is merged.

docs: fix dead links in client contributing guide (MINOR)

---

docs/developer-guide/ksqldb-clients/contributing.md

From https://github.com/confluentinc/ksql/pull/6564.

docs: cherry-pick: fix dead links in client contributing guide (DOCS-5762)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/Server.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TlsTest.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java

Fixes https://github.com/confluentinc/ksql/issues/6555
Functionality of the configs `ssl.enabled.protocols` and `ssl.cipher.suites` were lost in the Jetty -> Vert.x migration. This PR adds back the functionality.
There were also some other configs that weren't migrated:
- `ssl.endpoint.identification.algorithm`: I'm not entirely clear on the expected behavior of this config, particularly because it's a client config, not a server config. If configured, ksqlDB properly passes the config to outgoing clients such as Kafka admin clients, producers, consumers, etc. This PR adds support for the config in the ksqlDB CLI, for use when connecting to ksqlDB. Is the config also meant to apply to ksqlDB intra-node clients? Currently, hostname verification is configured for these intra-node requests …

fix: add back configs for setting TLS protocols and cipher suites

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/SourceDescription.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/AdminResponseHandlers.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/SourceDescriptionImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/SourceDescriptionImplTest.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/DdlCommandExec.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/DdlCommandExecTest.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/MetaStore.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/MutableMetaStore.java
ksqldb-metastore/src/test/java/io/confluent/ksql/metastore/MetaStoreImplTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionFactory.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionFactoryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionTest.java

This is partial implementation of [feat: terminate persistent query on DROP command](https://github.com/confluentinc/ksql/pull/6143)
The first commit of this PR was already reviewed in the above PR (https://github.com/confluentinc/ksql/pull/6143). This PR only adds extra work to:
* Return DROP source constraints from DESCRIBE EXTENDED
* Drop sources in order for Rest QTT cleanup methods
The change for this PR adds a constraint to a source to not delete it if it is referenced by another source. For instance:
```
ksql> create stream t1(id int) with (kafka_topic='t1');
ksql> create stream s1 as select * from t1;
ksql> terminate CSAS_S1_9;
ksql> drop stream t1;
Cannot drop T1.
The following streams and/or tables read from this source: [S1].
You need to drop them before dropping T1.
ksql> …
```

feat: add constraint to deny drop sources referenced by other CREATE_AS sources

---

ksqldb-common/src/main/java/io/confluent/ksql/properties/with/InsertIntoConfigs.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryIdUtil.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/StatementRewriter.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/QueryIdUtilTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/StatementRewriterTest.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/InsertIntoProperties.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateAsSelect.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/InsertInto.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/QueryContainer.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/properties/with/InsertIntoPropertiesTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/InsertIntoTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

Implements https://github.com/confluentinc/ksql/issues/6533
Add a `WITH` clause to the `INSERT/SELECT` statement to allow users specify a custom query QUERY_ID. 
For intance:
```
ksql> insert into s1 with (query_id='my_insert_id') select * from s1;
Message                            
------------------------------------
Created query with ID MY_INSERT_ID 
------------------------------------
ksql> show queries;
Query ID     | Query Type | Status    | Sink Name | Sink Kafka Topic | Query String                                              
----------------------------------------------------------------------------------------------------------------------------------
MY_INSERT_ID | PERSISTENT | RUNNING:1 | S1        | t1               | insert into s1 with (query_id='my_insert_id') select …
```

feat: add WITH clause and QUERY_ID property to INSERT INTO statements

---

docs/developer-guide/ksqldb-reference/operators.md
docs/developer-guide/ksqldb-reference/scalar-functions.md

Originally intended to add `CAST` to the docs, but Andy beat me by a few hours. Made some cosmetic fixes along the way. For example, the preface in the Operators section had broken formatting, and was just duplicating what is in the right nav bar.

Cosmetic doc fixes

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json

Implements #6441
Registering schema defined at CS/CT statement in SR when inferring schema in topic, so that avoid the need to set a dummy key/value schema.
Current code:
As the comments advise, there three places from which `allTopics` map get populated:
1. add all topics from topic nodes to the map
2. Infer topics if not added already
3. Get topics from inputs and outputs fields
This concept is also supported [schema-inference](https://docs.ksqldb.io/en/latest/concepts/schemas/#schema-inference)
As per **CR with/without key**, the doc mentions, when sending **message-values**, `The schema must be registered in Schema Registry under the subject pageviews-avro-topic-value`, therefore these scenarios must declare **schema-values** in `topic-node` to replicate SR, however in `avro.json`, …

chore: support partial schema inference in QTT (#6441)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopic.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicBackupImpl.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/CommandTopicCorruptionException.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/IncompatibleKsqlCommandVersionException.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/restore/KsqlRestoreCommandTopic.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/restore/RestoreOptions.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/RestoreCommandTopicIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicBackupImplTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandTest.java

https://github.com/confluentinc/ksql/issues/6305
Added a `-s` flag for skipping commands when restoring. If the flag isn't present, the restore command program will exit if it encounters errors deserializing commands from the command topic backup file. If it is present and true, it'll skip over the incompatible command instead. The program then prints out the number of skipped commands and tries to clean up any left over KafkaStreams internal topics and state stores if the skipped command was a query.
Added integration test
Local manual test

feat: update ksql restore command to skip incompatible commands if flag set

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/array/CollectListUdaf.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/array/CollectListUdafTest.java

Fixes https://github.com/confluentinc/ksql/issues/6341
Adds a check for the index of the last value and does nothing if it's not found.

fix: Check for index before removing value in undo of COLLECT_LIST

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/ImmutableAnalysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/RewrittenAnalysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/DdlCommandFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java

Before this PR, the `CreateStreamCommand` creation code was redundant in the `EngineExecutor.maybeCreateSinkDdl` and the `CreateSourceFactory`. This PR moves the code from the `EngineExecutor` to the `CreateSourceFactory` to re-use part of the code there.
Right now, the PR doesn't re-use code. But it will be needed by https://github.com/confluentinc/ksql/pull/6073 so it checks if the stream or table command exists before creating it.

refactor: re-use CreateSourceFactory to create streams/tables for CREATE_AS statements

---

docs/tutorials/embedded-connect.md
mkdocs.yml

From https://github.com/confluentinc/ksql/pull/6614 to 0.13.x-ksqldb.

docs: cherry-pick: use site var for kafka-connect-jdbc version (DOCS-5870)

---

docs/developer-guide/variable-substitution.md
ksqldb-parser/src/main/java/io/confluent/ksql/parser/VariableSubstitutor.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/VariableSubstitutorTest.java

Issue: Variables cannot be referenced in the DEFINE statement. i.e.
```
ksql> define env = 'qa';
ksql> define topicName = 'topic_${env}';
ksql> show variables;
Variable Name | Value    
--------------------------
env           | qa       
topicName     | topic_${env}
--------------------------
```
This PR fixes the above issue by looking at the `VariableValueContext` in the `VariableSubstitutor`, and replace any variables referenced there.
Example:
```
ksql> define env = 'qa';
ksql> define topicName = 'topic_${env}';
ksql> show variables;
Variable Name | Value    
--------------------------
env           | qa       
topicName     | topic_qa 
--------------------------
```
Verified manually

fix: cannot reference variables in DEFINE statement

---

ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SyntaxErrorValidator.java
ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/SyntaxErrorValidatorTest.java

Issue: The `DEFINE/UNDEFINE` statements do not allow variables names that matches the symbolic names found in `SqlBase.g4`. For instance `define topic = 't1';` fails because `topic` is a reserved keyword. However, these should not be a problem for variables names. We  should allow any variable name.
The `SqlBase.g4` has a rule for `nonReservedKeyword` which I used initially, but this is not scalable. There are several missing keywords in that rule, and not all statements allow the same keywords as non-reserved. To scale this rule, I added an extra validation to the parser error listener to check if a syntax error is caused by a keyword being used as variable name. If so, then it returns silently without throwing any error, thus allowing the `define` and `undefine` statements to continue. …

fix: allow reserved keywords on variables names

---

mkdocs.yml

To be consistent with conf.py in the CP docs repo.

docs: bump Scala version to 2.13 (DOCS-5875)

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/PersistentQueryMetadataTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

Fixes the build. Streams is not yet ready for migrating to the new API, but since we're building off master we're picking up this deprecation. AK might revert the `@Deprecated` for this method and we can revert this PR after that build is picked up in kafka-ccs.
https://github.com/confluentinc/ksql/issues/6639 tracks reverting it
Built it

chore: suppress deprecation UncaughtExceptionHandler

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/generic/GenericExpressionResolver.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/generic/GenericRecordFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlanBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/WhereInfo.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/generic/GenericExpressionResolverTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json

fixes #6602 
Supports key-lookups for keys that are not just literals. This is necessary for the generic key work being done because we will expose keys that are not just primitives, but can also be arrays and structs.
Note that maps are not tested because of #6621, we may consider just prohibiting maps from being keys altogether. I will port this over after #6375 is merged.
- new unit tests
- new RQTT tests

chore: support complex key pull queries

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksqldb-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/RequiredColumns.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ColumnExtractor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/StructKeyUtil.java
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_key_expression_-_with_null_value/6.2.0_1605825669504/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_key_expression_-_with_null_value/6.2.0_1605825669504/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_key_expression_-_with_null_value/6.2.0_1605825669504/topology
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_only_key_column_-_with_null_value/6.2.0_1605825669435/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_only_key_column_-_with_null_value/6.2.0_1605825669435/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_only_key_column_-_with_null_value/6.2.0_1605825669435/topology
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_udf_key_expression_-_with_null_value/6.2.0_1605825669538/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_udf_key_expression_-_with_null_value/6.2.0_1605825669538/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_udf_key_expression_-_with_null_value/6.2.0_1605825669538/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/PartitionByParamsFactory.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/PartitionByParamsFactoryTest.java

Fixes https://github.com/confluentinc/ksql/issues/6646
The current mapper used in repartitions builds the new key by evaluating the generated expression on the value. If the value is null, the mapper returns an empty key rather than the original key. More intuitive behavior is to detect when the partition by expression depends only on key column(s) and evaluate the new key on the key columns in these cases, allowing null values to be propagated. This is needed to enable the propagation of tombstones in https://github.com/confluentinc/ksql/pull/6635
Unit + QTT.

fix: propagate null-valued records in repartition

---

ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlArray.java
ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlDecimal.java
ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlMap.java
ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlPrimitiveType.java
ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlStruct.java
ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlType.java
ksqldb-udf/src/main/java/io/confluent/ksql/types/KsqlStruct.java
ksqldb-udf/src/test/java/io/confluent/ksql/schema/ksql/types/SqlArrayTest.java
ksqldb-udf/src/test/java/io/confluent/ksql/schema/ksql/types/SqlDecimalTest.java
ksqldb-udf/src/test/java/io/confluent/ksql/schema/ksql/types/SqlMapTest.java
ksqldb-udf/src/test/java/io/confluent/ksql/schema/ksql/types/SqlPrimitiveTypeTest.java
ksqldb-udf/src/test/java/io/confluent/ksql/schema/ksql/types/SqlStructTest.java
ksqldb-udf/src/test/java/io/confluent/ksql/types/KsqlStructTest.java

`KsqlStruct` is not yet used. However, the code calls `validateValue` when setting the value of a field. This check is not free and is on the critical path.  ksqlDB is strongly typed, so the only way the type would be wrong would be if a function or deserializer where returning incorrect data, i.e. a bug.  We should not pay the production runtime cost of checking _every_ field we set during _every_ record we process.
Rather than validate here, we should add a `-debug` option to ksqlDB that validates the returned data from deserializers and functions against the expected schema, as suggested here: https://github.com/confluentinc/ksql/issues/3624#issuecomment-729532558
not production code.

refactor: remove unused validation code

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/RegexClassifier.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/RegexClassifierTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java

Fixes error categorization when streams exits due to an internal NPE
- fixes the regex categorizer to correctly handle NPEs. NPEs have null
descriptions, so this patch changes the categorizer to ignore the
description if its null.
- fixes the uncaught handler to categorize errors as UNKNOWN if the
categorizer throws

fix: fix error categorization on NPE from streams

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/HARouting.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/HARoutingTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/AssertEventually.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/ThreadTestUtil.java

This fixes a leaked executor service with 100 threads that is being created once-per-request for pull queries.
1. The first commit fixes the leaked executor.
2. The second enhances RQTT to (hopefully) catch such errors in the future (this is the second such bug in quick succession).
This bug was stopping RQTT running locally for me, because the JVM was running out of resources.
**IMPORTANT**:  It looks to my untrained eye that the current pull query code is creating an executor with 100 threads **_on each request_**. (HARouting is created per-request).  Even with the code now closing down the executor, surely this isn't what we want?
**Minimal**

Pull query thread leak

---

ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json

Follows up from #6642 to actually enable support for windowed joins for SR-keys. This also fixes an issue where forced repartition allowed arbitrary repartitioning of tables.
QTT

chore: add support for windowed SR-key joins

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/auth/JaasAuthProviderTest.java

Functionality was lost from the JaasAuthProviderTest over the course of a couple refactors. Specifically, the test was no longer verifying that the authentication roles config was properly used in validating user authorization. This PR fixes the tests to check the behavior again, and also performs some minor cleanup in the file.
Credits to @big-andy-coates for discovering the test gap!
Tests pass now, and they also fail if conditions are changed to be erroneous.

test: fix JaasAuthProviderTest validation

---

README.md
design-proposals/README.md
docs/developer-guide/ksqldb-clients/contributing.md

We've just been using the community channel for all discussion, so let's recommend that one alone.

docs: development in single Slack channel

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/RegexClassifier.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/RegexClassifierTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java

Fixes error categorization when streams exits due to an internal NPE
- fixes the regex categorizer to correctly handle NPEs. NPEs have null
descriptions, so this patch changes the categorizer to ignore the
description if its null.
- fixes the uncaught handler to categorize errors as UNKNOWN if the
categorizer throws

fix: fix error categorization on NPE from streams (#6655)

---

ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_literal_args_-_JSON/6.0.0_1591214175189/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_literal_args_-_JSON/6.0.0_1591214175189/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_literal_args_-_JSON/6.0.0_1591214175330/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_literal_args_-_JSON/6.0.0_1591214175330/spec.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/elements.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/string-lpad-rpad.json
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/TableElements.java

Fixes #6352 by throwing an error message if anyone creates a source with no value columns.
Unit tests and QTT tests

fix: throw error message on create source with no value columns

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/LoggingHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/LoggingRateLimiter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/Server.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/LoggingHandlerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/LoggingRateLimiterTest.java

Changes the rate limiting logic within LoggingHandler to be a shared singleton.  Otherwise the limit is multiplied by the number of server verticles.
Ran unit tests and ran high qps requests manually to verify correct logging.

fix: Refactors rate limiter within LoggingHandler to be singleton

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/protobuf.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/KeyFormatUtils.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufFormat.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactory.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactoryTest.java

Supports protobuf keys (still under the config flag) 
updated `protobuf.json` to have tests for protobuf keys

feat: support PROTOBUF keys

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/FileWatcherTest.java

Allows the file watcher creation test to notify the call back more than once. We've seen the build
sometimes fail because it's notified twice. I suspect this can happen if the create and write straddle
a second boundary.

fix: allow the file watcher test to be notified more than once

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/RegexClassifier.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/RegexClassifierTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java

* fix: fix error categorization on NPE from streams
Fixes error categorization when streams exits due to an internal NPE
- fixes the regex categorizer to correctly handle NPEs. NPEs have null
descriptions, so this patch changes the categorizer to ignore the
description if its null.
- fixes the uncaught handler to categorize errors as UNKNOWN if the
categorizer throws

fix: fix error categorization on NPE from streams (#6655) (#6668)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestUtils.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/as_value.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/delimited.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/json.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/json_sr.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/kafka.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-col-keys.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/project-filter.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/protobuf.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/GenericKeySerDe.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/GenericKeySerDeTest.java

This PR is stacked on https://github.com/confluentinc/ksql/pull/6694. Only the last commit needs to be reviewed.
This PR separates the current key format feature flag (`ksql.key.format.enabled`) into three:
- `ksql.key.format.enabled` : controls the addition of new key formats. I've kept the old name in order to avoid clashes with https://github.com/confluentinc/ksql/pull/6692
- `ksql.complex.key.format.enabled` : controls support for array and struct keys
- `ksql.multicol.key.format.enabled` : controls support for multi-column keys
QTT

chore: split key format feature flag

---

ksql-cli/src/test/java/io/confluent/ksql/cli/BasicAuthFunctionalTest.java
ksql-engine/pom.xml
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
pom.xml

Using Jersey's private utility function prevent Jersey upgrades in upstream rest-utils. This pull request replaces jersey's Base64 utility with Java's built-in Base64 in two tests.
Tests run by CI

fix: use Java's Base64 instead of jersey's

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

We were getting failures like:
```
java.lang.UnsupportedOperationException: 
error msg: Could not write the statement 'TERMINATE CTAS_ID_15_9;' into the command topic.
Caused by: Timeout while waiting for command topic consumer to process command
topic
at io.confluent.ksql.cli.CliTest.setUp(CliTest.java:205)
```
I have no idea why those are happening, but I hope that this change (which just removes the parts which terminate queries) will make this better. Note that all queries are terminated after the class is done because `KSQL_REST_APP` is an `ExternalResource` which gets cleaned up by JUnit.

test: attempt to make CliTest more robust

---

ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocator.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocatorTest.java

Fixes https://github.com/confluentinc/ksql/issues/6249
Add a better error message when the issue in https://github.com/confluentinc/ksql/issues/6249 is thrown. 
```
ksql> CREATE TABLE MSG_COUNT WITH (KAFKA_TOPIC='MSG_COUNT', PARTITIONS=1, REPLICAS=1) AS SELECT
'X' X,
COUNT(*) MSG_CT
FROM PAGEVIEWS PAGEVIEWS
GROUP BY 'X'
EMIT CHANGES;
ksql> SELECT * FROM MSG_COUNT WHERE X='X';
Materialized data for key ['X'] is not available yet. Please try again later.
```
There was another fix that retry the failing request here (https://github.com/confluentinc/ksql/pull/6633), but seems pull queries must fail fast. Instead, the user should be warned about the issue and let them know they need to retry.
Uni tests …

fix: change locate() error message for a more user-friendly message

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/TopicValidationUtil.java
ksqldb-execution/src/main/java/io/confluent/ksql/exception/KafkaTopicExistsException.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/stubs/StubKafkaTopicClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/logging/processing/ProcessingLogServerUtils.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtilsTest.java

The number of partitions for the processing log topic is configurable via the `ksql.logging.processing.topic.partitions` config. However, if the processing log topic already exists with a different number of partitions, the existing topic is left untouched and the ksqlDB server continues to start up after logging a message indicating that topic exists and the number of partitions was not as expected. (The same behavior is true as well for number of replicas.) This log message is currently logged at level INFO. This PR changes the log message to level WARN instead.
Manual.

chore: update processing log exists msg from info to warn (MINOR)

---

docs/concepts/schemas.md
docs/developer-guide/serialization.md

Docs to accompany https://github.com/confluentinc/ksql/pull/6694

docs: docs for AVRO and JSON_SR keys

---

ksqldb-engine/src/main/java/io/confluent/ksql/KsqlExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/HARouting.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/HARoutingTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/WSQueryEndpointTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisherTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

With the pull query physical plan refactoring, a bug was introduced where the executor service was instantiated per pull query request. I fixed that by creating it once in the `KsqlRestApplication`. 
All tests pass

fix: don't create threads per request

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/offset/KudafByOffsetUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/offset/LatestByOffset.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/offset/LatestByOffsetTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_merging_session_windows_-_with_nulls_ignored_when_merging/6.2.0_1607120094381/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_merging_session_windows_-_with_nulls_ignored_when_merging/6.2.0_1607120094381/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_merging_session_windows_-_with_nulls_ignored_when_merging/6.2.0_1607120094381/topology
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_merging_session_windows_-_with_nulls_not_ignored_when_merging/6.2.0_1607120094482/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_merging_session_windows_-_with_nulls_not_ignored_when_merging/6.2.0_1607120094482/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/latest-offset-udaf_-_merging_session_windows_-_with_nulls_not_ignored_when_merging/6.2.0_1607120094482/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/latest-offset-udaf.json

Fixes: https://github.com/confluentinc/ksql/issues/6557
Added extra tests for ignoring nulls when merging

fix: Fixes bug in latests-by-offset when using nulls and sessions windows

---

docs/operate-and-deploy/installation/server-config/config-reference.md
ksqldb-common/src/main/java/io/confluent/ksql/configdef/ConfigValidators.java
ksqldb-common/src/test/java/io/confluent/ksql/configdef/ConfigValidatorsTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/LoggingHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/LoggingRateLimiter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/LoggingHandlerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/LoggingRateLimiterTest.java

Makes response codes logging rate limited too.  Also prints a message when rate limit is hit.
Unit tests and manual testing

fix: Makes response codes rate limited as well as prints a message when it is hit

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksqldb-common/src/main/java/io/confluent/ksql/util/ReservedInternalTopics.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/KsqlEngineMetrics.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/KsqlEngineMetricsTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunnerMetrics.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorMetrics.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerMetricsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorMetricsTest.java

Addresses https://github.com/confluentinc/ksql/issues/5948
We'll keep the legacy metrics with the ksql service id in the metric name for now so as to not break existing monitoring/metrics collection. Once those have been updated,  the old metrics can be removed at a later date.
The old legacy metrics were removed also.
Old bean name:
`io.confluent.ksql.metrics:type=_confluent-ksql-default_ksql-engine-query-stats`
New bean name:
`io.confluent.ksql.metrics:type=_confluent-ksql-engine-query-stats,ksql_service_id=default_`
Unit test
Looked at metrics in jconsole and verified that there are two sets of metric, one with new naming scheme and one with old

chore: emit metrics with ksql.service.id in metrics tag

---

ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/filters/KsqlAuthorizationFilterTest.java

This pull request updates the call signature for jersey's `ContainerRequest(...)` to a non-deprecated one in a test. Jersey 2.30 and above add a new `Configuration` parameter (see [here](https://javadoc.io/static/org.glassfish.jersey.bundles/jaxrs-ri/2.30/org/glassfish/jersey/server/ContainerRequest.html#constructor.summary)). 
The context for this pull request is that I am trying to update Jersey to 2.31 in upstream rest-utils (https://github.com/confluentinc/rest-utils/pull/210). Ksql treats warnings as errors, and the deprecation warning causes the upstream pull request from building correctly. Once that pull request actually upgrades the jetty version, ksql builds would fail without this current PR specifically because of treating deprecation warnings as errors. 
Merging this pull …

fix: (minor) don't use deprecated jersey calls

---

docs/developer-guide/joins/synthetic-keys.md

Removes a dead shortlink that doesn't contribute to the content.

docs: remove dead link

---

docs/concepts/schemas.md
docs/developer-guide/syntax-reference.md

Docs for https://github.com/confluentinc/ksql/pull/6722. I don't see anywhere in the docs today where we say only primitive types are supported as keys. With 0.15, all non-map types will be supported, which this PR explicitly clarifies.

docs: clarify that all data types except maps are supported as keys

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/SchemaRegistryUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/registry/SchemaRegistryUtilTest.java

Fixes #6729 
Don't use `getAllSubjects` when we can get look up just a single subject.
- unit testing
- e2e testing to make sure the right exception is thrown with real SRClient

chore: remove usage of SRClient#getAllSubjects

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopicInfoCache.java

Previous message was confusing:
```
>>>>> Test failed: Topic output: Failed to read record 0. io.confluent.ksql.test.TestFrameworkException: Failed to determine key type for
topic: output
reason: no source found for topic
```
New one gives more information on which topics are available. This is especially important because of case sensitivity.

test: improve error message for unknown output topic in QTT (MINOR)

---

ksqldb-common/src/main/java/io/confluent/ksql/properties/with/CommonCreateConfigs.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/AssertExecutor.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/delimited.json
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceAsProperties.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceProperties.java

Partial work toward #824 by supporting `KEY_DELIMITER` for delimited and adding some multi-col tests for delimited format.
Added QTT tests

chore: support KEY_DELIMITER and tests for multi-col

---

ksqldb-common/src/main/java/io/confluent/ksql/config/KsqlConfigResolver.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/test/java/io/confluent/ksql/config/KsqlConfigResolverTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListPropertiesExecutorTest.java

Fixes https://github.com/confluentinc/ksql/issues/6734
Includes `ksql.streams.topic.*` prefixed properties into the `LIST PROPERTIES` output.
```
ksql> list properties;
...        
ksql.streams.topic.min.insync.replicas                 | KSQL  | SERVER           | 1        
...
```
It also allows users to set the `ksql.streams.topic.*` properties from the CLI.
Verified manually

fix: include 'ksql.streams.topic.*' prefix properties on LIST PROPERTIES output

---

docs/developer-guide/ksqldb-clients/java-client.md
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java

The sentences that clarify when it is appropriate to use each of the `streamQuery()` and `executeQuery()` Java client methods are currently underneath the Javadoc excerpts in the docs, which makes them easy to miss. This PR pulls the information above the Javadoc excerpts, and also adds the information into the Javadocs themselves so it will appear in the API docs.

docs: make Java client method usage docs more prominent (MINOR)

---

docs/concepts/schemas.md
docs/developer-guide/aggregate-streaming-data.md
docs/developer-guide/joins/partition-data.md
docs/developer-guide/transform-a-stream-with-ksqldb.md
docs/tutorials/examples.md
docs/tutorials/index.md

Stream Processing Cookbook is out of date and being decommissioned.  This PR replaces links to the Cookbook with links to Kafka Tutorials (https://kafka-tutorials.confluent.io).  
Rendered the docs locally per docs/README.md instructions and validated all changes.

docs: Update ksqlDB Stream Processing Cookbook links to point to Kafka Tutorials

---

CHANGELOG.md
docs/operate-and-deploy/changelog.md

The automatic tool did not add all commits since changes from master were squashed into one commit when applied to 6.1.x
I went over the PR https://github.com/confluentinc/ksql/pull/6538 and added the missing (feat and fix) ones mannualy. I don't know what to do with chore and test PRs though.

chore: create changelog for 0.14.0 release

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/serde/SerdeFeaturesFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKGroupedStream.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestUtils.java
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_multiple_expressions_-_table_aggregate/6.2.0_1608012078420/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_multiple_expressions_-_table_aggregate/6.2.0_1608012078420/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_multiple_expressions_-_table_aggregate/6.2.0_1608012078420/topology
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_multiple_expressions_-_windowed/6.2.0_1608012078274/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_multiple_expressions_-_windowed/6.2.0_1608012078274/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_multiple_expressions_-_windowed/6.2.0_1608012078274/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by-multi-col.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/KeyFormat.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/GroupByParamsFactory.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StepSchemaResolver.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamGroupByBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/TableGroupByBuilder.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/GroupByParamsFactoryTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StreamGroupByBuilderTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/TableGroupByBuilderTest.java

Fixes https://github.com/confluentinc/ksql/issues/6371.
This PR adds support for multi-column GROUP BY. With this change, GROUP BY multiple columns will result in multiple key columns, rather than a single key column that is the string concatenation of the individual key fields (with delimiter `|+|`. A consequence of this change is that GROUP BY multiple columns is no longer allowed when using key formats that do not support it, such as the KAFKA format. 
This is a breaking change, and is currently guarded by a feature flag until we've added the corresponding pull query support and are ready to release. 
This PR adds test coverage in a new QTT file `group-by-multi-col.json` which is a copy-paste of the existing `group-by.json` with some additional tests added. Once the feature flag is …

chore: support multi-column keys in GROUP BY

---

ksqldb-common/src/main/java/io/confluent/ksql/function/FunctionRegistry.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/AggregateAnalyzerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/InternalFunctionRegistryTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/window-bounds.json
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java

tl;dr this PR improves error messages on invalid statements involving GROUP BYs.
The long version: Currently, in the logical planner when we build aggregate nodes, validation is split across the logic for building the aggregate schema (`LogicalPlanner#buildAggregateSchema()`) and for performing the aggregate analysis (`AggregateAnalyzer#analyze()`). The former throws a nice error message if the statement contains a function call that doesn’t exist. The latter throws a nice error message if the GROUP BY expressions contain window bounds (since doesn't support that today). However, the two pieces of logic throw unhelpful errors in the reverse scenarios: if the schema building logic encounters window bounds, it throws an error saying the column doesn’t exist. If the aggregate analyzer …

chore: improve error messages on invalid GROUP BYs

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/SelectionUtil.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/insert-into.json

fixes #6760 by ensuring that the old error message is thrown when we try to insert into a source with more columns than it has. before this patch, the code would fail with IndexOutOfBounds exception when trying to get the column at an index greater than the number of columns. this fixes it by "ignoring" that column and just letting it throw later down the line.
QTT testing

chore: fix bad error message on insert into

---

docs/concepts/schemas.md
ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksqldb-engine/src/main/java/io/confluent/ksql/serde/SerdeFeaturesFactory.java
ksqldb-functional-tests/src/test/resources/historical_plans/multi-col-keys_-_select___from_stream_-_with_key_inference/6.2.0_1608161572199/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-col-keys_-_select___from_stream_-_with_key_inference/6.2.0_1608161572199/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-col-keys_-_select___from_stream_-_with_key_inference/6.2.0_1608161572199/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-col-keys.json

Docs changes and a minor refactor to clarify that key schema inference always results in an unwrapped key today. Also adds a QTT for multi-column key schema inference to confirm.
New QTT passes.

chore: clarify single key unwrapping during schema inference (MINOR)

---

ksqldb-rest-app/pom.xml
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/BasicCallbackHandler.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/auth/BasicCallbackHandlerTest.java

fixes #6730 
Manual testing by adding the following configs to `ksql-server.properties`:
```
authentication.method=BASIC
authentication.realm=KsqlServer-Props
authentication.roles=Developers
```
`docker-compose.yml`:
```
version: '2'
services:
ldap:
image: osixia/openldap:1.4.0
hostname: ldap
container_name: ldap
environment:
LDAP_ORGANISATION: "Confluent"
LDAP_DOMAIN: "confluent.io"
ports:
- "389:389"
volumes:
- "$PWD/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom"
command: "--copy-service"
zookeeper:
image: confluentinc/cp-zookeeper:${CP_VERSION}
environment:
ZOOKEEPER_CLIENT_PORT: 32181
ZOOKEEPER_TICK_TIME: 2000
kafka:
image: confluentinc/cp-enterprise-kafka:${CP_VERSION}
ports:
- "29092:29092"
depends_on:
- zookeeper
environment:
KAFKA_BROKER_ID: 1 …
```

fix: LDAP Authentication

---

docs/concepts/queries/pull.md
docs/developer-guide/ksqldb-reference/select-pull-query.md
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlanBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/WhereInfo.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/operators/WhereInfoTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java

Support pull queries on aggregations that aggregate over multiple key columns by requiring that all keys that make up the primary key are selected in the `WHERE` clause as a conjunction of equality expressions (e.g. `WHERE K1=1 AND K2=2`). 
"In" queries are not yet supported, there's some thinking to be done about how we can support that (cc @AlanConfluent perhaps we could do something like `WHERE K1 IN (1, 2) AND K2 in (3,4)` and this would find keys that make up the cross-product of those fields `{1,3}, {1, 4}, {2, 3}, {2, 4}`)
Alternatively, we could consider supporting `OR` in order to get multiple keys (e.g. `WHERE (K1 = 1 AND K2 =2) OR (K1 = 3 AND K2 = 4`)
- Unit testing
- QTT testing
- e2e testing (in progress)

chore: support multi-col pull queries

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/WhereInfo.java

Fixes https://github.com/confluentinc/ksql/issues/6802
Previously:
```
ksql> select * from foo where v in ('val1', 'val2');
IN expression on unsupported column: V.  See https://cnfl.io/queries for more info.
Add EMIT CHANGES if you intended to issue a push query.
Pull queries require a WHERE clause that:
- limits the query to keys only, e.g. `SELECT * FROM X WHERE <key-column>=Y;`.
- specifies an equality condition that is a conjunction of equality expressions that cover all keys.
```
Now:
```
ksql> select * from foo where v in ('val1', 'val2');
IN expression on unsupported column: V.  See https://cnfl.io/queries for more info.
Add EMIT CHANGES if you intended to issue a push query.
Pull queries require a WHERE clause that:
- limits the query to keys only, e.g. `SELECT * FROM X WHERE …
```

chore: add mention of IN clause to pull query error msg (MINOR)

---

.gitignore
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-col-keys.json

Adds some additional  QTT coverage for null-handling in the context of multi-column keys:
- GROUP BY drops records if any key column evaluates to null
- Table sources do not drop records with null primary key columns, unless the entire key is null

test: additional test coverage for multi-column key null-handling (MINOR)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/KafkaStreamsQueryValidator.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryValidator.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/KafkaStreamsQueryValidatorTest.java

bound the total size of the shared buffer cache used by queries. The
bound is controlled by 2 configs, one for controlling the limit for
persistent queries, the other for transient queries. Today, this limit
is implemented by accounting the full limit for each query against the
total bound. In the future we may implement by using a shared cache.

feat: bound the size of the shared buffer cache used by queries

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/KsqlVersion.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/model/KsqlVersionTest.java

- Add support for Prereleased values. Eg: -alpha1, -beta1234.
- Add unit tests for supported versions.
- Updated exception message to include used pattern for matching.
The `6.2.x-alpha1` branch was failing to build in Jenkins due to a failure in some tests. They surfaced as `NoClassDefFound` exceptions, but if you watched the logs, there was actually an earlier `IllegalArgumentException` being thrown about the version not being in a format, so I tracked that down to here, made the regex a little more tolerant of this valid semver format, made the Exception message slightly more helpfull and added some Unit tests to support.
This is a meta change. Check the `6.2.x-alpha1` branch job in Jenkins and you can see after these changes it passes.

chore: Update VERSION_PATTERN to accomodate Prereleased versioned artifacts

---

mkdocs.yml

From https://github.com/confluentinc/ksql/pull/6781.

docs: cherry-pick: bump versions for 0.15.0 docs (DOCS-6397)

---

docs/how-to-guides/test-an-app.md

See https://github.com/confluentinc/ksql/pull/6713#discussion_r551358794. Based on the previous PR, I assume this needs to be cherry-picked to `6.1.x` and `0.14.0-ksqldb` -- can either @MichaelDrogalis or @JimGalasyn confirm?

docs: adds back text for making input files

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/WebsocketUtils.java
ksqldb-common/src/main/java/io/confluent/ksql/properties/PropertiesUtil.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KeystoreUtil.java
ksqldb-common/src/main/java/io/confluent/ksql/util/VertxSslOptionsFactory.java
ksqldb-common/src/test/java/io/confluent/ksql/util/VertxSslOptionsFactoryTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/Server.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/InternalKsqlClientFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientTest.java

This refactor is part of https://github.com/confluentinc/ksql/pull/6763. I split the previous PR to make the review easier.
This refactor creates a new class, `VertxSslOptionsFactory`, that builds the `JksOptions` and `PfxOptions` objects using the SSL truststore & keystore configs. The class is a util that avoids repeating code to build these objects.
Unit tests are passing

refactor: wrap Vert.x SSL configurations inside a VertxSslOptionsFactory class

---

docs/operate-and-deploy/installation/server-config/config-reference.md

Fixes a reference to `ksql.advertised.listener` in copy.

docs: fix ksql.advertised.listener setting (DOCS-6436)

---

CONTRIBUTING.md
checkstyle/checkstyle.properties

I have encountered some problems with Checkstyle as
described here: https://github.com/checkstyle/eclipse-cs/issues/190
Setting the version used by plugin to 8.18 is a good fix until
I understand who depends on the CheckStyle XML and how I can
fix it.
I have also sorted checkstyle.properties so it is easier to
copy it into the editor plugin configuration
No testing required - made sure IntelliJ works

docs: update onboardings docs for CheckStyle

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/ProjectOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PullProjectNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/PullProjectNodeTest.java

Prior to https://github.com/confluentinc/ksql/pull/6684, select * didn't compile expressions for each of the columns, which makes them much more performant.  This PR remakes that change to avoid a regression.
Unit tests and local benchmarking

fix: Make Select * avoid code gen for projections

---

docs/concepts/time-and-windows-in-ksqldb-queries.md
docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/type-coercion.md
docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md
docs/reference/serialization.md
docs/reference/sql/appendix.md
docs/reference/sql/data-types.md
docs/reference/sql/time.md
docs/reference/user-defined-functions.md

Docs on: 
* Timestamp serialization
* Casting and type coercion
* Brief description of what the timestamp type is
One thing that's concerning is that the word timestamp is also used to refer to timestamp of a record. I've added warnings in sections that talk about

docs: add documentation about timestamp data type

---

CHANGELOG.md
docs/operate-and-deploy/installation/upgrading.md

The upgrade guide is confusing right now since it suggests we don't support in-place upgrades at all, but we actually do for all the newer versions. This PR clarifies this.
Also, we DO support in-place upgrades from 0.7.0 to 0.8.0, whereas the current guide suggests we don't.
@JimGalasyn it'd be great if this could be backported to the live docs branch (0.14.0-ksqldb) once approved and merged. Thanks!

docs: clarify where in-place upgrades are supported

---

config/ksql-server.properties
docs/operate-and-deploy/installation/server-config/security.md
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/ClientOptions.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientOptionsImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTlsMutualAuthTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTlsTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslClientAuthFunctionalTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslFunctionalTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/WebsocketUtils.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KeystoreUtil.java
ksqldb-common/src/main/java/io/confluent/ksql/util/VertxSslOptionsFactory.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ListenersTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TlsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeWithTlsFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/SystemAuthenticationFunctionalTest.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/secure/ClientTrustStore.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/secure/ServerKeyStore.java

Fixes https://github.com/confluentinc/ksql/issues/6719
Different keystore and key passwords are not supported in Vert.x API. Internally. Vert.x always wants to decrypt the Private key using the keystore password. To fix this, this PR decrypts the Private key with the password specified in `ssl.key.password`, then re-encrypts it with the keystore password. The resulted encrypted bytes are then passed to Vert.x to handle the SSL communication.
The code has the re-encryption part in `KeyStoreUtil.java` already. I  just re-use the same keystore password when encrypting the key again.
The rest of the code in `Server.java`, `KsqlClient.java` and `InternalKsqlClientFactory.java` look for the `ssl.key.password` config, and passes the key password to the `KeyStoreUtil`. This is supported only when …

fix: client/server SSL settings fail when 'ssl.key.password' is set

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/EntityUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/EntityUtilTest.java
ksqldb-rest-model/pom.xml
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/ApiJsonMapper.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/SchemaInfoTest.java
ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlDecimal.java

Fixes #6843 
We want DESCRIBE queries to show the precision and scale for DECIMAL columns
It seems to me that maybe it would make sense to carry instances of
SqlBaseType on SchemaInfo instances somehow so that we could delegate
these formatting duties to them?
- new unit tests added

feat: display precision and scale when describing DECIMAL columns

---

config/ksql-server.properties
ksqldb-engine/src/main/java/io/confluent/ksql/query/KafkaStreamsQueryValidator.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/KafkaStreamsQueryValidatorTest.java

The buffer limit check first creates a dummy streams config to get the current
max bytes buffering value. To do this it creates a map of the streams props and
creates the config (with dummy values for all the required fields). However
sometimes those fields are already provided and ImmutableMap doesn't like
overwrites in the builder. So, use a plain old HashMap.

fix: fix how the buffer limit check evaluates streams config

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/BackupRollbackIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/CommandTopicFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/HealthCheckResourceFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java

There's a bug in 0.14.0 that causes the server to not enter degraded state when backups are enabled.
The bug is fixed in https://github.com/confluentinc/ksql/pull/6524 (removing deserialization from the CommandTopicBackupImpl)
This adds an integration test to check that incompatible commands are properly processed.
Also, enhanced the corruption integration test and cleaned up some other tests.

test: add integration test for incompatible command detection with backups enabled

---

findbugs/findbugs-exclude.xml
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_PROTOBUF_in_out/6.2.0_1611359934407/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_PROTOBUF_in_out/6.2.0_1611359934407/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_PROTOBUF_in_out/6.2.0_1611359934407/topology
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_PROTOBUF_should_not_trim_trailing_zeros/6.2.0_1611176012228/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_PROTOBUF_should_not_trim_trailing_zeros/6.2.0_1611176012228/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_PROTOBUF_should_not_trim_trailing_zeros/6.2.0_1611176012228/topology
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_partial_schema/6.2.0_1611365298133/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_partial_schema/6.2.0_1611365298133/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_inference_-_partial_schema/6.2.0_1611365298133/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/decimal.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/protobuf.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactory.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/KsqlProtobufDeserializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/KsqlProtobufSerializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactoryTest.java

fixes #5762
Support for decimal has been added to the Protobuf converter.  This PR enables decimal for Protobuf in ksqlDB.
Unit tests

feat: enable decimal for Protobuf

---

debian/Makefile
debian/confluent-ksqldb.spec.in
debian/control

- The check in the Makefile was overly strict in an attempt to be safe.
Instead of checking for 1 allowed location of being built
(/tmp/confluent), check for the conditions that would cause an issue the
code was originally trying to prevent (removing `/` or `/usr`)
- Remove virtual packages. Testing didn't go as planned for Debian
packages so this change is being undone from https://github.com/confluentinc/ksql/pull/6812
The /tmp/confluent check prevents users from building OS packages from any filesystem location. This check is a good idea to enforce so users don't accidentally remove / or /usr when attempting to build, but it assumes everyone will build the OS packages from /tmp/confluent, which isn't going to be the case always.
On the location check, see how bash reacts:
``` …
```

build: Fix up build process & remove virtual packages from ksqldb

---

docs/troubleshoot-ksqldb.md

Added scenario for java.lang.NoClassDefFoundError when java.io.tmpdir is not writable. 
For more information: https://github.com/confluentinc/ksql/issues/1332
@JimGalasyn

docs: update troubleshoot-ksqldb.md (DOCS-6717)

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/HARouting.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/HARoutingTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/HighAvailabilityTestUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

The PR https://github.com/confluentinc/ksql/pull/6665 made `HARouting` a singleton.  Unfortunately, it also kept a reference to the service context rather than using the user-aware context.  What this meant is that all forward requests did not provide authentication and failed.  This didn't fail in testing because it requires more than two nodes to expose the forwarding failure, since HA makes the request fall back to the fowarder itself.  For that reason, I made the routing functional test use auth, which does test the three node case and was able to expose the bug.
`PullQueryRoutingFunctionalTest` with auth.

fix: Fixes auth for forwarded requests for pull queries

---

ksqldb-common/src/main/java/io/confluent/ksql/errors/LogMetricAndContinueExceptionHandler.java

Don't use the streamthread to construct the log-metric-and-continue logger. Also set the level to
debug - this indicates an error with the data. In production usage of ksql, we've frequently seen
these deserialization errors spamming the ksql log. It was hard to tune the log level because we were
logging with the StreamThread category (which has lots of useful logs for streams internals). It also
didn't make sense to log these as warnings/errors since they didn't indicate a ksql bug or error.

fix: dont use the streamthread to construct the log-metric-and-continue logger

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java

We've observed a behaviour where if there are two concurrent PushQueries running against a KSQL cluster, upon terminating the websocket in the browser, one of the queries lingers.
This is a right pain to test because everything useful gets mocked, so I'm more than happy to take pointers about testing this unit-test wise. I have tested that the behaviour is now correct locally by doing the following:
1. deploy ksqldb, c3 and confluent platform
2. set up a socat relay between the frontend and ksqldb 
3. modify frontend to point at the relay instead of ksqldb
4. open two queries in separate tabs
5. kill socat to simulate a network split
Prior to the change one of the queries would always stay when running `show queries` from another client. After the change it does not. Body of commit …

Ksql 5716/close transient queries when network splits

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PullProjectNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/PullProjectNodeTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json

The intermediate row in a projection currently only contains a key if the `PullFilterNode` requires it, which means that `select * ` only works on key lookups.  With this change, we make sure to add keys if it's a `select * ` so that it's now found for table scan.
RQTT tests and unit tests.

fix: Select star table scans need keys in the intermediate row

---

Jenkinsfile

This is part of the work to automate our testing. This makes it so that whenever we successfully build an RC image via the ksql-db-release jenkins job, it will automatically update and kick off a build for the Kafka Tutorials `ksql-db-release` branch (e.g. https://confluentinc.semaphoreci.com/branches/abe8dbf4-589f-41ac-bb5a-4665fbf40983) and the commit message will have the version that it is kicking off a build for.
We will still occasionally need to maintain the kafka tutorials branch, and after we release the image we should sync between master and the ksql-db-release branch. I recommend we do this using the following process:
- if master has diverged from `ksql-db-release`, we should reset `ksql-db-release` to `master` occasionally
- stabilize KT `ksql-db-release` branch
- after the …

build: jenkins build now triggers a kafka-tutorial build with latest version

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/AstSanitizer.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/ExpressionTreeRewriter.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/LambdaContext.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/AstSanitizerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/ExpressionTreeRewriterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/LambdaContextTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/LambdaUtil.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/TriFunction.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/ExpressionVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/LambdaFunctionCall.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/LambdaFunctionExpression.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/LambdaLiteral.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/TraversalExpressionVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/VisitParentExpressionVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/helpers/LambdaUtilTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatterTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/expression/tree/LambdaFunctionCallTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/expression/tree/LambdaFunctionExpressionTest.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java

Adds syntax for lambda functions to the KSQL grammar
LambdaFunctionExpression for representing a lambda function node
LambdaLiteral for representing a lambda variable
During the AstBuilder phase, the lambda variables are treated as UnqualifiedColumnReferences since I couldn't pass in a proper context, so I decided to convert them with the AstSanitizer.
Currently, lambdas won't work properly because the corresponding SqlToJavaVisitor methods haven't been implemented yet.
Unit test
Manual test

feat: add lambda syntax to grammar

---

docs/operate-and-deploy/logging.md
mkdocs.yml

I accidentally deleted the logging guide as part of #6915. This patch restores it to a dedicated page.

docs: restores logging page

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java

Backport of https://github.com/confluentinc/ksql/pull/6062 to prevent excessive logging while the server is running.

chore: dont log at error level when client closes connection (#6062)

---

ksqldb-tools/pom.xml
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/Migrations.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/BaseCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CleanMigrationsCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/MigrationInfoCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommand.java

Set up all the boilerplate for the new migrations tool (see #6721)
Ran the `help` commands for various use cases to make sure that it works as expected:
This is the default command that runs with no arguments
```
usage: ksql-migrations [ {-c | --config-file} <config-file> ]
[ {-n | --dry-run} ] <command> [ <args> ]
Commands are:
apply      Migrates a schema to new available schema versions
create     Create a pair of migration files with <desc> as description. This will created a pair of empty migration files based on the next schema version.
info       Displays information about the current and available migrations
new        Cleans all resources related to migrations. WARNING: this is not reversible!
validate   Validate applied migrations against local files.
See 'ksql-migrations help …
```

chore: setup the skeleton for a migrations tool

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedConsumer.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedConsumerTest.java

Stubs out the call `groupMetadata()` in the `Consumer` used in our sandbox.

fix: Adds groupMetadata as a faked method of SandboxedConsumer

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatter.java

When `TimeWindowedDeserializer` was updated to take a `Long` instead of a `long` java can no longer deduce generics because it can't accept an `int` constant in that slot 🤦 
IntelliJ doesn't show an error anymore

chore: fix the build after AK update

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/AstSanitizer.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/ExpressionTreeRewriter.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/AstSanitizerTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/ExpressionVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/LambdaVariable.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/TraversalExpressionVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/VisitParentExpressionVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatterTest.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java

Instead of creating LambdaVariables in AstSanitizer, we do it in AstBuilder.
We need to do this because we need to be able to construct the LambdaVariable node from only AstBuilder since that's how KSQL plan's are deserialized (we can't do sanitization on expressions in the plan)
This is done by keeping track of what the LambdaArgs are in AstBuilder. Before visiting the body of the lambda expression, we add the args to the LambdaArgs set while keeping track of what the initial state of the set was before visiting the body. After returning from the body, we set the LambdaArgs set back to the initial state.
Renamed LambdaLiteral -> LambdaVariable 

chore: update how AstBuilder and AstSanitizer handles lambda functions

---

ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_literal_args_-_JSON/6.0.0_1591214175189/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_literal_args_-_JSON/6.0.0_1591214175189/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_literal_args_-_JSON/6.0.0_1591214175330/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_literal_args_-_JSON/6.0.0_1591214175330/spec.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/elements.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/string-lpad-rpad.json
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/TableElements.java

This reverts commit 14465a270d8249d5ea47fc1e6319eddd5eee5a48.
The original change is backwards incompatible. Even though it fixes an issue for a query that never worked in first place, it prevents us from reading commands that were enqueued onto the command topic. 
Waiting for unit tests to run.

Revert "fix: throw error message on create source with no value colum…ns (#6680)"

---

docs/developer-guide/ksqldb-rest-api/query-endpoint.md

Two minor fixes to the /query endpoint docs:
- request field is named "ksql" not "sql"
- push queries require `EMIT CHANGES` syntax

docs: correct examples on /query endpoint docs (MINOR)

---

docs/reference/server-configuration.md
ksqldb-engine/src/main/java/io/confluent/ksql/KsqlExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/HARouting.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlanBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/SelectOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/PullPlannerOptions.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PullFilterNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/PullFilterNodeTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisherTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

Now that we have both codegen for the filter condition and table scan functionality, this PR removes some restrictions that were formerly in place including disallowing:
- Key range queries
- Multiple constraints on the key
- Non-Key equality, range queries (or any non-key reference!)
- Queries missing columns from multi-column keys
These restrictions are only lifted when the config `ksql.query.pull.table.scan.enabled` is set to true.  Otherwise, the former restrictions are still in place.
One exception to this is that now, if you specify both a key equality and non-key constraint, it's done with a key lookup and no table scan is required.
Many RQTT and unit tests.

feat: Allows pull queries with generic WHERE clauses

---

docs/developer-guide/ksqldb-clients/java-client.md
docs/developer-guide/ksqldb-rest-api/info-endpoint.md
docs/faq.md
docs/operate-and-deploy/installation/check-ksqldb-server-health.md
docs/operate-and-deploy/installation/install-ksqldb-with-docker.md
docs/operate-and-deploy/installation/installing.md
docs/operate-and-deploy/monitoring.md
docs/troubleshoot-ksqldb.md
docs/tutorials/etl.md
docs/tutorials/event-driven-microservice.md
docs/tutorials/materialized.md
mkdocs.yml

Replace redundant `release` sitevar with equivalent `ksqldbversion`.

docs: replace release sitevar with ksqldbversion (DOCS-3260)

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/utils/SerdeUtil.java
ksqldb-functional-tests/src/test/resources/historical_plans/timestamp_-_PROTOBUF_in_out/6.2.0_1612233798997/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/timestamp_-_PROTOBUF_in_out/6.2.0_1612233798997/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/timestamp_-_PROTOBUF_in_out/6.2.0_1612233798997/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/timestamp.json
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/KsqlProtobufDeserializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/KsqlProtobufSerializerTest.java

One of the reasons the decimal and timestamp types were not enabled in protobuf was because those two types have dependencies that need to be registered first in order for schema registry to be able to read schemas involving these types. This PR adds an extra step before registering protobuf schemas that resolves dependencies. 
manually, unit and QTT tests

feat: Support timestamp protobuf serde

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterialization.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedSessionTable.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedWindowTable.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/SessionStoreCacheBypass.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/WindowStoreCacheBypass.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedSessionTableTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedWindowTableTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/SessionStoreCacheBypassTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/WindowStoreCacheBypassTest.java

Adds ability to bypass cache for pull queries
Updated existing unit tests

feat: Adds ability to bypass cache for pull queries

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/FormatTimestamp.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/ParseTimestamp.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/FormatTimestampTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/ParseTimestampTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/stringtimestamp_-_format_timestamp/6.2.0_1612493120070/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/stringtimestamp_-_format_timestamp/6.2.0_1612493120070/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/stringtimestamp_-_format_timestamp/6.2.0_1612493120070/topology
ksqldb-functional-tests/src/test/resources/historical_plans/stringtimestamp_-_format_timestamp_with_time_zone/6.2.0_1612493120113/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/stringtimestamp_-_format_timestamp_with_time_zone/6.2.0_1612493120113/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/stringtimestamp_-_format_timestamp_with_time_zone/6.2.0_1612493120113/topology
ksqldb-functional-tests/src/test/resources/historical_plans/timestamp-to-string_-_timestamp_to_string_without_a_time_zone/6.2.0_1612493125106/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/timestamp-to-string_-_timestamp_to_string_without_a_time_zone/6.2.0_1612493125106/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/timestamp-to-string_-_timestamp_to_string_without_a_time_zone/6.2.0_1612493125106/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/stringtimestamp.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/timestamp-to-string.json

Fixes #6943 
Makes format_timestamp and parse_timestamp assume UTC by default. Previously, they used local time by default.
Updated QTT and unit tests

fix: make format_timestamp and parse_timestamp default to utc

---

ksqldb-tools/pom.xml
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/Migrations.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java
ksqldb-tools/src/main/resources/log4j.properties

new: creates a new directory and empty properties file
initialize: creates migration stream and table

feat: new and initialize commands for migration tool

---

docs/developer-guide/ksqldb-clients/java-client.md
mkdocs.yml

Fixes https://github.com/confluentinc/ksql/issues/7021.
The beta tag for the 0.15 release is `6.2.0-beta201122193350-cp5`, rather than `6.2.0-beta201122193350`. This PR fixes the docs accordingly.
This fix needs to be cherry-picked to 0.15.0-ksqldb as well.

docs: fix beta tag for 0.15

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/ServerInfo.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/AdminResponseHandlers.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ServerInfoImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ServerInfoImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java

Add getInfo method to java client, which queries the `/info` endpoint
unit test

feat(client): add getInfo method to java client

---

docs/concepts/index.md
docs/how-to-guides/index.md
docs/reference/index.md
docs/stylesheets/extra.css
docs/tutorials/index.md

From https://github.com/confluentinc/ksql/pull/7033.
* docs: make card titles clickable
* docs: rewrap ref links in spans

docs: cherry-pick: makes the docs card titles clickable (DOCS-7152)

---

docs/concepts/index.md
docs/how-to-guides/index.md
docs/reference/index.md
docs/stylesheets/extra.css
docs/tutorials/index.md

From https://github.com/confluentinc/ksql/pull/7033.
* docs: make card titles clickable
* docs: rewrap ref links in spans

docs: cherry-pick: makes the docs card titles clickable (DOCS-7153)

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/Migrations.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/BaseCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CleanMigrationsCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/MigrationInfoCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommand.java

BaseCommand should handle returning the appropriate exit code after printing the execution time, rather than exiting from within the commands themselves.
Minor refactor, more thorough testing (in general) coming in a later PR.

chore: refactor migrations commands to not call exit from within command

---

ksqldb-benchmark/src/main/java/io/confluent/ksql/benchmark/SerdeBenchmark.java
ksqldb-benchmark/src/main/java/io/confluent/ksql/benchmark/UdfInvokerBenchmark.java

This PR decreases the default configs for the serde JMH benchmarks so they take about an hour to run, rather than 6.5 hours. Comparing results from the new defaults to the old defaults, I don't see any systematic differences (larger times or variances, etc). (When I tried decreasing the iteration times further, I did start to see variances rise.)
New default configs:
```
Benchmark                                (params)  Mode  Cnt   Score   Error  Units
SerdeBenchmark.deserialize   single-key/Delimited  avgt    9   5.002 ± 0.045  us/op
SerdeBenchmark.deserialize       single-key/Kafka  avgt    9   0.090 ± 0.021  us/op
SerdeBenchmark.deserialize        single-key/JSON  avgt    9   0.476 ± 0.031  us/op
SerdeBenchmark.deserialize        single-key/Avro  avgt    9   1.305 ± 0.161  us/op …
```

chore: adjust default jmh settings for benchmarks (MINOR)

---

ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java

Test was relying on an incompatible schema due to the `Record` names differing. Need to rename this field from `Test` to `KsqlDataSourceSchema`
Issue surfaced after tightening up the compatibility check in https://github.com/confluentinc/schema-registry/pull/1775

fix: incompatible schema causing KsqlEngineTest.shouldNotFailIfAvroSchemaEvolvable failure

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/Migrations.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationsUtil.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommandTest.java

This PR is stacked on https://github.com/confluentinc/ksql/pull/7053. Only the commits starting from `chore(migrations): require server url as argument to command` need to be reviewed.
The `ksql-migrations new` command now requires two arguments, the migrations directory and the ksqlDB server URL, which is used to initialize the migrations config file (the server URL is a required config). This means `initialize` may now be called immediately after `new`. 
In a future PR we can consider initializing the config file with other configs (set to their default values) and helpful comments for how to use them.

chore(migrations): require server url as argument to `new` command

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-tools/pom.xml
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/BaseCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommand.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
pom.xml

This PR is stacked on https://github.com/confluentinc/ksql/pull/7053 and https://github.com/confluentinc/ksql/pull/7059. Only the commits starting from `test(migrations): integration test for migrations tool (wip)` need to be reviewed.
This PR sets up an integration test for the migrations tool, and tests both of the commands that have already been implemented (`new` and `initialize`). This PR also fixes a bug in the usage of the `--config-file` option, in order to properly load the specified config file in `initialize`. Also some other minor changes (cleaning up the module's pom, changing the default migrations table name from `schema_version` to `migration_schema_versions`, etc).
The newly added integration test verifies that `new` and `initialize` work as expected, including verifying …

test(migrations): add integration test for migrations tool

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopic.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicTest.java

Our restore logic differentiates on restore behaviour vs "live" behaviour
to avoid making some newly added referential integrity checks and therefore
ensure we execute anything that was already logged. While this isn't the
best way to guarantee compatibility, it's what we're doing now and we have
a problem: sometimes the restore poll times out and returns no records,
so we don't execute any "restore" phase. This patch fixes this by first
sampling the end offset of the log and ensuring that all rows between the
begin and end are returned.
Unit tests for command store. Restart of a running server.

fix: get all available restore commands even on poll timeout

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MetadataUtil.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsDirectoryUtil.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsUtil.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommandTest.java

The `validate` command of the migrations tool:
1. Finds the latest migrated version by querying the metadata table for the current version and following "previous" pointers until one with status MIGRATED is found. This should never involve more than one hop following pointers since the `apply` command should always use the latest MIGRATED version as "previous". Currently an error is thrown if this is not the case, but we can revisit when we introduce the `abort` command to get out of bad states due to race conditions.
2. Continuing to follow "previous" pointers, validating each file's checksum (and that each version has status MIGRATED) along the way.
3. The "previous" pointers eventually lead to the special `NONE_VERSION`, indicating the first migration version has been reached.
Once …

feat(migrations): implement `validate` command

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java
ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_should_support_nested_regex_functions_with_different_signatures/7.0.0_1614204177000/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_should_support_nested_regex_functions_with_different_signatures/7.0.0_1614204177000/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_should_support_nested_regex_functions_with_different_signatures/7.0.0_1614204177000/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/regex.json

The code generated for nested UDFs is done incorrectly currently. If I have the following expression
`REGEXP_EXTRACT('.*', REGEXP_EXTRACT('(.*) (.*)', input_string, 2))`, this fails to process records correctly because the wrong function identifier is in the generated code.
Currently in CodeGenRunner, we add the unique function name to the CodeGenSpec after we've processed all function call arguments (child nodes) of the parent node so a PostOrder traversal to add function names to spec
In SqlToJavaVisitor, we get the function name of the parent node before we process the child node (and get their function name from spec) which is a PreOrder traversal to get the function names from the spec
This results in the ordering of the function names to be wrong in the generated code.
We need to …

fix: get unique function names in correct order

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/serdes.json

https://github.com/confluentinc/schema-registry/pull/1775 exposed an issue in our test, we were "overwriting" schemas that we had registered under the output subject in our tests. Registering these are pointless, as up until now they haven't enforced any true compatibility and in future versions we have `PostTopicNode` to ensure that the generated schema is as intended 
see https://github.com/confluentinc/ksql/blob/d064342cc0224569fc400d02b113c6432ed63cb7/ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/PostConditionsNode.java#L169
Ran the test

chore: remove unnecessary output schema in serde QTT

---

ksqldb-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java

Using the new exception handler, we block after a thread failed until we try to restart the thread. This lead to a test timeout, as `KafkaStreams.close()` blocks because the `StreamsThread` blocks.
Setting the blocking time to zero resolves the issue.

test: fix failing SecureIntegrationTest

---

config/log4j-rolling.properties

update the default for the kafka log appender to the producer send buffer does not fill up on a bad configuration

fix: quick fix for appender

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/MaterializationProviderBuilderFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/PersistentQueryMetadataTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedPersistentQueryMetadataTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryFunctionalTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocator.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializationFactory.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocatorTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializationFactoryTest.java

The call to `kafkaStreams.allMetadataForStore(stateStoreName)` returns metadata for all subtopologies associated with the store, including ones which don't actually contain the store.  The calling code assumed that it was for just one subtopology, so this resulted in a bug where TopicPartitions from the wrong subtopology could overwrite the intended one.
Unit tests and manual testing with table scans in a multi node environment.

fix: Table Scan: Filters out StreamsMetadata for wrong subtopology

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java

Adds a test that reads an integer from a source connector and writes it out to a sink connector

test: add connect integration test for timestamps

---

Jenkinsfile
build-packages.sh

After the recent refactoring to the build script, the maven-settings.xml file is no longer getting checked into the git tag, which means the release branches are no longer buildable. This PR adds back the file.
Wasn't able to test this with jenkins replay since the fix requires changes to build-packages.sh which we can't edit in replay. @andrewegel do you know of a workaround for testing this?

build: add back maven settings file into release commit (MINOR)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/Migration.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MetadataUtil.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsDirectoryUtil.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommandTest.java

Migrations tool `apply` command. Follows the algorithm outlined [here](https://github.com/jzaralim/ksql/pull/new/metadata-util). Also includes helper functions for writing metadata, loading all migration files and extracting the name of the migration from the file name, and introduces a new class, `Migration`
unit and integration tests

feat(migrations): apply command

---

ksqldb-parser/src/main/java/io/confluent/ksql/util/GrammarTokenExporter.java

Jira: [https://confluentinc.atlassian.net/browse/KCI-170](KCI-170)
This is closely related to the [https://github.com/confluentinc/ksql/pull/7118](7118) PR. I needed to edit the script because of changes in the UI counterpart. The script now exports an array instead of a string.

fix: script used in kci-170 is now exporting an array instead of string

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsDirectoryUtil.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommandTest.java

The `migrations create` command creates an empty migrations file, of the appropriate filename format.
Unit + integration.

feat(migrations): implement `create` command

---

docs/developer-guide/ksqldb-reference/table-functions.md

From https://github.com/confluentinc/ksql/pull/7095.

docs: cherry-pick: add example for CUBE table function (DOCS-7308)

---

docs/developer-guide/ksqldb-reference/table-functions.md

From https://github.com/confluentinc/ksql/pull/7095.

docs: cherry-pick: add example for CUBE table function (DOCS-7309)

---

docs/developer-guide/ksqldb-reference/table-functions.md

From https://github.com/confluentinc/ksql/pull/7095.

docs: cherry-pick: add example for CUBE table function (DOCS-7310)

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsDirectoryUtil.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommandTest.java

Adds a new option to `migrations apply` for applying a specific migration version. Also addresses follow-ups in https://github.com/confluentinc/ksql/pull/7099 and https://github.com/confluentinc/ksql/pull/7133#discussion_r585921808, and fixes a few bugs along the way.

feat(migrations): add ability to apply specific migration version

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/PullQueryExecutionUtil.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlanBuilder.java
ksqldb-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializationFunctionalTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/KTableHolder.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/TableTableJoinBuilder.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StreamTableJoinBuilderTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/TableTableJoinBuilderTest.java

Introduces materialization support for tables using CTAS to make tables queryable. 
We can make tables queryable by using:
`CREATE TABLE QUERYABLE_TABLE AS SELECT...`
This would help fix #4614 by adding a more helpful error message as well.
- Unit tests
- Query translation tests

feat: Introduce materialization support for tables using CTAS to make tables queryable

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CleanMigrationsCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/ServerVersionUtil.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/CleanMigrationsCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommandTest.java

This PR implements the `migrations clean` command, which cleans up the migrations metadata stream and table (and underlying Kafka topics), if present.
Also fixes a bug around custom migrations stream names.
Unit + integration.

feat(migrations): implement `clean` command

---

bin/ksql-migrations
bin/ksql-run-class
config/log4j-console.properties
ksqldb-docker/pom.xml
ksqldb-tools/src/assembly/development.xml

Script to run migration tool from command line as `ksql-migrations ...`
To test on docker, follow the instructions here:
https://github.com/confluentinc/ksql/tree/master/ksqldb-docker
And run the command `docker exec <container> ksql-migrations ...`
To build the tar, run this command:
`make VERSION=0.14.0 PACKAGE_TYPE=archive -f debian/Makefile archive`
If you're building on a Macbook, you might have to change `iPatch` to `IPatch` in debian/Makefile

chore(migrations): add script to run migration tool

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/Migrations.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/BaseCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CleanMigrationsCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/MigrationInfoCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationVersionInfoFormatter.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/MigrationVersionInfoFormatterTest.java

Various fixes and improvements to the migrations tool:
- BaseCommand now implements Runnable, so `migrations help` works again
- various command description cleanup and improved log messages
- dry-run option moved from BaseCommand to ApplyMigrationCommand since that's the only command for which it makes sense
- don't print MigrationsConfig contents on each command since that's too spammy
- fix execution time to not always print zero due to integer division
- `migrations new` now fails if a config file already exists
- add extra divider on `migrations info` table output for improved readability
Played around with the tool manually.

chore(migrations): miscellaneous migrations tool cleanup

---

mkdocs.yml

Accidentally deleted this line while resolving a manual merge conflict in https://github.com/confluentinc/ksql/pull/7163.

docs: add redirect from ksqldb-rest-api.md to api.md (DOCS-7369)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/embedded/KsqlContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/AstSanitizer.java
ksqldb-engine/src/test/java/io/confluent/ksql/embedded/KsqlContextTestUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTestUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/AstSanitizerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/security/KsqlAuthorizationValidatorImplTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutorFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

Adds a lambda feature flag so we can disable lambdas if anything awful happens after we ship them.
A bit of refactoring to pass in ksql config information all the way to AST sanitizer, could be used in the future if we want access to feature flag info in these classes
unit test to make sure we throw the proper error

feat: add lambda feature flag

---

docs/faq.md
docs/operate-and-deploy/installation/installing.md

Adds java 8 and java 11 compatibility note for ksqlDB to the docs.

docs: adds java 8 and java 11 compatibility note for ksqlDB

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/generic/GenericExpressionResolver.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/generic/GenericRecordFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PullFilterNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/generic/GenericExpressionResolverTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/PullFilterNodeTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json

fixes #4484 
This allows many cases when table scans are enabled.  Prior to this, a comparison must have been of the form `KEY=12345` or possibly `KEY=1 + 2` where there was a column on one side and a resolvable expression on the other.  When table scans are enabled, now these can be done:
- Both sides are column references (e.g. `KEY = COL`)
- Neither side is a column reference (e.g. `5 > 3`, `KEY + 1 = COL + 1` )
- One side is a column reference and the other is an unresolveable expression (e.g. `KEY = COL + 10`)
Resolves #4484 
RQTT tests and unit tests

feat: Allows lots of table scans cases where keys cannot easily be extracted

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PullFilterNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/execution/ExpressionEvaluatorParityTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/InterpretedExpressionFactory.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/TermCompiler.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/TermEvaluationContext.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/terms/LambdaFunctionTerms.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/terms/LambdaVariableTerm.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/interpreter/InterpretedExpressionTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-complex-lambda.json

Adds lambda functionality to the interpreter used with pull queries.  Now you should be able to use expressions like `SELECT ID, REDUCE(ID, 0, (x,y) => x + y) as sum FROM TABLE;` or `SELECT ID, count, VAL_LIST FROM AGGREGATE WHERE REDUCE(VAL_LIST, 0, (x,y) => x + y) > 4` where lambdas exist in either the `SELECT` or `WHERE `clauses. 
Wrote a bunch of unit tests and RQTT tests.

feat: Adds Lambda functionality to the interpreter

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java

If a request fails, the logs should contain the full stack trace.
Closes #6725

chore: improve error logs

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java

When printing topics, the record formatter throws and Index Out of Bounds exception in case the key or value is an empty string because the deserializers might not have a format to use. This PR fix this checking if the possible formats are not empty.
Included empty values in the tests which already exist to validate this behavior.

fix: prevent IOB when printing topics with a key/value with an empty string

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlConfigurable.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/QueryCapacityUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/QueryCapacityUtilTest.java

This PR limits the number of active push queries using the `ksql.max.push.queries` config.
- Unit testing
- Manual Testing
-

feat: limit the number of active push queries everywhere using "ksql.max.push.queries" config

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/Migrations.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/BaseCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CleanMigrationsCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/DestroyMigrationsCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/MigrationInfoCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommand.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsParsingTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/DestroyMigrationsCommandTest.java

This PR includes various UX improvements to the `ksql-migrations` tool:
- `ksql-migrations --help` and `ksql-migrations -h` are now supported (in addition to `ksql-migrations help`). Similarly, `ksql-migrations <command name> --help` and `ksql-migrations <command name> -h` are now supported, in addition to `ksql-migrations help <command name>`. 
- The `--config-file` flag is now accepted after the command name, in addition to before.
- Exceptions thrown when commands fail to parse arguments no longer print stacktraces (in order to clean up the error messages that users see).
- Three commands have been renamed in order to disambiguate and clarify their behaviors: `ksql-migrations new` is now `ksql-migrations initialize`, `ksql-migrations initialize` is now `ksql-migrations …

chore(migrations): command option ordering + misc UX improvements

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/PullPlannerOptions.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PullFilterNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PullProjectNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/PullProjectNodeTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java

The call to `sessionConfig.getConfig(true);` copies fields of ksqlconfig in order to apply overrides.  This is very inefficient, slowing pull query performance locally on my Mac from 10k qps for key lookups to 6k, a 40% reduction.
I had made this change recently with #7006 so that the interpreter override would be available for pull queries.  It had this unfortunate effect.  The solution is to avoid the large copy and check overrides deliberately.  We already have a pattern for this in `PullQueryConfigPlannerOptions`.
Ran unit tests

fix: Pull Queries: Avoids inefficient KsqlConfig copy with overrides

---

docs/reference/server-configuration.md
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullQueryResult.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/ConcurrencyLimiter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/WSQueryEndpointTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisherTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/ConcurrencyLimiterTest.java

While we already have `ksql.query.pull.max.qps` to limit the volume of requests in a given time period, this introduces `ksql.query.pull.max.concurrent.requests` to limit the number of concurrent requests to minimize the effects of long running requests such as table scans.  Most queries such as key lookups are quick and could register high qps while having a relatively low number of concurrent requests.  Table scans on the other hand can handle relatively low qps while still taxing the system, so this aims to mitigate that by limiting concurrent requests, which are a truer measure of system load.
Also removes the limitation of only allowing the client to disallow table scans.  Now the client can do either, including enabling them, even if the server config has them disabled.
Unit tests

feat: Adds max concurrent pull queries to limit effects of table scans

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/ConvertTz.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/FormatTimestamp.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/FromUnixTime.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/UnixTimestamp.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/ConvertTzTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/FormatTimestampTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/FromUnixTimeTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/UnixTimestampTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/convert-tz.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/from-unixtime.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/timestamp-to-string.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/unix-timestamp.json

Fixes #7160
Updated unit and QTT tests

fix: check for null inputs for various timestamp functions

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/MetricsCallback.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/MetricsCallbackHolder.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/OldApiUtils.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

This changes pull query metrics to be reported only for pull queries, and not push, since both use the `/query` endpoint.
Ran tests and manually verified.

fix: Make pull query metrics apply only to pull and not also push

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsUtil.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/CommandParserTest.java

This PR contains various minor improvements/fixes to the migrations tool:
- the tool now throws if an unsupported statement type (`DEFINE`, `UNDEFINE`, `DESCRIBE`, `EXPLAIN`, `SELECT`, `PRINT`, `SHOW`, `LIST`, `RUN SCRIPT`) is encountered when applying a migration
- the tool now throws if a migration file contains un-parsed statements at the end (i.e., missing semicolon), rather than silently ignoring such statements
- fixes case-sensitivity of `INSERT VALUES` commands, so we can now insert into case-sensitive streams and streams with case-sensitive field names
- adds a bunch of unit tests, both for negative cases (unsupported statement types) and positive cases (everything we explicitly want to support)
- fixes the case where an invalid `INSERT VALUES` command is thrown, by wrapping the …

chore(migrations): fail early on unsupported sql statements

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java

* Adds all supported commands to the integration test except for `TERMINATE`
* Adds auth to the integration test
* Also fixes a bug in `MigrationsConfig` that mixes up the ssl alias and password
.

test(migrations): add auth and more commands to integration test

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksqldb-common/src/main/java/io/confluent/ksql/properties/DenyListPropertyValidator.java
ksqldb-common/src/test/java/io/confluent/ksql/properties/DenyListPropertyValidatorTest.java

Issue: [#6869](https://github.com/confluentinc/ksql/issues/6869)
ksql.service.id was settable as a query-level parameter but it should only be settable as a server-level parameter.
The query-parameters that aren't allowed to be set are defined in the denylist that is imported from the ksql-server.properties. I hardcoded the 'ksql.servier.id' in the denylist as I wasn't sure if I should edit the config files. Hence, alternative to my approach we could edit the config files from where the denylist is imported.
Just made sure that all tests run as there were already tests checking whether the properties set in the denylist actually are actually denied from query-level parameter setting.

fix: ksql.service.id should not be usable as a query parameter

---

ksqldb-common/src/main/java/io/confluent/ksql/properties/DenyListPropertyValidator.java

`confluent-snapshot/master` is failing with a checkstyle violation
```
[2021-03-11T12:05:42.510Z] [ERROR] /home/jenkins/workspace/ntinc_confluent-snapshots_master/prod/ksql/ksqldb-common/src/main/java/io/confluent/ksql/properties/DenyListPropertyValidator.java:37: Line is longer than 100 characters (found 113). [LineLength]
```
This PR fixes it.

chore: fix checkstyle violation on DenyListPropertyValidator

---

ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java
ksqldb-parser/src/main/java/io/confluent/ksql/schema/ksql/SqlTypeParser.java
ksqldb-parser/src/test/java/io/confluent/ksql/schema/ksql/SqlTypeParserTest.java

fixes #7077
Improves the error message when encountering a bad type in parsing UDFs. This was particularly salient when the parser was parsing a sub-type with an empty token (e.g. `STRUCT<foo VARCHAR,>`) because the error message would be empty.
Unit testing, e2e testing

chore: improve error message for custom type parsing

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/PollableSubscriber.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/PollableSubscriberTest.java
ksqldb-common/src/main/java/io/confluent/ksql/reactive/BaseSubscriber.java

Fixes a small bug where `BaseSubscriber.makeRequest` can be called from outside the Vertx context, which should be disallowed.
`makeRequest` is called from `checkRequestTokens` and there are currently a few paths into `checkRequestTokens`:
- One is `afterSubscribe` which is called from the context
- The other is `poll` which is inherently blocking and shouldn't be called from the context.
For this reason, this PR exposes `runOnRightContext` and invokes `makeRequest` using that.
Fixes #7115 
Ran tests and manually exercised this path by fetching more than the batch size.

fix: Ensures BaseSubscriber.makeRequest is called on context in PollableSubscriber

---

config/log4j-rolling.properties
config/log4j.properties

The consumer and producer logs in particular are often critical for telling the whole story. They should be logged at the same level as Streams itself by default.

chore: bump clients and connect logging level to INFO

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md

The correct the "since" version for the STDDEV_SAMP function is `0.16.0`.
Related: https://github.com/confluentinc/ksql/pull/6845.

docs: fix since version for STDDEV_SAMP function (DOCS-7522)

---

Jenkinsfile

Fixes a long-standing issue where we need to manually copy the ECR cp-base-new into artifactory. This patch does that automatically as part of the release.
Hacked it together in a replay here: https://jenkins.confluent.io/job/confluentinc/job/ksql/job/ksql-db-release/921/console

build: copy cp-base-new to artifactory as part of build

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java
ksqldb-common/src/main/java/io/confluent/ksql/metrics/TopicSensors.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionFactory.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionTest.java

Jira: [KCI-284](https://confluentinc.atlassian.net/browse/KCI-284)
We are currently working towards displaying error metrics in the UI. These were returned as formatted string forcing us to parse it back if we want to use the numbers. The reason for that was so that they could be easily printed in the CLI. 
To simplify rendering in the UI, the additional fields "statisticsMap" and "errorStatsMap"  that return the JSON objects were added as can be seen in the following HTTP request:
The old fields "statistics" and "errorStats" still exist to make sure that the update doesn't break older clients:
Adjusted the unit tests and made sure that all run.

feat: update sourcedescription and errorstats to have statistics as structured objects

---

docs/operate-and-deploy/installation/server-config/index.md

We should document that all servers should be started up with the same queries file in headless mode, since this question comes up a lot.

docs: clarify headless mode should use same queries file

---

docs/operate-and-deploy/installation/server-config/index.md

From https://github.com/confluentinc/ksql/pull/7256.

docs: cherry-pick: clarify headless mode should use same queries file (DOCS-7549)

---

docs/operate-and-deploy/installation/server-config/index.md

From https://github.com/confluentinc/ksql/pull/7256.

docs: cherry-pick: clarify headless mode should use same queries file (DOCS-7550)

---

docs/operate-and-deploy/installation/server-config/index.md

From https://github.com/confluentinc/ksql/pull/7256.

docs: clarify headless mode should use same queries file (#7256)

---

ksqldb-rocksdb-config-setter/pom.xml

The master build is currently failing because the ksqldb-rocksdb-config-setter module can't find dependencies from `org.rocksdb`. This dependency was previously being pulled in transitively from the module's kafka-streams dependency but this no longer appears to be the case. (The transitive dependency is now pulled in with scope `runtime` which I believe explains the compilation error.) This PR fixes the build by adding the dependency explicitly. 
~~Weirdly, I can't find any recent changes to explain the change in behavior; if anyone else has more ideas for where to look that'd be great. The build started failing between 10:18am and 11:51am PST today.~~
Update: mystery has been solved (thanks, Sophie!). Here's the culprit (a change in Streams's transitive dependency handling): …

chore: add rocksdbjni as explicit dependency to config setter module

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/DescribeStreams.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/DescribeTables.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/ListQueries.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/ListStreams.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/ListTables.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/StatementWithExtendedClause.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RemoteDataAugmenter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/RemoteDataAugmenterTest.java
ksqldb-rocksdb-config-setter/pom.xml
ksqldb-test-util/pom.xml
pom.xml

This PR factors out the generic mechanism used to merge query results across multiple nodes without using the MetaStore (e.g. `list queries` or `describe streams`). This will let us collate stream/topic statistics across multiple nodes regardless of the node service the request in the consequent PR. This PR serves to prove that this mechanism works for `ListQueriesExecutor`
Unit tests pass

refactor(executor): factor out a class allowing you to merge local results with results for running the same statement on other nodes

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/DdlDmlRequestValidators.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java

The `executeStatement` Java client method fails if the given statement contains a string with semicolons. This PR updates the validator logic to ignore semicolons in strings when counting semicolons.

fix(java client): allow java client to accept statements with more than one semicolon

---

ksqldb-rocksdb-config-setter/pom.xml

This PR reverts https://github.com/confluentinc/ksql/pull/7262, since we no longer need the explicit dependency anymore in light of https://github.com/apache/kafka/pull/10341.
Will wait for Jenkins build to pass.

chore: remove explicit rocksdbjni dependency as it's no longer needed (MINOR)

---

docs/reference/metrics.md
ksqldb-engine/src/main/java/io/confluent/ksql/internal/PullQueryExecutorMetrics.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryMetricsTest.java

Updating the metrics bean name for ksql engine and ksql rest app metrics in the docs (no code change)
Also the new metric convention for pull queries didn't have the ksql prefix
Before change:
io.confluent.ksql.metrics:type=_confluent-pull-query,ksql_service_id=default_
After change:
io.confluent.ksql.metrics:type=_confluent-ksql-pull-query,ksql_service_id=default_

chore: update pull query metrics naming

---

ksqldb-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java
ksqldb-common/src/main/java/io/confluent/ksql/metrics/TopicSensors.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlHostInfo.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/ShowColumns.java
ksqldb-rest-app/pom.xml
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionFactory.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ClusterQueryStats.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RemoteHostExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RemoteSourceDescription.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RemoteSourceDescriptionExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/SystemAuthenticationFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestAppTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ClusterQueryStatsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/RemoteHostExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/RemoteSourceDescriptionExecutorTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java

This PR exposes new fields on SourceDescription - `clusterStatistics` and `clusterErrorStats`
These are mappings from the host running a partition of a query to its aggregated jmx metrics obtained from `MetricsCollectors`.
This is the backend side of this ticket: [KCI-206](https://confluentinc.atlassian.net/browse/KCI-206)

feat(executor): Allow SourceDescription returning executors to return cluster wide stream stats

---

ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StreamStreamJoinBuilderTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StreamTableJoinBuilderTest.java

The mock call are currently ambiguous and make a compilation error.  This makes the tests compile and pass.
Ran tests.

fix: Fixes ambiguous test mocks after streams change

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintTopicDescribeExtended.approved.json
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintTopicDescribeExtended.approved.tabular
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintWarnings.approved.json
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintWarnings.approved.tabular
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.testPrintConnectorDescription.approved.json
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.testPrintSourceDescriptionWithClusterStats.approved.json
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.testPrintSourceDescriptionWithClusterStats.approved.tabular

This teaches the CLI to print statistics broken down by host if available. It also teaches the CLI to always display stats as a table.
Used approval tests (which is why this needs to go in after #7293 )
For local stats only it looks like this:
```
Local runtime statistics
-------------------------
Host | Metric | Value      | Last Message             
-------------------------------------------------------
--   | ERROR  |          0 | 2020-08-05T16:28:56.314Z 
--   | TEST   |          0 | 2020-08-05T16:28:56.314Z 
-------------------------------------------------------
```
When data from other nodes is present it looks like so:
```
Runtime statistics by host
-------------------------
Host       | Metric | Value      | Last Message …
```

feat(cli): print stats/errors breakdown by host

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListPropertiesExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListPropertiesExecutorTest.java

When ksqlDB runs with embedded Connect via the `ksql.connect.worker.config` config, if a user lists server properties with `list properties;`, the entire contents of the connect worker config file is displayed in the output, including any potentially sensitive configs. This is in contrast to sensitive ksqlDB or Streams configs which are properly sanitized (displayed as `[hidden]`) in the properties listing output, including any/all UDF-specific configs. This PR fixes the issue for the connect worker configs by only displaying known connect worker properties (as specified by `DistributedConfig`) as we know these are safe to display.
Unit test added.

fix: only list known connect worker properties when listing server props

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListPropertiesExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListPropertiesExecutorTest.java

Backport https://github.com/confluentinc/ksql/pull/7304 to an older branch.
Unit test backported.

fix: only list known connect worker properties when listing server props (5.5.x)

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/HARouting.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/StandbyFallbackException.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/HARoutingTest.java

`HARouting` has previously treated all Exceptions the same and used them as reason to retry with standbys.  The issue is that certain errors are deterministic and often caused by some form of user error or code bug.  Not only is there no use in retrying something that will have the same effect on a standby, but if we treat it similar to a transient error and print the error message `Unable to execute pull query: "%s". Exhausted standby hosts to try.`, it's rather confusing since trying again won't fix the issue.
The goal of this PR is to surface any bug by requiring any standby retries to explicitly use `StandbyFallbackException` and by bubbling up other exceptions by default.  In particular, any network error gets wrapped in a `StandbyFallbackException` and everything else, including …

fix: Bubble up errors from HARouting unless using StandbyFallbackException

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientUtilTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/SessionProperties.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlRequest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryStreamArgs.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/KsqlRequestTest.java

Adds an extra parameter, `sessionVariables` to the /query-stream and /ksql endpoints so that users can pass in a map of variable substitutions and use them in statements. For `/ksql`, `sessionVariables` is a map of initial variable values that can be modified with `define` and `undefine` statements.
This is a prerequisite for enabling variable substitutions in the java client.
integration and unit tests

feat: enable variable substitution for /query-stream and /ksql endpoints

---

CHANGELOG.md
docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/7227.

docs: cherry-pick: add changelog for 0.16 (DOCS-7303)

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplier.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplierTest.java

Adds line breaks to the error message when a schema is not found
as described in issue #7205.
Adapted existing unit tests.

fix: Add line breaks to error message

---

ksqldb-api/pom.xml

This will fix the following three CVEs brought by io.netty:netty-codec-http2.
https://confluentinc.atlassian.net/browse/SEC-1883
https://confluentinc.atlassian.net/browse/SEC-2016
https://confluentinc.atlassian.net/browse/SEC-2022
Rely on existing tests.

fix: upgrade io.netty:netty-codec-http2 to 4.1.62.Final.

---

ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java

Fixes #7312 and other similar situations by appending additional fields to row values in `KsqlMaterialization.java`
- RQTT
- Unit Testing

fix: append additional fields to row values in `KsqlMaterialization.java` to fix pull query filtering

---

docs/developer-guide/api.md
docs/developer-guide/ksqldb-rest-api/cluster-status-endpoint.md
docs/reference/server-configuration.md
mkdocs.yml

The `/clusterStatus` endpoint is currently undocumented even though it's useful to users and mentioned in [this blog](https://www.confluent.io/blog/ksqldb-pull-queries-high-availability/). This PR adds docs for the endpoint, which has been around since January 2020.

docs: add docs for /clusterStatus endpoint

---

docs/operate-and-deploy/installation/cli-config.md

Our docs on ksqlDB CLI usage are currently lacking. AFAICT, there is no mention of the `--username`, `--password`, `--file`, `--execute`, or `--define` options, all of which are very useful. This PR adds the relevant docs, and fixes a few broken links.

docs: add content on ksqlDB CLI usage

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java

`show queries extended` now combines the task metadata information from remote hosts in the response.
If we ran a query where the source topic has two partitions and then got a QueryDescription of it, the description would only have 1 task metadata before this patch. Now it has both.
Updated integration test
Sample response with two ksqlDB servers running
```
[
{
"@type": "query_descriptions",
"statementText": "show queries extended;",
"queryDescriptions": [
{
"id": "CSAS_TEST_3",
"statementText": "CREATE STREAM TEST WITH (KAFKA_TOPIC='TEST', PARTITIONS=2, REPLICAS=1) AS SELECT *\nFROM PAGEVIEWS PAGEVIEWS\nEMIT CHANGES;",
...
"ksqlHostQueryStatus": {
"192.168.86.31:8089": "RUNNING",
"192.168.86.31:8088": "RUNNING"
},
"queryType": "PERSISTENT",
"queryErrors": [],
"tasksMetadata": [
{ …
```

feat: scatter gather task metadata for query descriptions

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java

Add a retry around a known flaky test to help stabilize master build. I know this isn't the best thing to do, but I think we have a pretty good understanding about why this test is flaky (cc @AlanConfluent I believe you investigated this, can you comment here so that we have history recorded?)
I see the following in the logs:
```
[2021-04-05 16:31:00,102] WARN Retrying test after 3 SECONDS due to: 
Expected: is "{\"row\":{\"columns\":[1,\"USER_1\"]}}]"
but: was "{\"errorMessage\":{\"@type\":\"generic_error\",\"error_code\":50000,\"message\":\"Unable to execute pull query \\"SELECT COUNT, USERID from AGG_TABLE WHERE USERID='USER_1';\\". Error executing query locally at node http://localhost:64740/: Failed to get value from materialized table\"}}]" (io.confluent.ksql.integration.Retry:135) …
```

test: retries for known flaky RestApiTest

---

.gitignore
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedAdminClientTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedConsumerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedProducerTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/TestMethods.java

close(long, TimeUnit) has finally been removed,
so we can drop our tests that verified it was a no-op
in our testing subclasses.

chore: remove deprecated members

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

Statements like `CREATE STREAM ${variable} ...` were failing when sent to the `/ksql` endpoint even if the request included the needed session variables because  the request validator was parsing the stream without first replacing the variables.
Updated an integration test to catch this scenario, added a unit test

fix: add sessionVariables to /ksql endpoint validator

---

Jenkinsfile

Per internal discusison, stop the ksql-db-release job from building nightly since we're experiencing frequent test failures. This should be re-enabled (likely with new configs) via https://confluentinc.atlassian.net/browse/KQE-196 when this branch has been moved to its own repo

chore: disable daily jenkins job for now

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/KsqlUncaughtExceptionHandler.java

https://github.com/confluentinc/ksql/pull/7405
but without the integration test for now
Tested manually

fix: ignore streams threads in KSQL uncaught exception handler

---

build-packages.sh

This reverts commit 76ccd1850d5da51d707eeec167ba06c43dbfec15.
I changed the jenkins file to stop using the `x.xx.x-1` naming strategy for real release jobs, in the process this broke the job for release _candidates_, reverting my fix to unblock the release and then will do a follow-up fix that should work for both
revert PR: https://github.com/confluentinc/ksql/pull/7406/files

chore: revert fix maven + docker version naming (#7406)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/SessionUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/SessionUtilTest.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/KsqlRequestTest.java

Reasons for closing websocket are limited to 123 bytes.
We can, however, emit a final message before closing the
socket - we're using that here to send a non-truncated
version of the error to display in the UI
- [] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).

feat: emit an error reason before closing websocket

---

docs/operate-and-deploy/migrations-tool.md
ksqldb-parser/src/main/java/io/confluent/ksql/parser/VariableSubstitutor.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/VariableSubstitutorTest.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/CommandParserTest.java

^^^
Previously, the tool parsed each command, collected them and then executed them. Because the variables are tracked in the java client, but SET/UNSET/INSERT VALUES don't do variable substitution through the client, the flow was refactored to parse commands and then execute them one by one.
unit + integration

feat(migrations): support DEFINE and UNDEFINE statements

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/HARouting.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/PullPlannerOptions.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/HARoutingTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/RoutingOptions.java
pom.xml

We recently noticed that a ksqlDB user was receiving erroneous responses to pull query requests. However, nothing relating to these errors was visible in the logs. We should ensure that we log any error a user receives in response to a command they've issued (whether from the UI or CLI) so that we can proactively investigate any unusual error activity.
Without this change, the following exception was returned but never present in the logs. I also made sure that errors that contain the error message get logged properly:
```
[2021-04-16 09:01:47,141] ERROR Failure to execute pull query, not logging the error message since it contains the query string, which may contain sensitive information. If you see this LOG message, please submit a GitHub ticket and we will scrub the statement text from …
```

chore: log any errors that happen for pull queries

---

build-packages.sh

Same as https://github.com/confluentinc/ksql/pull/7406 but more targeted. This PR fixes the bug with the maven and docker artifact versions, and leaves the deb, rpm, and archive versions as is. @andrewegel is it correct for the archive version to be the save as the deb and rpm versions, or should it match the maven and docker versions instead?

build: use proper artifact version during release builds

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafFactoryInvoker.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/array/CollectListUdaf.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/array/CollectSetUdaf.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/array/CollectListUdafTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/array/CollectSetUdafTest.java

The properties file by default sets the properties as strings, not integers, so the old mechanism of casting to a number doesn't work.
Unit test + local testing
```
ksql> create stream foo (id int) with (kafka_topic='a', format='json', partitions=1);
Message
Stream created
ksql> insert into foo (id) values (1);
ksql> insert into foo (id) values (1);
ksql> insert into foo (id) values (1);
ksql> insert into foo (id) values (1);
ksql> insert into foo (id) values (1);
ksql> insert into foo (id) values (1);
ksql> select collect_list(id) from foo group by id emit changes;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|KSQL_COL_0 …
```

chore: allow collect_* to be configured with string values

---

build-packages.sh

we've got an image mix up, maven is 0.XX.0 and RPM is picking up 0.XX.0-1. Error from Jenkins here:
`[2021-04-22T22:12:06.765Z] Building RPM packages [2021-04-22T22:12:06.765Z] mkdir -p RPM_BUILDING/BUILD [2021-04-22T22:12:06.765Z] mkdir -p RPM_BUILDING/RPMS [2021-04-22T22:12:06.765Z] mkdir -p RPM_BUILDING/SOURCES [2021-04-22T22:12:06.765Z] mkdir -p RPM_BUILDING/SPECS [2021-04-22T22:12:06.765Z] mkdir -p RPM_BUILDING/SRPMS [2021-04-22T22:12:06.765Z] # Safety precatuion to avoid removing of root dir when DESTDIR or PREFIX is not set, for wathever reason [2021-04-22T22:12:06.765Z] if [[ "/home/jenkins/workspace/onfluentinc_ksql_ksql-db-release/ksql-db/BUILD//usr" =~ ^/usr* ]] || [[ "/home/jenkins/workspace/onfluentinc_ksql_ksql-db-release/ksql-db/BUILD//usr" == / ]] || [[ …

chore: fix rpm packaging to pick up correct maven version

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/RestClientIntegrationTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/OldApiUtils.java
pom.xml

Currently, due to https://github.com/confluentinc/ksql/issues/7358, long-running queries block the main server event loop, even though they execute on the worker pool instead of the event loop pool.
This patch corrects this flaw.
Added integration tests to reproduce the bug (https://github.com/confluentinc/ksql/issues/7358).
Note that the newer HTTP2 API did not have the bug, but the integration test for the older API does hang and time out without the fix in place.

fix: long-running queries shouldn't block the main event loop

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java

As the title says. CP 5.5 was when execution plans were first introduced, not CP 5.0. This PR fixes the typo to avoid confusion. 

chore: fix error message for unsupport legacy statements version (MINOR)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-parser/src/main/java/io/confluent/ksql/util/QueryGuid.java
ksqldb-parser/src/test/java/io/confluent/ksql/util/QueryGuidTest.java

We want to be able to filter the anonymized queries according to things such as physical cluster, organization and time created. For this we need to get/generate the relevant meta-data. The organization and physical cluster id is picked up from the control plane via a metric set [here](https://github.com/confluentinc/cc-spec-ksql/pull/233).
Unit tests to make sure metadata gets computed as expected.
jira: [KCI-342](https://confluentinc.atlassian.net/browse/KCI-342)
cc-structs-ksql update: [PR-223](https://github.com/confluentinc/cc-spec-ksql/pull/233)
cc-scheduler-service update: [PR-2240](https://github.com/confluentinc/cc-scheduler-service/pull/2240)
protobuff update: [PR-1507](https://github.com/confluentinc/cc-structs/pull/1507)
old pr that was closed accidentally: …

feat: made class to compute essential meta-data

---

ksqldb-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java

test: Replace deprecated EOS configs with EXACTLY_ONCE_V2

---

ksqldb-version-metrics-client/pom.xml
ksqldb-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/VersionCheckerIntegrationTest.java

Fixes test and the build.
Ran test

fix: Fixes org.mock-server to be 5.11.2 to utilize newer netty

---

docs/developer-guide/ksqldb-clients/java-client.md

Based on user feedback, this small change to the example application config reduces the chance the `id` corresponding to the Confluent Packaging Maven repo conflicts with other Maven configurations that also use the current value, `confluent`.

docs: Update Maven repo name in Java Client config

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/AdminResponseHandlers.java
ksqldb-rest-app/pom.xml
ksqldb-version-metrics-client/pom.xml
ksqldb-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/VersionCheckerIntegrationTest.java
pom.xml

This is effectively a rollback to our previous version of netty since the update to 4.1.63.Final in common is breaking master.  Also pins jersey-common and fixes a small bug breaking master

chore: Override dependencies: netty -> 4.1.49.Final, jersey-common -> 2.31

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedTransientQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/PersistentQueryMetadataTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedPersistentQueryMetadataImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedTransientQueryMetadataTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java

In order to make bin packed Queries easier to implement I refactored the current version.
Now I can just implement the PersistantQueryMetadata interface and drop it in place. This will make the feature flag logic and change over much easier.

chore: refactor QueryMetadata and PersistentQueryMetadata

---

docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/nulls/NullIf.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/nulls/NullIfTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_null_if/6.2.0_1606813248690/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_null_if/6.2.0_1606813248690/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_null_if/6.2.0_1606813248690/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/null.json

[#6567](https://github.com/confluentinc/ksql/issues/6567)
The `NULLIF` function returns NULL if and only if **value1** and **value2** are equal. Otherwise it returns **value1**.
- **Engine**. Unit test covering `NULLIF` function.
- **Functional-tests**. Added test case in `null.json` and generated historial plan.

feat: added NULLIF function (#6567)

---

ksqldb-version-metrics-client/pom.xml
ksqldb-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/VersionCheckerIntegrationTest.java
pom.xml

Updates to Vert.x 3.9.7 and Netty 4.1.60.Final.
This is to mitigate https://github.com/advisories/GHSA-wm47-8v5p-wjpj
Running CI tests.

chore: Updates to Vert.x 3.9.7 and Netty 4.1.60.Final

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md

I think "none primary key" joins was a typo. Rephrasing it as "non-primary key" joins is a bit ambiguous, and "non-key" joins is quite clear.
N/A
- [ x ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ x ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

docs: Fix typo in documentation

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PlanNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/SelectionUtil.java
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select___-_some_key_some_value/6.2.0_1620261642747/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select___-_some_key_some_value/6.2.0_1620261642747/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select___-_some_key_some_value/6.2.0_1620261642747/topology
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select___-_some_key_some_value_-_key_first/6.2.0_1620261642829/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select___-_some_key_some_value_-_key_first/6.2.0_1620261642829/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select___-_some_key_some_value_-_key_first/6.2.0_1620261642829/topology
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select_explicit_-_reorder_/6.2.0_1620257307634/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select_explicit_-_reorder_/6.2.0_1620257307634/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select_explicit_-_reorder_/6.2.0_1620257307634/topology
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select_explicit_-_reorder_partition_by_but_keep_same_order_in_project/6.2.0_1620257307655/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select_explicit_-_reorder_partition_by_but_keep_same_order_in_project/6.2.0_1620257307655/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select_explicit_-_reorder_partition_by_but_keep_same_order_in_project/6.2.0_1620257307655/topology
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select_star_-_reorder_columns/6.2.0_1620257307582/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select_star_-_reorder_columns/6.2.0_1620257307582/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_select_star_-_reorder_columns/6.2.0_1620257307582/topology
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_some_key_some_value_-_key_first/6.2.0_1620261429513/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_some_key_some_value_-_key_first/6.2.0_1620261429513/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_some_key_some_value_-_key_first/6.2.0_1620261429513/topology
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_some_key_some_value_-_properly_ordered_in_selection/6.2.0_1620261797927/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_some_key_some_value_-_properly_ordered_in_selection/6.2.0_1620261797927/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_multiple_columns_-_some_key_some_value_-_properly_ordered_in_selection/6.2.0_1620261797927/topology
ksqldb-functional-tests/src/test/resources/historical_plans/select_-_multi-key_columns_reordered/6.2.0_1620257309645/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/select_-_multi-key_columns_reordered/6.2.0_1620257309645/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/select_-_multi-key_columns_reordered/6.2.0_1620257309645/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/select.json

There are a few situations where key columns are re-arranged (differ from the source/partition by). You can reproduce like this:
```sql
CREATE STREAM inputStream (id INT KEY, a INT, b INT, c INT) WITH (kafka_topic='input', partitions='4');
INSERT INTO input VALUES (1, 11, 21, 31);
INSERT INTO input VALUES (2, 12, 22, 32);
INSERT INTO input VALUES (1, 11, 21, 31);
CRATE STRAM repartitionedStream AS SELECT * FROM inputStream PARTITION BY c+5, b;
SELECT * FROM repartitionedStream EMIT CHANGES;
+-----------------+-----------------+-----------------+-----------------+-----------------+
|B                |KSQL_COL_0       |A                |C                |ID               |
+-----------------+-----------------+-----------------+-----------------+-----------------+
|36               |21 …
```

fix: multi-column keys are broken in some scenarios when rearranged

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestUtils.java

This PR refactors the logic in the logical planner for building join source nodes to first build a raw source node (either a JoinNode or a DataSourceNode) and then to add potential PreJoinRepartition or PreJoinProject nodes only after the join has been validated, since part of the validation is detecting whether the join is a foreign key join or not, and we do not want to add pre-join repartition nodes in the case of foreign key joins. This PR also adds a feature flag for foreign key joins while the feature is still under development.
This PR is mostly a refactor; I'll ensure that existing unit and QTT tests pass prior to merging. Test coverage for the new functionality (involving foreign key joins themselves) will be added once more of the relevant functionality is wired in.

chore: bypass pre-join repartition for foreign key joins
