docs/developer-guide/joins/partition-data.md, docs/developer-guide/ksqldb-reference/insert-values.md, docs/developer-guide/syntax-reference.md, docs/operate-and-deploy/installation/server-config/avro-schema.md, docs/operate-and-deploy/installation/upgrading.md, docs/tutorials/basics-docker.md, docs/tutorials/examples.md
From https://github.com/confluentinc/ksql/pull/5417.
=> docs: cherry-pick various copy edits (DOCS-4477)

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/HeartbeatAgent.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java, ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocator.java
Added extra logging for pull queries and HA that were helpful for debugging during experiments
=> feat: add extra log messages for pull queries

docs/developer-guide/ksqldb-reference/scalar-functions.md, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/RegexpExtractAll.java, ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/RegexpExtractAllTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_regex_extract_all_with_group/6.0.0_1590773084381/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_regex_extract_all_with_group/6.0.0_1590773084381/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_regex_extract_all_with_group/6.0.0_1590773084381/topology, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_regex_extract_all_without_group/6.0.0_1590773084300/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_regex_extract_all_without_group/6.0.0_1590773084300/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/regex_-_regex_extract_all_without_group/6.0.0_1590773084300/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/regex.json
Adds UDF regexp_extract_all that extracts the all subtrings matched by a regex pattern
Wrote unit tests
=> feat: Adds UDF regexp_extract_all

docs/developer-guide/joins/synthetic-keys.md, ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json
fixes: https://github.com/confluentinc/ksql/issues/5466
Add docs around what synthetic key columns are, when they occur and what they're called.
doc only change.
=> docs: add docs for synthetic keys

docs/developer-guide/ksqldb-reference/scalar-functions.md, ksqldb-engine/src/main/java/io/confluent/ksql/function/InternalFunctionRegistry.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Concat.java, ksqldb-engine/src/test/java/io/confluent/ksql/function/InternalFunctionRegistryTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/ConcatTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_fields_using_CONCAT/6.0.0_1591052563853/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_fields_using_CONCAT/6.0.0_1591052563853/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_fields_using_CONCAT/6.0.0_1591052563853/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/concat.json, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeFunctionExecutorTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListFunctionsExecutorTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
As per title. Tests and docs updated too.
Fixes #5078 
Unit tests, QTT, and manual testing all ok.
=> fix: update Concat UDF to new framework and make variadic

ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java, ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/KsqlConnectSerializer.java
fixes #5521 
Error message before was not very helpful, this patch serves to make it more clear to the user that the decimal scale was not being matched appropriately for example.
Reviewed manually by running some insert statements on ksql to see that error message was more appropriate now
=> fix: deals with issue #5521 by adding more descriptive error message

ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java, ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java, ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java, ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json
fixes: https://github.com/confluentinc/ksql/issues/5549
Missing test coverage allowed this bug to be introduced during recent changes. However, it's not been released.
This change fixes the issue and adds suitable tests.  It's a minimal fix, as the code will be cherry picked for 0.9.5
usual
=> chore: aggregating push query should not remove key from projection

ksqldb-functional-tests/src/test/resources/historical_plans/hopping-windows_-_out_of_order_-_explicit_grace_period/6.0.0_1591102264811/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/hopping-windows_-_out_of_order_-_explicit_grace_period/6.0.0_1591102264811/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/hopping-windows_-_out_of_order_-_explicit_grace_period/6.0.0_1591102264811/topology, ksqldb-functional-tests/src/test/resources/historical_plans/hopping-windows_-_out_of_order_-_no_grace_period/6.0.0_1591102264657/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/hopping-windows_-_out_of_order_-_no_grace_period/6.0.0_1591102264657/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/hopping-windows_-_out_of_order_-_no_grace_period/6.0.0_1591102264657/topology, ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_out_of_order_-_explicit_grace_period/6.0.0_1591102310430/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_out_of_order_-_explicit_grace_period/6.0.0_1591102310430/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_out_of_order_-_explicit_grace_period/6.0.0_1591102310430/topology, ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_out_of_order_-_no_grace_period/6.0.0_1591102310191/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_out_of_order_-_no_grace_period/6.0.0_1591102310191/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_out_of_order_-_no_grace_period/6.0.0_1591102310191/topology, ksqldb-functional-tests/src/test/resources/historical_plans/tumbling-windows_-_out_of_order_-_explicit_grace_period/6.0.0_1591102322160/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/tumbling-windows_-_out_of_order_-_explicit_grace_period/6.0.0_1591102322160/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/tumbling-windows_-_out_of_order_-_explicit_grace_period/6.0.0_1591102322160/topology, ksqldb-functional-tests/src/test/resources/historical_plans/tumbling-windows_-_out_of_order_-_no_grace_period/6.0.0_1591102322087/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/tumbling-windows_-_out_of_order_-_no_grace_period/6.0.0_1591102322087/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/tumbling-windows_-_out_of_order_-_no_grace_period/6.0.0_1591102322087/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/hopping-windows.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/session-windows.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/tumbling-windows.json
When GRACE PERIOD was introduced no QTT tests were added. This PR adds them. 
This ensures we've historical plans ensuring any changes maintain backwards compatibility.
=> test: add QTT tests covering GRACE PERIOD

ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtils.java, ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/KsqlInternalTopicUtilsTest.java
backport of #5560 to the hotfix branch
=> fix: change retention to -1L instead of Long.MAX_VALUE

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/CorsTest.java
Fixes: https://github.com/confluentinc/ksql/issues/5540
Verify tests pass
=> fix: Make CorsTest server use dynamically assigned port

README.md
Fixes some of the older naming.
=> docs: fixes naming on the README

docs/how-to-guides/convert-changelog-to-table.md, docs/how-to-guides/query-structured-data.md, docs/how-to-guides/use-a-custom-timestamp-column.md
Updates the how-to guides for the new record key syntax.
=> docs: update for new key syntax

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java, ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/integration/JoinIntTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/integration/StreamsSelectAndProjectIntTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ClusterTerminationTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
fixes #5587
This change will throw if a topic is configured to use a format that requires schema registry, but schema registry is not present.
Updated unit tests and manual testing
=> fix: fail AVRO/Protobuf/JSON Schema statements if SR is missing

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java
A previous PR updated the condition in this test to check for size equal to 6 to checking it's at least 6, since it may be more than 6 depending on the order in which tests are run. This PR adds a corresponding change that's needed to avoid flakiness.
Test passes without flake.
=> test: fix flaky test (MINOR)

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java, ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
Change exception type for schema registry missing in injector
Updated/ran the tests
=> chore: change exception type for missing SR (MINOR)

Jenkinsfile
Include the settings.xml when we release a tag so its easier to buidl from source with `-s`
https://github.com/confluentinc/ksql/blob/v0.10.0-rc373-ksqldb/maven-settings.xml
=> build: commit settings.mxl to build

docs/operate-and-deploy/installation/install-ksqldb-with-docker.md
Removes vestigial recommendation of headless mode.
=> docs: remove headless recommendation

scripts/changelog/README.md, scripts/changelog/process_commit_files.py
Documents the steps I've been using to generate the auto-generated changelog for each release. Also checks the processing script into version control. Apologies for the sloppiness.
Followed the README steps.
=> chore: document steps for generating changelog

ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_constant/6.1.0_1592310470099/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_constant/6.1.0_1592310470099/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_constant/6.1.0_1592310470099/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json
Added a test case for PARTITION BY a constant.
=> test: add test case to cover partitioning by a constant (MINOR)

docs/tutorials/embedded-connect.md
Needs to be cherry-picked to master, 0.9.0-ksqldb, and 0.10.0-ksqldb.
=> docs: remove quotes from compose file (DOCS-4659)

docs/tutorials/embedded-connect.md
=> docs: update query in connect tutorial (DOCS-4202)

docs/tutorials/embedded-connect.md
From https://github.com/confluentinc/ksql/pull/5647.
=> docs: cherry-pick: update query in connect tutorial (DOCS-4202)

ksqldb-functional-tests/src/test/resources/historical_plans/create-struct_-_empty_struct_creation/5.5.0_1581572087372/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/create-struct_-_empty_struct_creation/6.0.0_1588893908517/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/create-struct_-_empty_struct_creation/6.0.0_1589910855176/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_LPad_with_literal_args_-_JSON/6.0.0_1591214175189/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/string-lpad-rpad_-_RPad_with_literal_args_-_JSON/6.0.0_1591214175330/spec.json
Update historical tests
ran them locally
=> fix: update tests after merge for 5.5.x

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/geo/GeoDistance.java, ksqldb-functional-tests/src/test/resources/historical_plans/geodistance_-_small_distances_in_where/6.1.0_1592568336546/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/geodistance_-_small_distances_in_where/6.1.0_1592568336546/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/geodistance_-_small_distances_in_where/6.1.0_1592568336546/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/geodistance.json
fixes: https://github.com/confluentinc/ksql/issues/5636
Add test case proving bug already fixed.
usual
=> test: geo_distance test to prove bug already fixed (MINOR)

CHANGELOG.md
Preliminary changelog for 0.10.0 release
=> chore: changelog for 0.10.0

ksqldb-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializationFunctionalTest.java, ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/AssertEventually.java
fixes: https://github.com/confluentinc/ksql/issues/5654
usual
=> test: fix flaky test: KsMaterializationFunctionalTest

design-proposals/README.md, design-proposals/klip-27-enhanced-udf-configuration-options.md
=> docs: klip-27: Enhanced UDF Configuration Options

docs/tutorials/embedded-connect.md
Also cherry-pick to the live branch (0.10.0-ksqldb).
=> docs: fix broken note block (DOCS-4088)

docs/tutorials/embedded-connect.md
From https://github.com/confluentinc/ksql/pull/5685.
=> docs: cherry-pick: fix broken note block (DOCS-4742)

docs/developer-guide/api.md, docs/developer-guide/ksqldb-rest-api/streaming-endpoint.md
This PR contains API docs for the new server streaming endpoints.
N/A
=> docs: API docs for new Server endpoints

docs/developer-guide/api.md, docs/developer-guide/ksqldb-rest-api/streaming-endpoint.md
=> docs: API docs for new Server endpoints (#5639)

docs/developer-guide/ksqldb-reference/scalar-functions.md
From https://github.com/confluentinc/ksql/pull/5689.
=> docs: cherry-pick: move ARRAY_JOIN scalar function in TOC (DOCS-4746)

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/QueryInfo.java, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/AdminResponseHandlers.java, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/QueryInfoImpl.java, ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java, ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/QueryInfoImplTest.java, ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
Adds support for listing queries to the Java client.
Docs will come in a follow-up PR. Javadocs on the new method and interface are included in this one.
Added unit and integration tests.
=> feat(client): support list queries in Java client

docs/developer-guide/api.md, docs/developer-guide/ksqldb-rest-api/streaming-endpoint.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5692.
=> docs: cherry-pick: fix streaming-api issues in TOC (DOCS-4748)

CHANGELOG.md
=> chore: update 0.10.0 release date

docs/developer-guide/index.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5704.
=> docs: cherry-pick: add ksqlDB client topic to dev guide nav (DOCS-4758)

docs/developer-guide/ksqldb-clients/java-client.md
From https://github.com/confluentinc/ksql/pull/5712.
=> docs: cherry-pick: update links in client docs (MINOR)

docs/developer-guide/ksqldb-clients/java-client.md
Cherry-pick https://github.com/confluentinc/ksql/pull/5720 to live docs branch, to unblock usage of Java client.
=> docs: cherry-pick "add maven repo to Java client docs example"

docs/developer-guide/ksqldb-reference/scalar-functions.md
From https://github.com/confluentinc/ksql/pull/5733.
=> docs: cherry-pick: fix incorrect code in array_contains reference (DOCS-4774)

CHANGELOG.md, docs/operate-and-deploy/installation/upgrading.md
* docs: add upgrade notes for 0.9 - 0.10
From https://github.com/confluentinc/ksql/pull/5732.
=> docs: cherry-pick: add upgrade notes for 0.9 - 0.10 (DOCS-4787)

docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/5752.
=> docs: cherry-pick: link to 0.10.0 changelog in changelog.md (DOCS-4789)

ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java, ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
fixes: https://github.com/confluentinc/ksql/issues/5749
functional test + manual
=> fix: show overridden props in CLI

docs/tutorials/event-driven-microservice.md
Fixes #5764, which experienced some breakage in the upgrade to 0.10.0.
=> docs: fixes broken event-driven app tutorial

docs/tutorials/event-driven-microservice.md
From https://github.com/confluentinc/ksql/pull/5777.
=> docs: cherry-pick: fixes broken event-driven app tutorial (DOCS-4814)

ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/UdtfLoader.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeFunctionExecutorTest.java
Fixes: https://github.com/confluentinc/ksql/issues/5734
Improved test to test the function description
=> fix: Make sure UDTF describe shows actual function description

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlServerMainTest.java
fixes #5789 
Fixed typo from #5789
None
=> chore: fixed Typo from #5789

docs/README.md
From https://github.com/confluentinc/ksql/pull/5795.
=> docs: cherry-pick: update docs readme for mkdocs-redirects (DOCS-4833)

CHANGELOG.md
=> chore: update CHANGELOG for 0.10.1

docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/5802.
=> docs: cherry-pick: update ksqlDB changelog link for 0.10.1 (DOCS-4841)

docs/faq.md
From https://github.com/confluentinc/ksql/pull/5805.
=> docs: cherry-pick: link to blog post on ksqldb vs streams (DOCS-4843)

design-proposals/klip-10-suppress.md
Added design section to discuss the implementation of suppress
n/a
=> docs: suppress design implementation

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
Using https://github.com/confluentinc/kafka/blob/master/clients/src/main/java/org/apache/kafka/clients/CommonClientConfigs.java#L96
To standardize across CP
=> chore: rename ksql.metric.reporters to metric.reporters

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/FaultyKafkaConsumer.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/HighAvailabilityTestUtil.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQuerySingleNodeFunctionalTest.java
This test case covers restoring all state when active restarts and checks that we can see the lag as it restores completely. 
Ran integration tests
=> test:  Adds another test case for pull queries for active restoring state

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/AdminResponseHandlers.java, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/DdlDmlRequestValidators.java, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/DdlDmlResponseHandlers.java, ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java, ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
Fixes https://github.com/confluentinc/ksql/issues/5584
Javadocs for the new methods are included in this PR. Usage docs will come in a follow-up PR.
Unit + integration tests.
=> feat(client): support DDL/DML statements in Java client

ksqldb-functional-tests/src/test/resources/historical_plans/timestamp-to-string_-_timestamp_to_string_in_join/6.1.0_1594853229724/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/timestamp-to-string_-_timestamp_to_string_in_join/6.1.0_1594853229724/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/timestamp-to-string_-_timestamp_to_string_in_join/6.1.0_1594853229724/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/timestamp-to-string.json
test only change - fixes #5149 
=> test: add test for timestamp-to-string with join (MINOR)

ksqldb-engine/src/main/java/io/confluent/ksql/services/DefaultServiceContext.java, ksqldb-engine/src/main/java/io/confluent/ksql/services/ServiceContextFactory.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProvider.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/DefaultKsqlClient.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/InternalKsqlClientFactory.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/RestServiceContextFactory.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/services/TestDefaultKsqlClientFactory.java, ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java
* Reuse ksqlClient between requests
Backporting #5742
=> fix: Reuse KsqlClient instance for inter node requests (#5742)

design-proposals/klip-24-key-column-semantics-in-queries.md
AV_VALUE -> AS_VALUE typo fix
_Fixes a minor typo in the klip-24 document_
_N/A_
=> docs: Klip 24 documentation typo fix

docs/developer-guide/ksqldb-reference/quick-reference.md
From https://github.com/confluentinc/ksql/pull/5854.
=> docs: cherry-pick: fix broken links in quick reference topic (DOCS-4930)

docs/developer-guide/index.md, docs/developer-guide/ksqldb-reference/drop-stream.md, docs/developer-guide/ksqldb-reference/drop-type.md, docs/developer-guide/ksqldb-reference/index.md, docs/developer-guide/ksqldb-reference/print.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-pull-query.md, docs/developer-guide/ksqldb-reference/select-push-query.md, docs/developer-guide/ksqldb-reference/show-topics.md, docs/developer-guide/syntax-reference.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5848 and https://github.com/confluentinc/ksql/pull/5854.
=> Docs 4924b

docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md
From https://github.com/confluentinc/ksql/pull/5857.
=> docs: cherry-pick: fix link in ksql-endpoint topic (DOCS-4931)

docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md
From https://github.com/confluentinc/ksql/pull/5857.
=> docs: cherry-pick: fix link in ksql-endpoint topic (DOCS-4932)

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java, ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
fixes #5801 
fixes #5798 
This commit removes the schema compatibility check that happens on create statements when the schema already exists. This is preferable to the current behavior because we only really need _read_ compatibility while the schema registry check enforces _write_ compatibility as well. The problems caused by this are quite numerous (see #5801 and #5798). The trade-off is that these failures will be delayed when an `INSERT INTO` (either type) is issued onto the streams.
Note that this only affects `CREATE` statements, not `CREATE AS` statements - `C*AS` statements will still attempt to register the schema proactively as we can be certain we will be using it to write data.
=> fix: remove schema compat check if schema exists

docs/developer-guide/ksqldb-reference/describe-function.md, docs/developer-guide/ksqldb-reference/drop-stream.md, docs/developer-guide/ksqldb-reference/drop-table.md, docs/developer-guide/ksqldb-reference/insert-into.md, docs/developer-guide/ksqldb-reference/show-functions.md, docs/developer-guide/ksqldb-reference/show-properties.md, docs/developer-guide/ksqldb-reference/spool.md, docs/developer-guide/ksqldb-reference/terminate.md
Removes hanging TODOs from the docs.
=> docs: remove TODOs

docs/how-to-guides/control-the-case-of-identifiers.md, docs/how-to-guides/index.md, mkdocs.yml
A new how-to guide to answer a commonly asked question: how do I make ksqlDB stop uppercasing everything?
=> docs: how-to guide to control casing (DOCS-4102)

docs/how-to-guides/control-the-case-of-identifiers.md, docs/how-to-guides/index.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5886.
* docs: how-to guide to control casing
* docs: update index
* Update docs/how-to-guides/control-the-case-of-identifiers.md
* docs: integrated suggestions
* Update docs/how-to-guides/control-the-case-of-identifiers.md
Co-authored-by: Almog Gavra <almog@confluent.io>
Co-authored-by: Almog Gavra <almog@confluent.io>
=> docs: cherry-pick: how-to guide to control casing (DOCS-4977)

docs/how-to-guides/control-the-case-of-identifiers.md, docs/how-to-guides/index.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5886.
* docs: how-to guide to control casing
* docs: update index
* Update docs/how-to-guides/control-the-case-of-identifiers.md
* docs: integrated suggestions
* Update docs/how-to-guides/control-the-case-of-identifiers.md
Co-authored-by: Almog Gavra <almog@confluent.io>
Co-authored-by: Almog Gavra <almog@confluent.io>
=> docs: cherry-pick: how-to guide to control casing (DOCS-4978)

docs/how-to-guides/control-the-case-of-identifiers.md, docs/how-to-guides/index.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/5886.
* docs: how-to guide to control casing
* docs: update index
* Update docs/how-to-guides/control-the-case-of-identifiers.md
* docs: integrated suggestions
* Update docs/how-to-guides/control-the-case-of-identifiers.md
Co-authored-by: Almog Gavra <almog@confluent.io>
Co-authored-by: Almog Gavra <almog@confluent.io>
=> docs: cherry-pick: how-to guide to control casing (DOCS-4979)

docs/concepts/functions.md, docs/reference/metrics.md
=> docs: adds UDF metrics to reference section

docs/concepts/functions.md, docs/reference/metrics.md
From https://github.com/confluentinc/ksql/pull/5889.
=> docs: cherry-pick: adds UDF metrics to reference section (DOCS-4980)

docs/concepts/functions.md, docs/reference/metrics.md
From https://github.com/confluentinc/ksql/pull/5889.
=> docs: cherry-pick: adds UDF metrics to reference section (DOCS-4981)

docs/developer-guide/ksqldb-reference/operators.md, docs/developer-guide/syntax-reference.md
From https://github.com/confluentinc/ksql/pull/5903.
=> docs: cherry-pick: consolidate STRUCT content in syntax reference (DOCS-4999)

docs/developer-guide/ksqldb-reference/operators.md, docs/developer-guide/syntax-reference.md
From https://github.com/confluentinc/ksql/pull/5903.
=> docs: cherry-pick: consolidate STRUCT content in syntax reference (DOCS-4998)

docs/developer-guide/syntax-reference.md
From https://github.com/confluentinc/ksql/pull/5913.
=> docs: cherry-pick: add grammar section to syntax reference (DOCS-5018)

docs/developer-guide/syntax-reference.md
From https://github.com/confluentinc/ksql/pull/5913.
=> docs: cherry-pick: add grammar section to syntax reference (DOCS-5019)

docs/developer-guide/ksqldb-reference/describe-function.md, docs/developer-guide/ksqldb-reference/drop-stream.md, docs/developer-guide/ksqldb-reference/drop-table.md, docs/developer-guide/ksqldb-reference/insert-into.md, docs/developer-guide/ksqldb-reference/show-functions.md, docs/developer-guide/ksqldb-reference/show-properties.md, docs/developer-guide/ksqldb-reference/spool.md, docs/developer-guide/ksqldb-reference/terminate.md
From https://github.com/confluentinc/ksql/pull/5878.
=> docs: cherry-pick: remove TODOs (DOCS-5020)

docs/developer-guide/ksqldb-reference/describe-function.md, docs/developer-guide/ksqldb-reference/drop-stream.md, docs/developer-guide/ksqldb-reference/drop-table.md, docs/developer-guide/ksqldb-reference/insert-into.md, docs/developer-guide/ksqldb-reference/show-functions.md, docs/developer-guide/ksqldb-reference/show-properties.md, docs/developer-guide/ksqldb-reference/spool.md, docs/developer-guide/ksqldb-reference/terminate.md
From https://github.com/confluentinc/ksql/pull/5878.
=> docs: cherry-pick: remove TODOs (DOCS-5022)

docs/developer-guide/ksqldb-reference/describe-function.md, docs/developer-guide/ksqldb-reference/drop-stream.md, docs/developer-guide/ksqldb-reference/drop-table.md, docs/developer-guide/ksqldb-reference/insert-into.md, docs/developer-guide/ksqldb-reference/show-functions.md, docs/developer-guide/ksqldb-reference/show-properties.md, docs/developer-guide/ksqldb-reference/spool.md, docs/developer-guide/ksqldb-reference/terminate.md
From https://github.com/confluentinc/ksql/pull/5878.
=> docs: cherry-pick: remove TODOs (DOCS-5024)

.github/CODEOWNERS
^ to be consistent with the docs repo. Also removes the entry for docs-md as the directory no longer exists.
=> chore: update code owner for mkdocs.yml (MINOR)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/joins/join-streams-and-tables.md, docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md, docs/developer-guide/serialization.md, docs/developer-guide/syntax-reference.md
From https://github.com/confluentinc/ksql/pull/5923.
=> docs: cherry-pick: move keywords to quick ref; add join section (DOCS-5030)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/joins/join-streams-and-tables.md, docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md, docs/developer-guide/serialization.md, docs/developer-guide/syntax-reference.md
From https://github.com/confluentinc/ksql/pull/5923.
=> docs: cherry-pick: move keywords to quick ref; add join section (DOCS-5031)

CHANGELOG.md
^ as the title says. Also cleans up a few duplicate entries from old changelog sections.
=> docs: add 0.11.0 changelog

docs/concepts/functions.md
From https://github.com/confluentinc/ksql/pull/5932.
=> docs: cherry-pick: link to blog post on UDTFs and monitoring (DOCS-5042)

docs/concepts/functions.md
From https://github.com/confluentinc/ksql/pull/5932.
=> docs: cherry-pick: link to blog post on UDTFs and monitoring (DOCS-5043)

ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_windowed_join/5.5.1_1596471687145/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_windowed_join/5.5.1_1596471687145/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_windowed_join/6.0.0_1596492907687/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_windowed_join/6.0.0_1596492907687/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/group-by_-_windowed_join/6.0.0_1596492907687/topology
Test only change to fix the build
Ran the tests
=> test: fix historical plans for group-by windowed join

docs/operate-and-deploy/changelog.md, scripts/changelog/README.md
^ as the title says. Will cherry-pick to live docs branch once this is merged.
=> docs: link to 0.11.0 changelog from microsite page

ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/ExecutionStep.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/TableFilter.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/TableSelect.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/TableSink.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/TableSource.java, ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java, ksqldb-functional-tests/src/test/resources/query-validation-tests/upgrades.json, ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/model/StructuredDataSource.java
The corresponding code for table filters/selects as #5880 did for streams.
QTT tests covering the supported and some unsupported upgrades.
=> chore: add basic validation for table upgrades (MINOR)

design-proposals/README.md
=> docs: intent for klip-32: sql based testing tool

ksqldb-functional-tests/src/test/resources/query-validation-tests/suppress.json
None, test only change in suppress qtt
None, test only change in suppress qtt
=> test: fix typos and address nits

docs/reference2/sql-syntax/data-types/character.md, docs/reference2/sql-syntax/data-types/compound.md, docs/reference2/sql-syntax/data-types/numeric.md
Add numeric ranges and a few other bits of info.
=> docs: add numeric ranges and other bits

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestGeneratorTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/replace_-_Extract_escaped_JSON/6.1.0_1596716177940/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/replace_-_Extract_escaped_JSON/6.1.0_1596716177940/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/replace_-_Extract_escaped_JSON/6.1.0_1596716177940/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/replace.json
Off the back of a community member question.
=> test: add test case using REPLACE to extract escaped json (MINOR)

docs/concepts/queries/push.md, docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md
None, docs only change
None, docs only change
=> docs: add suppress docs

CHANGELOG.md, docs/developer-guide/ksqldb-reference/aggregate-functions.md, docs/developer-guide/ksqldb-reference/scalar-functions.md, docs/developer-guide/ksqldb-reference/table-functions.md
From https://github.com/confluentinc/ksql/pull/5954.
=> docs: cherry-pick: introduced-date annotations for ksqlDB functions (DOCS-5077)

docs/overview/apache-kafka-primer.md
=> docs: copy edit Kafka primer topic

bin/ksql-run-class
Add `share/java/confluent-telemetry` to ksqlDB's classpath.
=> METRICS-1988: add confluent-telemetry directory to ksql-run-class

ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocator.java, ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocatorTest.java
Fixes issue with deprecated code with kafka-streams.
=> fix: replace kafka-streams deprecated code

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java, ksqldb-functional-tests/src/test/resources/query-validation-tests/suppress.json, ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/TableSuppressBuilder.java
Doc only change, clarifying that the buffer size is number of bytes
=> chore: clarify unit of suppress buffer is bytes

design-proposals/klip-32-sql-testing-tool.md
Rendered: https://github.com/agavra/ksql/blob/klip-32/design-proposals/klip-32-sql-testing-tool.md
=> docs: klip-32: A SQL Testing Tool

docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/6000.
* docs: add release blog links to changelog (DOCS-5097) (#5996)
* docs: add release blog links to changelog (DOCS-5103)
=> docs: cherry-pick: add release blog links to changelog (DOCS-5102)

docs/developer-guide/test-and-debug/generate-custom-test-data.md, docs/developer-guide/test-and-debug/index.md
From https://github.com/confluentinc/ksql/pull/6002.
=> docs: cherry-pick: add link to podcast on ksqlDB testing (DOCS-5105)

docs/developer-guide/test-and-debug/generate-custom-test-data.md, docs/developer-guide/test-and-debug/index.md
From https://github.com/confluentinc/ksql/pull/6002.
=> docs: cherry-pick: add link to podcast on ksqlDB testing (DOCS-5106)

docs/operate-and-deploy/installation/server-config/config-reference.md, ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
Add docs detailing how the suppress buffer config works
=> docs: add suppress buffer config docs

ksqldb-functional-tests/src/test/resources/historical_plans/create-struct_-_in_aggregate/6.1.0_1597332672487/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/create-struct_-_in_aggregate/6.1.0_1597332672487/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/create-struct_-_in_aggregate/6.1.0_1597332672487/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/create-struct.json
Added missing test for using STRUCT constructor to format the structure of the output of an aggregation.
=> test: add test for using STRUCT constructor in aggregate (MINOR)

docs/operate-and-deploy/installation/upgrading.md
From https://github.com/confluentinc/ksql/pull/6021.
=> docs: cherry-pick: remove obsolete admonitions from upgrade guide (DOCS-5113)

docs/concepts/schemas.md, docs/developer-guide/create-a-stream.md, docs/developer-guide/create-a-table.md, docs/developer-guide/index.md, docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/serialization.md, docs/operate-and-deploy/installation/server-config/avro-schema.md
Edits for https://github.com/confluentinc/ksql/pull/5995.
=> Copy edits for new schema inference content (DOCS-5101)

docs/concepts/schemas.md, docs/developer-guide/create-a-stream.md, docs/developer-guide/create-a-table.md, docs/developer-guide/index.md, docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/serialization.md, docs/operate-and-deploy/installation/server-config/avro-schema.md
From https://github.com/confluentinc/ksql/pull/6027.
=> docs: copy edits for new schema inference content (DOCS-5120)

docs/concepts/schemas.md, docs/developer-guide/create-a-stream.md, docs/developer-guide/create-a-table.md, docs/developer-guide/index.md, docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/serialization.md, docs/operate-and-deploy/installation/server-config/avro-schema.md
From https://github.com/confluentinc/ksql/pull/6027.
=> docs: cherry-pick: copy edits for new schema inference content (DOCS-5119)

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/TestDriverPipeline.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/TestDriverPipelineTest.java
Another component for YATT (see #5965): the pipeline that chains test driver topologies together.
Unit testing
=> test: add TestDriverPipeline to execute chained topology drivers

ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
=> fix: remove unnecessary parser token (MINOR)

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/SqlTestLoader.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java, ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/projections.sql
KsqlTester tests covering `CREATE OR REPLACE` for projections.
=> test: add projections.sql

ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java, ksqldb-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamAggregate.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamGroupBy.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamGroupByKey.java, ksqldb-functional-tests/pom.xml, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java, ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/filters.sql, pom.xml
This PR add support and testing for modifying filters in stream aggregations. The main changes are in `StreamAggregate`, `StreamGroupBy` and `StreamGroupByKey` classes to check that they are the same when an upgrade happens.
- added tests to `filters.json`
=> chore: support filters for stream aggregations

docs/concepts/index.md, docs/concepts/upgrades.md, docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, mkdocs.yml
Copy edit from https://github.com/confluentinc/ksql/pull/6089.
=> docs: copy edit new query upgrade topic (DOCS-5200)

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/UserRepartitionNode.java, ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_null/6.1.0_1598409518833/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_null/6.1.0_1598409518833/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/partition-by_-_null/6.1.0_1598409518833/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json, ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/PartitionByParamsFactory.java, ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/PartitionByParamsFactoryTest.java
Fixes https://github.com/confluentinc/ksql/issues/5755
Added QTT.
=> feat: support PARTITION BY NULL for creating keyless stream

CONTRIBUTING.md
There is a minor bug in the documentation for IntelliJ Idea 
None
=> docs: Contributing.md IntelliJ

docs/operate-and-deploy/installation/server-config/config-reference.md
* docs: new section for custom response headers (DOCS-4879)
* docs: add docker env variable
=> docs: new section for custom response headers (DOCS-4879) (#6128)

docs/operate-and-deploy/installation/server-config/config-reference.md
* docs: new section for custom response headers (DOCS-4879)
* docs: add docker env variable
=> docs: new section for custom response headers (DOCS-5280)

docs/developer-guide/api.md, docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md, docs/developer-guide/ksqldb-rest-api/query-endpoint.md, docs/developer-guide/ksqldb-rest-api/streaming-endpoint.md
From https://github.com/confluentinc/ksql/pull/6093.
=> docs: cherry-pick: update example curl commands (DOCS-5205)

ksqldb-functional-tests/README.md
This PR fixes a typo in the README.md of the ksqldb-functional-tests module
mvn test -pl ksqldb-functional-tests -Dtest=QueryTranslationTest
=> docs: README.md Functional Tests

docs/tutorials/embedded-connect.md, docs/tutorials/index.md
Also fix legacy uses of "KSQL".
=> docs: update table of videos in tutorials (DOCS-5062)

docs/tutorials/embedded-connect.md, docs/tutorials/index.md
From https://github.com/confluentinc/ksql/pull/6147.
=> docs: cherry-pick: update table of videos in tutorials (DOCS-5286)

docs/tutorials/embedded-connect.md, docs/tutorials/index.md
From https://github.com/confluentinc/ksql/pull/6147.
* docs: update table of videos in tutorials (DOCS-5062)
* docs: tweak a video description
=> docs: cherry-pick: update table of videos in tutorials (DOCS-5287)

docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/6075.
=> docs: cherry-pick: use correct AVRO format in AVRO serialization example (DOCS-5179)

docs/operate-and-deploy/installation/install-ksqldb-with-docker.md
Related to https://github.com/confluentinc/ksql/pull/6008.
=> docs: improve default command in docker example (DOCS-5288)

docs/operate-and-deploy/installation/install-ksqldb-with-docker.md
From https://github.com/confluentinc/ksql/pull/6156.
=> docs: cherry-pick improve default command in docker install (DOCS-5289)

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
Done to stabilize tests that are sometimes failing due to messages being produced twice.
=> test: turn on EOS for RQTT (MINOR)

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/FlatMapNode.java, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct/6.1.0_1599586293527/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct/6.1.0_1599586293527/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct/6.1.0_1599586293527/topology, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct_with_dereference/6.1.0_1599586293578/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct_with_dereference/6.1.0_1599586293578/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct_with_dereference/6.1.0_1599586293578/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/explode.json
Fixes https://github.com/confluentinc/ksql/issues/6161
Added QTT.
=> fix: allow expressions in flat map

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/FlatMapNode.java, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct/6.0.0_1599596306478/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct/6.0.0_1599596306478/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct/6.0.0_1599596306478/topology, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct_with_dereference/6.0.0_1599596306507/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct_with_dereference/6.0.0_1599596306507/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/explode_-_explode_array_of_struct_with_dereference/6.0.0_1599596306507/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/explode.json
Same as https://github.com/confluentinc/ksql/pull/6163 but for 6.0.x.
QTT.
=> fix: allow expressions in flat map (6.0.x)

ksqldb-engine/src/main/java/io/confluent/ksql/query/MissingTopicClassifier.java, ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java, ksqldb-engine/src/test/java/io/confluent/ksql/query/MissingTopicClassifierTest.java
=> fix: missing topic classifier now uses MissingSourceTopicException 

docs/developer-guide/joins/partition-data.md, docs/developer-guide/joins/synthetic-keys.md, docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/6184.
=> docs: cherry-pick: add links to blog post on keys (DOCS-5338)

pom.xml
Pins Kafka version for 0.12.x branch
=> chore: pin kafka dependencies to hotfix version

config/connect.properties, docs/how-to-guides/use-connector-management.md, docs/tutorials/etl.md, docs/tutorials/event-driven-microservice.md, docs/tutorials/materialized.md
From https://github.com/confluentinc/ksql/pull/6237.
=> docs: cherry-pick: update key converters to avoid AvroConverter references (DOCS-5405)

config/connect.properties, docs/how-to-guides/use-connector-management.md, docs/tutorials/etl.md, docs/tutorials/event-driven-microservice.md, docs/tutorials/materialized.md
From https://github.com/confluentinc/ksql/pull/6237.
=> docs: cherry-pick: update key converters to avoid AvroConverter references (DOCS-5406)

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/utils/TestUtils.java
One of our master builds failed recently with port conflict (https://jenkins.confluent.io/job/confluentinc/job/ksql/job/master/5516/). This PR aims to reduce the possibility of that happening by assigning distinct ranges to each call to `findFreeLocalPort` at the cost of limiting it to 1000 free ports.
test-only change
=> test: harden random port finding

design-proposals/README.md
Reserve KLIP-38 for variable substitution
=> docs: reserve KLIP-38 for Variable Substitution

ksqldb-common/src/main/java/io/confluent/ksql/serde/SerdeOption.java, ksqldb-common/src/main/java/io/confluent/ksql/serde/SerdeOptions.java, ksqldb-common/src/test/java/io/confluent/ksql/serde/EnabledSerdeFeaturesTest.java, ksqldb-common/src/test/java/io/confluent/ksql/serde/SerdeOptionsTest.java, ksqldb-engine/src/main/java/io/confluent/ksql/serde/SerdeOptionsFactory.java, ksqldb-engine/src/test/java/io/confluent/ksql/serde/SerdeOptionsFactoryTest.java, ksqldb-serde/src/test/java/io/confluent/ksql/schema/ksql/PhysicalSchemaTest.java
fixes: https://github.com/confluentinc/ksql/issues/6209
This finishes the wiring of the `WRAP_SINGLE_KEYS` option up. (Some bits were missed in the first PR)
Usual
=> chore: finish wiring up unwrapped keys

docs/README.md
Add `mdx_truly_sane_lists` requirement for docs build.
=> docs: add requirement to docs readme (DOCS-5437)

docs/README.md
From https://github.com/confluentinc/ksql/pull/6276.
=> docs: cherry-pick: add requirement to docs readme (DOCS-5438)

docs/operate-and-deploy/installation/server-config/security.md
Fixes https://github.com/confluentinc/ksql/issues/6192
=> docs: Improve security docs for authentication

docs/operate-and-deploy/installation/server-config/security.md
From https://github.com/confluentinc/ksql/pull/6272.
=> docs: cherry-pick: improve security docs for authentication (DOCS-5446)

docs/troubleshoot-ksqldb.md
Update log syntax for customers who are running the Confluent CLI.
=> docs: update troubleshooting topic CLI syntax (DOCS-5449)

docs/troubleshoot-ksqldb.md
From https://github.com/confluentinc/ksql/pull/6290.
=> docs: cherry-pick: update troubleshooting topic CLI syntax (DOCS-5450)

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopic.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicBackupImpl.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/CommandTopicFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicBackupImplTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicTest.java
Follow up to https://github.com/confluentinc/ksql/pull/6164
Non-functional changes
=> chore: minor follow-ups to failing on backup corruption

CHANGELOG.md
=> docs: add 0.12.0 changelog

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/ComparisonExpression.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ComparisonUtil.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/util/ComparisonUtilTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_array_equality/6.1.0_1601291312437/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_array_equality/6.1.0_1601291312437/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_array_equality/6.1.0_1601291312437/topology, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_equals/6.1.0_1601291311609/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_equals/6.1.0_1601291311609/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_equals/6.1.0_1601291311609/topology, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_is_distinct_from_(2)/6.1.0_1601291312203/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_is_distinct_from_(2)/6.1.0_1601291312203/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_is_distinct_from_(2)/6.1.0_1601291312203/topology, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_is_not_distinct_from_(2)/6.1.0_1601291312322/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_is_not_distinct_from_(2)/6.1.0_1601291312322/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_is_not_distinct_from_(2)/6.1.0_1601291312322/topology, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_map_equality/6.1.0_1601291312494/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_map_equality/6.1.0_1601291312494/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_map_equality/6.1.0_1601291312494/topology, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_nested_collections_comparison/6.1.0_1601291312596/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_nested_collections_comparison/6.1.0_1601291312596/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_nested_collections_comparison/6.1.0_1601291312596/topology, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_not_equals/6.1.0_1601291311729/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_not_equals/6.1.0_1601291311729/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_not_equals/6.1.0_1601291311729/topology, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_struct_equality/6.1.0_1601291312550/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_struct_equality/6.1.0_1601291312550/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_struct_equality/6.1.0_1601291312550/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/binary-comparison.json
This PR fixes #4770 Support Comparisons on complex types 
mvn clean package
=> feat: Support Comparisons on complex types

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestRewriterTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_array_equality/6.1.0_1601291312437/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_equals/6.1.0_1601291311609/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_is_distinct_from_(2)/6.1.0_1601291312203/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_is_not_distinct_from_(2)/6.1.0_1601291312322/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_map_equality/6.1.0_1601291312494/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_nested_collections_comparison/6.1.0_1601291312596/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_not_equals/6.1.0_1601291311729/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/binary-comparison_-_struct_equality/6.1.0_1601291312550/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_key_and_optional_value_format/6.1.0_1600876624821/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_optional_key_and_explicit_value_format/6.1.0_1600876624904/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_optional_key_and_value_format/6.1.0_1600876624874/spec.json
fixes a build failure introduced when https://github.com/confluentinc/ksql/pull/6149 was merged
=> chore: fix build

mkdocs.yml
^ as the title says. This topic should be live but it currently isn't. I will cherry-pick this to the live branch once merged.
=> docs: make client contributing guide live (MINOR)

mkdocs.yml
The version is currently still on the version for 0.11.0, so the live docs are broken. I'll cherry-pick this patch to the live docs branch once merged.
=> docs: update CP dep version for 0.12.0 release

mkdocs.yml
From https://github.com/confluentinc/ksql/pull/6333.
=> docs: cherry-pick: bump Kafka and CP versions (DOCS-5507)

docs/index.md
From https://github.com/confluentinc/ksql/pull/6376.
=> docs: cherry-pick: add links to CP content (DOCS-5557)

docs/index.md
From https://github.com/confluentinc/ksql/pull/6376.
=> docs: cherry-pick: add links to CP content (DOCS-5558)

docs/index.md
From https://github.com/confluentinc/ksql/pull/6376.
=> docs: cherry-pick: add links to CP content (DOCS-5559)

docs/index.md
From https://github.com/confluentinc/ksql/pull/6376.
=> docs: cherry-pick: add links to CP content (DOCS-5560)

CHANGELOG.md, docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/6347.
=> docs: cherry-pick 0.10.2 changelog to live branch (DOCS-5561)

CHANGELOG.md, docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/6347.
=> docs: cherry-pick: 0.10.2 changelog to live branch (DOCS-5562)

CHANGELOG.md, docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/6347.
=> docs: cherry-pick 0.10.2 changelog to 0.13.x branch

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopicInfoCache.java
=> chore: fix build issue caused by line longer than 100 characters

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/ksqldb-reference/quick-reference.md
From https://github.com/confluentinc/ksql/pull/6364.
=> docs: cherry-pick: note GROUP BY must group by selected keys (DOCS-5609)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/ksqldb-reference/quick-reference.md
From https://github.com/confluentinc/ksql/pull/6364.
=> docs: cherry-pick: note GROUP BY must group by selected keys (DOCS-5510)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/ksqldb-reference/quick-reference.md
From https://github.com/confluentinc/ksql/pull/6364.
=> docs: cherry-pick: note GROUP BY must group by selected keys (DOCS-5611)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/ksqldb-reference/quick-reference.md
From https://github.com/confluentinc/ksql/pull/6364.
=> docs: cherry-pick: note GROUP BY must group by selected keys (DOCS-5612)

docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/ksqldb-reference/select-pull-query.md, docs/developer-guide/ksqldb-reference/select-push-query.md
Fixes #5140. Add snippets in appropriate places. Please let me know if you have ideas for other snippets!
=> docs: add grace period and window retention snippets (DOCS-5528)

docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/ksqldb-reference/select-pull-query.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/6362.
=> docs: cherry-pick: grace period and window examples to live branch (DOCS-5615)

docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/ksqldb-reference/select-pull-query.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/6362.
=> docs: cherry-pick: grace period and window examples to live branch (DOCS-5618)

docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/ksqldb-reference/select-pull-query.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/6362/.
=> docs: cherry-pick: grace period and window examples to live branch (DOCS-5619)

docs/tutorials/etl.md
Fixes bad connector version in the ETL tutorial.
=> docs: fixed broken connector version

docs/tutorials/etl.md
=> docs: cherry-pick: fixed broken connector version (DOCS-5624)

docs/tutorials/etl.md
=> docs: cherry-pick: fixed broken connector version (DOCS-5625)

docs/tutorials/etl.md
=> docs: cherry-pick: fixed broken connector version (DOCS-5626)

docs/tutorials/etl.md
=> docs: cherry-pick: fixed broken connector version (DOCS-5627)

docs/tutorials/etl.md
=> docs: cherry-pick: fixed broken connector version (DOCS-5629)

docs/developer-guide/ksqldb-reference/select-pull-query.md, docs/developer-guide/ksqldb-reference/select-push-query.md
Reverts a hack I used earlier today to fix a merge conflict.
=> docs: revert 6.0.x branch changes to select ref topics (DOCS-5630)

docs/developer-guide/ksqldb-reference/select-pull-query.md, docs/developer-guide/ksqldb-reference/select-push-query.md
Finally resolves the chain of merge conflicts caused by https://github.com/confluentinc/ksql/pull/6362.
=> docs: add master branch changes to select ref topics (DOCS-5631)

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplier.java, ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplierTest.java, ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/formats.json, ksqldb-serde/src/main/java/io/confluent/ksql/serde/SchemaTranslator.java, ksqldb-serde/src/main/java/io/confluent/ksql/serde/SerdeUtils.java, ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectFormatSchemaTranslator.java, ksqldb-serde/src/test/java/io/confluent/ksql/serde/connect/ConnectFormatSchemaTranslatorTest.java
Fixes https://github.com/confluentinc/ksql/issues/6424.
Added unit test. Will add QTT once https://github.com/confluentinc/ksql/pull/6432 is merged.
=> chore: default inferred anonymous key name to ROWKEY (MINOR)

docs/developer-guide/serialization.md
helps clear up some confusion such as in https://github.com/confluentinc/ksql/issues/6435
=> docs: minor clean up to 0.12.0 docs about JSON_SR

docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/6450.
=> docs: cherry-pick: minor clean up to 0.12.0 docs about JSON_SR (DOCS-5655)

docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/6450.
=> docs: cherry-pick: minor clean up to 0.12.0 docs about JSON_SR (DOCS-5656)

docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/6450.
=> docs: cherry-pick: minor clean up to 0.12.0 docs about JSON_SR (DOCS-5658)

docs/developer-guide/syntax-reference.md
From https://github.com/confluentinc/ksql/pull/6434.
* docs: note PARTITION BY requirement for aggregations (DOCS-5550)
=> docs: cherry-pick: note PARTITION BY requirement for aggregations (DOCS-5662)

docs/developer-guide/syntax-reference.md
From https://github.com/confluentinc/ksql/pull/6434.
* docs: note PARTITION BY requirement for aggregations (DOCS-5550)
=> docs: cherry-pick: note PARTITION BY requirement for aggregations (DOCS-5663)

docs/developer-guide/syntax-reference.md
From https://github.com/confluentinc/ksql/pull/6434.
* docs: note PARTITION BY requirement for aggregations (DOCS-5550)
=> docs: cherry-pick: note PARTITION BY requirement for aggregations (DOCS-5664)

docs/developer-guide/syntax-reference.md
From https://github.com/confluentinc/ksql/pull/6434.
* docs: note PARTITION BY requirement for aggregations (DOCS-5550)
=> docs: cherry-pick: note PARTITION BY requirement for aggregations (DOCS-5665)

ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java, ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/SchemaRegistryUtil.java, ksqldb-engine/src/main/java/io/confluent/ksql/topic/TopicDeleteInjector.java, ksqldb-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java, ksqldb-engine/src/test/java/io/confluent/ksql/schema/registry/SchemaRegistryUtilTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/topic/TopicDeleteInjectorTest.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/ClusterTerminator.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ClusterTerminationTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/ClusterTerminatorTest.java, ksqldb-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroSerializerTest.java, ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/RegisterSchemaCallback.java, ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/RegisterSchemaCallbackTest.java
Nearly completes the work for #6394 and #6395 - I haven't done any work around cleaning up `AvroUtil` because I think we should just remove it (c.f. #6133). If we merge #6452 first, then I can go ahead and close the two issues above and make the constants private.
Updated all the unit tests and added new ones where appropriate
=> chore: clean up SR key intergration

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java, ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/util/TestDataProvider.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ClusterTerminationTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/CommandTopicFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/HeartbeatAgentFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/LagReportingAgentFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeWithTlsFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/SystemAuthenticationFunctionalTest.java
As not all data providers return stream data, some return tables.
=> chore: rename TestDataProvider#kstreamName (MINOR)

ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/SchemaRegistryUtil.java, ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/PostConditionsNode.java, ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/model/PostConditionsNodeTest.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorTest.java, ksqldb-functional-tests/src/test/resources/query-validation-tests/as_value.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json
And some more tests to AVRO keys and the ability to check the registered schema in the post-conditions check. Shockingly, nothing was broken...
=> test: more avro key testing & schema verification

ksqldb-udf-quickstart/src/main/resources/archetype-resources/pom.xml
fixes: https://github.com/advisories/GHSA-269g-pwp5-87pp
Can't test until https://github.com/confluentinc/ksql/issues/6480 done, but low risk change.
=> test: fix junit dependency vulnerability (MINOR)

ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/filters.sql
One of several PRs to fix the broken master build. Full set needed for green build: [#6487, #6486,#6494]
Fixes some test failures due to upstream changes.
With the upstream fix https://github.com/apache/kafka/pull/9156 in, the streams topology is no longer emitting tombstones for rows that were never in the table to start with when an input doesn't pass a filter.
This change was causing some SQL Tester tests to fail.  This change fixes those tests.
The downside of the upstream change is that query upgrades can now miss sending tombstones for any rows that where in the table _before_ the upgrade, but which don't belong in the table _after_ the upgrade, e.g. because a filter has changed.  See https://github.com/confluentinc/ksql/issues/6493 for more details.
=> test: fix SQL tester tests

docs/developer-guide/create-a-stream.md, docs/developer-guide/create-a-table.md
Fixes broken links in the docs.
=> docs: fix broken links

docs/developer-guide/create-a-stream.md, docs/developer-guide/create-a-table.md
From https://github.com/confluentinc/ksql/pull/6498.
=> docs: cherry-pick: fix broken links (DOCS-5688)

docs/developer-guide/create-a-stream.md, docs/developer-guide/create-a-table.md
From https://github.com/confluentinc/ksql/pull/6498.
=> docs: cherry-pick: fix broken links (DOCS-5689)

docs/developer-guide/create-a-stream.md, docs/developer-guide/create-a-table.md
From https://github.com/confluentinc/ksql/pull/6498.
=> docs: cherry-pick: fix broken links (DOCS-5690)

ksqldb-cli/src/main/java/io/confluent/ksql/cli/Options.java
Fixes the NPE caused by the new -f,--file CLI parameter
=> chore: fix NPE caused by new -f,--file CLI parameter

ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_GROUP_BY_IS_NULL_with_null_value/6.2.0_1603449339510/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_GROUP_BY_IS_NULL_with_null_value/6.2.0_1603449339510/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_GROUP_BY_IS_NULL_with_null_value/6.2.0_1603449339510/topology, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_GROUP_BY_with_null_value/6.2.0_1603449339429/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_GROUP_BY_with_null_value/6.2.0_1603449339429/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_GROUP_BY_with_null_value/6.2.0_1603449339429/topology, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_PARTITION_BY_with_null_value/6.2.0_1603449339405/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_PARTITION_BY_with_null_value/6.2.0_1603449339405/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_PARTITION_BY_with_null_value/6.2.0_1603449339405/topology, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_filter_with_null_value/6.2.0_1603449339373/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_filter_with_null_value/6.2.0_1603449339373/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/null_-_stream_filter_with_null_value/6.2.0_1603449339373/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/null.json
Add more QTT tests around null handling - which we know to be inconsistent.  This is more about documenting current behaviour.
Raised https://github.com/confluentinc/ksql/issues/6506 for NPE bug found.
=> test: add explicit QTT tests for null handling

docs/concepts/upgrades.md
From https://github.com/confluentinc/ksql/pull/6505.
=> docs: cherry-pick: clarify adding fields in CREATE OR REPLACE (DOCS-5708)

docs/concepts/upgrades.md
From https://github.com/confluentinc/ksql/pull/6505.
=> docs: cherry-pick: clarify adding fields in CREATE OR REPLACE (DOCS-5709)

docs/concepts/upgrades.md
From https://github.com/confluentinc/ksql/pull/6505.
=> docs: cherry-pick: clarify adding fields in CREATE OR REPLACE (#6505)

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/PullQueryExecutor.java, ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/client/RestResponse.java
Some minor tweaks that make it easier to debug RQTT failures and production issues.
=> chore: minor RQTT debug improvements

ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json
Test only change to add some more INSERT INTO testing
=> test: add INSERT VALUES tests for AVRO (MINOR)

docker-compose.yml
Fixes https://github.com/confluentinc/ksql/issues/6519
Ran `docker-compose up --scale additional-ksqldb-server=2` and saw it no longer fails.
=> chore: remove docker compose container name to prevent conflicts (MINOR)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md, docs/operate-and-deploy/installation/server-config/config-reference.md, docs/reference/sql/appendix.md
From https://github.com/confluentinc/ksql/pull/6528.
=> docs: cherry-pick: remove references to EMIT FINAL (DOCS-5726)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md, docs/operate-and-deploy/installation/server-config/config-reference.md, docs/reference/sql/appendix.md
From https://github.com/confluentinc/ksql/pull/6528.
=> docs: cherry-pick: remove references to EMIT FINAL (DOCS-5727)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md, docs/operate-and-deploy/installation/server-config/config-reference.md, docs/reference/sql/appendix.md
From https://github.com/confluentinc/ksql/pull/6528.
=> docs: cherry-pick: remove references to EMIT FINAL (DOCS-5728)

docs/developer-guide/ksqldb-reference/operators.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/reference/sql/appendix.md
Adds documentation for IN operator.  This is currently only supported for pull queries, so it mentions that.
=> docs: Adds documentation for IN operator

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
Fixes #5707 
Replaces `ImmutableList.of()` with `ImmutableList.copyOf(Arrays.asList())`
Manual: Generated docker image and ran a manual test with 17 `CASE` conditions
=> feat: CASE expressions can now handle 12+ conditions in docker + cloud

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
=> feat: CASE expressions can now handle 12+ conditions in docker + cloud cherry picking

pom.xml
=> chore: bump AK version to 6.1.0-beta201006024150-hf-1

ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
We should always log the error type in our logs so that if we know what type the error was if metrics don't properly get emitted.
Logging-only change
=> chore: improve logging around query error type

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/Server.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TlsTest.java, ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java
Same as https://github.com/confluentinc/ksql/pull/6558 but for 6.0.x.
Integration test.
=> fix: add back configs for setting TLS protocols and cipher suites (6.0.x)

docs/operate-and-deploy/installation/server-config/security.md
Docs updates for https://github.com/confluentinc/ksql/pull/6559. This change does not need to be cherry-picked to any other branches this time. (It may apply to 6.0.1 depending on when the release is cut. We don't appear to have a 6.0.1-post branch yet. If we release ksqlDB 0.10.3 to correspond to 6.0.1, the change will be needed on 0.10.3-ksqldb but that doesn't exist yet either.)
=> docs: update docs for TLS configs (6.0.x)

docs/operate-and-deploy/installation/server-config/security.md
Docs updates for https://github.com/confluentinc/ksql/pull/6558. This change will also be merged forward to master.
=> docs: update docs for TLS configs

docs/developer-guide/ksqldb-reference/operators.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/reference/sql/appendix.md
Cherry pick of #6539 into 6.1.x
=> docs: Adds documentation for IN operator (#6539)

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java
=> chore: bump Command.VERSION to 2 for 6.1.0 (0.14.0) release

pom.xml
=> chore: update kafka artifacts

pom.xml
=> chore: set kafka version artifacts after publishing them

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java, pom.xml
=> chore: bump command version number

CHANGELOG.md, docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/6316.
=> docs: cherry-pick: changelog for 0.13 (DOCS-5814)

CHANGELOG.md, docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/6316.
=> docs: cherry-pick: changelog for 0.13 (DOCS-5816)

ksqldb-common/src/main/java/io/confluent/ksql/schema/Operator.java, ksqldb-common/src/main/java/io/confluent/ksql/util/DecimalUtil.java
=> refactor: remove duplicate decimal code (MINOR)

ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java, ksqldb-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java
Prevents `INSERT VALUES` from overwriting the schema in schema registry.
- unit tests
- manual testing to make sure that we can still insert values if ksqlDB created the schema via `CREATE STREAM/TABLE`
=> chore: refuse INSERT VALUES that would modify key schema

ksqldb-cli/src/main/java/io/confluent/ksql/Ksql.java
This feature is no longer utilized.
=> chore: remove CLI version checker agent

docs/tutorials/embedded-connect.md, mkdocs.yml
=> docs: use site var for kafka-connect-jdbc version (DOCS-5837)

docs/tutorials/embedded-connect.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/6614.
=> docs: cherry-pick: use site var for kafka-connect-jdbc version (DOCS-5869)

docs/how-to-guides/create-a-user-defined-function.md
Avoid hardcoding the CP version in our UDF guide.
=> docs: don't hardcode CP version

design-proposals/README.md
=> docs: intent for klip-42: Schema Migrations Tool

ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
Follow-up from https://github.com/confluentinc/ksql/pull/6601#discussion_r524878013
Ran the unit tests
=> chore: improve sr key schema check in insert values (MINOR)

docs/developer-guide/ksqldb-reference/type-coercion.md, mkdocs.yml
Draft: https://github.com/confluentinc/ksql/pull/6617.
=> docs: copy edit new Type Coercion topic (DOCS-5886)

design-proposals/README.md
=> docs: intent for klip-43: TIMESTAMP data type support

ksqldb-functional-tests/src/test/resources/query-validation-tests/as_value.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/delimited.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/json.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/json_sr.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/kafka.json, ksqldb-serde/src/main/java/io/confluent/ksql/serde/GenericKeySerDe.java, ksqldb-serde/src/test/java/io/confluent/ksql/serde/GenericKeySerDeTest.java
Fixes https://github.com/confluentinc/ksql/issues/6621 by disallowing map keys.
Unit + QTT.
=> chore: disallow map keys

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatter.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java
Simple change to add partitions to the output of print topic
Unit testing & local testing
=> feat: add partitions to PRINT TOPIC output

docs/operate-and-deploy/installation/server-config/config-reference.md
From https://github.com/confluentinc/ksql/pull/6670.
=> docs: cherry-pick: note result when ksqlDB IDs connect to same AK cluster (DOCS-6025)

docs/operate-and-deploy/installation/server-config/config-reference.md
From https://github.com/confluentinc/ksql/pull/6670.
=> docs: cherry-pick: note result when ksqlDB IDs connect to same AK cluster (DOCS-6026)

docs/operate-and-deploy/installation/server-config/config-reference.md
From https://github.com/confluentinc/ksql/pull/6670.
=> docs: cherry-pick: note result when ksqlDB IDs connect to same AK cluster (DOCS-6027)

README.md, design-proposals/README.md, docs/developer-guide/ksqldb-clients/contributing.md
From https://github.com/confluentinc/ksql/pull/6669.
=> docs: cherry-pick: development in single Slack channel (DOCS-6028)

README.md, design-proposals/README.md, docs/developer-guide/ksqldb-clients/contributing.md
From https://github.com/confluentinc/ksql/pull/6669.
=> docs: cherry-pick: development in single Slack channel (DOCS-6029)

README.md, design-proposals/README.md, docs/developer-guide/ksqldb-clients/contributing.md
From https://github.com/confluentinc/ksql/pull/6669.
=> docs: cherry-pick: development in single Slack channel (DOCS-6030)

docs/developer-guide/ksqldb-clients/contributing.md
From https://github.com/confluentinc/ksql/pull/6677.
=> docs: cherry-pick: fix typo in clients Contributing topic (DOCS-6032) (#6677)

docs/developer-guide/ksqldb-clients/contributing.md
From https://github.com/confluentinc/ksql/pull/6677.
=> docs: cherry-pick: fix typo in clients Contributing topic (DOCS-6034)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/joins/join-streams-and-tables.md, docs/developer-guide/ksqldb-reference/aggregate-functions.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/6660.
* docs: replace 'late-arriving' with 'out-of-order' (DOCS-6006)
* docs: capitalize a couple of headings
* docs: incorporate more feedback
=> docs: cherry-pick: replace 'late-arriving' with 'out-of-order' (DOCS-6062)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/joins/join-streams-and-tables.md, docs/developer-guide/ksqldb-reference/aggregate-functions.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/6660.
* docs: replace 'late-arriving' with 'out-of-order' (DOCS-6006)
* docs: capitalize a couple of headings
* docs: incorporate more feedback
=> docs: cherry-pick: replace 'late-arriving' with 'out-of-order' (DOCS-6063)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/joins/join-streams-and-tables.md, docs/developer-guide/ksqldb-reference/aggregate-functions.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/6660.
* docs: replace 'late-arriving' with 'out-of-order' (DOCS-6006)
* docs: capitalize a couple of headings
* docs: incorporate more feedback
=> docs: cherry-pick: replace 'late-arriving' with 'out-of-order' (DOCS-6064)

mkdocs.yml
From https://github.com/confluentinc/ksql/pull/6705.
=> docs: cherry-pick: update ksqlDB maven path for 0.13.0 (DOCS-6099)

ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json
Following up from https://github.com/confluentinc/ksql/pull/6692#discussion_r532969819
=> test: more protobuf tests

docs/index.md, docs/stylesheets/extra.css
Minor change to make the cards look easier on the eyes.
=> docs: adds border to cards

docs/concepts/schemas.md
From https://github.com/confluentinc/ksql/pull/6736.
* docs: fix spurious lists indentations in Schemas topic (DOCS-6153)
* docs: remove one more column
=> docs: cherry-pick: fix spurious list indentations in Schemas topic (DOCS-6160)

docs/concepts/schemas.md
From https://github.com/confluentinc/ksql/pull/6736.
* docs: fix spurious lists indentations in Schemas topic (DOCS-6153)
* docs: remove one more column
=> docs: cherry-pick: fix spurious list indentations in Schemas topic (DOCS-6161)

docs/concepts/index.md, docs/how-to-guides/index.md, docs/stylesheets/extra.css, docs/tutorials/index.md
Switches the how to guides to use the new card layout.
=> Use cards for the how-to guides

ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlanBuilder.java, ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/WhereInfo.java, ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/operators/WhereInfoTest.java
Improve `WhereInfo` and test coverage
Mostly a test-only change
=> chore: improve WhereInfo & testing

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopicInfoCache.java
=> test: improve error message for unknown output topic in QTT 

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java, ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/SchemaRegistryUtil.java, ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/schema/registry/SchemaRegistryUtilTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
=> chore: backport "remove usage of SRClient#getAllSubjects"

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md, docs/operate-and-deploy/installation/server-config/config-reference.md, docs/reference/sql/appendix.md
=> docs: cherry-pick: remove references to EMIT FINAL (DOCS-6217)

design-proposals/klip-42-schema-migrations-tool.md
KLIP for the new schema migrations tool. 
=> docs: klip-42 - Schema Migrations Tool

CHANGELOG.md, docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/6599.
* chore: create changelog for 0.14.0 release
* fix typo
* address comments
=> docs: cherry-pick: create changelog for 0.14.0 release (DOCS-6242)

design-proposals/README.md, design-proposals/klip-43-timestamp-data-type-support.md
KLIP for adding timestamp data type support to KSQL.
=> docs: klip-43: timestamp data type support

docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/6788.
=> docs: cherry-pick: link 0.14.0 blog post in changelog (DOCS-6272)

docs/concepts/schemas.md, docs/developer-guide/aggregate-streaming-data.md, docs/developer-guide/joins/partition-data.md, docs/developer-guide/transform-a-stream-with-ksqldb.md, docs/tutorials/examples.md, docs/tutorials/index.md
From https://github.com/confluentinc/ksql/pull/6769.
=> docs: cherry-pick: update ksqlDB Stream Processing Cookbook links to point to Kafka Tutorials (DOCS-6249)

docs/concepts/schemas.md, docs/developer-guide/aggregate-streaming-data.md, docs/developer-guide/joins/partition-data.md, docs/developer-guide/transform-a-stream-with-ksqldb.md, docs/tutorials/examples.md, docs/tutorials/index.md
From https://github.com/confluentinc/ksql/pull/6769.
=> docs: cherry-pick: update ksqlDB Stream Processing Cookbook links to point to Kafka Tutorials (DOCS-6251)

design-proposals/klip-42-schema-migrations-tool.md
A few changes on KLIP-42
- Remove the use of LATEST in KLIP-42
- Remove the reference that create/add creates two files
- Remove baseline and use initialize to set version/description
=> chore: fix KLIP-42 - Schema migrations

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java, ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json
I had accidentally committed `@Ignore` for this test! Shame on me. Unignoring it.
**NOTE**: The changed tests are as a result of #6762 which is intentional - you can no longer join windows that don't match.
Ran the test
=> test: re-enable RestQueryTranslationTest

ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
fix issue after rebase (changes some error messages)
=> test: fix RQTT pull query test after rebase

docs/developer-guide/joins/partition-data.md
Removes outdated text from the docs. I will cherry-pick to the live 0.14.0 branch once approved.
=> docs: remove outdated text on key requirements (MINOR)

docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/insert-into.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/serialization.md
Docs updates corresponding to https://github.com/confluentinc/ksql/pull/6803.
=> docs: docs for multi-column PARTITION BY (MINOR)

docs/how-to-guides/test-an-app.md
From https://github.com/confluentinc/ksql/pull/6826.
=> docs: cherry-pick: adds back text for making input files (DOCS-6398)

docs/how-to-guides/test-an-app.md
From https://github.com/confluentinc/ksql/pull/6826.
=> docs: cherry-pick: adds back text for making input files (DOCS-6399)

docs/how-to-guides/test-an-app.md
From https://github.com/confluentinc/ksql/pull/6826.
=> docs: cherry-pick: adds back text for making input files (DOCS-6400)

docs/developer-guide/joins/synthetic-keys.md
Updating the synthetic key documentations to avoid making perspective claims of what will be, as we have not yet decided the final semantics for join keys.
N/A
=> docs: clear up synthetic key documentation

debian/Makefile, debian/confluent-ksqldb.spec.in, debian/control
- Remove (package) dependency on rest-utils as its not needed.
- Add Virtual Package "Provides" to "provide" community-ksqldb release.
- Conditinalize RPM_VERSION setting.
With respect to KSQLDB and independent releases and OS packages, these changes are required in order to:
* Allow the ksqldb OS package to be "independent" of any other `confluent-*` packages
* Support building CP-versioned packages with a `community-ksqldb` "Virtual" package that "provides" said KSQLDB community version  (Other names may be suggested)
You will have to take my word for it, but you can build these artifacts as follows:
DEB:
```
git checkout -b debian-0.14.0-ksqldb origin/0.14.0-ksqldb
dch --newversion "6.1.0-0.ksqldb0.14.0" "Release version 6.1.0-0.ksqldb0.14.0"
dch --release --distribution unstable "" …
```
=> refactor: Tune Package Relationship

docs/operate-and-deploy/installation/server-config/config-reference.md
From https://github.com/confluentinc/ksql/pull/6839.
=> docs: fix ksql.advertised.listener setting (DOCS-6441)

docs/operate-and-deploy/installation/server-config/config-reference.md
From https://github.com/confluentinc/ksql/pull/6839.
=> docs: cherry-pick: fix ksql.advertised.listener setting (DOCS-6442)

docs/developer-guide/joins/synthetic-keys.md
From https://github.com/confluentinc/ksql/pull/6836.
=> docs: cherry-pick: clear up synthetic key documentation (DOCS-6447)

docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md
Removes an example where it shouldn't be and fixes the existing one.
=> docs: fixes ctas examples (DOCS-6494)

docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md
From https://github.com/confluentinc/ksql/pull/6857.
=> docs: cherry-pick: fixes ctas examples (DOCS-6498)

docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md
From https://github.com/confluentinc/ksql/pull/6857.
=> docs: cherry-pick: fixes ctas examples (DOCS-6499)

docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md
From https://github.com/confluentinc/ksql/pull/6857.
=> docs: cherry-pick: fixes ctas examples (DOCS-6500)

docs/operate-and-deploy/monitoring.md
=> docs: use version token in monitoring example

docs/developer-guide/ksqldb-clients/java-client.md
^ as the title says. This does not need to be backported to any other branches. (The change shouldonly go live once CP 6.1.0 is released.)
=> docs: use cprelease as example CP version for java client (MINOR)

docs/operate-and-deploy/monitoring.md
From https://github.com/confluentinc/ksql/pull/6861.
=> docs: cherry-pick: use version token in monitoring example (DOCS-6634)

docs/operate-and-deploy/monitoring.md
From https://github.com/confluentinc/ksql/pull/6861.
=> docs: cherry-pick: use version token in monitoring example (DOCS-6635)

CHANGELOG.md, docs/operate-and-deploy/installation/upgrading.md
From https://github.com/confluentinc/ksql/pull/6867.
=> docs: cherry-pick: in-place upgrades clarification (DOCS-6556)

CHANGELOG.md, docs/operate-and-deploy/installation/upgrading.md
From https://github.com/confluentinc/ksql/pull/6867.
=> docs: clarify where in-place upgrades are supported (DOCS-6557)

CHANGELOG.md, docs/operate-and-deploy/installation/upgrading.md
From https://github.com/confluentinc/ksql/pull/6867.
=> docs: cherry-pick: clarify where in-place upgrades are supported (DOCS-6636)

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/AuthenticationPlugin.java
update java docs, all implementations have this behavior so figured I should make it clear
n/a
=> docs: improve javadoc for AuthenticationPlugin [ultra-MINOR]

CONTRIBUTING.md
=> docs: update contribtuing.md to ensure that we don't squash commits (minor)

docs/reference/serialization.md
=> docs: fix incorrect statement about JSON_SR

docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/6900.
=> docs: cherry-pick: fix incorrect statement about JSON_SR (DOCS-6722)

docs/reference/serialization.md
From https://github.com/confluentinc/ksql/pull/6900.
=> docs: cherry-pick: fix incorrect statement about JSON_SR (DOCS-6723)

docs/developer-guide/serialization.md
From https://github.com/confluentinc/ksql/pull/6900.
=> docs: cherry-pick: fix incorrect statement about JSON_SR (DOCS-6724)

ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/PlanInfoExtractor.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluatorTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListVariablesExecutorTest.java
=> chore: fix some compiler warnings (MINOR)

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java, ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/HARouting.java, ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/HARoutingTest.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/HighAvailabilityTestUtil.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
=> fix: Fixes auth for forwarded requests for pull queries (#6895)

pom.xml
Upgrade Antlr to 4.7.1 per https://confluentinc.atlassian.net/browse/FF-3934 to fix the potential security issue.
No, existing tests should cover this.
=> fix: upgrade antlr to 4.7.1

ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/partition-by.json
Fixes some QTT tests after upgrade to antlr.
Ran QTT.
=> fix: Changes a couple query validation tests after upgrade to antlr

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java, ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
Fixes https://github.com/confluentinc/ksql/issues/6885
=> fix: npe when getting topic configs

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java, ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
Backport of https://github.com/confluentinc/ksql/pull/6946
To address https://github.com/confluentinc/ksql/issues/6885
=> fix: npe when getting topic configs (#6946)

docs/developer-guide/ksqldb-reference/create-table-as-select.md
=> docs: scrub reference to EMIT FINAL

pom.xml
Fix a potential security issue by minor version upgrade of httpclient
Existing tests are supposed to cover this.
=> fix: ff-4240 upgrade httpclient version

ksqldb-functional-tests/src/test/resources/query-validation-tests/key-field.json
Changes a query validation tests after upgrade to antlr
=> fix: Changes a query validation tests after upgrade to antlr

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java, ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java, ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java, ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java, ksqldb-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java, ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/util/PersistentQueryMetadataTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedPersistentQueryMetadataTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
Fixes the build to make sure that state dirs are properly closed.
ran `mvn clean install` locally
=> build: fix build after AK bump

docs/developer-guide/ksqldb-rest-api/query-endpoint.md
From https://github.com/confluentinc/ksql/pull/6980.
=> docs: cherry-pick: correct examples on /query endpoint docs (MINOR) (DOCS-7033)

docs/developer-guide/ksqldb-rest-api/query-endpoint.md
From https://github.com/confluentinc/ksql/pull/6980.
=> docs: cherry-pick: correct examples on /query endpoint docs (MINOR) (DOCS-7035)

docs/developer-guide/ksqldb-rest-api/query-endpoint.md
From https://github.com/confluentinc/ksql/pull/6980.
=> docs: cherry-pick: correct examples on /query endpoint docs (MINOR) (DOCS-7034)

ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java, ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
Cherry pick-ish of #6979 
Unit tests.
=> build: fix build after AK bump (#6979)

Jenkinsfile
Let's move build failure alerts to a less urgent channel
=> build: move alerts to #ksqldb-warn

ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
=> chore: fix CliTest.testDisableVariableSubstitution()

docs/reference/processing-log.md
Related: https://github.com/confluentinc/ksql/pull/6993.
=> docs: fix merge conflict from 6.1.x to master (DOCS-7084)

docs/reference/processing-log.md
Related: https://github.com/confluentinc/ksql/pull/6993.
=> docs: manual merge from 6.1.x to master (DOCS-7084)

docs/reference/processing-log.md
From https://github.com/confluentinc/ksql/pull/6993.
=> docs: cherry-pick: clarify file and env variables for log4j (DOCS-7085)

docs/reference/processing-log.md
Introduced in https://github.com/confluentinc/ksql/pull/6993.
=> docs: remove incorrect env variable (DOCS-7086)

docs/reference/processing-log.md
From https://github.com/confluentinc/ksql/pull/7001.
=> docs: cherry-pick: remove incorrect env variable (DOCS-7088)

ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/DateToString.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/FromUnixTime.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/ParseTimestamp.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToDate.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToTimestamp.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/TimestampToString.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/UnixDate.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/UnixTimestamp.java
Make changes in the UDF date/time functions.
=> chore: improve date/time UDF descriptions

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/TypeContext.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/TypeContextTest.java
Updates the context to contain all the information we need for the upcoming lambda type resolution
=> feat: adding TypeContext for Lambdas

CHANGELOG.md
* update changelog for 0.15
* address review feedback
* review feedback
* feedback
=> cherry-pick: update changelog for 0.15 (DOCS-7107)

CHANGELOG.md
* update changelog for 0.15
* address review feedback
* review feedback
* feedback
=> cherry-pick: update changelog for 0.15 (DOCS-7105)

docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/7009.
=> docs: cherry-pick: link to main 0.15.0 changelog in built changelog (DOCS-7118) 

docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/7009.
=> docs: cherry-pick: link to main 0.15.0 changelog in built changelog (DOCS-7125)

docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/7015.
=> docs: cherry-pick: link to 0.15.0 blog post in changelog topic (DOCS-7127)

docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/7015.
=> docs: cherry-pick: link to 0.15.0 blog post in changelog topic (DOCS-7115) (#7015)

docs/how-to-guides/create-a-user-defined-function.md
Removes old warning as of #5738.
=> Removes old UDAF configurable warning

docs/developer-guide/ksqldb-clients/java-client.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7024.
=> docs: cherry-pick: fix beta tag for 0.15 (DOCS-7136)

docs/developer-guide/ksqldb-clients/java-client.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7024.
=> docs: cherry-pick: fix for KStreams beta tag (DOCS-7137)

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationException.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationsUtil.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/BaseCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CleanMigrationsCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/MigrationInfoCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommand.java
Refactors some of the code commited here: #6988 
Specifically,
* move java client creation to a new utils file
* handle timing in BaseCommand class
* add new MigrationException class
=> chore: refactor schema migrations tool

ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatterTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/cast_-_struct_to_struct_with_same_schema/6.0.2_1613684374835/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/cast_-_struct_to_struct_with_same_schema/6.0.2_1613684374835/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/cast_-_struct_to_struct_with_same_schema/6.0.2_1613684374835/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/cast.json
Backports https://github.com/confluentinc/ksql/pull/6245 to 6.0.x.
Unit + QTT backported.
=> fix: format cast arguments with passed context (6.0.x)

docs/concepts/index.md, docs/how-to-guides/index.md, docs/reference/index.md, docs/stylesheets/extra.css, docs/tutorials/index.md
Responding to feedback that the cards should be clickable.
=> Makes the docs card titles clickable

docs/operate-and-deploy/how-it-works.md
From https://github.com/confluentinc/ksql/pull/7035.
=> docs: cherry-pick: fix YAML front matter in architecture topic (DOCS-7150)

docs/operate-and-deploy/how-it-works.md
From https://github.com/confluentinc/ksql/pull/7035.
=> docs: cherry-pick: fix YAML front matter in architecture topic (DOCS-7151)

docs/operate-and-deploy/how-it-works.md
Queryable state is no longer unique to Kafka Streams.
=> docs: state is now queryable, no longer a difference

docs/operate-and-deploy/how-it-works.md
From https://github.com/confluentinc/ksql/pull/7040.
=> docs: cherry-pick: state is now queryable, no longer a difference (DOCS-7158)

docs/operate-and-deploy/how-it-works.md
From https://github.com/confluentinc/ksql/pull/7040.
=> docs: cherry-pick: state is now queryable, no longer a difference (DOCS-7159)

docs/index.md, docs/stylesheets/extra.css
Robin just launched a video series. Let's link to them in the docs.
=> Link to Robin's new videos

docs/index.md, docs/stylesheets/extra.css
From https://github.com/confluentinc/ksql/pull/7042.
* docs: integrate Robin's videos
* docs: split videos into two columns
=> docs: cherry-pick: link to Robin's new videos (DOCS-7154)

docs/index.md, docs/stylesheets/extra.css
From https://github.com/confluentinc/ksql/pull/7042.
* docs: integrate Robin's videos
* docs: split videos into two columns
=> docs: cherry-pick: link to Robin's new videos (DOCS-7166)

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java, ksqldb-engine/src/main/java/io/confluent/ksql/engine/PullQueryExecutionUtil.java, ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
fixes #4025 
fixes #5821 
Added test to cover new error message
=> chore: update some pull query error messages and configs

ksqldb-tools/pom.xml, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommand.java
Also refactors the class to throw exceptions instead of calling `System.exit`
=> chore(migrations): update MigrationConfig to query /info with Java client

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationsUtil.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java, ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommandTest.java, ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommandTest.java
As the title says. Also fixes a minor bug with handling of migrations directories with trailing slashes.
:)
=> test(migrations): add unit tests for `new` and `initialize`

docs/operate-and-deploy/how-it-works.md
From https://github.com/confluentinc/ksql/pull/7068.
=> docs: cherry-pick: fix topic name mismatch in code example (DOCS-7194)

docs/operate-and-deploy/how-it-works.md
From https://github.com/confluentinc/ksql/pull/7068.
=> docs: cherry-pick: fix topic name mismatch in code example (DOCS-7195)

docs/developer-guide/joins/synthetic-keys.md
Original example had a table repartition, which is not supported.
Ran the example locally
=> docs: fix synthetic key example

docs/developer-guide/joins/synthetic-keys.md
From https://github.com/confluentinc/ksql/pull/7067.
=> docs: cherry-pick: fix synthetic key example (DOCS-7197)

docs/developer-guide/joins/synthetic-keys.md
From https://github.com/confluentinc/ksql/pull/7067.
=> docs: cherry-pick: fix synthetic key example (DOCS-7199)

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/Migrations.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/InitializeMigrationCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MetadataUtil.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsDirectoryUtil.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsUtil.java, ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java, ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommandTest.java
* Moves `MigrationUtil` into a util folder that also includes `MetadataUtil` for handling the migration stream/table, and `MigrationsDirectoryUtil` for handling the migrations directory.
* Adds functions in title
=> chore(migrations): utility functions for retrieving migration files and finding the current version

mkdocs.yml
=> docs: fixes 404 that should redirect

mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7079.
=> docs: cherry-pick: fixes 404 that should redirect (DOCS-7206)

mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7079.
=> docs: cherry-pick: fixes 404 that should redirect (DOCS-7207

mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7079.
=> docs: cherry-pick: fixes 404 that should redirect (DOCS-7208)

docs/developer-guide/ksqldb-reference/aggregate-functions.md, docs/reference/server-configuration.md
Now that #6711 is closed, we should update the docs accordingly!
n/a
=> docs: update docs for collect list/set

docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md
Add the WITHIN clause syntax on SELECT docs
=> docs: add WITHIN + other JOINS syntax to SELECT docs

docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/7110.
=> docs: cherry-pick: add WITHIN + other JOINS syntax to SELECT docs (DOCS-7264)

docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/7110.
=> docs: cherry-pick: add WITHIN + other JOINS syntax to SELECT docs (DOCS-7265)

docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/7111.
=> docs: cherry-pick: add WITHIN and other JOINS syntax to SELECT docs (DOCS-7266)

docs/reference/server-configuration.md
Related: https://github.com/confluentinc/ksql/pull/3386.
=> docs: remove ksql.connect.polling.enable config from docs (KCI-226)

docs/reference/server-configuration.md
From https://github.com/confluentinc/ksql/pull/7121.
=> docs: cherry-pick: remove ksql.connect.polling.enable config from docs (DOCS-7286)

docs/reference/server-configuration.md
From https://github.com/confluentinc/ksql/pull/7121.
=> docs: cherry-pick: remove ksql.connect.polling.enable config from docs (DOCS-7287)

docs/operate-and-deploy/how-it-works.md
From https://github.com/confluentinc/ksql/pull/7068.
=> docs: cherry-pick: fix topic name mismatch in code example (DOCS-7296)

docs/developer-guide/joins/synthetic-keys.md
From https://github.com/confluentinc/ksql/pull/7067.
=> docs: cherry-pick: fix synthetic key example (DOCS-7298)

mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7079.
=> docs: cherry-pick: fixes 404 that should redirect (DOCS-7299)

docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/7110.
=> docs: cherry-pick: add WITHIN + other JOINS syntax to SELECT docs (DOCS-7301)

docs/reference/server-configuration.md
From https://github.com/confluentinc/ksql/pull/7121.
=> docs: cherry-pick: remove ksql.connect.polling.enable config from docs (DOCS-7302)

docs/developer-guide/ksqldb-clients/java-client.md
From https://github.com/confluentinc/ksql/pull/7090.
=> docs: cherry-pick: link to Java client blog post (DOCS-7305)

docs/developer-guide/ksqldb-clients/java-client.md
From https://github.com/confluentinc/ksql/pull/7090.
=> docs: cherry-pick: link to Java client blog post (DOCS-7306)

docs/developer-guide/ksqldb-clients/java-client.md
From https://github.com/confluentinc/ksql/pull/7090.
=> docs: cherry-pick: link to Java client blog post (DOCS-7307)

docs/concepts/functions.md, docs/concepts/queries.md, docs/concepts/streams.md, docs/concepts/tables.md, docs/developer-guide/ksqldb-reference/define.md, docs/developer-guide/ksqldb-reference/show-variables.md, docs/developer-guide/ksqldb-reference/undefine.md, docs/how-to-guides/control-the-case-of-identifiers.md, docs/how-to-guides/convert-changelog-to-table.md, docs/how-to-guides/create-a-user-defined-function.md, docs/how-to-guides/index.md, docs/how-to-guides/query-structured-data.md, docs/how-to-guides/substitute-variables.md, docs/how-to-guides/test-an-app.md, docs/how-to-guides/update-a-running-persistent-query.md, docs/how-to-guides/use-a-custom-timestamp-column.md, docs/how-to-guides/use-connector-management.md, docs/operate-and-deploy/logging.md, docs/operate-and-deploy/monitoring.md, docs/operate-and-deploy/schema-registry-integration.md, docs/reference/metrics.md, docs/reference/sql/time.md, docs/reference/user-defined-functions.md, docs/tutorials/etl.md, docs/tutorials/event-driven-microservice.md, docs/tutorials/materialized.md
From https://github.com/confluentinc/ksql/pull/7147.
=> docs: cherry-pick: add YAML frontmatter to new topics (DOCS-7339)

ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlLambdaResolved.java
=> chore: make input type list immutable in SqlLambdaResolved

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsUtil.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/ServerVersionUtil.java, ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/MigrationsUtilTest.java
Reads auth configs from the config file and passes them to ClientOptions.
unit test for creating ClientOptions.
=> chore(migrations): enable auth for migrations tool

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/TimestampAdd.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/TimestampSub.java, ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/TimestampAddTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/TimestampSubTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/timestampadd_-_handles_null_values/7.0.0_1614885651365/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/timestampadd_-_handles_null_values/7.0.0_1614885651365/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/timestampadd_-_handles_null_values/7.0.0_1614885651365/topology, ksqldb-functional-tests/src/test/resources/historical_plans/timestampsub_-_handles_null_values/7.0.0_1614885652189/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/timestampsub_-_handles_null_values/7.0.0_1614885652189/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/timestampsub_-_handles_null_values/7.0.0_1614885652189/topology, ksqldb-functional-tests/src/test/resources/historical_plans/transform-array_-_apply_transform_lambda_function_to_array_of_timestamps/7.0.0_1614883229056/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/transform-array_-_apply_transform_lambda_function_to_array_of_timestamps/7.0.0_1614883229056/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/transform-array_-_apply_transform_lambda_function_to_array_of_timestamps/7.0.0_1614883229056/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/timestampadd.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/timestampsub.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/transform-array.json
Checks function inputs for null values
QTT and unit tests
=> fix: return null on null input for timestamp math functions

mkdocs.yml
Related: https://github.com/confluentinc/docs-platform/pull/493.
=> docs: add redirect from developer-guide to reference (DOCS-7367)

mkdocs.yml
Related: https://github.com/confluentinc/ksql/pull/7163.
=> docs: add redirect from developer-guide to reference (DOCS-7368)

mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7166.
=> docs: cherry-pick: add redirect from developer-guide to reference (DOCS-7372)

mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7166.
=> docs: cherry-pick: add redirect from developer-guide to reference (DOCS-7373)

docs/concepts/index.md, docs/concepts/lambda-functions.md, docs/developer-guide/ksqldb-reference/scalar-functions.md, docs/how-to-guides/index.md, docs/how-to-guides/use-lambda-functions.md, mkdocs.yml
Adds docs to describe + document lambda invocation functions
=> docs: add documentation for using lambda functions

docs/faq.md, docs/operate-and-deploy/installation/installing.md
From https://github.com/confluentinc/ksql/pull/7173.
* adds java 8 11 compatibility note
* adds java 8 11 compatibility note in supported versions
* Update docs/faq.md
* Update docs/operate-and-deploy/installation/installing.md
Co-authored-by: Chittaranjan Prasad <>
=> docs: cherry-pick: adds java 8 and java 11 compatibility note for ksqlDB (DOCS-7387)

docs/faq.md, docs/operate-and-deploy/installation/installing.md
From https://github.com/confluentinc/ksql/pull/7173.
* adds java 8 11 compatibility note
* adds java 8 11 compatibility note in supported versions
* Update docs/faq.md
* Update docs/operate-and-deploy/installation/installing.md
Co-authored-by: Chittaranjan Prasad <>
=> docs: cherry-pick: adds java 8 and java 11 compatibility note for ksqlDB (DOCS-7388)

docs/faq.md, docs/operate-and-deploy/installation/installing.md
From https://github.com/confluentinc/ksql/pull/7173.
* adds java 8 11 compatibility note
* adds java 8 11 compatibility note in supported versions
* Update docs/faq.md
* Update docs/operate-and-deploy/installation/installing.md
Co-authored-by: Chittaranjan Prasad <>
=> docs: cherry-pick: adds java 8 and java 11 compatibility note for ksqlDB (DOCS-7389)

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/InListEvaluator.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/LambdaVariable.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/VisitParentExpressionVisitor.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/TermCompiler.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/CoercionUtil.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/util/CoercionUtilTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/transform-array_-_transform_a_list_into_compatible_mismatching_struct_elements/7.0.0_1615242034422/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/transform-array_-_transform_a_list_into_compatible_mismatching_struct_elements/7.0.0_1615242034422/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/transform-array_-_transform_a_list_into_compatible_mismatching_struct_elements/7.0.0_1615242034422/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/transform-array.json, ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-complex-lambda.json
We need to pass lambda type mappings to coercion util which uses ExpressionTypeManager.
Unit test and QTT
=> fix: incorporate lambdas into CoercionUtil and change LambdaVariable from Literal to Expression

bin/ksql-migrations, config/ksql-migrations-log4j.properties, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/BaseCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsDirectoryUtil.java, ksqldb-tools/src/main/resources/log4j.properties, ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsParsingTest.java, ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommandTest.java, ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/MigrationsDirectoryUtilTest.java
Fixes https://github.com/confluentinc/ksql/issues/7200
Fixes https://github.com/confluentinc/ksql/issues/7199
Fixes https://github.com/confluentinc/ksql/issues/7197
Unit tests added.
=> chore(migrations): more misc. fixes/improvements to migrations tool

build-tools/pom.xml, ksqldb-api-client/pom.xml, ksqldb-api-reactive-streams-tck/pom.xml, ksqldb-benchmark/pom.xml, ksqldb-cli/pom.xml, ksqldb-common/pom.xml, ksqldb-console-scripts/pom.xml, ksqldb-docker/pom.xml, ksqldb-engine-common/pom.xml, ksqldb-engine/pom.xml, ksqldb-etc/pom.xml, ksqldb-examples/pom.xml, ksqldb-execution/pom.xml, ksqldb-functional-tests/pom.xml, ksqldb-metastore/pom.xml, ksqldb-package/pom.xml, ksqldb-parser/pom.xml, ksqldb-rest-app/pom.xml, ksqldb-rest-client/pom.xml, ksqldb-rest-model/pom.xml, ksqldb-rocksdb-config-setter/pom.xml, ksqldb-serde/pom.xml, ksqldb-streams/pom.xml, ksqldb-test-util/pom.xml, ksqldb-tools/pom.xml, ksqldb-udf-quickstart/pom.xml, ksqldb-udf/pom.xml, ksqldb-version-metrics-client/pom.xml, licenses/licenses.html, pom.xml
This reverts commit 60ebe90d2aa8fecc66e80239aacf0a49a81d8a5d.
revert the revert (,:
=> chore: re-do Bump Confluent to 7.0.0-0, Kafka to 7.0.0-0

docs/developer-guide/ksqldb-reference/insert-values.md
=> chore: clarify that insert into does not support tombstones

docs/concepts/performance-guidelines.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7221.
=> docs: cherry-pick: performance best practices topic (DOCS-7491)

docs/concepts/performance-guidelines.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7221.
* docs: draft performance best practices topic (DOCS-7488)
* docs: add links + another edit pass
=> docs: cherry-pick: performance best practices topic (DOCS-7493)

docs/developer-guide/ksqldb-reference/aggregate-functions.md
From https://github.com/confluentinc/ksql/pull/7236.
=> docs: cherry-pick: fix since version for STDDEV_SAMP function (DOCS-7523)

docs/operate-and-deploy/index.md, docs/operate-and-deploy/migrations-tool.md, docs/reference/migrations-tool-configuration.md, docs/reference/server-configuration.md, mkdocs.yml
As the title says. Here's a staged version for easier viewing: https://github.com/vcrfxia/ksql/blob/migrations-docs/docs/operate-and-deploy/migrations-tool.md
=> docs(migrations): add docs for migrations tool

docs/developer-guide/ksqldb-reference/insert-into.md
From https://github.com/confluentinc/ksql/pull/7245.
=> docs: cherry-pick: Update insert-into.md (DOCS-7538)

docs/developer-guide/ksqldb-reference/insert-into.md
From https://github.com/confluentinc/ksql/pull/7245.
=> docs: cherry-pick: Update insert-into.md (DOCS-7539)

docs/developer-guide/ksqldb-reference/insert-into.md
From https://github.com/confluentinc/ksql/pull/7245.
=> docs: update insert-into.md (DOCS-7540)

docs/developer-guide/ksqldb-reference/insert-into.md
From https://github.com/confluentinc/ksql/pull/7245.
=> docs: update insert-into.md (DOCS-7542)

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java
=> chore: bump version for 0.17

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java
bump to prep for 0.18, will _not_ need to be bumped before 0.18 but will be bumped _after_ to prep for 0.19
=> chore: bump ksql version for 0.17

scripts/changelog/process_commit_files.py
The changelog generator script isn't properly handling cherrypicked commits since cherrypicking causes the git SHA to differ on the cherrypicked branch, and this SHA appears in the changelog row generated for the commits (see https://github.com/confluentinc/ksql/pull/7227#discussion_r594755247 for context). This PR fixes the script to handle this by comparing commits for equality only on the prefix up to the first open parenthesis (if present) in the commit string.
Ran the script to generate the 0.16 changelog before and after the changes in this PR and verified that the output changes were as expected.
=> chore: fix changelog generator to handle cherry-picked commits

ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
MigrationsTest is currently flaky in that if the migrations metadata table is not yet ready to serve pull queries, an error will be returned from `RestIntegrationTestUtil.makeQueryRequest()` when a pull query is issued, which exits the `assertThatEventually()` call rather than triggering a retry as desired. This PR fixes the flakiness by wrapping the pull query request in order to avoid this and allow the retry mechanism to work as intended.
=> test: fix MigrationsTest to not fail while waiting for pull query materialization

ksqldb-version-metrics-client/pom.xml
No behavior changes. This is to upgrade one dependency version to get rid of CVE.
Ref SEC-1974
Rely on existing tests.
=> chore: Sync apache.httpcomponents.version

docs/reference/metrics.md
Related: https://github.com/confluentinc/ksql/pull/7270
=> docs: update pull query metrics names in live branch (DOCS-7597)

docs/reference/metrics.md
From: https://github.com/confluentinc/ksql/pull/7280
Related: https://github.com/confluentinc/ksql/pull/7270
=> docs: cherry-pick: update pull query metrics names in live branch (DOCS-7598)

docs/reference/metrics.md
From: https://github.com/confluentinc/ksql/pull/7280
Related: https://github.com/confluentinc/ksql/pull/7270
=> docs: cherry-pick: update pull query metrics names in live branch (DOCS-7599)

docs/reference/metrics.md
From: https://github.com/confluentinc/ksql/pull/7280
Related: https://github.com/confluentinc/ksql/pull/7270
=> docs: cherry-pick: update pull query metrics names in live branch (DOCS-7600)

docs/reference/metrics.md, ksqldb-engine/src/main/java/io/confluent/ksql/internal/PullQueryExecutorMetrics.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryMetricsTest.java
Same as https://github.com/confluentinc/ksql/pull/7270 but for 6.2.x
Also updated the pull query bean string to that of the new metric naming convention
=> chore: update pull query metrics naming 

ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/5.5.0_1581572086154/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1585182000596/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1585912758104/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1588893905811/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1589910852463/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1594233263741/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/5.5.0_1581572086189/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1585182000661/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1585912758148/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1588893905952/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1589910852673/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1594233263917/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/5.5.0_1581572086226/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1585182000710/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1585912758193/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1588893906070/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1589910852780/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1594233264114/spec.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/collect-list.json
Cf. https://issues.apache.org/jira/browse/KAFKA-12508
=> test: fix QTT tests after upstream change

docs/developer-guide/ksqldb-clients/java-client.md, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/ConnectorInfo.java
Docs for the following java client functions: serverInfo, createConnector, dropConnector, listConnectors and describeConnector.
=> docs: add docs for serverInfo and connector functions in java client

ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/5.5.0_1581572086154/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1585182000596/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1585912758104/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1588893905811/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_AVRO/6.0.0_1589910852463/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/5.5.0_1581572086189/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1585182000661/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1585912758148/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1588893905952/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_JSON/6.0.0_1589910852673/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/5.5.0_1581572086226/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1585182000710/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1585912758193/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1588893906070/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/collect-list_-_collect_list_string_table_-_PROTOBUF/6.0.0_1589910852780/spec.json
This reverts commit 2d60e371e849e403320683317e4c3bb67d5dea30.
=> fix: Revert "test: fix QTT tests after upstream change (#7294)"

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/ConnectorInfo.java
=> chore: fix checkstyle indentation in ConnectorInfo

docs/developer-guide/ksqldb-clients/java-client.md
This was originally in #7266, but was moved here so that this method could be documented for 0.16
=> docs: add docs for java client serverInfo method

design-proposals/klip-38-variable-substitution.md
=> docs: add details for java client to klip-38

docs/reference/processing-log.md
From https://github.com/confluentinc/ksql/pull/7313.
=> docs: fix example CREATE query for processing log (DOCS-7687)

docs/reference/processing-log.md
From https://github.com/confluentinc/ksql/pull/7313.
=> docs: fix example CREATE query for processing log (DOCS-7688)

docs/reference/processing-log.md
From https://github.com/confluentinc/ksql/pull/7313.
=> docs: fix example CREATE query for processing log (DOCS-7689)

docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md, docs/developer-guide/ksqldb-rest-api/streaming-endpoint.md
docs for changes made in #7271
=> docs: add documentation for variable substitution in /ksql and /query-stream

ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/StreamsTaskMetadata.java, pom.xml
make a returned type public so I can use it in HC
=> fix: Make topic offset public

docs/developer-guide/ksqldb-reference/select-pull-query.md
adds info about pull queries on derived table
=> docs: adds info about pull queries on derived table

README.md, docs/concepts/apache-kafka-primer.md, docs/concepts/events.md, docs/index.md, docs/operate-and-deploy/installation/installing.md, docs/reference/sql/data-definition.md, ksqldb-common/src/main/java/io/confluent/ksql/util/WelcomeMsgUtils.java, ksqldb-common/src/test/java/io/confluent/ksql/util/WelcomeMsgUtilsTest.java
Makes changes to tagline to match Confluent's updates.
Checked both the splash screens from the CLI/Server to make sure they looked good
=> docs: tagline updates

ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json, ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java, ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java
=> fix: append additional fields to row values in `KsqlMaterialization.java` to fix pull query filtering

docs/developer-guide/ksqldb-clients/java-client.md, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java, ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ConnectorCommandResponseHandler.java, ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java, ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
Adds the functions `define(variable, value)`, `undefine(variable)` and `showVariables()`, and passes session variables to requests.
integration + unit tests
=> feat: enable variable substitution for java client

docs/developer-guide/api.md, docs/developer-guide/ksqldb-rest-api/cluster-status-endpoint.md, docs/operate-and-deploy/installation/cli-config.md, docs/reference/server-configuration.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7338 and https://github.com/confluentinc/ksql/pull/7339.
=> docs: cherry-pick new content on ksqlDB CLI usage and /clusterStatus endpoint (DOCS-7777)

docs/developer-guide/api.md, docs/developer-guide/ksqldb-rest-api/cluster-status-endpoint.md, docs/operate-and-deploy/installation/cli-config.md, docs/reference/server-configuration.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7338 and https://github.com/confluentinc/ksql/pull/7339.
=> docs: cherry-pick: add content on ksqlDB CLI usage (DOCS-7779)

docs/operate-and-deploy/installation/upgrading.md
=> docs: add steps for in-place upgrades

scripts/changelog/README.md
The changelog instructions assume that the previous release is out of the gate which we can't necessarily bank on. This adds a note to consider how far along the previous release is before generating the changelog
=> chore: update changelog generation instructions

docs/reference/server-configuration.md
* docs: doc the compression type config (DOCS-7707)
* docs: add section for ksql.compression.type
* docs: add default values and mention INSERT INTO
* docs: remove redundant note about CCloud
=> docs: cherry-pick: doc the compression type config (DOCS-7798)

docs/reference/server-configuration.md
From https://github.com/confluentinc/ksql/pull/7354.
* docs: doc the compression type config (DOCS-7707)
* docs: add section for ksql.compression.type
* docs: add default values and mention INSERT INTO
* docs: remove redundant note about CCloud
=> docs: cherry-pick: doc the compression type config (DOCS-7799)

docs/reference/server-configuration.md
From https://github.com/confluentinc/ksql/pull/7354.
* docs: doc the compression type config (DOCS-7707)
* docs: add section for ksql.compression.type
* docs: add default values and mention INSERT INTO
* docs: remove redundant note about CCloud
=> docs: cherry-pick: doc the compression type config (DOCS-7800)

Jenkinsfile, build-packages.sh, smoke/common/test.sh, smoke/deb/Dockerfile, smoke/run_smoke.sh
Adds a smoke tests for deb packages.  This test:
- Installs packages for zookeeper and kafka
- Installs the deb package
- starts all three services
- Runs some simple ksql queries for creating a stream, table
- Runs a push query
- Runs a pull query
This is a test!
=> test: Adds smoke tests to the packaging for debs

ksqldb-tools/pom.xml, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java, ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsUtil.java, ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommandTest.java, ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/CommandParserTest.java
Switch to Java api to execute `CREATE CONNECTOR` and `DROP CONNECTOR`. 
Updated unit tests, existing integration test still passes
=> chore: remove old rest client from migrations tool

Jenkinsfile, smoke/common/test.sh, smoke/rpm/Dockerfile, smoke/rpm/confluent.repo, smoke/run_smoke.sh, smoke/tgz/Dockerfile
Adds more packaging tests.  This is an extension of https://github.com/confluentinc/ksql/pull/7332
Ran tests!
=> test: Adds more packaging tests for tar.gz and rpm

docs/developer-guide/ksqldb-reference/aggregate-functions.md
=> docs: add examples for TOPK and TOPKDISTINCT

docs/requirements.txt, pom.xml
This PR updates dependency versions
=> chore: updates dependency versions

docs/operate-and-deploy/changelog.md
From https://github.com/confluentinc/ksql/pull/7396.
=> docs: cherry-pick link to 0.17.0 changelog (DOCS-7902)

docs/developer-guide/ksqldb-reference/operators.md, docs/developer-guide/ksqldb-reference/select-push-query.md
Add a WHERE expression syntax to the operators.md document.
=> docs: add WHERE expression syntax to operators.md

docs/developer-guide/ksqldb-reference/operators.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/7389.
=> docs: cherry-pick: add WHERE expression syntax to operators.md (DOCS-7910)

docs/developer-guide/ksqldb-reference/operators.md, docs/developer-guide/ksqldb-reference/select-push-query.md
From https://github.com/confluentinc/ksql/pull/7389.
=> docs: cherry-pick: add WHERE expression syntax to operators.md (DOCS-7911)

build-packages.sh
change the naming so it's `0.v.0` instead of `0.v.0-1` for maven and docker
=> chore: fix maven + docker version naming

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java, ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java, ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopologyTestDriverContainer.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorTest.java, ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorUtilTest.java
=> test: fix TopologyTestDriverContainer to use new TTD methods

design-proposals/README.md
=> docs: intent for klip-46: date and time data type support

pom.xml
revert back to nano versioning
=> fix: revert schema registry version

build-packages.sh
=> chore: fix rpm to use the right maven versions for candidates and releases

docs/concepts/lambda-functions.md, mkdocs.yml
Also updates the Streams release tag, `kstreamsbetatag`.
=> docs: fix link to lambdas how-to (DOCS-7971)

docs/concepts/lambda-functions.md
From https://github.com/confluentinc/ksql/pull/7436.
=> docs: cherry-pick: fix link to lambdas how-to (DOCS-7972)

docs/concepts/lambda-functions.md, mkdocs.yml
From https://github.com/confluentinc/ksql/pull/7436 to 0.18.x-ksqldb.
=> docs: fix link to lambdas how-to (DOCS-7971) (#7436)

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java
update command version for next release
=> chore: bump command version 6 (0.18.0) to command version 7 (0.19.0)

docs/reference/server-configuration.md
From https://github.com/confluentinc/ksql/pull/7448.
=> docs: cherry-pick: update default compression type to snappy (DOCS-8007)

docs/reference/server-configuration.md
From https://github.com/confluentinc/ksql/pull/7448.
=> docs: cherry-pick: update default compression type to snappy (DOCS-8009)

ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/KTableHolder.java, ksqldb-parser/src/main/java/io/confluent/ksql/util/QueryGuid.java, ksqldb-parser/src/test/java/io/confluent/ksql/util/QueryGuidTest.java, ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/JoinParamsFactory.java
Minor cleanup on variable names. Fix flaky test (we need to "mock" the time.)
=> chore: minor cleanup and flaky test fix

docs/operate-and-deploy/migrations-tool.md
Add space above list so that the list renders as a list.
=> docs: render list in migrations docs properly

design-proposals/README.md, design-proposals/klip-46-date-and-time-data-type-support.md
KLIP for adding support for date and time types.
=> docs(klip-46): date and time data type support

docs/operate-and-deploy/installation/install-ksqldb-with-docker.md
Add some docs about classpath/volume mounts
n/a
=> docs: add some information to the docker docs

docs/concepts/queries.md
From https://github.com/confluentinc/ksql/pull/7467.
=> docs: cherry-pick: update statement about pull queries in 0.17.0 (DOCS-8071)

docs/concepts/queries.md
From https://github.com/confluentinc/ksql/pull/7467.
=> docs: cherry-pick: update statement about pull queries in 0.17.0 (DOCS-8072)

pom.xml
This is a temporary change in the kafka.version to fix the master branch from changes introduced in the latest kafka stream artifacts. These incompatible changes are related to the new left/outer join semantics.
=> chore: fixes the master branch temporary by using an old kafka version

design-proposals/README.md
=> docs: intent for klip-47: NON NULL columns and component types

docs/faq.rst, docs/installation/index.rst, docs/installation/installing.rst, docs/installation/server-config/config-reference.rst, docs/installation/server-config/integrate-ksql-with-confluent-control-center.rst, docs/installation/server-config/security.rst
=> Make link absolute

docs/installation/server-config/integrate-ksql-with-confluent-control-center.rst
=> Make link to Cloud docs absolute

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java, ksqldb-engine/src/main/java/io/confluent/ksql/internal/PullQueryExecutorMetrics.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryMetricsTest.java
Changes tag names for pull query metrics.
=> chore: Change pull query tag names to be shorter and less redundant

design-proposals/README.md
Intent to add KLIP-48: Schemas
=> docs: intent for KLIP-48: Schemas

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java, ksqldb-engine/src/main/java/io/confluent/ksql/internal/PullQueryExecutorMetrics.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryMetricsTest.java
=> chore: Renames one more tag to remove redundant naming

design-proposals/README.md
Add source table materialization KLIP
=> docs: intent for KLIP-49: source table materialization

ksqldb-rest-app/src/main/java/io/confluent/ksql/logging/query/QueryAnonymizingRewritePolicy.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/logging/query/QueryAnonymizingRewritePolicyTest.java
This follows up on Sergio's PR and encodes the desired behaviour in test
This adds test coverage
=> chore(ksql): add a test for NPE in QueryAnonymizingRewritePolicyTest

docs/how-to-guides/use-lambda-functions.md
@wcarlson5 found some bugs when trying to follow the lambda tutorial, so I addressed those.
Additionally, if you want to run through all parts of the tutorial, it makes sense to name the streams + topics different things instead of reusing the same name over and over
https://confluentinc.atlassian.net/browse/DOCS-8217
https://confluentinc.atlassian.net/browse/DOCS-8216
=> docs: update lambda tutorial with fixes

docs/how-to-guides/use-lambda-functions.md
=> docs: update lambda tutorial with fixes (#7497)

docs/index.md, docs/stylesheets/extra.css
From https://github.com/confluentinc/ksql/pull/7513.
=> docs: cherry-pick: make getting started button clearer (DOCS-8228)

docs/index.md, docs/stylesheets/extra.css
From https://github.com/confluentinc/ksql/pull/7513.
=> docs: cherry-pick: make getting started button clearer (DOCS-8229)

docs/developer-guide/ksqldb-clients/index.md
=> docs: add .NET client

ksql-common/src/test/java/io/confluent/ksql/util/timestamp/TimestampExtractionPolicyFactoryTest.java, pom.xml
=> chore: Remove guava version and fix test

pom.xml
This is to update the guava version for the detected [CVE](https://confluentinc.atlassian.net/browse/KCI-405?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel).
Made sure it builts.
=> fix: updated guave version

ksqldb-functional-tests/src/test/resources/query-validation-tests/fk-join.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/fk-n-way-join.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/table-table-join.json
Many of the new tests are disabled as they will not pass until the rest of the functionality for foreign key joins is wired in. (If curious, see inline comments plus inline comments in https://github.com/confluentinc/ksql/pull/7528 for details on why.)
😎
=> test: add test coverage for FK joins

ksqldb-rest-app/pom.xml, ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java, ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java, ksqldb-version-metrics-client/pom.xml, ksqldb-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/VersionCheckerIntegrationTest.java, pom.xml
see https://github.com/confluentinc/ksql/pull/7493
=> chore: backport various CVE bumps to 6.0

debian/Makefile
Support new security patch release pattern.
Add new security suffix for packaging name. This PR need to be manually merged up to master, there will be few name conflicts needed to be resolved on 5.4.x branches.
=> minor: security patch release support

ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java, ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_table-table-table_-_inner-inner_-_aliasing/7.0.0_1621996006430/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_table-table-table_-_inner-inner_-_aliasing/7.0.0_1621996006430/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_table-table-table_-_inner-inner_-_aliasing/7.0.0_1621996006430/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json
FK-join must resolve table alias correctly.
=> chore: fix alias resolution in n-way join logic

pom.xml
fixes the build, fixes CVEs, good vibes all around
Ran `ConnectIntegrationTest`
=> chore: upgrade jersey version

docs/concepts/queries.md
cherry pick #7597 in `0.18.0-ksqldb`
=> chore: fix pull queries in https://docs/concepts/queries.md (#7597)

docs/concepts/queries.md, docs/developer-guide/ksqldb-reference/select-pull-query.md
cherry-picking https://github.com/confluentinc/ksql/pull/7532 for manual sync
=> docs: rewrite pull query docs page

docs/developer-guide/ksqldb-reference/select-pull-query.md
=> docs: nit changes in pull query docs

docs/developer-guide/ksqldb-reference/select-pull-query.md
=> docs: nit changes in pull query docs (#7605)

docs/reference/server-configuration.md
Make it obvious that you can parameterize the producer/consumers of the server.
=> docs: call out producer/consumer props

ksql-common/pom.xml, pom.xml
Update to avoid security issue in version 1.9.13
=> chore: bump jackson-mapper-asl version

ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
The test `shouldRegisterDependenciesForProtobuf` was failing because the Protobuf schema registered didn't contain the references that the test expected. I'm unsure why the reference is not added when registering the schema in `SchemaRegisterInjector.registerSchema()`. Perhaps SR decided not to add it because it is duplicated in the protobuf schema already.
=> chore: fix test issue with SchemaRegisterInjectorTest

docs/developer-guide/ksqldb-reference/quick-reference.md
From https://github.com/confluentinc/ksql/pull/7635.
=> docs: cherry-pick: fix munged SQL code blocks in Quick Reference (DOCS-8562)

CONTRIBUTING.md
Refine the IDE instructions based on feedback.
1. Ran `./mvnw clean`, reproduced the problem with missing Lexer/Parser and KsqlVersionMetrics classes.
2. Ran the new commands, then verified I can build cleanly in IDEA.
=> docs: add source generation to IDE instructions

CONTRIBUTING.md
Add note about how to run the ksql cli via Maven
I've been using this command just like it's documented here.
=> docs: add note about how to run the ksql cli via Maven

docs/concepts/queries.md
Fixes a broken doc link for pull queries.
=> docs: fixes broken pull query link

docs/concepts/queries.md
=> docs: cherry-pick: fixes broken pull query link (DOCS-8601)

docs/concepts/queries.md
=> docs: cherry-pick: fixes broken pull query link (DOCS-8598)

docs/concepts/queries.md
=> docs: cherry-pick: fixes broken pull query link (DOCS-8599)

docs/concepts/queries.md
=> docs: cherry-pick: fixes broken pull query link (DOCS-8600)

docs/reference/processing-log.md
=> docs: cherry-pick: fixes dead links for Docker (DOCS-8603)

docs/reference/processing-log.md
=> docs: cherry-pick: fixes dead links for Docker (DOCS-8604)

docs/reference/processing-log.md
=> docs: cherry-pick: fixes dead links for Docker (DOCS-8605)

docs/reference/processing-log.md
=> docs: cherry-pick: fixes dead links for Docker (DOCS-8607)

docs/concepts/queries.md
=> docs: cherry-pick: fixes broken pull query link (DOCS-8608)

docs/reference/processing-log.md
=> docs: cherry-pick: fixes dead links for Docker (DOCS-8606)

mkdocs.yml
Streams beta dependency is https://jenkins-confluent-packages-beta-maven.s3-us-west-2.amazonaws.com/7.0.0-beta210423230724/2/maven/io/confluent/common/maven-metadata.xml
=> docs: update streams beta build to correct version

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java
=> chore: bump command version after cutting 0.19

ksqldb-common/src/main/java/io/confluent/ksql/function/types/DateType.java, ksqldb-common/src/main/java/io/confluent/ksql/function/types/ParamTypes.java, ksqldb-common/src/main/java/io/confluent/ksql/function/types/TimeType.java, ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/SchemaConverters.java, ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/SqlTypeWalker.java, ksqldb-common/src/test/java/io/confluent/ksql/schema/OperatorTest.java, ksqldb-common/src/test/java/io/confluent/ksql/schema/ksql/SchemaConvertersTest.java, ksqldb-common/src/test/java/io/confluent/ksql/schema/ksql/SqlTypeWalkerTest.java, ksqldb-engine-common/src/main/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercer.java, ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/SqlTypeCodeGen.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluatorTest.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/helpers/SqlTypeCodeGenTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/util/ApiSqlValueCoercerTest.java, ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlBaseType.java, ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlPrimitiveType.java, ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlTypes.java
Adds the DATE and TIME sql types to SqlBaseType, SqlTypes etc. 
Updated the related unit tests
=> feat: add the DATE and TIME sql types

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
Disables `PullQueryRoutingFunctionalTest`
=> chore: Disable PullQueryRoutingFunctionalTest until flakiness is fixed

ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-stream-stream_-_left-left/7.0.0_1622148781471/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-stream-stream_-_left-left/7.0.0_1622148781471/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-stream-stream_-_left-left/7.0.0_1622148781471/topology, ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-stream-stream_-_outer-outer/7.0.0_1622148781105/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-stream-stream_-_outer-outer/7.0.0_1622148781105/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-stream-stream_-_outer-outer/7.0.0_1622148781105/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json
Currently the only stream-stream-stream join test coverage we have is for inner joins. This PR adds two new tests: left-left and outer-outer. I considered adding left-outer and outer-left as well but I think the additional benefit beyond what's in the PR is minimal.
=> test: additional stream-stream-stream join tests (MINOR)

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
Cherry-pick #7343 to 6.2.x branch.
=> test: retries for known flaky RestApiTest (#7343)

docs/concepts/time-and-windows-in-ksqldb-queries.md, docs/developer-guide/joins/join-streams-and-tables.md, docs/developer-guide/joins/partition-data.md
Update the docs to explain FK-join support.
n/a
=> chore: update docs for FK-joins

ksqldb-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java, ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/ConsumerTestUtil.java
Trying to fix some ITs that recently started failing. I'm not sure why they have just started. Neither reverting the code nor reverting the dependencies had any effect, but increasing the timeout does.
Ran the integration tests.
=> fix: longer IT timeouts

docs/how-to-guides/create-a-user-defined-function.md
The phrase `(UDF for short)` appears in two places. The second is redundant, and kinda confusing as it implies 'UDF' is short for 'scalar function'.
=> Removing a duplicated clause.

docs/index.md
Links to the two other quickstarts on the home page.
=> Additional quickstarts

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQuerySingleNodeFunctionalTest.java
Disables test `PullQuerySingleNodeFunctionalTest.restoreAfterClearState`
=> chore: Disable flakey/failing test in PullQuerySingleNodeFunctionalTest

docs/developer-guide/joins/join-streams-and-tables.md
From https://github.com/confluentinc/ksql/pull/7677.
=> docs: cherry-pick: fixes example code docs typo (DOCS-8699)

docs/developer-guide/joins/join-streams-and-tables.md
From https://github.com/confluentinc/ksql/pull/7679.
=> docs: cherry-pick: fixes example code docs typo (DOCS-8700)

docs/developer-guide/joins/join-streams-and-tables.md
From https://github.com/confluentinc/ksql/pull/7679.
=> docs: cherry-pick: fixes example code docs typo (DOCS-8701)

docs/developer-guide/joins/join-streams-and-tables.md
From https://github.com/confluentinc/ksql/pull/7677.
=> docs: cherry-pick: fixes example code docs typo (DOCS-8703)

docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/insert-into.md, docs/developer-guide/ksqldb-reference/quick-reference.md, docs/developer-guide/ksqldb-reference/select-push-query.md
^ Updates the docs to include GRACE PERIOD on join syntax
=> docs: update join docs with GRACE PERIOD syntax

docs/developer-guide/joins/partition-data.md, docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md
Also, add a few headings for a bit of structure.
Also, fixes https://github.com/confluentinc/ksql/issues/7705:
=> docs: add notes about partitioning to CREATE* reference topics (KCI-513 and DOCS-8774)

docs/developer-guide/joins/partition-data.md, docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md
From https://github.com/confluentinc/ksql/pull/7703.
* docs: add notes about partitioning to CREATE* reference topics
* docs: fix list markdown in CREATE * AS SELECT  topic (DOCS-8774)
* docs: add note about changing partition count, per feedback
* docs: fix a typo
=> docs: cherry-pick: add notes about partitioning to CREATE* ref topics (KCI-513 and DOCS-8774)

docs/developer-guide/joins/partition-data.md, docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md
From https://github.com/confluentinc/ksql/pull/7703.
* docs: add notes about partitioning to CREATE* reference topics
* docs: fix list markdown in CREATE * AS SELECT  topic (DOCS-8774)
* docs: add note about changing partition count, per feedback
* docs: fix a typo
=> docs: cherry-pick: add notes about partitioning to CREATE* reference topics (KCI-513, DOCS-8774, DOCS-8795)

docs/developer-guide/joins/partition-data.md, docs/developer-guide/ksqldb-reference/create-stream-as-select.md, docs/developer-guide/ksqldb-reference/create-stream.md, docs/developer-guide/ksqldb-reference/create-table-as-select.md, docs/developer-guide/ksqldb-reference/create-table.md
From https://github.com/confluentinc/ksql/pull/7703.
* docs: add notes about partitioning to CREATE* reference topics
* docs: fix list markdown in CREATE * AS SELECT  topic (DOCS-8774)
* docs: add note about changing partition count, per feedback
* docs: fix a typo
=> docs: cherry-pick: add notes about partitioning to CREATE* reference topics (KCI-513, DOCS-8774, DOCS-8796)

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java, ksqldb-common/src/main/java/io/confluent/ksql/util/timestamp/PartialStringToTimestampParser.java, ksqldb-engine-common/src/main/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercer.java, ksqldb-engine-common/src/main/java/io/confluent/ksql/schema/ksql/SqlTimeTypes.java, ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java, ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/SqlTimeTypesTest.java, ksqldb-engine/src/main/java/io/confluent/ksql/engine/generic/GenericExpressionResolver.java, ksqldb-engine/src/test/java/io/confluent/ksql/engine/generic/GenericExpressionResolverTest.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java, ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluator.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java, ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluatorTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/util/ApiSqlValueCoercerTest.java, ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlBaseType.java
Adds casting/coercion for DATE/TIME, as well as parsers for STRING to DATE/TIME. 
Unit tests
=> feat: implement casting for DATE/TIME

ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java, ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/RestoreCommandTopicIntegrationTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java, ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
=> adding testing for cleaning state stores

ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
Add unit test to ensure correct behavior is preserved, described in #5873 
Added test to rqtt
=> test: add test for descriptive error message when duplicate columns are found in a pull query

docs/operate-and-deploy/installation/server-config/security.md
=> docs: update security docs for ssl.client.auth deprecation (DOCS-8732)

ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_out_of_order_-_explicit_grace_period/6.0.0_1591102310430/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/session-windows_-_out_of_order_-_explicit_grace_period/7.0.0_1618294688664/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/suppress_-_should_support_final_results_for_session_windows/6.1.0_1595998101485/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/suppress_-_should_support_final_results_for_session_windows/7.0.0_1618294694168/spec.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/session-windows.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/suppress.json
Fixes tests after https://issues.apache.org/jira/browse/KAFKA-12718
Ran tests locally
=> test: Fixes build with updates to sessions window tests

docs/developer-guide/ksqldb-reference/scalar-functions.md, docs/developer-guide/ksqldb-reference/type-coercion.md, docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md, docs/reference/serialization.md, docs/reference/sql/appendix.md, docs/reference/sql/data-types.md, docs/reference/user-defined-functions.md
Adds information on:
* date/time serializarion
* casting and type coercion
* overall description on what the types are
=> docs: add documentation about DATE/TIME data types

docs/developer-guide/ksqldb-reference/scalar-functions.md, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/TimeAdd.java, ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/TimeSub.java, ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/TimeAddTest.java, ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/TimeSubTest.java, ksqldb-functional-tests/src/test/resources/historical_plans/timeadd_-_adds/7.0.0_1624587222167/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/timeadd_-_adds/7.0.0_1624587222167/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/timeadd_-_adds/7.0.0_1624587222167/topology, ksqldb-functional-tests/src/test/resources/historical_plans/timeadd_-_adds_negative_intervals/7.0.0_1624587222218/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/timeadd_-_adds_negative_intervals/7.0.0_1624587222218/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/timeadd_-_adds_negative_intervals/7.0.0_1624587222218/topology, ksqldb-functional-tests/src/test/resources/historical_plans/timeadd_-_handles_null_values/7.0.0_1624587222266/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/timeadd_-_handles_null_values/7.0.0_1624587222266/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/timeadd_-_handles_null_values/7.0.0_1624587222266/topology, ksqldb-functional-tests/src/test/resources/historical_plans/timesub_-_handles_null_values/7.0.0_1624587224628/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/timesub_-_handles_null_values/7.0.0_1624587224628/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/timesub_-_handles_null_values/7.0.0_1624587224628/topology, ksqldb-functional-tests/src/test/resources/historical_plans/timesub_-_subtracts/7.0.0_1624587224517/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/timesub_-_subtracts/7.0.0_1624587224517/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/timesub_-_subtracts/7.0.0_1624587224517/topology, ksqldb-functional-tests/src/test/resources/historical_plans/timesub_-_subtracts_negative_intervals/7.0.0_1624587224581/plan.json, ksqldb-functional-tests/src/test/resources/historical_plans/timesub_-_subtracts_negative_intervals/7.0.0_1624587224581/spec.json, ksqldb-functional-tests/src/test/resources/historical_plans/timesub_-_subtracts_negative_intervals/7.0.0_1624587224581/topology, ksqldb-functional-tests/src/test/resources/query-validation-tests/timeadd.json, ksqldb-functional-tests/src/test/resources/query-validation-tests/timesub.json
^^^
The QTT tests won't pass until #7722 is merged, since it contains some changes needed to enable TIME for UDFs.
QTT + unit tests
=> feat: add TIMEADD and TIMESUB functions
