ksqldb-rest-app/src/main/java/io/confluent/ksql/logging/query/QueryAnonymizingRewritePolicy.java

I got an NPE when I started a KSQL server and didn't add the policy config.
```
(io.confluent.ksql.util.KsqlConfig:372)
[2021-05-11 15:41:58,342] ERROR Failed to start KSQL (io.confluent.ksql.rest.server.KsqlServerMain:69)
java.lang.NullPointerException
at io.confluent.ksql.logging.query.QueryAnonymizingRewritePolicy.<init>(QueryAnonymizingRewritePolicy.java:34)
at io.confluent.ksql.logging.query.QueryLogger.configure(QueryLogger.java:58)
at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:59)
(base) sergio@pop-os:~/Development/ksql$ ./bin/ksql-server-start config/ksql-server.properties
```
_Describe the testing strategy. Unit and integration tests are expected for any behavior …

chore: fix NPE in QueryAnonymizingRewritePolicy.<init>

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PreJoinProjectNode.java

Minor follow-up to https://github.com/confluentinc/ksql/pull/7491. This PR only affects foreign key joins (still under development, hidden behind a feature flag). Because https://github.com/confluentinc/ksql/pull/7491 removed the PreJoinRepartition node for foreign key joins, it's now possible that a PreJoinProject node is immediately preceded by a DataSourceNode rather than another JoiningNode. This PR updates PreJoinProject to accommodate this rather than the current behavior which is to throw an error.
Local QTT with feature flag enabled. (QTT for foreign key join still does not pass since the feature isn't complete yet, but the previous error that was thrown in PreJoinProject is no longer thrown.)

chore: update joins to allow lack of pre-join repartition (MINOR)

---

docs/index.md
docs/stylesheets/extra.css

Can't hurt to make it easier to start. :)

docs: make getting started button clearer

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/fk-join.json

Three minor changes in this PR:
- disallows foreign key joins in n-way joins, for this first iteration of FK joins. Note that it's fine if a chain of n-way joins starts with an FK join (as processed from left to right), but not if an FK join is encountered later on in the chain.
- adds versions of the existing FK joins tests (all negative test cases, as the functionality is not yet complete) with the feature flag enabled
- updates the existing negative test case for FK joins as part of an n-way join to have the FK join as the second join in the chain, rather than the first, in light of the note above
Tests pass.

chore: disallow FK joins in n-way joins (MINOR)

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java

since the state ERROR changed definitions the current isError is no longer really relevant. However it actually seems that isError is not used so I will just remove it._

fix: change the isError to not use the state

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java

Signed-off-by: Arjun Satish <arjun@confluent.io>
ksqldb java client can extend the java.io.closeable interface. 
clean run of unit tests.

chore: ksqlDB java client can extend Closeable

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/common/operators/AbstractPhysicalOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/common/operators/PhysicalOperatorUtil.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/common/operators/ProjectOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/common/operators/SelectOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/common/operators/UnaryPhysicalOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlan.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlanBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/KeyedTableLookupOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/KeyedWindowedTableLookupOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/TableScanOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/WindowedTableScanOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushPhysicalPlan.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushPhysicalPlanBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/operators/PeekStreamOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/operators/PushDataSourceOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/KeyConstraint.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryFilterNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryLogicalPlanUtil.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryProjectNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/common/operators/ProjectOperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/common/operators/SelectOperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/operators/KeyedWindowedTableLookupOperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/PushPhysicalPlanBuilderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/PushPhysicalPlanTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/operators/PeekStreamOperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/QueryFilterNodeTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/QueryProjectNodeTest.java

This adds the Scalable Push Query physical operators.  It introduces an operator `PeekStreamOperator` which registers a `ProcessingQueue` with the `ScalablePushRegistry`. This new operator is combined with existing pull query operators such as `ProjectOperator` and `SelectOperator` to create a full query execution.  These operators are created with newly introduced `PushPhysicalPlanBuilder`, which then creates a `PushPhysicalPlan` which actually does the execution.
Note that `PushPhysicalPlan` executes async on a Vert.x `Context`.  The idea is that all of the passing of rows doesn't require any dedicated threads, and so many requests can be executing at once and be long-running without taxing threadpools.
Also, this PR includes moving those common operators that are now used by both pull …

feat: Adds Scalable Push Query physical operators

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/QueryStateMetricsReportingListener.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/QueryStateMetricsReportingListenerTest.java

Sometimes when queries close the closing thread times out and leaves behind
the cleanup thread in streams. Then, this thread calls the state change callback
which causes our metrics listener to throw an NPE. This patch changes the listener
to deal with this case by checking for null values

fix: npe on transient query close

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/QueryStateMetricsReportingListener.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/QueryStateMetricsReportingListenerTest.java

Sometimes when queries close the closing thread times out and leaves behind
the cleanup thread in streams. Then, this thread calls the state change callback
which causes our metrics listener to throw an NPE. This patch changes the listener
to deal with this case by checking for null values
Cherry-pick #7530

fix: npe on transient query close (#7530)

---

docs/developer-guide/ksqldb-rest-api/info-endpoint.md
docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md
docs/developer-guide/ksqldb-rest-api/query-endpoint.md

Some versions of `curl` defaults to HTTP2, which not all our APIs support.
To avoid confusion, we can just specify HTTP1.1 in the docs.
I spun up a local ksql cluster using the quickstart and issued all the curl commands in this changeset.
I also generated the docs and verified the formatting.

docs: specify HTTP1.1 for curl

---

docs/developer-guide/ksqldb-rest-api/query-endpoint.md

KLIP-15 proposed to deprecate the `/query` endpoint, which is commonly understood
by some, but never documented nor widely discussed. This adds a callout to the docs
so that new users can be more informed.
I built the docs locally and verified the appearance and the links.

docs: document query API deprecation

---

ksql-cli/src/test/java/io/confluent/ksql/cli/BasicAuthFunctionalTest.java

This is a partial backport of @niteshmor's https://github.com/confluentinc/ksql/pull/6702/ back to `5.2.x`. It's only partial because only 1 of the 4 main changes actually apply here.
- In `5.2.x`, the 2 changed POMs don't have the dependency from which Jetty is excluded, and the integration test doesn't exist.
Just like [its sibling change in the blueway repo](https://github.com/confluentinc/blueway/pull/2258), this change is needed because of the CVE fixes in confluentinc/rest-utils#252 and confluentinc/rest-utils#253 - the `rest-utils` changes will be breaking without this.
The change is also missing from 5.3.x, but it's probably best to merge it with `-s ours` from here up and to post a separate PR with a full cherry-pick of the #6702 changes into `5.3.x` (which again should be merged …

Use Java's Base64 instead of Jersey's.

---

ksql-cli/src/test/java/io/confluent/ksql/cli/BasicAuthFunctionalTest.java
ksql-engine/pom.xml
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java

This is a cherry-pick of @niteshmor's https://github.com/confluentinc/ksql/pull/6702 back to `5.3.x`. Unlike the similar change in `5.2.x` (see #7534), this is almost identical to Nitesh's original change.
Just like its sibling changes for `5.2.x` and [in the blueway repo](https://github.com/confluentinc/blueway/pull/2258), this change is needed because of the CVE fixes in confluentinc/rest-utils#252 and confluentinc/rest-utils#253 - the rest-utils changes will be breaking without this.
- `mvn clean package -DskipTests` for the build
- `mvn -f ksql-rest-app/pom.xml -Dit.test=ClusterTerminationTest,KsqlResourceFunctionalTest,RestApiTest test-compile failsafe:integration-test` for the test utility

Backport "fix: use Java's Base64 instead of jersey's (#6702)"

---

docs/reference/server-configuration.md

The documentation for key UDF configs was missing:
1. the directory where UDFs must be uploaded
2. the pattern for passing configs to UDFs
I built the docs and verified the formatting as well as the hyperlink.

docs: document UDF configs

---

ksql-cli/src/test/java/io/confluent/ksql/cli/SslFunctionalTest.java

~Replaced a usage of the default `SslContextFactory` ctor in order to avoid a warning that breaks the build once Jetty is bumped so that the ctor is deprecated.~
I have replaced the fix with a warning suppression, so that this change can be merged proactively. The previous fix is better in theory, but it can be merged only after the `rest-utils` changes have been merged (so it also breaks CI right now).
- This is not a problem on `5.3.x` and above, so this change needs to land solely here. We should merge it up with `pint merge -s ours ksql`. **I actually don't have the permissions to do that, so I'll have to ask the reviewers to help me with this**.
- I didn't cherry-pick the changes fixing this in `5.3.x` as they are slightly messy (there are 2 commits for this, and there's a redundant …

chore: KREST-1030 suppress deprecated usage of SslContextFactory

---

design-proposals/klip-50-partition-and-offset-in-ksqldb.md

KLIP 50: proposal for exposing partition and offset in ksqlDB. Here's a rendered version for easier viewing: https://github.com/vcrfxia/ksql/blob/klip-50/design-proposals/klip-50-partition-and-offset-in-ksqldb.md

docs(klip-50): partition and offset in ksqlDB

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/fk-join.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/table-table-join.json

Add a check to disallow OUTER join for FK-joins.
Add new tests for FK-joins with "flipped" join condition. Luckily `JoinTree.build()` take care of the order by calling `join.flip()` if necessary, and thus we don't need to write additional code for FK-joins for this case. However, we should have the corresponding tests.
Only added tests for binary joins. Not sure if we should add tests for n-way joins at this point, as don't plan to support n-way joins yet.

test: don't allow FK-outer joins and add QTT cases for FK-join with flipped join condition

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java

The build is currently failing with a checkstyle error. This PR suppresses the warning for now to unblock the build. This can be revisited as part of the code cleanup planned for after foreign key joins are shipped.
Build passes.

chore: fix checkstyle build failure (MINOR)

---

ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_table_to_table_wrapped_single_field_value_schema_on_inputs/5.5.0_1581572097364/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_table_to_table_wrapped_single_field_value_schema_on_inputs/6.0.0_1588893930352/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_table_to_table_wrapped_single_field_value_schema_on_inputs/6.0.0_1589910877721/spec.json

Cherrypick of fix in 6.1.x: [#7306](https://github.com/confluentinc/ksql/pull/7306) as these three tests have been failing on 6.0.x (presumably since the emit-on-change logic was originally reverted in Streams, so almost two months)
Cf. https://issues.apache.org/jira/browse/KAFKA-12508

test: fix QTT tests after upstream change (#7306)

---

ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroDataTranslator.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/avro/AvroDataTranslatorTest.java

Fixes #7170 
If you run the following statements
```
CREATE STREAM A (dec DECIMAL(4,2)) WITH (topic='topic', value_format='AVRO');
CREATE STREAM B (dec DECIMAL(6,3)) WITH (topic='topic', value_format='AVRO');
CREATE STREAM C AS SELECT * FROM A;
INSERT INTO B VALUES (123.456);
```
You would end up with a `org.apache.kafka.common.errors.SerializationException` in the logs, instead of rejecting the value to begin with.  
And querying A would return the mismatched decimal
```
SELECT * FROM A EMIT CHANGES;
+---------+
|DEC      |
+---------+
|123.456  |
```
This PR changes the behaviour so that if there is a mismatching decimal, it first tries to convert the topic decimal to the ksql schema, and if that is impossible, then it skips that value and the logs a …

fix: reject mismatched decimals from avro topics

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/Operator.java
ksqldb-common/src/test/java/io/confluent/ksql/schema/OperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/execution/ExpressionEvaluatorParityTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/comparison-expression.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/math.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json

This PR makes the error handling better when we try to do arithmetic with `NULL`. 
```
ksql> SELECT NULL + 1 FROM s1 EMIT CHANGES;
Error processing expression (null + 1). Arithmetic on types null and INTEGER are not supported.
ksql> SELECT MAP(1 := 'cat') + NULL FROM s1 EMIT CHANGES;
Error processing expression: (MAP(1:='cat') + null). Arithmetic on types MAP<INTEGER, STRING> and null are not supported.
ksql> SELECT Array[1,2,3] + NULL FROM s1 EMIT CHANGES;
Error processing expression: (ARRAY[1, 2, 3] + null). Arithmetic on types ARRAY<INTEGER> and null are not supported.
ksql> SELECT 5.0 / NULL FROM s1 EMIT CHANGES;
Error processing expression: (5.0 / null). Arithmetic on types DECIMAL(2, 1) and null are not supported.
ksql> SELECT NULL * NULL FROM s1 EMIT CHANGES;
Error processing …
```

fix: better error message on illegal arithmetic with NULL values

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/Server.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java

Expose a config to set the server's idle timeout to work around https://github.com/confluentinc/ksql/issues/6970
Set the configuration to 5 seconds, ran the server locally, and verified that when I create a transient query on the HTTP2 API, the connection gets closed after 5 seconds of inactivity. I also verified that if I cancel my query (`Ctrl-C` on my `curl` command), the transient query gets shut down on the server.

feat: add idle timeout

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_key/5.5.0_1581572097758/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_key/6.0.0_1585912769122/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_key/6.0.0_1587575897830/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_value_column/5.5.0_1581572097800/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_value_column/6.0.0_1585912769161/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_value_column/6.0.0_1587575897905/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_value_column/6.0.0_1588893931453/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_value_column/6.0.0_1589910878677/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_value_column/6.0.0_1594233293706/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_value_column/6.1.0_1594164289267/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_on_non-STRING_value_column/7.0.0_1618294660070/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-table-table_-_explicit_ROWTIME/6.0.0_1588893939120/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-table-table_-_explicit_ROWTIME/6.0.0_1589910884946/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-table-table_-_explicit_ROWTIME/6.0.0_1594233301977/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-table-table_-_explicit_ROWTIME/6.1.0_1594164298243/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-table-table_-_explicit_ROWTIME/7.0.0_1618294677621/spec.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionFactory.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/DiscoverRemoteHostsUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/RemoteHostExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/DiscoverRemoteHostsUtilTest.java
pom.xml

As the title says. This PR contains a number of required fixes for doing so:
- Updates some stream-table join expected results, due to picking up https://github.com/apache/kafka/commit/476eccb968322879b1843dfa837b63ce386d192c
- Bumps jersey dependency version to accommodate https://github.com/apache/kafka/commit/b73d639adc9e4b5f1940d364f5ece481604b802a#diff-02b139e755ab0e27e0b0a6f9845843ef189116955cc340c49a4022587dbb2b52
- Updates DiscoverRemoteHostsUtil in order to fix a failing unit test in KsqlResourceTest
- Disables the enhancements to left and outer stream-stream joins (with regards to when nulls are emitted), since we're not ready to enable this feature in ksqlDB until the grace period is configurable.
Build passes.

chore: un-pin kafka dependency version

---

ksql-engine/src/main/java/io/confluent/ksql/function/udf/json/ArrayContainsKudf.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/ConfigTopicKeyTest.java

- backports #7562 
- pins the `ErrorHandler` code in the `KsqlRestApplication` to be backwards compatible with old versions (see inline comment for more information)
Ran the failed tests

fix: fix the 5.2.x build to be compatible with newer jetty/jackson versions

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json

Two minor fixes in this PR:
- Do not require copartitioning for foreign key joins. The existing QTTs for this (currently disabled) are now passing except for the requisite changes to the QTT framework (see https://github.com/confluentinc/ksql/pull/7576 for more).
- Disallow foreign key joins on windowed tables, since it doesn't make sense to extract a column/expression from the left source to match a windowed key from the right source. ksqlDB does not support persistent queries on windowed tables so this is only relevant for push queries, so I've added a corresponding RQTT.
Added tests. (Copartitioning tests will be enabled in a future PR.)

chore: relax copartitioning requirements for FK joins + disallow on windowed tables

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-table-table_-_qualified_select__/7.0.0_1621950302884/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-table-table_-_qualified_select__/7.0.0_1621950302884/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_stream-table-table_-_qualified_select__/7.0.0_1621950302884/topology
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_table-table-table-table_-_qualified_select__/7.0.0_1621951715025/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_table-table-table-table_-_qualified_select__/7.0.0_1621951715025/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-joins_-_table-table-table-table_-_qualified_select__/7.0.0_1621951715025/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/fk-n-way-join.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-joins.json

Fixes https://github.com/confluentinc/ksql/issues/7583.
Fixes https://github.com/confluentinc/ksql/issues/7584.
The reason for both bugs is because the current logic in `JoinNode#resolveSelectStar()` for finding data source names says "if the current node is a JoinNode, inspect its children, else use the current node". This is incorrect because
1. The current node might be neither a JoinNode nor a node corresponding to a single data source -- it might be a PreJoinRepartitionNode attached to a JoinNode. In this case, the current logic says to use the current node but the current node is not associated with any data source. As a result, some data sources are missing from the set of data source names considered when resolving the qualified select `*`.
2. Even if the current node is a …

fix: qualified select * now works in n-way joins with repartitions and multiple layers of nesting

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopicInfoCache.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java

The loop in `TestExecutor` that calls the `topicInfoCache.get()` does not do anything with the resulted topic info. Seesm it only checks the get() call works. This `get()` call is causing the errors with QTT when determining the key formats. This PR filters out those internal FK topics to allow QTT for FK joins to pass.

chore: ignore FK internal topics from QTT tests

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/ForeignKeyTableTableJoin.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/plan/ForeignKeyTableTableJoinTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/fk-n-way-join.json
ksqldb-rest-app/src/test/resources/ksql-plan-schema/schema.json
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/ForeignKeyTableTableJoinBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/KSPlanBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/TableTableJoinBuilder.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/ForeignKeyTableTableJoinBuilderTest.java

FK-joins need to set their output-format to make n-way join works. Without this fix, we fail with a `ClassCastException` because downstream operators fall back to default ByteArraySerde as no `valueSerde` is set.
All but two n-way join QQT test pass now, but as long as QTT is not fixed, we cannot enable them yet. One test fails with missing result columns (we need to fix forward in a follow up PR). The other fails with an error resolving an alias (this is fixed via #7547)
Tested locally using `fk-n-way-joins.json`

chore: fix bugs in FK n-way joins

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/fk-join.json

We should add a test that verifies that a format mismatch of left and right input does not trigger a repartitioning for FK-joins.
Added QTT test.

test: add test for FK-join with format mismatch

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/fk-join.json

We need to use the alias name (instead of the table name) if an alias exist to verify if the key column is present in the projection.
Updated existing QTT tests.

chore: fix alias resolution in n-way join logic

---

docs/concepts/queries.md

fix pull queries' description in https://docs/concepts/queries.md by deleting an entire section on `Pull query features and limitations` and just adding a link to https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/select-pull-query/ instead

chore: fix pull queries in https://docs/concepts/queries.md

---

docs/concepts/queries.md

cherry pick #7597 in `0.18.x-ksqldb`

chore: fix pull queries in https://docs/concepts/queries.md (#7597)

---

docs/developer-guide/ksqldb-reference/select-pull-query.md

Rewrite pull query docs page https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/select-pull-query/

docs: rewrite pull query docs page

---

ksql-cli/src/test/java/io/confluent/ksql/cli/SslFunctionalTest.java

From https://kafka.apache.org/21/documentation.html#upgrade_200_notable: 
The default value for ssl.endpoint.identification.algorithm was changed to https, which performs hostname verification (man-in-the-middle attacks are possible otherwise). Set ssl.endpoint.identification.algorithm to an empty string to restore the previous behaviour.

test: fix shouldNotBeAbleToUseWssIfClientDoesNotTrustServerCert test

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/PersistentQueryMetadataTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedPersistentQueryMetadataImplTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/QueryDescriptionFactoryTest.java

This PR fixes an issue when terminating an INSERT query that caused the underlying CREATE_AS query to not be terminated when dropping the stream.
i.e.
```
ksql> create stream p1 as select * from s1;
ksql> insert into p1 select * from s2;
ksql> show queries;
Query ID       | Query Type | Status    | Sink Name | Sink Kafka Topic | Query String                                                                                            
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERTQUERY_43 | PERSISTENT | RUNNING:1 | P1        | P1               | insert into p1 select * …
```

fix: DROP stream for persistent query doesn't always drop underlying query

---

ksqldb-common/src/main/java/io/confluent/ksql/util/DecimalUtil.java
ksqldb-common/src/test/java/io/confluent/ksql/util/DecimalUtilTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_DECIMAL_-_key_-_inference_-_default_precision/7.0.0_1622556612278/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_DECIMAL_-_key_-_inference_-_default_precision/7.0.0_1622556612278/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_DECIMAL_-_key_-_inference_-_default_precision/7.0.0_1622556612278/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json

Fixes https://github.com/confluentinc/ksql/issues/7429.
This PR implements the suggested change in https://github.com/confluentinc/ksql/issues/7429 to have ksqlDB mirror the Schema Registry behavior of defaulting precision for Avro decimals to 64 if not explicitly specified in the schema. This PR does _not_ change how ksqlDB generates output schemas -- the precision is still always written into the schema explicitly, even if the default of 64 was used. cc @colinhicks on whether we also want to make this additional change or not (considering potential implications for backwards incompatibility).
Added unit + integration tests.

feat: use Connect default precision for Avro decimals if unspecified (MINOR)

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java

couple fixes to query registration to avoid NPE on listing if register fails:
- notify listeners before registering the query. This ensures we don't register
on failure.
- dont do initialize as separate step from query metadata construction. There's no
reason not to just do it up front.
Added a unit test. Also tested manually by instrumenting a throw from
`QueryStateMetricsReportingListener`

fix: dont throw NPE on listing if register fails

---

.mvn/wrapper/maven-wrapper.properties
CONTRIBUTING.md

Update the wrapper to include https://github.com/confluentinc/maven/pull/1
Document what the wrapper does, and how to use it on the CLI and in IDEs
I verified the wrapper works as expected by doing:
```
mvn clean
rm -r ~/.m2/repository
./mvnw clean compile
```
This build completes in about 12 minutes with the wrapper, and takes a few hours without it. I can also visually verify that I'm not downloading extra pom files.
I also followed the documentation included in this PR to update IDEA and verified that it also doesn't resolve the extra dependencies (and that it also takes about 12 minutes to complete, instead of hours).

fix: Update Maven wrapper and document its use to fix version resolution

---

CONTRIBUTING.md

Document how to use parallel build in Maven to speed up tests.
Ran it locally. Also @agavra has been doing this for a while.

docs: document parallel build

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushRouting.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushRoutingOptions.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/TransientQueryQueue.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/PushRoutingTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/services/DisabledKsqlClient.java
ksqldb-execution/src/main/java/io/confluent/ksql/services/SimpleKsqlClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/DefaultKsqlClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/InternalKsqlClientFactory.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/ServerInternalKsqlClient.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/FaultyKsqlClient.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClientUtil.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTargetUtil.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/StreamPublisher.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientTest.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlTargetUtilTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryStreamArgs.java

The next step of scalable push queries, this adds the routing logic in `PushRouting`.
At the moment, it attempts to determine the set of hosts at start time to connect to and just sticks with them. A followup change will fail the query if there's a rebalance.
`PushRouting` does everything async, meaning that it uses the Vertx Context and CompletableFutures to handle everything, so it doesn't require a thread pool.
This also introduces a http2 client to `KsqlClient` since this is required to issue http2 requests, which this now does for the `/query-stream` requests between cluster instances.

feat: Adds Scalable Push Query Routing

---

docs/reference/processing-log.md

Found a few more dead links while fixing #7647. @JimGalasyn Can these all be merged to the live branch since they're 404?

docs: fixes dead links for Docker

---

design-proposals/klip-36-grace-stream-stream-joins.md

Updates the KLIP-36 to add GRACE PERIOD on joins with before/after windows.
i.e.
```
JOIN <stream> WITHIN (BEFORE <time unit>, AFTER <time unit>, GRACE PERIOD <time unit>) ON <condition>
```

docs: Update KLIP-36 to add GRACE syntax on joins with before/after windows

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/PersistentQueryMetadataTest.java

Fixes a race that was caused by exposing a query via the map `persistentQueries` or set `allLiveQueries` without having initialized it.  This is done in particular in `HeartbeatAgent` and `RemoteHostExecutor`.  For example, when calling:
```
final List<PersistentQueryMetadata> currentQueries = engine.getPersistentQueries();
final Set<HostInfo> uniqueHosts =
DiscoverRemoteHostsUtil.getRemoteHosts(currentQueries, localHost);
```
The list of persistent queries isn't guaranteed to be initialized and the calls to the query in `DiscoverRemoteHostsUtil` such as `getState()` and `getAllMetadata()` will fail with NPEs.
Unit tests.

fix: Fixes race condition exposing uninitialized query

---

docs/developer-guide/joins/join-streams-and-tables.md

Fixes missing comma in example code.
Let's merge this to the live branch since it's currently broken.

Fixes example code docs typo

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/AdminResponseHandlers.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java

If `sourceConstraints` is not included in the server response, then default to an empty list in the java client.

fix: make current java clients compatible with pre-0.15 servers

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java

We saw a flakey test failure on Jenkins where AuthTest.java somehow got stuck in a loop and caused the build to hit the four-hour timeout. This PR adds a test timeout to all the api tests (including AuthTest.java) to at least prevent bad test runs from timing out the entire build.

test: set test timeout for BaseApiTest (MINOR)

---

ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java

The build is currently failing since ksqlDB's KafkaEmbedded class depends on deprecated methods of KafkaConfig that were recently removed in https://github.com/apache/kafka/pull/10872. This PR switches away from the methods to fix the build.
Will wait for Jenkins to pass before merging.

chore: fix build for KafkaConfig deprecations (MINOR)

---

ksqldb-engine-common/src/main/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercer.java
ksqldb-engine-common/src/main/java/io/confluent/ksql/schema/ksql/SqlTimeTypes.java
ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/SqlTimeTypesTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/ExpressionTreeRewriter.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/ExpressionTreeRewriterTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluator.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatter.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/DateLiteral.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/ExpressionVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/TraversalExpressionVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/expression/tree/VisitParentExpressionVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/CastInterpreter.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/TermCompiler.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/Literals.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/expression/formatter/ExpressionFormatterTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java

Adds the DateLiteral class and define DATE expressions to be formatted as yyyy-MM-dd. Also renames `SqlTimestamps` to `SqlTimeTypes`
unit tests

feat: define how DATE data is formatted

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

We were logging `Transient query created` each time a pull query was issued incorrectly. This fixes that issue
Set a debugger and issued a pull query.

fix: dont incorrectly log events for each pull query

---

pom.xml

protobuf version was bumped in schema registry, so we're seeing test failures with errors such as
```
java.lang.NoSuchMethodError: com.google.protobuf.DescriptorProtos$FieldDescriptorProto$Builder.setProto3Optional(Z)
```
meaning that there are some functions in 3.17.0 that SR uses that the current version doesnt have. 
see #7710 
Master build passes locally

chore: bump protobuf version to 3.17.0

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/insert-into.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-push-query.md

Fix some accidental commas left from PR https://github.com/confluentinc/ksql/pull/7687. Also add a new note when using GRACE PERIOD syntax for left/outer joins.

docs: fix accidental commas and add extre note to GRACE PERIOD syntax

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommandTest.java

Adds a check to make sure the version specified by `apply -v <number>` is greater than the last applied version.
Unit and integration tests

fix: block out of order migrations in migrations tool

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedPersistentQueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

Fixes flaky test `PullQueryRoutingFunctionalTest`.  The symptom of the flakiness was the failure:
```
io.confluent.ksql.rest.integration.PullQueryRoutingFunctionalTest.shouldFilterLaggyServers
Error Message
error msg: Timed out while waiting for a previous command to execute. command sequence number: 14
Stacktrace
java.lang.UnsupportedOperationException: error msg: Timed out while waiting for a previous command to execute. command sequence number: 14
at io.confluent.ksql.rest.integration.PullQueryRoutingFunctionalTest.cleanUp(PullQueryRoutingFunctionalTest.java:287)
```
After a lot of investigation, I noticed that `SequenceNumberFutureStore.completeFuturesUpToAndIncludingSequenceNumber` was never being called in rare scenarios, causing the future to never complete.  It turns out that the …

fix: Fixes slow streams shut down bug which made tests flaky

---

ksqldb-engine/src/test/java/io/confluent/ksql/execution/ExpressionEvaluatorParityTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/TermCompiler.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/terms/LiteralTerms.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/interpreter/InterpretedExpressionTest.java

Fixes #7512. Implements `visitIntervalUnit ` in `TermCompiler`.

fix: enable time unit functions for interpreter

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/ConnectSerdeSupplier.java
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_AVRO_in_out/7.0.0_1624431539708/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_AVRO_in_out/7.0.0_1624431539708/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_AVRO_in_out/7.0.0_1624431539708/topology
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_DELIMITED_in_out/7.0.0_1624431539655/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_DELIMITED_in_out/7.0.0_1624431539655/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_DELIMITED_in_out/7.0.0_1624431539655/topology
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_JSON_in_out/7.0.0_1624431539733/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_JSON_in_out/7.0.0_1624431539733/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_JSON_in_out/7.0.0_1624431539733/topology
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_PROTOBUF_in_out/7.0.0_1624431539749/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_PROTOBUF_in_out/7.0.0_1624431539749/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_PROTOBUF_in_out/7.0.0_1624431539749/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/date.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/SerdeUtils.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectDataTranslator.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedDeserializer.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerializer.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/json/JsonSerdeUtils.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroDeserializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroSerializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/connect/ConnectDataTranslatorTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/delimited/KsqlDelimitedDeserializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/JsonSerdeUtilsTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonDeserializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonSerializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/KsqlProtobufDeserializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/KsqlProtobufSerializerTest.java

Implement serde for DATE. DATE gets serialized to an integer number of days since 1970-01-01, and deserialized to `java.sql.Date`
unit and QTT tests

feat: implement serde for DATE

---

ksqldb-engine-common/src/main/java/io/confluent/ksql/schema/ksql/SqlTimeTypes.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluator.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluatorTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_casting_-_date_to_string/7.0.0_1624662245517/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_casting_-_date_to_string/7.0.0_1624662245517/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_casting_-_date_to_string/7.0.0_1624662245517/topology
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_casting_-_string_to_date/7.0.0_1624662245629/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_casting_-_string_to_date/7.0.0_1624662245629/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_casting_-_string_to_date/7.0.0_1624662245629/topology
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_casting_-_timestamp_to_date/7.0.0_1624662245728/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_casting_-_timestamp_to_date/7.0.0_1624662245728/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_casting_-_timestamp_to_date/7.0.0_1624662245728/topology
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_date_in_complex_types/7.0.0_1624662245824/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_date_in_complex_types/7.0.0_1624662245824/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_date_in_complex_types/7.0.0_1624662245824/topology
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_casting_-_string_to_time/7.0.0_1624662360534/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_casting_-_string_to_time/7.0.0_1624662360534/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_casting_-_string_to_time/7.0.0_1624662360534/topology
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_casting_-_time_to_string/7.0.0_1624662360513/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_casting_-_time_to_string/7.0.0_1624662360513/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_casting_-_time_to_string/7.0.0_1624662360513/topology
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_casting_-_timestamp_to_time/7.0.0_1624662360555/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_casting_-_timestamp_to_time/7.0.0_1624662360555/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_casting_-_timestamp_to_time/7.0.0_1624662360555/topology
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_time_in_complex_types/7.0.0_1624662360577/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_time_in_complex_types/7.0.0_1624662360577/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_time_in_complex_types/7.0.0_1624662360577/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/date.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/time.json

There was a bug where casting TIMESTAMP to DATE/TIME did not remove the TIME/DATE from the actual timestamp value stored in `java.sql.Date`/`java.sql.Time`.
QTT and unit tests. When #7718 is merged I can add QTT tests for DATE.

fix: remove time/date component when casting timestamp to date/time

---

ksqldb-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksqldb-common/src/test/java/io/confluent/ksql/function/UdfIndexTest.java

When working on `LEAST` and `GREATEST` functions, I noticed there was some nondeterminism inside the `UdfIndex` class, specifically with the `order` field, which was intended to give comparably equal functions a final ordering based in the way they were added inside the Udf's class. This wasn't working in practice, and was leading to equally comparable methods that matched a query being selected arbitrarily. For example, when calling `LEAST(INT, LONG)`, several UDFs could be selected: `LEAST(LONG, LONG...)`, `LEAST(DOUBLE, DOUBLE...)`, `LEAST(DECIMAL, DECIMAL)`.
To fix this, `UdfIndex.Node.compare()` was changed to no longer consider `order`. As this change implies we are no longer able to select a matching function if multiple exist, `getFunction` now throws a `KsqlException` if there is …

fix: fixed nondeterminism in UdfIndex

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
ksqldb-rest-model/pom.xml
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/ApiJsonMapper.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/ApiJsonMapperTest.java

Check that DATE/TIME work with connect by adding them to the connect integration test.

test: add DATE/TIME to connect integration test

---

ksqldb-execution/src/main/java/io/confluent/ksql/schema/query/QuerySchemas.java
ksqldb-execution/src/test/java/io/confluent/ksql/schema/query/QuerySchemasTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopicInfoCache.java

This is an improvement from the PR https://github.com/confluentinc/ksql/pull/7464. This PR just works around the QTT framework to support multiple KV loggers detected on QTT changelog topics that use the same schema info. This is required by stream-stream left/outer joins because there is a shared state store that write multiple value formats. QTT uses joins with one format, so we won't have to support different schema yet.

chore: update QTT framework to support multiple key/value loggers with same schema

---

ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorFunctionalTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_date_schema_inference/7.0.0_1624942593300/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_date_schema_inference/7.0.0_1624942593300/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/date_-_date_schema_inference/7.0.0_1624942593300/topology
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_time_schema_inference/7.0.0_1624942671947/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_time_schema_inference/7.0.0_1624942671947/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/time_-_time_schema_inference/7.0.0_1624942671947/topology
ksqldb-functional-tests/src/test/resources/historical_plans/timestamp_-_timestamp_schema_inference/7.0.0_1624942672354/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/timestamp_-_timestamp_schema_inference/7.0.0_1624942672354/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/timestamp_-_timestamp_schema_inference/7.0.0_1624942672354/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/date.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/time.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/timestamp.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectSchemaUtil.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/connect/ConnectSchemaUtilTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonDeserializerTest.java

Fixes #7730
Adds logic to the schema converter to convert date/time/timestamp to their logical types rather than just int/bigint.
QTT and manually tested.

fix: enable schema inference for timestamp/time/date

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-common/src/main/java/io/confluent/ksql/function/types/ParamTypes.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafTypes.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/FormatTime.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/ParseTime.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/FormatTimeTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/ParseTimeTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/function/UdfUtil.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestGeneratorTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/format-time_-_time_to_string/7.0.0_1624490278830/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/format-time_-_time_to_string/7.0.0_1624490278830/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/format-time_-_time_to_string/7.0.0_1624490278830/topology
ksqldb-functional-tests/src/test/resources/historical_plans/parse-time_-_string_to_time/7.0.0_1624490348282/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/parse-time_-_string_to_time/7.0.0_1624490348282/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/parse-time_-_string_to_time/7.0.0_1624490348282/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/format-time.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/parse-time.json
ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/JavaToSqlConverter.java

Enables TIME data for UDFs and adds the`PARSE_TIME` and `FORMAT_TIME` functions + docs.
QTT + unit tests

feat: add PARSE_TIME and FORMAT_TIME functions

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-common/src/main/java/io/confluent/ksql/function/types/ParamTypes.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafTypes.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/FormatDate.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/ParseDate.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/FormatDateTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/ParseDateTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/function/UdfUtil.java
ksqldb-functional-tests/src/test/resources/historical_plans/format-date_-_date_to_string/7.0.0_1624668401000/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/format-date_-_date_to_string/7.0.0_1624668401000/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/format-date_-_date_to_string/7.0.0_1624668401000/topology
ksqldb-functional-tests/src/test/resources/historical_plans/parse-date_-_string_to_date/7.0.0_1624668480830/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/parse-date_-_string_to_date/7.0.0_1624668480830/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/parse-date_-_string_to_date/7.0.0_1624668480830/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/format-date.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/parse-date.json
ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/JavaToSqlConverter.java

Enables DATE data for UDFs and adds the PARSE_DATE and FORMAT_DATE functions + docs.
QTT + unit tests

feat: add PARSE_DATE and FORMAT_DATE functions

---

docs/developer-guide/ksqldb-reference/select-push-query.md
docs/operate-and-deploy/installation/upgrading.md
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_full_outer_join_with_out_of_order_and_custom_grace_period_-_AVRO/7.0.0_1623947957608/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_full_outer_join_with_out_of_order_and_custom_grace_period_-_AVRO/7.0.0_1623947957608/topology
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_full_outer_join_with_out_of_order_and_custom_grace_period_-_JSON/7.0.0_1623947957938/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_full_outer_join_with_out_of_order_and_custom_grace_period_-_JSON/7.0.0_1623947957938/topology
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_out_of_order_and_custom_grace_period_-_AVRO/7.0.0_1623947956837/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_out_of_order_and_custom_grace_period_-_AVRO/7.0.0_1623947956837/topology
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_out_of_order_and_custom_grace_period_-_JSON/7.0.0_1623947957230/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_out_of_order_and_custom_grace_period_-_JSON/7.0.0_1623947957230/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamStreamJoinBuilder.java

Now that https://github.com/confluentinc/ksql/pull/7695 is merged, this PR enables the stream-stream left/outer joins fix implemented in https://issues.apache.org/jira/browse/KAFKA-10847.
To enabled it, I removed the `ENABLE_KSTREAMS_OUTER_JOIN_SPURIOUS_RESULTS_FIX` compatibility flag (which was set to False) from `KsqlConfig.java` so that all QTT tests and joins commands use the bugfix. The flag is enabled by default, so there is no need to enable it in `KsqlConfig.java`.
I also call the new `JoinWindows.ofTimeDifferenceAndGrace()` API when the `GRACE PERIOD` clause is used in Joins. The new API has the bugfix enabled internally.
BREAKING CHANGE: If the user sets GRACE PERIOD explicitly in stream-stream left/outer joins, the grace period defines when the left/outer non-joined results are …

fix: enable KAFKA-10847 bugfix when GRACE PERIOD is used on Joins

---

ksqldb-functional-tests/README.md
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java

I needed to run just one or two RQTT tests, but it didn't seem to be supported. I didn't add a file-based filter, since the files contain close to 100 test cases. The test name is a much better filter basis.

test: add filter for RQTT

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java

Right now, the port check in `PullQueryRoutingFunctionalTest` errors out inconsistently because in a heavy load system, we'll sometimes use the standby port instead of the active port if the active port isn't in a good state or wasn't able to send health checks due to load. This check is valuable on some systems, but because the CI environment is less reliable, we're not getting consistent results there. Since this is giving us an inconsistent signal, it makes sense to remove this check for now. 
An alternative is to add a retry after the initial check, but that doesn't seem foolproof to me either. We could retry indefinitely but that wouldn't give us any signal for the test.
Recent master failures:
https://jenkins.confluent.io/job/confluentinc/job/ksql/job/master/7968/ …

chore: remove flaky pull query functional test

---

ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java

removes ambiguity from deleteTopics method call in unit tests by bounding the argument type

test: remove ambiguity from deleteTopics method call

---

docs/operate-and-deploy/migrations-tool.md

Fixes #7767 
This will also be cherry-picked to the 0.18.0-ksqldb and the 0.19.0-ksqldb branches.

docs: add version requirements for using define in migrations tool

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/array/ArrayConcat.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/array/ArrayConcatTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_both_null/7.0.0_1625738677323/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_both_null/7.0.0_1625738677323/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_both_null/7.0.0_1625738677323/topology
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_left_null/7.0.0_1625738677246/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_left_null/7.0.0_1625738677246/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_left_null/7.0.0_1625738677246/topology
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_literals/7.0.0_1625735660140/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_literals/7.0.0_1625735660140/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_literals/7.0.0_1625735660140/topology
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_primitive_type/7.0.0_1625735660187/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_primitive_type/7.0.0_1625735660187/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_primitive_type/7.0.0_1625735660187/topology
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_right_null/7.0.0_1625738677292/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_right_null/7.0.0_1625738677292/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/array-set-functions_-_array_concat_with_right_null/7.0.0_1625738677292/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/array-set-functions.json

Adding `array_concat` UDF function. 
DESCRIBE function array_concat:
```
Name        : ARRAY_CONCAT
Overview    : Concatenates two arrays, creating an array that contains all the elementsin the first array followed by all the elements in the second array.
Type        : SCALAR
Jar         : internal
Variations  : 
Variation   : ARRAY_CONCAT(left ARRAY<T>, right ARRAY<T>)
Returns     : ARRAY<T>
left        : First array of values
right       : Second array of values
```
Tested with different array values, including duplicates, null value array members and null value input parameters

feat: add `ARRAY_CONCAT` UDF

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/exception/KsqlSchemaAuthorizationException.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplier.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/SchemaRegistryUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplierTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/registry/SchemaRegistryUtilTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFunctionalTest.java

Part of https://github.com/confluentinc/ksql/pull/7773. This only added a new exception to manage SchemaRegistry authorization errors and calls it where it is needed.
https://github.com/confluentinc/ksql/pull/7773 requires other changes to provide better SR permissions checks. 

refactor: wrap SchemaRegistry authorization errors into a KsqlSchemaAuthorizationException

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/FileWatcherTest.java

This is the counterpart to #6696 except for also file updated, not just created.
Ran the test

test: fix flaky test where FileWatcher might be called multiple times for update

---

ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java

There were some times when the `shouldApplyMigrationsAndDisplayInfo` was failing due to a materialized view not being available within 30s. I've seen this happen before on really slow Jenkins nodes, so we're just increasing the timeout and hoping it doesn't happen again. The integration test is worth keeping.
Ran the test

test: increase time out for migrations test

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/UtilizationMetricsListener.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadataImpl.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

Adds a basic metric reporter skeleton for observability metrics. This will be expanded on when we implement storage by node + query and saturation etc.
Additional testing will be added when metrics are implemented, benchmarking for saturation confirms that this structure works

feat: add observability metric skeleton

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/MetricsReporter.java

The added interface specifies how to report metrics to a metrics
framework. The implementations of this interface specify how to
report to a specific metrics framework (e.g. JMX or Confluent's
Telemetry pipeline)
No tests at this point since it is a plain interface.

feat: add interface for metrics reporter

---

ksqldb-api-client/pom.xml
ksqldb-cli/pom.xml
ksqldb-common/pom.xml
ksqldb-engine/pom.xml
ksqldb-examples/pom.xml
ksqldb-execution/pom.xml
ksqldb-functional-tests/pom.xml
ksqldb-metastore/pom.xml
ksqldb-parser/pom.xml
ksqldb-rest-app/pom.xml
ksqldb-rest-client/pom.xml
ksqldb-rest-model/pom.xml
ksqldb-serde/pom.xml
ksqldb-streams/pom.xml
ksqldb-test-util/pom.xml
ksqldb-tools/pom.xml
ksqldb-udf/pom.xml
ksqldb-version-metrics-client/pom.xml

Spotbug was bumped upstream from 4.2.0 to 4.3.0 recently, breaking ksqlDB build.
This PR disabled spotbug temporarily to let the build pass again.
We will re-enable spotbug on a per-module basis with follow up PRs.

build(hotfix): temporarily disable spotbug for certain modules

---

pom.xml

We temporarily used Netty 4.1.60 despite known CVEs because VertX did not support later versions of netty. This PR addresses that issue.
Tested end-to-end with basic auth (which was the symptom of the incompatibility the first time around)

chore: upgrade to VertX 3.9.8 and Netty 4.1.65.Final to avoid CVE

---

pom.xml

Fix CVE with apache commons IO by bumping to 2.7
```
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ ksqldb-docker ---
[INFO] io.confluent.ksql:ksqldb-docker:jar:6.1.3-0
[INFO] \- io.confluent.ksql:ksqldb-functional-tests:jar:6.1.3-0:compile
[INFO]    \- commons-io:commons-io:jar:2.7:compile
```

chore: fix CVE with apache io-commons

---

mkdocs.yml

Sets the beta tag so that Confluent Platform dependencies for this release can be correctly referenced in the docs.

docs: update platform dependencies tag

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-common/src/main/java/io/confluent/ksql/util/BytesUtils.java
ksqldb-common/src/test/java/io/confluent/ksql/util/BytesUtilTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/FromBytes.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/ToBytes.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/FromBytesTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/ToBytesTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestGeneratorTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_ASCII_encoded_string/7.1.0_1626808248533/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_ASCII_encoded_string/7.1.0_1626808248533/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_ASCII_encoded_string/7.1.0_1626808248533/topology
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_BASE64_encoded_string/7.1.0_1626808248709/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_BASE64_encoded_string/7.1.0_1626808248709/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_BASE64_encoded_string/7.1.0_1626808248709/topology
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_HEX_encoded_string/7.1.0_1626808244818/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_HEX_encoded_string/7.1.0_1626808244818/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_HEX_encoded_string/7.1.0_1626808244818/topology
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_UTF8_encoded_string/7.1.0_1626808248632/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_UTF8_encoded_string/7.1.0_1626808248632/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_UTF8_encoded_string/7.1.0_1626808248632/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/bytes-and-strings.json

Adds `TO_BYTES` and `FROM_BYTES` functions. Supported encodings are `hex`, `ascii`, `utf8`, and `base64`.

feat: add TO_BYTES/FROM_BYTES functions for bytes/string conversions

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/ColumnType.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/KsqlArray.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/KsqlObject.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Row.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/RowImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/RowImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/StructuredTypesDataProvider.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/KeyValueExtractor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedDeserializer.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerializer.java

Adding support for the new `BYTES` column type in the Java client API. The API will accept and return byte arrays as the new type. 
```
Row
byte[] getBytes(String columnName);
byte[] getBytes(int columnIndex);
KsqlObject
KsqlObject put(final String key, final byte[] value);
byte[] getBytes(final String key);
KsqlArray
KsqlArray add(final byte[] value);
byte[] getBytes(final int pos);
```
Internally, the `byte[]` value is encoded to a base64 string by the internal JSON object converters. This allows the client to send/receive bytes between the client and the server.
In the Server, though, the base64 string is decoded and converted to a `ByteBuffer`, which is later used to serialize the JSON row to the topic. This JSON row is serialized by the Connect JSON converters, which understand …

feat: support BYTES column types in Java client API

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java

The Vert.x BodyHandler's `create()` convenience constructor configures the handler to field file uploads by default. This means some requests, including those that don't specify a Content-Type header can be interpreted as file uploads.
This change disables the file upload support, since ksqlDB doesn't support such requests.

chore: avoid interpreting requests as file uploads

---

ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/system-columns.json
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/SingleColumn.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/SingleColumnTest.java

Previously, when trying to name a user column a reserved name (I'll use `ROWTIME` for this example), the error message was:
`'ROWTIME' is a reserved column name.`
Contrasted with trying to alias a reserved column name:
`ROWTIME is a reserved system column name. You cannot use it as an alias for a column.`
There are a lot of differences here which I'd like to iron out. The main idea is that these should be consistent, but the details I've chosen are:
- Apostrophes around the reserved column name should stay
- Drop the `system`. `Reserved column name` is enough.
- Keep the `You cannot use it as an {alias/name} for a column`
_Changed relevant test files to expect new strings_

chore: improve error messages for user columns with reserved names

---

ksqldb-engine/src/test/java/io/confluent/ksql/execution/ExpressionEvaluatorParityTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/CastInterpreter.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/ComparisonInterpreter.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ComparisonUtil.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/interpreter/InterpretedExpressionTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/testutil/TestExpressions.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/util/ComparisonUtilTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_filter/7.1.0_1626462616037/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_filter/7.1.0_1626462616037/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_filter/7.1.0_1626462616037/topology
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_greater_than/7.1.0_1626462616003/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_greater_than/7.1.0_1626462616003/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_greater_than/7.1.0_1626462616003/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/bytes.json
ksqldb-metastore/src/test/java/io/confluent/ksql/util/MetaStoreFixture.java

Comparisons for BYTES - they are compared lexicographically using the `ByteByffer.compareTo` function.
QTT and unit tests.

feat: implement bytes comparisons

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Len.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/LenTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/len_-_length_of_a_string_-_JSON/7.1.0_1627010796566/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/len_-_length_of_a_string_-_JSON/7.1.0_1627010796566/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/len_-_length_of_a_string_-_JSON/7.1.0_1627010796566/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/len.json

update LEN function to accept either STRING or BYTES
QTT and unit tests

feat: update len function to accept BYTES

---

ksqldb-version-metrics-client/pom.xml
ksqldb-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/VersionCheckerIntegrationTest.java

This does two things:
1. fixes a flaky test by using a mock wire instead of spinning up an entire mocked proxy server 
2. removes a dependency that has historically caused us some grief as it depends on specific netty versions
Rejoice!
Test would fail 1/10 runs locally before this change, didn't fail with 1k runs afterwards.

test: fix flaky version checker test by using simpler mock

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Concat.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/ConcatWS.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/ConcatTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/ConcatWSTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_-_bytes/7.1.0_1627194645370/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_-_bytes/7.1.0_1627194645370/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_-_bytes/7.1.0_1627194645370/topology
ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_ws_-_bytes_-_JSON/7.1.0_1627194645291/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_ws_-_bytes_-_JSON/7.1.0_1627194645291/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_ws_-_bytes_-_JSON/7.1.0_1627194645291/topology
ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_ws_-_string_-_JSON/7.1.0_1627194645238/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_ws_-_string_-_JSON/7.1.0_1627194645238/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/concat_-_concat_ws_-_string_-_JSON/7.1.0_1627194645238/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/concat.json

Enable BYTES for CONCAT and CONCAT_WS
QTT and unit tests

feat: enables BYTES for CONCAT and CONCAT_WS

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/ClientOptions.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientOptionsImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ClientOptionsImplTest.java

Fixes #7426. Allow Java API clients to customize the max number of requests per connection. In some cases, the default value of -1 does not work when the connection traverses a proxy or firewall that enforces other limits on this value.
With the change, clients can optionally provide a value here. If no value is provided, the behavior is as before since we reuse the Vert.x default.
Updated unit test

feat: allow Java clients to set HTTP/2 multiplex limit

---

ksqldb-functional-tests/src/test/resources/historical_plans/key-schemas_-_VARCHAR(STRING)_as_key_and_value/7.1.0_1627023646891/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/key-schemas_-_VARCHAR(STRING)_as_key_and_value/7.1.0_1627023646891/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/key-schemas_-_VARCHAR(STRING)_as_key_and_value/7.1.0_1627023646891/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/key-schemas.json
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java

There’s an ambiguity in the grammar declared in `SqlBase.g4`. This is happening at **tableElement** only for primitive types.
Ex.  `BOB STRING (KEY)`, evaluates **STRING(KEY)** as a type parameter. 
One possible solution is support `(KEY)` by adding at **KEY** token another option as `'(KEY)'`, but this causes another ambiguity, since fields named as **KEY** are supported, causing ambiguity when using a function.
ex. `AS_VALUE(KEY)`.
My proposed solution validates the schema in code at the parsing, throwing an exception if any primitive type has been evaluated as type parameter.
ksqldb-parser - AstBuilderTest
ksqldb-functional-test - key-schema.json

fix: silently ignores KEY qualifier if enclosed in parentheses (#5852)

---

config/ksql-server.properties
ksqldb-engine/src/main/java/io/confluent/ksql/security/AuthObjectType.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlAccessValidator.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlAuthorizationProvider.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlAuthorizationValidatorFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlAuthorizationValidatorImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlBackendAccessValidator.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlCacheAccessValidator.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlProvidedAccessValidator.java
ksqldb-engine/src/main/java/io/confluent/ksql/topic/SourceTopicsExtractor.java
ksqldb-engine/src/main/java/io/confluent/ksql/topic/TopicCreateInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/security/KsqlAuthorizationValidatorFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/security/KsqlAuthorizationValidatorImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/security/KsqlBackendAccessValidatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/security/KsqlCacheAccessValidatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/security/KsqlProvidedAccessValidatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/topic/SourceTopicsExtractorTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/AuthTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/MockKsqlSecurityExtension.java

KSQL has already validations for Kafka permissions when a new query, DDL or DML statement is executed by a user. This PR adds another validation for Schema Registry permissions.
The idea behind this PR is to let users know exactly what's causing a query or DDL operation to fail and also produce a more generic authorization error message similar to the one we have with Kafka. Currently, some statements show the SR authorization error returned by SR, but queries, for instance, never shown anything. Queries run and do not show any error and users always wonder why there's no data streamed (reason was a SR denied operation).
NOTE
This PR is based on an very old PR (https://github.com/confluentinc/ksql/pull/3323). It was easier to push a new PR with the updates. Also, the comments in that PR …

feat: make SchemaRegistry permission validations on KSQL requests

---

mkdocs.yml

From https://github.com/confluentinc/ksql/pull/7884.

docs: cherry-pick: update KStreams beta tag for 0.20.0 docs (DOCS-9243)

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java

Saw this test failing multiple times with
```
ava.lang.NullPointerException
at io.confluent.ksql.test.rest.RestQueryTranslationTest.tearDown(RestQueryTranslationTest.java:147)
```
We should not call `get()` twice on an `AtomicReference` as there is not guarantee that it does not change between both calls.

test: fix race condition in RQTT

---

ksqldb-engine/src/main/java/io/confluent/ksql/logging/query/QueryLoggerMessage.java
ksqldb-engine/src/test/java/io/confluent/ksql/logging/query/QueryLoggerMessageTest.java

Jira: [KCI-778](https://confluentinc.atlassian.net/browse/KCI-778)
Anonymized queries were printed out wrongly due to a missing `toString` method in `QueryLogger`. This PR adds this missing method. 
- Made sure tests still run and manually checked if logged queries are printed out correctly now.,

feat: added missing tostring method

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/ThreadTestUtil.java

Rather than constantly comparing pull query outputs against expected results as a basis for checking correctness, this ensures that persistent queries have consumed input by looking at offsets and ensuring the consumer groups have reached the end.
This has a couple advantages:
- Partial results can't be matched against expected values, prematurely calling the output correct.  This can otherwise lead to flaky tests.
- With the current code, when output doesn't match, it retries over and over, which leads to bad error messages that usually take the form of timeouts rather than assertion errors.
Ran tests.

Improves RQTT by using offsets to measure readiness

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/LPad.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/RPad.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/LPadTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/RPadTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-lpad-rpad_-_LPAD_with_all_args_from_record_-_JSON/7.1.0_1627442359830/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-lpad-rpad_-_LPAD_with_all_args_from_record_-_JSON/7.1.0_1627442359830/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-lpad-rpad_-_LPAD_with_all_args_from_record_-_JSON/7.1.0_1627442359830/topology
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-lpad-rpad_-_RPAD_with_all_args_from_record_-_JSON/7.1.0_1627442359873/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-lpad-rpad_-_RPAD_with_all_args_from_record_-_JSON/7.1.0_1627442359873/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-lpad-rpad_-_RPAD_with_all_args_from_record_-_JSON/7.1.0_1627442359873/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/bytes-lpad-rpad.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/bytes.json

This PR enables LPAD and RPAD UDFs to accept BYTES as a parameter
Unit testing and QTTs

feat: enable BYTES for LPAD and RPAD

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java

The CI machine appears to be overloaded and is being slow, so it seems to be timing out when reading from the command topic. This results in several flaky tests such as `shouldRunScriptOnRunScript`,`shouldRunScriptOnRunInteractively`, `shouldHandlePullQuery` which all fail due to `Timeout while waiting for command topic consumer to process command topic`.
Ran locally several hundred times but unable to easily reproduce bug as the MacBook is too fast.

fix: increase default command response timeout

---

ksqldb-common/src/main/java/io/confluent/ksql/util/BytesUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/FromBytes.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/ToBytes.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/FromBytesTest.java

When encoding bytes with to_bytes(..., 'base64'), I noticed that `\r\n` characters were added to the string. This PR sure not to add those \r\n characters.

chore: remove \r\n chars from Base64 encoded strings

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/ConnectSerdeSupplier.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/ExpectedRecordComparator.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilder.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/bytes.json

Allow QTT run tests with Protobuf bytes. The tests in JSON require bytes to be encoded using base64 encodind and also define the protobuf schema as part of the QTT test. QTT will identify there's a schema with the bytes type and attempt to decode the base64 string to a ByteBuffer. This ByteBuffer is written to the input topics.
Later, when the test is executed, the QTT gets the ByteBuffer from the output topics, and then is converted to base64 in order to compare it with the base64 string used in the QTT output topic.

refactor: support BYTES on QTT for Protobuf

---

docs/developer-guide/joins/join-streams-and-tables.md

We fixed the issue of spurious left/outer join results in 0.20.x and need to update the docs accordingly.

docs: update stream-stream join docs

---

ksql-common/src/main/java/io/confluent/ksql/util/timestamp/MetadataTimestampExtractionPolicy.java
ksql-engine/src/main/java/io/confluent/ksql/function/udaf/placeholder/PlaceholderTableUdaf.java
ksql-engine/src/main/java/io/confluent/ksql/util/ArrayUtil.java
ksql-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java
ksql-parser/src/main/java/io/confluent/ksql/parser/ExpressionFormatter.java
ksql-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutorFactory.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/QueuedCommandStatus.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/InternalTopicJsonSerdeUtil.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/OptionsParser.java
ksql-serde/src/main/java/io/confluent/ksql/serde/avro/AvroDataTranslator.java
ksql-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectDataTranslator.java
ksql-serde/src/main/java/io/confluent/ksql/serde/tls/ThreadLocalDeserializer.java
ksql-serde/src/main/java/io/confluent/ksql/serde/tls/ThreadLocalSerializer.java
ksql-test-util/pom.xml
pom.xml

use Confluent's log4j instead of the CVE version in existing log4j
spun up a server and made sure logs were getting logged :)

chore: exclude log4j for CVE purposes, use confluent shaded

---

docs/developer-guide/joins/partition-data.md

From https://github.com/confluentinc/ksql/pull/7949.

docs: cherry-pick: updated minor syntax updates in docs (DOCS-9451)

---

ksqldb-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroSerializerTest.java

Apparently some small things around casting behavior
and error messages have changed. This change makes the
test more generic so that it works regardless of the JVM.
Ran the tests on my machine. If they also pass in Jenkins, it should be fine to merge.

fix: make KsqlAvroSerializerTest work with Java 16

---

ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/DdlCommandExec.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/DdlCommandExecTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/StatementRewriterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/DataSourceNodeTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/ddl/commands/CreateTableCommand.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/model/DataSource.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/model/KsqlStream.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/model/KsqlTable.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/model/StructuredDataSource.java
ksqldb-metastore/src/test/java/io/confluent/ksql/metastore/model/StructuredDataSourceTest.java
ksqldb-metastore/src/test/java/io/confluent/ksql/util/MetaStoreFixture.java
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateSource.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStream.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTable.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/CreateTableTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-app/src/test/resources/ksql-plan-schema/schema.json

This is part of https://github.com/confluentinc/ksql/pull/7474 which adds support of source tables and streams.
This PR just adds new syntax to create source tables using `CREATE SOURCE TABLE` statements. It also marks those tables internally for future reference, such as `CreateTable`, `CreateTableCommand` and `KsqlTable`. 
The `KsqlTable` is the object saved in the metastore. This object contains two new variables, `readOnly` and `materialized`. The `readOnly` just specifies the table is read-only; and `materialized` specifies this table is materialized (or should be materialized). I split the SOURCE keyword into these two variables because they mean different things. Also, we might support source streams in the future which they are read-only objects, but not materialized.
_Describe …

feat: add CREATE SOURCE TABLE syntax and metadata info

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/PullQueryExecutorMetrics.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryMetricsTest.java

Fixes the distribution metrics since they were not setup correctly.
Previously, the max value was set to be 1000 microseconds, which is much less than the single digit milliseconds we generally get.  I also changed it to be a "linear" bucketizer so as to have finer grained smaller metrics, even though the max value is ten seconds.
Manual and unit testing.

fix: Fixes pull query latency distribution metrics

---

pom.xml

chore, 1.20 of commons compress had a known vulnerability - it's pulled in transitively via avro, but we're pinning in here instead because upgrading avro historically has caused some issues.
ran the test suite and also spun up a ksql cluster and created/tested some topics with AVRO encoding.

chore: pin commons-compress to avoid transitive CVE

---

CONTRIBUTING.md
README.md

Based on feedback from @jaceklaskowski, make it more clear how to build from source, including from release tags. See the `Building a released version` section.
This also updates some project name references from KSQL to ksqlDB.

docs: building from tagged source

---

ksqldb-common/src/main/java/io/confluent/ksql/reactive/BasePublisher.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlRequestConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushPhysicalPlan.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushPhysicalPlanBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushQueryPreparer.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushRouting.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushRoutingOptions.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/ScalablePushRegistry.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/locator/AllHostsLocator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/operators/PeekStreamOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/ScalablePushQueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/PushPhysicalPlanBuilderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/PushPhysicalPlanTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/PushRoutingTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/ScalablePushRegistryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/operators/PeekStreamOperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/ScalablePushQueryMetadataTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/DelimitedQueryStreamResponseWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryConfigRoutingOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTargetUtil.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/StreamPublisher.java

Currently, we don't handle rebalances explicitly in SPQ.  If a new node joins the cluster or is removed from the cluster, we don't do anything.  In this PR, it attempts to start a new request to the node or expects the node to drop out of the cluster and tries to keep the connections ongoing, ensuring now data is missed.

feat: Allow scalable push queries to handle rebalances

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java

This PR adds a check to prevent running INSERT statements onto source streams and tables.

feat: reject INSERT statements on SOURCE streams and tables

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/insert-into.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-push-query.md

Revert GRACE keyword in Joins

---

CHANGELOG.md
docs/developer-guide/joins/join-streams-and-tables.md

From https://github.com/confluentinc/ksql/pull/8030.

docs: cherry-pick: revert left/outer stream-stream join doc updates (DOCS-9600)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/8035.

docs: cherry-pick: link to 0.20.0 blog in built changelog (DOCS-9601)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/8035.

docs: cherry-pick: link to 0.20.0 blog in built changelog (DOCS-9602)

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/QueryAnonymizer.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/QueryAnonymizerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/QueryAnonymizerTest.shouldAnonymizeCreateSourceStreamQueryCorrectly.approved.txt
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/QueryAnonymizerTest.shouldAnonymizeCreateSourceTableCorrectly.approved.txt

As title says
Updated QueryAnonymizerTest

feat: add SOURCE streams/tables to query anonymizer

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryIdUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/QueryIdUtilTest.java

As part of the source table materialization feature, this PR creates a query plan for a source table command.
The query plan is not executed in this PR yet (a follow-up PR will include this). 
I will add unit tests in `KsqlEngineTest` in the PR that adds the CST query execution.

feat: create and write a query plan for source tables

---

ksqldb-common/src/main/java/io/confluent/ksql/util/timestamp/StringToTimestampParser.java
ksqldb-common/src/test/java/io/confluent/ksql/util/timestamp/StringToTimestampParserTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/ParseDate.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/ParseTime.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/StringToDate.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/ParseDateTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/ParseTimeTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/StringToDateTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/parse-date.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/parse-time.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/stringtimestamp.json

fixes #7961
This PR changes `PARSE_TIMESTAMP`, `PARSE_DATE` to parse case-insensitive strings.
As written in the [original issue](https://github.com/confluentinc/ksql/issues/7961) `PARSE_TIMESTAMP('29-JUN-21','dd-MMM-yy')` yields a null value, but will now result with the same value as of `PARSE_TIMESTAMP('29-Jun-21','dd-MMM-yy')`.
Affected functions - `PARSE_TIMESTAMP`, `PARSE_DATE` (and the deprecated functions - `STRINGTOTIMESTAMP`, `STRINGTODATE`)
Wrote unit tests

fix: date parsing functions: case-insensitive name parsing

---

ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/topic/TopicDeleteInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/DropSourceFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/topic/TopicDeleteInjectorTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/source-stream.json

Throws an error if a user tries to DROP...DELETE TOPIC for read-only sources.
Unit + QTT test

feat: block DROP...DELETE TOPIC for read-only sources

---

ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactoryTest.java

This PR prevents to call `TERMINATE` on source table queries.

chore: reject TERMINATE commands on CST tables

---

ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java

In the jenkins job that builds ksql off the latest kafka, there were failures due to ambiguous method reference. In AK PR [#9769](https://github.com/apache/kafka/pull/9769), a new `DescribeTopics` method was added to `Admin.java`. This made our `KafkaClientTopicImpl` test fail because we mocked with `any()` in the `DescribeTopics` method call, which now map sto two methods -> `describeTopics(java.util.Collection<java.lang.String>,org.apache.kafka.clients.admin.DescribeTopicsOptions)` and
`describeTopics(org.apache.kafka.common.TopicCollection,org.apache.kafka.clients.admin.DescribeTopicsOptions)`
This PR specifies that we should be looking for a `Collection`. 
The test errors were:
`[2021-08-29T16:07:40.085Z] [ERROR] Failed to execute goal …

chore: resolve ambiguous method reference

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopologyTestDriverContainer.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorUtilTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/source-table_-_create_source_table/7.1.0_1630345391687/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/source-table_-_create_source_table/7.1.0_1630345391687/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/source-table_-_create_source_table/7.1.0_1630345391687/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/source-table.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-cst-materialized.json
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TerminateTransientQueryFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

Added QTT tests for source tables and RQTT to test pull queries on materialized CST tables. The PR also tests that TERMINATE cannot be executed on CST tables.

test: add QTT tests for CST commands

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/ProcessingQueue.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryExecutorTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ScalablePushQueryFunctionalTest.java

Replaces the check for `ksql.query.push.scalable.enabled` with `ksql.query.push.scalable.registry.installed` to insert the streams Processor for Scalable Push Queries. The idea behind this is that we want the user to be able to enable SPQs using the config `ksql.query.push.scalable.enabled` per request or in the CLI and control the registry installation separately.
Also, ups the ProcessingQueue limit to 1000 to allow for larger bursts.
Verified it works as intended.

fix: Removes config check to insert SPQ Processor

---

ksqldb-common/src/main/java/io/confluent/ksql/config/ImmutableProperties.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java

Adds a feature flag disable source table materialization. The config to disable is:
```
ksql.source.table.materialization.enabled=true
```
The  config can only be disabled from the `ksql-server.properties`. This config cannot be set on the CLI or other clients to avoid ksql clients users to enable it without notice of the ksql server admin (like Cloud users).
When the config is disabled, KSQL will not accept new CST commands. However, current CST commands found in the command topic will be executed but with no materialization and pull query support. I left the behavior this way to prevent crashing the KSQL on startup if this config is disabled and there were CST commands already running. CST tables will still be read-only, though.
I didn't add tests because there's still a PR pending …

feat: add feature flag to disable source table materialization

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java

This test very rarely flakes out, but when it does it just "times out". I'd like to know which part is timing out.
N/A logging only

test: add logging to shouldStreamInserts in case it times out again

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgentTest.java

Should fix this upstream build failure:
```
09:22:14  [ERROR] /home/jenkins/workspace/apache-kafka-to-ksql-test_trunk/ksql-master/ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgentTest.java:[100,21] reference to describeTopics is ambiguous
09:22:14    both method describeTopics(java.util.Collection<java.lang.String>,org.apache.kafka.clients.admin.DescribeTopicsOptions) in org.apache.kafka.clients.admin.Admin and method describeTopics(org.apache.kafka.common.TopicCollection,org.apache.kafka.clients.admin.DescribeTopicsOptions) in org.apache.kafka.clients.admin.Admin match
09:22:14  [ERROR] /home/jenkins/workspace/apache-kafka-to-ksql-test_trunk/ksql-master/ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgentTest.java:[142,69] …
```

chore: mock describeTopics w/ explicit type to resolve ambiguous ref

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/JmxDataPointsReporter.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/MetricsReporter.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/utilization/PersistentQuerySaturationMetrics.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/JmxDataPointsReporterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/utilization/PersistentQuerySaturationMetricsTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

Add a persistent query saturation metric, and report it over JMX. Saturation
is computed by sampling total-blocked-time for each stream thread. We sample
the total blocked time every minute, and compute saturation by looking back
5 minutes and computing how long the thread was blocked in that interval.
Saturation is (5 minutes - blocked time)/(5 minutes).
This patch also adds a reporter that exposes reported data points over JMX.
The reporter adds a new Metric for every new data point name/tag combination
it sees, and implements the metric by reading the latest data point for the
name/tag, with a threshold on staleness.

feat: add persistent query saturation metric

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/InternalKsqlClientFactory.java

Vertx throws an error when http2 and tls are enabled, but the ALPN option isn't set on the options:
https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpClientImpl.java#L548
This sets the option when tls is used for http2, internal requests.
Tested using http2 and tls.

fix: Enables ALPN for internal requests when http2 and tls are in use

---

ksqldb-common/src/main/java/io/confluent/ksql/GenericKey.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/HARouting.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlan.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlanBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/KeyedTableLookupOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/KeyedWindowedTableLookupOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/QueryPlannerOptions.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/KeyConstraint.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryFilterNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/HARoutingTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/operators/KeyedTableLookupOperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/operators/KeyedWindowedTableLookupOperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/QueryFilterNodeTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-with-range-scan.json
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryConfigPlannerOptions.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryFunctionalTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/Locator.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/MaterializedTable.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocator.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedTable.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocatorTest.java

Use range interface in state store for range pull queries, instead of doing a table scan
no testing yet

Optimize key-range queries in pull queries (#6105)

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/SystemColumns.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java

As a result of https://github.com/confluentinc/ksql/pull/7990, we now materialize all key and pseudo columns in the value schema in order to allow for `ROWPARTITION` and `ROWOFFSET` in joins involving tables. This is wasteful as we are able to access timestamp and key columns after the materialization step, this PR adds just the partition and offset information without also storing the information we don't need.
Before:
```
Sub-topology: 0
Source: KSTREAM-SOURCE-0000000001 (topics: [t])
--> KTABLE-SOURCE-0000000002
Processor: KTABLE-SOURCE-0000000002 (stores: [])
--> KTABLE-MAPVALUES-0000000003
<-- KSTREAM-SOURCE-0000000001
Processor: KTABLE-MAPVALUES-0000000003 (stores: [KsqlTopic-Reduce])
--> KTABLE-TRANSFORMVALUES-0000000004
<-- KTABLE-SOURCE-0000000002
Processor: …
```

chore: Materialize only partition and offset information in V2 table source steps

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/ScalablePushUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ScalablePushQueryFunctionalTest.java

Changes the config names of scalable push queries to be push queries v2. The idea is that this uses a more efficient methodology if possible and falls back to the conventional method if not, so it's really an updated version of push queries.

chore: Rename Scalable Push Query to be push query v2

---

Jenkinsfile

Consolidates the alerting for failed builds into the ksqldb-quality-oncall channel.

chore: Move build alerts to quality-oncall

---

Jenkinsfile

We want to keep builds for three months to support investigations,
but have been hampered by the default value of maxBuildsToKeep (15).
I just raised it arbitrarily to 99. I also made the default retention time
of 90 days explicit in the Jenkinsfile.

chore: raise the limit on number of builds to keep

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporter.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporterTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

per https://confluentinc.atlassian.net/browse/KCI-938, make storage utilization per node metrics initialized when the app starts up. this means that even if the app has no queries, we'll still be getting metrics at the node level. previously, we'd only see node level metrics after we created a query
kept existing unit tests

feat: update storage utilization metrics to start when app is initialized

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryPlan.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistry.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/QueryPlanTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java
ksqldb-rest-app/src/test/resources/ksql-plan-schema/schema.json

Make it so the config value for shared runtimes are enabled is written into the cmd topic so it is specific to when each query was launched

feat: add shared runtime config to QueryPlan

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-streams.json

Since stream pull queries are only implemented for the HTTP/1 REST endpoint, they will be disabled by default.
The config is overridable on a per-query basis, though, in case people want to use the feature in a preview state.

feat: disable stream pull queries by default

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/SlidingWindowRateLimiter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/PullBandwidthThrottleIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ScalablePushBandwidthThrottleIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/SlidingWindowRateLimiterTest.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java

Scalable push query bandwidth on the http2 endpoint is now tracked and is throttled just like the http1 endpoint. Bandwidth limit error messages also now specify whether it was pull or push bandwidth that was exceeded. 
Added integration test and updated unit/integration tests.

fix: fix spq bandwidth throttling on http2 

---

docs/developer-guide/ksqldb-clients/java-client.md
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/HttpRequestImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/HttpResponseImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/HttpRequestImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/HttpResponseImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java

This PR adds methods and classes that allow users to directly execute HTTP requests against ksqldb's REST server. The API client today uses a number of "high level" classes. With an 'escape hatch' as implemented in this PR, users do not need to wait for all the REST APIs, request and response objects to be implemented as java objects and classes in the api-client. 
This PR resolves one of the issues described in #8042.
Unit and integration tests (and tests against a local docker container).

feat: add methods and classes to execute low level HTTP requests in the ksqldb-api-client

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushRouting.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/PushRoutingTest.java

The Vertx timer which is used to ensure connections with other nodes in the cluster correctly checks if the handle has been closed, but the condition for isClosed only considered if there was an error, not if it had been manually closed as when the connection is closed.
Called it in unit tests and manually verified.

fix: Ensures background timer completes for scalable push queries

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryBuilderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java

For so long, I've been getting confused about the real job of the `QueryExecutor`. The class does not executes anything, but only builds transient and persistent queries metadata. So why not refactoring to avoid more confusion?

refactor: rename QueryExecutor to QueryBuilder

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientMutationIntegrationTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/InsertsStreamEndpoint.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java

Inserting into tables using CLI is permitted but using Java API is not. Allow it in Java API to make the behavior consistent.
Fixes https://github.com/confluentinc/ksql/issues/7948
* Remove checks for table insertion in `ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/InsertsStreamEndpoint.java`.
* Remove two unit tests in `ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java` as they use `testEndpoint` and doesn't actually test anything in production endpoint.
* Add 4 test in integration test. All other changes in Integration test comes from Intellij auto formatting
* Insert and Pull from table -> Exception
* Insert and Push query from table -> Success
* Insert and Pull from CTAS table -> Nothing returns
* Insert to topic and Pull from CTAS table -> …

fix: allow insert into table using HTTP/2 endpoint and Java API

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporter.java
ksqldb-engine/src/main/java/io/confluent/ksql/utilization/PersistentQuerySaturationMetrics.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/utilization/PersistentQuerySaturationMetricsTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

We need to pass the `customTags` from the `ksqlConfig` to both the saturation and storage metrics to make sure we're picking up all the necessary tags. Right now, we pass the logical cluster as a tag in through this config and we need that to query through the metrics API
will test on devel shortly

add logical cluster id to observability metrics

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java

Fixes https://github.com/confluentinc/ksql/issues/8104
The issue in https://github.com/confluentinc/ksql/issues/8104 was caused by a `persistentQuery.initialize()` call in the `QueryRegistryImpl` class because it was attempting to initialize a new kafka streams with a state directory that was used by the old kafka streams. This old kafka streams is not stopped because it is run in a sandboxed environment, however, the state store is never unlinked from this old kafka streams, so the new query fails linking to it.
The fix is just to avoid initializing the new query in a sandboxed environment. 
This issue started happening since ksqldB 0.17.0

fix: CREATE OR REPLACE TABLE on an existing query fails while initializing kafka streams

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlan.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullQueryResult.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/TransientQueryQueue.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/TransientQueryQueueTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryMetricsFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

Add metrics and limiters (rate, bandwidth, concurrency) for stream pull queries. The limiters are counting both table and stream pull queries in the same limit. For example, if we allow 100 concurrent queries it must hold: table-pull + stream-pull <= 100
Added new junit tests for metrics. Did manual tests for limiters.

feat: Add metrics and limiters for stream pull queries for HTTP1 endpoint

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java

Clean up the Websocket PushQueryPublisher to remove a bunch of
unnecessary fields and code paths.

refactor: clean up push query publisher

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/json/JsonExtractString.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/json/JsonExtractStringKudfTest.java

Allows the `extract` function to be invoked on the same instance multiple times with different `path` variables.
A unit test has been added and the steps that reproduce the bug validated.

fix: Allow multiple EXTRACTJSONFIELD invocations on different paths (#8122)

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java

Finishing out the stream pull query implementation cycle, this adds support
to the websocket endpoint, building on the HTTP/1 and HTTP/2 endpoints.

feat: add stream pull queries to websocket endpoint

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java

Previously, if you `SET 'auto.offset.reset'='earliest'` or `'latest'`, the query would fail
with an exception. This patch fixes that and simply overrides the configs as desired.

fix: stream pull query internal overrides shouldn't clash with query configs

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullQueryResult.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/SlidingWindowRateLimiter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java

When the bandwidth rate limit is hit, it never decrements the concurrency counter.  This change ensures it always does.
Ran tests and verified manually

fix: Always dec. concurrency counter, even hitting rate limits

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryEngine.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java

To add a feature flag for [KLIP-50](https://github.com/confluentinc/ksql/blob/master/design-proposals/klip-50-partition-and-offset-in-ksqldb.md) in https://github.com/confluentinc/ksql/pull/8120, a `KsqlConfig` had to be available in every location where a decision had to be made about which psuedo column version to use. For certain queries that require session config overrides, these were being ignored, as only the engine config was being provided. This PR fixes that.
None. I think this is acceptable because this will be removed when the flag is removed, and other tests should fail if this fix is undone. If there is smart test coverage to be done here, I'm open to adding it.

chore: fix for bug where QueryAnalyzers weren't being constructed with session configs

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaConsumerGroupClientImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/ExecutorUtil.java

During local testing, I've noticed that consumer group cleanup for my transient queries 
is frequently timing out and leaving defunct groups lying around. This patch increases the amount
of time to wait for the group to become empty.

fix: allow more time for consumer group cleanup

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/ScalablePushUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/ScalablePushUtilTest.java

Before this change, you had to set the config for spqs via the config `ksql.query.push.v2.enabled`.  This allows it to be enabled via override.
Manual testing an unit tests.

chore: Allow SPQs to be enabled via request overrides

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java

This PR only logs a warning message when restoring the command topic if the https://github.com/confluentinc/ksql/issues/8173 bug is hit.

chore: log a warning message when known IF NOT EXISTS bug is found

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/SystemColumns.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryLogicalPlanUtil.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryProjectNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/QueryProjectNodeTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderBase.java

Ensures that we don't provide the new pseudo column version (and therefore ROWOFFSET and ROWPARTITION) to pull queries or scalable push queries yet since they don't (and in the case of pull queries won't) support it.
Also, stores the right state store schema in `MaterializationInfo` since this breaks when comparing to the actual rows (which have the new cols) without this change.
Ran RQTT tests and unit tests.

chore: fix pull and push query v2 to properly ignore ROWOFFSET/ROWPARTITION

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/ScalablePushUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/ScalablePushUtilTest.java

Assume that if no latest config is set, `auto.offset.reset` is "latest" for SPQ, which is the default for push queries in ksqlDB.
Unit testing and manual testing

chore: Assume default push queries are latest for SPQ

---

ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json

The order or result records is non-deterministic. Reducing the result size to a single record avoid this issue.
A long term fix (for `master`) might be to extend the test framework to ignore order when verifying the result

test: fix flaky windowed joined RQTT tests

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/PushPhysicalPlan.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/PushPhysicalPlanTest.java

Observed a failing test run with error: `Cannot subscribe to failed publisher.`
The reason is a race condition because the subscriber subscribes to the publisher after the publisher background thread is started. This PR changes the order to register the subscriber before we start the publisher thread.
Using a breakpoint on the old `publisher.subscribe()` line allows to 100% reproduce the race. Thus no additional testing is needed as we call `publisher.subscribe()` earlier now (and setting a breakpoint at the new line verifies that the issue is resolved).

test: fix race condition in PushPhysicalPlanTest

---

ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/AlterSourceFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/AlterSourceFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceFactoryTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/source-stream.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/source-table.json

Disables the use of CREATE OR REPLACE on streams and tables to prevent the issue in https://github.com/confluentinc/ksql/issues/8197. This PR is created to continue with the 0.22 release. 
Examples for Streams:
```
ksql> CREATE OR REPLACE STREAM INPUT (K STRING KEY, text STRING) WITH (kafka_topic='test_topic', value_format='DELIMITED');
Cannot add stream 'INPUT': CREATE OR REPLACE is not supported on source streams or tables.
ksql> CREATE OR REPLACE SOURCE STREAM INPUT (K STRING KEY, text STRING) WITH (kafka_topic='test_topic', value_format='DELIMITED');
Cannot add stream 'INPUT': CREATE OR REPLACE is not supported on source streams or tables.
```
Examples for Tables:
```
ksql> create or replace source table t1(id int primary key, name string) with (kafka_topic='t1', value_format='json', …
```

chore: disable CREATE OR REPLACE on source streams and tables

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java

Fixes #8129 
`QueryId` does not implement `Comparable`, so calls made to `Stream<QueryId>.sorted()` threw errors. This is a quick fix to get around that.

fix: ClassCastException when dropping sources with 2+ insert queries

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java

We were seeing some command topics go into a `degraded` state after a cluster was terminated because the command runner deleted the command topic but doesn't close itself. This has the command runner `close` right after seeing a `terminate` command so we don't get spurious alerts.
unit test and manual test.
manual test:
created ksql cluster, rolled to this image
issued a terminate command
`
curl -X "POST" "endpoint/ksql/terminate" \
-H "Content-Type: application/vnd.ksql.v1+json; charset=utf-8" \
-d $'{
}' -v --http2 -H "Authorization: Basic $AUTH"
`
saw the following in datadog:

fix: close command runner when command topic is deleted

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullQueryResult.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/SlidingWindowRateLimiter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java

cherry pick https://github.com/confluentinc/ksql/commit/0e0551970190861edaa1f7dc4c68ab279597d30b for 0.21 hotfix
* fix: Always dec. concurrency counter, even hitting rate limits

fix: Always dec. concurrency counter, even hitting rate limits (#8165)

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/ScalablePushQueryMetadata.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/ScalablePushQueryMetadataTest.java

Correctly capture rows returned for scalable push query metrics, by using a TransientQueryQueue in the scalable push query metadata, since that is the queue we pass in anyway during instantiation.
Unit tests updated

fix: correctly capture rows returned for scalable push query metrics

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md

The aggregate function docs has [blank lines in the middle of the sentence](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/aggregate-functions/#earliest_by_offset) which causes it to appear split as shown below. 
Removed the extra blank lines.
Only docs change, no code change.

docs: Removed extra blank lines in the middle of sentence

---

docs/overrides/main.html

https://confluentinc.atlassian.net/browse/UIF-1010
In order to support more sophisticated, faceted search in docs.confluent.io, we are looking at adding some meta tags to a number of websites that are currently included in docs' swiftype search engine. This will allow search results to be targeted at specific sites (and languages).  
The following sites are involved:
Site | Id
-- | --
https://docs.confluent.io/ | 1
https://www.confluent.io/blog/ | 2
https://developer.confluent.io/ | 3
https://docs.ksqldb.io/en/latest/ | 4
https://kafka-tutorials.confluent.io/ | 5
https://api.telemetry.confluent.cloud/docs | 6
The change involved is minimal and would be to add the following meta tag into the main template file of each site:
`<meta class="swiftype" name="site-id" data-type="integer" …

feat: [UIF-1010] Add swiftype metatag for site of ksqldb

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java

Command version in 0.22.0 release is 10. We need to bump it to 11 for 0.23.

chore: bump command version from 10 to 11 for v0.23

---

docs/requirements.txt

From https://github.com/confluentinc/ksql/pull/8316.
* chore(deps): bump mkdocs from 1.1.2 to 1.2.3 in /docs
Bumps [mkdocs](https://github.com/mkdocs/mkdocs) from 1.1.2 to 1.2.3.
- [Release notes](https://github.com/mkdocs/mkdocs/releases)
- [Commits](https://github.com/mkdocs/mkdocs/compare/1.1.2...1.2.3)
---
updated-dependencies:
- dependency-name: mkdocs
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
* docs: update mkdocs-macros-plugin to 0.6.0
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
_Describe the testing strategy. Unit and integration tests are expected for any …

docs: cherry-pick: bump mkdocs from 1.1.2 to 1.2.3 in /docs (DOCS-10738)

---

docs/requirements.txt

From https://github.com/confluentinc/ksql/pull/8316.
* chore(deps): bump mkdocs from 1.1.2 to 1.2.3 in /docs
Bumps [mkdocs](https://github.com/mkdocs/mkdocs) from 1.1.2 to 1.2.3.
- [Release notes](https://github.com/mkdocs/mkdocs/releases)
- [Commits](https://github.com/mkdocs/mkdocs/compare/1.1.2...1.2.3)
---
updated-dependencies:
- dependency-name: mkdocs
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
* docs: update mkdocs-macros-plugin to 0.6.0
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
_Describe the testing strategy. Unit and integration tests are expected for any …

docs: cherry-pick: bump mkdocs from 1.1.2 to 1.2.3 in /docs (DOCS-10739)

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/PullQueryRewriter.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryFilterNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/PullQueryRewriterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/QueryFilterNodeTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-with-predicates.json

Add the support of LIKE and BETWEEN operators for pull query table scans.
This problem was reported in #7793 
Add new tests to Integration Test.

fix: Pull query table scans support LIKE and BETWEEN operators

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/DdlDmlResponseHandlers.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java

```
ksql> CREATE STREAM IF NOT EXISTS BAR AS SELECT * FROM FOO EMIT CHANGES;
Message                                                              
----------------------------------------------------------------------
Cannot add stream `BAR`: A stream with the same name already exists. 
----------------------------------------------------------------------
ksql> CREATE STREAM FOO (id INT KEY, bar VARCHAR) WITH(value_format='json', kafka_topic='foo', partitions=6);
Cannot add stream 'FOO': A stream with the same name already exists
ksql> 
```

fix: if not exists return type

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommands.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LocalCommandsTest.java

We had multiple on call incidents where a race condition occurs when writing to the local commands file which corrupts it. Processing this corrupt local commands file on startup kills the ksqldb app. The local commands is meant to only be a best effort attempt at cleaning up orphaned transient topics #6714 and abandoned state stores #6720, so we should not kill the ksqldb app if we fail to clean these up. Instead of throwing an error we now simply just log the error and continue on. 
Follow up work will be done to log the race conditions that result in the corrupted local commands file. 

fix: dont throw error on processing local commands, just log 

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/ImmutabilityTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/functional/ImmutabilityTest.java
ksqldb-metastore/src/test/java/io/confluent/ksql/metastore/ImmutabilityTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/ImmutabilityTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/app/ImmutabilityTest.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/ImmutabilityTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/ImmutabilityTest.java
ksqldb-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/ImmutabilityTest.java

Add BytesLiteral to all the immutability tests in packages that depend on `ksqldb-execution` so that `mvn test` and intellij runs would pass.

test: add BytesLiteral as immutable type everywhere

---

ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SchemaParser.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/TableElement.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/SchemaParserTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/TableElementTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/TableElementsTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/util/GrammarTokenExporterTest.java

Adds `HEADERS` as a column type (like `KEY` or `PRIMARY KEY`) as a part of https://github.com/confluentinc/ksql/pull/8293
At some point in the future, changes will be made to
1. Reject `HEADERS` columns that are not of type `ARRAY<STRUCT<key STRING, value BYTES>>`
2. Add `HEADER(key)` to the syntax
Unit tests

feat: add HEADERS column type to syntax

---

ksqldb-common/pom.xml
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/datetime/ParseDate.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/ParseDateTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/parse-date.json
pom.xml

Fixes #8328
Reason it didn't work is because `LocalDate` doesn't do partial parsing. `LocalTime` does partial parsing for `hh:mm`, but not just `hh`. I think that is fine though.
`StringToDate` also has this problem, but I did not fix that because it is deprecated.
Unit + QTT

fix: make parse_date able to parse partial dates

---

Jenkinsfile

Capping in branches 5.2.x through 6.0.x the number of concurrent Jenkins jobs running down to just 2 (one running, all others queued) in order to reduce the impact of releases has on Jenkins (To cap the “Jenkins Build Storm” after releases are finalized and bumped to the next version every quarter). This change will save a lot of Jenkins build resources.

build: disable concurrent jobs up through 6.0.x

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/HARouting.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/HARoutingTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/services/DisabledKsqlClient.java
ksqldb-execution/src/main/java/io/confluent/ksql/services/SimpleKsqlClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/DefaultKsqlClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/ServerInternalKsqlClient.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryConsistencyFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/FaultyKsqlClient.java

Following the practice introduced in #8264 this PR is using request properties to pass the consistency token between servers

chore: passing consistency token using request properties in HARouting

---

docs/operate-and-deploy/installation/upgrading.md

Replace hard-coded version with `{{ site.ksqldbversion }}` token.

docs: bump version in upgrade notes for 0.21.0 (DOCS-10840)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java

Adds back the test `shouldQueryActiveWhenActiveAliveQueryIssuedToStandby` which was removed when it was being flaky.  Also, attempts to address flakiness by using a static task assigner for streams which should consistently give the same tasks over and over again to the same servers, so rebalancing won't be an issue.
Ran tests!

fix: Makes PullQueryRoutingFunctionalTest  more reliable and adds back test

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

Currently, the `QueryCleanupService` waits 30s on shutdown.  For some hard to debug reason, in tests, I constantly get `GroupNotEmptyException`s for query ids of queries that have been deleted in tests.  This makes mosts functional tests timeout at 30s.
This PR makes that value a config and sets it to 500ms in functional tests.  After all, when a server is shut down in a test, the state is going to be wiped out anyway.  This makes many functional tests go from 40s to 10s in my testing which makes it much easier to deal with and will hopefully speed up our test runs.
Ran tests.

fix: Makes tests wait only 500ms for consumer group cleanup

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryFilterNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/QueryFilterNodeTest.java

Optimize the key constraint extraction logic.
This problem was reported in issue #6973
Add new unit tests.

fix: Pull Query Key Extraction Optimizations

---

docs/reference/server-configuration.md

The configs `ksql.fail.on.production.error` and `ksql.fail.on.deserialization.error` can only be set at a server level, and cannot be applied per-query. This PR fixes an error in the docs to reflect this.
Once merged, I'll cherry-pick to the (recent) live ksqlDB docs branches as well.

docs: fix docs to reflect that `fail.on.*.error` configs cannot be applied per query

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryPlan.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryBuilderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java

Extracting some self-contained pieces of the mega-PR [#8219](https://github.com/confluentinc/ksql/pull/8219) before I tackle any of the large refactoring that was suggested.
This PR just prepares only the necessary changes for us to finally merge [https://github.com/apache/kafka/pull/11272](#11272)  without breaking the build. Since we were already starting up an empty KafkaStreams, the only changes we need here are to get the `TopologyBuilder` from this KafkaStreams

chore: adapt to the new API for NamedTopology builders and runtimes

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/FlatMapNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerFunctionalTest.java

Fixes https://github.com/confluentinc/ksql/issues/8065#event-5563432289
The last comment on https://github.com/confluentinc/ksql/issues/8065#event-5563432289 suggested that table functions should not be allowed in CASE functions. 
Today, we support one table function only (`EXPLODE`) which returns one column and several rows. But if in the future we support other tables functions (created with SQL UDTF for example) that return different columns, then mixing UDTF with CASE will complicate the resulted schema.
A quick example why not to support this case. The CASE will attempt to return 1 column for IDs < then 10, but 8 columns for > 10. This is not possible to do.
```
SELECT CASE
WHEN s1.id >= 10 THEN
tableFunctionReturns1Column()
ELSE
tableFunctionReturns2Columns()
END
FROM ...
```
The …

fix: return error message if table functions are used inside a CASE

---

ksqldb-api/pom.xml

Need to upgrade Netty to fix CVE. This is only for 5.5.x

fix: upgrade Netty for 5.5.x

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/ScalablePushRegistry.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/consumer/LatestConsumer.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/consumer/ScalablePushConsumer.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/consumer/LatestConsumerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/consumer/ScalablePushConsumerTest.java

This PR actually fixes two bugs.  One is that there is a case where the last messages were produced to some output topic over 30s ago but the last latest consumer was run much longer before.  The intent is that we seek to latest since there are no recent messages but instead it would find null values in the map from the call to:
```
final Map<TopicPartition, OffsetAndTimestamp> offsetAndTimestampMap =
consumer.offsetsForTimes(timestamps);
```
And the result is that it would not do a comparison and default to using committed offsets.  If the committed offsets were old, you'd get a lot of data!
Another fix is of calling the `close` method on `ScalablePushConsumer`, which would call `consumer.close()`, which could happen from another thread than the one the `KafkaConsumer` was on, which …

fix: Fixes a timestamp bug with Scalable Push Queries

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/Column.java
ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/SystemColumns.java
ksqldb-common/src/main/java/io/confluent/ksql/util/DuplicateColumnException.java
ksqldb-common/src/test/java/io/confluent/ksql/config/KsqlConfigResolverTest.java
ksqldb-common/src/test/java/io/confluent/ksql/schema/ksql/ColumnMatchers.java
ksqldb-common/src/test/java/io/confluent/ksql/schema/ksql/ColumnTest.java
ksqldb-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/TableElements.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/TableElementsTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderV1.java

Adds `HEADERS` and `HEADER('key')` columns to the logical schema. 
Changes include
* Added a new property, `Optional<String> headerKey` to `Column`
* LogicalSchema builder can add header columns
* LogicalSchema builder checks that there is only one HEADER column, and that the same header key is not used twice

feat: add headers to the logical schema

---

ksqldb-version-metrics-client/pom.xml
ksqldb-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/VersionCheckerIntegrationTest.java

After the netty version was bumped on 5.5.x, the version checker test started failing. This PR ports a fix that makes the test not dependent on specific netty versions.
The test passes locally

test: cherry-pick #7863 to the 5.5.x branch

---

ksql-version-metrics-client/pom.xml
ksql-version-metrics-client/src/test/java/io/confluent/ksql/version/metrics/VersionCheckerIntegrationTest.java

Port changes from #7863 to 5.4.x

fix: port changes from #7863 to 5.4.x

---

ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/HARoutingTest.java

Now that partition fetch operations are executed in parallel the number of fetch operations that are being executed until the coordinator aborts is no longer deterministic. This PR relaxes the assumption with regard to the number of partition fetch calls being made in a flaky test.

fix: tolerate out-of-order execution on HARouting tests

---

mkdocs.yml

When we concatenate the packaging URL for Confluent Platform dependencies in the documentation (e.g. the sample Java client pom), both the artifact version and the build number must be accurate. This updates the build number for the 0.22.0 release.

docs: Update packaging build number for artifacts

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ScalablePushBandwidthThrottleIntegrationTest.java

Because `ScalablePushBandwidthThrottleIntegrationTest` creates a server per test, the startup time is attributed to the test, so although there's a 2 minute limit, most of it can be taken up by this startup.  When the test then runs, the server gets terminated part way through and you get a funny connection closed error rather than a timeout, leading to confusion.
This ups the timeout of this test to prevent this.
Ran the test and simulated slow startup and was able to reproduce flaky stacktraces.

fix: Fixes flaky ScalablePushBandwidthThrottleIntegrationTest caused by timeout

---

docs/developer-guide/ksqldb-clients/index.md

From https://github.com/confluentinc/ksql/pull/8311.

docs: cherry-pick: add Go and Python community clients to the list (DOCS-10933)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/BytesUtils.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/ToBytesTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/bytes-and-strings.json

Fixes #8302
Replaces Google's BaseEncoding class with `javax.xml.bind.DatatypeConverter ` for Hex conversions.
Added unit and QTT tests

fix: make to_bytes work with lowercase hex

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/json/JsonPathTokenizer.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/json/JsonExtractStringKudfTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/extract-json-field_-_concat_two_extracted_fields/7.2.0_1638208773077/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/extract-json-field_-_concat_two_extracted_fields/7.2.0_1638208773077/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/extract-json-field_-_concat_two_extracted_fields/7.2.0_1638208773077/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/extract-json-field.json

Fixes https://github.com/confluentinc/ksql/issues/8358
Easy fix that allows the `@` character in the JSON path name.
```
ksql> select EXTRACTJSONFIELD('{"@type": "foo"}', '$.@type') from test emit changes;
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|KSQL_COL_0                                                                                                                                                                    |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|foo
```
_Describe the testing strategy. Unit and integration …

fix: allow valid @ character on JSON extract functions

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksqldb-common/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemaTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/DistributingExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java

Makes the following statements fail:
* `INSERT INTO ... SELECT ...` if the target source has header columns
* `INSERT VALUES ...` if one of the target columns is a header column
Manually tested and added unit tests. Integration tests will be in another PR.

feat: block inserting into sources with headers

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ScalablePushBandwidthThrottleIntegrationTest.java

I think this test is slow because the iterations can take a while to do, so this boils down the iterations to just 5 total rather than 12.
Ran test locally.

test: Attempts to speed up ScalablePushBandwidthThrottleIntegrationTest

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/reference/user-defined-functions.md
ksqldb-common/src/main/java/io/confluent/ksql/util/BytesUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/conversions/BigIntFromBytes.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/conversions/DoubleFromBytes.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/conversions/IntFromBytes.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/conversions/BigIntFromBytesTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/conversions/DoubleFromBytesTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/conversions/IntFromBytesTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_INT,_BIGINT,_and_DOUBLE_using_BIG_ENDIAN/7.2.0_1638229348360/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_INT,_BIGINT,_and_DOUBLE_using_BIG_ENDIAN/7.2.0_1638229348360/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_INT,_BIGINT,_and_DOUBLE_using_BIG_ENDIAN/7.2.0_1638229348360/topology
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_INT,_BIGINT,_and_DOUBLE_using_LITTLE_ENDIAN/7.2.0_1638229348474/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_INT,_BIGINT,_and_DOUBLE_using_LITTLE_ENDIAN/7.2.0_1638229348474/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes-and-strings_-_convert_bytes_to_INT,_BIGINT,_and_DOUBLE_using_LITTLE_ENDIAN/7.2.0_1638229348474/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/bytes-and-strings.json
ksqldb-udf/src/main/java/io/confluent/ksql/function/FunctionCategory.java

Add `INT_FROM_BYTES`, `BIGINT_FROM_BYTES`, and `DOUBLE_FROM_BYTES` functions.
All functions use the byte order `BIG_ENDIAN` as default. A 2nd parameter is accepted to specify the byte order:
```
SELECT INT_FROM_BYTES(b) ...
SELECT INT_FROM_BYTES(b, 'BIG_ENDIAN') ...
SELECT INT_FROM_BYTES(b, 'LITTLE_ENDIAN') ...
```

feat: Add int/bigint/double conversion functions from bytes 

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryLimitHARoutingTest.java

makes `PullQueryLimitHARoutingTest` more stable by ensuring that lags are reported for all the test apps

fix: make PullQueryLimitHARoutingTest more stable

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactoryTest.java

We want to make sure that no other query is running before changing `processing.guarantee` with the new `ALTER SYSTEM` query
```
ksql>  alter system 'processing.guarantee'='exactly_once';
Could not write the statement 'alter system 'processing.guarantee'='exactly_once';' into the command topic.
Caused by: Invalid value null for configuration Failed to set
processing.guarantee to exactly_once. Please terminate all running queries
before attempting to set processing.guarantee
```
unit test + manual testing

feat: verify no other query is running before putting into command topic

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactory.java

We decided to prevent users from modifying the server-level `processing.guarantee` config unless there are no persistent queries running at the time which would be affected by this change, to avoid mixed processing of exactly-once and at-least-once semantics. We should make sure to state clearly the reasoning behind this

chore: clarify reasoning behind preventing live updates to `processing.guarantee` config

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ConsistencyOffsetVectorFunctionalTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/BlockingQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QuerySubscriber.java

I added more logs and made a change to the code that adds the consistency token to the queue. 
The problem stems from the fact that rows are streamed asynchronously and the limit handler is also set asynchronously. Hence there is a race on whether the limit handler is called first or not.
The code path where this was happening before would not be called if the limit handler was called first on an empty queue. So, what might be happening is that we poll the last row of data from the queue but the complete flag has not been set yet hence the consistency token is not added. Then, the limit handler gets called and sets the complete flag and also initiates complete on the subscriber. Only then, can the consistency token be added but we have already completed the response so it is lost.
It is …

fix: maybe fix flaky test

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java

Now that we have the NamedTopology info in the StreamsException class, we should check whether a given error has originated from a specific query and add it to that query's error queue rather than the runtime error queue instead

chore: get query-specific errors from StreamsException

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java

we shouldn't be trying to clean up named topologies for transient queries when shared runtimes are on. 

fix: clean up transient queries when using shared runtimes

---

pom.xml

There is a security vulnerability with log4j versions prior to 2.15.0, we dont use it for logging but it did show up in the jars so here  we bump the confluent patch of log4j which removes any transitive dependencies on log4j 2.10. Note that trying to exclude does not work since the exclusion logic is not recursive.

fix: explicitly set confluent log4j version to 1.2.17-cp5

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistry.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java

Once the system configs are altered we need to restart the runtimes to pick up the change. This PR is dependend on https://github.com/confluentinc/ksql/pull/8434
unit tests

feat: restart runtime after alter system query

---

docs/operate-and-deploy/changelog.md

Corrects link on this page: https://docs.ksqldb.io/en/latest/operate-and-deploy/changelog/

docs: fix link to 0.22 announcement post

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClientFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/ServiceContextFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/FileWatcher.java
ksqldb-engine/src/test/java/io/confluent/ksql/embedded/KsqlContextTestUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/TestServiceContext.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/FileWatcherTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/services/ConnectClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProvider.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/KsqlSecurityContextProvider.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/Server.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/RestServiceContextFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProviderTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

This PR broadens the types of Connect deployments that ksqlDB's connector integration can work with. Specifically, this PR:
* adds new configs for specifying custom HTTP basic auth credentials to be sent with ksql connector requests. If not specified, then ksqlDB will continue to forward the incoming request auth header as it does today.
* adds support for automatically reloading file-based basic auth credentials (see above), if configured. This functionality is off by default in order to avoid the background thread that monitors for file changes.
* adds a configuration to specify whether missing/malformed credentials (see above) should result in an error or not. By default, an error will be thrown, but this PR adds a config to control this behavior to support use cases where, e.g., the …

feat: custom auth configs for ksql connector requests

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/InternalKsqlClientFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/services/InternalKsqlClientFactoryTest.java

Related to #8505.  Since we currently close connections upon being finished with a request, this disables multiplexing so that shared connections are not closed, affecting other requests.
Ran locally.

fix: Prevents internal http2 requests from having shared connections closed

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/PullQueryExecutionUtil.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/SlidingWindowRateLimiter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/query/QueryExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/ConcurrencyLimiter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/RateLimiter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/SlidingWindowRateLimiterTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/SystemAuthenticationFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/query/QueryExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/RateLimiterTest.java

It was previously not possible to observe the state of the limiters (how much remains toward the limit) or the number of requests that have been rejected. This work corrects that.
I write unit tests and also checked the JMX metrics in a locally run ksql. I did not add an integration test for the metrics because ksql keeps its metrics in a static map, so there can be no isolation between tests. I decided not to tackle a full-blown refactor of the metrics framework right now.

chore: Add metrics for push and pull limiters

---

ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-with-limit-clause.json
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java

Disallows persistent query limit clause. Throws an error message saying `CREATE STREAM/TABLE AS SELECT statements don't support LIMIT clause.` for `CSAS/CTAS` statements
unit tests
Rest query validation tests

fix: disallow persistent query limit clause

---

ksqldb-functional-tests/src/test/resources/historical_plans/headers_-_Can_use_header_columns_in_filters/7.2.0_1639450823104/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/headers_-_Can_use_header_columns_in_filters/7.2.0_1639450823104/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/headers_-_Can_use_header_columns_in_filters/7.2.0_1639450823104/topology
ksqldb-functional-tests/src/test/resources/historical_plans/headers_-_Can_use_header_columns_in_functions/7.2.0_1639450823058/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/headers_-_Can_use_header_columns_in_functions/7.2.0_1639450823058/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/headers_-_Can_use_header_columns_in_functions/7.2.0_1639450823058/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/headers.json
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4

Fixes #8446 
Changed some QTTs to use these as column names

fix: make HEADER and HEADERS non-reserved

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactoryTest.java

The `Alter System` work work as expected in the old runtime. We want to disallow this if the feature flag is not set.
Existing tests

feat: throw exception if feature flag is off

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistry.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java

this is about cleaning up the validation runtimes. when creating the sandbox there was some issues where the runtimes would get made at creation but the sandbox execution context doesn’t get cleaned up. Now I don’t make the validation runtimes until a query is issued. And ensue that all the runtimes get cleaned up.

fix: close all runtimes in sandbox

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java

Fix for the query-level metrics such as [Query Status](https://ccloud-production.datadoghq.com/dashboard/m59-7gm-x4j/ksql-node-health?fullscreen_end_ts=1639468089988&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1636876089988&fullscreen_widget=8638173689799481&from_ts=1636876064877&to_ts=1639468064877&live=true) which aren't coming through due to the fact that we aren't registering a `StateListener` on the shared `KafkaStreams` runtime. This patch sets a `StateListener` that loops over all queries in the runtime and invokes the `#onStateChange` callback on their individual query listeners.
Also includes a miscellaneous set of minor fixes/cleanups in the BinPackedPersistentQueryMetadataImpl and SharedKafkaStreamsRuntime interface/subclasses

fix: invoke per-query listeners upon state change in shared runtime

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistry.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java

After https://github.com/confluentinc/ksql/pull/8498 we needed to do some refactoring for the restart runtime.
Unit tests
- Is there any way we can do an end to end test to verify this works?

fix: refactoring properties replacement before restarting runtime

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/RuntimeAssignor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedBinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTestUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/RuntimeAssignorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/ReplaceWithSharedRuntimesIntTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryBuilderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImplTest.java

Move the runtime selection into the query plan. The runtime should be assigned and then validated. If validated correctly it will be assigned the same runtime and put on the cmd topic. If not validated the actual assignor will not not be affected and will move on to the next query. 
When receiving the plan to build the query the query build will find the runtime with that ID. If it doesn't exist it will make a new one.
Right now its doesn't check for config compatibility which is how it currently is. There needs to be some more work for config checking, but that should be a follow up PR. 

feat: new runtime selection

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandIdAssigner.java

The command id for the `alter system` query was using a uuid plus the query in string form. This was leading to the server to crash as the `/` is not allowed as a command id due to the following line `final String[] splitOnSlash = fromString.split("/", 3);`. 
This changes the command id to only use a random uuid as originally planned. 
manual testing

fix: only use uuid as alter system command id

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java

If the validation node goes down or needs to replay the cmd topic we need to pick up the running queries from cmd topic an put them in the assignor. This will make sure that the runtime assignor will always be in sync with the runtimes using the Engine Context.

fix: Restore runtime assignor

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ConsistencyOffsetVectorFunctionalTest.java
ksqldb-api-reactive-streams-tck/src/test/java/io/confluent/ksql/api/tck/BlockingQueryPublisherVerificationTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/PullQueryQueue.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/PullQueryQueueTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/BlockingQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/DelimitedQueryStreamResponseWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/JsonQueryStreamResponseWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/JsonStreamedRowResponseWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryHandle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamResponseWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QuerySubscriber.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/QueryPublisher.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/Http2OnlyStreamTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestQueryPublisher.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/RunnerUtils.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/utils/ListRowGenerator.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/utils/RowGenerator.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryResponseMetadata.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/StreamedRow.java

This is part of an effort to consolidate endpoints.  What this aims to do is add support for StreamedRow to `/query-stream`.  This should allow a followup change to install the same handler for `/query`.  Then we can support multiple paths under the same handling logic.
Also, this allows handling of http 1.1 requests using `/query-stream`.
Ran tests and manually tested.

feat: Adds support to /query-stream for http1.1 and StreamedRow json format

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java

Now that we have the runtime assignor we don't need to keep checking the sources in the runtime. There will not be queries assigned to `SharedKafkaStreamRuntime` with the same sources. If by some bug there is the add will fail.

feat: don't book keep sources in runtime as well

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PushQueryConfigRoutingOptions.java

Allows scalable push queries to be set via sercer config, not just via the request.
Tested the change manually and ran tests.

fix: Allow disabling Scalable Push Query ALOS to be set via config

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/PullQueryQueue.java

fixes https://github.com/confluentinc/ksql/issues/8517 by making adding rows to pull query queue threadsafe
I ran `io.confluent.ksql.rest.integration.PullQueryLimitHARoutingTest.shouldReturnLimitRowsMultiHostSetupTable` locally ~90 times and it never failed. Before this fix, it used to fail before ~25 runs

fix: make adding to pull query queue threadsafe

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/CommandParserTest.java

Fixes bug in migrations tool where using variable substitution for `CREATE CONNECTOR` statements fail. This is what happens when you try something like `CREATE SOURCE CONNECTOR ${name} WITH ...`:
```
Exception in thread "main" java.lang.UnsupportedOperationException: not yet implemented
at io.confluent.ksql.parser.AstBuilder$Visitor.aggregateResult(AstBuilder.java:1339)
at io.confluent.ksql.parser.AstBuilder$Visitor.aggregateResult(AstBuilder.java:218)
at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:47)
at io.confluent.ksql.parser.SqlBaseBaseVisitor.visitVariableLiteral(SqlBaseBaseVisitor.java:958)
at io.confluent.ksql.parser.SqlBaseParser$VariableLiteralContext.accept(SqlBaseParser.java:8224)
at …
```

fix: variable substitution with CREATE CONNECTOR in migrations tool

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

Typo in REGEXP_EXTRACT section (`substring` instead of `subtring`)
No code change, only documentation correction

docs: Corrected typo in REGEXP_EXTRACT section

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporter.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporterTest.java

We're adding a metric (`max_task_storage_used_bytes`) that takes the maximum task disk usage on a node and emits that. This allows users to see the maximum disk space a single task is taking up without having to filter through all the task metrics on their side.
We're also adding a metric `num_stateful_tasks` that records the number of stateful tasks on a node. These two metrics combined will allow users to better understand their task work distribution and understand how to tune their system for their needs. 
unit tests, tested on jconsole

feat: add max task usage and num stateful tasks metrics

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryConsistencyFunctionalTest.java

Making use of static task assignment to avoid issues due to rebalances. This is basically copying the fix that was previously proposed in the PullQueryConsistencyRoutingFunctionalTest (#8351).

fix: make PullQueryConsistencyFunctionalTest more reliable

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/DelimitedInsertsStreamResponseWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/InsertsStreamHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/JsonInsertsStreamResponseWriter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java
ksqldb-test-util/src/main/resources/log4j.properties

the `shouldStreamInserts` test is flaky (see https://jenkins.confluent.io/job/confluentinc/job/ksql/job/master/9268/testReport/junit/io.confluent.ksql.api/TlsTest/shouldStreamInserts/) and we added some logging in #8092 to help this and now I see that it's timing out in the insert part itself (never getting a response) so I've added logging to help dig into that...
looks like this is going to be a multi-step debugging process!
**NOTE**: I've also changed our test configuration logging for the `io.confluent.ksql.api.server` package to `DEBUG` because some of the logging that I added was in production code
Ran the test and saw the logs

test: add more logging to flaky stream insert test

---

ksqldb-engine/src/main/java/io/confluent/ksql/topic/TopicDeleteInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/topic/TopicDeleteInjectorTest.java

This PR fixes https://github.com/confluentinc/ksql/issues/8548.
I added a new unit test and checked manually that `DROP STREAM IF EXISTS DELETE TOPIC` works as expected now.

fix: Fix DROP STREAM IF EXISTS DELETE TOPIC

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedKafkaTopicClient.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedServiceContext.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedKafkaTopicClientTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/FakeKafkaClientSupplier.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

If replication factor `-1` is used (implying to use the broker default) the
SandboxKafkaTopicClient created a mocked topic with replication factor 0
instead of using the broker default.
If multiple statement are submitted as once (ie, via a file), later
statement could inherit the incorrect replication factor and thus fail,
which fails all statements in the file.
Closes #4800

fix: SandboxKafkaTopicClient should use default replication factor if applicable

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/PullQueryQueue.java

As @Gerrrr mentioned in #8517, there are multiple current issues with our current mechanism:
- First of all, PullQueryQueue #acceptRow is synchronized for all pull queries, not just the ones that have LIMIT clause.
- The entire method is a critical section which is very much suboptimal given we run a callback there. The only practical usage of that callback is to publish messages, so we'd rather not do that under a lock.
- AFAIU a lock is not even needed in that case - we just need to update totalRowsQueued with CAS. Without contention there is no additional overhead required to ensure thread-safety.
This PR fixes #8517 

feat: un-synchronize PullQueryQueue row queuing when limit absent

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClientFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/TestServiceContext.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/services/TestRestServiceContextFactory.java

Fixes https://github.com/confluentinc/ksql/issues/6631.
This PR adds support for TLS configs to configure ksqlDB requests to an external Connect deployment. Configs prefixed with `ksql.connect.` are applied only to ksqlDB's Connect client. Non-prefixed configs are also applied to ksqlDB's Connect client by default, similar to how ksqlDB handles its Schema Registry TLS configs today.
Example configs:
```
ksql.connect.url=https://localhost:8443
ksql.connect.ssl.truststore.location=/path/to/client.truststore.jks
ksql.connect.ssl.truststore.password=<some password here>
ksql.connect.ssl.truststore.type=JKS
ksql.connect.ssl.endpoint.identification.algorithm=none
```
I wanted to add an integration test but hit a few dead ends trying to configure an embedded Connect with custom TLS configs. Open …

feat: add support for connect specific https configs

---

ksqldb-engine/src/main/java/io/confluent/ksql/security/DefaultKsqlPrincipal.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlPrincipal.java
ksqldb-engine/src/test/java/io/confluent/ksql/security/DefaultKsqlPrincipalTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/AuthenticationPlugin.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/AuthenticationPluginHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/SystemAuthenticationHandler.java

Minor change to expose the original Principal wrapped inside DefaultKsqlPrincipal, so that custom extensions can access the original principal even after wrapping. This PR also updates the existing code to always wrap the original principal in DefaultKsqlPrincipal, and have DefaultKsqlPrincipal pass through the custom properties of the original principal, even if the original principal is a KsqlPrincipal. This change is made because otherwise we'd have two patterns for custom extensions to access original principals:
* have the original principal implement KsqlPrincipal (comes at no cost since KsqlPrincipal has a default implementation for the only method beyond the Principal interface that it extends), which causes the original principal to be passed through (throughout the ksql engine) …

chore: expose original principal from DefaultKsqlPrincipal (MINOR)

---

docs/concepts/time-and-windows-in-ksqldb-queries.md

First draft of the new "Windows emission" section, cribbed from [Windows behavior – quick doc suggestion](https://docs.google.com/document/d/1P_qyxIFmGqFP4Nhs-SP4OaU7pkFlxt6hxASub3S67Q8/edit#).
Apologies for the HTML goo. The tables render like this:

docs: add details on window emission (DOCS-11621)

---

ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/ReservedWordMetaTest.java

fixes #8591 and also adds a test to make sure we don't accidentally add more words to the reserved list and make these kind of breaking changes 
(see also #8490 for context)
The meta-test that this adds iterates the entire vocabulary and makes sure that the words are either reserved explicitly or part of the nonReserved rule.

fix: add GRACE and PERIOD to the nonReserved and automate testing

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/QueryStateMetricsReportingListener.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/TransientQueryMetadata.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TerminateTransientQueryFunctionalTest.java

In tests, at times, a double call was being made to `QueryStateMetricsReportingListener.onDeregister` which would cause an NPE the second time.  This was causing terminations to fail, such as in `TerminateTransientQueryFunctionalTest`.
The two calls were caused by first the termination, which calls `TransientQueryMetadata.close` and issues a complete event to be send to the client, causing it to close the connection and end the request, which in turn caused a `TransientQueryMetadata.close` to be called again.  If each was done just right, the `onDeregister` call would complete in one case and then the second would fail.  Other times, they would each run, finding the query, and not get an NPE.
This should ensure that whether the query ends entirely by the client or as a result of a …

fix: Fixes an NPE which was causing terminate to fail

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/KeyedTableLookupOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/KeyedWindowedTableLookupOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/TableScanOperator.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/operators/WindowedTableScanOperator.java
ksqldb-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializationFunctionalTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/operators/KeyedTableLookupOperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/operators/KeyedWindowedTableLookupOperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/operators/TableScanOperatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/pull/operators/WindowedTableScanOperatorTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterialization.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/MaterializedTable.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/MaterializedWindowedTable.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedQueryResult.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedSessionTable.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedSessionTableIQv2.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedTable.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedTableIQv2.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedWindowTable.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedWindowTableIQv2.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedSessionTableIQv2Test.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedSessionTableTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedTableIQv2Test.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedTableTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedWindowTableIQv2Test.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedWindowTableTest.java

Created a new return type `KsMaterializedQueryResult` for `table.get` methods that query the streams store to return, besides the KeyValue, also the position used for consistency. Previously, the methods returned a single object, a list, an iterator but all were converted to iterators. So I changed the return type to always be an iterator. 
Note, this is only an API change. The actual using of the position will be done in a separate PR
Updated all unit tests for IQv1 and IQv2

feat: Change API to return Position from Streams

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java

The bugfix introduces a helper method **originalsWithPrefixOverride** similar to existing **valuesWithPrefixOverride**. Contrary to the latter it does not limit the result to defined configuration entries. The new method is used instead of **originals** to provide the values for Kafka configuration in KsqlConfig.
Unit test added to KsqlConfigTest failing in unmodified class.

fix: Streams overrides bugfix

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java

Without shared runtimes: `_confluent-ksql-default_query_CSAS_CART_EVENT_PRODUCT_1-Join-repartition`
shared runtimes without change: `_confluent-ksql-default_query_-1-CSAS_CART_EVENT_PRODUCT_1-Join-repartition`
shared runtimes with change: `_confluent-ksql-default_query-CSAS_CART_EVENT_PRODUCT_1-Join-repartition`
Will remove the runtime Id from internal topics so that we will be able to use topic in a different application with later work

feat: uses internal topics prefix for shared runtimes

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/StatementParser.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/ClusterTerminator.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java

This PR brings 939a75f01d1765f1714aa6862ca68b95f0d5f432  (https://github.com/confluentinc/ksql/pull/8546) back to fix `master` build. I assume that this commit was part of https://github.com/confluentinc/ksql/pull/8599 by accident.
/cc @ableegoldman
Re-ran CI.

chore: Fix findbugs errors (#8546)

---

ksqldb-engine/src/main/java/io/confluent/ksql/connect/ConnectRequestHeadersExtension.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/ConnectClientFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClientFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/ServiceContextFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/embedded/KsqlContextTestUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/TestServiceContext.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/ApiSecurityContext.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/DefaultApiSecurityContext.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProvider.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/RestServiceContextFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProviderTest.java

This PR builds on the custom connect headers extension introduced in https://github.com/confluentinc/ksql/pull/8357. Three changes in this PR:
* The auth header used by ksqlDB for connector requests is now configurable as well. 
* The principal associated with the incoming ksql request is no longer piped through to the extension, as the interface for custom headers no longer accepts the KsqlPrincipal as a parameter. (We thought we had a use case for this but turns out we don't, so I've cleaned up the code.)
* Incoming request headers are now piped through to the extension instead, as the custom auth header might be interested in these.
Unit tests + manual.

feat: allow custom connect auth header configuration

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/json/JsonKeys.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/json/JsonKeysTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/json_keys_-_extract_keys_from_a_json_object/7.2.0_1642513802022/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/json_keys_-_extract_keys_from_a_json_object/7.2.0_1642513802022/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/json_keys_-_extract_keys_from_a_json_object/7.2.0_1642513802022/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/json_keys.json

This PR introduces a new UDF - `json_keys` that returns an array of object keys. See the corresponding section in [KIP-59](https://github.com/confluentinc/ksql/blob/4cd79269dcb217e5b43aa47ee420a85b720f72fb/design-proposals/klip-59-json-functions.md#json_keys) for more details.
Added unit and functional tests.

feat: add json_keys UDF

---

pom.xml

* This version allows for use of the flag -Dmaven.gitcommitid.nativegit=true
to allow developers to use native git rather than JGit.
* This version allows for use of the flag -Dmaven.gitcommitid.nativegit=true
to allow developers to use native git rather than JGit.

build: Update Git Commit Id plugin

---

docker-compose.yml

Tutorial - https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/installing/
Step 3 previously broken due to using deprecated zookeeper connection instead of bootstrap_servers

fix: make tutorial work

---

docs/reference/server-configuration.md

Make `pint merge` happy by updating links to match what's in master.

docs: fix merge conflict from 7.1.x to master (DOCS-11772)

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/locator/AllHostsLocator.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/locator/AllHostsLocatorTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ClusterStatusResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/DiscoverRemoteHostsUtil.java

Apparently we used the StreamsMetadataImpl.NOT_AVAILABLE variable throughout the ksql repo, but we very much should not have been since this is actually not in the public API of Streams. The risk of using internal APIs is that they have no public contract or compatability guarantees of any kind, and can for example be removed at any time without deprecation/warning.
Unfortunately this is exactly what just happened to `StreamsMetadataImpl.NOT_AVAILABLE`, but at least we can easily address this since it was pretty much just a convenience to begin with used for comparisons, and we no longer return any metadata for unavailable clients rather than build up this metadata and then just filter it out on the user side (ie ksql)

fix: remove usages of internal Streams API/variable that was removed upstream

---

design-proposals/README.md
design-proposals/klip-59-json-functions.md

KLIP for adding new JSON functions.

docs: klip-59: JSON functions

---

ksqldb-common/src/main/java/io/confluent/ksql/util/QueryApplicationId.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/locator/AllHostsLocator.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/restore/KsqlRestoreCommandTopic.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/PersistentQueryCleanupImpl.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/PersistentQueryCleanupImplTest.java

https://github.com/confluentinc/ksql/pull/8607 made it so the app id was not always the prefix for internal topics now we clean up based on that not the app id 

fix: clean up custom prefixed internal topics

---

ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/locator/AllHostsLocatorTest.java

Fixes the AllHostsLocatorTest by adding back the metadata variable.

fix: Fixes the AllHostsLocatorTest

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/RuntimeAssignor.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/RuntimeAssignorTest.java

Don't hit an immutability issue. the query returns its list of sources in an immutable set so we need to add them all to the existing set instead of replace them
ksql> drop stream filtered_users;
Message                                                      
--------------------------------------------------------------
Source `FILTERED_USERS` (topic: FILTERED_USERS) was dropped. 
--------------------------------------------------------------
instead of
ksql> drop table users_agg_2;
Message                              
--------------------------------------
Source `USERS_AGG_2` does not exist. 
--------------------------------------
added coverage in unit tests

fix: don't throw on drop

---

docs/tutorials/event-driven-microservice.md

Running `docker-compose up` with the given docker-compose.yml results in schema-registry exiting with an error about not finding bootstrap servers.
I ran `docker-compose up` with the modified version and it worked.

docs: add missing environment variable in event-driven-microservice tutorial

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/PersistentQueryCleanupImpl.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/PersistentQueryCleanupImplTest.java

we were looking at all dir for queries and removing all the ones that were being actively used. but for named topologies if there was no state then we would not see that runtime as being used and we would delete it out from under streams. Streams would get confused and when you then tried to drop the query for real everything would hang
Manual testing

fix: keep shared runtime dirs even if no query has state

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java

error message for named topologies is different and is wrapped in the streams exception now

fix: error message for named topologies is different

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/locator/AllHostsLocator.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/locator/AllHostsLocatorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/ClusterStatusResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/DiscoverRemoteHostsUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/HeartbeatAgentTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/DiscoverRemoteHostsUtilTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStore.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsStateStoreTest.java

a rebase of https://github.com/confluentinc/ksql/pull/8579

fix: use topology-specific IQ APIs

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/type-coercion.md
docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md
docs/how-to-guides/update-a-running-persistent-query.md
docs/reference/serialization.md
docs/reference/sql/appendix.md
docs/reference/sql/data-types.md
docs/reference/user-defined-functions.md

Restore BYTES and ARRAY_CONCAT content that was reverted in https://github.com/confluentinc/ksql/pull/8016 for v0.20.0.

docs: restore BYTES and ARRAY_CONCAT content (DOCS-11937)

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java

When shared runtimes are needed they are added but currently they are not removed after all the queries have stopped processing. When runtimes no longer have queries running in them we should close them

feat: remove old runtimes

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java

When a query using the old runtimes is recreated with the shared runtimes flag on then it should still use the shared runtimes.  This PR makes it so that the query will stay in the appropriate runtime

fix: recreating old queries in the old runtime will still use the old runtimes

---

ksqldb-docker/pom.xml

Adds the docker plugin to pom.xml as described in https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/2535687371/Support+for+repo-specific+callbacks+during+release+build#Example-pom.xml-modifications
in order to build the on prem docker images for ksqldb

build: add docker plugin for release stabilization

---

ksqldb-engine/src/main/java/io/confluent/ksql/connect/ConnectRequestHeadersExtension.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/DefaultKsqlPrincipal.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlPrincipal.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/ConnectClientFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClientFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/ServiceContextFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/embedded/KsqlContextTestUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientFactoryTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/TestServiceContext.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/ApiUser.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/AuthenticationPluginHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/DefaultApiSecurityContext.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/JaasAuthProvider.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/JaasPrincipal.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/SystemAuthenticationHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProvider.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/RestServiceContextFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProviderTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/services/TestRestServiceContextFactory.java

One main change in this PR:
* KsqlPrincipal now carries the incoming request IP address (as obtained from the routing context). This IP address is set before the KsqlPrincipal is piped throughout the ksqlDB engine. As part of doing this, the ApiUser interface was updated to return a DefaultKsqlPrincipal, rather than a KsqlPrincipal.
And two minor ones:
* KsqlPrincipal is made available to the ConnectRequestHeadersExtension interface, which requires piping the principal throughout various parts of the request flow.
* the subject obtained from the HTTP basic auth handler (JaasAuthProvider) is always wrapped inside a DefaultKsqlPrincipal, regardless of whether the incoming subject already implements KsqlPrincipal or not, in order to be consistent with the AuthenticationPluginHandler.
Unit + …

chore: pipe user IP via KsqlPrincipal to connect headers extension

---

ksqldb-docker/pom.xml

Fix packaging/master by only building the docker image when the docker profile is activated on Jenkins, for more context see https://confluent.slack.com/archives/C8486MR1C/p1643918373509689
Summary of thread is that there is no docker build support out in packaging builder VMs, so we skip building docker globally,  and only build it when we activate the docker profile.

fix: skip docker build for packaging

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/PropertiesList.java

This forces any queries coming into the shared runtimes to not have overridden the server level props. If the query will not be going into the new shared runtimes (i.e. is a `create or replace` of an old query) it will not be held to those standards.

feat: allow for only Gen 1 create or replace queries with server level configs via rest api, bars all gen 2 queries

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/PropertiesList.java

When a set cmd checks to see if the config is valid it will now also make sure if it is a query level config for gen 2 queries

feat: include checking the the config during validation of SET

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactoryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

When we restart a query with `create or replace` stmt we would like to use the previous runtime that query was executed on. Today if we `create or replace` an existing query that's running on the old, non-shared runtime, it will still come up in a non shared runtime. However it's plan written to the cmd topic will indicate that it should use the new shared runtime.
To fix this, when executing the `create or replace` stmt we would only create the new query in the new runtime only if 1) a shared runtime id is assigned, 2) The queries config has the shared runtimes FF enabled and 3) the old query either does not exist or it has already been running on the shared runtime.
Test to make sure the cmd gen'd is for a gen 1 query in the case it is being replaced. And that is doesn't happen to a gen …

fix: when a isolated query is restarted then it should stay isolated

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java

To avoid having a broken query in the cmd topic we should only do the check for query level configs during validation

fix: only check configs on validation

---

ksqldb-common/src/main/java/io/confluent/ksql/util/DecimalUtil.java
ksqldb-common/src/test/java/io/confluent/ksql/util/DecimalUtilTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_decimal_between_-1_and_1/7.2.0_1644051383155/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_decimal_between_-1_and_1/7.2.0_1644051383155/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/decimal_-_decimal_between_-1_and_1/7.2.0_1644051383155/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/decimal.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json

Fix for bug in https://github.com/confluentinc/ksql/issues/8413 where ksqldb doesn't allow non-zero decimals between (-0.1, 0.1) to be inserted or queried. The root cause is that we use BigDecimal to parse the string, and it has a different behavior for precision than the SQL standard for (-1, 1): "0.005" has precision 1 in BigDecimal, whereas SQL expects it to have precision 4 (total number of digits). For anything in (-0.1, 0.1) this causes the code to throw since scale is greater than precision.
Something to note: the fix introduces a quirk in how decimals starting with a period are processed: "0.005" and ".005" are both treated as having precision 4, whereas SQL expects precision 3 for the latter. To fix this we'd have to stop using BigDecimal as the internal representation (since it …

fix: bug preventing decimals in (-1, 1) from being inserted / queried

---

docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md
docs/developer-guide/ksqldb-rest-api/query-endpoint.md

Minor docs fix: these two curl examples are missing line continuation characters so they don't work when copy-pasted.

docs: fix line continuation chars in curl examples

---

docs/developer-guide/ksqldb-clients/java-client.md

We no longer use beta packaging builds for our dependencies anymore, we now publish those dependency jars directly to  'https://ksqldb-maven.s3.amazonaws.com/maven/' , so we can just remove the beta packaging urls all together

docs: remove beta packages url

---

docs/developer-guide/ksqldb-clients/java-client.md

From https://github.com/confluentinc/ksql/pull/8729.
We no longer use beta packaging builds for our dependencies anymore, we now publish those dependency jars directly to  'https://ksqldb-maven.s3.amazonaws.com/maven/' , so we can just remove the beta packaging urls all together.

docs: cherry-pick: remove beta packages url (#8729)

---

mkdocs.yml

Similar reasoning to https://github.com/confluentinc/ksql/pull/8729, but essentially we no longer use beta tags for our dependency, so we don't need these tokens to try find the correct beta packaging url. Intsead we just use https://ksqldb-maven.s3.amazonaws.com/maven/ for everything

docs: remove beta tag tokens

---

ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-streams.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-with-headers.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-with-limit-clause.json
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/JsonStreamedRowResponseWriterTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/QueryStreamHandlerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryLimitHARoutingTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriterTest.java

fixes #8554 
Stream pull queries current produce invalid json #8554.  
This fix produces a final message for stream pull queries saying "Query Completed".  Normal pull queries keep a row buffered to avoid this bug so that they know if there is another row that follows, allowing them to output a comma or not.  While I could have ported stream pull queries over to the logic of normal pull queries, this would have been a much larger change since stream pull queries resemble push queries much more than pull. Also, a final message is just part of the API, so should be handled regardless of the nature of push, pull, etc.
Tested examples given in the issue and ran existing tests.

fix: Gives a query completed message for stream pull queries

---

pom.xml

Updating netty to 4.1.72 and also netty-tcnative-boringssl-static to 2.0.46

chore: update netty to 4.1.72.Final to account for CVE

---

pom.xml

Still not sure if we could actually "unpin" the `tcnative` version and rely on transitive version resolution? But it should be a good intermediate step to just add a commend to avoid pulling in incompatible versions in the future.

chore: add comment about netty/tcnative version dependeny

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/BackupReplayFile.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicBackupImpl.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/BackupReplayFileTest.java

This patch makes writes to the backup file atomic. Writing a record now will either
complete in full, or not at all. This is achieved by writing the record to a dirty
copy, and then renaming the dirty copy to the live backup file. To maintain the dirty
copy without creating a new copy on each write, we create a temporary hardlink to
the live copy before renaming the dirty copy, and then rename the link to the dirty
copy. Finally, the write appends the record to the dirty copy (which was the old
live copy) to keep it in sync

fix: make writes to the backup file atomic

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/RuntimeAssignor.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/RuntimeAssignorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryBuilderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/PropertiesList.java

During a refactor we missed a couple of issue. 
1. removing queries for the map when stoping the queries.
2. adding the topology to the sandbox to properly validate
3. registering the query outside for validation runtimes.

fix: various fixes for tracking shared runtime queries in validation

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporter.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporterTest.java

[KCI-1455](https://confluentinc.atlassian.net/browse/KCI-1455)
The metric name `max_used_task_storage_bytes` was conflicting with the `TASK_STORAGE_USED_BYTES` in `getMaxTaskUsage(metricRegistry)` and was thus leading to an infinite loop. 
unit test

fix: change conflicting metrics name that leads to infinite loop

---

ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientTest.java

Commit a33b1e68426ae61fb8bf45c267f198d3eb3d6ff3
has changed the `create` method signature without
deprecating the old one first, causing the drift benchmarks
to fail with:
```
java.lang.NoSuchMethodError: io.confluent.ksql.rest.client.KsqlRestClient.create(
java/lang/String;
java/util/Map;
java/util/Map;
java/util/Optional;
)
io/confluent/ksql/rest/client/KsqlRestClient;
```
We're just adding back the missing signagure
No test changes, just added a basic sanity check that we don't remove the signature later down the line

fix: reinstate the old KsqlRestClient.create overload

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java

If the validation fails due to an exception it can leave the runtimes lying around and this can cause issues for future validations until the cleaner service can get to them. To prevent that we should just clean them up even if there is an exception. 

fix: always close validation runtimes even on an exception

---

ksqldb-examples/src/main/java/io/confluent/ksql/datagen/DataGen.java

We have changed our SpotBugs version to 4.5.3 which was causing:
```
[ERROR] Medium: Do not catch NullPointerException like in io.confluent.ksql.datagen.DataGen$Arguments$Builder.build() [io.confluent.ksql.datagen.DataGen$Arguments$Builder] At DataGen.java:[line 440] DCN_NULLPOINTER_EXCEPTION
[INFO]
```
This change is SpotBugs compliant way of doing the same thing
- explicit null checks, rather than delegating to a method
that checks for null and throws NPE
Verified that spotbugs is happy with the new code

fix: pass DCN_NULLPOINTER_EXCEPTION spotbugs error

---

ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/AnalysisTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/StatementRewriterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/lambda/ReduceTest.java
pom.xml

* ignore all spotbugs warnings in tests that only occur with Java 11
* remove duplicate commons-compress dependency declaration causing maven build warnings

fix: spotbugs warnings with Java 11

---

pom.xml

* common is on a newer version of mockito already
* overriding the version also prevents using the mockito-bom in
https://github.com/confluentinc/common/pull/433 since 3.x doesn't
publish a bom

chore: inherit mockito version from common

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporter.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporterTest.java

When registering the saturation metric we used to parse the Thread name to get the query ID. When we use shared runtimes the query ID is not in the Thread name. Instead that is in the Task ID, so we will just try to parse that to see if we can find the Query ID  first then fall back to the old approach. Then we don't have to worry about passing through a config. 
Just add a unit test with no Query ID in the thread name put it is in the Task ID

fix: check for the queryId in the Task ID for registering saturation metric

---

docs/operate-and-deploy/migrations-tool.md
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/ClientOptions.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientOptionsImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientBasicAuthTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTlsTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ClientOptionsImplTest.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsUtil.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/MigrationsUtilTest.java

This PR adds support for specifying custom request headers for requests issued to the ksqlDB server via the Java client, and also when applying migrations with the ksql migrations tool.
When creating a Java client instance, the new `ClientOptions#setRequestHeaders(Map<String,String>)` method can be used to set custom request headers:
```
/**
* Sets custom request headers to be sent with requests to the ksqlDB server.
* These headers are in addition to any automatic headers such as the
* authorization header.
*
* <p>If this method is called more than once, only the headers passed on
* the last invocation will be used. To update existing custom headers,
* use this method in combination with {@link ClientOptions#getRequestHeaders()}.
*
* <p>In case of overlap between these custom headers and …
```

feat: support custom request headers from java client and migrations tool

---

ksqldb-benchmark/pom.xml
pom.xml

Switches plugins used to build the benchmarks.jar.
This will allow developers to skip all assembly work with `mvn -Dassembly.skipAssembly <goals>`

chore: Switching from shade to assembly plugin for ksqldb-benchmarks.

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/restore/KsqlRestoreCommandTopic.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/RestoreCommandTopicMultipleKafkasIntegrationTest.java

We recently updated the ksql command topic to make sure that it's using the command topic configs that can be passed in through the properties file, https://github.com/confluentinc/ksql/pull/8742. With these changes, we needed to update the restore command topic tool to make sure it's using the same configs as would be used when we create the command topic. This ensures that if the tool is used on a ksql that has its command topic on a separate kafka from the rest of its topics, the command topic will be properly recreated on the separate kafka.
Added an integration test, the same tests as we currently do for the restore tool but separates the command topic onto a different kafka broker

fix: update restore command topic tool to work with command topic configs

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/QueryAnonymizerTest.java

Run the inner class's tests.
I found this will poking at the build generally.  To verify the fix, I ran the test manually in IntelliJ.  Without the change, the enclosed class's tests do not run.

chore: Fixing QueryAnonymizerTest so that it runs its enclosed class.

---

pom.xml

There is a known CVE (CVE-2021-4104) for log4j12 regarding
the JMS appender. ksqlDB is not affected by the CVE since
ksqlDB does not enable the JMS appender as stated under
https://support.confluent.io/hc/en-us/articles/4412615410580-December-2021-Log4j-Vulnerabilities-Advisory
Nevertheless versions of confluent-log4j higher than 1.2.17-cp6
removed the JMSAppender class completely. Thus, it is reasonable
to upgrade the confluent-log4j to 1.2.17-cp9 (latest version at
the creation time of this commit)

chore: upgrade confluent-log4j to 1.2.17-cp9

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/ClientOptions.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientOptionsImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ConsistencyOffsetVectorFunctionalTest.java
ksqldb-common/src/main/java/io/confluent/ksql/util/ClientConfig.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryConsistencyFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryIQv2FunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientTest.java

Add two consistency levels for pull queries, `Eventual` and `Monotonic Reads`. The user can choose a consistency level when creating the client and this level will be used for all pull queries. 
Updated the existing tests that exercise both levels

feat: add consistency levels to clients

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/JsonStreamedRowResponseWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/JsonStreamedRowResponseWriterTest.java

Ports over the buffering behavior to `/query-stream` for pull queries that exists in `PullQueryStreamWriter`.  This ensures that each chunk is a good size rather than outputting one row per chunk.
Unit and existing integration tests.

chore: Port over buffering for pull queries to /query-stream

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

Adds a config for enabling push v2 metrics and enables it by default.
Manual testing

chore: Enable push query v2 metrics by default

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryConsistencyFunctionalTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/ConsumerTestUtil.java

Previous logging revealed the producer does indeed produce the required number of records. So, the problem lies in the consumer. I am increasing the timeout to see if this helps.

chore: increase consumer timeout

---

docs/reference/migrations-tool-configuration.md
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/CreateMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/MigrationInfoCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ValidateMigrationsCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsDirectoryUtil.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/MigrationsDirectoryUtilTest.java

Fixes https://github.com/confluentinc/ksql/issues/8125.
This PR adds a new migrations config, `ksql.migrations.dir.override`, which allows users to specify the path to the directory containing migrations files to be applied. This config is not needed if the migrations project was set up using the `ksql-migrations new-project` command.
If no override is provided, the migrations directory will continue to be inferred relative to the migrations configuration file passed when using the `ksql-migrations` tool, as it is today. (Specifically, we infer the migrations directory as a directory with name `migrations` contained in the same directory as the migrations configuration file. This is the default file structure created by the `ksql-migrations new-project` command.)
Added unit + integration …

feat: allow users to specify custom migrations dir location

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_coalesce_-_with_parse_date/7.2.0_1646427911071/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_coalesce_-_with_parse_date/7.2.0_1646427911071/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_coalesce_-_with_parse_date/7.2.0_1646427911071/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/null.json

Addresses: https://github.com/confluentinc/ksql/issues/8324
This issue is about nested UDFs.  If a UDF has an error in processing, a null is returned.
In the case of `coalesce`, accepting a null value and doing something useful is possible.
Before this PR, the entire expression for a column was being evaluated in a single pass.  This means that
any exception would cause the entire expression to return null.
The general solution here is to wrap inner function calls with a "try-catch" which can return a null in the case of
an inner function throwing an exception.
Since such errors may represent an error in input data, the error is logged.  This handling is similar to struct and map handling.
The `SqlToJavaVisitorTest` has been updated to reflect the new code for nested functions.

fix: Adds error handling for nested functions

---

docs/developer-guide/ksqldb-clients/java-client.md
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/AdminResponseHandlers.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java

Adds an optional `ifExist` parameter to `dropConnector()` and `ifNotExist` to `createConnector()`
These are the java client changes needed for https://github.com/confluentinc/ksql/issues/8014. The migrations tool changes will be in another PR.
Unit + integration

fix(ksql): add ifExists/ifNotExist parameters to java client connector functions

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/MigrationsTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/commands/ApplyMigrationCommandTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/CommandParserTest.java

Fixes #8014 
Requires #8851 to be merged for the build to pass.
Unit + integration testing

fix(ksql): allow migrations tool to run connector commands with IF [NOT] EXISTS clauses

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/WindowingSharedRuntimeIntTest.java

To make sure the repartition topics get cleaned up we now check both possible names
I made sure these tests get run with the flag on always

fix: clean up mistaken topic names

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/QueryStreamHandlerTest.java

On http2, when a client connection is closed, the response end handler is called twice, so this prevents that.  The metrics were getting double counted as a result. 
Wrote unit test and tested manually.

fix: Ensures response end handler is invoked just once

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java

In the validation runtime we should use the blocking call so that if the future gets completed exceptionally we can fail validation. Also for COR queries we are going to validate stoping and and re-adding the topology.
Also this improves the failure message.
##

fix: use blocking call and throw exception on failure

---

release_stabilization.py

There was an issue with publishing the on prem docker images during the 0.24 release. This was because jenkins cannot pull from `confluent-docker.jfrog.io/` due to an authentication error. It needs to instead pull from `confluent-docker-internal.jfrog.io/`, which is what this PR changes.
Tested by replaying and editing the jenkins script to try both urls and confirm the behavior described above.

build: pull from docker internal for onprem image

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java

We recently saw a failure for this test where an exception wasn't thrown, indicating that we didn't hit the rate limit. I wasn't able to reproduce locally so it must be something specific with the CI. I added more chances to hit the exception so hopefully, this won't be flaky anymore.

fix: update rate limiting test so it's not flaky

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafAggregateFunctionFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafFactoryInvoker.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/TestUdaf.java
ksqldb-udf/src/main/java/io/confluent/ksql/function/udaf/Udaf.java

Various UDAFs can operate on input of any type.  This presents a challenge since ksqlDB needs to compute
the aggregate and return types of a function at runtime.
Here the `Udaf` interface is extended in order to allow for such functions to be written.
This work addresses https://github.com/confluentinc/ksql/issues/6638.
As motivation for the change, see https://github.com/confluentinc/ksql/issues/7697 and https://github.com/confluentinc/ksql/issues/5437.
This change has been validated with other work-in-progress branches.  This PR only has the interface changes to focus discussion.
- Depending on discussion, docs may be updated with a separate PR.

feat: Extend Udaf interface to allow for polymorphic UDAFs.

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

Since we bumped up the default number of StreamThreads per runtime to 4, we should decrease the default number of runtimes accordingly. 
The optimal number should ultimately be derived from the benchmarks, and we have a LaunchDarkly flag so we can modify the default further as more results come out, but for now we should still set the default in the code based on our initial observations.
If we start with just two runtimes, then with 4 threads each we will end up with 8 StreamThreads by default, which follows our rule of thumb for configuring the num.stream.threads (aka 2x # of cores on each node)

fix: decrease default number of shared runtimes

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java

RQTTs for scalable push queries have been occasionally failing due to flakey timeouts. This PR adds more logging to the RestTestExecutor to make it easier to debug these failures in the future. It also bumps the timeouts we have to find persistent queries and topics, since this has been identified as a source of potential flakiness in the past #8117

chore: add more logging to rqtt

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java

Benchmarks showed that creating 100 queries took up to 5 hours. This is likely because we currently wait on the future returned by `#addNamedTopology`, which blocks until all threads in the runtimes have ack'ed the new topology. Since this requires exiting the processing loop to check for topology updates before polling, and this depends on the configured `max.poll.interval.ms` for which we increased the default value with shared runtimes, waiting on this future can take a long time and will only increase as more queries are added.
Since we only really care about the topology being synced to the runtime's TopologyMetadata, and not whether the threads on a particular client have received it yet, we should just remove the `.all().get()` in `SharedKafkaStreamsRuntime#start(query)`

fix: Reduce query creation time with shared runtimes

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java

This reverts commit f3c58508a379543b0e545a9cb03af1e9166760c3.
The commit this is reverting was causing drop queries to block.
The behavior in streams is:
1. All threads are waiting for a non empty topology
2. A topology gets added.
3. Thread 1 updates, others do not yet
4. topology is removed Thread 1 removes and unsubscribes and goes back to waiting for a non empty topology
5. All other threads have not moved and so the remove future can never complete

Revert "fix: reduce query creation time with shared runtimes (#8888)"

---

ksqldb-cli/src/main/java/io/confluent/ksql/Ksql.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java

If there is an error executing a script or single command, the CLI should return error code -1 instead of 0 (no error).
Closes #7051 
Extended existing unit tests.

fix: CLI should return non-zero error code on failure

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java

This commit https://github.com/confluentinc/ksql/commit/f3c58508a379543b0e545a9cb03af1e9166760c3 is  causing drop queries to block.
The behavior in streams is:
All threads are waiting for a non empty topology
A topology gets added.
Thread 1 updates, others do not yet
topology is removed Thread 1 removes and unsubscribes and goes back to waiting for a non empty topology
All other threads have not moved and so the remove future can never complete
So before all removing a topology we make sure all the adds are compelete

fix: make sure topologies are done added before removing

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java

The list of futures of added topologies is never trimmed. Here we clear it after they are all completed

fix: empty to add future list

---

docs/developer-guide/ksqldb-reference/print.md

We made updates recently in https://github.com/confluentinc/ksql/pull/8802 to allow users more control over where their command topic lives. Since the command topic doesn't have to live on the same kafka that the rest of the topics do, it doesn't make sense to use the command topic as the basice example for what printing a topic would look like. This updates the print topic guide to use a user topic.
Did the example in CLI

chore: update print guide to remove command topic example

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/KafkaStreamsQueryValidator.java

Variables were swapped so the limit was reported as the usage and the usage was reported as the limit

fix: re-oder cache usage error

---

docs/operate-and-deploy/installation/server-config/security.md

ksqlDB supports using separate TLS trust stores for communication with Kafka vs external communication with ksqlDB clients, by prefixing the Kafka TLS configs with `ksql.streams.` but this is not currently documented. This PR adds docs.
See https://github.com/confluentinc/ksql/issues/8512 and https://github.com/confluentinc/ksql/pull/8514 for context.

docs: add note about prefixed kafka SSL configs

---

docs/developer-guide/api.md

Fixing this error that is thrown while following instructions found in the docs at https://docs.ksqldb.io/en/latest/developer-guide/api/
```
▶ curl -X "POST" "http://localhost:8088/query" \
-H "Accept: application/vnd.ksql.v1+json" \
-d $'{
"sql": "SELECT * FROM TEST_STREAM EMIT CHANGES;",
"streamsProperties": {}
}'
{"@type":"generic_error","error_code":40000,"message":"\"ksql\" field must be populated"}%
```

docs: fix /query REST API docs to use `ksql` field

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/BaseAggregateFunction.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/FunctionLoaderUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafAggregateFunction.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafFactoryInvoker.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafTableAggregateFunction.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/ExtensionSecurityManager.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdtfLoaderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/BadTestUdaf.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/BadTestUdf.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/BadTestUdtf.java

This PR adds calls to the `ExtensionSecurityManager` around all the calls that UDFs, UDAFs, and UDTFs can make.
Addresses https://github.com/confluentinc/ksql/issues/8662
Unit tests have been added.

fix: Apply the ExtensionSecurityManager to UDAFs

---

ksqldb-functional-tests/README.md

Fixing functional tests *min* version typo

docs: functional tests min version for lower bound

---

ksqldb-engine/src/main/java/io/confluent/ksql/exception/KsqlTopicAuthorizationException.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java

AK recently enabled idempotent producers by default: https://issues.apache.org/jira/browse/KAFKA-13598. This changes the exception thrown when a producer does not have write permissions from TopicAuthorizationException (for the non-idempotent producer case) to ClusterAuthorizationException when the idempotent producer fails to initialize a transaction (because either write permissions are missing or, for broker versions no later than 2.8, because IDEMPOTENT_WRITE permissions on the cluster are missing). 
This PR updates ksql to account for the ClusterAuthorizationException case to throw a better error message when INSERT VALUES fails, similar to the special handling that exists today for TopicAuthorizationException.
Added unit test.

chore: better error message on ClusterAuthorizationException during INSERT VALUES

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java

only create relevant runtimes for validation. Because we are now selecting runtimes in the assignor I think we don't need to make every runtime anymore. This should really speed up validation, especially when we have a topic that is queried a lot

fix: only make shared runtime that is chosen

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java

When running `Alter System` with many queries running we were encountering errors like 
```Stack trace: org.apache.kafka.streams.errors.StreamsException: Unable to initialize state, this can happen if multiple instances of Kafka Streams are running in the same state directory (current state directory is [/mnt/data/data/ksql-state/_confluent-ksql-pksqlc-8xo8rquery_0]
at org.apache.kafka.streams.processor.internals.StateDirectory.initializeProcessId(StateDirectory.java:191)
at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:891)
at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:874)
at org.apache.kafka.streams.processor.internals.namedtopology.KafkaStreamsNamedTopologyWrapper.<init>(KafkaStreamsNamedTopologyWrapper.java:87)```
the clean up of state from the …

fix: clean up state when restarting runtimes to avoid errors

---

docs/requirements.txt

From https://github.com/confluentinc/ksql/pull/8945.

docs: cherry-pick: pin jinja2 version to 3.0.3 to fix docs build break (DOCS-13195)

---

ksqldb-common/src/main/java/io/confluent/ksql/config/ImmutableProperties.java
ksqldb-engine/src/main/java/io/confluent/ksql/execution/PhysicalToExecutionPlanTranslator.java
ksqldb-engine/src/main/java/io/confluent/ksql/execution/json/PlanJsonMapper.java
ksqldb-engine/src/main/java/io/confluent/ksql/physicalplanner/LogicalToPhysicalPlanTranslator.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/StreamSelect.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/transform/select/Selection.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/plan/StreamSelectTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/transform/select/SelectionTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/select.json
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StepSchemaResolver.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamAggregateBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamFilterBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamFlatMapBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamSelectBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/TableAggregateBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/TableFilterBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/TableSelectBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/TableSuppressBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/transform/KsTransformer.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/transform/KsValueTransformer.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StepSchemaResolverTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StreamSelectBuilderTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/transform/KsTransformerTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/transform/KsValueTransformerTest.java

Previously, ksqlDB requires a CSAS statement to include key columns in
the SELECT. There is no semantic reason for this restriction and this
PR removes the key-column-requirement for CSAS statements.

feat: allow STREAMS with no key

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/RuntimeAssignor.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/RuntimeAssignorTest.java

When we remove the last query from a runtime we clean it up. However we don't clean up the assignor so a new query can be assigned again. This make the assignment spread out over all the runtimes ever created instead of as few as possible.
added a unit test

feat: clean up extra runtimes so the assignment is more focused

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/exception/KsqlTopicAuthorizationException.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java

Backport https://github.com/confluentinc/ksql/pull/8927 to 7.0.x since the producer idempotency default behavior change goes back to 3.0.1 (see https://issues.apache.org/jira/browse/KAFKA-13598).
Build.

chore: better error message on ClusterAuthorizationException during INSERT VALUES (7.0.x)

---

ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorUtilTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json

The build's got a few test failures at the moment because of [this bad merge](https://github.com/confluentinc/ksql/commit/20b75ea451468d7f80f905d46e5698a3979160a2) from 7.1.x last night. This PR fixes the bad merge so tests should be green again afterwards.
Build.

test: fix bad merge from 7.1.x

---

docs/reference/migrations-tool-configuration.md

The PR that introduced this feature missed the original, intended 0.25 release cut so the docs said 0.26, but now that the release cut has been pushed back, the feature is actually in 0.25. This PR updates the docs accordingly.

docs: update release version for custom migrations headers (MINOR)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ScalablePushBandwidthThrottleIntegrationTest.java

this fixed another flakey spq integration test so going to try to add it here as well in case it helps.

fix: wait longer while waiting for expected spq

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

docs: add note to deprecated TIMESTAMPTOSTRING for param workaround (DOCS-13327)

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

From https://github.com/confluentinc/ksql/pull/8979.

docs: cherry-pick: note for deprecated ksqlDB TIMESTAMPTOSTRING func (DOCS-13364)

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/max/MaxAggFunctionFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/min/MinAggFunctionFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/sum/SumAggFunctionFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopKAggregateFunctionFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctAggFunctionFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java

If you call the `sum` function with an unsupported argument type, it
throws an error complaining about the `max` function. This is clearly a
copy & paste error. I've fixed it, and amended the code to make future
copy & paste errors less likely.
Fixes #8976.
This is just an error message improvement, so there are no additional tests.

Improved/fixed aggregate function error messages.

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

resolve the configs before checking if they are at the query level. This way we can have the ksql.streams prefix for streams configs

chore: resolve configs before checking if they are query level

---

docs/requirements.txt

From https://github.com/confluentinc/ksql/pull/8945.

docs: cherry-pick: pin jinja2 version to 3.0.3 to fix docs build break (DOCS-13425)

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxConnectClient.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedServiceContext.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxConnectClientTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedServiceContextTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ConnectExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ConnectExecutorTest.java

This PR is stacked on https://github.com/confluentinc/ksql/pull/8998. Only commits starting with `chore: move create connector validation to validate phase` need to be reviewed.
Currently, a `CREATE CONNECTOR` request has three steps performed during the execution phase, and no validation. The execution steps are, in order:
1. use the Connect client to validate configs
2. check for existing connectors, if `IF NOT EXISTS` is present in the statement
3. use the Connect client to create the connector
The fact that there's no ksql validation for `CREATE CONNECTOR` statements (validation is only performed during execution) isn't great because it means that, in the case where a `CREATE CONNECTOR` statement is issued along with other ksql statements in the same request, the entire group of …

fix: move create connector validation to validate phase

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/KafkaStreamsQueryValidator.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/KafkaStreamsQueryValidatorTest.java

This will allow for more than 107 quereis to be made without hitting cache errors using shared runtimes. When using shared runtimes the cache can be shared among queries. When we go to see if the new query could put us over the total limit we cannot just add the query cache sizes together. Instead the queries must be grouped by runtime. Then we can see what the total usage is as the sum of the runtimes. We will assume worst case for the new query, that it will make a new runtime. This is not always the case but will prevent the runtime from being created and not having enough space. We can improve this but it would be a much more pervasive change and I think this is a strict improvement and we should get this in first regardless.
added a couple of unit tests.

fix: shared runtimes calculate cache size for validation properly

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/9020.

docs: cherry-pick: move ksql.streams.max.idle.ms section to be alphabetically correct (DOCS-13443)

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/ExpectedRecordComparator.java
ksqldb-functional-tests/src/test/resources/historical_plans/headers_-_Can_infer_key_and_value_schemas/7.3.0_1649879131547/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/headers_-_Can_infer_key_and_value_schemas/7.3.0_1649879131547/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/headers_-_Can_infer_key_and_value_schemas/7.3.0_1649879131547/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/headers.json

Fixes https://github.com/confluentinc/ksql/issues/8978
When injecting key and value schemas to a source that has header columns, the header columns get lost, causing the schema to be incorrect.
Unit+QTT tests

fix: include header columns when injecting schemas

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/SchemaRegistryUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/registry/SchemaRegistryUtilTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/protobuf/ValueSpecProtobufSerdeSupplier.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/utils/SerdeUtil.java
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_specify_a_protobuf_schema_from_multiple_protobuf_schema_definitions/7.3.0_1649453206637/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_specify_a_protobuf_schema_from_multiple_protobuf_schema_definitions/7.3.0_1649453206637/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_specify_a_protobuf_schema_from_multiple_protobuf_schema_definitions/7.3.0_1649453206637/topology
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_specify_a_protobuf_schema_name_with_SCHEMA_FULL_NAME/7.3.0_1649453337688/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_specify_a_protobuf_schema_name_with_SCHEMA_FULL_NAME/7.3.0_1649453337688/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_specify_a_protobuf_schema_name_with_SCHEMA_FULL_NAME/7.3.0_1649453337688/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/protobuf.json
ksqldb-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourcePropertiesTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/Format.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectFormat.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufFormat.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufSchemaTranslator.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/KsqlProtobufSerializerTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufFormatTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufSchemaTranslatorTest.java

Fixes https://github.com/confluentinc/ksql/issues/5265
Ignore 1st commit https://github.com/confluentinc/ksql/pull/8933/commits/58e470336cc3a583872cf33f46557a1fd65acb41 which is being reviewed here -> https://github.com/confluentinc/ksql/pull/8984
This PR supports the `KEY_SCHEMA_FULL_NAME` and `VALUE_SCHEMA_FULL_NAME` properties in the `WITH` clause when creating a stream. These properties allows users to specify the full name of a protobuf schema instead of using a default name (current default is `ConnectDefault1`).
When registering a new schema, if the properties are given, then the schema will be registered in SR with the new name, i.e.
```
ksql> create stream t1(id int key, c1 double, c2 int) with (kafka_topic='t1', format='protobuf', key_schema_full_name='ProtobufKey1', …
```

fix: Create stream fails when multiple Protobuf schema definitions exist

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/json/JsonRecords.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/json/JsonRecordsTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/json_records.json

When `JSON_RECORDS` converts a string field to a string, it adds extra quotations. For example,
```
SELECT JSON_RECORDS('{"key": "value"}') FROM SOURCE EMIT CHANGES;
> {"KSQL_COL_0": {"key": "\"value\""}}
```
This is what the user in #9000  is facing. 
QTT + unit test

fix: remove double quotes from json_records function

---

ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/ImmutableAnalysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/RewrittenAnalysis.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/AnalysisTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/QueryAnalyzerFunctionalTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/count.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/suppress.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json

Helps to partially fix #430 by allowing users to create aggregations without group by clauses in push queries .

feat: allow aggregations without group bys

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java

When restarting the runtime we need to register the state change listener for the new runtime.

fix: register state listener after restarting runtime

---

CHANGELOG.md
docs/operate-and-deploy/changelog.md

Reverts confluentinc/ksql#8987. I wasn't aware that I need to wait to merge this until I roll to prod.

Revert "chore/generate-0.25.1-changelog"

---

CHANGELOG.md
docs/operate-and-deploy/changelog.md

This is reapplying https://github.com/confluentinc/ksql/pull/8987. I had to revert it as I wasn't aware that I need to merge it only when rolling the final RC to prod.

tolgadur:generate-0251-changelog

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksqldb-functional-tests/src/test/resources/historical_plans/elements_-_validate_schema_id_and_schema_full_name_from_multiple_schema_definitions_OK_-_PROTOBUF/7.3.0_1650556180294/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/elements_-_validate_schema_id_and_schema_full_name_from_multiple_schema_definitions_OK_-_PROTOBUF/7.3.0_1650556180294/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/elements_-_validate_schema_id_and_schema_full_name_from_multiple_schema_definitions_OK_-_PROTOBUF/7.3.0_1650556180294/topology
ksqldb-functional-tests/src/test/resources/historical_plans/elements_-_validate_schema_id_without_elements_with_non-default_schema_name_OK_-_PROTOBUF/7.3.0_1650556179734/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/elements_-_validate_schema_id_without_elements_with_non-default_schema_name_OK_-_PROTOBUF/7.3.0_1650556179734/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/elements_-_validate_schema_id_without_elements_with_non-default_schema_name_OK_-_PROTOBUF/7.3.0_1650556179734/topology
ksqldb-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_elements_with_non-default_schema_name_OK_-_PROTOBUF/7.3.0_1650556179599/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_elements_with_non-default_schema_name_OK_-_PROTOBUF/7.3.0_1650556179599/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/elements_-_validate_without_elements_with_non-default_schema_name_OK_-_PROTOBUF/7.3.0_1650556179599/topology
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_INSERT_INTO_stream_with_SCHEMA_ID_and_SCHEMA_FULL_NAME/7.3.0_1650558675555/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_INSERT_INTO_stream_with_SCHEMA_ID_and_SCHEMA_FULL_NAME/7.3.0_1650558675555/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_INSERT_INTO_stream_with_SCHEMA_ID_and_SCHEMA_FULL_NAME/7.3.0_1650558675555/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/elements.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/insert-into.json

When I created a stream with `SCHEMA_ID` and a `SCHEMA_FULL_NAME` to select a schema from a multiple schema definition, the INSERT VALUES statement fails that the SR schema was not compatible with the one generated during insert.
i.e.
```
ksql> create stream m1 with (kafka_topic='m1', format='protobuf', key_schema_id='11', key_schema_full_name='M1_2', value_schema_id='12', value_schema_full_name='M1_2');
Message        
Stream created 
ksql> insert into m1(k2, v2) values(1, 1);
Failed to insert values into 'M1'. Cannot INSERT VALUES into data source `M1`. ksqlDB generated schema would overwrite existing key schema.
Existing Schema: syntax = "proto3";
message M1_1 {
int32 K1 = 1;
}
message M1_2 {
int32 K2 = 1;
}
ksqlDB Generated: syntax = "proto3";
message …
```

fix: INSERT/VALUES on a stream with SCHEMA_ID/SCHEMA_FULL_NAME fails

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ExecuteQueryResponseHandler.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/QueryResponseHandler.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/StreamQueryResponseHandler.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/util/RowUtil.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ClientImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/util/RowUtilTest.java
ksqldb-common/src/main/java/io/confluent/ksql/util/BytesUtils.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTargetUtil.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/StreamPublisher.java

Migrate the java client to use `application/vnd.ksql.v1+json` format when hitting the `/query-stream` endpoint without breaking backward compatibility

feat: migrate java client to use application/vnd.ksql.v1+json

---

ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/TopicNode.java

Jackson was bumped upstream: https://github.com/confluentinc/common/pull/446
Version 2.13 returns `null` instead of `NullNode` (cf https://github.com/FasterXML/jackson-databind/issues/3389)
PR cannot be cherry-picked/merge into 5.5.x branch. PR for 5.5.x #9068

chore: fix broken build due to upstream Jackson version bump

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/PostConditionsNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/TopicNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/utils/SerdeUtil.java

Jackson was bumped upstream: https://github.com/confluentinc/common/pull/446
Version 2.13 returns `null` instead of `NullNode` (cf https://github.com/FasterXML/jackson-databind/issues/3389)
Should be merged to all newer branches.

chore: fix broken master build after upstream Jackson version bump

---

mkdocs.yml

From https://github.com/confluentinc/ksql/pull/8989.

docs: cherry-pick: bump docs version to 0.25.1 (DOCS-13614)

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/MissingSubjectClassifier.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/SchemaAuthorizationClassifier.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/MissingSubjectClassifierTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/SchemaAuthorizationClassifierTest.java

Added a couple of classifiers that classify missing SR subjects and authorization errors from SR as USER errors. The classifiers just log the errors similar to the  `MissingTopicClassifier` class.

fix: classify SR missing subject and access rights query errors as USER errors

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintAssertNotExistsTopicResult.approved.json
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintAssertNotExistsTopicResult.approved.tabular
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AssertTopic.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/AssertTopicTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/AssertTopicExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/AssertTopicExecutorTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/AssertTopicEntity.java

Adds `NOT EXISTS` to `ASSERT TOPIC` which asserts that a topic doesn't exist
Manual, unit+integration tests

feat: assert not exists topic

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java

We observes some test failures:
```
org.junit.runners.model.TestTimedOutException: test timed out after 90 seconds
at io.confluent.ksql.api.TlsTest.lambda$shouldReloadCert$0(TlsTest.java:145)
at io.confluent.ksql.api.TlsTest.shouldReloadCert(TlsTest.java:137)
```
It seems we are blocking in the `get()` call on the future. Adding a timeout should help as it would trigger a re-try to send the request, avoiding that the test blocks and eventually times out via the `@Rule public final Timeout timeout = Timeout.seconds(90);` annotation.

test: add timeout to future for TlsTest to avoid blocking

---

ksqldb-common/src/main/java/io/confluent/ksql/function/AggregateFunctionFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/max/MaxAggFunctionFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/min/MinAggFunctionFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/max/BytesMaxKudafTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/max/StringMaxKudafTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/min/BytesMinKudafTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/min/StringMinKudafTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/max-group-by_-_max_bytes_group_by/7.3.0_1651157910151/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/max-group-by_-_max_bytes_group_by/7.3.0_1651157910151/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/max-group-by_-_max_bytes_group_by/7.3.0_1651157910151/topology
ksqldb-functional-tests/src/test/resources/historical_plans/max-group-by_-_max_string_group_by/7.3.0_1651157908841/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/max-group-by_-_max_string_group_by/7.3.0_1651157908841/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/max-group-by_-_max_string_group_by/7.3.0_1651157908841/topology
ksqldb-functional-tests/src/test/resources/historical_plans/min-group-by_-_min_bytes_group_by/7.3.0_1651157920145/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/min-group-by_-_min_bytes_group_by/7.3.0_1651157920145/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/min-group-by_-_min_bytes_group_by/7.3.0_1651157920145/topology
ksqldb-functional-tests/src/test/resources/historical_plans/min-group-by_-_min_string_group_by/7.3.0_1651157918955/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/min-group-by_-_min_string_group_by/7.3.0_1651157918955/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/min-group-by_-_min_string_group_by/7.3.0_1651157918955/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/max-group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/min-group-by.json

Enable bytes n string data types for max/min udaf
Added unit and integration tests

Enable bytes and string data types for max/min udaf

---

ksqldb-engine/src/main/java/io/confluent/ksql/execution/pull/HARouting.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocator.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocatorTest.java

We need to re fetch the streams instance when providing the Materialization incase it was updated when changing a config.
pull queries after an `ALTER SYSTEM` do not return an error with gen 2 queries

fix: re fetch streams for each materializationProviderBuilder

---

ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/VariableSubstitutor.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/VariableSubstitutorTest.java

1. Allows users to specify topic names and schema subjects using either strings or identifier names. This is important because topics and schemas are allowed to use the `-` character in names, but ksqlDB does not allow that in identifiers.
2. Allows variable substitution for quoted names. 
Unit tests, manual testing. Integration testing will be included with java client changes.

chore: improve variable substitution for assert statements

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/AssertExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/AssertSchemaExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/AssertTopicExecutor.java

~changed `ksql.assert.topic.default.timeout.ms` to `ksql.assert.default.timeout.ms ` because it covers schemas as well~
Adds a separate config for schema timeouts, `ksql.assert.schema.default.timeout.ms`
should pass all tests

chore: add config for assert schema timeout

---

mkdocs.yml

From https://github.com/confluentinc/ksql/pull/9122.

docs: cherry-pick: bump AK version token for 0.26.0 (DOCS-13846)

---

mkdocs.yml

From https://github.com/confluentinc/ksql/pull/9122.

docs: cherry-pick: bump AK version token for 0.26.0 (DOCS-13845)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md

In ksqlDB 0.25.1, UDAFs like COLLECT_LIST and COLLECT_SET were updated to work with any types.
This PR updates the docs and removes a note about the prior restriction.

docs: Updates aggregate functions reference

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java

https://github.com/confluentinc/ksql/pull/9103 introduced a new protobuf Content-Type: `application/vnd.ksql.v1+protobuf`.
Upon introduction, `application/vnd.ksql.v1+protobuf` accidentally became the default content type for the `/query-stream` endpoint superseding our old default `application/vnd.ksqlapi.delimited.v1`. This happened because the `/query-stream` route had an equal weighting for all the content types including the new protobuf format. When there are equal weights on all the formats, then `routingContext.getAcceptableContentType()` https://github.com/confluentinc/ksql/blob/bd9034774cf11693f751472ef168f6fe9c99515d/ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java#L123 just picks the first match (which happened to be the protobuf format in our …

fix: revert default `/query-stream` Content-Type to `application/vnd.ksqlapi.delimited.v1` from `application/vnd.ksql.v1+protobuf`

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocatorTest.java

Refactor `PullQueryRoutingFunctionalTest` into `HaRoutingTest` and KsLocatorTest that are unit tests. `HaRouting` takes an ordered list of nodes and forwards the query in order to these nodes. This functionality is tested in `HaRoutingTest`. `KsLocator` returns an ordered list of nodes based on the routing filters such as liveness and lag. This functionality is tested in `KsLocatorTest`. Moreover, we have muckrake tests that kill nodes and test that pull queries keep succeeding  because they get forwarded to standby.
From the above, I feel it is safe to ignore the flaky `PullQueryRoutingFunctionalTest`. The only thing missing was a test in `KsLocatorTest` regarding the lag filter.

chore: refactor pull query routing test into and ignore it

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/PropertiesList.java

I noticed some configs that should be query level were missing from the `queryLevelProperties` list. Most of these are already included in the UI and were just missing here, but there are two ksql configs that I believe should be classified as query-level (see [here](https://github.com/confluentinc/ksql/pull/9143/files#r883243664))
This PR also expands & improves the javadocs.
Finally, it [fixes a small bug](https://github.com/confluentinc/ksql/pull/9144/files#diff-b956beb11421b0d6b59a03136c7fa40e577144778834e7af1479775fddd81b4dR248) where we should be checking both the query-level AND system-level properties list when validating an `ALTER SYSTEM` command, as query-level configs can be set this way but are interpreted instead as a default value.

fix: move misplaced query-level configs to the correct list

---

docs/operate-and-deploy/changelog.md

Related: https://github.com/confluentinc/ksql/pull/9080.

docs: link to main 0.26.0 changelog in built changelog topic (DOCS-13330 and DOCS-13337)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/9088.

docs: cherry-pick link to main 0.26.0 changelog in built changelog topic (DOCS-14400)

---

findbugs/findbugs-exclude.xml
pom.xml

There's an issue with the recent Findbugs 4.7.0 version that introduce new detectors.
https://github.com/spotbugs/spotbugs/issues/2040
The issue seems to fail only on Java 11. This PR excludes the new detectors from findbugs.

chore: ignore new findbugs 4.7.0 detectors causing ksql build to fail

---

docs/reference/server-configuration.md

I added this note, per KCI-1636:

docs: add note about query-level configs (KCI-1636)

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/kafka/KafkaSerdeSupplier.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestGeneratorTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_KAFKA_in_out/7.3.0_1654811779148/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_KAFKA_in_out/7.3.0_1654811779148/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_KAFKA_in_out/7.3.0_1654811779148/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/bytes.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/kafka/KafkaSerdeFactory.java

Fixes #8693 by adding ByteBuffer serdes to the KafkaSerdeFactory. Added a new QTT to the bytes.json to check correct behaviour for the KAFKA format.

fix: add BYTES support for KAFKA format

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporter.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/ThroughputMetricsReporter.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/ThroughputMetricsReporterTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/metrics/RocksDBMetricsCollector.java

Introduces a ThroughputMetricsReporter to report the consumed/produced total throughput metrics added to Streams in KIP-846. 
Metrics are aggregated to spit out a total sum of records & bytes consumed/produced per topic, per query

chore: add ThroughputMetricsReporter for consumed/produced metrics from KIP-846

---

ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/metrics/RocksDBMetricsCollectorTest.java

the shouldNotUpdateIfWithinInterval test checks that we dont
update the metric value if the interval has not passed. It
tries to configure a very long interval. However the config
does not get applied because we need to first reset the
static configuration.

fix: reset collector before reconfiguring

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/ThroughputMetricsReporter.java

This PR contains two fixes:
1. changes the group name for ksql's per-query topic-level metrics to `ksql-query-throughput-metrics` so that we can distinguish them from the Streams metrics they are derived from
2. have the `ThroughputTotalMetric` extend the Kafka metrics class `CumulativeSum` so that the ce-kafka metrics reporter we integrate with will know to compute the diff and only forward the throughput deltas (see [here](https://github.com/confluentinc/ce-kafka/blob/6bb7cd13e0c7ca01474c3f04f4e081bdf42d2448/ce-metrics/src/main/java/io/confluent/telemetry/collector/KafkaMetricsCollector.java#L171)). This is a bit of a hack but it's necessary to ensure that the downstream metrics processing will accumulate the totals correctly.

fix: change group name and extend CumulativeSum in ThroughputMetricsReporter

---

ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/metrics/RocksDBMetricsCollector.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/metrics/RocksDBMetricsCollectorTest.java

fix the interval check in RocksDBMetricCollectorTest. Previously
it would return true if called multiple times in the same millisecond.
Now it only returns true if the instant actually changes

fix: fix the interval check in RocksDBMetricCollectorTest

---

pom.xml

Fixes: https://github.com/confluentinc/ksql/issues/9060
~~We should actually not bump to `-M7` but remove the pinning -- this is just a trial PR to see it `-M7` actually works.~~
~~After the PR to common is merged (https://github.com/confluentinc/common/pull/462), this PR needs to be update to _remove_ the pinning.~~

chore: unpin surefire version

---

pom.xml

A previous issue with mockito 4.5.1 was causing test issues in Ksql. We had to use the lower 4.3.1 version of mockito in Ksql. These tests issues are gone with 4.6.1 which will be available in the `commos` repo soon. This PR removes the static 4.3.1 version so we can use the new one from `commons`.
Let's wait until this PR is merged https://github.com/confluentinc/common/pull/461 and tests are passing.

chore: revert mockito version changes causing test issues

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/MetricsTagUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporter.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/ThroughputMetricsReporter.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/ThroughputMetricsReporterTest.java

Adjust the throughput metric tags  used in `ThroughputMetricsReporter` to conform to the existing tag names used elsewhere (eg in the clients):
1. Convert the `"topic-name"` tag currently set by Streams to just `"topic"` -- can remove this once the upstream fix is merged & synced through to ccs-kafka (won't cause any issues if it's not removed in time, though)
2. Replace the `"thread-id"` tag with the `"consumer_group_member_id"` tag that's used in other metrics/is an existing metrics label in Druid

fix: convert topic tag name and add consumer group member id tag to ThroughputTotalMetrics

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/MetricsTagUtils.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/ThroughputMetricsReporterTest.java

I realized that while the final tag in the Metrics API is called `consumer_group_id`, it's actually just called `member` within Druid. So we need to change the tag to match this

fix: change consumer_group_member_id tag to just member to match Druid label name

---

ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/AcosTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/AsinTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/Atan2Test.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/AtanTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/CosTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/CoshTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/CotTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/DegreesTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/PiTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/RadiansTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/SinTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/SinhTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/TanTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/math/TanhTest.java

The checks for PR #9213 passed because they used Java 11. However, master uses Java 8, and some of the unit tests are now failing because the floating point values are not matching. (The Java library trig methods allow a 1 ulp difference from the exact result, so some implementation or optimization must have changed between versions.)
I have updated the trig unit tests to use close matches for floating point values instead of exact matches.
Confirmed the tests were failing locally on Java 8 and then passing after these fixes. Also checked Java 11.

fix: Trig tests failing on master/Java 8

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/AuthenticationPluginHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/KsqlAuthorizationProviderHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/auth/AuthenticationPluginHandlerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/auth/KsqlAuthorizationProviderHandlerTest.java

fixes #9206 by respecting the `authentication.skip.paths` in `KsqlAuthorizationProviderHandler.java`
spun up CFK with MTLS and RBAC enabled on the normal endpoints. see relevant portion of configuration:
```
authentication.skip.paths=/chc*,/heartbeat,/lag
bootstrap.servers=kafka.operator-feyrhf.svc.cluster.local:9073
config.providers=file
config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
confluent.metadata.basic.auth.user.info=${file:/mnt/secrets/ksqldb-mds-client/bearer.txt:username}:${file:/mnt/secrets/ksqldb-mds-client/bearer.txt:password}
confluent.metadata.bootstrap.server.urls=https://kafka.operator-feyrhf.svc.cluster.local:8090
confluent.metadata.http.auth.credentials.provider=BASIC
confluent.metadata.ssl.truststore.location=/mnt/sslcerts/trustst …
```

fix: respect authentication.skip.paths properly

---

ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/PropertiesList.java

KIP-770 that added `STATESTORE_CACHE_MAX_BYTES_CONFIG` was reverted.
Thus, we need to remove it to not break compilation.

chore: remove `reverted` property

---

ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlAuthTokenProvider.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/AuthenticationUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/AuthenticationUtilTest.java

After #9239 was merged, the *correct* auth token is accessible from ApiSecurityContext, so we can use that instead of generic Principals to extract timeouts.
Updated unit test. Will manually test as well.

fix: change auth token provider to accept token strings instead of principals

---

docs/requirements.txt
mkdocs.yml

Related: https://github.com/confluentinc/ksql/pull/9297.

docs: pin Markdown to v3.3.6 (DOCS-15014)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/PreconditionChecker.java

the precondition check backoff can reach a maximum of 30 seconds which is a bit high. Let's make it configurable

chore: make precondition backoff configurable

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ClientImplTest.java

We currently test single digit version numbers only, ie, `1.2.3`, which fails for double digits, eg, `0.27.0`.
Not sure why this was not an issue earlier.

test: fix version pattern in ClientImplTest

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/PreconditionChecker.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/PreconditionCheckerTest.java

We only create the service context when the pre condition checker is initialized, we should actually get a new service context each time we do a check as the service context should have the most up to date properties from the properties loader (incase new configs have come in since last time)

feat: refresh service context and topic client in precondition checker

---

docs/requirements.txt
mkdocs.yml

From https://github.com/confluentinc/ksql/pull/9299.

docs: cherry-pick: pin Markdown to v3.3.6 (DOCS-15035)

---

ksqldb-common/src/main/java/io/confluent/ksql/reactive/BasePublisher.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java

The test sometimes fails with a NPE due to a race condition.
The needed `subscriber` is registered async in a different thread.
This PR adds a check in the setup that the `subscriber` was indeed
registered and is not `null` before the test can start.

test: fix flaky test ClientTest.shouldFailPollStreamedQueryResultIfFailed

---

docs/reference/metrics.md
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryEventListener.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/QueryStateMetricsReportingListener.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/QueryStateMetricsReportingListenerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PauseResumeIntegrationTest.java

The existing metric `query-status` reports the state of the Kafka Streams application.
This new metric `ksql-query-status` reports the state of the ksqlDB.
This is being added to show that the query can be paused.  (While a ksqlDB query is paused,
the underlying Kafka Stream application is still in the `RUNNING` state.)
Added unit tests and verified the new metric with JConsole locally.

feat: Adding ksqlDB Query Status metric.

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/ApiSecurityContext.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/AuthenticationPlugin.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/DefaultApiSecurityContext.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProvider.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/impl/DefaultKsqlSecurityContextProviderTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java

Refactor `getAuthToken` to be `getAuthHeader` since what we really want to pass on is a full header value, not simply just an authorization token.

refactor: rename getAuthToken to getAuthHeader

---

debian/Makefile
reset-versions.py

Pinned nanoversion broke the packaging process because it builds without access to any nanoversions, and instead builds everything in topological order. Previously, this process worked automatically, as the ranges would resolve to the only available version for those dependencies (eg `7.3.0-0`).
Now that the dependencies are pinned, we need to explicitly set the dependencies to the packaging version. Sadly, we can't do it with Maven, since the Maven versions plugin fails when the pom contains unresolvable versions (or any other errors).

chore: reset dependencies during packaging

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/KsqlSerializationClassifier.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/KsqlSerializationClassifierTest.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/KsqlSerializationException.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/KsqlConnectSerializer.java

Add a classifier to classify SerializationException as USER error
It looks for the exception message and verifies the topic name doesn't contain the prefix `_confluent_ksql`

KSE-1045: Classify serialization exception

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/TestDriverPipeline.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java
ksqldb-functional-tests/src/test/resources/sql-tests/test.sql

Fixes #6113 and #6058
The issue is that the testing tool works by creating a `TopologyTestDriver` for every query, so when doing insertions and checking values, it looks for drivers. DDL sources are not queries though, so YATT ends up not finding a driver.  The fix here is to register a driver with an empty topology for every DDL source.
Added a test to the testing tool test

fix: allow YATT to insert into and check contents of DDL sources

---

CHANGELOG.md

This PR fixes a broken link to 0.27.1 release in the changelog.

chore: fix the link to 0.27.1 release

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/cast_-_cast_function_with_error_to_null_without_logging_error/7.3.0_1658780839480/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/cast_-_cast_function_with_error_to_null_without_logging_error/7.3.0_1658780839480/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/cast_-_cast_function_with_error_to_null_without_logging_error/7.3.0_1658780839480/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/cast.json

Addresses https://github.com/confluentinc/ksql/issues/9311
This change adds a try-catch around calls to `Cast`.  When an exception is thrown, then a null is returned by the cast.
Updates to unit tests and new QTTs.

fix: Map invalid casts to null.

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/DdlDmlResponseHandlers.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java

Fixes #9253
Previously, we were identifying DDL warnings by looking for "IF NOT EXISTS" in the command, but that fails when the command is in lower case or has extra spaces.
See discussion in #8322 for context on why we are filtering warning responses to begin with.
Unit + integration

fix: make api client recognize ddl warnings better

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/state/ServerState.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ServerStateTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ClusterTerminationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/state/ServerStateTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/Errors.java

Add a new server state `TERMINATED` for when we have finished cleaning up state after calling `clusterTerminator.terminateCluster(deleteTopicList)`
Unit tests

chore: add TERMINATED server state

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/TestDriverPipeline.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java
ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/chained-upgrades.sql

Fixes #6059. Also enables schema upgrades on big chains of queries :)
Previously, every time a query was called, YATT would create a new input node and a new output node specifically for that query. This made evolution complicated, because the same topic would have several nodes associated with it and we would have to update every single one with the new schema. This refactor consolidates all the input and output nodes into a single topic node to make query upgrades possible. 
added a yatt test

refactor: combine yatt input and output nodes into one topic node

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/loader/TestLoader.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/SqlTestLoader.java

- Currently, we can pass the test file as an input and it runs all the tests
within the file.
- However, we might be interested in running/debugging a specific test within
a file or across all the tests
- This commit adds support to a parameter ksql.test.names which accepts one or
more test names and only runs those whitelisted tests
- It doesn't alter the old behavior i.e. if you don't pass the test names it
runs all the tests
Tested by running all the tests without any parameter
Tested by passing the -Dksql.test.names="foo bar" and ensuring only "foo bar" test ran
Tested by passing the -Dksql.test.files=foo.sql and ensuring all tests run from the file
Tested by passing the -Dksql.test.files=foo.sql and -Dksql.test.names="foo bar" and ensuring only "foo bar" test ran
Tested by passing …

minor: Allow passing test name as a parameter to run specific tests

---

Jenkinsfile
pom.xml

Pinned nanoversions aren't completely implemented for the release stabilization tool, so re-cutting this release resulted in a mixed dependency set. This PR manually fixes up the dependencies and disables pinned nanoversions.
For future reference, there are two commits we need to undo for releases to function:
1. https://github.com/confluentinc/ksql/commit/577029425c4ae4288fa527488acf1ef4820aade2
2. https://github.com/confluentinc/ksql/commit/d3545b9d8873465f967b6e951a45260fb775c948

fix: complete rollback of pinned nanoversions

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java

Signed-off-by: Walker Carlson <wcarlson@confluent.io>
For when shared runtimes are on we should use the internal topics prefix for transient queries as well.
run with the shared runtimes turned on

fix: use internal topic config for transient queries too

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/RuntimeAssignor.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/RuntimeAssignorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryBuilderTest.java

When packing we relied on the source names being mapped to a topic. but it turns out you can make duplicate sources from the same topics with different names. So we now will check the topics directly.
updated the unit testing to use topics instead of sources
This set of cmds now works
```
create` stream t1_stream (id varchar key, foo varchar) with (kafka_topic='t1', value_format='json', PARTITIONS=1);
create table t1_table (id varchar primary key, foo varchar) with (kafka_topic='t1', value_format='json');
create stream t1_stream_copy as select * from t1_stream;
create stream t1_stream_copy_2 as select * from t1_stream;
create table t1_table_copy as select * from t1_table;
```

fix: compare topics not sources

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplicationMetrics.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

moves udf loading to run before the precondition checker. this ensures
we can quickly start the main server once the precondition checker is
completed running. Also adds a metric to measure server start time
unit test + test in devel

fix: move udf loading to run before the precondition checker

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/MetricsTagUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporter.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/ThroughputMetricsReporter.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/ThroughputMetricsReporterTest.java

Fixes a bug wherein the throughput metrics fail to extract the full query id for Stream names that contain one or more hyphen characters

fix: fix regex used to extract queryId from threadId metrics tag

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java

For when shared runtimes are on we should use the internal topics prefix for transient queries as well.

fix: use internal topic config for transient queries too (#9393)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/correlation/CorrelationUdaf.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/correlation/CorrelationUdafTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_double/7.3.0_1659562540395/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_double/7.3.0_1659562540395/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_double/7.3.0_1659562540395/topology
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_int/7.3.0_1659986544367/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_int/7.3.0_1659986544367/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_int/7.3.0_1659986544367/topology
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_long/7.3.0_1659986545310/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_long/7.3.0_1659986545310/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_long/7.3.0_1659986545310/topology
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_udaf_with_table/7.3.0_1659562541482/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_udaf_with_table/7.3.0_1659562541482/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/correlation-udaf_-_correlation_udaf_with_table/7.3.0_1659562541482/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/correlation-udaf.json

Follow-up to #9361. Adds a new UDAF, `CORRELATION`, to compute the Pearson correlation coefficient between two `DOUBLE` columns in a stream or table.
Added unit tests and QTTs for the new UDAF.

feat: add `CORRELATION` UDAF

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java

Since a KafkaStreams runtime is created when ALTER SYSTEM commands are read with shared runtimes, any paused topologies need to be paused in the new runtime.
Added a unit test.

fix: With shared runtimes, ALTER SYSTEM would cause paused queries to resume.

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java

Signed-off-by: Walker Carlson <wcarlson@confluent.io>
A join int test was failing with shared runtimes on. And it seem the NamedTopology.sourceTopics doesn't work when not in an application
testing already covered this

fix: topologies with internal topics can not use get sources

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/json/JsonItems.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/json/UdfJsonMapper.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/json/JsonItemsTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/json_items_-_convert_a_json_array_string_to_an_array_of_json_objects/7.3.0_1659931620853/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/json_items_-_convert_a_json_array_string_to_an_array_of_json_objects/7.3.0_1659931620853/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/json_items_-_convert_a_json_array_string_to_an_array_of_json_objects/7.3.0_1659931620853/topology
ksqldb-functional-tests/src/test/resources/historical_plans/json_items_-_extract_timestamps_from_json_objects/7.3.0_1659931620907/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/json_items_-_extract_timestamps_from_json_objects/7.3.0_1659931620907/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/json_items_-_extract_timestamps_from_json_objects/7.3.0_1659931620907/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/json_items.json

This FEAT converts a string with JSON array to an array of JSON strings - JSON_ITEMS(String) -> Array[String]
Then, a user could do something like
TRANSFORM(JSON_ITEMS(message), (obj) => EXTRACTJSONFIELD(obj, '$.time`))
Unit test
QTT
see #9062

feat: add support for JSON arrays

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializationFunctionalTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImplTest.java

* fix: Update default to not delete consumer groups
Signed-off-by: Walker Carlson <wcarlson@confluent.io>
* fix: Update default to not delete consumer groups when closing
Signed-off-by: Walker Carlson <wcarlson@confluent.io>
* fix: Update default to not delete consumer groups when closing
Signed-off-by: Walker Carlson <wcarlson@confluent.io>
* fix: Update default to not delete consumer groups when closing
Signed-off-by: Walker Carlson <wcarlson@confluent.io>
* fix: Update default to not delete consumer groups when closing
Signed-off-by: Walker Carlson <wcarlson@confluent.io>
* do not change the stop default, just the call in query registry
Signed-off-by: Walker Carlson <wcarlson@confluent.io>
* do not change the stop default, just the call in query registry
Signed-off-by: Walker Carlson …

fix: Update default to not delete consumer groups (#9407)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlAuthTokenProvider.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlDefaultSecurityExtension.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlSecurityExtension.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/AuthenticationUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/AuthTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/MockKsqlSecurityExtension.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/WSQueryEndpointTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/AuthenticationUtilTest.java

Backport https://github.com/confluentinc/ksql/pull/9147 to 6.0
Starting in 6.0, the KsqlAuthTokenProvider will accept a string token instead of a principal.
manually tested

chore: terminate websocket connections after token expiration

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LagReportingAgent.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java

Ensures that the lag reporter doesn't fail to send lags due to failures.  Also logs failures if they occur.
Unit tests plus functional tests.

fix: Ensure lag reporter doesn't crash

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java

Another minor refactor on the `TestCaseBuilderUtil` class. The `createTopicFromStatement` method was a little confusing. It was using a for loop when only one statement was allowed; registering types when the method name intent was to create topic from a create statement. This was causing some confusion while debugging the code.
I moved the majority of the code from `createTopicFromStatement` to the caller which is the one that loops through each SQL statement and decides what to do with it.

refactor: refactor TestCaseBuilderUtil class

---

pom.xml

Stopgap until the release tooling is fixed: we have to manually bump the versions to the 7.4.0 series.

chore: manually update pinned nanos for 7.4.0

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

Set the default max timeout to 1 hour. 5.4.x - 7.2.x have the same default, it just got lost in a merge.
Manually tested

chore: turn on websocket ff

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LagReportingAgent.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java

Ensures that the lag reporter doesn't fail to send lags due to failures. Also logs failures if they occur.
Cherry pick of #9423 
Unit tests plus functional tests.

fix: Ensure lag reporter doesn't crash (#9423)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java

The custom error handler in KsqlResource is currently only applied to raw exceptions and KsqlExceptions, but not KsqlStatementExceptions. This means the error handler misses cases such as when Schema Registry is not enabled, because the DefaultSchemaInjector has [logic](https://github.com/confluentinc/ksql/blob/f1d1757faec4a14728e48d8065be64d11aa4ab6d/ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java#L133-L138) to wrap the KsqlException in a KsqlStatementException. 
We could fix this by not having injectors (and other parts of the code) wrap KsqlExceptions, but it seems better to leave that flexibility and instead apply the error handler to KsqlStatementExceptions from KsqlResource. At least, I see no reason not to.

fix: apply custom error handler to KsqlStatementException (MINOR)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/AuthHandlers.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/AuthTest.java

What's happening is that if the request is a simple stream that only sends headers and no data vertx can end the request in the same event loop handling that it initiates the request.
some auth plugins, however, issue a call to executeBlocking which works on the worker thread and allows the event loop to continue in the background. The request, then "ends" before we return from the blocking action and when we try to pause it the request fails because you can't pause a finished request
if we pause the request before we issue the executeBlocking call, then when it tries to end the request instead it just enqueues it on a buffer to execute the end asyncrhonously once the request is unpaused (which is after execution of the thread).
Added test and verified that it fails without this change.
I …

chore: add pause before running auth plugins

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/KsqlCorsHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PreconditionVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/PreconditionServer.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/CorsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ServerCorsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PreconditionCheckerIntegrationTest.java

This patch adds cors handling for the precondition server. It also refactors the
cors test so that it can be used to test any server, and then uses the refactored
test to test the precondition server

fix: cors handling for precondition server

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/KsqlCorsHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PreconditionVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/PreconditionServer.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/CorsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ServerCorsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PreconditionCheckerIntegrationTest.java

This patch adds cors handling for the precondition server. It also refactors the
cors test so that it can be used to test any server, and then uses the refactored
test to test the precondition server

fix: cors handling for precondition server (#9448)

---

docs/concepts/time-and-windows-in-ksqldb-queries.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-push-query.md
docs/reference/server-configuration.md
docs/reference/sql/appendix.md

Restored and updated from https://github.com/confluentinc/ksql/pull/6528/.

docs: restore docs for EMIT FINAL syntax (DOCS-15926)

---

docs/concepts/time-and-windows-in-ksqldb-queries.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-push-query.md
docs/reference/server-configuration.md
docs/reference/sql/appendix.md

From https://github.com/confluentinc/ksql/pull/9459.

docs: cherry-pick: restore docs for EMIT FINAL syntax (#9459)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgent.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/state/ServerState.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/healthcheck/HealthCheckAgentTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/healthcheck/HealthCheckResponseTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/HealthCheckResourceFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/HealthCheckResponse.java

Add the server state to the` /healthcheck` endpoint of the KSQL server since that endpoint isn’t currently authenticated. This is so the pre-stop cleanup hook can tell when the server has finished cleaning up state since it will wait until server state is `TERMINATED`. 
Updated tests

chore: add server state to healthcheck

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryBuilderTest.java

* fix: only use the internal topic id for the shared runtimes without a query id
* add case for prefix alt for old runtime
* remove type
Co-authored-by: Rohan <desai.p.rohan@gmail.com>

fix: only use the internal topic id for the shared runtimes without a… (#9470)

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/PostConditionsNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/TopicNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/Topic.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/model/PostConditionsNodeTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/StubKafkaServiceTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestExecutorTest.java

This is part of supporting schema references on QTT. First part is to add `keySchemaId` and `valueSchemaId` to the `topics` section in QTT tests. 
For example:
```
"CREATE STREAM INPUT WITH (kafka_topic='input', value_format='PROTOBUF', value_schema_id=5);",
"CREATE STREAM OUTPUT as SELECT * from INPUT;"
]
"topics": [
{
"name": "input",
"valueSchemaId": 5,
"valueFormat": "PROTOBUF",
"valueSchema": "syntax = \"proto3\";\n\nmessage Event {\n int64 timestamp = 1;\n}"
}
]
```
Currently, the ID specified in the CREATE statement is confusing 'cause the subjects ID do not exist yet. Seems we need to start with `1` and `2` if one key and key value schema are part of the `topics` section. You …

refactor: add 'keySchemaId' and 'valueSchemaId'  on QTT/topics sections

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/AssertExecutor.java
ksqldb-functional-tests/src/test/resources/sql-tests/test.sql

Make the assert executor only check the values of the columns specified in the assert command instead of the entire record.
Fixes #6056
Added a YATT test.

fix: allow assert values command to check partial columns

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksqldb-common/src/main/java/io/confluent/ksql/function/KsqlFunction.java
ksqldb-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksqldb-common/src/test/java/io/confluent/ksql/function/UdfIndexTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafTypes.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdafTypesTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/MiddleVarArgUdaf.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/TermCompiler.java
ksqldb-functional-tests/src/test/resources/historical_plans/middle-variadic-udaf_-_all_arguments/7.3.0_1660161097805/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/middle-variadic-udaf_-_all_arguments/7.3.0_1660161097805/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/middle-variadic-udaf_-_all_arguments/7.3.0_1660161097805/topology
ksqldb-functional-tests/src/test/resources/historical_plans/middle-variadic-udaf_-_no_variadic_args/7.3.0_1660161100790/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/middle-variadic-udaf_-_no_variadic_args/7.3.0_1660161100790/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/middle-variadic-udaf_-_no_variadic_args/7.3.0_1660161100790/topology
ksqldb-functional-tests/src/test/resources/historical_plans/middle-variadic-udaf_-_regular_arg_literal/7.3.0_1660161099405/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/middle-variadic-udaf_-_regular_arg_literal/7.3.0_1660161099405/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/middle-variadic-udaf_-_regular_arg_literal/7.3.0_1660161099405/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/middle-variadic-udaf.json
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeFunctionExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeFunctionExecutorTest.java

Follow-up to #9361. This PR adds support for a variadic argument anywhere in the function signature. There can still be only one variadic argument in the function signature.
This change is being made because we currently cannot support variadic UDAFs with initial arguments. Allowing a variadic argument in the middle removes this restriction.
The main changes to enable this feature are in `UdfIndex`. The tree of parameter types is now based on pairs of parameters, with one parameter from the left half of the parameter list and one parameter from the right half. This structure ensures the loop for variadic arguments is always at the bottom of the tree, eliminating most edge cases. There is also a new rule to determine function precedence:
> If two methods exist that match given the above …

feat: Support variadic arguments in the middle of a function signature

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/AssertExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/TestDriverPipeline.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java
ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/session-windows.sql

Previously YATT would throw serialization errors when trying to test windowed queries.
DDL over windowed sources is still not supported yet. We also can't directly assert windowstart/windowend yet without selecting them in the query.
Converted some of the tests from [session-windows.json](https://github.com/confluentinc/ksql/blob/master/ksqldb-functional-tests/src/test/resources/query-validation-tests/session-windows.json) to YATT tests.

fix: handle windowed queries in YATT

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/reference/server-configuration.md

Add admonitions about limits for the  COLLECT_LIST and COLLECT_SET aggregation functions in Confluent Cloud.
@JSeb225 , I assume the `ksql.functions.collect_list.limit` config also has a limit of 1000, is that true?

docs: document specific limits for CC COLLECT_SET (DOCS-15311)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/9486.

docs: cherry-pick: document specific limits for CC COLLECT_SET (DOCS-16838)

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/SchemaReferencesNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/TopicNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/SchemaReference.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/Topic.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/utils/SerdeUtil.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/StubKafkaServiceTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_specify_a_protobuf_schema_with_external_references/7.4.0_1661267781763/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_specify_a_protobuf_schema_with_external_references/7.4.0_1661267781763/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_specify_a_protobuf_schema_with_external_references/7.4.0_1661267781763/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/protobuf.json

This is part of the fix for https://github.com/confluentinc/ksql/issues/9169
The above fix requires QTT to support schema references in order to verify schemas with references will work. This PR does not fix the issue yet. It only allows QTT to use schema references on Protobuf. I added a test to validate schema references can be used in QTT.
For example:
```
"CREATE STREAM INPUT WITH (kafka_topic='input', value_format='PROTOBUF', value_schema_id=1);",
"CREATE STREAM OUTPUT as SELECT * from INPUT;"
],
"topics": [
{
"name": "input",
"valueFormat": "PROTOBUF",
"valueSchema": "syntax = \"proto3\";\n\nimport \"event.proto\"; \n\nmessage Logistics {\n Event event = 1;\n}", …
```

chore: add 'keySchemaReferences' and 'valueSchemaReferences' to QTT

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksqldb-common/src/main/java/io/confluent/ksql/function/UdfIndex.java
ksqldb-common/src/main/java/io/confluent/ksql/function/types/AnyType.java
ksqldb-common/src/main/java/io/confluent/ksql/function/types/ParamTypes.java
ksqldb-common/src/test/java/io/confluent/ksql/function/UdfIndexTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafTypes.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdafTypesTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/ObjVarColArgUdaf.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/function/UdfUtil.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/function/UdfUtilTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_different_decimals_in_var_arg/7.4.0_1661206992270/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_different_decimals_in_var_arg/7.4.0_1661206992270/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_different_decimals_in_var_arg/7.4.0_1661206992270/topology
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_list_in_var_arg/7.4.0_1661206996380/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_list_in_var_arg/7.4.0_1661206996380/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_list_in_var_arg/7.4.0_1661206996380/topology
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_map_in_var_arg/7.4.0_1661206995011/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_map_in_var_arg/7.4.0_1661206995011/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_map_in_var_arg/7.4.0_1661206995011/topology
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_no_variadic_args/7.4.0_1661206997735/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_no_variadic_args/7.4.0_1661206997735/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_no_variadic_args/7.4.0_1661206997735/topology
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_only_primitives_in_var_arg/7.4.0_1661206990896/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_only_primitives_in_var_arg/7.4.0_1661206990896/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_only_primitives_in_var_arg/7.4.0_1661206990896/topology
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_struct_in_var_arg/7.4.0_1661206993687/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_struct_in_var_arg/7.4.0_1661206993687/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/obj-var-col-arg-udaf_-_struct_in_var_arg/7.4.0_1661206993687/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/obj-var-col-arg-udaf.json
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeFunctionExecutorTest.java

Follow-up to #9361. This PR adds support for heterogeneous variadics in a UDAF variadic column argument by using `Object` as the type parameter to `VariadicArgs`. UDAF implementations must do the type checking manually if the aggregate type or output type depends on the input types. See `Udaf#getAggregateSqlType()` and `Udaf#getReturnSqlType()`.
A new `ParamType`, `AnyType`, has been added. It accepts any argument, but it can only be used by having `VariadicArgs<Object>` in the input type of a UDAF signature. Attempting to use `Object` anywhere else will prevent the UDAF or UDF from loading, as we do not intend to support that with this PR. This means having `Object...` as a UDAF initial argument is not supported.
User documentation for this will be added with the rest of the new docs for …

feat: Support `Object` as the type parameter for a UDAF variadic column argument

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LagReportingAgent.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/LagReportingAgentFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TerminateTransientQueryFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryStateStoreId.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocator.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializationFactory.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocatorTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializationFactoryTest.java

Hotfix: https://github.com/confluentinc/ksql/pull/9420

fix: track lag by queryId rather than applicationId (#9420)

---

ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryBuilderTest.java

Make sure the change log is named correctly in Gen1, Gen2 and with Gen1 queries running in Gen2  env.

test: verify change log is named correctly

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java

KSE-1001
The ksqlConnectIntegrationTest lacked a successful `CREATE CONNECTOR` response and `LIST CONNECTOR PLUGINS` which are added in this fix.
integration test
[KSE-1001]: https://confluentinc.atlassian.net/browse/KSE-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Enhance integration test coverage for ksql/connect integration

---

ksqldb-common/src/main/java/io/confluent/ksql/metrics/MetricAppender.java

Introduce `MetricAppender`, which can be added to the root logger to track the number of ERROR/WARN/INFO messages that are being logged for a host.
I spent quite a long time on the internet scouring to see if there's an already built implementation of this, but it looks like it's dependent on the metric system that you use (e.g. Prometheus and Dropwizard each have their own instrumenting adapter, but Kafka metrics systems do not). In the future, it may make sense to contribute this back to Kafka or some common Confluent repository.
I enabled it in the log4j configuration:
```
log4j.appender.metrics=io.confluent.ksql.metrics.MetricAppender
log4j.rootLogger=INFO, stdout, metrics
```
And then used `jconsole` to confirm the JMX beans were reported properly.

feat: add a customer log4j MetricAppender to track log level stats

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/utils/SerdeUtil.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_PROTOBUF_insert_query_with_schema_references/7.4.0_1661784103632/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_PROTOBUF_insert_query_with_schema_references/7.4.0_1661784103632/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/insert-into_-_PROTOBUF_insert_query_with_schema_references/7.4.0_1661784103632/topology
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_deserialize_and_serialize_schema_using_internal_references/7.4.0_1661374501015/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_deserialize_and_serialize_schema_using_internal_references/7.4.0_1661374501015/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_deserialize_and_serialize_schema_using_internal_references/7.4.0_1661374501015/topology
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_deserialize_and_serialize_schema_using_internal_references_using_schema_id/7.4.0_1661374501105/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_deserialize_and_serialize_schema_using_internal_references_using_schema_id/7.4.0_1661374501105/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_deserialize_and_serialize_schema_using_internal_references_using_schema_id/7.4.0_1661374501105/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/insert-into.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/protobuf.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactory.java

Fixes https://github.com/confluentinc/ksql/issues/9169
The SR config `id.compatibility.strict` is set to `false` in this PR when serialization happens on streams that have a XXX_SCHEMA_ID reference. 
The `id.compatibility.strict` to true is too restrictive. If true, then records with SR schemas that have references to external schemas cannot be serialized due to incompatible issues.  For instance, the below SR schema (schemaID = 1) imports the `Event` type from an external protobuf schema `event.proto`.
```
syntax = "proto3";
import "event.proto";
message Logistics {
string id = 1;
Event event = 2;
}
```
When running INSERT or C*AS statements, the call to the SR API resolves the schema by importing the imports and adding the external types to the main schema like this:
```
syntax = …
```

fix: disable SR ID_COMPATIBILITY_STRICT for Protobuf to allow serialization with external references

---

release_stabilization.py

Use the two registry updates that are currently working in branch [0.28.2-cc-docker-ksql.119.x](https://github.com/confluentinc/ksql/blob/0.28.2-cc-docker-ksql.119.x/release_stabilization.py#L6-L7)

Artifactory migration for release_stabilization.py

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TerminateTransientQueryFunctionalTest.java

Disable shared runtimes for TerminateTransientQueryFunctionalTest since it was making the test flaky.
Ran tests many times!

Disable shared runtimes for TerminateTransientQueryFunctionalTest

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-common/src/main/java/io/confluent/ksql/properties/with/CommonCreateConfigs.java
ksqldb-engine/src/main/java/io/confluent/ksql/topic/TopicCreateInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/topic/TopicCreateInjectorTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/AssertExecutorMetaTest.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceAsProperties.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceProperties.java

Injects `CLEANUP_POLICY` to `CreateSourceProperties` and `CreateSourceAsProperties`.
The cleanup policy is exposed visa the `getCleanupPolicy()` method in the respective property classes. 
- unit testing
- manual testing

feat: expose cleanup policy in create statements

---

docs/reference/server-configuration.md

Related: https://github.com/confluentinc/ksql/pull/9527.

docs: revert statestore.cache.max.bytes config (DOCS-17067)

---

docs/reference/server-configuration.md

Related: https://github.com/confluentinc/ksql/pull/9527.

docs: revert statestore.cache.max.bytes config (DOCS-17068)

---

ksqldb-common/src/main/java/io/confluent/ksql/parser/NodeLocation.java
ksqldb-common/src/main/java/io/confluent/ksql/parser/TokenLocation.java
ksqldb-common/src/test/java/io/confluent/ksql/parser/TokenLocationTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/AstSanitizer.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/KsqlTestException.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/DirectiveParser.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/ParsingException.java
ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserUtil.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/DescribeConnectorTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/ListConnectorsTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/PartitionByTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/util/ParserUtilTest.java

- Change constructor of `NodeLocation` to:
```java
public NodeLocation(final TokenLocation start, final TokenLocation stop) {
this.start = start;
this.stop = stop;
}
```
Take the example SQL:
```sql
CREATE TABLE customer_bookings
WITH (KAFKA_TOPIC = 'customer_bookings', KEY_FORMAT = 'JSON', VALUE_FORMAT = 'JSON') AS
SELECT C.EMAIL,
B.id,
B.flight_id,
COUNT(*)
FROM bookings B
INNER JOIN customers C ON B.customer_id = C.id
WINDOW TUMBLING (SIZE 1 HOUR, GRACE PERIOD 2 HOURS)
WHERE B.customer_id > 0 AND INSTR(C.EMAIL, '@') > 0
GROUP BY C.EMAIL, B.ID, B.flight_id
HAVING COUNT(*) > 0;
```
These will be the arguments for the root CTAS statement:
Using these new parameters, 2 new public methods are introduced for `NodeLocation`:
```java
public OptionalInt getStopLine() {
return stop.getLine();
} …
```

feat: add stop co-ordinates to NodeLocation

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicBackupImpl.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicMigrationUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/CommandTopicBackupImplTest.java

When migrating the command topic, we fence off the old command topic with a migration command from other running servers that haven't migrated yet. We shouldn't back this command into the backup file since it's not a valid command
unit test

chore: skip migration command in command topic backup

---

docs/operate-and-deploy/installation/install-ksqldb-with-docker.md

From https://github.com/confluentinc/ksql/pull/9458.
Adding a newline to avoid the need to remember to leave an empty line at the end of a KSQL script to allow for EXIT to be correctly appended to the script.

docs: cherry-pick: adding newline to allow correct script execution (DOCS-17111)

---

docs/operate-and-deploy/installation/install-ksqldb-with-docker.md

From https://github.com/confluentinc/ksql/pull/9458.
Adding a newline to avoid the need to remember to leave an empty line at the end of a KSQL script to allow for EXIT to be correctly appended to the script.

docs: cherry-pick: adding newline to allow correct script execution (DOCS-17112)

---

ksqldb-common/src/main/java/io/confluent/ksql/properties/with/CreateConfigs.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceProperties.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourceAsPropertiesTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourcePropertiesTest.java

Add a Stream/Table property `sourced_by_connector` to indicate which source connector is writing to it. This helps express the dataflow between connectors and the topics they source.
For example: 
```
CREATE SOURCE CONNECTOR `jdbc-connector` WITH(
"connector.class"='io.confluent.connect.jdbc.JdbcSourceConnector',
"connection.url"='jdbc:postgresql://localhost:5432/my.db',
"mode"='bulk',
"topic.prefix"='jdbc-',
"table.whitelist"='users',
"key"='username');
CREATE STREAM users (
page_id BIGINT KEY
) WITH (
KAFKA_TOPIC = 'jdbc-users',
VALUE_FORMAT = 'JSON_SR'
SOURCED_BY_CONNECTOR = 'jdbc-connector'
);
```
Please note that there is no validation logic for ensuring that the source connector exists. This is a cosmetic change.
- unit tests

feat: add source connector property to CREATE SOURCE statements

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutorTest.java

The RQTT proto response validator was checking the order of responses even if `verifyOrder` is set to true. As a result, sometimes RQTT protobuf tests fail due to incorrect ordering.
Passes RQTTs locally, added unit tests

test: ignore order of protobuf responses in rqtt

---

docs/operate-and-deploy/installation/server-config/index.md

From https://github.com/confluentinc/ksql/pull/9548.

docs: cherry-pick: fix typo in server config section on schemas (DOCS-17150)

---

docs/operate-and-deploy/installation/server-config/index.md

From https://github.com/confluentinc/ksql/pull/9548.

docs: cherry-pick: fix typo in server config section on schemas (DOCS-17151)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandIdAssigner.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/ValidatedCommandFactory.java

Refactor so that we have these static methods to get the command and command id objects for `TERMINATE CLUSTER`

MINOR: add static terminate cluster command and id

---

Jenkinsfile
pom.xml

Pinned nanoversions aren't completely implemented for the release stabilization tool, so cutting this release resulted in a mixed dependency set. This PR manually fixes up the dependencies and disables pinned nanoversions.
For future reference, there are two commits we need to undo for releases to function:
https://github.com/confluentinc/ksql/commit/577029425c4ae4288fa527488acf1ef4820aade2
https://github.com/confluentinc/ksql/commit/d3545b9d8873465f967b6e951a45260fb775c948
See also the 0.28 rollback:  https://github.com/confluentinc/ksql/pull/9374

fix: roll back pinned nanoversions

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/PreconditionChecker.java

The precondition checker was using raw configs to create an http client, so if a user uses  [secrets protection](https://docs.confluent.io/platform/current/security/secrets.html), then the client created would use passwords like `${securepass...}` instead of the actual password that gets resolved in `AbstractConfig`
Manually tested

fix: use resolved configs in precondition checker

---

ksqldb-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceFactory.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/DataSourceExtractor.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/MetaStore.java
ksqldb-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java

Generalises the solution for [issue#9243](https://github.com/confluentinc/ksql/issues/9243)
When performing `DROP` on a source name with a very special case of typo (typing source name mistakenly with/without double quotes), the error message is the same as when the source is not existing at all. This fix adds a Hint to the error message to make it more informative.
Unit test
manual testing

fix: enhance error messages when source has extra/lacks double quotes

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/HighAvailabilityTestUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/IntegrationTestUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryLimitHARoutingTest.java

Previously, we weren't ensuring that the active was actually caught up with input, so refactored logic from RQTT to be used.   Also, we didn't ensure that the reported lags were zero, ensuring that standbys were caught up.
These introduced race conditions. where we would query a state store that wasn't guaranteed to be up to date with the upstream topics.
After discussing with @cprasad1, I decided to also remove the HA checks since we have these elsewhere and they have little to do with limit functionality.
Also, makes the test dedupe the results.  This is because after hitting the limit, the last row appears periodically (but rarely) to be duplicated.  I tried for a while to debug this, but this will have to wait for a future PR.
_Describe the testing strategy. Unit and integration tests …

test: Makes PullQueryLimitHARoutingTest more reliable

---

Jenkinsfile

remove cc-docker-ksql from downstream builds for 7.3.x as we
don't cut cp release branches for cc-docker-ksql.

remove cc-docker-ksql from downstream builds

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java

Generalises the solution for [issue#9243](https://github.com/confluentinc/ksql/issues/9243)
When performing `DESCRIBE` on a source name with a very special case of typo (typing source name mistakenly with/without double quotes), the error message is the same as when the source is not existing at all. This fix adds a Hint to the error message to make it more informative.
Unit test
Manual testing

fix: give hint when source name has extra/lacks dquotes

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionFactory.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java

Related to [issue#9243 ](https://github.com/confluentinc/ksql/issues/9243) ([PR#9531](https://github.com/confluentinc/ksql/pull/9531))
The output of `SHOW STREAMS/TABLES` must list the source names that contain small letters wrapped in double quotes.  This avoids the confusion for using the source names in other commands such as `SELECT`, `DROP`, and etc.
Unit test
Manual testing

fix: show command must list the exact names of sources

---

docs/reference/metrics.md

These metric attributes don't really give a good measurement of query health, as they just sample however many queries happen to be in a given state at any given time - which doesn't really give any good information if a given query is healthy or not over a period of time.
Please see https://confluentinc.atlassian.net/browse/KSE-1040?filter=21619

KSE-1040 Remove misleading metric attributes from docs

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/KsqlResourceFunctionalTest.java

We've seen the `KsqlResourceFunctionalTest.shouldHandleInterDependantCsasTerminateAndDrop()` test fail three times in the past year (twice in the past three months) due to a timeout while waiting for the command topic consumer to finish processing prior statements. The test currently uses the default of 5 seconds for this timeout. This PR increases the timeout to 30 seconds for this test (extra conservative) since our CI is known to be slow at times, in order to de-flake the test.

test: increase command runner timeout for KsqlResourceFunctionalTest

---

mkdocs.yml

From https://github.com/confluentinc/ksql/pull/9609.

docs: remove Python and Dotnet clients from TOC (DOCS-18252)

---

mkdocs.yml

From https://github.com/confluentinc/ksql/pull/9609.

docs: remove Python and Dotnet clients from TOC (docs-18253)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/RequestValidator.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/validation/RequestValidatorTest.java

If persistent query limit count has been reached, don't an error for statements like `SHOW STREAMS;` because that would cause the healthcheck to fail.
unit tests + manual test

fix: dont throw persistent query limit errors for non-queries

---

pom.xml

Remove `rc2` from pom.xml
It still builds after I remove it and rc2 code is same without it in Schema Registry.

fix: remove rc2

---

CONTRIBUTING.md

release tag doesn't have `ksqlDB` in it now

fix: fix tag pattern in doc

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/TransientQueryCleanupService.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/TransientQueryCleanupServiceTest.java

There were leaked transient topics not cleaned up due to a bug. The leaked transient topic pattern is `<topic_prefix>_<query_id>_<suffix>`. But the pattern in local commands file is `<topic_prefix>_transient_<query_id>_<timestamp>`. This PR extracts `query_id` from local commands and construct the leaked transient topic pattern with it to match leaked transient topic so that they could be cleaned up.
unit test

cleanup fix

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java

This is a follow-up to https://github.com/confluentinc/ksql/pull/9303. The source of the flakiness is indeed because the subscriber is registered async. However, the query publisher is not registered until after the streamQuery() call is made, which means the first fix (which places the wait into the setup() method) is a no-op. This patch moves the wait into the test itself to be after streamQuery() is called.

test: fix flaky ClientTest.shouldFailPollStreamedQueryResultIfFailed

---

ksqldb-common/src/main/java/io/confluent/ksql/util/BytesUtils.java
ksqldb-common/src/test/java/io/confluent/ksql/util/BytesUtilTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/TestHeader.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/headers.json
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SourceBuilderUtils.java

Headers with null fields were not being handled, which caused NPEs:
```
./bin/kafka-console-consumer --bootstrap-server localhost:9092 --topic headersbugtopic --from-beginning --property print.headers=true
some_value_header:0,null_header:null	Value123
ksql> create stream headerbugstr(key string key, value string, h1 ARRAY<STRUCT<key STRING, value BYTES>> HEADERS) with (kafka_topic='headersbugtopic',value_format='kafka');
Message        
Stream created 
ksql> select * from headerbugstr emit changes;
+--------------------------------------------------------------------+--------------------------------------------------------------------+--------------------------------------------------------------------+
|KEY …
```

fix: null handling in headers

---

ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types/7.4.0_1666063444063/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types/7.4.0_1666063444063/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types/7.4.0_1666063444063/topology
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types_and_default_value/7.4.0_1666063444283/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types_and_default_value/7.4.0_1666063444283/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types_and_default_value/7.4.0_1666063444283/topology
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types_and_default_value_in_the_end_of_schema/7.4.0_1666063444659/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types_and_default_value_in_the_end_of_schema/7.4.0_1666063444659/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types_and_default_value_in_the_end_of_schema/7.4.0_1666063444659/topology
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types_and_optional_value/7.4.0_1666063444480/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types_and_optional_value/7.4.0_1666063444480/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/avro_-_VALUE_SCHEMA_ID_with_compound_types_and_optional_value/7.4.0_1666063444480/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/avro.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/insert-values.json
ksqldb-serde/src/main/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslator.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/avro/AvroSRSchemaDataTranslatorTest.java

Fixes #8919 
- Logical schema generated by Ksql always contains optional fields.
- The Schema Registry registered Avro schema may or may not contain optional
fields.
- If the SR schema doesn't contain optional fields for compound data types such
as array, map, struct then the schema comparison between logical and physical
schemas fails.
- To fix this, we create a copy of the data using the physical schema thus
getting rid of any optional fields in the process. Schema type validation is
done before this step and therefore copying the data using physical schema is
a safe process.
Added QTTs
Added RQTT
Pending - generate historical plans

Fix avro optional fields

---

ksqldb-rest-app/pom.xml
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/ServerVerticle.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/spi/Endpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/TestEndpoints.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/InsertsStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/PullQueryRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/perf/QueryStreamRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlTestResult.java
ksqldb-testing-tool/src/main/java/io/confluent/ksql/tools/test/KsqlTestException.java
ksqldb-testing-tool/src/main/java/io/confluent/ksql/tools/test/parser/SqlTestLoader.java

Adds a rest endpoint to run YATT tests. The endpoint is `/test` and the request body would be a string of one or more YATT tests.
Output is a list of objects:
```
[{
name: <name of test>,
result: {true if pass, false if fail},
message: <error message if test failed>
}]
```
integration test passes

feat: add endpoint to run sql tests

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Uuid.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/UuidTest.java
pom.xml

Issue
* https://github.com/confluentinc/ksql/issues/9639

feat:Support Bytes to UUID UDF Function

---

docs/reference/serialization.md

Add detail describing the difference between JSON and JSON_SR formats when using Confluent Schema Registry.

docs: add section for per-format schema syntax (KSE-1294)

---

pom.xml

bump vert.x to 3.9.14 and netty to 4.1.84.Final
output of `mvn dependency:tree -Dincludes=io.netty:netty-codec-http`:
```           
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 12.6
[INFO] os.detected.version.major: 12
[INFO] os.detected.version.minor: 6
[INFO] os.detected.classifier: osx-x86_64
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ksqldb-parent                                                      [pom]
[INFO] …
```

chore: bump vert.x to 3.9.14 and netty to 4.1.84.Final

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/restore/KsqlRestoreCommandTopic.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/RestoreCommandTopicIntegrationTest.java
pom.xml

It seems that old records have a null value for runtime ID and the deserializer doesn't interrupt that as an empty optional. Se we add a new check to filter those out.

fix: prevent null values in runtimeID cmd records from throwing errors

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/Cli.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/JLineReader.java
ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/cmd/RemoteServerSpecificCommand.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
ksqldb-common/src/main/java/io/confluent/ksql/util/ErrorMessageUtil.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlStatementException.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/QueryAnonymizer.java
ksqldb-engine/src/main/java/io/confluent/ksql/logging/query/QueryLogger.java
ksqldb-engine/src/test/java/io/confluent/ksql/logging/query/QueryLoggerTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/key-schemas.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-ctas-materialized.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-materialized-aggregates.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-streams.json
ksqldb-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/RestoreCommandsCompactor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/query/QueryExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/QueryCapacityUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PauseResumeIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/query/QueryExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/QueryCapacityUtilTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/Errors.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlRequest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlStatementErrorMessage.java

* fix: use QueryLogger for logging queries
* anonymize processed queries
* logging for unparsable queries
* anonymized query handling logs
* anonymized received queries
* anonymized streaming query
* checkstyle
* prevent exception from querylogger
* don't include statement text in exception message
* don't include statement text in exception messages
* fix tests
* fix tests
* fix tests
* checkstyle
* checkstyle
* fix parser test
* fix tests
* checkstyle
* restore ability to print errors in CLI
* checkstyle
* checkstyle
* fix error code
* One more fix for RestoreCommandsCompactor
* Fix style bug
Co-authored-by: Alan Sheinberg <asheinberg@confluent.io>
_Describe the testing strategy. Unit and integration …

chore: Use QueryLogger any time we log a query (#9681)

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/reference/serialization.md
ksqldb-common/src/main/java/io/confluent/ksql/properties/with/CommonCreateConfigs.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/ConnectSerdeSupplier.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/protobuf/ValueSpecProtobufSerdeSupplier.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/protobuf.json
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceAsProperties.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceProperties.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourceAsPropertiesTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourcePropertiesTest.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufProperties.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufSchemaTranslator.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactory.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufPropertiesTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufSchemaTranslatorTest.java
ksqldb-testing-tool/src/main/java/io/confluent/ksql/tools/test/driver/AssertExecutor.java

The protobuf support in schema registry by default represents an optional field (corresponding in KSQL to a nullable SQL column) by a singular protobuf field. For primitive types, singular protobuf fields cannot distinguish default values (such as `0` for `int32` and `""` for `string`) from `null`.
This change introduces two properties for the KSQL `CREATE` statements that can enable two alternative representations of nullable fields. The properties are named `KEY_PROTOBUF_NULLABLE_REPRESENTATION`and `VALUE_PROTOBUF_NULLABLE_REPRESENTATION` which control the nullable behavior for keys and value serialization, respectively. Both new properties can take the values `OPTIONAL`, to use protobuf's `optional` keyword, or `WRAPPER`, to use nullable protobuf wrappers (e.g. using …

feat: Alternative representations for nullable protobuf fields

---

pom.xml

Not needed after https://github.com/confluentinc/common/pull/485.

APIF-3122: Unpin Protobuf version.

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/reference/serialization.md
ksqldb-common/src/main/java/io/confluent/ksql/properties/with/CommonCreateConfigs.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/driver/AssertExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/ConnectSerdeSupplier.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/serde/protobuf/ValueSpecProtobufSerdeSupplier.java
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null/7.4.0_1668008700948/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null/7.4.0_1668008700948/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null/7.4.0_1668008700948/topology
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_optional/7.4.0_1668008701004/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_optional/7.4.0_1668008701004/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_optional/7.4.0_1668008701004/topology
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_wrapper/7.4.0_1668008701047/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_wrapper/7.4.0_1668008701047/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_wrapper/7.4.0_1668008701047/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/protobuf.json
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceAsProperties.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceProperties.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourceAsPropertiesTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/properties/with/CreateSourcePropertiesTest.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufProperties.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufSchemaTranslator.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufSerdeFactory.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufPropertiesTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufSchemaTranslatorTest.java

The protobuf support in schema registry by default represents an
optional field (corresponding in KSQL to a nullable SQL column) by
a singular protobuf field. For primitive types, singular protobuf
fields cannot distinguish default values (such as 0 for int32 and
"" for string) from `null`.
This change introduces a new option for KSQL `CREATE` statements
that can enable two alternative representations of nullable fields.
One is to use nullable protobuf wrappers
(e.g. using `google.protobuf.StringValue` for strings), the other
is to use the `optional` keyword. Both options will allow KSQL and
downstream consumers to clearly distinguish between default values
and `null`.
New unit tests are added to cover that the properties are
propagated from the `CREATE` statement to the `Serde` …

feat: Alternative representations for nullable protobuf fields (backport)

---

pom.xml

**Context**
packaging/7.1.x and 7.2.x [smoke tests](https://jenkins.confluent.io/job/confluentinc/job/packaging/job/7.1.x/570/execution/node/583/log/) are failing on error `Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/internal/tcnative/CertificateCompressionAlgo`
Quick search of this issue gives me this slack convo, which indicates that tcnative version needs to be 2.0.50+ https://confluent.slack.com/archives/C209F54E8/p1667547233169589
**Changes:**
Update tcnative version to 2.0.54.Final. Checked netty versions and the tcnative version corresponding to the current netty-4.1.84.Final being used here should be [2.0.54.Final](https://github.com/netty/netty/blob/netty-4.1.84.Final/bom/pom.xml#L68)
To be pint merged through 7.2.x onwards

Bump netty tcnative version to 2.0.54.Final

---

docs/developer-guide/ksqldb-reference/table-functions.md

From https://github.com/confluentinc/ksql/pull/9724.

docs: cherry-pick: clarify table functions support only stream sources (DOCS-19041)

---

docs/developer-guide/ksqldb-reference/table-functions.md

From https://github.com/confluentinc/ksql/pull/9724.

docs: cherry-pick: clarify table functions support only stream sources (DOCS-19042)

---

docs/developer-guide/ksqldb-reference/table-functions.md

From https://github.com/confluentinc/ksql/pull/9724.

docs: cherry-pick: clarify table functions support only stream sources (DOCS-19043)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionFactory.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java

solves issue #9730 
Currently, the command `show streams/tables`, lists the names of sources that have been originally creates using double quotes wrapped in back ticks, while the expected behaviour is that all source names are listed as they are not wrapped within any other character.
Unit tests
Manual testing

fix: show streams/tables should not return names in back tick

---

docs/how-to-guides/test-an-app.md
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/KsqlTestingTool.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/KsqlTestingToolTest.java

Fixes #4665 
Current behavior is the ksql-test-runner exits with only a "0" exit code regardless if it encounters an error while executing or if any tests fail that it is running. This prevents use in a CI/CD deployment pipeline. The change I submit here will let ksql-test-runner return exit code "1" if any test failure or errors are encountered and a "0" exit code if all tests completed successfully.
I have included modifications to existing unit tests that verify the ksql test runner does return a "0" exit code on successful executions and a "1" exit code on any test failures or errors encountered while attempting to run the ksql tests.
I have also executed the KsqlTestingTool.java class from my IDE with parameters to a ksql test I wrote and validated the program returns the expected …

feat: ksql-test-runner tool returns exit code "1" on test failure

---

pom.xml

This fixes CVE-2022-41881 and, potentially, CVE-2022-41915 vulnerabilities.

[KSE-1612] Upgrade netty to 4.1.86

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java
pom.xml

pinned-dependencies tooling is only partially completed, so CP branch cuts require some manual work. This commit bumps our SR dependency to the 7.5 series, pins the parent pom in the 7.5 series, and fixes a failing test related to the updated SR dependency.
running the CI job is sufficient

fix: complete transition to 7.5.x series

---

docs/overrides/main.html

[SSEO-3393](https://confluentinc.atlassian.net/browse/SSEO-3393)
In order to make content from [ksqlDB Docs](https://docs.ksqldb.io) searchable via Zendesk Federated Search in Support Portal ([support.confluent.io](https://support.confluent.io/hc)), we need to add a HTML meta tag to this website.
Zendesk's search crawler uses this tag for domain verification each time it runs and more info about the crawler setup can be found in [support.zendesk.com/hc/en-us/articles/4593564000410](https://support.zendesk.com/hc/en-us/articles/4593564000410).
[SSEO-3393]: https://confluentinc.atlassian.net/browse/SSEO-3393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SSEO-3393 - Add metatag for Zendesk search crawler

---

ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java

Right now there is no way to find out what happened when embedded Kafka cluster fails to delete the log directory. This commit adds the stacktrace into the log message.

chore: Add exception into the error message when KafkaEmbedded fails to delete log dir

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RemoteHostExecutor.java

Currently when the flaky test `io.confluent.ksql.rest.integration.TerminateTransientQueryFunctionalTest.shouldTerminatePushQueryOnAnotherNode ` fails , we get the following unhelpful log line.
```
[2022-12-21 17:48:19,595] WARN Failed to retrieve info from host: HostInfo{host='localhost', port=1239}, statement: terminate transient_PAGEVIEW_KSTREAM_609054729411180441;, cause: null (io.confluent.ksql.rest.server.execution.RemoteHostExecutor:135)
[2022-12-21 17:48:19,599] INFO Processed unsuccessfully: KsqlRequest{configOverrides={}, requestProperties={}, commandSequenceNumber=Optional.empty} (26a2ed7f-da74-3a24-b1d5-20c11ce11610): TERMINATE query; (io.confluent.ksql.logging.query.QueryLogger:98)
```
And the “cause: null” isn’t very helpful. Hopefully next time it fails, we will have a …

chore: log whole exception not just message to avoid null error message

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenSpec.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenUtil.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CompiledExpression.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/CodeGenTestUtil.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/CompiledExpressionTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluatorTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/helpers/NullSafeTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java

Fixes #9353
When generating java from ksql, all arguments are passed as individual method arguments. The java compiler only allows up to 255 method arguments. After a ksql statement reaches a certain size, this limit is nolonger sufficient resulting in the following ClassFormatError:
`Exception in thread "main" java.lang.ClassFormatError: Too many arguments in method signature in class file SC
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
at org.codehaus.janino.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:74)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at …

fix: use args map instead of method args in generated java code

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopologyTestDriverContainer.java

The code for running query translation tests doesn't call close() on the TopologyTestDriver instances it creates, which means thousands of them accumulate until the entire suite of QTTs is finished running. This PR calls close on the TopologyTestDrivers after each individual test case is run, in order to prevent accumulation of resources (e.g., tens of thousands of file descriptors) while the test suite is running.
Verified that open file descriptors no longer accumulate while the QTT suite is running.

test: close TopologyTestDrivers in between QTTs (MINOR)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java

`ApiTest#shouldHandleErrorInProcessingQuery` test failed for no apparent reason. The assertion that was not satisfied reads a set of keys from a `ConcurrentHashMap` and verifies that that set is empty. The theory is that the assertion reads the set of keys before the key is concurrently removed from the hash map. This PR replaces the failing assertion with an assertion that retries the assertion for a certain amount of time before it fails.    
Tested locally

test: wait for successful assertion to avoid test failure due to race

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PauseResumeIntegrationTest.java

Fixes flaky pause/resume integration test. The test pauses a query and then it verifies that the REST app has a paused query and that the metrics show the query as paused. The latter verification has failed sometimes because the metrics have not been updated before the verification was called. This PR repeatedly verifies the metrics and only fails after the metrics do not show the paused state after a certain period of time.    
Before the fix, the test failed locally every 2-3 runs. With the fix the test run 50 times in a row without failure.

test: fix flaky pause/resume integration test

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

`JSON_ITEMS` will be available for users in the [0.29.0 release](https://github.com/confluentinc/ksql/commit/c62c2d24fb0ee687b3824941464c368a8f0a74d2). However, the docs claim that the function is available since 0.28.0 which confuses our users - https://github.com/confluentinc/ksql/issues/9786#issuecomment-1436362671.
This PR changes `JSON_ITEMS` release to 0.29.0.

docs: Fix the release for JSON_ITEMS

---

ksqldb-api-reactive-streams-tck/pom.xml

testng needs to be upgraded to 7.7.0 due to a CVE. See https://github.com/confluentinc/ksql/security/dependabot/24
Successfully build with `mvn -pl ksqldb-api-reactive-streams-tck clean verify`.
Command `mvn dependency:tree -Dincludes=org.testng:testng | grep -C 5 testng` only shows the upgraded version.

chore: upgrade testng to 7.7.0

---

Jenkinsfile

jenkins/dockerfile uses Java 8 to build ksql. With the recent upgrade of testng to 7.7.0 (https://github.com/confluentinc/ksql/commit/096155ee27aa7772dc5b2fdf56cb29cdf8ccc5ca) Java 11 is required. jenkins/common is able to use Java 11.

chore: use jenkins/common instead of jenkins/dockerfile

---

ksqldb-api-reactive-streams-tck/pom.xml

Adds the `surefire-testng` so that builds can find the testng tests in ksqldb-api-reactive-streams-tck` sub-module.
Tested locally by running `/mvnw  clean install -pl ksqldb-api-reactive-streams-tck` and observing that the build did run the tests.

chore: Fix testng test running.

---

Jenkinsfile
ksqldb-api-reactive-streams-tck/pom.xml

Reverts https://github.com/confluentinc/ksql/pull/9801 and corresponding follow-up changes https://github.com/confluentinc/ksql/pull/9807 and https://github.com/confluentinc/ksql/pull/9805 on older branches since these older branches are not set up to run with Java 11 (there are various test failures due to discrepancies between Java 8 and 11). This revert will only be merged forward through 7.1.x, as newer branches are already Java 11 compatible.

chore: revert testng dependency to 6.11 on older branches

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java

Catches TopicAuthorizationException in KafkaTopicClient#getTopicConfig and transforms it to KsqlTopicAuthorizationException.
Unit testing

fix: catch TopicAuthorizationExceptions when getting topic config

---

ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlRequest.java

This fix was spread over several commits, so I'm squashing it into one backportable chunk. Most of it is a no-op on 7.3.
chore: Use QueryLogger any time we log a query (#9681)
* fix: use QueryLogger for logging queries
* anonymize processed queries
* logging for unparsable queries
* anonymized query handling logs
* anonymized received queries
* anonymized streaming query
* checkstyle
* prevent exception from querylogger
* don't include statement text in exception message
* don't include statement text in exception messages
* fix tests
* fix tests
* fix tests
* checkstyle
* checkstyle
* fix parser test
* fix tests
* checkstyle
* restore ability to print errors in CLI
* checkstyle
* checkstyle
* fix error code
* One more fix for RestoreCommandsCompactor
* Fix style bug
Co-authored-by: Alan …

chore: Backport Use QueryLogger any time we log a query

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientOptionsImpl.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/MigrationConfig.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/commands/NewMigrationCommand.java
ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsUtil.java

Ever since https://github.com/confluentinc/ksql/pull/9717, the ksql-migrations tool doesn't work without basic auth because an NPE is hit as soon as the tool needs to interact with the ksql server because the default basic auth password is null, and the previous change calls `.value()` on it.
This PR fixes the bug by changing the password config defaults (and related non-password configs for consistency) from null to empty string instead. 
The earlier regression wasn't caught by our integration testing because the integration tests only run with basic auth enabled. I updated the test locally to run without basic auth and saw the regression was fixed.

fix: migrations tool without basic auth works again

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/MigrationsUtil.java

https://github.com/confluentinc/ksql/pull/9821 was merged to 6.2.x and encountered no conflicts merging forward to later branches, but one of the imports which existed on 6.2.x does not exist on later branches, and led to a compilation error. This PR fixes the error and will be merged forward to later branches as well.
Compilation error is fixed.

chore: fix compilation error from bad merge

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/DefaultKsqlClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/services/RestServiceContextFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/services/DefaultKsqlClientTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/services/TestDefaultKsqlClientFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/services/TestRestServiceContextFactory.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlTargetTest.java

Sets a timeout for pull query requests which are forwarded to 20s by default, though allows it to be set by the client.
Unit tests, plus was able to test manually.

fix: Set timeout for pull query forwarded requsts to 20s

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/AuthenticationPluginHandler.java

Avoid calling `context.fail()` twice as currently its possible for both the plugin and the plugin handler to do so.
Existing tests

fix: Avoid calling context.fail() twice

---

ksqldb-engine/src/main/java/io/confluent/ksql/execution/pull/HARouting.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/PullQueryExecutorMetrics.java
ksqldb-engine/src/test/java/io/confluent/ksql/execution/pull/HARoutingTest.java

Addresses issue https://github.com/confluentinc/ksql/issues/8816 
Revert the change of partition fan out and replace it with node fan out, i.e a pull query is forwarded to at most # ksql-nodes and hence uses at most # ksql-nodes threads. 
Note, this is not a fix of the deadlock problem but will make it much less prevalent. A fix would require breaking of the circular dependencies between the pools: we would need to differentiate between the pools that accept external pull query requests and internal forwarded requests. 
Metrics for the thread pools are added in subsequent PR.
Existing unit and integration tests

chore: revert partition fan out to reduce chance of deadlock

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QueryStreamHandler.java

Addresses issue https://github.com/confluentinc/ksql/issues/9282 for the \query endpoint. The migration flag is true by default so I only fixed it in `QueryStreamHandler`
```
curl -v -X "POST" "http://localhost:8088/query"      -H "Accept: application/vnd.ksql.v1+protobuf"      -d $'{
"ksql": "SELECT * FROM tab3;",
"streamsProperties": {}
}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8088...
* Connected to localhost (127.0.0.1) port 8088 (#0)
> POST /query HTTP/1.1
> Host: localhost:8088
> User-Agent: curl/7.87.0
> Accept: application/vnd.ksql.v1+protobuf
> Content-Length: 62
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< content-type: …
```

chore: return content type in header response for /query endpoint

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopic.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicMigrationUtil.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/QueuedCommand.java

We need to recreate the command topic on the new broker with records as byte array. If we deserialize and then re-serialize records from the old command topic, we can inadvertently add new fields to the new records due to new fields that we introduce to the command object.

hotfix: fix command topic migration to produce byte array records to command topic

---

ksqldb-serde/src/main/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerializer.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/delimited/KsqlDelimitedSerializerTest.java

bugfix: NPE for BigDecimal in CSV serializer

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ClusterTerminationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TransientQueryResourceCleanerIntTest.java
ksqldb-test-util/pom.xml
pom.xml

Switch ksql dependency to ce-kafka for all kafka related dependencies (kafka-clients, kafka-streams, connect etc)
* Existing tests.
* Manually build docker image and tested in ccloud
* Install with `./mvnw clean install -DversionFilter=true -Dspotbugs.skip  -DskipTests -Dcheckstyle.skip=True  -am -pl ksqldb-console-scripts,ksqldb-metastore,ksqldb-parser,ksqldb-rest-app,ksqldb-rocksdb-config-setter,ksqldb-version-metrics-client`
* Verified dependencies don't have `ccs` anywhere: 
```
hli@MacBook ~/projects/confluentinc/ksql$ ./mvnw dependency:tree | grep ccs
hli@MacBook ~/projects/confluentinc/ksql$
```

chore: change kafka dependencies to ce-kafka

---

Jenkinsfile

Changes from #9870 ported to 7.4.x.
I realized that commits are not back-ported, but rather older branches are merged into newer ones.
So I plan to merge this PR into 7.4.x and then pint-merge into master.

chore: Only trigger downstream docker build for master branch

---

ksqldb-engine/src/main/java/io/confluent/ksql/security/DefaultKsqlPrincipal.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlPrincipal.java
ksqldb-engine/src/test/java/io/confluent/ksql/security/DefaultKsqlPrincipalTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/DefaultApiSecurityContext.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/JaasPrincipal.java

Add port number to principle as well since it's needed to populate client port config `confluent.proxy.protocol.client.port` in addition to ip config `confluent.proxy.protocol.client.address`.
Unit test

chore: [1/N][client_ip]add port to principle

---

ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/SinkBuilder.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SinkBuilderTest.java

Checks if the record is a tombstone before it is forwarded to the sink topic. 
Before this change, a tombstone record would cause a NullPointerException when ksql tries to extract the timestamp from the value since the value of a tombstone is null. The NullPointerException caused the following error log message:
"Error writing row with extracted timestamp: null","record":null,"cause":["java.lang.NullPointerException"]
If the record is a tombstone the stream time is used as the timestamp of the tombstone record.  
Added a unit test.

fix: check for tombstone before forwarding to sink

---

PULL_REQUEST_TEMPLATE.md

We used to bump the ksql command version on every release but that no longer makes sense as we switch to more frequent releases. Instead, we'll now leave it up to code contributors and reviewers to evaluate whether changes require bumping the command version, and to bump the version as part of those changes if so. This PR adds the relevant line item into the PR template.

chore: add item for rollback compatibility into PR template (MINOR)

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java

`QUOTED_STRING_OR_WHITESPACE` regex suffers from catastrophic backtracking. At the same time, the only method using this regex does not require extracting quoted strings that causes the backtracking issue.
https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/ksql/job/PR-9881/2/

fix: Replace regex in CommandParser with a split by space

---

ksqldb-tools/src/main/java/io/confluent/ksql/tools/migrations/util/CommandParser.java

QUOTED_STRING_OR_WHITESPACE regex suffers from catastrophic backtracking. At the same time, the only method using this regex does not require extracting quoted strings that causes the backtracking issue.
This is a port of https://github.com/confluentinc/ksql/pull/9881 to 6.2.x.
CI run - https://jenkins.confluent.io/job/Confluent%20Public%20Repo%20PR%20builder/job/ksql/job/PR-9883/1/

Fix remove unnecessary complex regex

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

From https://github.com/confluentinc/ksql/pull/9891.

docs: cherry-pick: millisecond format limit is 9 digits in PARSE_TIMESTAMP (DOCS-23668)

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

From https://github.com/confluentinc/ksql/pull/9891.

docs: cherry-pick: millisecond format limit is 9 digits in PARSE_TIMESTAMP (DOCS-23669)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RemoteHostExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TerminateTransientQueryFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/RemoteHostExecutorTest.java

`TerminateTransientQueryFunctionalTest` has been historically flaky, and the most recent fix was to improve the logging https://github.com/confluentinc/ksql/pull/9784.
`[2023-04-19 09:42:55,508] WARN Failed to retrieve info from host: HostInfo{host='localhost', port=1621}, statement: terminate transient_PAGEVIEW_KSTREAM_8865619672769769280;, cause: {} (io.confluent.ksql.rest.server.execution.RemoteHostExecutor:135) java.util.concurrent.TimeoutException
`
This new improved logging indicated the issue was with the timeout in RemoteHostExecutor, which has it configured to 10 seconds, so we bump this up 20 seconds in this PR.
Address feedback on https://github.com/confluentinc/ksql/pull/9890
_Describe the …

chore: make fetch remote host timeout configurable for test

---

pom.xml

```
java.lang.NoSuchMethodError: 'void io.netty.handler.ssl.SniHandler.<init>(io.netty.util.AsyncMapping, long)'
at io.vertx.core.net.impl.VertxSniHandler.<init>(VertxSniHandler.java:33)
at io.vertx.core.net.impl.SSLHelper.createSniHandler(SSLHelper.java:347)
at io.vertx.core.net.impl.SSLHelper.createHandler(SSLHelper.java:352)
at io.vertx.core.http.impl.HttpServerWorker.configurePipeline(HttpServerWorker.java:139)
at io.vertx.core.http.impl.HttpServerWorker.handle(HttpServerWorker.java:132)
at io.vertx.core.http.impl.HttpServerWorker.handle(HttpServerWorker.java:55)
at io.vertx.core.net.impl.ServerChannelLoadBalancer.initChannel(ServerChannelLoadBalancer.java:61)
at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
at …
```

Upgrade netty to 4.1.87.Final

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/MD5.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/MD5Test.java
ksqldb-functional-tests/src/test/resources/historical_plans/md5_-_md5_to_hex_string/7.4.0_1681850900031/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/md5_-_md5_to_hex_string/7.4.0_1681850900031/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/md5_-_md5_to_hex_string/7.4.0_1681850900031/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/md5.json

Adds a new `MD5` UDF that takes a string as input and outputs the hex-encoded MD5 hash of the string.

feat: add MD5 hash UDF

---

docs/requirements.txt

Upgrade `pymdown-extensions` version to resolve vulnerability ([KSE-1698](https://confluentinc.atlassian.net/browse/KSE-1698)). 
Verified `mkdocs serve` works with the new version
[KSE-1698]: https://confluentinc.atlassian.net/browse/KSE-1698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: upgrade pymdown-extensions and Pygments version

---

docs/developer-guide/ksqldb-clients/java-client.md

Since Maven 3.8.1, non-ssl maven repositories are blocked. We need to use https here.
manually executed the steps

Use https for repository

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/9896.

docs: cherry-pick: fix link to 0.28.2 blog post (DOCS-23732)

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/UserFunctionLoader.java

We scanned the whole classpath for UDF functions, while we should only scan the UDF directory and the ksql-engine jar.
This is a regression introduced in Scalable push queries end to end #7661.

fix: do not scan the whole classpath

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/average-udaf.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/collect-list.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/correlation-udaf.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/elements.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/sum.json

Some QTTs are failing now that [KIP-904](https://cwiki.apache.org/confluence/display/KAFKA/KIP-904%3A+Kafka+Streams+-+Guarantee+subtractor+is+called+before+adder+if+key+has+not+changed) has been merged because KIP-904 results in table aggregates for the same key being processed as a single update, rather than two (removal followed by addition). This PR updates the failing tests to reflect the new behavior.
This PR also contains another test update for KAFKA-7499 ([PR](https://github.com/apache/kafka/pull/13477)). The test in `elements.json` checked for a specific error message, but that error is now nested inside another one as a result of the linked PR. This PR updates the expected message to be the new outer message instead; we could also remove the test entirely if that's preferable …

test: update QTT for KIP-904 and KAFKA-7499

---

CHANGELOG.md
docs/operate-and-deploy/changelog.md

^ in preparation for the upcoming 0.29 release.

docs: add changelog for 0.29

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonSchemaDeserializerTest.java
pom.xml

Some unit tests are failing in the build after https://github.com/confluentinc/schema-registry/pull/2674 was merged, due to improper usage of mock SR clients on the ksql side. We should be using the provided `MockSchemaRegistryClient` implementation rather than `Mockito.mock(SchemaRegistryClient.class)` since the methods which need to be mocked when using the latter are implementation details of SR which are subject to change.
The specific failure in this case is that a new internal method added to the `SchemaRegistryClient` usage is resulting in an NPE in our unit tests because the unit tests do not provide mocked implementations for this new method. Here's an example failure from `KsqlJsonSchemaDeserializerTest.shouldDeserializeJsonObjectCorrectly`:
```
Error serializing message to …
```

chore: fix tests for updated Schema Registry client internals

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/9992.

docs: cherry-pick: add CP and CCloud defaults for server configs (DOCS-24457)

---

ksqldb-serde/src/test/java/io/confluent/ksql/serde/unwrapped/UnwrappedDeserializerTest.java

This commit fixes "reference to deserialize is ambiguous" compilation error in UnwrappedDeserializerTest.

fix: cast UnwrappedDeserializer's bytes argument

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonSchemaDeserializerTest.java

This PR cherrypicked the commit [here](https://github.com/confluentinc/ksql/commit/1c8979460c0704320a8145f0d1db6a49b22d17c1) in order to backporting fixes to 7.4.x so that the unit tests pass.

chore: fix tests for updated Schema Registry client internals (#9982)

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/serde/json/ValueSpecJsonSchemaSerdeSupplierTest.java
pom.xml

https://github.com/confluentinc/schema-registry/pull/2674 introduced a new default method `registerWithResponse` which throws exception by default. `SandboxedSchemaRegistryClient.java` should implement it. Otherwise `io.confluent.ksql.rest.server.InsertionIntegrationTest.shouldSupportEvolvingSchemasOnInsert` and `KsqlResourceFunctionalTest.shouldInsertIntoValuesForAvroTopic` fail.
`io.confluent.ksql.rest.server.InsertionIntegrationTest.shouldSupportEvolvingSchemasOnInsert` and `KsqlResourceFunctionalTest.shouldInsertIntoValuesForAvroTopic` pass after the fix.

fix: implement default method for schema registry client

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java

Remove duplicate definition of `registerWithResponse`
Existing unit test

fix: remove duplicate definition

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Encode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-functional-tests/pom.xml
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
ksqldb-udf/pom.xml
pom.xml

The guava version used in ksql is affected by CVE-2023-2976.
This PR upgrades the guava dependency to 32.0.1.
Resolves https://confluentinc.atlassian.net/browse/KSE-1714
Builds must pass.

chore: upgrade guava to 32.0.1

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/QueryTranslationTest.java

Changes to the sandbox SR client introduced  in https://github.com/confluentinc/ksql/pull/10006 caused a large number of historical QTTs to start failing. I'm disabling historical QTTs to unblock the release, we need to revert this PR and fix the test soon.

test:disable historical QTTs to unblock release

---

Jenkinsfile
ksqldb-common/pom.xml
ksqldb-examples/pom.xml
ksqldb-rest-app/pom.xml
ksqldb-serde/pom.xml
pom.xml

This reverts commit https://github.com/confluentinc/ksql/commit/577029425c4ae4288fa527488acf1ef4820aade2
CP release tooling doesn't know how to deal with pinned dependencies, reverting these changes for 7.5.x so that we can get a clean RC cut for upcoming CP 7.5 release
Only intended for 7.5.x for now, will pint merge -strategy ours to resolve the conflict
(Note: This is similar to https://github.com/confluentinc/ksql/pull/9815 PR for 7.4.x)

Revert "chore: switch to pinned nanoversion strategy (#9193)"

---

ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Encode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluator.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigRoutingOptions.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
pom.xml

chore: upgrade guava to 32.0.1 on master

---

ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Encode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluator.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigRoutingOptions.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
pom.xml

chore: upgrade guava to 32.0.1 on 7.4.x

---

ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Encode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluator.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigRoutingOptions.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
pom.xml

chore: upgrade guava to 32.0.1 on 7.2.x

---

ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Encode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluator.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigRoutingOptions.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryConsistencyFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
pom.xml

chore: upgrade guava to 32.0.1 on 7.1.x

---

ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Encode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluator.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigRoutingOptions.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
pom.xml

chore: upgrade guava to 32.0.1 on 7.0.x

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/JsonQueryStreamResponseWriter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/JsonStreamedRowResponseWriter.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/server/JsonStreamedRowResponseWriterTest.java

With 50k buffers for pull queries, writing to the http response could overwhelm the output buffer and seemingly corrupt the output.  Normally, this is managed by checking  `response.writeQueueFull()`, which it is in `QuerySubscriber`, and waiting until the write queue is no longer full.  This works when small amounts of data is written at a time, but not when the last row triggers a massive buffer to be written.  For that reason, I have made the buffer much smaller.  It should still have a nice performance benefit, and hopefully avoid triggering the corruption.
It's still a bit unclear to me why the output is corrupted -- it's possible that since Vertx is non-blocking framework, if the write buffer is near full, its only option is to top it off and discard the rest since you don't want to …

fix: Fixes corruption in the output of pull queries with large responses

---

pom.xml

```
java.lang.NoSuchMethodError: 'void io.netty.handler.ssl.SniHandler.<init>(io.netty.util.AsyncMapping, long)'
at io.vertx.core.net.impl.VertxSniHandler.<init>(VertxSniHandler.java:33)
at io.vertx.core.net.impl.SSLHelper.createSniHandler(SSLHelper.java:347)
at io.vertx.core.net.impl.SSLHelper.createHandler(SSLHelper.java:352)
at io.vertx.core.http.impl.HttpServerWorker.configurePipeline(HttpServerWorker.java:139)
at io.vertx.core.http.impl.HttpServerWorker.handle(HttpServerWorker.java:132)
at io.vertx.core.http.impl.HttpServerWorker.handle(HttpServerWorker.java:55)
at io.vertx.core.net.impl.ServerChannelLoadBalancer.initChannel(ServerChannelLoadBalancer.java:61)
at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
at …
```

fix: Upgrade netty to 4.1.89.Final

---

ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Encode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluator.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigRoutingOptions.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
pom.xml

chore: upgrade guava to 32.0.1 on 7.3.x

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/QueryTranslationTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/average-udaf.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/collect-list.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/correlation-udaf.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/elements.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/group-by.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/sum.json

There are [285 test failures](https://jenkins.confluent.io/job/confluentinc/job/ksql/job/7.5.x/134/testReport/) for branch 7.5.x. 
This PR solves these failures by 3 steps:
- Changes to the sandbox SR client introduced in https://github.com/confluentinc/ksql/pull/10006 caused a large number of historical QTTs to start failing. Those tests has been disabled in master branch. I'm disabling them in 7.5.x as well to unblock https://github.com/confluentinc/ksql/pull/10028. We need to revert this PR and fix the test later. 
- Some QTTs are failing now that [KIP-904](https://cwiki.apache.org/confluence/display/KAFKA/KIP-904%3A+Kafka+Streams+-+Guarantee+subtractor+is+called+before+adder+if+key+has+not+changed) has been merged because KIP-904 results in table aggregates for the same key being …

[KSE-1714] test: update QTT for KSE-1714

---

ksqldb-engine-common/src/test/java/io/confluent/ksql/schema/ksql/DefaultSqlValueCoercerTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Encode.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/json/JsonPathTokenizerTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/helpers/CastEvaluator.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MaximumLagFilter.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigPlannerOptions.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryConfigRoutingOptions.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/LagReportingAgentTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SchemaInfo.java
pom.xml

chore: upgrade guava to 32.0.1 on 7.5.x

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

fix: checkstyle violations in KsqlConfig

---

.readthedocs.yml

Required by ReadThe Docs: [Use build.os instead of build.image on your configuration file](https://blog.readthedocs.com/use-build-os-config/).

docs: Update docs build to use build.os config key (DOCS-25078)

---

ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedKafkaTopicClientTest.java
pom.xml

chore: version bump failed in jenkins so manually moving it up

---

ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java

Hoping that updating how the exception is checked will get it to stop failing on Jenkins when it passes just fine locally

tests: change_expection_check

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java
pom.xml

The SR client added a new method with broke our sandboxing tests. The auto version bump failed so manually doing it now 

fix: SR client dep manual bump and test fix

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryBuilderTest.java

to prevent the transient queries from creating standby replicas when they shouldn't I force the number to be set to zero before the stream is made

fix: force the number of standby to always be zero for transient queries

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/PullQueryWriteStream.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/PullQueryWriteStreamTest.java

Fix for a race inside vert.x’s `RecordParser`. Two threads are hitting `RecordParserImpl.handleParsing`, one is entering from upstream via `RecordParser.handle`, and one thread is coming from the downstream via `ReadStream.resume`. Once our `PullQueryWriteStream` is half empty, we call the drain handler, which calls `RecordParser.resume`, which synchronously starts parsing new records from the buffer. `RecordParser.handleParsing` is not thread-safe.
The cause is that the monitor inside `PullQueryWriteStream` is insufficient to protect from races inside the `RecordParser`. This makes two changes:
- We run the drain handler as part of the `ReadStream` context, which ensures that it is race-free with other calls into `RecordParser` since it's executed as part of the same netty event loop.
- …

fix: concurrency bug when doing high volume pull query over java client (alternative)

---

pom.xml

This PR upgrades netty to `4.1.00.Final` and `netty-tcnative-version` to `2.0.61.Final` to address https://nvd.nist.gov/vuln/detail/CVE-2023-44487.
`4.1.100.Final` address the vulnerability according to https://netty.io/news/2023/10/10/4-1-100-Final.html.

chore: Upgrade netty to 4.1.100.Final for CVE-2023-44487

---

pom.xml

Jetty / vertx was pulling in older versions of netty, which is exposed to CVE-2023-44487.
Upgrading vertx to `4.4.6`, and jetty to `9.4.53.v20231009`, which according to the following addresses the CVE:
1. https://github.com/jetty/jetty.project/releases/tag/jetty-9.4.53.v20231009
2. https://vertx.io/blog/eclipse-vert-x-4-4-6/
Did a `mvn dependency:tree | grep netty`, which shows that now all pulled in netty deps are on the target version `4.1.100.Final`.

chore: Upgrade jetty / vertx to address CVE-2023-44487

---

Jenkinsfile

We need to get a new image asap. So disable test for now. Will enable it after I got a new image

temporarily disable test to get a new image asap

---

pom.xml

Backports of #10080 and #10081 to CP 7.5.x to address CVE-2023-44487.

chore: Upgrade netty to 4.1.100.Final to address CVE-2023-44487

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
pom.xml

Fix changed signature of `TaskAssignor` in https://github.com/apache/kafka/blob/trunk/streams/src/main/java/org/apache/kafka/streams/processor/internals/assignment/TaskAssignor.java#L33
Builds

fix: [KSQL-11345] fix changed TaskAssignor

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/SlidingWindowRateLimiter.java

Fix logging for pull query bandwidth limit which reports results in MB instead of B
```
Hit bandwidth rate limit of 199229440MB with use of 279042475MB
```

[KSQL-11372] Log pull query bandwidth rate in bytes

---

ksqldb-common/src/main/java/io/confluent/ksql/errors/LogMetricAndContinueExceptionHandler.java
ksqldb-common/src/test/java/io/confluent/ksql/errors/LogMetricAndContinueExceptionHandlerTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java

KSQL currently treats an exception due to missing permission on schema registry during deserialization as any other deserialization exception, and the default action for deserialization exception is log and continue.
The permission issue should stop KSQL from processing.
With this change:
- We scan the exception in the `LogMetricAndContinueExceptionHandler` for a `RestClientException` (can have multiple levels of wrapping) to get the error code and check if we have to deal with an authorization error.
- Return `FAIL` from the `deserializationExceptionHandler` for such exceptions.
- The exception will fall through to `StreamsUncaughtExceptionHandler`. There, we make sure that the exception is classified as a `USER` error so that on-call is not alerted. The uncaught exception handler will …

fix: do not continue processing records on permission errors in schema registry

---

ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/BufferCopyStream.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java

On chunked HTTP responses inside pull query handling logic for multi-node KSQL clusters, KSQL runs into a regression in upstream library Vert.x. Its record parser attempts to reuse the buffer from the HTTP response when aggregating chunks, however, when SSL is enabled, the buffers produced by the netty backend cannot be reused. This results in exceptions of the form
```java.lang.IndexOutOfBoundsException: writerIndex(1) + minWritableBytes(1) exceeds maxCapacity(1): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf(ridx: 0, widx: 1, cap: 1/1)```
Similar instances have been described here:
- https://github.com/eclipse-vertx/vert.x/issues/3546 in vert.x 3.9.2 (fixed)
- https://github.com/eclipse-vertx/vert.x/issues/4811 in vert.x 4.4.4 (not fixed)
To work around the bug, we …

fix: vert.x regression bug when doing high volume pull query

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

Make sure to not enable the new state updater thread of Kafka Streams in KSQL, since further testing is required to tests its compatibility with KSQL.
Tested by the usual unit tests. No actual change in the current behavior, because state updater is still disabled by default in ce-kafka.

chore: disable state updater in KSQL

---

ksqldb-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroSerializerTest.java

- Build of branch 7.5.x fails: https://jenkins.confluent.io/job/confluentinc/job/ksql/job/7.5.x/459/console
- The local test shows that this is due to a format issue of avro schema:
```
Caused by: org.apache.avro.SchemaParseException: dangling content after end of schema: }
at org.apache.avro.Schema$Parser.parse(Schema.java:1484)
at org.apache.avro.Schema$Parser.parse(Schema.java:1458)
at io.confluent.ksql.serde.avro.KsqlAvroSerializerTest.parseAvroSchema(KsqlAvroSerializerTest.java:1534)
at io.confluent.ksql.serde.avro.KsqlAvroSerializerTest.<clinit>(KsqlAvroSerializerTest.java:225)
```
- This PR fixes this format issue and pass the test.

[hotfix] fix the 7.5.x avro schemas format issue

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/ApiTest.java

This test was failing on https://jenkins.confluent.io/job/confluentinc/job/ksql/job/6.2.x/2522/ (opened the PR against `6.0.x` that seems to have the same issue).
It's a classic race condition.
Note that the failing `TlsTest` is a sub-class of `ApiTest` is thus is fixed by this PR, too.

MINOR: fix flaky test

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslClientAuthFunctionalTest.java

Disable SslClientAuthFunctionalTest to unblock build 7.5.x
Discussion link: https://confluent.slack.com/archives/C9Z794XSL/p1699981849954699

Disable SslClientAuthFunctionalTest to unblock build 7.5.x

---

pom.xml

When trying to run Data Contract rules in ksql, ksql-server fails to start with the following exception.  This PR attempts to upgrade Antlr to 4.13.1 (the same version used by Schema Registry in master)
```
ANTLR Tool version 4.9.2 used for code generation does not match the current runtime version 4.11.1
ANTLR Runtime version 4.9.2 used for parser compilation does not match the current runtime version 4.11.1
Exception in thread "main" java.lang.ExceptionInInitializerError
at io.confluent.ksql.util.ParserKeywordValidatorUtil.createFromVocabulary(ParserKeywordValidatorUtil.java:82)
at io.confluent.ksql.util.ParserKeywordValidatorUtil.<clinit>(ParserKeywordValidatorUtil.java:53)
at io.confluent.ksql.function.InternalFunctionRegistry.<init>(InternalFunctionRegistry.java:34)
at …
```

Upgrade Antlr to 4.13.1

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java

Not sure why, but `io.confluent.ksql.rest.util.PersistentQueryCleanupImplTest.shouldDeleteExtraStateStores` started to fail recently (cf https://jenkins.confluent.io/job/confluentinc/job/ksql/job/7.0.x/2171/testReport/junit/io.confluent.ksql.rest.util/PersistentQueryCleanupImplTest/shouldDeleteExtraStateStores/):
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at io.confluent.ksql.rest.util.PersistentQueryCleanupImplTest.shouldDeleteExtraStateStores(PersistentQueryCleanupImplTest.java:86)
```
Capturing the log output did not work any longer. Updating how we create the logger in `QueryCleanupService` fixes the issue

chore: fix broken test

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslClientAuthFunctionalTest.java

Cherry-pick of https://github.com/confluentinc/ksql/pull/10156 to 7.3.x

fix: Makes SslClientAuthFunctionalTest work with both java 8 and 11

---

findbugs/findbugs-exclude.xml

`Master` is broken currently due to `SourceBuilderTest` hitting a false positive spot bug https://github.com/spotbugs/spotbugs/issues/872 upon bumping these:
```
<groupId>io.confluent</groupId>
<artifactId>common</artifactId>
-        <version>7.7.0-154</version>
+        <version>7.7.0-204</version>
-        <io.confluent.schema-registry.version>7.7.0-53</io.confluent.schema-registry.version>
+        <io.confluent.schema-registry.version>7.7.0-80</io.confluent.schema-registry.version>
```
Repro: 
- On `master` run 
```
./mvnw clean install
-Dmaven.multiModuleProjectDirectory=<PATH_TO_KSQL>
-U
-T 100
-Dmaven.gitcommitid.nativegit=true
-DskipTests -DskipIntegrationTests
-Dmaven.wagon.http.retryHandler.count=10
-Pjenkins
-Djava.io.tmpdir=/Volumes/RAMDisk
--batch-mode
--update-snapshots
``` …

chore: suppress RV_RETURN_VALUE_IGNORED_NO_SIDE_EFFECT in SourceBuilderTest

---

ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlTargetTest.java

https://github.com/confluentinc/ksql/blob/master/ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java#L505 won't be true if status code isn't 200. As a result, the error message is parsed and json exception is thrown. See https://confluentinc.atlassian.net/browse/KSE-1778. 
This can reproduced by starting two local ksql nodes with configs:
```
listeners=http://0.0.0.0:8088
ksql.streams.state.dir=/tmp/1
ksql.streams.num.standby.replicas=1
ksql.heartbeat.enable=true
ksql.lag.reporting.enable=true
ksql.query.pull.enable.standby.reads=true
ksql.advertised.listener=http://localhost:8088
```
and 
```
listeners=http://0.0.0.0:8089
ksql.streams.state.dir=/tmp/2
ksql.streams.num.standby.replicas=1
ksql.heartbeat.enable=true
ksql.lag.reporting.enable=true …
```

fix: check status code and do not parse pull query error message

---

Jenkinsfile

This PR removes the `confluent-cloud-plugins` and `confluent-security-plugins` repos as downstream repos in `Jenkinsfile`.  This change allows the `confluent-cloud-plugins` and `confluent-security-plugins` repos to finish Jenkins deprecation without causing this repo (ksql) downstream build to fail because Jenkins would not be present in `confluent-cloud-plugins` and `confluent-security-plugins`. `confluent-cloud-plugins` and `confluent-security-plugins` can be added again as downstream repos in `service.yml` when the semaphore migration occurs (the Semaphore migration PR already has `confluent-cloud-plugins` and `confluent-security-plugins` listed as downstream repos in `service.yml`). I made the removal of the downstream repos as a commenting out (instead of just removing the line) for …

Remove downstream repos in Jenkinsfile

---

pom.xml

Uses a nanoversion range instead of a pinned nanoversion for common. The used pinned version was set by release tooling is most likely wrong and let builds fail. This is a quick fix to unblock other work.

chore: change pinned version to version range for common

---

Jenkinsfile
pom.xml

This PR enables pinned nanoversions and sets the version of dependency common to a specific version.

chore: enable pinned nanoversions

---

docs/overrides/partials/copyright.html

Add script for year: `<script>document.write(new Date().getFullYear());</script>`.

docs: update hardcoded copyright year in footer with script (DOCS-26825)

---

ksqldb-rest-app/pom.xml
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutorFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFactoryTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java

We missed to call method configure on the KsqlBoundedMemoryConfigSetter when ksql is started with --queries-file. That resulted in
java.lang.IllegalStateException: Cannot use KsqlBoundedMemoryRocksDBConfigSetter before it's been configured.
https://github.com/confluentinc/ksql/issues/10121
This is a cherry-pick of https://github.com/confluentinc/ksql/pull/10174
Added functional and unit test

fix: configure KsqlBoundedMemoryConfigSetter in StandaloneExecutor mode

---

pom.xml

Pin the nanoversion for common dependency for 7.4.x branch. This was done for branches like 7.1.x here: https://github.com/confluentinc/ksql/pull/10181 and 7.2.x here: https://github.com/confluentinc/ksql/pull/10182 but was skipped on 7.4.x here: https://github.com/confluentinc/ksql/pull/10184. This step was skipped likely due to a build failure in `common` repo on 7.4.x resulting in no artifacts being created yet on 7.4.x and as a result no nanoversion to pin.
Build passing should prove this fix works

Add pinned nano version for common for 7.4.x

---

pom.xml

Pin the nanoversion for common dependency for 7.3.x branch. This was done for branches like 7.1.x here: https://github.com/confluentinc/ksql/pull/10181 and 7.2.x here: https://github.com/confluentinc/ksql/pull/10182 but was skipped on 7.3.x here: https://github.com/confluentinc/ksql/pull/10183. This step was skipped likely due to a build failure in `common` repo on 7.3.x resulting in no artifacts being created yet on 7.3.x and as a result no nanoversion to pin.
Build passing should prove this fix works

Add pinned nano version for common on 7.3.x

---

Jenkinsfile

Bumping timeout to 6 hours from the current limit of 5 hours due to builds hitting timeout. Last 2 builds on 7.3.x timed out, the last green build took 4.5 hours on Jan 3rd and the previous build directly before the green build on Jan 3rd timed out. 
Noticed the branches before 7.3.x have timeout of 4 hours while branches starting on 7.3.x and after have timeout of 5 hours so just bumping the branches 7.3.x to master (will pint merge) from 5 hours to 6 hours.
N/A

Set timeout to 6 hours on branches starting on 7.3.x

---

.semaphore/project.yml
.semaphore/semaphore.yml
Jenkinsfile
ksqldb-engine/src/main/java/io/confluent/ksql/function/UserFunctionLoader.java
ksqldb-engine/src/test/java/io/confluent/ksql/KsqlConfigTestUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
pom.xml
service.yml

Summary of changes:
1. Migrate the build job from jenkins to semaphore.
2. Fixed the thread leak in the setup() of KsqlEngine instances in KsqlEngineTest.
3. Cherry-picked the change for UserFunctionLoader to scan for select modules.
4. Use different state dirs for each test invocation and corresponding test fixes.
5. Specify rerun of failing flaky tests to atmost thrice.
6. Specify a fixed timeout for KsqlEngineTests to avoid build timeouts.

KSE-1786 | Migration: Jenkins -> Semaphore (7.4.x)

---

.semaphore/project.yml
.semaphore/semaphore.yml
Jenkinsfile
ksqldb-engine/src/main/java/io/confluent/ksql/function/UserFunctionLoader.java
ksqldb-engine/src/test/java/io/confluent/ksql/KsqlConfigTestUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
pom.xml
service.yml

Summary of changes:
1. Migrate the build job from jenkins to semaphore.
2. Fixed the thread leak in the setup() of KsqlEngine instances in KsqlEngineTest.
3. Cherry-picked the change for UserFunctionLoader to scan for select modules.
4. Use different state dirs for each test invocation and corresponding test fixes.
5. Specify rerun of failing flaky tests to atmost thrice.
6. Specify a fixed timeout for KsqlEngineTests to avoid build timeouts.

KSE-1786 | Migration: Jenkins -> Semaphore (7.5.x)

---

ksqldb-api-reactive-streams-tck/pom.xml

To fix  `CVE-2022-4065`, updating the version of  `org.testng:testng` to 7.5.1
Refer: https://confluentinc.atlassian.net/browse/KSE-1627
Checked using `mvn dependency:tree`, 7.5.1  version was observed for the same

KSE-1627: Update org.testng:testng to 7.5.1

---

ksqldb-engine/src/test/resources/udf-example-2/pom.xml
ksqldb-engine/src/test/resources/udf-example-2/src/main/java/io/confluent/example2/ksql/udf/BackwardConcat.java

Group ID: "org.example2.ksql.udf" has domain available for registration: "[example2.org](http://example2.org/)"  which makes it vulnerable to supply chain attacks in Maven where an attacker could potentially purchase domains of abandoned projects and claim their group ids
Fix: Changing the groupID to `io.confluent.example2.ksql.udf`
Also, the usage is in the `test` folder, so changing the groupID appears to be a safe approach.
I searched for the usages of the existing groupID in the github, and these were the only 2 occurrences. 

KSQL-11784: Change groupID to a more secure name

---

.semaphore/semaphore.yml
ksqldb-rest-app/pom.xml

Kotlin standard library is being pulled in as transitive test dependency. This overrides the version already set in commons. Exclude this dependency to pick the correct version.

Exclude transitive test dependency for kotlin-stdlib. Fixed maven caching in semaphore jobs.

---

ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
pom.xml

This is to resolve CVE-2024-26308 and CVE-2024-25710
Security patch
Existing tests

KSE-1816: Update commons-compress

---

.semaphore/semaphore.yml
ksqldb-rest-app/pom.xml
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java

Exclude kotlin std lib test dependency, fix maven caching in semaphore jobs.

Exclude kotlin std lib test dependency, fix maven caching in semaphore jobs.

---

ksqldb-serde/src/main/java/io/confluent/ksql/serde/protobuf/ProtobufNoSRConverter.java
ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufNoSRConverterTest.java

This PR adds a no-arg constructor for a Converter implementation.
Even though the Converter is used only in ksqldb and instantiated explicitly with a Schema argument, this class might be in the plugin path for the Connect framework. To avoid failures while loading the Converter we add a no-arg constructor - though it is not intended to be used with that pattern.

KSE-1824 | Add a no-arg constructor for ProtobufNoSRConverter.

---

docs/reference/server-configuration.md

Fixes https://github.com/confluentinc/ksql/issues/10284 by adding sections for `ksql.connect.basic.auth.credentials.file` and `ksql.connect.basic.auth.credentials.source` configs.

docs: document settings for authenticated Kafka Connect (DOCS-28313)

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/10289.

docs: cherry-pick: document settings for authenticated Kafka Connect (DOCS-28323)

---

ksqldb-common/src/main/java/io/confluent/ksql/query/QueryError.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/QueryStateMetricsReportingListener.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/QueryStateMetricsReportingListenerTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunnerMetrics.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerMetricsTest.java

Initially raised this change request against `master`: https://github.com/confluentinc/ksql/pull/10288
But RC will cut from `7.7.x`, hence raising against it.
In process of migrating ksql metrics to otel, we found a few string valued metrics
```
ksql.server.command_runner.status
ksql.server.command_runner.degraded.reason
ksql.query.status
ksql.query.lifecycle.status
ksql.query.error.status
```
These metrics are currently getting dropped because TelemetryReporter [skips](https://github.com/confluentinc/ce-kafka/blob/e707e9b1db4aee6ef76c525e7b2155e2f9946aa7/ce-metrics/src/main/java/io/confluent/telemetry/collector/KafkaMetricsCollector.java#L102-L106) the String Valued metrics and JMX Metrics Insights [skips](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/1b7d32586 …

KSQL-12064: Add Num valued metrics corresponding to String valued metrics

---

ksqldb-api-client/pom.xml

**Issue**: KsqlDB build failing.
**RCA**: The version of the dependency `bouncycastle.jdk18` was changed recently
- https://github.com/confluentinc/common/pull/599/files
- https://github.com/confluentinc/common/pull/601/files
The new jars included classes build using JAVA 21. But the `maven-shade-plugin` version we used did not support the support the java 21 class files.
**Fix**: Upgraded the plugin to a version which supports java 21 as well.
Build passing

KSQL-12154: Update plugin version

---

pom.xml

KSE-1832 | CVE fix for vertx dependency.

KSE-1832 | CVE fix for vertx dependency.

---

ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java

Fix compilation errors due to visibility change in Kafka properties.

KSQL-12175 | Fix compilation errors due to visibility change in Kafka properties.

---

ksqldb-stream-lib/pom.xml

**Background:** We did a pint merge of the PR: https://github.com/confluentinc/ksql/pull/10305 from `7.7.x` to master.
**Bug:** The version in the pom.xml which was 7.7.0 also got propagated, which is causing build failure.
**Fix:** Changing the version to 7.8.0
Ran the build locally

KSQL-11272: Fix build failure

---

ksqldb-api-client/pom.xml
ksqldb-cli/pom.xml
ksqldb-rest-app/pom.xml
ksqldb-tools/pom.xml
pom.xml

Background: Currently, all the ITs of ksqldb are getting skipped due to some failures(as per historical context - the failures are not due to functionality issues) cc @pbadani 
Instead of skipping all the ITs, this change will skip only the failing ITs.
Then we can pick up to fix them one by one.

KSQL-12164: Remove disable ITs flag

---

ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

We make of kafka configs property in Ksql code base.
The property name was dependent on ce-kafka.
Recently the code in ce-kafka got refactored and the config name was moved.
Old code: https://github.com/confluentinc/ce-kafka/commit/a402dfb01e7ab5499d502fb83fc10cb4d806dae3#diff-cbe6a8b71b05ed22cf09d97591225b588e9fca6caaf95d3b34a43262cfd23aa6L172
New Code: https://github.com/confluentinc/ce-kafka/commit/a402dfb01e7ab5499d502fb83fc10cb4d806dae3#diff-8eb3e01716508551f203b0b37c2d5f951e93cce7ffed7c00c2b33633d7c8ed23R45
We could 2 approaches now:
1. Add the name of the propoerty in ksql codebase explicitly.
2. Or include the ce-server dependency in ksql codebase and use the new path for the config name
I am going ahead with approach 1.
_Describe the testing strategy. Unit and integration tests …

KSQL-12187: Add property name in the ksql codebase

---

ksqldb-common/pom.xml
ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/SchemaConverters.java
ksqldb-common/src/test/java/io/confluent/ksql/schema/ksql/SchemaConvertersTest.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectDataTranslator.java
ksqldb-udf/pom.xml
ksqldb-udf/src/main/java/io/confluent/ksql/schema/ksql/types/SqlStruct.java
ksqldb-udf/src/test/java/io/confluent/ksql/schema/ksql/types/SqlStructTest.java

Union/AnyOf types in Schema Registry are encoded in Connect as a Struct with a special schema name: **io.confluent.connect.json.OneOf** and one field for each of the alternative types.
{"anyOf":[{"type":"string"},{"type":"integer"},{"type":"boolean"}]
The fields for each alternative types are named as following for the given example:
**io.confluent.connect.json.OneOf.field.0** - String type
**io.confluent.connect.json.OneOf.field.1** - Integer type
**io.confluent.connect.json.OneOf.field.2** - boolean type
During Ser/De in the JsonSchemaConverter the first field with a non-null value is picked as the value of the current Union/AnyOf type. (see Class JsonSchemaData in Schema Registry).
KsqlDB schema in the Command object does not maintain this special information for the Structs (nor does …

KSE-1795 | Add support for AnyOf Json type while encoding Ksql schemas.

---

ksqldb-engine/pom.xml
pom.xml

Revert classgraph version to older one

[KSQL-12378] Downgrade classgraph to 4.8.59

---

ksqldb-engine/pom.xml
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/PullBandwidthThrottleIntegrationTest.java
pom.xml

Bump up the classgraph to latest version

[KSQL-12378] Downgrade classgraph to 4.8.59 and fix 7.1.x tests

---

ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java

Make the appropriate changes in ksql repo.
Kafka changes for ref: https://github.com/apache/kafka/commit/133f2b0f311ba1fd5a999f477bad38370c1772ca

KSQL-12387 | SystemTime is refactored to a singleton class. Fix the ref in the class KafkaEmbedded.

---

ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java

The response object is nullable and accessing the connection status to check if it was SSL results in an NPE.
This PR adds a null check for the object.

KSQL-12384 | Add a null check in the response object to avoid NPE while accessing the connection status.

---

ksqldb-api-client/pom.xml
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java
ksqldb-rest-app/pom.xml
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/PullBandwidthThrottleIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
ksqldb-tools/pom.xml
pom.xml

Mock Connectors used in the IT tests were moved to a different connect module. This PR adds a test dependency for those modules.

KSQL-12239 | Fix the dependency for test artifacts. Implement the new method registerWithResponse in SchemaRegistryClient.

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslClientAuthFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/CorsTest.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientTest.java
pom.xml

Follow-up of https://github.com/confluentinc/ksql/pull/10402
The version used in the above mentioned PR still have the CVE. Upgrading it to 4.4.8(version used in 7.3 and above as well). This version caused some test failures. These test failed in the higher branches as well which were then fixed. I have cherry-picked those commits
- https://github.com/confluentinc/ksql/pull/10159
- https://github.com/confluentinc/ksql/pull/9770

Update vertx version (#52)

---

ksqldb-serde/src/test/java/io/confluent/ksql/serde/protobuf/ProtobufSchemaTranslatorTest.java

One test shouldApplyNullableAsOptional in ProtobufSchemaTranslatorTest.java has started failing on `7.8.x` and `master`.
```
java.lang.AssertionError Expected: is "syntax = \"proto3\";\n\nmessage ConnectDefault1 {\n optional int32 optional_int32 = 1 [deprecated = false];\n optional bool optional_boolean = 2 [deprecated = false];\n optional string optional_string = 3 [deprecated = false];\n}\n" but: was "syntax = \"proto3\";\n\nmessage ConnectDefault1 {\n optional int32 optional_int32 = 1;\n optional bool optional_boolean = 2;\n optional string optional_string = 3;\n}\n"
java.lang.AssertionError: 
Expected: is "syntax = \"proto3\";\n\nmessage ConnectDefault1 {\n  optional int32 optional_int32 = 1 [deprecated = false];\n  optional bool optional_boolean = 2 [deprecated = false];\n  optional …
```

KSQL-12484: Update protobuf schema assertion (#80)

---

.semaphore/semaphore.yml

This PR updates cp jar build task invocation for PR builds to make sure downstream components don't break with the PR changes.
cp jar build task is invoked as part of SemaphoreCI pipeline running as part of this PR.

CPBR-1736: updating cp-jar-build block in semaphore pipeline

---

.semaphore/semaphore.yml

This PR fixes pint merge issues occurring when merging 7.7.x branch in 7.8.x. 
Not required as the semaphore block added for cp-jar-build here is already tested in 7.0.x. Because of recent ksql changes, that block will be failing. New PR will be raised for that after this PR is merged.

7.8.x pint merge conflict resolution

---

bin/ksql
bin/ksql-datagen
bin/ksql-restore-command-topic
bin/ksql-server-start
bin/ksql-test-runner
bin/run-ksql-test

When installing with cp-ansible , it could be that the path is installed into /etc/ksqldb/
When done so a user will get an error on the CLI: 
```
[root@ksql01-dev]#  ksql  https://localhost:8088 -u moshe
log4j:ERROR Could not read configuration file from URL [file://etc/ksqldb/log4j-file.properties].
java.net.UnknownHostException: etc
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
at java.base/java.net.Socket.connect(Socket.java:609)
at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:1062)
at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:1024)
at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1119)
at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1105)
at …
```

fix base_dir as / causing  java.net.UnknownHostException: etc

---

ksqldb-version-metrics-client/src/test/java/io/confluent/support/metrics/utils/WebClientTest.java

The test is trying to access the server that is under maintainence. Ignoring the tests for now.

KSQL-12481: Ignore Public PhoneHomeServer endpoint usage tests (#79)

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryProjectNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/QueryProjectNodeTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-with-struct-star.json

Expansion of stuctField->* fails for pull-queries though works for streaming/push queries. This change is to fix the expansion. (Fixes #KSE-1846)
**Yes** (Unit Tests & Functional Tests)

Fixes#KSE-1846: Fix for select struct->* for Pull Queries

---

ksqldb-common/src/main/java/io/confluent/ksql/security/oauth/OAuthBearerCredentials.java

Fixes master build for ksql
HttpAccessTokenRetriever class which comes from kafka-clients has an extra boolean parameter which was not present in the kafka-clients version used for 7.8.x.
This comes from apache kafka.
Similar fix has been done for schema-registry as well.
SR - master : https://github.com/confluentinc/schema-registry/blob/7ad27f480bc904fd35f4f7ee598668afe1a26bc6/client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/OauthCredentialProvider.java#L110-L112
SR - 7.8.x : https://github.com/confluentinc/schema-registry/blob/6e471189d67ad45410d6068d52291a32a5927006/client/src/main/java/io/confluent/kafka/schemaregistry/client/security/bearerauth/oauth/OauthCredentialProvider.java#L110-L112

Fix master build for ksql

---

pom.xml

Upgrade git commit id plugin version from 2.2.6 to 4.9.10 and include git.commit.id property.

Upgrade git commit id plugin version from 2.2.6 to 4.9.10 and include git.commit.id property.

---

CONTRIBUTING.md
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/ExpectedExceptionNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/exceptions/KsqlExpectedException.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/sum.json

With the implementation of [KIP-1033](https://lists.apache.org/thread/1nhhsrogmmv15o7mk9nj4kvkb5k2bx9s), KStream now wraps all errors in a StreamsException, including the original KsqlFunctionException. This change affects exception handling in test cases, where previously only the KsqlFunctionException was expected.
Changes includes
- Implementation of Expectation.Cause Matcher in Tests
- Updated Tests with New Expectations

KSQL-12544 | Update numeric overflow exception tests (#134)

---

.semaphore/semaphore.yml
ksqldb-engine/src/main/java/io/confluent/ksql/function/UserFunctionLoader.java
ksqldb-version-metrics-client/src/test/java/io/confluent/support/metrics/utils/WebClientTest.java
pom.xml

In the current implementation, although the Thread.setContextClassLoader() method is not explicitly used, there is a possibility that the context class loader could be altered elsewhere, which was affecting the integration tests. This can lead to non-deterministic behavior in the loading of user-defined functions (UDFs) and cause unpredictable test results.
To address this issue, we ensure that the correct class loader is used explicitly for UDF loading without relying on the thread's context class loader. This change prevents unintended interference and guarantees that UDFs are loaded consistently, improving the stability and reliability of the integration tests.
The fix involves using ClassGraph.overrideClassLoaders(loader) to explicitly set the class loader for classpath scanning, thus …

KSQL-12554 | Ensure Deterministic UDF Loading by Avoiding Context ClassLoader Interference

---

service.yml

This PR modifies service.yml to add cp jar build block in semaphore.yml to trigger cp jar build job on every PR build. This PR will be reverted if the changes don't work as expected.
After merging the PR, cc-service-bot (using custom branch) will be invoked on ksql to test the actual changes done in semaphore.yml to make sure cp jar build block is added in semaphore.yml correctly.

CPBR-1799: adding PR CI gating config in service.yml for cc-service-bot to enable cp jar build

---

ksqldb-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/ExpectedExceptionNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/exceptions/KsqlExpectedException.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/elements.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/sum.json

tldr; This PR fixes the ksql build by updating the usage of `TimeWindowedDeserializer`
The method used by our test has been deprecated for quite some time, it was recently removed in [this commit](https://github.com/confluentinc/ce-kafka/commit/8148361c090ef2749385004fb815f5d2caf6ab66) in ce-kafka, which broke our build. We have now used the more generic method and provided the window size as `Long.MAX_VALUE`, which is exactly what it was in the deprecated method
Ran build and tests locally

[KSQL-12662] Add default window size in WindowingIntTest

---

docs/README.md

Deprecate the content in the docs directory in favor of https://docs.confluent.io/platform/current/ksqldb.

docs: add deprecation note for documentation (DOCS-31223)

---

docs/README.md

Deprecate the content in the docs directory in favor of https://docs.confluent.io/platform/current/ksqldb.
Related: https://github.com/confluentinc/ksql/pull/10499

docs: add deprecation note for documentation (DOCS-31223) (#10498)

---

docs/overrides/main.html
docs/overrides/partials/copyright.html
docs/overrides/partials/header.html
mkdocs.yml

Adds noindex tagging to 0.10.0-ksqldb version of the documentation.

DOCS-31406 - Add no index to old versions ksqldb docs

---

.gitignore
CONTRIBUTING.md
ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java

Added a log statement to capture and log errors when describing Kafka topics in the KafkaTopicClientImpl class. This helps in debugging and monitoring topic-related issues.

feat: add error log for logging topic client errors

---

ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamAggregateBuilder.java

Fix the apis for deprecated methods in Kafka Streams.
The default 24 hour grace period in Kafka Streams was marked for deprecation in 
https://cwiki.apache.org/confluence/display/KAFKA/KIP-633%3A+Deprecate+24-hour+Default+Grace+Period+for+Windowed+Operations+in+Streams
To keep the existing ksqlDB behaviour unchanged, this default is explicitly set here.

KSQL-12705 | Fix the deprecated api methods.

---

.gitignore
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestCase.java
ksqldb-rest-app/pom.xml
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/utils/KsqlPlanSchemaGenerator.java

Fix#KSQL-12720 JsonConfig lib used in ksqldb-rest-app tests will be one.ducking instead of original one. Original has dependency on scala.
one.ducking is a fork of com.kjetland. Schema-registry is dependent on one.duckling:mbknor-jackson-jsonschema-java8
hence all the downstream projects had to use that one only. [Ref PR](https://github.com/confluentinc/schema-registry/pull/3396/files)

fix: for dependency update for jsonschema

---

pom.xml

CVE fix for netty-common. Bump up tcnative dependency as per https://github.com/netty/netty/blob/netty-4.1.115.Final/pom.xml

KSQL-12737 | CVE fix for netty-common

---

docs/developer-guide/ksqldb-clients/java-client.md
maven-settings.xml

As part of account resources migration, the s3 content of existing repo is moved to a new s3 bucket.

ksql-12727 | chore: updated maven repo urls

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/CloseQueryHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/PushQueryHolder.java

Fixes context mismatch error while closing query using close query rest api endpoint.
Tested locally

[KSQL-12793] | Vedarth Sharma | Fix close query context error

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/function/udaf/KudafAggregator.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/function/udtf/KudtfFlatMapper.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/transform/KsqlTransformer.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/transform/select/SelectValueMapper.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/transform/sqlpredicate/SqlPredicate.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/function/udaf/KudafAggregatorTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/function/udtf/KudtfFlatMapperTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/transform/select/SelectValueMapperTest.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/transform/sqlpredicate/SqlPredicateTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamAggregateBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/StreamSelectBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/TableSelectBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/TableSuppressBuilder.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationFactory.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/transform/KsTransformer.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/transform/KsValueTransformer.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StreamAggregateBuilderTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/TableAggregateBuilderTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/TableFilterBuilderTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/KsqlMaterializationFactoryTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/transform/KsTransformerTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/transform/KsValueTransformerTest.java

KSQL transformer has an unused argument `ctx` across all its implementation. Current PR removes that. It is being done to ease the changes related to migration from kstream.transform to kstream.process function.
Not doing it explicitly with this PR. Will do it with this [PR#10628](https://github.com/confluentinc/ksql/pull/10628) Master is broken and fix required is split into 2 PRs.

refactor: refactored ksqltransformer and its implementations

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java

[[KSQL-12853](https://confluentinc.atlassian.net/browse/KSQL-12853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)] Added Warn Logger for Orphan Topics (UnknownTopicOrPartitionException) & for Command Topic Size exceeding threshold
[KSQL-12853]: https://confluentinc.atlassian.net/browse/KSQL-12853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added Warn Logger for Orphan Topics (UnknownTopicOrPartitionException) & for Command Topic Size exceeding threshold

---

pom.xml

KSQL-12882 | CVE fix for netty-common dependency

KSQL-12882 | CVE fix for netty-common dependency.

---

ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlClient.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
ksqldb-rest-client/src/main/java/io/confluent/ksql/rest/client/KsqlTarget.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlTargetTest.java

Fix the placement of default port number and capture the sub path while creating a client to ksqlDB.

KSQL-12936 | Fix the placement of default port number and capture the sub path while creating a client to ksqlDB.

---

ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/TimestampToStringTest.java

In local, the timezone tests fail for format like `X`. X formats the timezone diff. If the timezone difference is 0530, X return 05 , XX return 0530. Hence, it is required that the timezone tests take care of that.

fix: timezone test fixes for local setup

---

ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/datetime/TimestampToStringTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderV1Test.java

CheckStyle fixes
- MockRecordMetadata should be static class.
- Length of line should not be longer than 100.
Additional change - reverted timestamptostring test.
- It is building locally.

refactor: fixed checkstyle and spotbugs for sourcebuilderv1test

---

ksqldb-common/src/main/java/io/confluent/ksql/util/DecimalUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java

Packaging flow is ignoring the warning suppression `ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD` and breaking. The current pr refactored the code to address that issue.

fix: fixed udf config test to avoid write static from instance ctx err

---

.semaphore/semaphore.yml
docker-compose.yml
ksqldb-examples/README.md
sonar-project.properties

Added sonar.properties

---

ksqldb-common/pom.xml
ksqldb-common/src/main/java/io/confluent/ksql/security/oauth/OAuthBearerCredentials.java
ksqldb-common/src/main/java/io/confluent/ksql/security/ssl/HostSslSocketFactory.java
ksqldb-common/src/test/java/io/confluent/ksql/security/ssl/HostSslSocketFactoryTest.java

This fixes a compatibility issue between SunJSSE' HttpsURLConnection and BCJSSE' sockets, where the host name information is not passed to BCJSSE sockets.
Implements the suggested fix https://github.com/bcgit/bc-java/blob/main/tls/src/main/java/org/bouncycastle/jsse/util/SetHostSocketFactory.java
i.e wraps and explicitly sets the hostname on bouncy castle sockets.
Locally validated that the sockets are being wrapped and the host is being set correctly on Bouncy Castle Sockets.

Bouncy Castle and SunJSSE compatibility fix.

---

pom.xml

KSQL-13061] CVE-2025-24970: io.netty:netty-handler in ksql

CVE-2025-24970: io.netty:netty-handler in ksql

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

SecurityManager is deprecated from java 21 onwards. This Config is defaulted to false.

KSQL-13064 | Set the default value for SecurityManager enablement to false as it is deprecated on java 21.

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientOAuthTest.java
pom.xml

- Jetty version comes from common.
- Right now it’s upgraded to 12.
- We need dependencies to be on jetty 12 before jetty 12 works with ksql.
- Downgrading will fix build failure
Tested locally

[KSQL-13105] | Vedarth Sharma | Downgrade jetty version to fix build

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaConsumerGroupClientImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/KafkaConsumerGroupClientTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java

Context:
Following Kafka's KIP-1043, describing a non-existent consumer group now consistently throws GroupIdNotFoundException. 
Treat this expected scenario as a group with zero consumers by returning an empty consumerGroupSummary. This logs the exception, encapsulates the exception handling, simplifying the caller's contract.
Another approach: https://github.com/confluentinc/ksql/pull/10727

Ksql 13066 - Catch original GroupIdNotfoundException

---

ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
pom.xml

Pin JDK to 17 since common will use 11 (since some clients rely on common)

Pin JDK to 17

---

config/datagen.properties

need to remove `interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor` as monitoring-interceptors are going out of support from 8.0 onwards

remove monitoring interceptor classes

---

docs/how-to-guides/create-a-user-defined-function.md
docs/how-to-guides/use-connector-management.md
docs/operate-and-deploy/installation/installing.md
docs/tutorials/etl.md
docs/tutorials/event-driven-microservice.md
docs/tutorials/materialized.md
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java
licenses/licenses.html
mkdocs.yml

Removes all the zookeeper references from the codebase

[KSQL-13335] Remove zookeeper references from the codebase

---

findbugs/findbugs-exclude.xml

Suppress spotbugs that occurred when spotbug version is changed in common: https://github.com/confluentinc/common/pull/786:
Identification:
I ran SpotBugs across each module using maven plugin, reviewed the reported spotbugs and then suppressed those spotbugs.
1. Adds blanket exclusion for CT_CONSTRUCTOR_THROW warnings for classes under the io.confluent namespace.
2. Suppresses additional errors (US_USELESS_SUPPRESSION_ON_METHOD, US_USELESS_SUPPRESSION_ON_CLASS, AT_NONATOMIC_64BIT_PRIMITIVE, AT_NONATOMIC_OPERATIONS_ON_SHARED_VARIABLE, AT_STALE_THREAD_WRITE_OF_PRIMITIVE, PA_PUBLIC_PRIMITIVE_ATTRIBUTE) for all io.confluent.* classes.
3. Excludes a specific warning (FS_BAD_DATE_FORMAT_FLAG_COMBO) for the Console class in the ksql.cli.console package.
_Describe the testing strategy. Unit and …

Suppress spotbugs due to spotbug version upgrade in common.

---

findbugs/findbugs-exclude.xml
ksqldb-common/src/main/java/io/confluent/ksql/security/oauth/CachedOAuthTokenRetriever.java
ksqldb-common/src/main/java/io/confluent/ksql/security/oauth/OAuthBearerCredentials.java
ksqldb-common/src/test/java/io/confluent/ksql/security/oauth/CachedOAuthTokenRetrieverTest.java

1. Suppress spotbugs that occurred when spotbug version is changed in common: [common#786](https://github.com/confluentinc/common/pull/786):
1. Adds blanket exclusion for CT_CONSTRUCTOR_THROW warnings for classes under the io.confluent namespace.
2. Suppresses additional warnings (US_USELESS_SUPPRESSION_ON_METHOD, US_USELESS_SUPPRESSION_ON_CLASS, AT_NONATOMIC_64BIT_PRIMITIVE, AT_NONATOMIC_OPERATIONS_ON_SHARED_VARIABLE, AT_STALE_THREAD_WRITE_OF_PRIMITIVE, PA_PUBLIC_PRIMITIVE_ATTRIBUTE) for all io.confluent.* classes.
3. Excludes a specific warning (FS_BAD_DATE_FORMAT_FLAG_COMBO) for the Console class in the ksql.cli.console package.
2. Rename few OAuth classes - Due to a recent commit in ce-kafka: https://github.com/confluentinc/ce-kafka/pull/21030 (cherry pick from AK), few OAuth layer …

suppress spotbugs.

---

findbugs/findbugs-exclude.xml

Suppress spotbugs that occurred when spotbug version is changed in common: https://github.com/confluentinc/common/pull/786.
Related PR for suppressions required in ksql repo: https://github.com/confluentinc/ksql/pull/10751
Suppressing - SS_SHOULD_BE_STATIC specifically to unblock cp-br packaging failing with errors similar to:
```
[ERROR] Medium: Unread field: io.confluent.ksql.test.util.ImmutableTesterTest$4TestSubject.f11; should this field be static? [io.confluent.ksql.test.util.ImmutableTesterTest$4TestSubject] At ImmutableTesterTest.java:[line 107] SS_SHOULD_BE_STATIC
```
https://semaphore.ci.confluent.io/jobs/a9aebfe9-cbfa-428b-a383-2358a5242586#L3056

Resolve checkstyle errors.

---

findbugs/findbugs-exclude.xml
pom.xml

This pull request includes updates to improve the configuration of FindBugs and modify its behavior regarding test classes. The most significant changes involve altering the exclusion rules for test classes in the `findbugs-exclude.xml` file and commenting out the `includeTests` configuration in the `pom.xml` file.
* [`findbugs/findbugs-exclude.xml`](diffhunk://#diff-6103f0f51c1c3e4cb11f9c5fad828b086d902e8655b8005477e9c6f8091c447bL101-L104): Updated the exclusion rule to match all test classes using the pattern `~.*Test` instead of the previous `~io.confluent.ksql.test.*`. This broadens the scope of excluded test classes.
* [`pom.xml`](diffhunk://#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L923-R923): Commented out the `includeTests` configuration in the FindBugs …

Ksql 13436 suppress test spotbugs

---

.semaphore/semaphore.yml
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java
pom.xml

_What behavior do you want to change, why, how does your patch achieve the changes?_  
* fixes the test getting skipped issue by adding junit-vintage-engine dependency to the pom.xml file
* fix the port binding issue by updating the port assignment logic by removing `getFreePort()` with `:0`, so that it gets auto assigned.
* whitelisted `executor-share-coordinator` thread as it is not a case of thread leak and its executors is present.
jiira: https://confluentinc.atlassian.net/browse/KSQL-13451

KSQL-13451 | fix master 

---

ksqldb-common/src/test/java/io/confluent/ksql/security/oauth/CachedOAuthTokenRetrieverTest.java

`CachedOAuthTokenRetrieverTest` is failing because `JwtRetriever.retrieve()` throws `JwtRetrieverException`, not `IOException`.

Fix CachedOAuthTokenRetrieverTest to throw the correct exception type for JwtRetriever.retrieve()

---

ksqldb-common/pom.xml
ksqldb-parser/pom.xml
pom.xml

KSQL-13692 | CVE fix for commons-lang3. Bump the version to 3.18.0

KSQL-13692 | CVE fix for commons-lang3. Bump the version to 3.18.0

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/ServiceContextFactory.java

This PR makes changes to pass the user's IP address and port in proxy protocol configs to the Kafka clients instantiated.

KSQL-13699 | Pass the proxy protocol headers to admin, producer and consumer clients if the user principal is available.

---

ksqldb-cli/src/main/java/io/confluent/ksql/Ksql.java
ksqldb-cli/src/test/java/io/confluent/ksql/KsqlTest.java

Addresses the issue linked at https://github.com/confluentinc/ksql/issues/5547
sasl.* and security. protocol are not passed over to ksql server for all the persistent queries. They are treated as configs only used for the cli to connect to the ksql server.

KSQL-13763 | Filter out security.protocol and sasl.mechanism as configs to be passed to ksql query overrides.

---

config/ksql-production-server.properties
config/ksql-server.properties
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlResourceExtension.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java

Project Lasso - requires KSQL to have license validation logic. The changes here are meant to append a extension for license validation. The extension is written in the confluent-security-plugins.

KSQL-13744 Changes to add License Validation plugin from CSP

---

pom.xml

Addresses CVE-2024-57699 (DoS via stack exhaustion) in json-smart versions 2.5.0-2.5.1 by overriding transitive dependencies with secure version 2.5.2. Check https://confluentinc.atlassian.net/browse/CVE-4846 for details.
- **CVE**: CVE-2024-57699
- **Impact**: Potential DoS via stack exhaustion when processing specially crafted JSON with many opening curly braces
- **Affected versions**: net.minidev:json-smart 2.5.0 through 2.5.1
- **Fixed version**: 2.5.2
Multiple dependencies in ksqlDB 8.0.x pull in vulnerable json-smart versions:
- `com.jayway.jsonpath:json-path:2.9.0` → `json-smart:2.5.0` (PRIMARY)
- `org.apache.kafka:kafka_2.13` → `json-smart:2.x.x` (SECONDARY)
Added dependency management override in root `pom.xml`:
```bash
./mvnw dependency:tree -Dincludes=net.minidev:json-smart …
```

Address CVE-2024-57699 

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java

Add retries for ListConnector api call in the unit test.
Unit test.

KSQL-13806 | Add retries for ListConnector api call in the unit test.

---

ksqldb-common/src/main/java/io/confluent/ksql/util/timestamp/StringToTimestampParser.java
ksqldb-common/src/test/java/io/confluent/ksql/util/timestamp/StringToTimestampParserTest.java

Set the order of timestamp fields to be processed to avoid incorrect modifications for daylight savings.

KSQL-13833 | Set the order of timestamp fields to be processed to avoid incorrect modifications for daylight savings.

---

ksqldb-api-client/pom.xml
pom.xml

* [KSQL-13829] | Unpin jackson version
* [KSQL-13829] | Bump up shade plugin version
(cherry picked from commit d45322338ddd0b8c6d089604afc30dd9aa79427f)
[KSQL-13829]: https://confluentinc.atlassian.net/browse/KSQL-13829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KSQL-13829]: https://confluentinc.atlassian.net/browse/KSQL-13829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[KSQL-13829] | Unpin jackson version and upgrade shade plugin (#10841)

---

pom.xml

Update Netty to 4.1.125 to resolve CVE

KSQL-13839: update netty to 4.1.125

---

ksqldb-common/src/main/java/io/confluent/ksql/util/timestamp/StringToTimestampParser.java
ksqldb-common/src/test/java/io/confluent/ksql/util/timestamp/StringToTimestampParserTest.java

Set the order of timestamp fields to be processed to avoid incorrect modifications for daylight savings.

KSQL-13833 | Set the order of timestamp fields to be processed to avoid incorrect modifications for daylight savings. (#10833)

---

ksqldb-cli/pom.xml
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/JLineReaderTest.java
pom.xml

* upgrade jline dependency to address terminal sizing issue
* upgrade jline dependency to address terminal sizing issue
* use terminal builder in jline tests
(cherry picked from commit 96e1f07d2e2bfcb3aa1b03c8d33861e42e9ec1b8)

upgrade jline dependency to address terminal sizing issue (#10869)
