confluentinc/ksql

ksqldb-engine/src/test/java/io/confluent/ksql/execution/ExpressionEvaluatorParityTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/CastInterpreter.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/ComparisonInterpreter.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/TermCompiler.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/interpreter/terms/LiteralTerms.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/interpreter/InterpretedExpressionTest.java
ksqldb-metastore/src/test/java/io/confluent/ksql/util/MetaStoreFixture.java

Implements DATE/TIME casting and comparisons for interpreted expressions.
DATE/TIME compiled casting: https://github.com/confluentinc/ksql/pull/7708
DATE/TIME compiled comparisons: https://github.com/confluentinc/ksql/pull/7734
Unit and manually tested

feat: enable date/time for the query interpreter

---

CHANGELOG.md

Add 0.19 changelog
no testing required

chore: add changelog entries for the 0.19 release cut

---

design-proposals/README.md

docs: intent for klip-52: BYTES data type support

---

ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_full_outer_join_with_out_of_order_and_custom_grace_period_-_AVRO/7.0.0_1623947957608/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_full_outer_join_with_out_of_order_and_custom_grace_period_-_JSON/7.0.0_1623947957938/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_out_of_order_and_custom_grace_period_-_AVRO/7.0.0_1623947956837/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/joins_-_stream_stream_left_join_with_out_of_order_and_custom_grace_period_-_JSON/7.0.0_1623947957230/spec.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/joins.json

chore: fix QTT left/outer joins tests due to KAFKA-10847

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java

SR made a change where internally they stopped using a method we mocked, this mocks the proper method
ran the test

test: fix SR incompatbility in RecordFormatterTest

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java

I accidentally used `a_struct['foo']` instead of `a_struct->foo` and was entirely confused by the error message (I thought `TIMESTAMP` as not supported in structs). This gives a better error message (see unit tests)
Unit testing

chore: improve error message for subscript misuse

---

docs/developer-guide/api.md
mkdocs.yml

From https://github.com/confluentinc/ksql/pull/7800.

docs: cherry-pick: add is_valid_property endpoint to toc (DOCS-9137)

---

docs/developer-guide/api.md
mkdocs.yml

From https://github.com/confluentinc/ksql/pull/7800.

docs: cherry-pick: add is_valid_property endpoint to toc (DOCS-9138)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/7763.

docs: cherry-pick: link to 0.19.0 changelog in built changelog topic (DOCS-9144)

---

docs/developer-guide/ksqldb-reference/select-pull-query.md
docs/developer-guide/ksqldb-reference/select-push-query.md

Add struct example to SELECT topics. Also, rework headings and links.

docs: add struct examples to SELECT topics (DOCS-8265)

---

docs/developer-guide/ksqldb-reference/select-pull-query.md
docs/developer-guide/ksqldb-reference/select-push-query.md

From https://github.com/confluentinc/ksql/pull/7837.

docs: cherry-pick: add struct examples to SELECT topics (DOCS-9167)

---

docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md

From https://github.com/confluentinc/ksql/pull/7845.

docs: cherry-pick: add Content-Type header to curl example (DOCS-9181)

---

pom.xml

Upgrade Guava version
This is the version on `master`, will let the tests run on this PR though

chore: pin guava to 30.1.1-jre to address CVE

---

docs/developer-guide/ksqldb-reference/create-table.md

Also, move the SR note to a more reasonable location.

docs: update CREATE TABLE statement for JSON_SR (DOCS-7622)

---

docs/developer-guide/ksqldb-reference/create-table.md

From https://github.com/confluentinc/ksql/pull/7848.
* docs: update CREATE TABLE statement for JSON_SR (DOCS-7622)
* Fix whitespace

docs: cherry-pick: update CREATE TABLE statement for JSON_SR (DOCS-9184)

---

docs/operate-and-deploy/installation/server-config/security.md

From https://github.com/confluentinc/ksql/pull/7847.
* docs: replace zookeeper with bootstrap-server in ACLs (DOCS-8995)
* docs: remove authorizer-properties and fix port
* docs: prepend bootstrap-server with -- chars

docs: cherry-pick: replace zookeeper with bootstrap-server in ACLs (DOCS-9186)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md

From https://github.com/confluentinc/ksql/pull/7851.

docs: cherry-pick: add examples for TOPK and TOPKDISTINCT (DOCS-9187)

---

docs/reference/server-configuration.md

Related: https://github.com/confluentinc/ksql/pull/5877

docs: doc the ksql.properties.overrides.denylist config (DOCS-6882)

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/7853.

docs: cherry-pick: doc the ksql.properties.overrides.denylist config (DOCS-9190)

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/7855.

docs: cherry-pick: fix a typo denylist config (DOCS-9193)

---

ksqldb-engine/src/test/java/io/confluent/ksql/engine/ImmutabilityTest.java

fix: Prevent bytes immutability test from failing

---

pom.xml

This is to fix CVE for https://github.com/advisories/GHSA-7r82-7xv7-xcpj

chore: upgrade httpclient5 to 5.0.3 to address CVE

---

ksqldb-api-client/pom.xml
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/BatchedQueryResult.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/BatchedQueryResultImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ConnectorDescriptionImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/RowImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/SourceDescriptionImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/StreamInsertsSubscriber.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/StreamedQueryResultImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/TopicInfoImpl.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/util/JsonMapper.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/util/ClientTestUtil.java

build: update `api-client` module for spotbug 4.3.0 and re-enable plugin

---

ksqldb-common/pom.xml
ksqldb-common/src/main/java/io/confluent/ksql/GenericKey.java
ksqldb-common/src/main/java/io/confluent/ksql/config/ImmutableProperties.java
ksqldb-common/src/main/java/io/confluent/ksql/config/SessionConfig.java
ksqldb-common/src/main/java/io/confluent/ksql/function/AggregateFunctionFactory.java
ksqldb-common/src/main/java/io/confluent/ksql/function/AggregateFunctionInitArguments.java
ksqldb-common/src/main/java/io/confluent/ksql/function/KsqlFunction.java
ksqldb-common/src/main/java/io/confluent/ksql/function/KsqlScalarFunction.java
ksqldb-common/src/main/java/io/confluent/ksql/function/types/LambdaType.java
ksqldb-common/src/main/java/io/confluent/ksql/function/types/StructType.java
ksqldb-common/src/main/java/io/confluent/ksql/logging/processing/ProcessingLoggingJsonMapper.java
ksqldb-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java
ksqldb-common/src/main/java/io/confluent/ksql/properties/with/ConfigMetaData.java
ksqldb-common/src/main/java/io/confluent/ksql/reactive/BasePublisher.java
ksqldb-common/src/main/java/io/confluent/ksql/reactive/BaseSubscriber.java
ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/PersistenceSchema.java
ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/SystemColumns.java
ksqldb-common/src/main/java/io/confluent/ksql/serde/FormatInfo.java
ksqldb-common/src/main/java/io/confluent/ksql/serde/SerdeFeature.java
ksqldb-common/src/main/java/io/confluent/ksql/serde/SerdeFeatures.java
ksqldb-common/src/test/java/io/confluent/ksql/reactive/PublisherTestBase.java

build: update `common` module for spotbug 4.3.0 and re-enable plugin

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java

Updates command version from 8 to 9 to prep for the 0.20 release.

chore: update command version from 8 to 9

---

ksqldb-functional-tests/pom.xml
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/InputRecordsNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/OutputRecordsNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/PostConditionsNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/TestCaseNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/parser/SqlTestLoader.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCase.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestJsonMapper.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopologyAndConfigs.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/stubs/StubKafkaConsumerGroupClient.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/SchemaTranslationTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestsUpToDateTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/TestCaseSpecNode.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestCaseNode.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/model/Response.java

build: update `functional-tests` module for spotbug 4.3.0 and re-enable plugin

---

ksqldb-parser/src/main/java/io/confluent/ksql/parser/KsqlParser.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AlterSource.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateConnector.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/GroupBy.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/InsertValues.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/Join.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/PartitionBy.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/Select.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/Statements.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/WithinExpression.java
ksqldb-parser/src/main/java/io/confluent/ksql/util/ParserKeywordValidatorUtil.java

build: update `parser` module for spotbug 4.3.0 and re-enable plugin

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/PersistentQueryCleanupImpl.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/PersistentQueryCleanupImplTest.java

Due to overlapping PR, `master` breaks with a spotbug warning.

build: suppress spotbug warning to fix build

---

docs/developer-guide/joins/join-streams-and-tables.md

docs: improve join docs

---

docs/how-to-guides/update-a-running-persistent-query.md

As the title says. Very small PR.

docs: fix minor typos in query upgrade docs (MINOR)

---

docs/developer-guide/api.md
mkdocs.yml

From https://github.com/confluentinc/ksql/pull/7800.

docs: cherry-pick: add is_valid_property endpoint to toc (DOCS-9234)

---

docs/developer-guide/ksqldb-reference/select-pull-query.md
docs/developer-guide/ksqldb-reference/select-push-query.md

From https://github.com/confluentinc/ksql/pull/7837.

docs: cherry-pick: add struct examples to SELECT topics (DOCS-9236)

---

docs/developer-guide/ksqldb-reference/create-table.md

From https://github.com/confluentinc/ksql/pull/7848.
* docs: update CREATE TABLE statement for JSON_SR (DOCS-7622)
* Fix whitespace

docs: cherry-pick: update CREATE TABLE statement for JSON_SR (DOCS-9237)

---

docs/operate-and-deploy/installation/server-config/security.md

From https://github.com/confluentinc/ksql/pull/7847.
* docs: replace zookeeper with bootstrap-server in ACLs (DOCS-8995)
* docs: remove authorizer-properties and fix port
* docs: prepend bootstrap-server with -- chars

docs: cherry-pick: replace zookeeper with bootstrap-server in ACLs (DOCS-9238)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md

From https://github.com/confluentinc/ksql/pull/7851.

docs: cherry-pick: add examples for TOPK and TOPKDISTINCT (DOCS-9239)

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/7853.

docs: cherry-pick: doc the ksql.properties.overrides.denylist config (DOCS-9240)

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/7855.

docs: cherry-pick: fix a typo denylist config (DOCS-9242)

---

docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md

From https://github.com/confluentinc/ksql/pull/7845.

docs: cherry-pick: add Content-Type header to curl example (DOCS-9182)

---

docs/developer-guide/joins/join-streams-and-tables.md

From https://github.com/confluentinc/ksql/pull/7699.

docs: cherry-pick: improve join docs (DOCS-9244)

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/ScalablePushRegistry.java
ksqldb-engine/src/test/java/io/confluent/ksql/physical/scalablepush/ScalablePushRegistryTest.java

chore: move off deprecated Processor API

---

docs/index.md

I added a **Courses** tile to the landing page:

docs: add card for DevX courses (DOCS-9197)

---

docs/index.md

From https://github.com/confluentinc/ksql/pull/7881.

docs: cherry-pick: add card for DevX courses (DOCS-9265)

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md

From https://github.com/confluentinc/ksql/pull/7912.

docs: cherry-pick: add EMIT CHANGES to CSAS/CTAS examples (DOCS-9269)

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md

From https://github.com/confluentinc/ksql/pull/7912.

docs: cherry-pick: add EMIT CHANGES to CSAS/CTAS examples (DOCS-9270)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/restore/KsqlRestoreCommandTopic.java

fix: no named topologies yet

---

ksqldb-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
ksqldb-engine/src/main/java/io/confluent/ksql/structured/SchemaKTable.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/plan/ForeignKeyTableTableJoin.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/plan/ForeignKeyTableTableJoinTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/ExecutionStepFactory.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/ForeignKeyTableTableJoinBuilderTest.java

chore: FK join expression support follow-ups

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/type-coercion.md
docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md
docs/reference/serialization.md
docs/reference/sql/appendix.md
docs/reference/sql/data-types.md
docs/reference/user-defined-functions.md

docs: add docs for the BYTES type

---

ksqldb-engine/src/main/java/io/confluent/ksql/physical/scalablepush/ScalablePushRegistry.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/StreamAggregateBuilderTest.java

chore: fix more checkstyle / spotbugs issues

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
ksqldb-common/src/main/java/io/confluent/ksql/util/BytesUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Split.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udf/string/SplitTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_a_message_by_commas_and_display_pos_0_and_2_of_the_returned_array/7.1.0_1627559375925/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_a_message_by_commas_and_display_pos_0_and_2_of_the_returned_array/7.1.0_1627559375925/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_a_message_by_commas_and_display_pos_0_and_2_of_the_returned_array/7.1.0_1627559375925/topology
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_a_message_by_using_the_'$$'_delimiter/7.1.0_1627559375723/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_a_message_by_using_the_'$$'_delimiter/7.1.0_1627559375723/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_a_message_by_using_the_'$$'_delimiter/7.1.0_1627559375723/topology
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_a_message_by_using_the_'.'_delimiter/7.1.0_1627559371428/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_a_message_by_using_the_'.'_delimiter/7.1.0_1627559371428/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_a_message_by_using_the_'.'_delimiter/7.1.0_1627559371428/topology
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_all_characters_by_using_the_''_delimiter/7.1.0_1627559375821/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_all_characters_by_using_the_''_delimiter/7.1.0_1627559375821/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/split_-_split_all_characters_by_using_the_''_delimiter/7.1.0_1627559375821/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/split.json

Update the `SPLIT` function to support `BYTES`.

Bytes split function

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Split.java

Fix checkstyle error
No behavior changed.

fix: checkstyle remove separation in imports

---

docs/developer-guide/joins/join-streams-and-tables.md

From https://github.com/confluentinc/ksql/pull/7938.

docs: cherry-pick: update stream-stream join docs (DOCS-9403)

---

ksqldb-common/pom.xml
ksqldb-engine/pom.xml
ksqldb-metastore/pom.xml
ksqldb-parser/pom.xml
ksqldb-serde/pom.xml

chore: cleanup pom files

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/TopicNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilder.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/Topic.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/StubKafkaServiceTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_AVRO_in_out/7.1.0_1628037600064/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_AVRO_in_out/7.1.0_1628037600064/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_AVRO_in_out/7.1.0_1628037600064/topology
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_PROTOBUF_in_out/7.1.0_1628037599988/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_PROTOBUF_in_out/7.1.0_1628037599988/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/bytes_-_PROTOBUF_in_out/7.1.0_1628037599988/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/bytes.json

Cherry-picked the changes from #7940 to run Jenkins.

refactor: add avro bytes QTT test

---

docs/developer-guide/joins/partition-data.md

I noticed that this page in the docs is missing some syntax that is included in the newer versions of ksql. This is PR is updating that.

docs: updated minor syntax updates in docs

---

docs/stylesheets/extra.css

docs: improve version picker rendering in Windows

---

docs/developer-guide/joins/partition-data.md

From https://github.com/confluentinc/ksql/pull/7949.

docs: cherry-pick: updated minor syntax updates in docs (DOCS-9406)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9418)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9425)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9426)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9427)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9428)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9429)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9430)

---

docs/stylesheets/extra.css

docs: improve version picker rendering in Windows (#7957)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9432)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9433)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9434)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9435)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9436)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9437)

---

docs/stylesheets/extra.css

docs: cherry-pick: improve version picker rendering in Windows (DOCS-9438)

---

design-proposals/README.md

Starting the KLIP process for Pull Queries on Streams

docs: intent for klip-53: Pull Queries on Streams

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/PullQueryExecutorMetrics.java
ksqldb-engine/src/main/java/io/confluent/ksql/physical/pull/PullPhysicalPlan.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java

Refactor pull query metrics to remove the need for confusing "UNKNOWN" enum values on
the various query types.
Internal refactor. Existing tests should be sufficient.

refactor: pull query metrics

---

design-proposals/README.md

docs: intent for klip-53: Optimized Range Pull Queries on Tables

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlAuthorizationValidatorFactory.java
ksqldb-engine/src/test/java/io/confluent/ksql/security/KsqlAuthorizationValidatorFactoryTest.java

Re-use the same flag to disable Kafka permissions checks to also disable SR permissions checks.

chore: add feature flag to disable Schema Registry permissions checks

---

CHANGELOG.md

From https://github.com/confluentinc/ksql/pull/7883.
* docs: add changelog for 0.20
* commit Patrick's suggestion
Co-authored-by: Patrick Sullivan <psullivan@confluent.io>
* edit KAFKA-10847 bugfix changelog
* nit: longer integration tests timeouts
* Update CHANGELOG.md zara 1
Co-authored-by: Zara Lim <jzaralim@gmail.com>
* Update CHANGELOG.md zara 2
Co-authored-by: Zara Lim <jzaralim@gmail.com>
* Update CHANGELOG.md zara 3
Co-authored-by: Zara Lim <jzaralim@gmail.com>
* Update CHANGELOG.md zara 4
Co-authored-by: Zara Lim <jzaralim@gmail.com>
* Update CHANGELOG.md zara 5
Co-authored-by: Zara Lim <jzaralim@gmail.com>
* Update CHANGELOG.md zara 6
Co-authored-by: Zara Lim <jzaralim@gmail.com>
* Update CHANGELOG.md zara 7
Co-authored-by: Zara Lim <jzaralim@gmail.com>
* Update CHANGELOG.md …

docs: cherry-pick: add changelog for 0.20 (DOCS-9543)

---

design-proposals/klip-54-optimized-range-pull-queries.md

docs: klip-54: Optimized Range Pull Queries on Tables

---

docs/developer-guide/ksqldb-reference/quick-reference.md

From https://github.com/confluentinc/ksql/pull/8010.

docs: cherry-pick: fix munged markdown for IN ref topic (DOCS-9569)

---

docs/developer-guide/ksqldb-reference/quick-reference.md

From https://github.com/confluentinc/ksql/pull/8010.

docs: cherry-pick: fix munged markdown for IN ref topic (DOCS-9576)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/8006.

docs: cherry-pick: add v0.20.0 section to built changelog (DOCS-9577)

---

docs/reference/server-configuration.md

docs: update docs for idle connection timeout

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/insert-into.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-push-query.md

From https://github.com/confluentinc/ksql/pull/8020.

docs: cherry-pick: revert GRACE keyword in Joins (DOCS-9583)

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/insert-into.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-push-query.md

From https://github.com/confluentinc/ksql/pull/8020.

docs: cherry: revert GRACE keyword in Joins (DOCS-9583)

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/insert-into.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-push-query.md

From https://github.com/confluentinc/ksql/pull/8020.

docs: cherry-pick: revert GRACE keyword in Joins (DOCS-9582)

---

CHANGELOG.md
docs/developer-guide/joins/join-streams-and-tables.md

docs: revert left/outer stream-stream join doc updates

---

CHANGELOG.md
docs/developer-guide/joins/join-streams-and-tables.md

From https://github.com/confluentinc/ksql/pull/8030.

docs: cherry-pick: revert left/outer stream-stream join doc updates (DOCS-9598)

---

CHANGELOG.md
docs/developer-guide/joins/join-streams-and-tables.md

From https://github.com/confluentinc/ksql/pull/8030.

docs: cherry-pick: revert left/outer stream-stream join doc updates (DOCS-9599)

---

docs/operate-and-deploy/migrations-tool.md

From https://github.com/confluentinc/ksql/pull/8075.

docs: cherry-pick: link to schema evolution blog post (DOCS-9735)

---

docs/operate-and-deploy/migrations-tool.md

From https://github.com/confluentinc/ksql/pull/8075.

docs: cherry-pick: link to schema evolution blog post (DOCS-9736)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java

chore: update cmd version

---

CONTRIBUTING.md

docs: clarify use of conventional commit types (MINOR)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TerminateTransientQueryFunctionalTest.java

I added a test in https://github.com/confluentinc/ksql/pull/8079 that checks TERMINATE cannot be called in CST queries. The test was added in `TerminateTransientQueryFunctionalTest`. This query is very flaky and I'm not sure what's causing the queries to be removed (perhaps some before/after calls in `TestKsqlRestApp`). Anyway, this test shouldn't be in this class 'cause the class only tests transient queries, but CST queries are persistent. 
I removed this test to unblock master. I will follow up in another PR to re-locate the test.

chore: remove flaky test for TERMINATE CST queries

---

docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table.md

Added docs for source tables and streams.

docs: add docs for CST commands

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintExplainQueryWithError.approved.json
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescriptionFactory.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ExplainExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListQueriesExecutorTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java

add consumer group ID to the query description

feat: add consumerGroupId to QueryDescription

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/ColumnType.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/RowImplTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/util/RowUtilTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/StructuredTypesDataProvider.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/BaseApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ApiIntegrationTest.java

Fixes #7878
Enables queries involving date/time/timestamp
Updated tests

fix: add time types to Java client

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/SystemColumns.java

This PR inlines the inner class `PseudoColumns` into `SystemColumns`.  Since `SystemColumns` relied on static blocks defined below in `PseudoColumns`, they weren't being initialized in time and resulted in NPEs in tests (and maybe in non test code?).
The main solution was to either inline, or pull the (private) logic out to another class in the package, so I did this.  Also circular dependent classes  are also tricky, so avoided that: https://stackoverflow.com/questions/6416408/static-circular-dependency-in-java
I'm not sure how this works on CI except maybe that it uses a different version of java, but I still don't see how it could pass the same tests.
Ran package tests

chore: Inlines inner class PseudoColumns since the static order was incorrect

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestTestExecutor.java

Currently, for scalable push queries, input is produced after the queries start, so there are no offsets to track.  For this reason, it may finish without being in the running state, which introduces a race. Now, for all queries, before even tracking offsets, this ensures the persistent queries are in the RUNNING state.
Ran RQTT tests!

test: For RQTTs, wait for persisent queries to run

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java

Just a small cleanup to inline some needlessly roundabout code.
It looks like this was intended to provide a hook for testing or something,
but it serves no purpose now. Past refactoring probably rendered this
complexity pointless.

refactor: simplify websocket endpoint

---

CHANGELOG.md

chore: new change-log for 0.21

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryMetricsFunctionalTest.java

Ignore flaky metrics test until we figure out why it is failing

test: add ignore to flaky test (PullQueryMetricsFunctionalTest)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryMetricsFunctionalTest.java

Ignore PullQueryMetricsFunctionalTest since it is still flaky

test: add ignore to test to fix master

---

docs/operate-and-deploy/high-availability-pull-queries.md
docs/operate-and-deploy/index.md
docs/reference/server-configuration.md
mkdocs.yml

Adds documentation for high availability in pull queries.

docs: High Availability for Pull Query documentation

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java

chore: fix imports

---

config/ksql-server.properties
ksqldb-functional-tests/src/test/resources/query-validation-tests/row-offset-and-partition.json
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/push-queries.json

QTTs for [KLIP-50](https://github.com/confluentinc/ksql/blob/master/design-proposals/klip-50-partition-and-offset-in-ksqldb.md).

test: QTT coverage for ROWPARTITION/ROWOFFSET

---

docs/developer-guide/ksqldb-reference/create-stream.md

From https://github.com/confluentinc/ksql/pull/8209.

docs: cherry-pick: update CREATE STREAM statements for JSON_SR (DOCS-10172)

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-streams.json

Enable stream pull queries by default now that feature implementation is complete

chore: enable stream pull queries by default

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/DistributingExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

chore: fix conflicts for IF NOT EXISTS

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.testPrintPropertyList.approved.json
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListPropertiesExecutorTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/PropertiesList.java

We want to specify whether a property is internal and which level (server or query) it is for the `list properties` command:
Unit testing

Kci 1191/extend list properties

---

design-proposals/klip-58-limit-clause-for-pull-queries.md

klip-58: `LIMIT` clause for Pull Queries

docs: klip-58: LIMIT clause for Pull Queries

---

docs/operate-and-deploy/high-availability-pull-queries.md
docs/operate-and-deploy/index.md
docs/reference/server-configuration.md
mkdocs.yml

From https://github.com/confluentinc/ksql/pull/8157.
* docs: High Availability for Pull Query documentation

docs: cherry-pick: high Availability for Pull Query documentation (DOCS-10795)

---

docs/operate-and-deploy/high-availability-pull-queries.md
docs/operate-and-deploy/index.md
docs/reference/server-configuration.md
mkdocs.yml

From https://github.com/confluentinc/ksql/pull/8157.
* docs: High Availability for Pull Query documentation

docs: cherry-pick: high Availability for Pull Query documentation (DOCS-10796)

---

docs/operate-and-deploy/high-availability-pull-queries.md
docs/operate-and-deploy/index.md
docs/reference/server-configuration.md
mkdocs.yml

From https://github.com/confluentinc/ksql/pull/8157.
* docs: High Availability for Pull Query documentation

docs: cherry-pick: high Availability for Pull Query documentation (DOCS-10797)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/HighAvailabilityTestUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/SystemAuthenticationFunctionalTest.java

The test was flaky for the reasons described in #8274 (I verified it at some point in the logs), this PR fixes that.
Ran this test

test: fix flaky SystemAuthenticationFunctionalTest

---

docs/developer-guide/ksqldb-reference/create-table.md

From https://github.com/confluentinc/ksql/pull/8360.

docs: cherry-pick: clarify grammar in CREATE TABLE topic (DOCS-10827)

---

docs/developer-guide/ksqldb-reference/create-table.md

From https://github.com/confluentinc/ksql/pull/8360.

docs: cherry-pick: clarify grammar in CREATE TABLE topic (DOCS-10828)

---

Jenkinsfile

build: Disable concurrent builds 54x

---

docs/operate-and-deploy/installation/upgrading.md

From https://github.com/confluentinc/ksql/pull/8370.

docs: cherry-pick: bump version in upgrade notes for 0.21.0 (DOCS-10842)

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/DefaultSchemaRegistryClient.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java

update default schema registry client to include new methods

fix: update client to fix build

---

ksqldb-common/src/main/java/io/confluent/ksql/config/ImmutableProperties.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateSource.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStream.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTable.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RequestHandler.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/FeatureFlagChecker.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/RequestHandlerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/FeatureFlagCheckerTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/PropertiesList.java

I added the following config to disable/enable headers columns: `ksql.headers.columns.enabled`.

chore: add feature flag to disable HEADERS columns

---

pom.xml

duplicate declaration in pom causing confusing warnings

fix: fix warnings in pom

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/OrphanedTransientQueryCleaner.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/PersistentQueryCleanupImpl.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/PersistentQueryCleanupImplTest.java

look for shared runtimes when cleaning up and remove only the queries internal topics

feat: clean up based on query id for shared runtimes

---

scripts/changelog/README.md

Update changelog instructions to make sure you wait for the previous release to have added their changes first

chore: Update changelog scripts README.md

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/average/AverageUdaf.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/average/AverageUdafTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/average-udaf_-_average_udaf_with_table/7.2.0_1637551696763/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/average-udaf_-_average_udaf_with_table/7.2.0_1637551696763/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/average-udaf_-_average_udaf_with_table/7.2.0_1637551696763/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/average-udaf.json

This PR fixes an NPE which occurs in the average udaf when removing a null value from the average.
added a QTT and a unit test

fix: handle null input for average udaf

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java

We need to increment the command version for each next release.

chore: bump command version from 11 to 12 for v0.24

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/LocalCommandsFile.java

Attempt to fix race condition when writing local command file: https://confluentinc.atlassian.net/browse/KQE-532

fix: synchronizing writes to localcommand file

---

ksqldb-common/src/main/java/io/confluent/ksql/config/SessionConfig.java
ksqldb-common/src/test/java/io/confluent/ksql/config/SessionConfigTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjector.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplier.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/TopicSchemaSupplier.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorFunctionalTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/DefaultSchemaInjectorTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/elements.json
ksqldb-parser/src/main/java/io/confluent/ksql/parser/properties/with/CreateSourceProperties.java
ksqldb-serde/src/main/java/io/confluent/ksql/serde/connect/ConnectFormat.java

* Add raw schema to schema result
* Populate raw schema to session config to be used later in Schema Injector
* Don't populate schema id to property if implicitly used
* Unit test. Will add more unit test

chore: add raw schema to session override

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java
ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/SchemaRegistryUtil.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/schema/registry/SchemaRegistryUtilTest.java

Register raw schema fetched using schema id
* Unit test.

chore: register raw parsed schema fetched from schema id if exist

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ExecuteQueryResponseHandler.java
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/StreamQueryResponseHandler.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ConsistencyOffsetVectorFunctionalTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/PullQueryQueue.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/BlockingQueryPublisher.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/server/QuerySubscriber.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/PullQueryPublisher.java

Add logging to obtain more information for debugging flaky test that cannot get reproduced locally. The logs will only occur when consistency is enabled which doesn't happen in production so they should not spam production code.

chore: add logging for debugging flaky test

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjector.java

Catch `FormatFactory.of` exception and rethrow with better message if it's because of not supporting `schemaId`
Existing unit test

fix: fix broken test

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/8442.

docs: cherry-pick: add SOURCE setting to ksqlDB config (DOCS-10979)

---

docs/developer-guide/ksqldb-reference/create-table.md
docs/reference/sql/data-definition.md

From https://github.com/confluentinc/ksql/pull/8454.

docs: cherry-pick: add note about primary keys for tables (DOCS-10993)

---

ksqldb-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroSerializerTest.java

Remove import which broken openjdk build
Builds

fix: remove unnecessary import

---

design-proposals/klip-56-schema-id-in-create-statements.md

Update klip-56 with more detailed design.

docs: update klip-56

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryBuilderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java

Use the blocking changes made in streams to fix many issues with adding and removing qureies 

feat: use blocking topology changes

---

ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/PropertiesList.java

We want to disallow changing certain properties at the server level. This PR is removing them from the allow list that is used to determine whether a property can be changed with the `ALTER SYSTEM` query. 
```
ENABLE_AUTO_COMMIT_CONFIG,
AUTO_COMMIT_INTERVAL_MS_CONFIG,
PARTITION_ASSIGNMENT_STRATEGY_CONFIG,
TRANSACTIONAL_ID_CONFIG,
APPLICATION_ID_CONFIG
```
made sure existing tests run

feat: removed properties from allowlist

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java

create new topologies and use those to get a new kafka streams runtimes

feature: allow shared runtimes to be restarted to pick up config changes

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/rewrite/AstSanitizer.java
ksqldb-engine/src/test/java/io/confluent/ksql/ddl/commands/DdlCommandExecTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/KsqlEngineTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/AstSanitizerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/headers.json
ksqldb-metastore/src/test/java/io/confluent/ksql/util/MetaStoreFixture.java

Also adds a check to `AstSanitizer`. Previously the checks were only in `DistributingExecutor`

test: add functional tests for INSERT statements with headers

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/operate-and-deploy/schema-inference-with-id.md

Schema id docs update
N/A for now

docs: schema id docs

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/8502.

docs: cherry-pick: fix link to 0.22 announcement post (DOCS-11048)

---

docs/operate-and-deploy/index.md
docs/operate-and-deploy/schema-inference-with-id.md
mkdocs.yml

Copy edit for https://github.com/confluentinc/ksql/pull/8484.

docs: edit pass on new Schema Inference with ID content (DOCS-11037)

---

ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java

there were a few tests that were broken that are fixed now that we have blocking add and remove topologies merged

chore: enable tests 

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java

Adds more logging to debug issues with deleting topics for transient queries.

chore: Adds more logging for cleaning up topics for push queries

---

ksqldb-common/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchema.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/planner/plan/QueryProjectNode.java
ksqldb-engine/src/test/java/io/confluent/ksql/planner/plan/QueryProjectNodeTest.java
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-with-headers.json

Include header columns in source table queries
RQTT + manual test

feat: enable headers for source tables

---

docs/concepts/events.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/developer-guide/ksqldb-reference/insert-values.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/reference/server-configuration.md
docs/reference/sql/appendix.md
docs/reference/sql/data-definition.md

Add documentation for `HEADERS` feature

docs: add docs for header feature

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/StatementParser.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/ClusterTerminator.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TemporaryEngine.java

Fixes errors on master
Ran findbugs

chore: Fix findbugs errors

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

chore: turn off headers feature flag

---

docs/operate-and-deploy/how-it-works.md

From https://github.com/confluentinc/ksql/pull/8560.

docs: add ksqlDB courses to architecture docs (DOCS-11232)

---

ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/driver/KsqlTesterTest.java

Sometimes, the following exception is thrown by the `KsqlTesterTest`.
```
io.confluent.ksql.util.KsqlException: java.nio.file.NoSuchFileException: /home/jenkins/workspace/confluentinc_ksql_master/ksqldb-functional-tests/junit2355510253803863994/_confluent-ksql-some.ksql.service.idquery_CTAS_B_0/0_0/rocksdb/KsqlTopic-Reduce/000024.sst
at io.confluent.ksql.test.driver.KsqlTesterTest.closeDriver(KsqlTesterTest.java:309)
at io.confluent.ksql.test.driver.KsqlTesterTest.access$100(KsqlTesterTest.java:98)
at io.confluent.ksql.test.driver.KsqlTesterTest.close(KsqlTesterTest.java:198)
Caused by: java.nio.file.NoSuchFileException: /home/jenkins/workspace/confluentinc_ksql_master/ksqldb-functional-tests/junit2355510253803863994/_confluent-ksql-some.ksql.service.idquery_CTAS_B_0/0_0/rocksdb/KsqlTopic- …
```

chore: do not throw an exception in KsqlTesterTest when copying non-existing files

---

ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedTableIQv2.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedTableIQv2Test.java

Just a few cleanup items after #8556 
Running the CIT suite

refactor: small IQv2 cleanup

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryIQv2FunctionalTest.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterialization.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedSessionTableIQv2.java
ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedWindowTableIQv2.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedSessionTableIQv2Test.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/materialization/ks/KsMaterializedWindowTableIQv2Test.java

This PR is using the recently added IQv2 based Window and Session queries to implement window and session key lookups and table scans.

Using IQv2 API for pull queries on window stores

---

docs/overrides/main.html

https://confluentinc.atlassian.net/browse/UIF-1113
https://confluentinc.atlassian.net/wiki/spaces/DOC/pages/2696544739/1-Pager+Improved+doc+site+search
This adds an additional meta tag to support search relevancy boosting for docs search.
Tested locally for the presence of the new metatag in the output

feat: [UIF-1113] Add weighting to search results based on domain

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/developer-guide/ksqldb-reference/create-connector.md
docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/insert-values.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/select-pull-query.md
docs/developer-guide/ksqldb-reference/select-push-query.md

From https://github.com/confluentinc/ksql/pull/8580.

docs: cherry-pick: embed links to recipes and tutorials (DOCS-11640)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/developer-guide/ksqldb-reference/create-connector.md
docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/insert-values.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/select-pull-query.md
docs/developer-guide/ksqldb-reference/select-push-query.md

From https://github.com/confluentinc/ksql/pull/8580.

docs: cherry-pick: embed links to recipes and tutorials (DOCS-11641)

---

docs/concepts/time-and-windows-in-ksqldb-queries.md

From https://github.com/confluentinc/ksql/pull/8573.

docs: cherry-pick: add details on window emission (DOCS-11647)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/8588.

docs: cherry-pick: link to 0.23.1 blog post in changelog (DOCS-11650)

---

ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/timestamp/TimestampExtractionPolicyFactory.java

Fix typo
No code changes, just a typo fix

fix: typo in TimestampExtractionPolicyFactory

---

docs/developer-guide/ksqldb-reference/select-push-query.md

From https://github.com/confluentinc/ksql/pull/8594.

docs: cherry-pick: link to blog post in push query doc (DOCS-11654)

---

docs/reference/server-configuration.md

_What behavior do you want to change, why, how does your patch achieve the changes?
Quick doc change to add a link to SHOW PROPERTIES in the config page.
N/A
- [N/A] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

Docs: Update server-configuration.md to add link to SHOW PROPERTIES

---

docs/how-to-guides/convert-changelog-to-table.md

update changelog guide to use CTAS work

docs: update changelog guide to use CREATE SOURCE TABLE

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/PullQueryQueue.java

cherrypick https://github.com/confluentinc/ksql/commit/a41a8d855ffc9f802fb279264eaa572c049519e1

fix: make adding to pull query queue threadsafe (#8544)

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/PullQueryQueue.java

cherry-pick https://github.com/confluentinc/ksql/commit/c7793a8677d0648c250376485e6979eb9a43eb5c

feat: un-synchronize PullQueryQueue row queuing when limit absent (#8563)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java

Follow up to #8551
For an unknown topic, the topic shall be created with the default
replication factor.

test: extend RecoveryTest for unknown topic

---

docs/overrides/main.html
docs/requirements.txt

Munged in https://github.com/confluentinc/ksql/pull/8613.
Also syncs docs/overrides/main.html with master.

docs: fix munged requirements.txt (DOCS-11699)

---

docs/overrides/main.html
docs/requirements.txt

From https://github.com/confluentinc/ksql/pull/8620.

docs: cherry-pick: fix munged requirements.txt (DOCS-11700)

---

docs/requirements.txt

From https://github.com/confluentinc/ksql/pull/8622.

docs: cherry-pick: fix mdx-truly-sane-lists version in requirements.txt (DOCS-11703)

---

docs/concepts/time-and-windows-in-ksqldb-queries.md
docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/developer-guide/ksqldb-rest-api/streaming-endpoint.md

From https://github.com/confluentinc/ksql/pull/8626.

docs: cherry-pick: Fix list formatting in admonitions (DOCS-11707)

---

docs/developer-guide/ksqldb-reference/print.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/show-connectors.md
docs/developer-guide/ksqldb-reference/terminate.md
docs/reference/sql/appendix.md

From https://github.com/confluentinc/ksql/pull/8629.

docs: cherry-pick: update reference with new keywords (DOCS-11709)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java

Include https://github.com/confluentinc/ksql/commit/f1d45b27cea2dd22d32dae2bc81658ca70c4d560 in the release

chore: turn off headers feature flag (#8536)

---

docs/developer-guide/ksqldb-reference/create-stream.md
ksqldb-functional-tests/src/test/resources/rest-query-validation-tests/pull-queries-against-streams.json

Correct the docs and add a test to prove it.
New functional test.

fix: pull queries are supported on source streams now.

---

docs/operate-and-deploy/installation/installing.md

docs: missing docker exec -it option

---

docs/operate-and-deploy/installation/installing.md

From https://github.com/confluentinc/ksql/pull/8601.

docs: cherry-pick: docker exec -it (DOCS-11767)

---

docs/overrides/partials/copyright.html

From https://github.com/confluentinc/ksql/pull/8648.

docs: cherry-pick: update footer with Inc. (DOCS-11758)

---

docs/developer-guide/ksqldb-reference/run-script.md

Minor docs fix. Also clarifies that RUN SCRIPT is CLI-only.

docs: fix title on RUN SCRIPT docs (MINOR)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-pull-query.md
docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/8654.

docs: cherry-pick: fix a few broken links (DOCS-11771)

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/type-coercion.md
docs/developer-guide/ksqldb-rest-api/ksql-endpoint.md
docs/how-to-guides/update-a-running-persistent-query.md
docs/reference/serialization.md
docs/reference/sql/appendix.md
docs/reference/sql/data-types.md
docs/reference/user-defined-functions.md

From https://github.com/confluentinc/ksql/pull/8688 and https://github.com/confluentinc/ksql/pull/8690.

docs: cherry-pick: scalar functions page updates to live branch (DOCS-11999)

---

docs/developer-guide/ksqldb-reference/create-stream.md

From https://github.com/confluentinc/ksql/pull/8697.

docs: cherry-pick edits to CREATE STREAM topic to live branch (DOCS-12019)

---

docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table.md

From https://github.com/confluentinc/ksql/pull/8702.

docs: cherry-pick CREATE TOPIC edits to live branch (DOCS-12024)

---

docs/operate-and-deploy/schema-inference-with-id.md
docs/operate-and-deploy/schema-registry-integration.md

Add more details in schema inference without id
NA

docs: enrich schema inference without id doc

---

design-proposals/README.md

docs: intent for KLIP-60: Support input topics with multiple message types

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/RuntimeAssignor.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java

Prints the runtime Id's instead of the object hashes

fix: logging improvement

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/RuntimeAssignor.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java

fix: reorder imports

---

docs/tutorials/etl.md
docs/tutorials/event-driven-microservice.md
docs/tutorials/materialized.md

Fixed docker compose content in tutorials
local testing with docker-compose

DOC fix: replaced old schema registry config with bootstrap servers

---

docs/tutorials/etl.md
docs/tutorials/event-driven-microservice.md
docs/tutorials/materialized.md

From https://github.com/confluentinc/ksql/pull/8734.

docs: cherry-pick: update SR config for bootstrap servers (DOCS-12097)

---

docs/tutorials/etl.md
docs/tutorials/event-driven-microservice.md
docs/tutorials/materialized.md

From https://github.com/confluentinc/ksql/pull/8734.

docs: cherry-pick: update SR config for bootstrap servers (DOCS-12098)

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/8766.

docs: cherry-pick: add ksql.max.task.idle.ms to server config topic (DOCS-12179)

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

- Fill in missing "Since" versions.
- Standardize examples and symbol markup.
- Increase font-weight in headings.
- Add horizontal separators between functions.
- Various edits for consistency.

docs: edit pass on scalar functions topic (DOCS-12173)

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

From https://github.com/confluentinc/ksql/pull/8759.

docs: cherry-pick edits to scalar function topic (DOCS-12180)

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

Related: https://github.com/confluentinc/ksql/pull/8759.

docs: edit pass on new functions topic (DOCS-12182)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md

Related: https://github.com/confluentinc/ksql/pull/8771.

docs: tweaks to aggregate functions topic (DOCS-12184)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/developer-guide/ksqldb-reference/table-functions.md

From https://github.com/confluentinc/ksql/pull/8771 and https://github.com/confluentinc/ksql/pull/8772.

docs: cherry-pick: edit pass on aggregate functions topic (DOCS-12185)

---

design-proposals/README.md

docs: intent for klip-61: bootstrapped TABLE subscriptions

---

maven-settings.xml

As part of the internal release stabilization process, we produce non-public artifacts, and this change allows us to access them by using the staging repo.
Ran the benchmark, building using this repo

chore: Adds repo to maven-settings.xml for building against unpublished artifacts

---

docs/reference/processing-log.md

From https://github.com/confluentinc/ksql/pull/8795.

docs: cherry-pick: remove repeated section in processing log topic (DOCS-12818)

---

ksqldb-functional-tests/src/assembly/development.xml
ksqldb-functional-tests/src/assembly/package.xml

This removes netty from the functional tests packaging.

chore: Remove netty from functional tests packaging.

---

design-proposals/klip-61-bootstrapped-table-subscriptions.md

docs: klip-61: bootstrapped TABLE subscriptions

---

CHANGELOG.md
docs/operate-and-deploy/changelog.md

chore: generate 0.24.0 changelog

---

docs/js/analytics.js

From https://github.com/confluentinc/ksql/pull/8800.

docs: cherry-pick: add Segment integration (DOCS-12858)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/ScalablePushBandwidthThrottleIntegrationTest.java

Makes `ScalablePushBandwidthThrottleIntegrationTest` less flaky.  This uses the same technique on the http2 test as the http1 test, hopefully improving reliability by removing separate requests in a single test.
Ran test!

test: Make a pull query v2 test less flaky

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/TransientQueryCleanupService.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/LeakedResourcesMetrics.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

Introduces JMX metrics for monitoring the number of leaked resources (topics and state dierctories) and the state of the `TransientQueryCleanupService`.
The 4 metrics introduced are:
- `leaked_topics`: The number of leaked topics that the `TransientQueryCleanupService` has identified.
- `leaked_state_files`: The number of leaked state directories that the `TransientQueryCleanupService` has identified.
- `leaked_topics_after_cleanup`: The number of leaked topics that the `TransientQueryCleanupService` has identified immediately after attempting to cleanup the leaked topics. This would serve as a heuristic for how many leaked topics the `TransientQueryCleanupService` failed to clean up. 
- `leaked_state_dirs_after_cleanup`: The number of leaked state directories that the …

feat: add cleanup service metrics

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryConsistencyFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryIQv2FunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQuerySingleNodeFunctionalTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/ConsumerTestUtil.java

Add logging to identify if the problem is in the consumer or producer. Also, increased the poll timeout to 300ms

chore: add logging to failing flaky tests

---

ksqldb-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java

Manual testing is in progress.

fix: Set the sslFactory properly for the SR REST client.

---

CHANGELOG.md
docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/8751.

docs: cherry-pick: generate 0.24.0 changelog (DOC-12895)

---

CHANGELOG.md
docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/8751.

docs: cherry-pick: generate 0.24.0 changelog (DOCS-12896)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/8838.

docs: cherry-pick: link to 0.24.0 changelog in built changelog topic (DOCS-12898)

---

mkdocs.yml

Updates docs config to use latest public Confluent Platform version.

docs: fix cprelease version

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/ConnectJsonMapper.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/DefaultConnectClientTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/services/ConnectClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListConnectorPluginsExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListConnectorPluginsTest.java
pom.xml

Addresses https://github.com/confluentinc/ksql/issues/8841 / https://github.com/confluentinc/ksql/issues/8863
This follows up on a change in Apache Kafka here: https://github.com/apache/kafka/commit/029a14b530dcaab980faee4fa18c925b95db3122
Unit test updates should be sufficient.

chore: Update references to ConnectorPluginInfo to PluginInfo

---

ksqldb-common/src/main/java/io/confluent/ksql/config/ImmutableProperties.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/PropertiesList.java

Add feature flag for new persistent query planner.

chore: add feature flag for new logical planner

---

ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java

We make sure that the topologies running are the same as the ones that are being tracked. 
The build will not pass until https://github.com/apache/kafka/pull/11808 get sync'd

chore: Add some logging so that we can be sure that the metadata matches with the reality during validation

---

ksqldb-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryConsistencyFunctionalTest.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/ConsumerTestUtil.java

test: change consumer subscribe to assign

---

docs/reference/processing-log.md
docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/8886.

docs: cherry-pick: add note about CCloud default for processing log (DOCS-13014)

---

docs/how-to-guides/create-a-user-defined-function.md
docs/reference/user-defined-functions.md

Relates to https://github.com/confluentinc/ksql/issues/6638

docs: Adding description of how to write a dynamic UDAF.

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/json_sr.json

Demonstrates the test case / error from https://github.com/confluentinc/ksql/issues/8861

test: Adding test to show GitHub issue #8861

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/ClientImpl.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ClientImplTest.java

Adds a user agent to the java client so that it can be logged and potentially used to tag metrics.
Unit test and manually verified.

chore: Adds user agent to the java client

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryConsistencyFunctionalTest.java

chore: add more elaborate logging to flaky test

---

docs/operate-and-deploy/changelog.md

Related: https://github.com/confluentinc/ksql/pull/8543

docs: fix 0.23.1 changelog link (DOCS-9867)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/8959.

docs: cherry-pick 0.24.0 blog post link (DOCS-13248)

---

Jenkinsfile

chore: disable downstream validation for PR builds

---

docs/reference/server-configuration.md
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java

docs: add docs for endpoint logging configs

---

docs/reference/server-configuration.md
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java

From https://github.com/confluentinc/ksql/pull/8988.

docs: cherry-pick: add docs for endpoint logging configs (#8988)

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/9009.

docs: cherry-pick: update max.task.isle.ms param in config topic (DOCS-13424)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/create-table.md
docs/developer-guide/ksqldb-reference/insert-values.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/developer-guide/ksqldb-reference/select-pull-query.md
docs/developer-guide/ksqldb-reference/select-push-query.md

From https://github.com/confluentinc/ksql/pull/9012.

docs: cherry-pick: update example code in-page links (DOCS-13428)

---

ksqldb-engine/src/main/java/io/confluent/ksql/execution/scalablepush/PushPhysicalPlanBuilder.java

chore: improve registry not found error message

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_if_null_with_nested_structs/7.2.0_1647957600195/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_if_null_with_nested_structs/7.2.0_1647957600195/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_if_null_with_nested_structs/7.2.0_1647957600195/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/null.json

Addresses https://github.com/confluentinc/ksql/issues/8917

fix: Guard null struct dereferencing inside function calls

---

docs/developer-guide/ksqldb-reference/scalar-functions.md
docs/reference/sql/time.md

Fixes #8971.
Add note to time functions:

docs: add note about singular time units (DOCS-13323)

---

docs/reference/sql/time.md

* docs: add note about singlular time units (DOCS-13323)
* docs: add note to time functions on plural time units (DOCS-13323)
* docs: remove singular time units

docs: cherry-pick: add note about singular time units (DOCS-13570)

---

pom.xml

chore: fix surefire caused build failures

---

docs/operate-and-deploy/exactly-once-semantics.md

From https://github.com/confluentinc/ksql/pull/9064.

docs: cherry-pick: update EOS topic for v2 (DOCS-13604)

---

docs/requirements.txt

Per https://twitter.com/readthedocs/status/1507388916013314048.

docs: fix docs build break (DOCS-13605)

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

This is a port of @JimGalasyn 's https://github.com/confluentinc/ksql/pull/8906 to 0.25.1

docs: fix examples for new JSON functions (DOCS-13045) (#8906)

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udaf/sum/DecimalSumKudaf.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/KSqlFunctionClassifier.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/KsqlFunctionClassifier.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/KsqlFunctionClassifierTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/sum_-_sum_decimal_should_not_overflow_with_cast_to_higher_precision/7.3.0_1651526575310/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/sum_-_sum_decimal_should_not_overflow_with_cast_to_higher_precision/7.3.0_1651526575310/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/sum_-_sum_decimal_should_not_overflow_with_cast_to_higher_precision/7.3.0_1651526575310/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/sum.json

Throw KsqlFunctionException when a Decimal field overflows while using the sum udaf
Addresses https://github.com/confluentinc/ksql/issues/8707
Added unit and integration(QTT) tests

Fix sum udaf decimal overflow

---

ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintAssertNotExistsSchemaResult.approved.json
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintAssertNotExistsSchemaResult.approved.tabular
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintAssertSchemaResult.approved.json
ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.shouldPrintAssertSchemaResult.approved.tabular
ksqldb-functional-tests/src/test/resources/query-validation-tests/asserts.json
ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AssertResource.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AssertSchema.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/AssertTopic.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/AssertSchemaTest.java
ksqldb-parser/src/test/java/io/confluent/ksql/util/GrammarTokenExporterTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/AssertExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/AssertSchemaExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/AssertTopicExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/CustomExecutors.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/validation/CustomValidators.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/AssertSchemaExecutorTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/AssertSchemaEntity.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlEntity.java

Adds `ASSERT SCHEMA` command to ksqlDB. See discussion here: https://github.com/confluentinc/ksql/issues/8752
Manual, unit and integration

feat: add ASSERT SCHEMA statement

---

docs/reference/sql/time.md

From https://github.com/confluentinc/ksql/pull/8992.
* docs: add note about singlular time units (DOCS-13323)
* docs: add note to time functions on plural time units (DOCS-13323)
* docs: remove singular time units

docs: cherry-pick: add note about singular time units (DOCS-13571)

---

Jenkinsfile

This should enable the tooling to automatically trigger build
in cc-docker-ksql whenever we hit a green master commit in this
repository

feat: automatically build confluent cloud image on every master merge

---

docs/reference/serialization.md

This PR mentions the new `PROTOBUF_NOSR` format in serialization docs.

docs: Include PROTOBUF_NOSR in serialization docs

---

docs/reference/sql/data-definition.md

From https://github.com/confluentinc/ksql/pull/9109.

docs: cherry-pick: add missing pseudocolumns to DDL table (DOCS-13815)

---

docs/reference/sql/data-definition.md

From https://github.com/confluentinc/ksql/pull/9109.

docs: add missing pseudocolumns to DDL table (DOCS-13816)

---

docs/developer-guide/joins/join-streams-and-tables.md

From https://github.com/confluentinc/ksql/pull/9113.

docs: cherry-pick: update grace period description in join topic (DOCS-13817)

---

docs/developer-guide/joins/join-streams-and-tables.md

From https://github.com/confluentinc/ksql/pull/9113.

docs: cherry-pick: update grace period description in join topic (DOCS-13818)

---

docs/operate-and-deploy/capacity-planning.md

From https://github.com/confluentinc/ksql/pull/9116.

docs: cherry-pick: add notes about enabling bound memory usage (DOCS-13834)

---

ksqldb-engine/pom.xml
ksqldb-execution/pom.xml
ksqldb-rest-model/pom.xml
ksqldb-streams/pom.xml
pom.xml

Switch from confluent-log4j to reload4j

---

docs/developer-guide/ksqldb-clients/java-client.md
docs/developer-guide/ksqldb-reference/assert-schema.md
docs/developer-guide/ksqldb-reference/assert-topic.md
docs/developer-guide/ksqldb-reference/index.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/operate-and-deploy/migrations-tool.md
docs/reference/server-configuration.md
docs/reference/sql/appendix.md

docs for asserts! should cover changes in these commits:
#9107 
#9099 
#9091 
#9086 
#9066

docs: add documentation for asserts

---

pom.xml

Upgrade protobuf-java to version 3.19.4

chore: Upgrade protobuf-java to version 3.19.4

---

CHANGELOG.md

chore: add 0.26.0 changelog entries

---

ksqldb-engine/src/test/java/io/confluent/ksql/execution/ExpressionEvaluatorParityTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitorTest.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/planned/PlannedTestGeneratorTest.java
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_dereference_nested_structs_with_nulls/7.3.0_1652819920723/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_dereference_nested_structs_with_nulls/7.3.0_1652819920723/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_dereference_nested_structs_with_nulls/7.3.0_1652819920723/topology
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_log_no_errors_when_there_is_a_null_array/7.3.0_1652819920944/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_log_no_errors_when_there_is_a_null_array/7.3.0_1652819920944/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_log_no_errors_when_there_is_a_null_array/7.3.0_1652819920944/topology
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_log_no_errors_when_there_is_a_null_map/7.3.0_1652819920843/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_log_no_errors_when_there_is_a_null_map/7.3.0_1652819920843/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/null_-_log_no_errors_when_there_is_a_null_map/7.3.0_1652819920843/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/null.json

* Dereferencing a null struct no longer returns a null.
Addresses https://github.com/confluentinc/ksql/issues/9029.
* Calling subscripts on null maps/arrays no longer returns a null.
Addresses https://github.com/confluentinc/ksql/issues/9030
* Added a test to show that calling subscripts on a null map/array in a function call works properly.
Addresses https://github.com/confluentinc/ksql/issues/9031
Unit tests and QTTs have been added.

fix: Fixes a few null handling bugs

---

docs/reference/sql/data-types.md

docs: improve data-types.md clarity

---

design-proposals/README.md

docs: fix broken bootstapped-table-subs link

---

docs/developer-guide/ksqldb-reference/alter-system.md
docs/developer-guide/ksqldb-reference/index.md
docs/developer-guide/ksqldb-reference/quick-reference.md

docs: add page for the new ALTER SYSTEM command (DOCS-14391)

---

docs/developer-guide/joins/join-streams-and-tables.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/reference/sql/appendix.md

From https://github.com/confluentinc/ksql/pull/9002.

docs: cherry-pick: describe RIGHT JOIN in documentation (DOCS-14440)

---

docs/developer-guide/joins/join-streams-and-tables.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/reference/sql/appendix.md

From https://github.com/confluentinc/ksql/pull/9002.

docs: cherry-pick: describe RIGHT JOIN in documentation (DOCS-14441)

---

design-proposals/README.md

docs: intent for klip-66: multiple parameter udafs

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/9159.

docs: cherry-pick: link to 0.26.0 blog post in changelog topic (DOCS-14469)

---

docs/operate-and-deploy/high-availability.md
docs/reference/server-configuration.md
mkdocs.yml

Ported from https://github.com/confluentinc/ksql/pull/7696.

docs: add docs for high availability (DOCS-14472)

---

docs/operate-and-deploy/high-availability.md
docs/reference/server-configuration.md
mkdocs.yml

From https://github.com/confluentinc/ksql/pull/9178.

docs: cherry-pick: add docs for high availability (DOCS-14474)

---

docs/developer-guide/joins/partition-data.md

From https://github.com/confluentinc/ksql/pull/9188.

docs: cherry-pick: explain how to retain the key for PARTITION BY (DOCS-14514)

---

docs/reference/user-defined-functions.md

From https://github.com/confluentinc/ksql/pull/9198.

docs: cherry-pick: update UdfSchemaProvider method argument (DOCS-14577)

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlAuthTokenProvider.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlDefaultSecurityExtension.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlSecurityExtension.java
ksqldb-rest-app/pom.xml
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerEndpoints.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/AuthenticationUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/AuthTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/MockKsqlSecurityExtension.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/WSQueryEndpointTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/util/AuthenticationUtilTest.java
pom.xml

Check if a websocket connection has a JWT token. If it does, then close the connection when the timeout passes.
Manual + unit testing.

feat: close websocket connections with expired tokens

---

docs/developer-guide/joins/synthetic-keys.md

docs: typo

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/auth/AuthenticationPluginHandlerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/auth/KsqlAuthorizationProviderHandlerTest.java

used a deprecated method, also worker executor code was changed to use the three parameter version
ran the tests

chore: fix tests from bad merge

---

docs/operate-and-deploy/capacity-planning.md
docs/operate-and-deploy/how-it-works.md

Add info on behavior related to Command Topic in Confluent Cloud
N/A

Docs: Update info related to Command Topics in CC

---

docs/developer-guide/ksqldb-reference/operators.md
docs/how-to-guides/query-structured-data.md
docs/reference/sql/data-types.md

Update operators and data-types docs to include the `struct->*` syntax.

docs: add STRUCT dereference with * syntax

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksqldb-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java
ksqldb-parser/src/main/java/io/confluent/ksql/util/QueryMask.java
ksqldb-parser/src/test/java/io/confluent/ksql/util/QueryMaskTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/api/util/ApiServerUtils.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ConnectExecutor.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/util/CommandStoreUtil.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/util/ApiServerUtilsTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ConnectExecutorTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlRequest.java
ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/KsqlRequestTest.java

Backport https://github.com/confluentinc/ksql/pull/9263 to 5.5.x

fix: masked properties for create connector statement for 5.5.x

---

ksql-engine/src/main/java/io/confluent/ksql/services/DefaultConnectClient.java
ksql-parser/src/main/java/io/confluent/ksql/parser/DefaultKsqlParser.java
ksql-parser/src/main/java/io/confluent/ksql/util/QueryMask.java
ksql-parser/src/test/java/io/confluent/ksql/util/QueryMaskTest.java
ksql-rest-app/src/main/java/io/confluent/ksql/api/util/ApiServerUtils.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ConnectExecutor.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/CommandStoreUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/api/util/ApiServerUtilsTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ConnectExecutorTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
ksql-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlRequest.java
ksql-rest-model/src/test/java/io/confluent/ksql/rest/entity/KsqlRequestTest.java

Backport https://github.com/confluentinc/ksql/pull/9263 to 5.4.x

fix: masked properties for create connector statement for 5.4.x

---

CHANGELOG.md

chore: add 0.27.0 changelog entries

---

docs/developer-guide/ksqldb-clients/index.md
docs/developer-guide/ksqldb-clients/python-client-api/batched_query_result.html
docs/developer-guide/ksqldb-clients/python-client-api/client.html
docs/developer-guide/ksqldb-clients/python-client-api/exceptions.html
docs/developer-guide/ksqldb-clients/python-client-api/index.html
docs/developer-guide/ksqldb-clients/python-client-api/row.html
docs/developer-guide/ksqldb-clients/python-client-api/streamed_query_result.html
docs/developer-guide/ksqldb-clients/python-client-api/types/array_sql_type.html
docs/developer-guide/ksqldb-clients/python-client-api/types/basic_sql_type.html
docs/developer-guide/ksqldb-clients/python-client-api/types/column.html
docs/developer-guide/ksqldb-clients/python-client-api/types/decimal_sql_type.html
docs/developer-guide/ksqldb-clients/python-client-api/types/index.html
docs/developer-guide/ksqldb-clients/python-client-api/types/map_sql_type.html
docs/developer-guide/ksqldb-clients/python-client-api/types/schema.html
docs/developer-guide/ksqldb-clients/python-client-api/types/sql_type.html
docs/developer-guide/ksqldb-clients/python-client-api/types/sql_type_enum.html
docs/developer-guide/ksqldb-clients/python-client-api/types/struct_sql_type.html
docs/developer-guide/ksqldb-clients/python-client.md
mkdocs.yml

* docs: python client
* docs: add api docs
* Apply suggestions from code review
* Update docs/developer-guide/ksqldb-clients/python-client.md
* Rearrange API ref topic layout
* Add markup for bullet list

docs: cherry-pick: python client API reference (DOCS-15010)

---

docs/developer-guide/ksqldb-clients/dotnet-client.md
docs/developer-guide/ksqldb-clients/index.md
mkdocs.yml

Adds documentation for the new .NET client

docs: Adds documentation for the new .NET client

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/impl/ClientImplTest.java

We normally run this test on master which
follows the confluent platform versinoing scheme
(e.g. 7.3.0-123) and never has double digits
in the USER_AGENT string. On open source
release branches versions look like 0.27.0

bugfix: fix test for client USER_AGENT

---

ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/filters.sql

Follow up PR to https://github.com/confluentinc/ksql/pull/9141#discussion_r916237261

test: remove stale tests

---

ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/SqlToJavaVisitor.java
ksqldb-functional-tests/src/test/resources/historical_plans/json_records_-_extract_records_from_a_json_objects_nested/7.3.0_1658230979224/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/json_records_-_extract_records_from_a_json_objects_nested/7.3.0_1658230979224/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/json_records_-_extract_records_from_a_json_objects_nested/7.3.0_1658230979224/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/json_records.json

Addresses: https://github.com/confluentinc/ksql/issues/9313
Added a QTT.

fix: Allows functions which return maps to be dereferenced again.

---

pom.xml

Merge Conflict Resolution (from 5.4.x to 5.5.x)

---

pom.xml

Merge Conflict Resolution (from 7.0.x to 7.1.x)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java

chore: bump command topic version as part of 0.27 release

---

docs/reference/processing-log.md

From https://github.com/confluentinc/ksql/pull/9344.

docs:  cherry-pick: link to processing log tutorial in docs (DOCS-15331)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java

Cherry pick https://github.com/confluentinc/ksql/pull/9258 to release branch

chore: bump command topic version as part of 0.27 release (#9258)

---

docs/reference/processing-log.md
docs/reference/server-configuration.md

ksql.logging.processing.rows.include can be changed in CC by user while provisioning new ksqldb
Tested in UI. Attached below images.
Jira tickets:-
https://confluentinc.atlassian.net/browse/KCI-1715
https://confluentinc.atlassian.net/browse/KCI-1745
- [ X] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ X] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

Updated documentation for detailed processing log in KsqlDB.io project

---

docs/operate-and-deploy/capacity-planning.md

From https://github.com/confluentinc/ksql/pull/9355.

docs: cherry-pick: update # of partitions in output topic (DOCS-15346)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md

Adds a doc note for https://github.com/confluentinc/ksql/issues/9320:

docs: add note about calling UDAFs with * (DOCS-15335)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md

From https://github.com/confluentinc/ksql/pull/9348.

docs: cherry-pick: add note about calling UDAFs with * (DOCS-15388)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java

chore: bump command version after 0.28 release

---

ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCaseBuilderUtil.java

Just a minor refactor on the `TestCaseBuilderUtil.getAllTopics()` to make it simpler to understand.

refactor: minor refactor on TestCaseBuilderUtil.getAllTopics()

---

ksqldb-common/src/main/java/io/confluent/ksql/util/Quadruple.java
ksqldb-common/src/main/java/io/confluent/ksql/util/Quintuple.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/BaseAggregateFunction.java
ksqldb-engine/src/main/java/io/confluent/ksql/function/UdafTypes.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/FiveArgUdaf.java
ksqldb-engine/src/test/java/io/confluent/ksql/function/udaf/FourArgUdaf.java
ksqldb-functional-tests/src/test/resources/historical_plans/multi-arg-udaf_-_all_arguments_(five_cols)/7.3.0_1659473426328/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-arg-udaf_-_all_arguments_(five_cols)/7.3.0_1659473426328/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-arg-udaf_-_all_arguments_(five_cols)/7.3.0_1659473426328/topology
ksqldb-functional-tests/src/test/resources/historical_plans/multi-arg-udaf_-_all_arguments_(four_cols)/7.3.0_1659473424923/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-arg-udaf_-_all_arguments_(four_cols)/7.3.0_1659473424923/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/multi-arg-udaf_-_all_arguments_(four_cols)/7.3.0_1659473424923/topology
ksqldb-functional-tests/src/test/resources/query-validation-tests/multi-arg-udaf.json

Follow-up to #9361. Added support for creating UDAFs with four or five column arguments.
Added QTTs and two test UDAFs for four and five arguments.

feat: Add support for four and five column arguments to UDAFs

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/InsertValuesExecutorTest.java

When a user with insufficient permissions tries to execute an INSERT VALUES statement, they may hit a ClusterAuthorizationException from Kafka. ksqlDB has logic to catch this exception and wrap it in a more informative error message for the user. Turns out, the error message behavior from Kafka is inconsistent, in that sometimes a ClusterAuthorizationException wrapped in a KafkaException is thrown instead. Because ksqlDB only checks for a raw ClusterAuthorizationException, ksqlDB misses this case and the error message shown to the user is confusing. This PR adds a check for a ClusterAuthorizationException wrapped in a KafkaException, in order to provide a better error message.
See https://issues.apache.org/jira/browse/KAFKA-14138 for more about the inconsistent error message behavior in …

chore: better error message on wrapped ClusterAuthZException during inserts

---

docs/reference/metrics.md

From https://github.com/confluentinc/ksql/pull/9363.

docs: cherry-pick: add RockDB metrics (DOCS-15487)

---

docs/reference/metrics.md

From https://github.com/confluentinc/ksql/pull/9363.

docs: cherry-pick: add RockDB metrics (DOCS-15488)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/PreconditionChecker.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PreconditionCheckerIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/PreconditionCheckerTest.java

make sure to close clients from precondition checker
unit test + test in devel

fix: make sure to close clients from precondition checker

---

ksqldb-engine/src/main/java/io/confluent/ksql/internal/MetricsTagUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporter.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/ThroughputMetricsReporter.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/ThroughputMetricsReporterTest.java

* WIP
* checkstyle
* fix up storage utilization metrics tests
* update consumer member tag name after rebas to fix tests

fix: fix regex used to extract queryId from threadId metrics tag (#9394)

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/RuntimeAssignor.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/MetricsTagUtils.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporter.java
ksqldb-engine/src/main/java/io/confluent/ksql/internal/ThroughputMetricsReporter.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadataImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/engine/RuntimeAssignorTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/StorageUtilizationMetricsReporterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/internal/ThroughputMetricsReporterTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryBuilderTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplicationMetrics.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/PreconditionChecker.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PreconditionCheckerIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/PreconditionCheckerTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java

Cherry picks
1. https://github.com/confluentinc/ksql/pull/9393
1. https://github.com/confluentinc/ksql/pull/9388
1. https://github.com/confluentinc/ksql/pull/9392
1. https://github.com/confluentinc/ksql/pull/9391
1. https://github.com/confluentinc/ksql/pull/9394

fix: cherry pick a few commits for 0.28 release

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializationFunctionalTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImplTest.java

Signed-off-by: Walker Carlson <wcarlson@confluent.io>
Don't delete consumer groups by default

fix: Update default to not delete consumer groups

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryRegistryImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SandboxedSharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntime.java
ksqldb-engine/src/main/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImpl.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/UdfIntTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/materialization/ks/KsMaterializationFunctionalTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/query/QueryRegistryImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/BinPackedPersistentQueryMetadataImplTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/util/SharedKafkaStreamsRuntimeImplTest.java

https://github.com/confluentinc/ksql/pull/9408
https://github.com/confluentinc/ksql/pull/9410
https://github.com/confluentinc/ksql/pull/9407

fix: a couple of hotfixes

---

ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksql-engine/src/main/java/io/confluent/ksql/security/KsqlAuthTokenProvider.java
ksql-engine/src/main/java/io/confluent/ksql/security/KsqlDefaultSecurityExtension.java
ksql-engine/src/main/java/io/confluent/ksql/security/KsqlSecurityExtension.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
ksql-rest-app/src/main/java/io/confluent/ksql/rest/util/AuthenticationUtil.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/MockKsqlSecurityExtension.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
ksql-rest-app/src/test/java/io/confluent/ksql/rest/util/AuthenticationUtilTest.java

Backport #9147 to 5.4
It's a bit different because  the rest app code has changed quite a bit since 5.4.
Manually tested.

chore: terminate websockets on token timeout

---

ksqldb-common/src/main/java/io/confluent/ksql/util/QueryApplicationId.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java

turn off internal topic for transient queries so the cleaner can find them

fix: turn off internal topic for transient queries

---

Jenkinsfile

The Jenkins we use to build ksqlDB can have its Maven goals override/managed; this PR does that.

chore: Override Maven goals in Jenkins job.

---

docs/operate-and-deploy/high-availability-pull-queries.md
docs/operate-and-deploy/high-availability.md

Discussion: https://confluentcommunity.slack.com/archives/C6UJNMY67/p1658922529620649
Fixes https://github.com/confluentinc/ksql/issues/8256
Previewed the docs.

Adds documentation about combined HA and Authentication uses

---

ksqldb-common/src/main/java/io/confluent/ksql/util/QueryApplicationId.java
ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryBuilder.java

* fix: turn off internal topic for transient queries
* use constant

fix: turn off internal topic for transient queries (#9424)

---

docs/developer-guide/ksqldb-clients/java-client.md
docs/developer-guide/ksqldb-reference/index.md
docs/developer-guide/ksqldb-reference/pause.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/resume.md
docs/faq.md
docs/operate-and-deploy/how-it-works.md
docs/operate-and-deploy/migrations-tool.md
docs/reference/sql/appendix.md
ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/Client.java

Docs for https://github.com/confluentinc/ksql/pull/9203

docs: Documentation for Pause/Resume functionality.

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryCleanupService.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandRunner.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandRunnerTest.java

fix: Do not clean up when in degraded mode

---

docs/concepts/time-and-windows-in-ksqldb-queries.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md
docs/developer-guide/ksqldb-reference/quick-reference.md
docs/developer-guide/ksqldb-reference/select-push-query.md
docs/reference/server-configuration.md
docs/reference/sql/appendix.md

From https://github.com/confluentinc/ksql/pull/9459.

docs: cherry-pick: restore docs for EMIT FINAL syntax (DOCS-15927)

---

CHANGELOG.md
docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/9377.
* chore: add 0.28.2 changelog
* fix: comments
* fix: comment

chore: cherry-pick: add 0.28.2 changelog (DOCS-16163)

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

From https://github.com/confluentinc/ksql/pull/9471.

docs: cherry-pick: add note about BIGINT millisecond param to FORMAT_TIMESTAMP topic (DOCS-16743)

---

docs/developer-guide/ksqldb-reference/scalar-functions.md

From https://github.com/confluentinc/ksql/pull/9471.

docs: cherry-pick: add note about BIGINT millisecond param to FORMAT_TIMESTAMP topic (DOCS-16744)

---

docs/developer-guide/ksqldb-reference/aggregate-functions.md
docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/9486.

docs: cherry-pick: document specific limits for CC COLLECT_SET (DOCS-16839)

---

docs/how-to-guides/create-a-user-defined-function.md
docs/reference/user-defined-functions.md

Adds user documentation for the changes in #9361, #9451, and #9481 to the [UDF reference](https://docs.ksqldb.io/en/latest/reference/user-defined-functions/) and [how-to guide](https://docs.ksqldb.io/en/latest/how-to-guides/create-a-user-defined-function/).
N/A

docs: Add user docs for multi-arg and variadic UDAFs

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md

Docs for RETENTION_MS config in the WITH clause while creating streams/tables
Related PR - https://github.com/confluentinc/ksql/pull/9223

docs: Update docs with RETENTION_MS config for stream/table

---

release_stabilization.py

This reverts commit 522af267346e85e59cf8c9310a31a42506a53496.

Revert "Update release_stabilization.py"

---

release_stabilization.py

This reverts commit c5d5f00136bbd2c7286a8ff65ced3c5c72e962cf.

Revert "Revert "Update release_stabilization.py" (#9501)"

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/KsqlEngine.java
ksqldb-engine/src/main/java/io/confluent/ksql/engine/SandboxedExecutionContext.java

I audited the ff uses and replaced all the ones I could with the query type rather than the config value so we check query type rather than the config.

fix: don't confuse flag on with old queries

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/PullQueryWriteStream.java

moves the 
```java
if (isDone()) {
return;
}
```
block into the monitor, so that other threads don't enter the queuing process before checking `isDone()`. 
Also made incrementing the counter conditional on successful queuing since that is the right thing to do

fix: avoid race in PullQueryWriteStream

---

docs/developer-guide/ksqldb-clients/python-client-api/batched_query_result.html
docs/developer-guide/ksqldb-clients/python-client-api/client.html
docs/developer-guide/ksqldb-clients/python-client-api/exceptions.html
docs/developer-guide/ksqldb-clients/python-client-api/index.html
docs/developer-guide/ksqldb-clients/python-client-api/row.html
docs/developer-guide/ksqldb-clients/python-client-api/streamed_query_result.html
docs/developer-guide/ksqldb-clients/python-client-api/types/array_sql_type.html
docs/developer-guide/ksqldb-clients/python-client-api/types/basic_sql_type.html
docs/developer-guide/ksqldb-clients/python-client-api/types/column.html
docs/developer-guide/ksqldb-clients/python-client-api/types/decimal_sql_type.html
docs/developer-guide/ksqldb-clients/python-client-api/types/index.html
docs/developer-guide/ksqldb-clients/python-client-api/types/map_sql_type.html
docs/developer-guide/ksqldb-clients/python-client-api/types/schema.html
docs/developer-guide/ksqldb-clients/python-client-api/types/sql_type.html
docs/developer-guide/ksqldb-clients/python-client-api/types/sql_type_enum.html
docs/developer-guide/ksqldb-clients/python-client-api/types/struct_sql_type.html

Reflects changes to minor refactoring (name changes) in the python client.
The docs are generated using `pdoc3 --html ksqldb` from within the root of the python client directory

docs: update python client API reference

---

ksqldb-engine/src/main/java/io/confluent/ksql/query/PullQueryWriteStream.java

cherry-pick 34fbf87d26571a629fc10a263cb798a8f7e7f260

fix: avoid race in PullQueryWriteStream (#9537)

---

docs/developer-guide/ksqldb-clients/java-client.md
ksqldb-api-client/pom.xml

Addresses https://github.com/confluentinc/ksql/issues/7470 and https://github.com/confluentinc/ksql/issues/9245.
I have tested locally with some example Java client code.

fix: Add shaded jar for java-client and document its use

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/CommandTopicMigrationUtil.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java

minor change to add more logging in the migration code

chore: add more logging to command topic migration code

---

bin/ksql-run-class

Switch to G1 garbage collector so that 7.3+ can work with Java 17.
Tested manually

chore: upgrade garbage collector to g1

---

docs/developer-guide/ksqldb-clients/python-client.md

adds some minor info and steps. Changes pip command to `pip install confluent-ksqldb` as the package name has been changed.

docs: add links to github and pypi for py client

---

docs/developer-guide/ksqldb-clients/python-client.md

cherry-pick e162eb8c97019b3e5b001cdefda063108682b5b0

docs: add links to github and pypi for py client (#9565)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/RestoreCommandTopicIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/AuthorizationFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ClusterTerminationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/HeartbeatAgentFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/LagReportingAgentFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ScalablePushQueryFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeWithTlsFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TerminateTransientQueryFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TransientQueryResourceCleanerIntTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
pom.xml

This should speed up tests quite a bit.  Next steps will be to do similar changes to remaining integration tests.

test: Makes tests under rest/integration/ run in parallel

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java

See the comment in the PR itself. We were already aware that this test had the potential for race condition, but we didn't handle the possibility properly. (As written, the test still fails under the race condition because assertThatEventually() breaks when it encounters an exception.)

test: fix flaky ConnectIntegrationTest.shouldDescribeConnector()

---

CHANGELOG.md

fix: link fix

---

docs/operate-and-deploy/high-availability-pull-queries.md

From https://github.com/confluentinc/ksql/pull/9647.

docs: cherry-pick: fix broken link in high availability topic (KSQL-9421)

---

docs/operate-and-deploy/high-availability-pull-queries.md

From https://github.com/confluentinc/ksql/pull/9647.

docs: cherry-pick: fix broken link in high availability topic (KSQL-9422)

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/StreamQueryResponseHandler.java

Follow-up to https://github.com/confluentinc/ksql/pull/9645 to port the fix to the streaming client.

fix: remove spurious consistency error message (2)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java

chore: bump command topic version number as part of 0.29 release

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/9654.

docs: cherry-pick: link to 0.28.2 blog post in changelog topic (DOCS-18473)

---

docs/operate-and-deploy/changelog.md

From https://github.com/confluentinc/ksql/pull/9654.

docs: cherry-pick: link to 0.28.2 blog post in changelog topic (DOCS-18474)

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/udf/string/Uuid.java

Fix checkstyle error(`Line is longer than 100 characters`) in `Uuid.java`
Checkstyle validation passed in my IDE after the fix

style: fix checkstyle error - Line is longer than 100 characters

---

docs/reference/serialization.md

From https://github.com/confluentinc/ksql/pull/9671.

docs: cherry-pick: add section for per-format schema syntax (DOCS-18667)

---

docs/reference/serialization.md

From https://github.com/confluentinc/ksql/pull/9671.

docs: cherry-pick: add section for per-format schema syntax (DOCS-18668)

---

CONTRIBUTING.md

Add instructions how to speed up builds significantly

chore: add instructions to speed up builds

---

ksqldb-api/pom.xml

bump vert.x to 3.9.14 and netty to 4.1.84.Final.
output of `mvn dependency:tree -Dincludes=io.netty:netty-codec-http`
```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 12.6
[INFO] os.detected.version.major: 12
[INFO] os.detected.version.minor: 6
[INFO] os.detected.classifier: osx-x86_64
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ksqldb-parent                                                      [pom]
[INFO] …
```

chore: bump vert.x to 3.9.14 and netty to 4.1.84.Final

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryLimitHARoutingTest.java

Disables PullQueryLimitHARoutingTest since it's flaky

Disables PullQueryLimitHARoutingTest since it's flaky

---

ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619816138/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619816138/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619816138/topology
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_key_and_optional_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619804048/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_key_and_optional_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619804048/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_key_and_optional_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619804048/topology
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_key_and_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619815871/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_key_and_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619815871/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_explicit_key_and_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619815871/topology
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_optional_key_and_explicit_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619815987/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_optional_key_and_explicit_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619815987/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_optional_key_and_explicit_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619815987/topology
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_optional_key_and_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619815198/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_optional_key_and_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619815198/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/formats_-_optional_key_and_value_format_-_ksql.new.query.planner.enabled=true/0.28.3_1667619815198/topology
ksqldb-functional-tests/src/test/resources/historical_plans/select_-_all_columns_-_star_-_ksql.new.query.planner.enabled=true/0.28.3_1667619937577/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/select_-_all_columns_-_star_-_ksql.new.query.planner.enabled=true/0.28.3_1667619937577/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/select_-_all_columns_-_star_-_ksql.new.query.planner.enabled=true/0.28.3_1667619937577/topology

Fixes PlannedTestsUpToDateTest tests in 0.28.3-cc-docker-ksql.129.x

Fixes PlannedTestsUpToDateTest tests in 0.28.3-cc-docker-ksql.129.x

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/restore/KsqlRestoreCommandTopic.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/RestoreCommandTopicIntegrationTest.java

fix: null check of query plan when restoring

---

docs/how-to-guides/test-an-app.md

replace documentation for the old test runner with the new test runner

docs: add docs for yatt

---

ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null/7.4.0_1668008700948/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null/7.4.0_1668008700948/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null/7.4.0_1668008700948/topology
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_optional/7.4.0_1668008701004/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_optional/7.4.0_1668008701004/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_optional/7.4.0_1668008701004/topology
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_wrapper/7.4.0_1668008701047/plan.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_wrapper/7.4.0_1668008701047/spec.json
ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_wrapper/7.4.0_1668008701047/topology

Add missing historical plans.
Tested by CI.

chore: fix QTT historical plans

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlStatementException.java
ksqldb-engine/src/main/java/io/confluent/ksql/execution/scalablepush/PushRouting.java

chore: use QueryLogger to log queries, part 3

---

ksqldb-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
ksqldb-engine/src/test/java/io/confluent/ksql/execution/ExpressionEvaluatorParityTest.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/codegen/CodeGenRunner.java
ksqldb-execution/src/main/java/io/confluent/ksql/execution/util/ExpressionTypeManager.java
ksqldb-execution/src/test/java/io/confluent/ksql/execution/util/ExpressionTypeManagerTest.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/CommandStore.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/CommandStoreTest.java

chore: Use QueryLogger to log queries, part 4

---

ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/KsqlRequest.java

cherry-pick one more fix that was applied to the release branch, but not master.

chore: Use QueryLogger to log queries, part 5

---

docs/how-to-guides/test-an-app.md
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/KsqlTestingTool.java
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/tools/KsqlTestingToolTest.java

Feature return tests result code

---

docs/developer-guide/ksqldb-reference/insert-into.md

Add missing information into documentation about QUERY_ID properties into INSERT.

QUERY_ID into insert statement docs

---

pom.xml

Merge Conflict Resolution (from 7.4.x to master)

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/RecordFormatterTest.java
pom.xml

cf https://github.com/confluentinc/ksql/pull/9772

chore: Resolved updated dependencies.

---

docs/overrides/main.html

From https://github.com/confluentinc/ksql/pull/9774.

docs: cherry-pick: Add metatag for Zendesk search crawler (DOCS-22032)

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/auth/DefaultApiSecurityContext.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/ShowQueriesMultiNodeFunctionalTest.java

fix: default to get authHeader if using basic

---

Jenkinsfile

Backport https://github.com/confluentinc/ksql/pull/9825 to 7.2.x.
N/A

Update Jenkinsfile Nodelabel (#9825)

---

docs/overrides/main.html

From https://github.com/confluentinc/ksql/pull/9774.
Related: https://github.com/confluentinc/ksql/pull/9778.

docs: cherry-pick metatag for Zendesk search crawler to (new) live branch (DOCS-22880)

---

ksqldb-engine/pom.xml

hotfix: unpin version dependency

---

docs/overrides/partials/copyright.html

From https://github.com/confluentinc/ksql/pull/9847.

docs: cherry-pick: change docs feedback alias for legacy versions (DOCS-22945)

---

docs/overrides/partials/copyright.html

From https://github.com/confluentinc/ksql/pull/9847.

docs: cherry-pick: change docs feedback alias for legacy versions (DOCS-22976)

---

ksqldb-api-client/src/main/java/io/confluent/ksql/api/client/impl/DdlDmlRequestValidators.java

The regex we use for extracting SQL strings and identifiers has the catastrophic backtracking, meaning that it'll have to try O(2^n) combinations on the some inputs.
This patch fixes the issue by slightly simplifying the pattern.
Reproduce the issue by opening https://regex101.com/ and using the original `QUOTED_STRING_OR_IDENTIFIER` as a pattern and `'&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&` as input. The expected output is `Catastrophic backtracking has been detected and the execution of your expression has been halted.` on the right side of the screen.
Verify that the new `QUOTED_STRING_OR_IDENTIFIER` does not have this issue by replacing the pattern with the new one.

fix: Simplify regex in DdlDmlRequestValidators to avoid catastrophic backtracking

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java

Add config to control if we should pass client ip/port to kafka client
Unit test

chore: [2/N][client_ip] add config to control if we should pass client ip/port

---

pom.xml

To fix CVE-2023-24815: io.vertx_vertx-web in ksql
```
➜  ksql git:(master) ✗ mvn dependency:tree -Dincludes=io.vertx
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.bitness: 64
[INFO] os.detected.version: 11.3
[INFO] os.detected.version.major: 11
[INFO] os.detected.version.minor: 3
[INFO] os.detected.classifier: osx-x86_64
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] ksqldb-parent …
```

chore: bump vertx to 4.3.8

---

docs/concepts/time-and-windows-in-ksqldb-queries.md

From https://github.com/confluentinc/ksql/pull/9901.

docs: cherry-pick: fix typos in example code (DOCS-6713) (#9901)

---

ksqldb-docker/README.md

docs: update ksqldb-docker mvn image build cmd to include settings file

---

docs/reference/processing-log.md

From https://github.com/confluentinc/ksql/pull/9906.

docs: cherry-pick: note that users can't change the processing log level (DOCS-23899)

---

docs/requirements.txt

From https://github.com/confluentinc/ksql/pull/9911.

docs: cherry-pick: upgrade pymdown-extensions and Pygments version (DOCS-24135)

---

docs/developer-guide/ksqldb-clients/java-client.md

From https://github.com/confluentinc/ksql/pull/9916.

docs: cherry-pick: use https for repository (DOCS-24145)

---

docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md

From https://github.com/confluentinc/ksql/pull/9499.

docs: cherry-pick RETENTION_MS sections to live branch (DOCS-24158)

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md

From https://github.com/confluentinc/ksql/pull/9931.

docs: cherry-pick: update RETENTION_MS description with details (DOCS-24158)

---

docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md

From https://github.com/confluentinc/ksql/pull/9935.

docs: cherry-pick: update CS and CTAS ref topics with RETENTION_MS details (DOCS-24190)

---

docs/overrides/partials/copyright.html

From https://github.com/confluentinc/ksql/pull/9847.

DOCS-22944 - Change docs feedback alias for legacy versions (#9848)

---

docs/overrides/partials/copyright.html

docs: change docs feedback alias for legacy versions (DOCS-22944)

---

docs/requirements.txt

From https://github.com/confluentinc/ksql/pull/9911.

docs: cherry-pick: upgrade pymdown-extensions and Pygments version (DOCS-24136)

---

docs/concepts/time-and-windows-in-ksqldb-queries.md

From https://github.com/confluentinc/ksql/pull/9901.

docs: cherry-pick: fix typos in example code (DOCS-23788)

---

docs/reference/processing-log.md

From https://github.com/confluentinc/ksql/pull/9906.

docs: cherry-pick: note that users can't change the processing log level (DOCS-23900)

---

docs/developer-guide/ksqldb-clients/java-client.md

From https://github.com/confluentinc/ksql/pull/9916.

docs: cherry-pick: use https for repository (DOCS-24146)

---

docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md

From https://github.com/confluentinc/ksql/pull/9935.

docs: cherry-pick: update CS and CTAS ref topics with RETENTION_MS details (DOCS-24189) 

---

ksqldb-rocksdb-config-setter/pom.xml
ksqldb-rocksdb-config-setter/src/main/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBConfig.java
ksqldb-rocksdb-config-setter/src/main/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBConfigSetter.java
ksqldb-rocksdb-config-setter/src/test/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBConfigSetterTest.java
ksqldb-rocksdb-config-setter/src/test/java/io/confluent/ksql/rocksdb/KsqlBoundedMemoryRocksDBConfigTest.java

feat: expose compaction and compression configs for RocksDB

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md

From https://github.com/confluentinc/ksql/pull/9962.

docs: cherry-pick: remove statement about join queries in CSAS and CTAS topics (DOCS-24283)

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md

From https://github.com/confluentinc/ksql/pull/9965.
* docs: clarify RETENTION_MS in CSAS and CTAS topics (DOCS-24322)
* add code markdown; remove table from CTAS note

docs: cherry-pick: clarify RETENTION_MS in CSAS and CTAS topics (DOCS-24324)

---

docs/developer-guide/ksqldb-reference/create-stream-as-select.md
docs/developer-guide/ksqldb-reference/create-stream.md
docs/developer-guide/ksqldb-reference/create-table-as-select.md

From https://github.com/confluentinc/ksql/pull/9965.
* docs: clarify RETENTION_MS in CSAS and CTAS topics (DOCS-24322)
* add code markdown; remove table from CTAS note

docs: cherry-pick: clarify RETENTION_MS in CSAS and CTAS topics (DOCS-24325)

---

pom.xml

update Jetty to the latest version to address CVEs

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutor.java

hotfix: Do not log commands on failed start up.

---

docs/operate-and-deploy/migrations-tool.md

Adds troubleshooting note for https://github.com/confluentinc/ksql/issues/9985.

docs: note auth failure in migration tool troubleshooting section (DOCS-24447)

---

docs/operate-and-deploy/migrations-tool.md

From https://github.com/confluentinc/ksql/pull/9988.
Adds troubleshooting note for https://github.com/confluentinc/ksql/issues/9985.

docs: cherry-pick: note auth failure in migration tool troubleshooting section (DOCS-24448)

---

docs/developer-guide/ksqldb-reference/alter-system.md
docs/reference/server-configuration.md
mkdocs.yml

From https://github.com/confluentinc/ksql/pull/9995.

docs: cherry-pick: update ALTER SYSTEM description (DOCS-24479)

---

docs/reference/serialization.md

Add a Known Limitations section:

docs: document limitation for ksqlDB JSON serialization (DOCS-24871)

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/10041.

docs: cherry-pick: update replica configs for -1 value (DOCS-24989)

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedKafkaTopicClient.java
ksqldb-engine/src/main/java/io/confluent/ksql/statement/InjectorChain.java
ksqldb-engine/src/main/java/io/confluent/ksql/statement/InjectorWithSideEffects.java
ksqldb-engine/src/main/java/io/confluent/ksql/topic/TopicCreateInjector.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/FakeKafkaTopicClient.java
ksqldb-execution/src/main/java/io/confluent/ksql/services/KafkaTopicClient.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/DistributingExecutor.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java
ksqldb-testing-tool/src/main/java/io/confluent/ksql/tools/test/stubs/StubKafkaTopicClient.java

fix: delete created Kafka if the corresponding command fails

---

.readthedocs.yml

From https://github.com/confluentinc/ksql/pull/10051.

docs: cherry-pick: update docs build to use build.os config key (DOCS-25081)

---

docs/reference/serialization.md

Updates https://github.com/confluentinc/ksql/pull/10036.

docs: clarify limitation for ksqlDB JSON serialization (DOCS-24871)

---

docs/reference/serialization.md

From https://github.com/confluentinc/ksql/pull/10056.

docs: cherry-pick: clarify limitation for ksqlDB JSON serialization (DOCS-25127)

---

docs/reference/server-configuration.md

docs: update ksql.streams.cache.max.bytes.buffering config for CP (DOCS-25215)

---

docs/reference/server-configuration.md

From https://github.com/confluentinc/ksql/pull/10062.

docs: cherry-pick: update ksql.streams.cache.max.bytes.buffering config for CP (DOCS-25220)

---

ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java

fix: import not picked back in fix

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java

Merge Conflict Resolution (from 7.3.x to 7.4.x)

---

docs/reference/sql/syntax/lexical-structure.md

From https://github.com/confluentinc/ksql/pull/10106.

docs: cherry-pick: note that CCloud UI does not handle comment block syntax (DOCS-26070)

---

ksqldb-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlAvroSerializerTest.java

There was some changes in SR (Oct/13/2023) that broke ksql build.

MINOR: fix broken build

---

ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/materialization/ks/KsLocator.java

When shutting down queries, we encounter an IllegalStateException when running pull queries. This happens temporarily for ~1s while shutting down the node, and the request should be retried. Return the same error that we also use for unavailable metadata here, which asks the client to retry.

fix: return retryable error during shutdown

---

ksqldb-common/src/test/java/io/confluent/ksql/util/VertxSslOptionsFactoryTest.java

This PR fixes a unit test according to the latest changes in code.

Test: fix fips unit test

---

ksqldb-test-util/pom.xml
pom.xml

Upstream ZK version bump, requires to add new dependency.

chore: fix broken build setup

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/SystemAuthenticationFunctionalTest.java

chore: change ksql service id in test to make logs clearer

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/SystemAuthenticationFunctionalTest.java

Merge Conflict Resolution (from 6.2.x to 7.0.x)

---

pom.xml

like https://github.com/confluentinc/cc-docker-connect/blob/668bcf27d7d401fae33030ca92f8f290d53bd204/cc-delegating-connectors-service/delegating-rest-extension/pom.xml#L34

chore: bump heap size to fix broken test

---

pom.xml

Exclude logback dependency inherited from ZooKeeper

chore: fix pom

---

.semaphore/project.yml
.semaphore/semaphore.yml
Jenkinsfile
pom.xml
service.yml

Jenkins migration to semaphore.
This is the same as the autogenerated PR https://github.com/confluentinc/ksql/pull/10102/files
But targeted to 6.2.x branch onwards 
https://docs.confluent.io/platform/current/installation/versions-interoperability.html

KSE-1786 | Migration: Jenkins -> Semaphore

---

docs/overrides/partials/copyright.html

From https://github.com/confluentinc/ksql/pull/10187.

docs: cherry-pick: update hardcoded copyright year in footer with script (DOCS-26837)

---

Jenkinsfile
pom.xml

KSE-1786 | Enable pinned nanoversions.

---

.semaphore/project.yml
.semaphore/semaphore.yml
Jenkinsfile
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StatusResourceTest.java
service.yml

Pint merge from https://github.com/confluentinc/ksql/pull/10173

KSE-1786 | Migration: Jenkins -> Semaphore (7.0.x)

---

.semaphore/project.yml
.semaphore/semaphore.yml
Jenkinsfile
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StatusResourceTest.java
pom.xml
service.yml

KSE-1786 | Migration: Jenkins -> Semaphore (7.1.x)

---

docs/operate-and-deploy/capacity-planning.md

From https://github.com/confluentinc/ksql/pull/10208.

docs: cherry-pick: update recommended RAM to 16GB (DOCS-27495)

---

docs/developer-guide/joins/join-streams-and-tables.md

docs: add limitation for N-way joins (DOCS-27519)

---

docs/developer-guide/joins/join-streams-and-tables.md

From https://github.com/confluentinc/ksql/pull/10213.

docs: cherry-pick: add limitation for N-way joins (DOCS-27529)

---

pom.xml

MINOR: Pinned the common nanoversion to 7.6.1-3

---

pom.xml

Update commons-io
Resolve CVE
Existing testing

KSE-1817: Update apache.io.version

---

pom.xml

KSE-1816: Update Commons-Compress and commons-io

---

.semaphore/semaphore.yml
ksqldb-rest-app/pom.xml

Exclude kotlin std lib test dependency, fix maven caching in semaphore jobs.

Exclude kotlin std lib test dependency, fix maven caching in semaphore jobs.

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
pom.xml

[KSE-1820] | Vedarth Sharma | Fixes ksql build failures

---

.semaphore/semaphore.yml
ksqldb-rest-app/pom.xml

Apply changes from 7.2.x https://github.com/confluentinc/ksql/pull/10259/files

Exclude transitive test dependency for kotlin-stdlib. Fixed maven caching in semaphore jobs.

---

service.yml

add service.yml file so the config can be read by service-bot

add service.yml file

---

pom.xml

[KSQL-12016] | Vedarth Sharma | Use latest available nanoversion for common

---

pom.xml

Fixes common package version in pom

[KSQL-12027] | Vedarth Sharma | Update common version in pom (7.7.x)

---

pom.xml

[KSQL-12005] | Vedarth Sharma | Fix schema registry version

---

ksqldb-functional-tests/src/test/resources/query-validation-tests/fk-join.json
pom.xml

Fixes functionality tests for 7.7.x

[KSQL-12061] Fix functionality tests and upgrade common version

---

docs/developer-guide/ksqldb-reference/create-stream.md

From https://github.com/confluentinc/ksql/pull/10286.

docs: cherry-pick: Update create-stream.md (DOCS-28312)

---

docs/operate-and-deploy/how-it-works.md

To partially (or temporarily) fix https://github.com/confluentinc/ksql/issues/5625.
no

Add docs for connector

---

docs/operate-and-deploy/how-it-works.md

From https://github.com/confluentinc/ksql/pull/10268.

docs: cherry-pick: add docs for connector (DOCS-28344)

---

pom.xml

[KSQL-12104] | Vedarth Sharma | Fix 7.6.x build

---

pom.xml

[KSE-1831] | Vedarth Sharma | Update netty version to stable one

---

pom.xml

[KSQL-12104] | Vedarth Sharma | Fix 7.5.x build

---

pom.xml

(cherry picked from commit 0c284c3db573673de5bc942e2d44bd30e4e89daa)

[KSE-1831] | Vedarth Sharma | Update netty version to stable one 

---

Jenkinsfile
pom.xml

[KSQL-12107] | Vedarth Sharma | Migrate 6.2.x to ranges

---

Jenkinsfile
pom.xml

[KSQL-12107] | Vedarth Sharma | Migrate 7.0.x to ranges

---

Jenkinsfile
pom.xml

[KSQL-12107] | Vedarth Sharma | Migrate 7.1.x to ranges

---

Jenkinsfile
pom.xml

[KSQL-12107] | Vedarth Sharma | Migrate 7.4.x to ranges

---

Jenkinsfile
pom.xml

[KSQL-12107] | Vedarth Sharma | Migrate 7.5.x to ranges

---

Jenkinsfile
pom.xml

[KSQL-12107] | Vedarth Sharma | Migrate to 7.6.x to ranges

---

Jenkinsfile
ksqldb-common/pom.xml
ksqldb-examples/pom.xml
ksqldb-rest-app/pom.xml
ksqldb-serde/pom.xml
pom.xml

[KSQL-12107] | Vedarth Sharma | Migrate master to ranges

---

Jenkinsfile
pom.xml

[KSQL-12107] | Vedarth Sharma | Migrate 7.2.x to ranges

---

Jenkinsfile
pom.xml

[KSQL-12107] | Vedarth Sharma | Migrate 7.3.x to ranges

---

Jenkinsfile
ksqldb-common/pom.xml
ksqldb-examples/pom.xml
ksqldb-rest-app/pom.xml
ksqldb-serde/pom.xml
pom.xml

[KSQL-12107] | Vedarth Sharma | Migrate 7.7.x to ranges

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TransientQueryResourceCleanerIntTest.java

 [KSQL-12110] | Check if directory exists before cleanup 7.3.x

---

.semaphore/semaphore.yml
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TransientQueryResourceCleanerIntTest.java
pom.xml

[KSQL-12110] | Vedarth Sharma | Check if directory exists before cleanup 7.4.x

---

ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

[KSQL-12135] | Vedarth Sharma | Move private kafka configs inside ksql

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/TransientQueryResourceCleanerIntTest.java

[KSQL-12110] | Vedarth Sharma | Check if directory exists before cleanup 7.2.x

---

pom.xml

KSE-1829 | Fix CVE for janino dependency.

KSE-1829 | Fix CVE for janino dependency.

---

ksqldb-api-client/pom.xml

Cherry picks https://github.com/confluentinc/ksql/pull/10332

KSQL-12154: Update plugin version(cherry picks #10332)

---

pom.xml

KSE-1832 | CVE fix for vertx dependency. 

KSE-1832 | CVE fix for vertx dependency.

---

ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java

[KSQL-12187] | Vedarth Sharma | Migrate configs to ksql repo

---

pom.xml

Apply https://github.com/confluentinc/ksql/pull/10349 from v7.0.x onwards.

MINOR: Update snapshot URLs.

---

pom.xml

Update jackson components version to reflect upgraded version in ce-kafka. 
Track version from common pom

remove jackson pin to update jackon to version specified in common 

---

.mvn/wrapper/maven-wrapper.properties

Update ref to confluent-packaging-tools

---

.semaphore/semaphore.yml

CPBR-1261: add cp-jar-build tasks when running pr workflows

---

ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

This is related to https://github.com/confluentinc/ce-kafka/pull/15279 PR.

MINOR: Fix compilation failures due to kafka changes

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryRoutingFunctionalTest.java

KSQL-12326: Fix ksql build failure

---

ksqldb-api-client/pom.xml

Fix ksqldb api client behaviour for streaming responses
Tested locally

[KSQL-12245] | Vedarth Sharma | Add kafka streams dependency on ksqldb api client

---

pom.xml

Opening PR on behalf of ksql team.
CC: @kagarwal06

KSQL-12349: Use range version instead of pinned nano-versions

---

ksqldb-engine/pom.xml

Unpin version of classgraph dependency to use the version defined in common

KSE-1845: unpin classgraph dependency to use the version defined in common  (CP-7-7-0-cp1)

---

CONTRIBUTING.md

This is a test PR that fixes a typo in the ReadME

MINOR: Fix typo (#1)

---

ksqldb-engine/pom.xml

Reverts https://github.com/confluentinc/ksql/pull/10373

(Revert)KSE-1845: unpin classgraph dependency (#2)

---

ksqldb-engine/pom.xml

KSE-1845: Unpin version and use version from common 

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/PullBandwidthThrottleIntegrationTest.java

KSQL-12379: Ignore pullStreamBandwidthThrottleTest-7.3.x

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/PullBandwidthThrottleIntegrationTest.java

KSQL-12379: Ignore pullStreamBandwidthThrottleTest-7.4.x

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/api/integration/PullBandwidthThrottleIntegrationTest.java

KSQL-12379: Ignore pullStreamBandwidthThrottleTest-7.5.x

---

.semaphore/semaphore.yml
service.yml

Increase time limit for the pipeline

[KSQL-12386] | Vedarth Sharma | Increase time limit for the pipeline

---

ksqldb-api-client/pom.xml

Package Kafka Streams in ksqldb api client to fix the client behaviour
Tested locally

[KSQL-12245] | Vedarth Sharma | Package kafka streams in api client

---

ksqldb-common/src/main/java/io/confluent/ksql/metrics/MetricAppender.java
ksqldb-common/src/main/java/io/confluent/ksql/metrics/MetricCollectors.java
ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/KafkaEmbedded.java

Fix the ref in the class MetricCollectors, MetricAppender.

KSQL-12387 | SystemTime is refactored to a singleton class. Fix the ref in the class MetricCollectors, MetricAppender.

---

ksqldb-cli/src/test/java/io/confluent/ksql/cli/SslClientAuthFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/api/CorsTest.java
ksqldb-rest-client/src/test/java/io/confluent/ksql/rest/client/KsqlClientTest.java
pom.xml

This PR reverts the PR: https://github.com/confluentinc/ksql/pull/10408

Revert vertx CVE upgrade

---

ksqldb-engine/pom.xml

KSE-1845: Use classgraph version from the common of 7.7.0-cp2 (#64)

---

.gitignore
CONTRIBUTING.md
README.md
bin/ksql-run-class
docker-compose.yml
ksqldb-docker/README.md

Added code for debugging ksql server
**Not Required**

KSQL-12422: Added Debug Capability and Updated ReadMe

---

ksqldb-functional-tests/src/test/resources/historical_plans/protobuf_-_protobuf_primitives_with_null_and_nullable_as_optional/7.4.0_1668008701004/spec.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/protobuf.json
ksqldb-version-metrics-client/src/test/java/io/confluent/support/metrics/utils/WebClientTest.java

Adjust the test assertion for SR changes in protobuf classes.
Unit tests

KSQL-12515 | Remove [deprecated = false] from the test assertion.

---

ksqldb-api-client/pom.xml
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientOAuthTest.java
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/util/IdentityProviderService.java
ksqldb-common/src/test/java/io/confluent/ksql/security/BasicCredentialsTest.java
ksqldb-common/src/test/java/io/confluent/ksql/security/CredentialsFactoryTest.java
ksqldb-common/src/test/java/io/confluent/ksql/security/oauth/CachedOAuthTokenRetrieverTest.java
ksqldb-common/src/test/java/io/confluent/ksql/security/oauth/IdpConfigTest.java
ksqldb-common/src/test/java/io/confluent/ksql/security/oauth/OAuthBearerCredentialsTest.java
ksqldb-common/src/test/java/io/confluent/ksql/security/oauth/OAuthTokenCacheTest.java
ksqldb-tools/src/test/java/io/confluent/ksql/tools/migrations/util/MigrationsUtilTest.java

This fixes CP Jar build failures for 7.8.x

CPSEC-393: Fix CP Jar Build

---

pom.xml

Update netty version from 4.1.108.Final to 4.1.113.Final..

Update netty version from 4.1.108.Final to 4.1.113.Final.

---

ksqldb-engine/src/main/java/io/confluent/ksql/function/UserFunctionLoader.java
pom.xml

Merge Conflict Resolution (from 7.1.x to 7.2.x)

---

pom.xml

Update netty version from 4.1.108.Final to 4.1.113.Final in 7.0.x

Update netty version from 4.1.108.Final to 4.1.113.Final in 7.0.x

---

ksqldb-common/src/main/java/io/confluent/ksql/security/KsqlClientConfig.java

https://confluentinc.atlassian.net/browse/KSQL-12616

KSQL-12616: Change configType to PASSWORD

---

pom.xml

This change is to fix the CVE.

KSE-1849: Update version of commons-io in pom.xml

---

pom.xml

KSE-1849: Update version to fix cve

---

pom.xml

KSE-1849: Fix cve

---

ksqldb-common/src/main/java/io/confluent/ksql/security/oauth/OAuthBearerCredentials.java

kafka updated the args for HttpAccessTokenRetriever.

Fix for Arg Count Mismatch

---

ksqldb-common/src/main/java/io/confluent/ksql/security/oauth/OAuthBearerCredentials.java

Updated the args as per changes in kafka

---

pom.xml

KSQL-12654: Update version to fix cve

---

ksqldb-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/model/ExpectedExceptionNode.java
ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/exceptions/KsqlExpectedException.java
ksqldb-functional-tests/src/test/resources/query-validation-tests/elements.json
ksqldb-functional-tests/src/test/resources/query-validation-tests/sum.json

Remove use of a deprecated api and fix broken tests
Tested locally

Fix 7.9.x build

---

.readthedocs.yml

We are migrating the contents of docs.ksqldb.io to docs.confluent.io and need to create redirects for all moved pages.

Test the redirect functionality (#159)

---

.readthedocs.yml

This reverts commit 113a2e587f4ae8e5246441a4d9541e6b781dcc28.

Revert "Test the redirect functionality (#159)" (#161)

---

docs/overrides/main.html

DOCS-31175 - Add no index tags to all docs pages

---

ksqldb-common/src/main/java/io/confluent/ksql/security/oauth/OAuthBearerCredentials.java

Fix the argument list for HttpAccessTokenRetriever constructor.

Fix the argument list for HttpAccessTokenRetriever.

---

docs/robots.txt

Adding custom robots.txt that tells search engines not to index, [per the instructions](https://docs.readthedocs.io/en/latest/reference/robots.html#how-it-works).

Add blocking robots file to default branch

---

docs/overrides/main.html
mkdocs.yml

DOCS-31175 - Add no index tags to all docs pages (#10497)

---

docs/overrides/main.html

Add no index to docs pages

---

.readthedocs.yml

Add missing build OS config

---

.readthedocs.yml

Remove redundant python declaration

---

mkdocs.yml

Fix mdx_gh_links for docs build

docs: Fix mdx_gh_links config (DOCS-31550)

---

docs/requirements.txt

Update requirements.txt to fix build

docs: fix build in 0.25.1-ksqldb branch

---

docs/requirements.txt

Update requirements.txt to fix the build

docs: fix build in 0.23.1-ksqldb branch (DOCS-31552)

---

.readthedocs.yml

docs: fix python version (DOCS-31549)

---

docs/robots.txt

This reverts commit 6f995aa01be2cffe7d079d84bc1a65073377ecba.

Revert "Add blocking robots file to default branch (#10534)"

---

ksqldb-api-client/pom.xml
ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/RestClientIntegrationTest.java
ksqldb-cli/pom.xml
ksqldb-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
ksqldb-rest-app/pom.xml
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/InsertionIntegrationTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFunctionalTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestAppTest.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/InteractiveStatementExecutorTest.java
ksqldb-tools/pom.xml
pom.xml

Enable all the skipped integration tests.

KSQL-12239 | Remove the skip for integration tests.

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/integration/PauseResumeIntegrationTest.java

Fix the metric lookup name for the intergration test.

MINOR: Fix the metric lookup name for the intergration test.

---

ksqldb-rest-app/pom.xml

Updated the source for json schema dependency
Tested locally

[KSQL-12867] | Vedarth Sharma | Fix jsonschema dependency

---

ksqldb-engine/src/test/java/io/confluent/ksql/function/UdfLoaderTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java

Fix spotbugs errors in the test.

KSQL-12975 | Fix spotbugs errors in the test.

---

PULL_REQUEST_TEMPLATE.md
pom.xml

KSQL-12980 unpinned jetty version

CVE Fix: Unpinned Jetty Version

---

pom.xml

unpin jetty / remove redundant message

---

ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderTest.java
ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/SourceBuilderV1Test.java

Resolve the ambiguity in the instance passed for AutoOffsetReset

Fix the compilation error.

---

pom.xml

Update netty dependency to resolve known security vulnerabilities

[KSQL-13038] update netty

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedAdminClient.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedConsumer.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedProducer.java
ksqldb-engine/src/test/java/io/confluent/ksql/integration/KafkaConsumerGroupClientTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedAdminClientTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedConsumerTest.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedProducerTest.java

[KSQL-13054] Fix the test failures caused by new methods added in kafka clients

---

ksqldb-rest-app/src/main/resources/log4j2.yaml

The log4j2 config file was incorrect for ksqldb rest app package. This pr fixes the config file.
Tested locally

[KSQL-13120] | Vedarth Sharma | Fix log4j2 config

---

ksqldb-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java

[KSQL-13136] Removed JaasUtil's zookeeper dependency for Ksql Build

---

ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedSchemaRegistryClient.java
ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedSchemaRegistryClientTest.java

Implement new SR client method getIdWithResponse

---

config/log4j2-rolling.yaml
config/log4j2.yaml
docker-compose.yml
pom.xml

Remove zookeeper references from the codebase

[KSQL-13333] | Remove zookeeper references

---

ksqldb-rest-app/src/main/java/io/confluent/ksql/api/impl/QueryEndpoint.java

Return a server error for host unavailability errors in pull queries.
This change differentiates between a retriable server error and a client error.

KSQL-13249 | Return a server error for host unavailability errors in pull queries.

---

.semaphore/semaphore.yml

[KSQL-13480] | Fix machine type

---

ksqldb-cli/src/main/java/io/confluent/ksql/Ksql.java
ksqldb-cli/src/test/java/io/confluent/ksql/KsqlTest.java

PR merge 7 9 x to 8 0 x

---

ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/test/java/io/confluent/ksql/util/KsqlConfigTest.java
ksqldb-engine/src/main/java/io/confluent/ksql/services/ServiceContextFactory.java

Add option to use local mode in proxy protocol headers.

KSQL-13699 | Add option to use local mode in proxy protocol headers.

---

ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/integration/ClientIntegrationTest.java

KSQL-13806 | Fix the unit test.

---

config/ksql-production-server.properties
config/ksql-server.properties
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
ksqldb-engine/src/main/java/io/confluent/ksql/security/KsqlResourceExtension.java
ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java

(cherry picked from commit 78ea9e08389b2945f768678028ddca1d1481dc6c)

KSQL-13744 Changes to add License Validation plugin from CSP (#10789)

---

pom.xml

update netty version

---

pom.xml

 Merge branch '7.4.x' into 7.5.x by ayushRanjanCnflt

---

pom.xml

(cherry picked from commit b28a7af2dd032889be97b0f438547863ad1c30bb)

[KSQL-13829] | Unpin jackson version (#10845)

---

ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListPropertiesExecutorTest.java

Added bootstrap servers config to connect test properties 
- [Y] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [Y] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")
- [N] Do these changes have compatibility implications for rollback? If so, ensure that the ksql [command version](https://github.com/confluentinc/ksql/blob/master/ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/Command.java#L41) is bumped.

Added bootstrap servers config to connect test properties
